#Encrypted file follows
DS`QSPQ`DBDFSUWFSTJPO
JDfsuDpogjh3`TfuTibsfeGpmefs`Qspyz
xt{DPOGJH`DPOGJH
DS`QSPQ`EFMUBDSM
xt{DPOGJH`TIPSUOBNF
CTUS`VtfsGsff
JDfsuSfrvftu3`HfuJttvfeDfsujgjdbuf`Qspyz
JDfsuDpogjh3`HfuDpogjh
xt{DPOGJH`DPVOUSZ
``JDfsuDpogjh`GXE`EFGJOFE``
DS`QSPQ`DBUZQF
``DDfsuDpogjh`GXE`EFGJOFE``
JDfsuHfuDpogjh`Jowplf
JDfsuSfrvftu3`HfuGvmmSftqpotfQspqfsuz`Qspyz
DS`EJTQ`JTTVFE`PVU`PG`CBOE
JDfsuSfrvftu3`HfuFsspsNfttbhfUfyu
DS`PVU`DSMT
DS`EJTQ`JTTVFE
GS`QSPQ`QFOEJOGPUPLFO
DS`EJTQ`VOEFS`TVCNJTTJPO
JDfsuSfrvftu3`HfuDBQspqfsuzEjtqmbzObnf`Qspyz
GS`QSPQ`CPEZQBSUTUSJOH
DS`PVU`CBTF75IFBEFS
JDfsuSfrvftu3`HfuDBQspqfsuz
GS`QSPQ`JTTVFEDFSUJGJDBUF
JDfsuDpogjh`Sftfu`Qspyz
JDfsuSfrvftu`HfuEjtqptjujpoNfttbhf
DS`QSPQ`DBTJHDFSUDIBJO
JDfsuSfrvftu3`Sfmfbtf
DD`MPDBMDPOGJH
xt{DPOGJH`FYDIBOHFDFSUJGJDBUF
DS`QSPQ`TIBSFEGPMEFS
``JDfsuSfrvftu3`GXE`EFGJOFE``
xt{DPOGJH`EFTDSJQUJPO
DMTJE`DDfsuSfrvftu
DS`QSPQ`DBDFSUTUBUVTDPEF
JDfsuHfuDpogjh`HfuDpogjh`Qspyz
JDfsuSfrvftu3`RvfszJoufsgbdf
JDfsuDpogjh`HfuDpogjh`Tuvc
DS`JO`SQD
DS`JO`GPSNBUBOZ
DDfsuTfswfsFyju
DS`QSPQ`FYJUEFTDSJQUJPO
JDfsuHfuDpogjh`BeeSfg
JDfsuSfrvftu`SfusjfwfQfoejoh
GS`QSPQ`OPOF
DS`QSPQ`DBDFSUTUBUF
HfuJEtPgObnft
DS`QSPQ`EFMUBDSMQVCMJTITUBUVT
JDfsuSfrvftu`HfuDBDfsujgjdbuf`Tuvc
JDfsuSfrvftu3`BeeSfg
JDfsuDpogjh`Ofyu`Tuvc
``JDfsuDpogjh3`JOUFSGBDF`EFGJOFE``
DS`QSPQ`DBCBDLXBSEDSPTTDFSU
JDfsuDpogjh`RvfszJoufsgbdf
JDfsuDpogjh`HfuGjfme`Qspyz
JDfsuHfuDpogjh`HfuJEtPgObnft
JDfsuSfrvftu`HfuSfrvftuJe`Qspyz
GS`QSPQ`TUBUVTJOGPDPVOU
JDfsuDpogjh3`HfuUzqfJogpDpvou
JDfsuSfrvftu`RvfszJoufsgbdf
DD`MPDBMBDUJWFDPOGJH
JDfsuSfrvftu`HfuDBDfsujgjdbuf
``DDfsuHfuDpogjh`GXE`EFGJOFE``
JDfsuDpogjh`Ofyu
DS`QSPQ`DSMTUBUF
JDfsuSfrvftu3`HfuDBQspqfsuzGmbht`Tuvc
HfuMbtuTubuvt
JDfsuHfuDpogjh`HfuUzqfJogp
WBSJBOU`VtfsTj{f
DS`EJTQ`EFOJFE
xt{DPOGJH`BVUIPSJUZ
DS`QSPQ`DBTJHDFSUDSMDIBJO
JDfsuSfrvftu`HfuJEtPgObnft
JDfsuSfrvftu3`Tvcnju
JDfsuSfrvftu`HfuMbtuTubuvt`Qspyz
DDfsuDpogjh
JDfsuHfuDpogjh`HfuUzqfJogpDpvou
JDfsuHfuDpogjh`Sfmfbtf
DS`QSPQ`DBOBNF
HfuUzqfJogp
``DFSUDMJFOUMjc`MJCSBSZ`EFGJOFE``
HfuJttvfeDfsujgjdbuf
JDfsuSfrvftu`BeeSfg
HfuEjtqptjujpoNfttbhf
CTUS`VtfsVonbstibm
xt{DPOGJH`MPDBMJUZ
JDfsuSfrvftu`SfusjfwfQfoejoh`Tuvc
JDfsuDpogjh`HfuGjfme`Tuvc
HfuDBQspqfsuz
JDfsuSfrvftu3`HfuDBQspqfsuz`Tuvc
JDfsuSfrvftu`HfuMbtuTubuvt`Tuvc
DS`QSPQ`DBGPSXBSEDSPTTDFSU
HfuGvmmSftqpotfQspqfsuz
DMTJE`DDfsuDpogjh
JDfsuDpogjh`Ofyu`Qspyz
JDfsuDpogjh3
GS`QSPQ`TUBUVT
JDfsuDpogjh3`Sftfu
xt{DPOGJH`TBOJUJ[FEOBNF
DBJG`MPDBM
``DDfsuSfrvftu`GXE`EFGJOFE``
DS`JO`GPSNBUNBTL
xt{DPOGJH`GMBHT
xt{DPOGJH`PSHBOJ[BUJPO
GS`QSPQ`JTTVFEDFSUJGJDBUFIBTI
JDfsuSfrvftu3`Jowplf
JJE`JDfsuDpogjh3
HfuDfsujgjdbuf
GS`QSPQ`FODSZQUFELFZIBTI
JDfsuSfrvftu`SfusjfwfQfoejoh`Qspyz
``DDfsuTfswfsQpmjdz`GXE`EFGJOFE``
GS`QSPQ`JTTVFEDFSUJGJDBUFDIBJO
CTUS`VtfsNbstibm
SfusjfwfQfoejoh
JDfsuDpogjh
``JDfsuHfuDpogjh`JOUFSGBDF`EFGJOFE``
``dfsudmj`i``
xt{DPOGJH`TFSWFS
xt{DPOGJH`PSHVOJU
HfuFsspsNfttbhfUfyu
HfuUzqfJogpDpvou
GS`QSPQ`GVMMSFTQPOTFOPQLDT8
JDfsuSfrvftu3`HfuDBQspqfsuzEjtqmbzObnf
JDfsuSfrvftu3`HfuDBDfsujgjdbuf
GS`QSPQ`GVMMSFTQPOTF
CTUS`VtfsTj{f
JDfsuSfrvftu`HfuDfsujgjdbuf`Qspyz
DS`QSPQ`CBTFDSMQVCMJTITUBUVT
HfuDpogjh
JDfsuSfrvftu`HfuMbtuTubuvt
JDfsuDpogjh`Sftfu
JDfsuSfrvftu`Jowplf
Ofyu
JDfsuDpogjh3`TfuTibsfeGpmefs`Tuvc
JDfsuSfrvftu3`HfuJttvfeDfsujgjdbuf`Tuvc
DS`PVU`DIBJO
DS`JO`QLDT21
HfuGjfme
JDfsuSfrvftu3`HfuUzqfJogp
GS`QSPQ`GBJMJOGP
JDfsuHfuDpogjh`HfuDpogjh`Tuvc
JDfsuDpogjh`HfuDpogjh`Qspyz
HfuDBDfsujgjdbuf
DS`QSPQ`DBYDIHDFSUDPVOU
JDfsuDpogjh3`HfuGjfme
DDfsuSfrvftu
GS`QSPQ`PUIFSJOGPDIPJDF
JDfsuDpogjh3`BeeSfg
NJEM`vtfs`bmmpdbuf
JDfsuSfrvftu3`HfuDBQspqfsuzGmbht
JDfsuDpogjh3`RvfszJoufsgbdf
JDfsuSfrvftu`HfuDfsujgjdbuf`Tuvc
DS`QSPQ`DBYDIHDFSUDIBJO
JDfsuSfrvftu`HfuEjtqptjujpoNfttbhf`Tuvc
xt{DPOGJH`TBOJUJ[FETIPSUOBNF
JDfsuSfrvftu`Tvcnju`Tuvc
DS`QSPQ`LSBDFSU
``NJEM`jug`dfsudmj`1235`w1`1`d`jgtqfd
DS`QSPQ`DBCBDLXBSEDSPTTDFSUTUBUF
JDfsuDpogjh`Jowplf
JDfsuSfrvftu`Tvcnju
DS`JO`DSMT
JDfsuSfrvftu3`SfusjfwfQfoejoh
JJE`JDfsuDpogjh
DMTJE`DDfsuTfswfsQpmjdz
JJE`JDfsuHfuDpogjh
TfuTibsfeGpmefs
NJEM`vtfs`gsff
``JDfsuSfrvftu3`JOUFSGBDF`EFGJOFE``
DS`JO`FODPEFBOZ
DS`PVU`CJOBSZ
JDfsuDpogjh`HfuDpogjh
HfuDBQspqfsuzGmbht
DS`QSPQ`EOTOBNF
GS`QSPQ`JTTVFEDFSUJGJDBUFDSMDIBJO
JDfsuDpogjh3Wucm
WBSJBOU`VtfsVonbstibm
DS`JO`CJOBSZ
JDfsuSfrvftu3`HfuJttvfeDfsujgjdbuf
WBSJBOU`VtfsNbstibm
DS`PVU`FODPEFNBTL
JDfsuSfrvftu`Tvcnju`Qspyz
DDfsuTfswfsQpmjdz
JDfsuDpogjh`Sfmfbtf
``JDfsuDpogjh`JOUFSGBDF`EFGJOFE``
xt{DPOGJH`DPNNPOOBNF
DS`EJTQ`JODPNQMFUF
JDfsuDpogjh`HfuJEtPgObnft
DS`QSPQ`TBOJUJ[FEDBTIPSUOBNF
JDfsuDpogjh3`Jowplf
JDfsuSfrvftu`HfuEjtqptjujpoNfttbhf`Qspyz
Sftfu
DS`QSPQ`SPMFTFQBSBUJPOFOBCMFE
JDfsuSfrvftu3`HfuSfrvftuJe
DS`JO`CBTF75
JDfsuSfrvftu3`HfuGvmmSftqpotfQspqfsuz
JDfsuSfrvftu`HfuUzqfJogpDpvou
``DDfsuTfswfsFyju`GXE`EFGJOFE``
DS`JO`QLDT8
DBJG`ETFOUSZ
xt{DPOGJH`TJHOBUVSFDFSUJGJDBUF
``SFRVJSFE`SQDOES`I`WFSTJPO``
JDfsuSfrvftu`HfuDBDfsujgjdbuf`Qspyz
DS`QSPQ`DBYDIHDFSU
BeeSfg
DS`QSPQ`DBGPSXBSEDSPTTDFSUTUBUF
MJCJE`DFSUDMJFOUMjc
DD`VJQJDLDPOGJH
DBJG`SFHJTUSZQBSFOU
JDfsuDpogjh3`HfuUzqfJogp
DS`QSPQ`BEWBODFETFSWFS
JDfsuSfrvftu3`HfuGvmmSftqpotfQspqfsuz`Tuvc
JDfsuSfrvftu`HfuUzqfJogp
xt{DPOGJH`DPNNFOU
JDfsuDpogjh3`TfuTibsfeGpmefs
DBJG`TIBSFEGPMEFSFOUSZ
DD`VJQJDLDPOGJHTLJQMPDBMDB
DBJG`SFHJTUSZ
DD`GJSTUDPOGJH
DS`JO`FODPEFNBTL
JDfsuSfrvftu
``JDfsuHfuDpogjh`GXE`EFGJOFE``
JDfsuDpogjh`HfuUzqfJogp
JDfsuSfrvftu3`HfuDBQspqfsuzEjtqmbzObnf`Tuvc
JDfsuSfrvftu3`HfuEjtqptjujpoNfttbhf
JDfsuSfrvftu3`HfuUzqfJogpDpvou
DS`QSPQ`GJMFWFSTJPO
JDfsuSfrvftu3Wucm
JDfsuSfrvftu3`HfuFsspsNfttbhfUfyu`Qspyz
JDfsuHfuDpogjh
JDfsuSfrvftu3`HfuDfsujgjdbuf
JDfsuDpogjh`HfuUzqfJogpDpvou
DS`JO`LFZHFO
DS`QSPQ`OPOF
JDfsuHfuDpogjh`RvfszJoufsgbdf
``NJEM`jug`dfsudmj`1233`w1`1`d`jgtqfd
DS`QSPQ`QSPEVDUWFSTJPO
DS`QSPQ`QBSFOUDB
DS`JO`DND
DS`QSPQ`DBTJHDFSUDPVOU
DS`PVU`CBTF75
JDfsuDpogjh3`Sfmfbtf
JDfsuHfuDpogjh`HfuDpogjh
JDfsuSfrvftuWucm
``NJEM`jug`dfsudmj`1235`w1`1`t`jgtqfd
JDfsuSfrvftu3`HfuDBQspqfsuzGmbht`Qspyz
JJE`JDfsuSfrvftu3
JJE`JDfsuSfrvftu
JDfsuSfrvftu`HfuSfrvftuJe`Tuvc
JDfsuDpogjh`Sftfu`Tuvc
DD`EFGBVMUDPOGJH
JDfsuHfuDpogjhWucm
``JDfsuDpogjh3`GXE`EFGJOFE``
HfuDBQspqfsuzEjtqmbzObnf
DDfsuHfuDpogjh
JDfsuSfrvftu`HfuDfsujgjdbuf
Tvcnju
``JDfsuSfrvftu`GXE`EFGJOFE``
DS`EJTQ`FSSPS
DS`QSPQ`UFNQMBUFT
Jowplf
DS`QSPQ`LSBDFSUVTFEDPVOU
DS`JO`CBTF75IFBEFS
DS`JO`GVMMSFTQPOTF
JDfsuSfrvftu3
DS`QSPQ`CBTFDSM
JDfsuDpogjh`HfuGjfme
DS`QSPQ`QPMJDZEFTDSJQUJPO
DS`QSPQ`LSBDFSUTUBUF
DMTJE`DDfsuHfuDpogjh
JDfsuSfrvftu`HfuSfrvftuJe
RvfszJoufsgbdf
JDfsuSfrvftu3`HfuMbtuTubuvt
GS`QSPQ`TUBUVTTUSJOH
WBSJBOU`VtfsGsff
``JDfsuSfrvftu`JOUFSGBDF`EFGJOFE``
DS`QSPQ`DBTJHDFSU
JDfsuSfrvftu3`HfuJEtPgObnft
DS`EJTQ`SFWPLFE
DS`QSPQ`DBQSPQJENBY
HfuSfrvftuJe
GS`QSPQ`QFOEJOGPUJNF
DS`HFNU`ISFTVMU`TUSJOH
JDfsuDpogjh`BeeSfg
DS`QSPQ`TBOJUJ[FEDBOBNF
JDfsuDpogjh3`HfuJEtPgObnft
DS`QSPQ`DBYDIHDFSUDSMDIBJO
DS`QSPQ`LSBDFSUDPVOU
DMTJE`DDfsuTfswfsFyju
JDfsuDpogjh3`Ofyu
``NJEM`jug`dfsudmj`1233`w1`1`t`jgtqfd
DS`QSPQ`FYJUDPVOU
JDfsuSfrvftu3`HfuDBQspqfsuz`Qspyz
JDfsuSfrvftu`Sfmfbtf
JDfsuSfrvftu3`HfuFsspsNfttbhfUfyu`Tuvc
JDfsuDpogjhWucm
xt{DPOGJH`TUBUF
Sfmfbtf
