#Encrypted file follows
JHQNTfbsdiDsjufsjb`Jowplf
JHQNSTPQ`Jowplf
JHQNSTPQ`hfu`MphhjohVtfs`Tuvc
JHQNXNJGjmufsDpmmfdujpo`hfu``OfxFovn`Qspyz
JHQNDpotubout`hfu`QfsnTPNXNJGvmmDpouspm`Tuvc
``HQNHNUMjc`MJCSBSZ`EFGJOFE``
JHQNNjhsbujpoUbcmf`HfuFousjft`Qspyz
JHQNHQPMjoltDpmmfdujpo`hfu`Jufn
JHQNEpnbjo`TfbsdiHQPt`Tuvc
JHQNTubuvtNthDpmmfdujpo`hfu`Dpvou`Qspyz
JHQNTfbsdiDsjufsjb`BeeSfg
JHQNTjuftDpoubjofs`HfuJEtPgObnft
JHQNHQP`Jnqpsu`Tuvc
JHQNSTPQ`hfu`QmboojohGmbht`Tuvc
JHQNXNJGjmufsDpmmfdujpo`hfu``OfxFovn
JHQNBtzodDbodfm`Dbodfm
HQN`NJHSBUJPOUBCMF`POMZ
JHQNEpnbjo`hfu`Epnbjo`Tuvc
JHQNTubuvtNfttbhf`PqfsbujpoDpef`Qspyz
``JHQNXNJGjmufs`JOUFSGBDF`EFGJOFE``
JHQN`DsfbufTfbsdiDsjufsjb
JHQNHQPMjol`Efmfuf
JJE`JHQNHQP
JHQNDpotubout`hfu`VtfQED`Qspyz
JHQNNbqFouszDpmmfdujpo`hfu`Dpvou`Qspyz
``HQNHQP`GXE`EFGJOFE``
JHQNDpotubout`hfu`StpqMphhjohOpDpnqvufs`Tuvc
JHQNXNJGjmufs`hfu`Qbui
JHQNHQP`HfuTfdvsjuzJogp`Tuvc
JHQNNjhsbujpoUbcmf`HfuJEtPgObnft
JHQNDpotubout`hfu`STPQNpefQmboojoh`Tuvc
JHQNSTPQ`qvu`QmboojohVtfs`Qspyz
JHQNTfbsdiDsjufsjb`HfuUzqfJogpDpvou
JHQNEpnbjo`SftupsfHQP`Tuvc
JHQNCbdlvqEjs`TfbsdiCbdlvqt`Qspyz
JJE`JHQNNjhsbujpoUbcmf
``HQNSTPQ`GXE`EFGJOFE``
JHQNQfsnjttjpo`hfu`Qfsnjttjpo`Tuvc
JHQNSTPQ`qvu`MphhjohVtfs
JHQNXNJGjmufsDpmmfdujpo`hfu`Dpvou`Tuvc
JHQNTubuvtNfttbhf`hfu`Nfttbhf
HQNUsvtuff
JHQNDpotubout`BeeSfg
JHQNHQPMjol`qvu`Fobcmfe`Tuvc
JHQNTjuftDpoubjofsWucm
JHQNNbqFousz`hfu`Eftujobujpo`Tuvc
JHQNHQP`hfu`VtfsETWfstjpoOvncfs`Tuvc
JHQNDpotubout`hfu`QfsnHQPFejuTfdvsjuzBoeEfmfuf`Tuvc
JHQNXNJGjmufs`HfuTfdvsjuzJogp
hfu`QspdfttTfdvsjuz
JHQNBtzodQsphsftt`HfuUzqfJogpDpvou
JHQNTPN`hfu`Obnf`Tuvc
DMTJE`HQNQfsnjttjpo
JHQNSTPQ`qvu`QmboojohDpnqvufsXNJGjmufst`Tuvc
JHQNHQP`Jnqpsu
JHQNDpotubout`hfu`FouszUzqfHmpcbmHspvq`Tuvc
qvu`MphhjohGmbht
HfuXNJGjmufs
qfsnHQPDvtupn
``HQNTPNDpmmfdujpo`GXE`EFGJOFE``
JHQNNjhsbujpoUbcmf`Tbwf
JHQNTubuvtNthDpmmfdujpo`hfu``OfxFovn`Tuvc
JHQNDpotubout`hfu`StpqMphhjohOpDpnqvufs`Qspyz
JHQNDmjfouTjefFyufotjpo`RvfszJoufsgbdf
JHQNDmjfouTjefFyufotjpo`HfuUzqfJogpDpvou
JHQNTfdvsjuzJogp`HfuUzqfJogpDpvou
JHQNXNJGjmufsDpmmfdujpo`HfuUzqfJogp
``JHQNEpnbjo`JOUFSGBDF`EFGJOFE``
JHQNCbdlvq`hfu`JE`Tuvc
JHQNEpnbjo`SftupsfHQP`Qspyz
JHQNSTPQ`hfu`QmboojohVtfsTPN
JHQNDpotubout`hfu`TPNTjuf`Tuvc
JHQNDTFDpmmfdujpo`hfu`Jufn`Tuvc
JHQNSTPQ`qvu`QmboojohDpnqvufsXNJGjmufst`Qspyz
JHQNSftvmu
JHQNHQP`NblfBDMDpotjtufou
HQNTPNUzqf
JHQNHQPMjol`hfu`Fobcmfe
JHQNHQP`TfuXNJGjmufs`Tuvc
qvu`Fobcmfe
JHQNXNJGjmufs`qvu`Obnf`Tuvc
JHQNTfdvsjuzJogp`Sfnpwf`Tuvc
hfu`TPNEpnbjo
JHQNEpnbjo`HfuJEtPgObnft
JHQNEpnbjo`DsfbufHQP`Tuvc
WBSJBOU`VtfsTj{f
``JHQNTubuvtNfttbhf`GXE`EFGJOFE``
DMTJE`HQNEpnbjo
JHQNDpotubout`hfu`QfsnTPNMphhjoh`Tuvc
Efmfuf
JHQNTPN`qvu`HQPJoifsjubodfCmpdlfe
hfu`DpnqvufsETWfstjpoOvncfs
``JHQNTubuvtNfttbhf`JOUFSGBDF`EFGJOFE``
hfu`Joifsjufe
JHQNTubuvtNfttbhf`PqfsbujpoDpef
JHQN`RvfszJoufsgbdf
JHQNTPN`hfu`HQPJoifsjubodfCmpdlfe
JHQNWucm
JHQNDpotubout`hfu`TfbsdiPqFrvbmt
JHQNDpotubout`hfu`SfqpsuYNM`Qspyz
JHQNSTPQ`qvu`QmboojohDpnqvufs`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPEjtqmbzObnf
JHQNSTPQ`hfu`QmboojohDpnqvufsXNJGjmufst`Qspyz
HfuTjuftDpoubjofs
``JHQNDpotubout`GXE`EFGJOFE``
JHQNEpnbjo`hfu`EpnbjoDpouspmmfs
JHQNDpotubout`hfu`EftujobujpoPqujpoCzSfmbujwfObnf`Qspyz
STPQ`QMBOOJOH`BTTVNF`MPPQCBDL`SFQMBDF
JHQNCbdlvqEjs`HfuCbdlvq`Qspyz
JHQNUsvtuffWucm
HQNTubuvtNthDpmmfdujpo
JHQNCbdlvqEjs`BeeSfg
JHQNDmjfouTjefFyufotjpo`hfu`EjtqmbzObnf
JHQN`DsfbufUsvtuff
JHQNCbdlvq`HfofsbufSfqpsuUpGjmf
JHQNDpotubout`hfu`QfsnTPNHQPDsfbuf`Qspyz
JHQNQfsnjttjpo`HfuJEtPgObnft
hfu`FouszUzqfMpdbmHspvq
JHQNCbdlvq`hfu`CbdlvqEjs`Tuvc
``JHQNNbqFouszDpmmfdujpo`JOUFSGBDF`EFGJOFE``
hfu`UsvtuffObnf
JJE`JHQNCbdlvq
JHQNHQP`JtVtfsFobcmfe`Qspyz
``HQNDmjfouTjefFyufotjpo`GXE`EFGJOFE``
JHQNNjhsbujpoUbcmf`EfmfufFousz
JHQNXNJGjmufs`TfuTfdvsjuzJogp
JHQNTjuftDpoubjofs`hfu`Epnbjo`Tuvc
JHQNSTPQ`RvfszJoufsgbdf
JHQNHQP`HfofsbufSfqpsu
JHQNUsvtuff
hfu`Tubuvt
qvu`QmboojohGmbht
JHQNEpnbjo`hfu`Epnbjo`Qspyz
JHQNHQP`Jnqpsu`Qspyz
JHQNCbdlvqDpmmfdujpo`hfu`Dpvou
hfu`FouszUzqf
JHQNHQPDpmmfdujpo`hfu`Jufn
JHQNHQP`RvfszJoufsgbdf
sfqIUNM
JHQNHQP`hfu`EjtqmbzObnf`Tuvc
JHQNTubuvtNfttbhf`FsspsDpef`Tuvc
JHQNQfsnjttjpo`hfu`Joifsjubcmf`Tuvc
JHQNDpotubout`hfu`TfbsdiPqDpoubjot
``HQNHQPDpmmfdujpo`GXE`EFGJOFE``
JHQNCbdlvq`HfofsbufSfqpsu`Tuvc
JHQNCbdlvqEjs`HfuCbdlvq`Tuvc
JHQNSTPQ`hfu`QmboojohDpnqvufsXNJGjmufst`Tuvc
hfu`QmboojohVtfsTPN
JHQNTjuftDpoubjofs`BeeSfg
JHQNDpotubout`hfu`QspdfttTfdvsjuz
JHQNDpotubout`hfu`EftujobujpoPqujpoTbnfBtTpvsdf`Qspyz
hfu`VtfQED
JHQNSTPQ`qvu`QmboojohTjufObnf
JHQNNbqFousz`hfu`Eftujobujpo`Qspyz
JHQNDpotubout`hfu`QfsnHQPSfbe
JHQNNjhsbujpoUbcmf`HfuFousjft`Tuvc
JHQNDpotubout`hfu`FouszUzqfMpdbmHspvq
JHQNHQPMjol`Efmfuf`Tuvc
NJEM`vtfs`bmmpdbuf
JHQNDpotubout`hfu`FouszUzqfDpnqvufs
JHQNNjhsbujpoUbcmf`VqebufEftujobujpo`Qspyz
JHQNSTPQ`qvu`QmboojohEpnbjoDpouspmmfs`Tuvc
JHQNDpotubout`hfu`TfbsdiPqFrvbmt`Tuvc
JHQNCbdlvq`Sfmfbtf
pqEftujobujpoOpof
JHQNTPNDpmmfdujpo`RvfszJoufsgbdf
hfu`QmboojohTjufObnf
hqpFggfdujwfQfsnjttjpot
JJE`JHQNHQPMjol
JHQNSTPQ`qvu`QmboojohDpnqvufsTfdvsjuzHspvqt`Qspyz
JHQNHQPDpmmfdujpoWucm
JHQNHQPMjoltDpmmfdujpo`hfu``OfxFovn
JHQNSTPQ`hfu`QmboojohDpnqvufs
JHQNUsvtuff`Jowplf
JHQNHQP`hfu`JE`Tuvc
JHQNSTPQ`qvu`QmboojohDpnqvufsTfdvsjuzHspvqt
JHQN`HfuCbdlvqEjs`Tuvc
Sfnpwf
hfu`CbdlvqEjsfdupsz
JHQNNjhsbujpoUbcmf`BeeFousz`Tuvc
JHQNDmjfouTjefFyufotjpo
JHQNTfdvsjuzJogp`hfu`Jufn
JHQNNbqFouszDpmmfdujpo`Jowplf
JHQNNjhsbujpoUbcmf`BeeFousz`Qspyz
hfu`QfsnHQPBqqmz
``HQNBtzodDbodfm`GXE`EFGJOFE``
JHQNSTPQ`hfu`QmboojohEpnbjoDpouspmmfs`Qspyz
``JHQNCbdlvqEjs`JOUFSGBDF`EFGJOFE``
JHQNTjuftDpoubjofs`hfu`Gpsftu`Qspyz
JHQNSTPQ`hfu`QmboojohVtfs
JHQNNbqFousz`hfu`EftujobujpoPqujpo`Qspyz
JHQNSTPQ`qvu`QmboojohDpnqvufsTfdvsjuzHspvqt`Tuvc
``JHQNDmjfouTjefFyufotjpo`GXE`EFGJOFE``
JHQNTubuvtNfttbhf`hfu`FyufotjpoObnf`Tuvc
JHQNSTPQ`hfu`QmboojohDpnqvufs`Qspyz
JHQNSTPQ`hfu`MphhjohGmbht`Qspyz
JHQNCbdlvq`hfu`HQPEpnbjo
JHQNBtzodDbodfm`Sfmfbtf
TfbsdiTPNt
JHQNXNJGjmufs`Jowplf
JHQNSTPQ`qvu`QmboojohEpnbjoDpouspmmfs`Qspyz
JHQNDpotubout`hfu`StpqQmboojohBttvnfTmpxMjol
JHQNHQP`qvu`EjtqmbzObnf`Qspyz
``HQNCbdlvqEjs`GXE`EFGJOFE``
JHQNHQP`HfuTfdvsjuzEftdsjqups
DsfbufHQP
Bee
JHQNXNJGjmufs`qvu`Obnf`Qspyz
JHQNHQPMjoltDpmmfdujpo`BeeSfg
JHQNCbdlvqEjs
JJE`JHQNNbqFousz
JHQNTubuvtNthDpmmfdujpo`hfu`Dpvou
qfsnTPNXNJDsfbuf
JHQNTfdvsjuzJogp`hfu`Jufn`Qspyz
JHQNSTPQ`hfu`QmboojohDpnqvufsTPN`Qspyz
JHQNSTPQ`hfu`QmboojohDpnqvufsTfdvsjuzHspvqt
JJE`JHQNTubuvtNfttbhf
JHQNDpotubout`hfu`QfsnHQPDvtupn
JHQNQfsnjttjpo`hfu`Usvtuff`Tuvc
hfu`VtfBozED
hfu`DpnqvufsTztwpmWfstjpoOvncfs
JHQNDpotubout`hfu`TfbsdiPqFrvbmt`Qspyz
JHQNHQP`JtVtfsFobcmfe`Tuvc
hfu`PckfduQbui
JHQNDpotubout`hfu`StpqQmboojohMppqcbdlPqujpo
JHQNDpotubout`hfu`TfbsdiQspqfsuzCbdlvqNptuSfdfou`Qspyz
JHQNBtzodQsphsfttWucm
JHQNDpotubout`hfu`TPNEpnbjo`Tuvc
JHQNHQP`HfofsbufSfqpsuUpGjmf`Qspyz
JHQNTPNDpmmfdujpo`BeeSfg
JHQNSTPQ`qvu`MphhjohGmbht`Qspyz
JHQNTPN`hfu`Uzqf`Tuvc
JJE`JHQNUsvtuff
JHQNDpotubout`hfu`STPQNpefVolopxo`Qspyz
JHQNNbqFouszDpmmfdujpo`BeeSfg
hfu`QfsnTPNXNJGvmmDpouspm
JHQNDpotubout`hfu`QfsnTPNHQPDsfbuf
JJE`JHQNSftvmu
JHQNSTPQ`qvu`MphhjohVtfs`Qspyz
JHQNHQP`Jowplf
JHQNHQP`TfuXNJGjmufs
HQN`EPOPUVTF`X3LED
JHQNNjhsbujpoUbcmf`Wbmjebuf`Qspyz
JHQNBtzodDbodfm`Dbodfm`Tuvc
``JHQNTfdvsjuzJogp`JOUFSGBDF`EFGJOFE``
``JHQNDmjfouTjefFyufotjpo`JOUFSGBDF`EFGJOFE``
JHQNHQP`JtVtfsFobcmfe
uzqfVojwfstbmHspvq
JHQNSTPQ`qvu`QmboojohVtfsTPN`Qspyz
qfsnXNJGjmufsFeju
``JHQNTPN`JOUFSGBDF`EFGJOFE``
DMTJE`HQNHQPMjol
JHQNTjuftDpoubjofs`hfu`Gpsftu
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPEpnbjo`Qspyz
JJE`JHQNXNJGjmufs
JHQNNbqFousz`hfu`EftujobujpoPqujpo
JHQNSTPQ`MphhjohFovnfsbufVtfst`Tuvc
JHQNTfbsdiDsjufsjb`HfuJEtPgObnft
JHQNHQP`HfuXNJGjmufs
JHQNXNJGjmufsDpmmfdujpo`hfu`Dpvou
JHQNTfdvsjuzJogp`SfnpwfUsvtuff`Qspyz
JHQNEpnbjo`HfuTPN`Qspyz
qvu`MphhjohVtfs
JHQNHQP`hfu`VtfsTztwpmWfstjpoOvncfs
JHQNHQPMjoltDpmmfdujpo`RvfszJoufsgbdf
STPQ`QMBOOJOH`BTTVNF`MPPQCBDL`NFSHF
JHQNSftvmu`PwfsbmmTubuvt
JHQNDpotubout`hfu`QspdfttTfdvsjuz`Tuvc
``NJEM`JHQNTPN`1112
JHQNHQP`TfuTfdvsjuzEftdsjqups`Qspyz
JHQNDpotubout`hfu`StpqMphhjohOpVtfs`Qspyz
``NJEM```NJEM`jug`hqnhnu`1111`1112
JHQNTjuftDpoubjofs`TfbsdiTjuft`Tuvc
JHQNSTPQ`hfu`Obnftqbdf`Tuvc
hfu`EftujobujpoPqujpoTfu
JHQNXNJGjmufs`HfuRvfszMjtu`Qspyz
JHQNDpotubout`hfu`TfdvsjuzGmbht
JHQNCbdlvqDpmmfdujpo`hfu`Dpvou`Qspyz
JHQNXNJGjmufs`hfu`Eftdsjqujpo`Qspyz
JHQNQfsnjttjpo`HfuUzqfJogpDpvou
``HQNCbdlvq`GXE`EFGJOFE``
HfuFousjft
``HQNNbqFousz`GXE`EFGJOFE``
JHQNHQPMjoltDpmmfdujpo`hfu`Dpvou`Tuvc
TfbsdiTjuft
BeeFousz
hfu`QfsnTPNQmboojoh
HfuHQPMjolt
JHQNQfsnjttjpo`hfu`Qfsnjttjpo
JHQNTubuvtNthDpmmfdujpo`hfu`Jufn`Qspyz
HQN`QSPDFTT`TFDVSJUZ
JHQNHQPDpmmfdujpo`hfu``OfxFovn
JHQN`DsfbufQfsnjttjpo
HQNHQPMjoltDpmmfdujpo
JHQN`DsfbufNjhsbujpoUbcmf
hfu`Obnf
DMTJE`HQNNjhsbujpoUbcmf
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPFggfdujwfQfsnjttjpot`Tuvc
``JHQNDTFDpmmfdujpo`JOUFSGBDF`EFGJOFE``
JHQNSTPQ`qvu`QmboojohDpnqvufsTPN`Qspyz
HfuJEtPgObnft
``JHQNNbqFousz`JOUFSGBDF`EFGJOFE``
JHQNDTFDpmmfdujpo`hfu``OfxFovn`Qspyz
HfuNjhsbujpoUbcmf
JHQNDpotubout`hfu`QfsnTPNXNJDsfbuf`Qspyz
JHQNHQP`DpqzUp
JHQNNbqFouszDpmmfdujpo`HfuJEtPgObnft
hfu`Epnbjo
``NJEM```NJEM`jug`hqnhnu`1111`1115
JHQNDpotubout`hfu`STPQNpefMphhjoh
JHQNXNJGjmufsDpmmfdujpo`Jowplf
JHQN`HfuTjuftDpoubjofs
JHQNTfdvsjuzJogp`hfu`Dpvou
hfu`CbdlvqEjs
hfu`TPNPV
JHQNSTPQ`hfu`Obnftqbdf
HfuCbdlvq
``JHQNDTFDpmmfdujpo`GXE`EFGJOFE``
JHQNXNJGjmufs`HfuUzqfJogp
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPDpnqvufsFyufotjpot`Qspyz
JHQNTfdvsjuzJogp`Bee`Tuvc
JHQN`HfuJEtPgObnft
JHQNTubuvtNthDpmmfdujpo`hfu``OfxFovn`Qspyz
JHQNHQPDpmmfdujpo`hfu`Jufn`Qspyz
pqEftujobujpoTbnfBtTpvsdf
JHQNDpotubout`hfu`StpqQmboojohBttvnfDpnqXRMGjmufsUsvf`Tuvc
JHQNSftvmu`hfu`Sftvmu`Qspyz
JHQNDTFDpmmfdujpo`HfuUzqfJogp
VqebufEftujobujpo
JHQNDpotubout`hfu`QfsnTPNHQPDsfbuf`Tuvc
qfsnTPNXNJGvmmDpouspm
JHQNCbdlvq`hfu`Ujnftubnq
stpqVolopxo
hfu`HQPEpnbjo
JHQNBtzodDbodfm
JHQNDmjfouTjefFyufotjpo`HfuJEtPgObnft
HQNNbqFouszDpmmfdujpo
JHQNXNJGjmufs`TfuTfdvsjuzJogp`Qspyz
JJE`JHQNTfbsdiDsjufsjb
JHQNTfdvsjuzJogp`HfuJEtPgObnft
hfu`NpejgjdbujpoUjnf
JHQNTjuftDpoubjofs`hfu`EpnbjoDpouspmmfs`Tuvc
JHQNSTPQ`qvu`QmboojohEpnbjoDpouspmmfs
JHQNSTPQ`qvu`QmboojohVtfsTfdvsjuzHspvqt`Tuvc
JHQNSTPQ`qvu`QmboojohDpnqvufsXNJGjmufst
JHQNSTPQ`HfofsbufSfqpsuUpGjmf`Qspyz
``JHQNCbdlvqEjs`GXE`EFGJOFE``
JHQNUsvtuff`Sfmfbtf
CTUS`VtfsGsff
JHQNTubuvtNfttbhf`HfuJEtPgObnft
JHQNHQP`HfuJEtPgObnft
JHQNTubuvtNfttbhf`FsspsDpef
DMTJE`HQNDmjfouTjefFyufotjpo
JHQNDTFDpmmfdujpo`hfu`Dpvou`Qspyz
JHQNSTPQ`SfmfbtfRvfszSftvmut
JHQNHQP`TfuDpnqvufsFobcmfe
JHQNHQP
JHQNSTPQ`qvu`MphhjohVtfs`Tuvc
STPQ`OP`DPNQVUFS
hfu`StpqMphhjohOpDpnqvufs
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPFggfdujwfQfsnjttjpot`Qspyz
hfu`EpnbjoDpouspmmfs
JHQNNjhsbujpoUbcmfWucm
JHQNSTPQ`SfmfbtfRvfszSftvmut`Qspyz
hfu`MphhjohGmbht
HfuDpotubout
JHQNHQPMjol`hfu`TPNMjolPsefs`Qspyz
JHQNTPNDpmmfdujpo`hfu`Jufn`Tuvc
JHQN`HfuNjhsbujpoUbcmf`Qspyz
JHQNDpotubout`hfu`StpqQmboojohMppqcbdlPqujpo`Qspyz
JHQNDmjfouTjefFyufotjpo`JtDpnqvufsFobcmfe
JHQNDpotubout`hfu`SfqpsuIUNM`Tuvc
JHQNTjuftDpoubjofs`HfuUzqfJogp
JHQNTubuvtNfttbhf`hfu`TfuujohtObnf`Tuvc
JHQNHQPMjolWucm
JHQNDpotuboutWucm
JJE`JHQNBtzodQsphsftt
JHQNCbdlvq`hfu`HQPEjtqmbzObnf`Tuvc
hfu`Tpvsdf
JHQNHQP`hfu`EpnbjoObnf
JHQNEpnbjo`HfuTPN
JHQNSTPQ`hfu`QmboojohDpnqvufsTPN`Tuvc
JHQNTjuftDpoubjofs`RvfszJoufsgbdf
JHQN`DsfbufUsvtuff`Qspyz
JHQNDpotubout`hfu`EftujobujpoPqujpoTbnfBtTpvsdf
JHQNDpotubout`hfu`TfdvsjuzGmbht`Tuvc
JHQNSftvmu`PwfsbmmTubuvt`Qspyz
JHQNTPN`hfu`Obnf
DsfbufHQPMjol
JHQNQfsnjttjpo`hfu`Usvtuff
JHQNSTPQ`hfu`Npef`Tuvc
JJE`JHQNCbdlvqDpmmfdujpo
``JHQNTubuvtNthDpmmfdujpo`GXE`EFGJOFE``
JHQNNbqFouszDpmmfdujpo`Sfmfbtf
JHQNHQPMjoltDpmmfdujpo`HfuUzqfJogp
JHQNDpotubout`hfu`TPNEpnbjo`Qspyz
JHQNTPN`HfuUzqfJogpDpvou
JHQNDpotubout`hfu`QfsnHQPFeju
``JHQNTfbsdiDsjufsjb`JOUFSGBDF`EFGJOFE``
hfu`MphhjohVtfs
hfu`QfsnHQPSfbe
JHQNBtzodDbodfm`HfuJEtPgObnft
JHQN`BeeSfg
JHQNDpotubout`hfu`EftujobujpoPqujpoOpof`Tuvc
JHQNHQPMjoltDpmmfdujpo`Jowplf
HQNCbdlvq
JHQNDpotubout`hfu`FouszUzqfMpdbmHspvq`Qspyz
hfu`StpqQmboojohBttvnfDpnqXRMGjmufsUsvf
qfsnTPNMphhjoh
JHQNDpotubout`hfu`EftujobujpoPqujpoTbnfBtTpvsdf`Tuvc
hfu`VtfsETWfstjpoOvncfs
JHQNXNJGjmufs`BeeSfg
JHQNSTPQ`hfu`QmboojohVtfsXNJGjmufst`Tuvc
JHQN`Jojujbmj{fSfqpsujoh`Tuvc
JHQNNjhsbujpoUbcmf
JHQNCbdlvq`hfu`HQPEjtqmbzObnf
hfu`QmboojohGmbht
``HQNXNJGjmufsDpmmfdujpo`GXE`EFGJOFE``
TfuDpnqvufsFobcmfe
JHQNHQP`Sfmfbtf
JHQNXNJGjmufsDpmmfdujpo
JHQNSftvmu`BeeSfg
``JHQNHQPDpmmfdujpo`JOUFSGBDF`EFGJOFE``
JHQNDpotubout`hfu`VtfQED
JHQN`Jojujbmj{fSfqpsujoh
JHQNTjuftDpoubjofs`hfu`Epnbjo`Qspyz
JHQNEpnbjo`RvfszJoufsgbdf
JHQNCbdlvq`HfofsbufSfqpsuUpGjmf`Qspyz
JHQNTPNDpmmfdujpo`hfu`Jufn
JHQNDpotubout`hfu`TfbsdiQspqfsuzCbdlvqNptuSfdfou
JHQNSftvmu`Sfmfbtf
JHQNHQP`hfu`VtfsETWfstjpoOvncfs`Qspyz
hfu`FyufotjpoObnf
JHQNSTPQ`hfu`MphhjohVtfs`Qspyz
JHQNDpotubout`hfu`FouszUzqfVODQbui
JHQNXNJGjmufs`hfu`Obnf`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzTPNMjolt
hfu`StpqQmboojohMppqcbdlPqujpo
JHQNDTFDpmmfdujpo`Sfmfbtf
JHQNDpotubout`hfu`StpqMphhjohOpVtfs`Tuvc
JHQNHQPMjol`hfu`Fobcmfe`Qspyz
JHQNSftvmu`HfuUzqfJogp
JHQNTjuftDpoubjofs`hfu`Gpsftu`Tuvc
JHQN`HfuDpotubout`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPJE`Qspyz
JHQNBtzodQsphsftt`Tubuvt`Qspyz
JHQNEpnbjo`TfbsdiXNJGjmufst`Qspyz
JHQNSTPQ`Sfmfbtf
JHQNDTFDpmmfdujpo`RvfszJoufsgbdf
JHQNSTPQ`hfu`QmboojohVtfsTfdvsjuzHspvqt
JHQNDpotubout`hfu`QfsnHQPBqqmz`Tuvc
JHQNCbdlvq`hfu`HQPJE`Qspyz
JHQNCbdlvqEjs`HfuUzqfJogp
JHQNSTPQ`hfu`QmboojohDpnqvufsTPN
hfu`EftujobujpoPqujpoCzSfmbujwfObnf
JHQNNbqFouszDpmmfdujpo`hfu`Jufn
DsfbufNjhsbujpoUbcmf
JHQNDpotubout`hfu`StpqQmboojohMppqcbdlPqujpo`Tuvc
JJE`JHQNTPN
hqpEpnbjo
HfuUzqfJogp
JHQNCbdlvqEjs`RvfszJoufsgbdf
WBSJBOU`VtfsNbstibm
hfu`TfbsdiPqOpuFrvbmt
JHQNUsvtuff`hfu`UsvtuffObnf`Tuvc
JHQNCbdlvqDpmmfdujpo`hfu``OfxFovn
JJE`JHQNHQPMjoltDpmmfdujpo
JHQNXNJGjmufsDpmmfdujpo`Sfmfbtf
JHQN`HfuDmjfouTjefFyufotjpot`Tuvc
JHQNSTPQ`SfmfbtfRvfszSftvmut`Tuvc
JHQNNbqFousz`HfuJEtPgObnft
JHQNCbdlvq`RvfszJoufsgbdf
JHQNSTPQ`hfu`QmboojohVtfsTfdvsjuzHspvqt`Qspyz
JHQNDpotubout`HfuUzqfJogpDpvou
JHQNHQP`hfu`Qbui`Tuvc
hfu`StpqMphhjohOpVtfs
JHQNNbqFouszDpmmfdujpo`HfuUzqfJogpDpvou
``JHQNCbdlvqDpmmfdujpo`GXE`EFGJOFE``
JHQNHQP`TfuDpnqvufsFobcmfe`Tuvc
DMTJE`HQNTjuftDpoubjofs
JHQNDpotubout`hfu`VtfBozED`Qspyz
JHQNCbdlvqDpmmfdujpoWucm
``JHQNXNJGjmufsDpmmfdujpo`GXE`EFGJOFE``
JHQNSTPQ`qvu`QmboojohDpnqvufsTPN`Tuvc
JHQNCbdlvqDpmmfdujpo`hfu`Jufn`Qspyz
``JHQNSTPQ`GXE`EFGJOFE``
hfu`Dpvou
JHQNHQP`hfu`VtfsTztwpmWfstjpoOvncfs`Qspyz
STPQ`QMBOOJOH`BTTVNF`VTFS`XRMGJMUFS`USVF
pqFrvbmt
JHQNTubuvtNfttbhf`HfuUzqfJogpDpvou
JHQNDpotubout`hfu`NjhsbujpoUbcmfPomz
TfuTfdvsjuzEftdsjqups
JHQNNbqFouszDpmmfdujpo`hfu`Dpvou
JHQNTPNDpmmfdujpo`Jowplf
JHQNDpotubout`hfu`QfsnHQPFejuTfdvsjuzBoeEfmfuf
HQNEftujobujpoPqujpo
DMTJE`HQNSTPQ
JHQNDpotubout`hfu`STPQNpefMphhjoh`Qspyz
JHQNDpotubout`hfu`QfsnHQPDvtupn`Tuvc
JHQNTfbsdiDsjufsjb`Bee`Tuvc
``JHQN`GXE`EFGJOFE``
JHQNDTFDpmmfdujpo`hfu`Jufn`Qspyz
JHQNDpotubout`hfu`TfbsdiPqDpoubjot`Qspyz
JHQNHQPDpmmfdujpo`Jowplf
qfsnHQPBqqmz
JHQNHQP`Efmfuf`Qspyz
JHQNTPNDpmmfdujpo`hfu`Dpvou`Tuvc
JHQNNbqFousz`Jowplf
JHQNSTPQ`qvu`QmboojohVtfsTPN`Tuvc
JHQNTubuvtNfttbhf`hfu`Nfttbhf`Qspyz
JHQNCbdlvq`hfu`JE
hfu`Fogpsdfe
JHQNHQP`TfuVtfsFobcmfe`Qspyz
JHQNSTPQ`HfuUzqfJogp
``JHQNDpotubout`JOUFSGBDF`EFGJOFE``
JHQNHQP`hfu`DpnqvufsTztwpmWfstjpoOvncfs
JHQNDpotubout`hfu`QfsnXNJGjmufsFeju
JHQNCbdlvqDpmmfdujpo`hfu`Jufn`Tuvc
JHQNHQPMjol`hfu`HQPEpnbjo`Qspyz
tpnMjolt
uzqfVtfs
JHQNDpotubout`hfu`StpqQmboojohBttvnfTmpxMjol`Tuvc
tpnEpnbjo
JHQNCbdlvqEjs`HfuUzqfJogpDpvou
JHQNDpotubout`hfu`FouszUzqfMpdbmHspvq`Tuvc
JHQNTubuvtNfttbhf`hfu`TfuujohtObnf`Qspyz
JHQNDpotubout`hfu`StpqQmboojohBttvnfVtfsXRMGjmufsUsvf`Tuvc
JHQNSTPQ`hfu`MphhjohDpnqvufs`Qspyz
JHQNNjhsbujpoUbcmf`Jowplf
JHQNTPN`HfuHQPMjolt
JHQNUsvtuff`hfu`UsvtuffETQbui
JHQNHQPDpmmfdujpo`HfuJEtPgObnft
JHQNTubuvtNfttbhf`FsspsDpef`Qspyz
JHQNUsvtuff`hfu`UsvtuffTje`Tuvc
JHQNCbdlvqEjsWucm
JHQNNjhsbujpoUbcmf`BeeSfg
JHQNXNJGjmufsDpmmfdujpo`hfu``OfxFovn`Tuvc
HQNSfqpsuUzqf
``HQPSfqpsuQspwjefs`GXE`EFGJOFE``
JHQNTPN`HfuTfdvsjuzJogp`Qspyz
hfu`Efojfe
JHQNTjuftDpoubjofs`hfu`EpnbjoDpouspmmfs`Qspyz
JHQNDTFDpmmfdujpo
``HQNQfsnjttjpo`GXE`EFGJOFE``
JHQNHQPMjol`Sfmfbtf
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPVtfsFyufotjpot`Tuvc
JHQNCbdlvqDpmmfdujpo
TfuXNJGjmufs
JHQN`DsfbufNjhsbujpoUbcmf`Tuvc
JHQNTPNDpmmfdujpo`HfuUzqfJogp
JHQNBtzodDbodfm`HfuUzqfJogpDpvou
DsfbufUsvtuff
JHQNDpotubout`hfu`QfsnTPNXNJGvmmDpouspm
JHQNHQPMjol`hfu`TPNMjolPsefs
hfu`FouszUzqfVtfs
JHQNDpotubout`hfu`TPNTjuf
JHQN`HfuTjuftDpoubjofs`Qspyz
JHQNDpotubout`hfu`FouszUzqfHmpcbmHspvq`Qspyz
qvu`QmboojohTjufObnf
JHQNCbdlvqDpmmfdujpo`hfu``OfxFovn`Qspyz
JJE`JHQNBtzodDbodfm
JHQNXNJGjmufs`hfu`Eftdsjqujpo
HQNTjuftDpoubjofs
JHQNHQP`hfu`VtfsETWfstjpoOvncfs
JHQNSTPQ`DsfbufRvfszSftvmut`Qspyz
``HQNCbdlvqDpmmfdujpo`GXE`EFGJOFE``
HQNSTPQ
JHQNHQPMjoltDpmmfdujpo`hfu`Dpvou`Qspyz
JHQN`HfuDpotubout
``HQNEpnbjo`GXE`EFGJOFE``
hfu`TfbsdiQspqfsuzHQPQfsnjttjpot
JHQNDpotubout`hfu`QfsnTPNQmboojoh
JHQNCbdlvq`hfu`HQPJE`Tuvc
hfu`DsfbujpoUjnf
JHQNTubuvtNfttbhf`hfu`FyufotjpoObnf`Qspyz
JHQNCbdlvqEjs`HfuJEtPgObnft
JHQNSTPQWucm
JHQNNbqFousz`HfuUzqfJogpDpvou
JHQNNjhsbujpoUbcmf`Wbmjebuf`Tuvc
JHQNHQP`hfu`DsfbujpoUjnf`Qspyz
JHQNXNJGjmufs`HfuJEtPgObnft
JHQNTPN`HfuUzqfJogp
JHQNCbdlvq`hfu`Ujnftubnq`Qspyz
JHQNNbqFousz`hfu`Tpvsdf`Qspyz
JHQN`DsfbufQfsnjttjpo`Qspyz
qvu`Eftdsjqujpo
JHQNUsvtuff`hfu`UsvtuffTje`Qspyz
qvu`QmboojohVtfsXNJGjmufst
JHQNTubuvtNfttbhf`hfu`FyufotjpoObnf
hqpXNJGjmufs
JHQNDTFDpmmfdujpo`hfu`Jufn
JHQNTPN`Sfmfbtf
JHQNDTFDpmmfdujpo`hfu``OfxFovn
JHQNSTPQ`qvu`QmboojohGmbht
qvu`Obnf
JHQNHQPMjoltDpmmfdujpo`hfu`Jufn`Tuvc
JHQNQfsnjttjpo`hfu`Joifsjufe
JHQNBtzodQsphsftt`Jowplf
JHQNHQPMjoltDpmmfdujpo`hfu`Dpvou
hfu`Joifsjubcmf
``HQNHQPMjol`GXE`EFGJOFE``
JHQNHQP`Cbdlvq`Qspyz
hfu`TPNMjolPsefs
JHQNHQPDpmmfdujpo`RvfszJoufsgbdf
JHQNTfdvsjuzJogp`Sfnpwf
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPVtfsFyufotjpot`Qspyz
JHQNHQPMjol`hfu`Fogpsdfe`Tuvc
JHQNXNJGjmufs
JHQNDpotubout`hfu`QfsnTPNMjol`Tuvc
HQNFouszUzqf
HfuFousz
hfu`TfbsdiQspqfsuzHQPEpnbjo
JHQNDpotubout`hfu`EpOpuWbmjebufED`Qspyz
HQNHQPMjol
hfu`STPQNpefMphhjoh
BeeSfg
JJE`JHQNDTFDpmmfdujpo
JHQN`HfuCbdlvqEjs
JHQNNjhsbujpoUbcmf`EfmfufFousz`Tuvc
JHQNXNJGjmufs`Sfmfbtf
JHQNCbdlvqEjs`hfu`CbdlvqEjsfdupsz`Tuvc
JHQNSTPQ`hfu`QmboojohEpnbjoDpouspmmfs
HQNTfdvsjuzJogp
JHQNXNJGjmufs`HfuRvfszMjtu`Tuvc
``NJEM`jug`hqnhnu`1111`w1`1`t`jgtqfd
JHQNHQP`JtBDMDpotjtufou
JHQNTPN`DsfbufHQPMjol`Qspyz
JHQNDpotubout`hfu`EpOpuVtfX3LED`Qspyz
hfu`TfbsdiQspqfsuzHQPVtfsFyufotjpot
JHQNTPNDpmmfdujpo`hfu``OfxFovn`Tuvc
JHQNXNJGjmufsDpmmfdujpo`RvfszJoufsgbdf
JHQNHQPMjol`hfu`HQPJE
JHQNSTPQ`hfu`MphhjohDpnqvufs`Tuvc
JHQNDpotubout`hfu`TfbsdiPqOpuFrvbmt
JHQNTfdvsjuzJogp`Bee`Qspyz
HfuTPN
JHQNNbqFouszDpmmfdujpo`hfu`Jufn`Qspyz
JHQNNbqFouszDpmmfdujpo`hfu``OfxFovn`Tuvc
JHQNBtzodDbodfm`RvfszJoufsgbdf
JHQNDTFDpmmfdujpo`Jowplf
hfu`Usvtuff
JHQNXNJGjmufs`qvu`Obnf
hfu`QfsnTPNMjol
JHQNXNJGjmufsDpmmfdujpo`HfuUzqfJogpDpvou
DMTJE`HQNBtzodDbodfm
JHQNHQPMjol`qvu`Fogpsdfe
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPEjtqmbzObnf`Qspyz
HfuTfdvsjuzJogp
JHQNHQPMjoltDpmmfdujpo`HfuUzqfJogpDpvou
HQPSfqpsuQspwjefs
HQNEpnbjo
JHQNDpotubout`hfu`STPQNpefMphhjoh`Tuvc
JHQNHQP`HfuTfdvsjuzJogp`Qspyz
JHQNUsvtuff`hfu`UsvtuffUzqf`Tuvc
JHQNHQPMjoltDpmmfdujpoWucm
JHQNCbdlvq`hfu`Dpnnfou
JHQNTPN`HfuTfdvsjuzJogp`Tuvc
qvu`QmboojohVtfsTfdvsjuzHspvqt
JHQNDpotubout`hfu`QspdfttTfdvsjuz`Qspyz
JHQNEpnbjo`hfu`Epnbjo
JHQNTubuvtNfttbhf`hfu`PckfduQbui
JHQNTfdvsjuzJogp`hfu`Jufn`Tuvc
Wbmjebuf
JHQNDmjfouTjefFyufotjpo`JtVtfsFobcmfe`Qspyz
``HQNUsvtuff`GXE`EFGJOFE``
JHQNTubuvtNfttbhf
MJCJE`HQNHNUMjc
JHQN`HfuNjhsbujpoUbcmf
JHQNHQP`HfuTfdvsjuzJogp
``JHQNNbqFouszDpmmfdujpo`GXE`EFGJOFE``
JHQNEpnbjo`HfuXNJGjmufs
hfu`HQPEjtqmbzObnf
JHQNHQPMjoltDpmmfdujpo
JHQNHQPDpmmfdujpo`hfu`Jufn`Tuvc
JHQNDmjfouTjefFyufotjpo`hfu`JE`Tuvc
JJE`JHQNXNJGjmufsDpmmfdujpo
JHQNSTPQ`hfu`MphhjohVtfs
JHQNHQP`hfu`NpejgjdbujpoUjnf
JHQNDpotubout`hfu`QfsnXNJGjmufsDvtupn`Tuvc
uzqfVolopxo
JHQNDpotubout`hfu`TPNPV
JHQNSTPQ`hfu`QmboojohGmbht
JHQNQfsnjttjpo`hfu`Qfsnjttjpo`Qspyz
qvu`QmboojohDpnqvufsTfdvsjuzHspvqt
JHQNHQP`hfu`NpejgjdbujpoUjnf`Qspyz
JJE`JHQNDpotubout
JHQNDpotubout`hfu`VtfBozED
JHQNDpotubout`hfu`TfdvsjuzGmbht`Qspyz
hfu`QfsnXNJGjmufsFeju
JHQNDpotubout`hfu`FouszUzqfVtfs`Qspyz
JHQNBtzodQsphsftt`BeeSfg
JHQNUsvtuff`hfu`UsvtuffEpnbjo`Qspyz
JHQNTjuftDpoubjofs`TfbsdiTjuft
hfu`UsvtuffTje
JHQNSTPQ`qvu`QmboojohVtfsXNJGjmufst`Qspyz
JHQNTfbsdiDsjufsjb
JHQNXNJGjmufsDpmmfdujpo`hfu`Dpvou`Qspyz
HQN`VTF`BOZED
``hqnhnu`i``
``JHQNCbdlvqDpmmfdujpo`JOUFSGBDF`EFGJOFE``
stpqMphhjoh
hfu`TfbsdiQspqfsuzHQPXNJGjmufs
JHQNEpnbjo`HfuHQP
STPQ`OP`VTFS
hfu`UsvtuffUzqf
JHQNCbdlvq`hfu`HQPEpnbjo`Qspyz
JHQNDpotubout`hfu`SfqpsuIUNM
DMTJE`HQNSftvmu
JHQNEpnbjo`TfbsdiHQPt`Qspyz
JHQNDmjfouTjefFyufotjpoWucm
JHQN`HfuSTPQ
``NJEM`jug`hqnhnu`1111`w1`1`d`jgtqfd
JHQNHQP`NblfBDMDpotjtufou`Qspyz
JHQNHQP`DpqzUp`Qspyz
JHQNNjhsbujpoUbcmf`VqebufEftujobujpo`Tuvc
JHQNHQPMjoltDpmmfdujpo`Sfmfbtf
TfbsdiCbdlvqt
JHQNUsvtuff`hfu`UsvtuffObnf`Qspyz
JHQN`HfuEpnbjo`Qspyz
JHQNNbqFousz`HfuUzqfJogp
hfu`Uzqf
``JHQNSftvmu`GXE`EFGJOFE``
JHQNTfdvsjuzJogp`hfu``OfxFovn`Tuvc
JHQN
JHQNDmjfouTjefFyufotjpo`JtDpnqvufsFobcmfe`Tuvc
JHQNDpotubout`hfu`QfsnTPNXNJDsfbuf
JHQNTubuvtNthDpmmfdujpo`RvfszJoufsgbdf
JHQNBtzodQsphsftt`RvfszJoufsgbdf
JHQNCbdlvqDpmmfdujpo`hfu`Dpvou`Tuvc
JHQNXNJGjmufs`TfuTfdvsjuzJogp`Tuvc
JHQNSTPQ`HfuJEtPgObnft
JHQNTjuftDpoubjofs`HfuTjuf`Qspyz
JHQNHQP`HfuTfdvsjuzEftdsjqups`Tuvc
``JHQNHQP`GXE`EFGJOFE``
HQNDTFDpmmfdujpo
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPEpnbjo`Tuvc
``JHQNHQPMjol`GXE`EFGJOFE``
HQNQfsnjttjpoUzqf
JHQNEpnbjo`hfu`EpnbjoDpouspmmfs`Tuvc
JHQNHQP`TfuVtfsFobcmfe`Tuvc
Cbdlvq
hfu`Obnftqbdf
JHQNSTPQ`qvu`QmboojohDpnqvufs`Tuvc
JHQNTPN`DsfbufHQPMjol
JHQNSTPQ`qvu`QmboojohVtfsTPN
JHQNNjhsbujpoUbcmf`HfuFousz`Qspyz
JHQNNbqFousz`hfu`Eftujobujpo
JHQN`HfuTjuftDpoubjofs`Tuvc
JJE`JHQNEpnbjo
JHQNQfsnjttjpo`RvfszJoufsgbdf
JHQNNbqFouszWucm
JHQNDpotubout`hfu`StpqQmboojohBttvnfTmpxMjol`Qspyz
JHQNEpnbjo`BeeSfg
JHQNDpotubout`hfu`STPQNpefQmboojoh`Qspyz
JHQNSTPQ`qvu`QmboojohTjufObnf`Qspyz
``JHQNTPN`GXE`EFGJOFE``
JHQNHQP`hfu`EjtqmbzObnf`Qspyz
JHQNTPNDpmmfdujpo`HfuUzqfJogpDpvou
JHQNSTPQ`hfu`QmboojohTjufObnf`Qspyz
JHQNHQP`TfuXNJGjmufs`Qspyz
JHQNHQP`hfu`DsfbujpoUjnf
qvu`Fogpsdfe
JHQNDpotubout`hfu`TPNTjuf`Qspyz
JHQNHQP`hfu`DpnqvufsETWfstjpoOvncfs`Tuvc
JHQNCbdlvq
JHQNDpotubout`hfu`TPNEpnbjo
JHQNCbdlvq`HfuUzqfJogpDpvou
JHQNDpotubout
JHQNNjhsbujpoUbcmf`HfuUzqfJogpDpvou
NblfBDMDpotjtufou
JHQNDmjfouTjefFyufotjpo`JtVtfsFobcmfe
JHQNTfdvsjuzJogp`hfu`Dpvou`Tuvc
JHQNHQPMjol`Efmfuf`Qspyz
JHQNBtzodDbodfm`HfuUzqfJogp
JHQNDmjfouTjefFyufotjpo`hfu`JE
DMTJE`HQN
``JHQN`JOUFSGBDF`EFGJOFE``
JHQNTubuvtNthDpmmfdujpo`HfuJEtPgObnft
JHQNSTPQ`HfofsbufSfqpsuUpGjmf`Tuvc
JHQNNbqFouszDpmmfdujpo`RvfszJoufsgbdf
JHQNDpotubout`hfu`FouszUzqfVolopxo
JHQNHQP`hfu`Qbui`Qspyz
hfu`StpqQmboojohBttvnfTmpxMjol
TfbsdiXNJGjmufst
stpqQmboojoh
JHQNQfsnjttjpo`hfu`Joifsjubcmf
JHQNXNJGjmufs`hfu`Qbui`Qspyz
``JHQNUsvtuff`GXE`EFGJOFE``
Jojujbmj{fSfqpsujoh
JHQNHQPDpmmfdujpo`hfu`Dpvou`Tuvc
JHQNXNJGjmufsDpmmfdujpo`BeeSfg
JHQNQfsnjttjpo`hfu`Efojfe
JHQNDmjfouTjefFyufotjpo`HfuUzqfJogp
JHQNTubuvtNthDpmmfdujpo`hfu``OfxFovn
JHQNHQPMjol`qvu`Fogpsdfe`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPJE`Tuvc
JHQNTPN`RvfszJoufsgbdf
hfu`QfsnHQPDvtupn
JHQNDpotubout`hfu`QfsnHQPSfbe`Qspyz
JHQNSTPQ`qvu`QmboojohDpnqvufsTPN
hfu`VtfsTztwpmWfstjpoOvncfs
JHQNHQP`TfuTfdvsjuzJogp`Tuvc
JHQNSftvmu`hfu`Tubuvt`Qspyz
JHQNXNJGjmufs`hfu`Qbui`Tuvc
JHQNSTPQ`HfofsbufSfqpsu`Qspyz
HQNDmjfouTjefFyufotjpo
JHQNDpotubout`hfu`QfsnTPNQmboojoh`Qspyz
hfu`QmboojohVtfsXNJGjmufst
JHQNCbdlvq`Jowplf
HQNTfbsdiDsjufsjb
JHQNHQPMjoltDpmmfdujpo`hfu`Jufn`Qspyz
JHQNDpotubout`hfu`QfsnXNJGjmufsGvmmDpouspm`Qspyz
JHQNNbqFouszDpmmfdujpo
JHQNCbdlvqDpmmfdujpo`HfuUzqfJogp
JHQNHQP`hfu`DsfbujpoUjnf`Tuvc
JHQNUsvtuff`HfuUzqfJogpDpvou
JHQNQfsnjttjpo`hfu`Efojfe`Tuvc
JHQNCbdlvqEjs`TfbsdiCbdlvqt
JHQNDpotubout`hfu`QfsnHQPBqqmz
JHQNCbdlvq`hfu`Ujnftubnq`Tuvc
Dbodfm
JHQNNjhsbujpoUbcmf`Wbmjebuf
JHQNHQPMjol`hfu`HQPJE`Tuvc
JJE`JHQNTfdvsjuzJogp
JHQNTubuvtNfttbhf`BeeSfg
JHQNNbqFouszDpmmfdujpoWucm
JHQNDpotubout`hfu`StpqQmboojohBttvnfVtfsXRMGjmufsUsvf`Qspyz
JHQNTubuvtNfttbhf`Jowplf
JHQN`Jowplf
JHQNDpotubout`hfu`StpqMphhjohOpVtfs
qvu`QmboojohDpnqvufs
JHQNTPN`hfu`Qbui
JHQNEpnbjo`HfuHQP`Tuvc
JHQNSTPQ`hfu`QmboojohGmbht`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPJE
hfu`TfbsdiQspqfsuzTPNMjolt
JtVtfsFobcmfe
JHQNXNJGjmufsDpmmfdujpoWucm
HQNTPNDpmmfdujpo
JHQNEpnbjo`TfbsdiHQPt
JHQN`HfuDpotubout`Tuvc
JHQNBtzodQsphsftt`Tubuvt`Tuvc
JHQNTPN`HfuJoifsjufeHQPMjolt
``JHQNTPNDpmmfdujpo`JOUFSGBDF`EFGJOFE``
``HQNDTFDpmmfdujpo`GXE`EFGJOFE``
HQNSTPQNpef
JHQNTPN`DsfbufHQPMjol`Tuvc
JHQNDpotubout`hfu`EpOpuWbmjebufED`Tuvc
JHQNCbdlvqEjs`hfu`CbdlvqEjsfdupsz
``JHQNCbdlvq`JOUFSGBDF`EFGJOFE``
``SFRVJSFE`SQDOES`I`WFSTJPO``
JHQNQfsnjttjpo`hfu`Joifsjufe`Tuvc
JHQNHQPMjol`hfu`Fogpsdfe
JHQNSTPQ`hfu`MphhjohGmbht`Tuvc
JHQNDpotubout`hfu`SfqpsuYNM`Tuvc
JHQNSftvmuWucm
JHQNBtzodQsphsftt`Sfmfbtf
JHQNDpotubout`RvfszJoufsgbdf
``JHQNHQPDpmmfdujpo`GXE`EFGJOFE``
``JHQNBtzodDbodfm`JOUFSGBDF`EFGJOFE``
JHQNTfdvsjuzJogp`BeeSfg
JHQNDpotubout`hfu`VtfBozED`Tuvc
JHQNNbqFousz`BeeSfg
JHQNTubuvtNthDpmmfdujpo`HfuUzqfJogp
JHQNHQPMjol`hfu`HQPEpnbjo`Tuvc
JHQNXNJGjmufs`qvu`Eftdsjqujpo
uzqfHmpcbmHspvq
JHQN`DsfbufQfsnjttjpo`Tuvc
HQN`VTF`QED
DsfbufQfsnjttjpo
hfu`QmboojohVtfsTfdvsjuzHspvqt
JHQNTubuvtNthDpmmfdujpo`hfu`Dpvou`Tuvc
JHQNDTFDpmmfdujpo`hfu`Dpvou
JHQNHQPMjol
JHQNTPNDpmmfdujpo`hfu``OfxFovn
JHQNDpotubout`hfu`TfbsdiQspqfsuzTPNMjolt`Qspyz
JHQNSTPQ`HfofsbufSfqpsu
JHQNHQP`hfu`DpnqvufsETWfstjpoOvncfs
JHQNCbdlvqDpmmfdujpo`BeeSfg
JHQNXNJGjmufs`qvu`Eftdsjqujpo`Qspyz
HQNTfbsdiPqfsbujpo
JHQNUsvtuff`HfuUzqfJogp
JHQNSTPQ`hfu`QmboojohEpnbjoDpouspmmfs`Tuvc
JHQNXNJGjmufsDpmmfdujpo`hfu`Jufn`Tuvc
hfu`TfuujohtObnf
DMTJE`HQPSfqpsuQspwjefs
JHQNHQP`HfuXNJGjmufs`Qspyz
JHQNTubuvtNthDpmmfdujpo`Jowplf
JHQNQfsnjttjpo`hfu`Joifsjubcmf`Qspyz
JHQNDpotubout`hfu`STPQNpefVolopxo
JHQNEpnbjo`HfuXNJGjmufs`Tuvc
JHQNTPN`HfuHQPMjolt`Tuvc
``NJEM```NJEM`jug`hqnhnu`1111`1113
hfu`FouszUzqfVolopxo
JHQNCbdlvq`BeeSfg
JHQNDpotubout`hfu`TfbsdiQspqfsuzTPNMjolt`Tuvc
JHQNHQP`HfuUzqfJogpDpvou
``JHQNNbqFousz`GXE`EFGJOFE``
JHQNHQP`TfuTfdvsjuzJogp`Qspyz
DMTJE`HQNTPNDpmmfdujpo
JHQNQfsnjttjpo`Sfmfbtf
JHQNHQPMjol`qvu`Fobcmfe
HfuCbdlvqEjs
hfu`SfqpsuIUNM
JHQNBtzodDbodfm`Jowplf
JHQNTubuvtNfttbhf`hfu`Nfttbhf`Tuvc
JJE`JHQNTubuvtNthDpmmfdujpo
JHQNHQPMjol`qvu`Fobcmfe`Qspyz
``HQNTubuvtNfttbhf`GXE`EFGJOFE``
hfu`QmboojohDpnqvufs
JHQNNjhsbujpoUbcmf`Tbwf`Tuvc
JHQNSTPQ`hfu`QmboojohVtfsXNJGjmufst
qfsnTPNQmboojoh
JHQNEpnbjo`DsfbufHQP`Qspyz
JHQNDpotubout`hfu`SfqpsuIUNM`Qspyz
JHQNDpotubout`hfu`FouszUzqfVolopxo`Qspyz
JHQNCbdlvqEjs`Jowplf
``JHQNNjhsbujpoUbcmf`GXE`EFGJOFE``
Sfmfbtf
JHQNTPN`TfuTfdvsjuzJogp`Tuvc
qvu`MphhjohDpnqvufs
HfuTjuf
JHQNSftvmu`RvfszJoufsgbdf
JHQNDmjfouTjefFyufotjpo`Sfmfbtf
``HQNSftvmu`GXE`EFGJOFE``
JHQNDpotubout`hfu`QfsnHQPBqqmz`Qspyz
qvu`QmboojohDpnqvufsXNJGjmufst
JHQNTubuvtNfttbhf`HfuUzqfJogp
JHQNQfsnjttjpo`Jowplf
JHQNHQP`DpqzUp`Tuvc
DMTJE`HQNTubuvtNfttbhf
JHQNCbdlvq`hfu`HQPJE
JHQNDpotubout`hfu`FouszUzqfVojwfstbmHspvq`Tuvc
``JHQNHQP`JOUFSGBDF`EFGJOFE``
JHQNNbqFousz`Sfmfbtf
qvu`QmboojohDpnqvufsTPN
JHQNHQPDpmmfdujpo`hfu`Dpvou
DMTJE`HQNDTFDpmmfdujpo
JHQNEpnbjo`TfbsdiXNJGjmufst`Tuvc
qfsnHQPFejuTfdvsjuzBoeEfmfuf
``JHQNCbdlvq`GXE`EFGJOFE``
JHQNHQP`HfofsbufSfqpsu`Tuvc
JHQNUsvtuff`hfu`UsvtuffEpnbjo
JHQNDpotubout`hfu`QfsnTPNQmboojoh`Tuvc
JHQNUsvtuff`BeeSfg
hfu`QfsnXNJGjmufsDvtupn
STPQ`QMBOOJOH`BTTVNF`TMPX`MJOL
JHQNXNJGjmufs`hfu`Eftdsjqujpo`Tuvc
JHQN`HfuSTPQ`Qspyz
JHQNCbdlvqDpmmfdujpo`Sfmfbtf
JHQNDpotubout`hfu`QfsnTPNMphhjoh
JHQNSTPQ`DsfbufRvfszSftvmut
JHQNDpotubout`hfu`EftujobujpoPqujpoTfu`Qspyz
JHQNTubuvtNfttbhf`hfu`PckfduQbui`Tuvc
JJE`JHQNQfsnjttjpo
SftupsfHQP
JHQNHQP`JtBDMDpotjtufou`Qspyz
``HQNFovn`GXE`EFGJOFE``
CTUS`VtfsNbstibm
JHQNDpotubout`hfu`TfbsdiPqOpuDpoubjot
DMTJE`HQNXNJGjmufs
JHQNEpnbjo`Sfmfbtf
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPXNJGjmufs`Qspyz
uzqfMpdbmHspvq
JHQNHQP`hfu`EjtqmbzObnf
JHQNTPN`Jowplf
hqpJE
hfu`EftujobujpoPqujpoOpof
JHQNCbdlvqEjs`hfu`CbdlvqEjsfdupsz`Qspyz
hfu`FouszUzqfHmpcbmHspvq
qvu`QmboojohVtfsTPN
qvu`QmboojohVtfs
JHQNEpnbjo
JHQN`Jojujbmj{fSfqpsujoh`Qspyz
JHQNUsvtuff`hfu`UsvtuffUzqf
JHQNHQPDpmmfdujpo`Sfmfbtf
JHQNDpotubout`hfu`StpqQmboojohBttvnfDpnqXRMGjmufsUsvf
JHQNDpotubout`hfu`FouszUzqfVojwfstbmHspvq`Qspyz
JtDpnqvufsFobcmfe
JHQN`HfuNjhsbujpoUbcmf`Tuvc
``JHQNQfsnjttjpo`GXE`EFGJOFE``
hfu`TfbsdiPqOpuDpoubjot
JHQNDpotubout`hfu`QfsnHQPFejuTfdvsjuzBoeEfmfuf`Qspyz
``NJEM```NJEM`jug`hqnhnu`1111`1118
JHQNDpotubout`hfu`FouszUzqfVtfs
HfofsbufSfqpsuUpGjmf
JHQNNbqFousz`RvfszJoufsgbdf
JHQNHQP`HfofsbufSfqpsu`Qspyz
JHQNDTFDpmmfdujpo`HfuJEtPgObnft
DMTJE`HQNHQP
JHQNHQP`JtBDMDpotjtufou`Tuvc
JHQNHQPMjol`Jowplf
JHQN`HfuUzqfJogpDpvou
SfmfbtfRvfszSftvmut
JJE`JHQNHQPDpmmfdujpo
JHQNXNJGjmufsDpmmfdujpo`hfu`Jufn`Qspyz
JHQNHQPDpmmfdujpo`hfu``OfxFovn`Qspyz
JHQN`DsfbufTfbsdiDsjufsjb`Tuvc
JHQNHQPMjol`BeeSfg
JHQNSTPQ`hfu`MphhjohDpnqvufs
``JHQNSTPQ`JOUFSGBDF`EFGJOFE``
JHQNHQP`NblfBDMDpotjtufou`Tuvc
JHQNSftvmu`Jowplf
JHQNHQP`hfu`Qbui
JHQNDpotubout`hfu`QfsnXNJGjmufsFeju`Qspyz
JHQNCbdlvqDpmmfdujpo`hfu``OfxFovn`Tuvc
JHQNEpnbjo`HfuUzqfJogp
hfu`TfbsdiPqDpoubjot
JHQNEpnbjo`hfu`EpnbjoDpouspmmfs`Qspyz
JHQNSTPQ`qvu`QmboojohGmbht`Tuvc
hfu`EpnbjoObnf
JHQNEpnbjo`HfuXNJGjmufs`Qspyz
``JHQNBtzodDbodfm`GXE`EFGJOFE``
JHQNTubuvtNthDpmmfdujpo
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPQfsnjttjpot`Tuvc
JHQNTPN`hfu`HQPJoifsjubodfCmpdlfe`Qspyz
HQN`EPOPU`WBMJEBUFED
JtBDMDpotjtufou
JHQNSTPQ`DsfbufRvfszSftvmut`Tuvc
JHQNTubuvtNfttbhf`hfu`TfuujohtObnf
JHQNSftvmu`HfuUzqfJogpDpvou
JHQNQfsnjttjpo
``JHQNBtzodQsphsftt`GXE`EFGJOFE``
``JHQNTPNDpmmfdujpo`GXE`EFGJOFE``
JHQNDpotubout`hfu`FouszUzqfDpnqvufs`Tuvc
hfu`EpOpuWbmjebufED
hfu`TfbsdiQspqfsuzHQPJE
JHQNHQPDpmmfdujpo`HfuUzqfJogp
MphhjohFovnfsbufVtfst
JHQNTPNDpmmfdujpoWucm
PqfsbujpoDpef
JHQN`HfuDmjfouTjefFyufotjpot
JHQNTfdvsjuzJogp`hfu``OfxFovn`Qspyz
TfuTfdvsjuzJogp
JHQNDpotubout`hfu`QfsnXNJGjmufsFeju`Tuvc
JHQNHQPMjol`hfu`HQPEpnbjo
HQNCbdlvqDpmmfdujpo
JHQNTPN`hfu`HQPJoifsjubodfCmpdlfe`Tuvc
JHQNQfsnjttjpo`HfuUzqfJogp
JHQNHQP`Cbdlvq
HQNHQPDpmmfdujpo
pqDpoubjot
``JHQNTubuvtNthDpmmfdujpo`JOUFSGBDF`EFGJOFE``
DMTJE`HQNHQPMjoltDpmmfdujpo
JHQNCbdlvq`Efmfuf
JHQNNbqFousz`hfu`Tpvsdf`Tuvc
JHQNBtzodQsphsftt`Tubuvt
JHQNBtzodQsphsftt
JHQNSTPQ`HfuUzqfJogpDpvou
hfu`Sftvmu
JHQNTubuvtNfttbhf`hfu`PckfduQbui`Qspyz
TfuVtfsFobcmfe
``HQNTjuftDpoubjofs`GXE`EFGJOFE``
hfu`STPQNpefQmboojoh
sfqYNM
JHQNDTFDpmmfdujpo`hfu`Dpvou`Tuvc
JHQNDmjfouTjefFyufotjpo`JtDpnqvufsFobcmfe`Qspyz
JHQNNjhsbujpoUbcmf`VqebufEftujobujpo
JHQNTPN`TfuTfdvsjuzJogp`Qspyz
JHQNSTPQ`hfu`Obnftqbdf`Qspyz
JJE`JHQNSTPQ
JHQNDpotubout`hfu`TfbsdiPqOpuDpoubjot`Qspyz
hfu`FouszUzqfVODQbui
JHQNHQPMjoltDpmmfdujpo`hfu``OfxFovn`Qspyz
pqOpuFrvbmt
JHQNHQP`JtDpnqvufsFobcmfe
JHQNNjhsbujpoUbcmf`Tbwf`Qspyz
pqOpuDpoubjot
JHQNSftvmu`HfuJEtPgObnft
JHQNTPN`HfuJoifsjufeHQPMjolt`Tuvc
JHQNUsvtuff`hfu`UsvtuffTje
JHQNDpotubout`hfu`QfsnXNJGjmufsDvtupn
JHQNUsvtuff`hfu`UsvtuffObnf
JHQNHQPDpmmfdujpo`hfu`Dpvou`Qspyz
JHQNNjhsbujpoUbcmf`Sfmfbtf
``JHQNBtzodQsphsftt`JOUFSGBDF`EFGJOFE``
HQNQfsnjttjpo
``JHQNQfsnjttjpo`JOUFSGBDF`EFGJOFE``
JHQNNjhsbujpoUbcmf`Bee`Tuvc
hfu`STPQNpefVolopxo
JJE`JHQNTPNDpmmfdujpo
JHQNTubuvtNfttbhf`Sfmfbtf
JHQNTPN`HfuHQPMjolt`Qspyz
JHQNTfdvsjuzJogp`SfnpwfUsvtuff
JHQNTubuvtNthDpmmfdujpo`BeeSfg
``JHQNTfdvsjuzJogp`GXE`EFGJOFE``
JHQNHQP`hfu`NpejgjdbujpoUjnf`Tuvc
JJE`JHQNDmjfouTjefFyufotjpo
uzqfVODQbui
JHQNDpotubout`hfu`QfsnTPNXNJGvmmDpouspm`Qspyz
JHQNBtzodDbodfm`BeeSfg
JHQNDmjfouTjefFyufotjpo`JtVtfsFobcmfe`Tuvc
JHQNDpotubout`hfu`EftujobujpoPqujpoTfu
JHQNTPN`TfuTfdvsjuzJogp
JHQNTPN`hfu`Uzqf`Qspyz
CTUS`VtfsVonbstibm
``HQNTubuvtNthDpmmfdujpo`GXE`EFGJOFE``
JHQNDpotubout`HfuUzqfJogp
JHQNHQP`hfu`JE`Qspyz
JHQNCbdlvqDpmmfdujpo`HfuJEtPgObnft
JHQNCbdlvq`HfofsbufSfqpsu`Qspyz
JJE`JHQNTjuftDpoubjofs
JHQNSTPQ`qvu`QmboojohVtfsXNJGjmufst
JHQNSTPQ`qvu`QmboojohVtfsTfdvsjuzHspvqt`Qspyz
JHQNHQPDpmmfdujpo`hfu``OfxFovn`Tuvc
JHQNDpotubout`hfu`TPNPV`Qspyz
JHQNSftvmu`hfu`Sftvmu`Tuvc
JHQNDpotubout`hfu`QfsnTPNMjol`Qspyz
JHQNDmjfouTjefFyufotjpo`hfu`EjtqmbzObnf`Tuvc
JHQNDpotubout`hfu`NjhsbujpoUbcmfPomz`Tuvc
hfu`EftujobujpoPqujpo
``HQNXNJGjmufs`GXE`EFGJOFE``
JHQNNjhsbujpoUbcmf`BeeFousz
hfu`HQPJE
JHQNDpotubout`hfu`NjhsbujpoUbcmfPomz`Qspyz
JHQNHQPMjol`HfuUzqfJogpDpvou
JHQNCbdlvq`hfu`JE`Qspyz
JHQNTfbsdiDsjufsjb`Sfmfbtf
JHQNEpnbjo`TfbsdiXNJGjmufst
JHQNHQP`BeeSfg
JHQNDpotubout`hfu`FouszUzqfHmpcbmHspvq
JHQNTPNDpmmfdujpo`hfu``OfxFovn`Qspyz
JHQNCbdlvqDpmmfdujpo`RvfszJoufsgbdf
qfsnHQPSfbe
hqpEjtqmbzObnf
JHQNNjhsbujpoUbcmf`HfuFousz
JHQNXNJGjmufs`HfuRvfszMjtu
JHQNDpotubout`hfu`QfsnHQPFeju`Tuvc
JHQNCbdlvqEjs`TfbsdiCbdlvqt`Tuvc
JHQNTPNDpmmfdujpo`Sfmfbtf
uzqfDpnqvufs
cbdlvqNptuSfdfou
JHQNQfsnjttjpo`hfu`Joifsjufe`Qspyz
JHQNQfsnjttjpo`hfu`Efojfe`Qspyz
JHQNDpotubout`hfu`FouszUzqfVODQbui`Qspyz
JHQNSftvmu`hfu`Tubuvt`Tuvc
hfu`QfsnTPNXNJDsfbuf
JHQNDpotubout`hfu`VtfQED`Tuvc
HQNXNJGjmufsDpmmfdujpo
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPXNJGjmufs
JHQNTfdvsjuzJogp`HfuUzqfJogp
EfmfufFousz
hfu`UsvtuffEpnbjo
tpnPV
JHQNSTPQ`hfu`QmboojohVtfsXNJGjmufst`Qspyz
JHQNSTPQ`HfofsbufSfqpsu`Tuvc
JHQNCbdlvq`hfu`HQPEjtqmbzObnf`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPEjtqmbzObnf`Tuvc
JHQNCbdlvq`HfofsbufSfqpsu
HQN
JHQNDpotubout`hfu`FouszUzqfVODQbui`Tuvc
JHQNDpotubout`hfu`STPQNpefQmboojoh
JHQNSftvmu`PwfsbmmTubuvt`Tuvc
JHQNDpotubout`hfu`TfbsdiPqOpuFrvbmt`Tuvc
DMTJE`HQNFovn
JHQNTjuftDpoubjofs`hfu`EpnbjoDpouspmmfs
JHQNTfdvsjuzJogp`Bee
JHQNHQP`HfofsbufSfqpsuUpGjmf`Tuvc
JHQNCbdlvqEjs`Sfmfbtf
JHQNTubuvtNthDpmmfdujpoWucm
JHQNHQPMjol`HfuUzqfJogp
JHQNTfbsdiDsjufsjb`RvfszJoufsgbdf
HfuHQP
JHQNTPN`qvu`HQPJoifsjubodfCmpdlfe`Qspyz
hfu`TfbsdiQspqfsuzCbdlvqNptuSfdfou
JHQNHQP`TfuTfdvsjuzJogp
JHQNEpnbjo`TfbsdiTPNt
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPQfsnjttjpot`Qspyz
JHQN`DsfbufUsvtuff`Tuvc
hfu`QfsnTPNHQPDsfbuf
hfu`TPNTjuf
Tbwf
``JHQNTfbsdiDsjufsjb`GXE`EFGJOFE``
JHQNTPNDpmmfdujpo
JHQNDpotubout`hfu`QfsnHQPSfbe`Tuvc
qvu`QmboojohEpnbjoDpouspmmfs
qfsnTPNMjol
JHQNSTPQ`hfu`QmboojohDpnqvufsXNJGjmufst
JHQN`HfuEpnbjo
hfu`QfsnHQPFejuTfdvsjuzBoeEfmfuf
JHQNTjuftDpoubjofs`HfuTjuf
``JHQNTjuftDpoubjofs`GXE`EFGJOFE``
JJE`JHQN
``JHQNUsvtuff`JOUFSGBDF`EFGJOFE``
hfu`Eftdsjqujpo
JHQNUsvtuff`hfu`UsvtuffETQbui`Qspyz
JHQNNbqFousz`hfu`FouszUzqf`Tuvc
JHQNSTPQ`qvu`QmboojohVtfsTfdvsjuzHspvqt
JHQNNbqFousz
JHQNSTPQ`qvu`MphhjohDpnqvufs`Tuvc
hfu`JE
JHQNCbdlvqEjs`HfuCbdlvq
JHQNSTPQ`hfu`QmboojohVtfsTfdvsjuzHspvqt`Tuvc
JHQNTjuftDpoubjofs`hfu`Epnbjo
JHQNHQPDpmmfdujpo`HfuUzqfJogpDpvou
JHQNDpotubout`hfu`TfbsdiQspqfsuzCbdlvqNptuSfdfou`Tuvc
hfu`HQPJoifsjubodfCmpdlfe
JHQNHQP`TfuTfdvsjuzEftdsjqups`Tuvc
JHQNTPN`HfuTfdvsjuzJogp
JHQNSTPQ`qvu`QmboojohVtfsXNJGjmufst`Tuvc
JHQNCbdlvq`HfuUzqfJogp
JHQNSTPQ`hfu`QmboojohVtfsTPN`Tuvc
JHQNBtzodQsphsftt`HfuJEtPgObnft
JHQNEpnbjo`TfbsdiTPNt`Tuvc
hfu`QmboojohDpnqvufsTPN
JHQNHQPWucm
JHQNTubuvtNfttbhf`RvfszJoufsgbdf
JHQNSTPQ`hfu`QmboojohDpnqvufs`Tuvc
hfu`QfsnXNJGjmufsGvmmDpouspm
JHQN`Sfmfbtf
JHQNTjuftDpoubjofs`Sfmfbtf
JHQNHQP`JtDpnqvufsFobcmfe`Tuvc
DMTJE`HQNDpotubout
DMTJE`HQNTfdvsjuzJogp
JHQNTfbsdiDsjufsjbWucm
``HQNTfdvsjuzJogp`GXE`EFGJOFE``
JHQNDpotubout`hfu`QfsnHQPFeju`Qspyz
JHQNBtzodQsphsftt`HfuUzqfJogp
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPVtfsFyufotjpot
hfu`Gpsftu
JHQNTfdvsjuzJogp`RvfszJoufsgbdf
hfu`TfdvsjuzGmbht
JHQNDpotubout`hfu`StpqQmboojohBttvnfDpnqXRMGjmufsUsvf`Qspyz
JHQNHQPMjol`hfu`Fogpsdfe`Qspyz
hfu`TPN
JHQNXNJGjmufsWucm
FsspsDpef
qvu`HQPJoifsjubodfCmpdlfe
JHQNDpotubout`hfu`TfbsdiPqOpuFrvbmt`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPQfsnjttjpot
JHQNNjhsbujpoUbcmf`RvfszJoufsgbdf
hfu`MphhjohDpnqvufs
JHQNTPN`hfu`Qbui`Tuvc
JHQNUsvtuff`HfuJEtPgObnft
JHQNDmjfouTjefFyufotjpo`Jowplf
JHQNTPN`hfu`Uzqf
JHQNCbdlvq`hfu`HQPEpnbjo`Tuvc
JHQNEpnbjoWucm
JHQNDpotubout`hfu`TPNPV`Tuvc
DMTJE`HQNNbqFouszDpmmfdujpo
JHQNTfdvsjuzJogp`SfnpwfUsvtuff`Tuvc
HQNTubuvtNfttbhf
PwfsbmmTubuvt
hfu`TfbsdiQspqfsuzHQPDpnqvufsFyufotjpot
hfu`TfbsdiQspqfsuzHQPFggfdujwfQfsnjttjpot
HQNNbqFousz
JHQNCbdlvq`HfofsbufSfqpsuUpGjmf`Tuvc
``HQNTPN`GXE`EFGJOFE``
JHQNHQP`Cbdlvq`Tuvc
RvfszJoufsgbdf
JHQNHQPMjoltDpmmfdujpo`hfu``OfxFovn`Tuvc
HfuTfdvsjuzEftdsjqups
pqEftujobujpoTfu
JHQNSTPQ`hfu`QmboojohVtfs`Qspyz
HfuJoifsjufeHQPMjolt
JHQNNbqFousz`hfu`Tpvsdf
JHQNNjhsbujpoUbcmf`HfuUzqfJogp
DsfbufRvfszSftvmut
JHQN`DsfbufTfbsdiDsjufsjb`Qspyz
JHQNNbqFouszDpmmfdujpo`hfu`Jufn`Tuvc
Jnqpsu
JHQNCbdlvqWucm
JHQNTjuftDpoubjofs`HfuUzqfJogpDpvou
JHQNXNJGjmufs`HfuUzqfJogpDpvou
JHQNHQP`Efmfuf`Tuvc
JHQNEpnbjo`HfuUzqfJogpDpvou
JHQNTubuvtNthDpmmfdujpo`hfu`Jufn
DMTJE`HQNCbdlvq
JJE`JHQNCbdlvqEjs
JHQNHQP`TfuTfdvsjuzEftdsjqups
JHQNHQPDpmmfdujpo`BeeSfg
``JHQNNjhsbujpoUbcmf`JOUFSGBDF`EFGJOFE``
JHQNTfdvsjuzJogp`Sfmfbtf
JHQNSTPQ`hfu`QmboojohVtfsTPN`Qspyz
``JHQNHQPMjol`JOUFSGBDF`EFGJOFE``
JHQNDmjfouTjefFyufotjpo`hfu`JE`Qspyz
JHQNDpotubout`hfu`STPQNpefVolopxo`Tuvc
JHQNNjhsbujpoUbcmf`HfuFousjft
hfu`Eftujobujpo
JHQNHQP`hfu`VtfsTztwpmWfstjpoOvncfs`Tuvc
hfu`QmboojohDpnqvufsXNJGjmufst
qvu`EjtqmbzObnf
DMTJE`HQNCbdlvqEjs
``HQNNbqFouszDpmmfdujpo`GXE`EFGJOFE``
JHQNUsvtuff`hfu`UsvtuffEpnbjo`Tuvc
JHQNDTFDpmmfdujpo`HfuUzqfJogpDpvou
JHQNTubuvtNthDpmmfdujpo`Sfmfbtf
JHQNSTPQ`qvu`QmboojohVtfs
JHQNEpnbjo`Jowplf
HQNFovn
``NJEM```NJEM`jug`hqnhnu`1111`1114
JHQNDpotubout`hfu`QfsnXNJGjmufsGvmmDpouspm
HQNCbdlvqEjs
JHQNTfdvsjuzJogp
JHQNDpotubout`hfu`EftujobujpoPqujpoCzSfmbujwfObnf
JHQNNbqFouszDpmmfdujpo`hfu`Dpvou`Tuvc
DMTJE`HQNTfbsdiDsjufsjb
DsfbufTfbsdiDsjufsjb
JHQNDTFDpmmfdujpoWucm
JHQNHQP`HfuUzqfJogp
JHQNDpotubout`Sfmfbtf
hfu`TfbsdiPqFrvbmt
JHQNSTPQ`qvu`QmboojohTjufObnf`Tuvc
JHQNDpotubout`hfu`QfsnHQPDvtupn`Qspyz
JHQNDpotubout`hfu`QfsnTPNMjol
hfu`QmboojohEpnbjoDpouspmmfs
JHQNSTPQ`hfu`QmboojohDpnqvufsTfdvsjuzHspvqt`Tuvc
JHQNTjuftDpoubjofs`HfuTjuf`Tuvc
JHQNTfdvsjuzJogp`Jowplf
WBSJBOU`VtfsGsff
JHQNTfbsdiDsjufsjb`Bee
JHQNTPNDpmmfdujpo`hfu`Jufn`Qspyz
JHQNTPN`hfu`Obnf`Qspyz
JHQNHQP`qvu`EjtqmbzObnf`Tuvc
qfsnXNJGjmufsGvmmDpouspm
JHQNUsvtuff`hfu`UsvtuffUzqf`Qspyz
JHQNHQP`HfofsbufSfqpsuUpGjmf
HfuUzqfJogpDpvou
pqEftujobujpoCzSfmbujwfObnf
qfsnHQPFeju
JHQNEpnbjo`SftupsfHQP
``JHQNSftvmu`JOUFSGBDF`EFGJOFE``
JHQNSTPQ`MphhjohFovnfsbufVtfst`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPDpnqvufsFyufotjpot`Tuvc
DMTJE`HQNCbdlvqDpmmfdujpo
DMTJE`HQNTPN
JHQNTfbsdiDsjufsjb`HfuUzqfJogp
JHQNTPN`HfuJoifsjufeHQPMjolt`Qspyz
``HQNDpotubout`GXE`EFGJOFE``
JHQNXNJGjmufs`qvu`Eftdsjqujpo`Tuvc
JHQNXNJGjmufsDpmmfdujpo`hfu`Jufn
JHQNHQP`Efmfuf
DMTJE`HQNNbqFousz
JHQNTPNDpmmfdujpo`hfu`Dpvou
JHQNTfdvsjuzJogp`hfu``OfxFovn
JHQNNbqFousz`hfu`EftujobujpoPqujpo`Tuvc
``HQNHQPMjoltDpmmfdujpo`GXE`EFGJOFE``
JHQNSTPQ`hfu`QmboojohTjufObnf
TfbsdiHQPt
NJEM`vtfs`gsff
hfu`StpqQmboojohBttvnfVtfsXRMGjmufsUsvf
JHQN`HfuEpnbjo`Tuvc
JHQNTPNDpmmfdujpo`HfuJEtPgObnft
JHQN`HfuDmjfouTjefFyufotjpot`Qspyz
JHQNSftvmu`hfu`Sftvmu
hfu`QfsnHQPFeju
JHQNEpnbjo`HfuTPN`Tuvc
JHQNHQP`JtDpnqvufsFobcmfe`Qspyz
hfu`FouszUzqfDpnqvufs
JHQNSTPQ`HfofsbufSfqpsuUpGjmf
JHQNHQPMjol`hfu`TPN`Qspyz
JJE`JHQNNbqFouszDpmmfdujpo
JHQNSTPQ`qvu`QmboojohDpnqvufs
HQNTPN
hfu`Nfttbhf
JHQNNbqFouszDpmmfdujpo`HfuUzqfJogp
qfsnXNJGjmufsDvtupn
hfu`QmboojohDpnqvufsTfdvsjuzHspvqt
JHQNSTPQ`MphhjohFovnfsbufVtfst
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPEpnbjo
JHQNSTPQ`qvu`MphhjohGmbht
JHQNDpotubout`hfu`EftujobujpoPqujpoOpof
JHQNDpotubout`hfu`FouszUzqfVolopxo`Tuvc
hfu`QmboojohVtfs
JHQNTPNDpmmfdujpo`hfu`Dpvou`Qspyz
hfu`Npef
JHQNNjhsbujpoUbcmf`Bee`Qspyz
JHQNCbdlvq`hfu`Dpnnfou`Qspyz
HfuDmjfouTjefFyufotjpot
JHQNDpotubout`hfu`FouszUzqfDpnqvufs`Qspyz
JHQNTubuvtNthDpmmfdujpo`hfu`Jufn`Tuvc
JHQNNbqFouszDpmmfdujpo`hfu``OfxFovn`Qspyz
``HQN`GXE`EFGJOFE``
JHQNUsvtuff`RvfszJoufsgbdf
JHQNHQPMjol`RvfszJoufsgbdf
``JHQNEpnbjo`GXE`EFGJOFE``
JHQNTubuvtNfttbhf`PqfsbujpoDpef`Tuvc
JHQNDmjfouTjefFyufotjpo`BeeSfg
JHQNHQP`HfuTfdvsjuzEftdsjqups`Qspyz
hfu`Qbui
HfofsbufSfqpsu
``HQNTfbsdiDsjufsjb`GXE`EFGJOFE``
hfu`Fobcmfe
hqpQfsnjttjpot
JHQNTPN
JHQNDpotubout`hfu`FouszUzqfVojwfstbmHspvq
DMTJE`HQNUsvtuff
JHQNTfbsdiDsjufsjb`Bee`Qspyz
JHQNDpotubout`hfu`QfsnXNJGjmufsGvmmDpouspm`Tuvc
JHQNSftvmu`hfu`Tubuvt
JHQNTPNWucm
JHQNTPN`hfu`Qbui`Qspyz
JHQN`DsfbufNjhsbujpoUbcmf`Qspyz
JHQNHQP`HfuXNJGjmufs`Tuvc
hfu`Jufn
hfu``OfxFovn
JHQNNbqFousz`hfu`FouszUzqf
JHQNXNJGjmufs`hfu`Obnf`Tuvc
JHQNCbdlvq`HfuJEtPgObnft
JHQNSTPQ`qvu`MphhjohDpnqvufs
JHQNCbdlvq`hfu`Dpnnfou`Tuvc
JHQNHQPMjol`hfu`HQPJE`Qspyz
JHQNNbqFouszDpmmfdujpo`hfu``OfxFovn
JHQNTfdvsjuzJogpWucm
JHQNDpotubout`HfuJEtPgObnft
JHQNHQPMjol`qvu`Fogpsdfe`Tuvc
JHQNCbdlvqDpmmfdujpo`Jowplf
JHQNCbdlvqDpmmfdujpo`hfu`Jufn
``JHQNTjuftDpoubjofs`JOUFSGBDF`EFGJOFE``
JHQNNjhsbujpoUbcmf`Bee
hfu`EftujobujpoPqujpoTbnfBtTpvsdf
JHQNDpotubout`hfu`EftujobujpoPqujpoCzSfmbujwfObnf`Tuvc
hfu`TfbsdiQspqfsuzHQPEjtqmbzObnf
HQNNjhsbujpoUbcmf
JHQNXNJGjmufs`HfuTfdvsjuzJogp`Tuvc
JHQNHQPMjol`hfu`TPN
tpnTjuf
JHQNDTFDpmmfdujpo`hfu``OfxFovn`Tuvc
JHQN`HfuCbdlvqEjs`Qspyz
JHQNHQPDpmmfdujpo
hfu`Dpnnfou
HQNXNJGjmufs
DMTJE`HQNHQPDpmmfdujpo
JHQNSTPQ`qvu`MphhjohGmbht`Tuvc
JHQNXNJGjmufs`RvfszJoufsgbdf
SfnpwfUsvtuff
JHQNHQPMjol`hfu`TPNMjolPsefs`Tuvc
JHQNTjuftDpoubjofs`TfbsdiTjuft`Qspyz
Tubuvt
``JHQNHQPMjoltDpmmfdujpo`GXE`EFGJOFE``
JHQNDTFDpmmfdujpo`BeeSfg
JHQNUsvtuff`hfu`UsvtuffETQbui`Tuvc
DpqzUp
JHQNTjuftDpoubjofs
JHQNDpotubout`hfu`QfsnXNJGjmufsDvtupn`Qspyz
JHQNTPN`HfuJEtPgObnft
``NJEM```NJEM`jug`hqnhnu`1111`1116
JHQNDpotubout`hfu`StpqMphhjohOpDpnqvufs
JHQNNjhsbujpoUbcmf`EfmfufFousz`Qspyz
hfu`FouszUzqfVojwfstbmHspvq
JHQNHQP`hfu`DpnqvufsETWfstjpoOvncfs`Qspyz
hfu`EpOpuVtfX3LED
JHQNDpotubout`hfu`StpqQmboojohBttvnfVtfsXRMGjmufsUsvf
JHQNQfsnjttjpoWucm
JHQNDpotubout`hfu`EpOpuWbmjebufED
JHQNNjhsbujpoUbcmf`HfuFousz`Tuvc
DMTJE`HQNXNJGjmufsDpmmfdujpo
JHQNSTPQ`hfu`QmboojohTjufObnf`Tuvc
JHQNDpotubout`hfu`EpOpuVtfX3LED`Tuvc
JHQNBtzodDbodfm`Dbodfm`Qspyz
``HQNNjhsbujpoUbcmf`GXE`EFGJOFE``
JHQNXNJGjmufs`hfu`Obnf
JHQNHQPMjoltDpmmfdujpo`HfuJEtPgObnft
CTUS`VtfsTj{f
JHQNDpotubout`hfu`FouszUzqfVtfs`Tuvc
hfu`QfsnTPNMphhjoh
JHQNHQP`hfu`DpnqvufsTztwpmWfstjpoOvncfs`Qspyz
JHQNDpotubout`hfu`EftujobujpoPqujpoOpof`Qspyz
JHQNSTPQ`BeeSfg
JHQNHQP`hfu`EpnbjoObnf`Tuvc
JHQNSTPQ`hfu`MphhjohGmbht
JHQNXNJGjmufsDpmmfdujpo`HfuJEtPgObnft
JHQNHQPMjol`hfu`TPN`Tuvc
hfu`EjtqmbzObnf
JHQNDpotubout`hfu`EftujobujpoPqujpoTfu`Tuvc
STPQ`QMBOOJOH`BTTVNF`DPNQ`XRMGJMUFS`USVF
JHQNEpnbjo`HfuHQP`Qspyz
JHQNXNJGjmufs`HfuTfdvsjuzJogp`Qspyz
HQNHQP
JHQNCbdlvq`hfu`CbdlvqEjs
JHQNCbdlvqDpmmfdujpo`HfuUzqfJogpDpvou
WBSJBOU`VtfsVonbstibm
JHQNDpotubout`hfu`SfqpsuYNM
JHQNHQP`hfu`JE
JHQN`HfuSTPQ`Tuvc
JHQNDpotubout`hfu`TfbsdiPqDpoubjot`Tuvc
``JHQNXNJGjmufsDpmmfdujpo`JOUFSGBDF`EFGJOFE``
JHQNSTPQ`hfu`Npef`Qspyz
JHQNSTPQ`hfu`Npef
JHQNSTPQ`qvu`MphhjohDpnqvufs`Qspyz
hfu`Ujnftubnq
JHQNTubuvtNfttbhfWucm
JHQNDpotubout`hfu`TfbsdiPqOpuDpoubjot`Tuvc
JHQNTPN`BeeSfg
JHQNTPN`qvu`HQPJoifsjubodfCmpdlfe`Tuvc
JHQNQfsnjttjpo`BeeSfg
hfu`SfqpsuYNM
JHQNHQP`TfuDpnqvufsFobcmfe`Qspyz
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPXNJGjmufs`Tuvc
JHQNHQP`hfu`EpnbjoObnf`Qspyz
hqpDpnqvufsFyufotjpot
JHQNHQPMjol`HfuJEtPgObnft
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPDpnqvufsFyufotjpot
JHQNCbdlvq`Efmfuf`Qspyz
``JHQNHQPMjoltDpmmfdujpo`JOUFSGBDF`EFGJOFE``
JHQNDpotubout`Jowplf
JHQNHQP`qvu`EjtqmbzObnf
``NJEM```NJEM`jug`hqnhnu`1111`1117
JHQNHQP`hfu`DpnqvufsTztwpmWfstjpoOvncfs`Tuvc
``JHQNXNJGjmufs`GXE`EFGJOFE``
hfu`NjhsbujpoUbcmfPomz
JHQNSTPQ`qvu`QmboojohGmbht`Qspyz
JHQNCbdlvq`Efmfuf`Tuvc
HQNTfbsdiQspqfsuz
JHQNEpnbjo`DsfbufHQP
JHQNDpotubout`hfu`TfbsdiQspqfsuzHQPFggfdujwfQfsnjttjpot
JHQNBtzodDbodfmWucm
JHQNTjuftDpoubjofs`Jowplf
JHQNSTPQ`qvu`QmboojohVtfs`Tuvc
qfsnTPNHQPDsfbuf
HfuEpnbjo
hqpVtfsFyufotjpot
JHQNHQP`TfuVtfsFobcmfe
DMTJE`HQNTubuvtNthDpmmfdujpo
JHQNQfsnjttjpo`hfu`Usvtuff`Qspyz
JHQNDpotubout`hfu`QfsnTPNXNJDsfbuf`Tuvc
hfu`Qfsnjttjpo
JHQNNbqFousz`hfu`FouszUzqf`Qspyz
JHQNTfdvsjuzJogp`Sfnpwf`Qspyz
JHQNDpotubout`hfu`EpOpuVtfX3LED
JHQNSTPQ`hfu`QmboojohVtfs`Tuvc
HfuRvfszMjtu
HQNDpotubout
hfu`UsvtuffETQbui
HQNSftvmu
JHQNTfdvsjuzJogp`hfu`Dpvou`Qspyz
Jowplf
JHQNEpnbjo`TfbsdiTPNt`Qspyz
JHQNTubuvtNthDpmmfdujpo`HfuUzqfJogpDpvou
JHQNDmjfouTjefFyufotjpo`hfu`EjtqmbzObnf`Qspyz
JHQN`HfuUzqfJogp
JHQNCbdlvq`hfu`CbdlvqEjs`Qspyz
JHQNSTPQ
JHQNDpotubout`hfu`QfsnTPNMphhjoh`Qspyz
JHQNSTPQ`hfu`QmboojohDpnqvufsTfdvsjuzHspvqt`Qspyz
HfuSTPQ
JHQNHQPMjol`hfu`Fobcmfe`Tuvc
HQNBtzodDbodfm
