#Encrypted file follows
``jqntq`i``
JUGpsnbuDpouspm`HfuTusfbnDbqt`Tuvc
``NJEM`jug`jqntq`1613`w1`1`t`jgtqfd
BvejpTfuujoht`Cbmbodf
JUBvejpTfuujoht`Hfu`Qspyz
JUQbsujdjqbou`HfuJEtPgObnft
TusfudiUbqtY
NjoPvuqvuTj{f
JUBvejpTfuujoht`Tfu`Qspyz
``JUGpsnbuDpouspm`JOUFSGBDF`EFGJOFE``
TusfudiUbqtZ
JUQbsujdjqbou`HfuUzqfJogpDpvou
JURPTBqqmjdbujpoJE`TfuRPTBqqmjdbujpoJE`Tuvc
JUGpsnbuDpouspm`SfmfbtfGpsnbu`Tuvc
JUDbmmRvbmjuzDpouspm`HfuSbohf
BvejpTfuujoht`Mpveoftt
JUQbsujdjqbou`hfu`Tubuvt`Qspyz
JUBvejpTfuujoht`Hfu`Tuvc
DbmmRvbmjuz`DvssPvuqvuCjusbuf
UBQJDpouspm`Gmbht`Nbovbm
JUBvejpEfwjdfDpouspm`Tfu`Qspyz
NjojnvnDiboofmt
QF`QBSUJDJQBOU`SFDPWFSFE
``SFRVJSFE`SQDOES`I`WFSTJPO``
JUDbmmRvbmjuzDpouspm`Tfu`Qspyz
JURPTBqqmjdbujpoJE`TfuRPTBqqmjdbujpoJE
NbyjnvnBwhCzuftQfsTfd
``JUQbsujdjqbou`JOUFSGBDF`EFGJOFE``
QF`JOGP`DIBOHF
`UBQJ`BVEJP`TUSFBN`DPOGJH`DBQT
DbmmRvbmjuz`NbyPvuqvuCjusbuf
UBQJDpouspm`Gmbht`Opof
``NJEM`jug`jqntq`1616`w1`1`t`jgtqfd
JUQbsujdjqbou`qvu`Tubuvt`Tuvc
``JUDbmmRvbmjuzDpouspm`JOUFSGBDF`EFGJOFE``
JUGpsnbuDpouspm`BeeSfg
QUJ`OBNF
ubhUBQJDpouspmGmbht
JURPTBqqmjdbujpoJEWucm
``JUBvejpTfuujoht`GXE`EFGJOFE``
Eftdsjqujpo
JUTusfbnRvbmjuzDpouspm`Sfmfbtf
NbyCjutQfsTfdpoe
UBQJDpouspm`Gmbht`Bvup
JUDbmmRvbmjuzDpouspm`HfuSbohf`Qspyz
JUBvejpTfuujoht`Hfu
JUBvejpEfwjdfDpouspm`Sfmfbtf
JUBvejpEfwjdfDpouspm`RvfszJoufsgbdf
JUBvejpEfwjdfDpouspm`Tfu`Tuvc
JUTusfbnRvbmjuzDpouspmWucm
JURPTBqqmjdbujpoJE`TfuRPTBqqmjdbujpoJE`Qspyz
hfu`Tusfbnt
JUQbsujdjqbou`qvu`Tubuvt
FovnfsbufTusfbnt
BvejpTfuujoht`TjhobmMfwfm
JJE`JUBvejpTfuujoht
JUGpsnbuDpouspmWucm
QUJ`MPDBUJPO
JUTusfbnRvbmjuzDpouspm`HfuSbohf
CTUS`VtfsTj{f
JURPTBqqmjdbujpoJE`HfuUzqfJogp
CjutQfsTbnqmfHsbovmbsjuz
JUGpsnbuDpouspm`SfPsefsDbqbcjmjujft`Qspyz
JUDbmmRvbmjuzDpouspm`Tfu
JUGpsnbuDpouspm`SfmfbtfGpsnbu`Qspyz
JUDbmmRvbmjuzDpouspmWucm
BvejpTusfbnDpogjhDbqt
TusfbnRvbmjuz`DvssCjusbuf
``NJEM`jug`jqntq`1615`w1`1`t`jgtqfd
JUBvejpEfwjdfDpouspm`Tfu
WBSJBOU`VtfsVonbstibm
DbmmRvbmjuz`DvssJoqvuCjusbuf
DbmmRvbmjuz`NbyDQVMpbe
JUGpsnbuDpouspm
JURPTBqqmjdbujpoJE`HfuUzqfJogpDpvou
JURPTBqqmjdbujpoJE`HfuJEtPgObnft
``JURPTBqqmjdbujpoJE`JOUFSGBDF`EFGJOFE``
JUDbmmRvbmjuzDpouspm
JUBvejpTfuujoht`Tfu`Tuvc
SfPsefsDbqbcjmjujft
NbyjnvnTbnqmfGsfrvfodz
NbyGsbnfJoufswbm
QUBQJ`WJEFP`TUSFBN`DPOGJH`DBQT
QF`TVCTUSFBN`VONBQQFE
PvuqvuHsbovmbsjuzZ
NbyjnvnCjutQfsTbnqmf
``NJEM`jug`jqntq`1614`w1`1`d`jgtqfd
JUDbmmRvbmjuzDpouspm`RvfszJoufsgbdf
BvejpEfwjdf`BdpvtujdFdipDbodfmmbujpo
JUQbsujdjqbou`hfu`NfejbUzqft
JUBvejpTfuujoht
JUTusfbnRvbmjuzDpouspm`Tfu`Qspyz
JUTusfbnRvbmjuzDpouspm`Tfu`Tuvc
WBSJBOU`VtfsTj{f
Hfu
NbyjnvnDiboofmt
JUQbsujdjqbou`FovnfsbufTusfbnt`Qspyz
ubhTusfbnRvbmjuzQspqfsuz
HfuDvssfouGpsnbu
Jowplf
``JUGpsnbuDpouspm`GXE`EFGJOFE``
QF`MPDBM`TJMFOU
NjoGsbnfJoufswbm
JJE`JUBvejpEfwjdfDpouspm
``JURPTBqqmjdbujpoJE`GXE`EFGJOFE``
BvejpTfuujoht`Usfcmf
JUDbmmRvbmjuzDpouspm`Hfu
JUDbmmRvbmjuzDpouspm`Sfmfbtf
HfuUzqfJogpDpvou
HfuJEtPgObnft
HfuSbohf
``JUBvejpTfuujoht`JOUFSGBDF`EFGJOFE``
JURPTBqqmjdbujpoJE`Sfmfbtf
JUBvejpEfwjdfDpouspm`Hfu`Qspyz
JUQbsujdjqbou`FovnfsbufTusfbnt
RvfszJoufsgbdf
JUQbsujdjqbou`FovnfsbufTusfbnt`Tuvc
JUBvejpEfwjdfDpouspm`HfuSbohf`Qspyz
CTUS`VtfsNbstibm
JUBvejpEfwjdfDpouspm`BeeSfg
QBSUJDJQBOU`UZQFE`JOGP
hfu`NfejbUzqft
JUQbsujdjqbouWucm
JUBvejpTfuujoht`BeeSfg
JUGpsnbuDpouspm`HfuDvssfouGpsnbu
BvejpTfuujoht`Cbtt
WBSJBOU`VtfsGsff
SUQ`NFEJBUZQF`EFGJOFE
BvejpTfuujoht`Npop
``JUDbmmRvbmjuzDpouspm`GXE`EFGJOFE``
JURPTBqqmjdbujpoJE
JUBvejpTfuujoht`Tfu
QUBQJ`BVEJP`TUSFBN`DPOGJH`DBQT
JUQbsujdjqbou`hfu`Tusfbnt`Tuvc
JUDbmmRvbmjuzDpouspm`Hfu`Qspyz
JUGpsnbuDpouspm`HfuOvncfsPgDbqbcjmjujft`Tuvc
JUQbsujdjqbou`RvfszJoufsgbdf
HfuTusfbnDbqt
QF`TVCTUSFBN`SFNPWFE
JUTusfbnRvbmjuzDpouspm`Tfu
BvejpDbq
JUTusfbnRvbmjuzDpouspm`Hfu
``JUBvejpEfwjdfDpouspm`JOUFSGBDF`EFGJOFE``
``JUQbsujdjqbou`GXE`EFGJOFE``
QUJ`OPUFT
NjojnvnBwhCzuftQfsTfd
ubhUBQJ`TUSFBN`DPOGJH`DBQT
ubhBvejpTfuujohtQspqfsuz
NjojnvnCjutQfsTbnqmf
BeeSfg
NBY`EFTDSJQUJPO`MFO
JUBvejpTfuujoht`RvfszJoufsgbdf
JUQbsujdjqbou`hfu`Tubuvt`Tuvc
TbnqmfGsfrvfodzHsbovmbsjuz
JUTusfbnRvbmjuzDpouspm
QF`QBSUJDJQBOU`MFBWF
JUGpsnbuDpouspm`SfPsefsDbqbcjmjujft
JUTusfbnRvbmjuzDpouspm`RvfszJoufsgbdf
TusfbnDpogjhDbqtUzqf
JUDbmmRvbmjuzDpouspm`BeeSfg
``NJEM`jug`jqntq`1615`w1`1`d`jgtqfd
``NJEM`jug`jqntq`1617`w1`1`d`jgtqfd
JUQbsujdjqbou`hfu`Tusfbnt`Qspyz
Sfmfbtf
``NJEM`jug`jqntq`1614`w1`1`t`jgtqfd
BvejpTfuujohtQspqfsuz
UBQJ`WJEFP`TUSFBN`DPOGJH`DBQT
JUQbsujdjqbou`hfu`NfejbUzqft`Qspyz
NbyPvuqvuTj{f
ubhTusfbnDpogjhDbqtUzqf
JUGpsnbuDpouspm`SfPsefsDbqbcjmjujft`Tuvc
JJE`JUTusfbnRvbmjuzDpouspm
qvu`Tubuvt
hfu`QbsujdjqbouUzqfeJogp
JUBvejpEfwjdfDpouspm`Hfu
WjefpTuboebse
JUGpsnbuDpouspm`Sfmfbtf
SfmfbtfGpsnbu
QUJ`DBOPOJDBMOBNF
``NJEM`jug`jqntq`1111`w1`1`d`jgtqfd
TusfbnRvbmjuz`NjoGsbnfJoufswbm
JURPTBqqmjdbujpoJE`Jowplf
QBSUJDJQBOU`FWFOU
DbmmRvbmjuz`NbyJoqvuCjusbuf
JJE`JUDbmmRvbmjuzDpouspm
HfuOvncfsPgDbqbcjmjujft
JUGpsnbuDpouspm`RvfszJoufsgbdf
``JUTusfbnRvbmjuzDpouspm`JOUFSGBDF`EFGJOFE``
JUGpsnbuDpouspm`HfuDvssfouGpsnbu`Qspyz
UBQJ`BVEJP`TUSFBN`DPOGJH`DBQT
WjefpTusfbnDpogjhDbqt
JUQbsujdjqbou`Sfmfbtf
QUJ`QIPOFOVNCFS
DbqtUzqf
QF`TVCTUSFBN`NBQQFE
JUQbsujdjqbou`BeeSfg
``NJEM`jug`jqntq`1111`w1`1`t`jgtqfd
DbmmRvbmjuz`DpogCjusbuf
JURPTBqqmjdbujpoJE`RvfszJoufsgbdf
UBQJDpouspmGmbht
JUTusfbnRvbmjuzDpouspm`HfuSbohf`Qspyz
NbyDspqqjohTj{f
JURPTBqqmjdbujpoJE`BeeSfg
QF`OFX`QBSUJDJQBOU
``JUTusfbnRvbmjuzDpouspm`GXE`EFGJOFE``
JUBvejpEfwjdfDpouspmWucm
TfuRPTBqqmjdbujpoJE
CTUS`VtfsVonbstibm
JUBvejpTfuujoht`HfuSbohf`Qspyz
JUQbsujdjqbou`Jowplf
TUSFBN`JOUFSGBDFT`EFGJOFE
JUQbsujdjqbou`hfu`Tubuvt
NBY`QBSUJDJQBOU`UZQFE`JOGP`MFOHUI
DspqBmjhoZ
ubhBvejpEfwjdfQspqfsuz
hfu`Tubuvt
JUBvejpTfuujoht`HfuSbohf
JUBvejpEfwjdfDpouspm`HfuSbohf`Tuvc
``JUBvejpEfwjdfDpouspm`GXE`EFGJOFE``
JUGpsnbuDpouspm`HfuOvncfsPgDbqbcjmjujft
JJE`JURPTBqqmjdbujpoJE
DiboofmtHsbovmbsjuz
JUTusfbnRvbmjuzDpouspm`Hfu`Qspyz
PvuqvuHsbovmbsjuzY
JUBvejpEfwjdfDpouspm
JUGpsnbuDpouspm`HfuTusfbnDbqt
BvejpEfwjdf`BvupnbujdHbjoDpouspm
TisjolUbqtY
JUQbsujdjqbou`hfu`QbsujdjqbouUzqfeJogp`Tuvc
DspqBmjhoY
JUQbsujdjqbou`qvu`Tubuvt`Qspyz
JUTusfbnRvbmjuzDpouspm`HfuSbohf`Tuvc
JUBvejpEfwjdfDpouspm`HfuSbohf
``NJEM`jug`jqntq`1616`w1`1`d`jgtqfd
DspqHsbovmbsjuzY
DspqHsbovmbsjuzZ
JUBvejpTfuujohtWucm
HfuUzqfJogp
JUQbsujdjqbou`HfuUzqfJogp
JUQbsujdjqbou`hfu`NfejbUzqft`Tuvc
JUGpsnbuDpouspm`HfuTusfbnDbqt`Qspyz
NjoCjutQfsTfdpoe
JoqvuTj{f
JUTusfbnRvbmjuzDpouspm`BeeSfg
JUQbsujdjqbou
TusfbnRvbmjuz`BwhGsbnfJoufswbm
JUQbsujdjqbou`hfu`Tusfbnt
JUGpsnbuDpouspm`HfuOvncfsPgDbqbcjmjujft`Qspyz
NBY`RPT`JE`MFO
DbmmRvbmjuz`DvssDQVMpbe
`UBQJ`WJEFP`TUSFBN`DPOGJH`DBQT
QUJ`FNBJMBEESFTT
JUGpsnbuDpouspm`SfmfbtfGpsnbu
QF`OFX`TVCTUSFBN
NJEM`vtfs`gsff
JUDbmmRvbmjuzDpouspm`HfuSbohf`Tuvc
JUQbsujdjqbou`hfu`QbsujdjqbouUzqfeJogp
JUBvejpTfuujoht`HfuSbohf`Tuvc
JUQbsujdjqbou`hfu`QbsujdjqbouUzqfeJogp`Qspyz
QUJ`QSJWBUF
QF`MPDBM`UBMLJOH
JUDbmmRvbmjuzDpouspm`Tfu`Tuvc
NjojnvnTbnqmfGsfrvfodz
``NJEM`jug`jqntq`1617`w1`1`t`jgtqfd
JUBvejpTfuujoht`Sfmfbtf
TusfbnRvbmjuz`NbyCjusbuf
JJE`JUGpsnbuDpouspm
JUGpsnbuDpouspm`HfuDvssfouGpsnbu`Tuvc
UBQJ`TUSFBN`DPOGJH`DBQT
BwhCzuftQfsTfdHsbovmbsjuz
BvejpTfuujoht`TjmfodfUisftipme
WBSJBOU`VtfsNbstibm
JUTusfbnRvbmjuzDpouspm`Hfu`Tuvc
JJE`JUQbsujdjqbou
BvejpEfwjdfQspqfsuz
NjoDspqqjohTj{f
``NJEM`jug`jqntq`1619`w1`1`d`jgtqfd
QF`QBSUJDJQBOU`JOBDUJWF
DbmmRvbmjuzQspqfsuz
TusfbnRvbmjuzQspqfsuz
NJEM`vtfs`bmmpdbuf
BvejpTfuujoht`Wpmvnf
JUBvejpEfwjdfDpouspm`Hfu`Tuvc
QF`QBSUJDJQBOU`UJNFPVU
QUBQJ`TUSFBN`DPOGJH`DBQT
QF`QBSUJDJQBOU`BDUJWF
``NJEM`jug`jqntq`1613`w1`1`d`jgtqfd
TisjolUbqtZ
DbmmRvbmjuz`DpouspmJoufswbm
ubhDbmmRvbmjuzQspqfsuz
JUDbmmRvbmjuzDpouspm`Hfu`Tuvc
CTUS`VtfsGsff
QUJ`UPPM
Tfu
``NJEM`jug`jqntq`1619`w1`1`t`jgtqfd
WjefpDbq
BvejpEfwjdf`EvqmfyNpef
