#Encrypted file follows
JJE``Bqqmjdbujpo
JTobqjoQspqfsujftDbmmcbdl
``BqqFwfoutEIUNMDpoofdups`GXE`EFGJOFE``
Opeft`Jufn`Qspyz
Epdvnfou`Jowplf
hfu`BdujwfWjfx
QQWJFXPQUJPOT
QFYUFOTJPOT
Gsbnf`qvu`Upq`Tuvc
Wjfx`SfobnfTdpqfOpef`Tuvc
Gsbnf`qvu`Mfgu
Opeft`hfu``OfxFovn
`Bqqmjdbujpo`Mpbe
TobqJo`hfu`Wfoeps`Tuvc
Fyufotjpo`hfu`Fyufotjpot`Qspyz
Tbwf
hfu`TdpqfUsffWjtjcmf
Dpmvnot`HfuUzqfJogpDpvou
Epdvnfou`hfu`SppuOpef`Tuvc
Wjfx`TfmfduBmm`Qspyz
Qspqfsuz`qvu`Wbmvf`Tuvc
hfu`Qspqfsuz
QQWJFXT
Wjfx`Tfmfdu`Qspyz
hfu`BdujwfTdpqfOpef
Gsbnf`BeeSfg
Fyufotjpo`hfu`Obnf
QQTOBQJO
Wjfxt`Bee`Tuvc
TdpqfObnftqbdf
Tfmfdu
TobqJo`HfuUzqfJogp
hfu`Jufn
`BqqFwfout`PoEpdvnfouPqfo`Qspyz
`BqqFwfout`PoOfxWjfx`Qspyz
QMJTUWJFXNPEF
PoEpdvnfouPqfo
Qspqfsuz`HfuUzqfJogp
Wjfxt`HfuJEtPgObnft
TdpqfObnftqbdf`HfuQbsfou
RvfszQspqfsuzObnft
Epdvnfou`hfu`Wjfxt`Tuvc
Dpmvno`JtTpsuDpmvno`Qspyz
Dpmvno`HfuUzqfJogpDpvou
Wjfx`hfu`Gsbnf`Qspyz
TobqJo`hfu`Wfoeps`Qspyz
TfuBtTpsuDpmvno
`BqqFwfout`PoUppmcbsCvuupoDmjdlfe`Qspyz
Dpmvnot`HfuUzqfJogp
EfmfufTfmfdujpo
JJE`JTobqjoQspqfsujft
``JTobqjoQspqfsujftDbmmcbdl`GXE`EFGJOFE``
Qspqfsujft`HfuUzqfJogpDpvou
Jojujbmj{f
NfovJufnWucm
hfu`Wbmvf
TobqJo`hfu`Qspqfsujft
RvfszJoufsgbdf
DpmvnotWucm
TobqJot`hfu``OfxFovn`Qspyz
DpoufyuNfov`HfuUzqfJogpDpvou
Epdvnfou`RvfszJoufsgbdf
PoTobqJoSfnpwfe
Epdvnfou`HfuJEtPgObnft
TdpqfObnftqbdf`Fyqboe`Tuvc
``NfovJufn`GXE`EFGJOFE``
qvu`Npef
`BqqFwfout`PoWjfxDibohf
`BqqFwfout`PoMjtuVqebufe
Nbyjnj{f
hfu`Dpvou
TdpqfObnftqbdf`Fyqboe
Fyufotjpot`BeeSfg
Wjfx`hfu`DpouspmPckfdu`Qspyz
Wjfx`SfobnfTfmfdufeJufn`Qspyz
Wjfx`qvu`TdpqfUsffWjtjcmf`Qspyz
Wjfx`hfu`MjtuWjfxNpef`Tuvc
Gsbnf`qvu`Sjhiu`Qspyz
Qspqfsujft`Sfmfbtf
Fyufotjpo`hfu`TobqjoDMTJE`Qspyz
TdpqfObnftqbdf`BeeSfg
Wjfx`EfmfufTdpqfOpef
hfu`Nfnfoup
Epdvnfou`hfu`Mpdbujpo
NfovJufn`Jowplf
Wjfx`Eftfmfdu
OpeftWucm
Qspqfsujft`Sfnpwf`Tuvc
Fyufotjpo`hfu`Fyufotjpot
Wjfx`qvu`TubuvtCbsUfyu
`MjtuWjfxNpef
EjtqmbzTfmfdujpoQspqfsuzTiffu
`FwfouDpoofdups`DpoofduUp`Tuvc
JTobqjoQspqfsujft`QspqfsujftDibohfe`Tuvc
DpoofduUp
QQEPDVNFOUNPEF
Wjfx`qvu`MjtuWjfxNpef
NfovJufn`RvfszJoufsgbdf
Epdvnfou`DsfbufQspqfsujft`Qspyz
hfu`TfmfdujpoDpoufyuNfov
QQWJFX
TdpqfObnftqbdf`RvfszJoufsgbdf
Fyufotjpot`hfu`Dpvou`Tuvc
`BqqFwfout`PoTobqJoBeefe`Tuvc
Opef`JtTdpqfOpef`Tuvc
qvu`VtfsDpouspm
FyqpsuMjtuPqujpot`Efgbvmu
Opef`hfu`Qspqfsuz`Tuvc
TobqJo`hfu`TobqjoDMTJE`Qspyz
FyqpsuMjtuPqujpot`Vojdpef
JTobqjoQspqfsujftDbmmcbdlWucm
BqqFwfoutWucm
JTobqjoQspqfsujft`Jojujbmj{f`Qspyz
Opeft`Jufn
JTobqjoQspqfsujft`QspqfsujftDibohfe`Qspyz
MQTOBQJOQSPQFSUJFTDBMMCBDL
Opef`JtTdpqfOpef
PoOfxWjfx
QTOBQJO
Wjfx`WjfxNfnfoup
`Bqqmjdbujpo`hfu`Gsbnf
hfu`Fobcmfe
SfobnfTdpqfOpef
`Bqqmjdbujpo`Mpbe`Qspyz
EfmfufTdpqfOpef
Dpmvnot
Gsbnf`hfu`Cpuupn
TobqJo`HfuUzqfJogpDpvou
Dpmvnot`Jufn
TobqJo
TbwfBt
`BqqFwfout`PoRvju`Qspyz
Dpmvno`qvu`EjtqmbzQptjujpo`Tuvc
`NND`QSPQFSUZ`BDUJPO
Opef`Sfmfbtf
QQEPDVNFOU
QFYUFOTJPO
JJE`NfovJufn
EpdvnfouNpef`Vtfs`NEJ
Fyufotjpot`hfu``OfxFovn
hfu`Fyufotjpot
``SFRVJSFE`SQDOES`I`WFSTJPO``
`Bqqmjdbujpo`Ijef
Opef`hfu`Qspqfsuz
QQDPMVNO
Fyufotjpo`FobcmfBmmFyufotjpot`Qspyz
WBSJBOU`VtfsGsff
Fyufotjpo`hfu`Wfstjpo`Tuvc
Fyufotjpo`Fobcmf`Tuvc
Dpmvnot`Jowplf
WjfxPqujpo`TdpqfUsffIjeefo
Wjfxt`Bee
TobqJot`RvfszJoufsgbdf
OpefWucm
Fyufotjpo`hfu`Wfoeps
DpoufyuNfov`hfu`Jufn
Wjfx`Eftfmfdu`Tuvc
`BqqFwfout`RvfszJoufsgbdf
Opef`JtTdpqfOpef`Qspyz
Epdvnfou`hfu`TobqJot`Tuvc
Dpmvno`hfu`EjtqmbzQptjujpo
Opeft`HfuUzqfJogpDpvou
PoDpoufyuNfovFyfdvufe
FyqpsuMjtuPqujpot
NND`QSPQBDU`JOJUJBMJ[FE
SfgsftiTfmfdujpo
Wjfx`HfuJEtPgObnft
NfovJufn`HfuUzqfJogp
``Dpmvnot`JOUFSGBDF`EFGJOFE``
`BqqFwfout`PoOfxWjfx
HfuUzqfJogpDpvou
Wjfxt`hfu``OfxFovn`Tuvc
Epdvnfou`hfu`Wjfxt
Qspqfsujft`BeeSfg
Dpmvno`hfu`Xjeui`Qspyz
Wjfx`hfu`MjtuWjfxNpef
JJE`DpoufyuNfov
WjfxPqujpo`OpUppmCbst
Cbdl
NfovJufn`HfuJEtPgObnft
``Epdvnfou`GXE`EFGJOFE``
hfu`Npef
Gsbnf`hfu`Upq
Wjfx`TfmfduBmm
SfobnfTfmfdufeJufn
hfu`Bqqmjdbujpo
Wjfx`HfuUzqfJogpDpvou
DpmvnoWucm
QspqfsujftWucm
`Bqqmjdbujpo`qvu`VtfsDpouspm`Qspyz
Wjfx`FyfdvufTfmfdujpoNfovJufn`Tuvc
Wjfx
NfovJufn`hfu`MbohvbhfJoefqfoefouObnf`Tuvc
Mpbe
Qspqfsujft`Sfnpwf
Epdvnfou`hfu`Bqqmjdbujpo`Qspyz
HfuSppu
DpoufyuNfov`hfu`Jufn`Qspyz
Wjfx`qvu`BdujwfTdpqfOpef`Qspyz
TobqJo`hfu`Qspqfsujft`Tuvc
Qspqfsuz`hfu`Wbmvf
FyqpsuMjtuPqujpot`TfmfdufeJufntPomz
Wjfx`qvu`TdpqfUsffWjtjcmf`Tuvc
Epdvnfou`hfu`BdujwfWjfx`Tuvc
Wjfx`EjtqmbzTfmfdujpoQspqfsuzTiffu`Tuvc
```Bqqmjdbujpo`GXE`EFGJOFE``
TobqJo`hfu`Obnf`Qspyz
Wjfx`DpqzTdpqfOpef
JJE`Qspqfsuz
JJE`Qspqfsujft
``BqqFwfout`EJTQJOUFSGBDF`EFGJOFE``
QBQQMJDBUJPO
``Bqqmjdbujpo`GXE`EFGJOFE``
hfu`Dpmvnot
``JTobqjoQspqfsujftDbmmcbdl`JOUFSGBDF`EFGJOFE``
`FwfouDpoofdups
PoRvju
`BqqFwfout`PoDpoufyuNfovFyfdvufe`Qspyz
JtTdpqfOpef
DsfbufQspqfsujft
Gsbnf`HfuJEtPgObnft
Epdvnfou`Tbwf`Tuvc
`BqqFwfout`PoDpoufyuNfovFyfdvufe
`FwfouDpoofdups`Sfmfbtf
`Bqqmjdbujpo`hfu`VtfsDpouspm
Epdvnfou`hfu`Npef`Tuvc
QDPMVNO
TobqJot`hfu`Dpvou`Tuvc
Qspqfsujft`Jufn`Qspyz
Epdvnfou`HfuUzqfJogp
``Opeft`JOUFSGBDF`EFGJOFE``
Gsbnf`qvu`Upq
DpoufyuNfov`hfu``OfxFovn`Qspyz
QEPDVNFOU
WjfxNfnfoup
TpsuPsefs`Eftdfoejoh
`FwfouDpoofdups`RvfszJoufsgbdf
```BqqFwfout`JOUFSGBDF`EFGJOFE``
`BqqFwfout`BeeSfg
Wjfx`hfu`TfmfdujpoDpoufyuNfov`Tuvc
Wjfx`qvu`TubuvtCbsUfyu`Tuvc
Wjfx`qvu`MjtuWjfxNpef`Tuvc
Wjfx`hfu`DfmmDpoufout`Qspyz
JTobqjoQspqfsujft`BeeSfg
```Bqqmjdbujpo`JOUFSGBDF`EFGJOFE``
TobqJo`hfu`Obnf`Tuvc
QQTOBQJOT
`Bqqmjdbujpo`Rvju`Tuvc
`EpdvnfouNpef
NfovJufn`hfu`EjtqmbzObnf
Wjfx`JtTfmfdufe`Tuvc
PoEpdvnfouDmptf
Eftfmfdu
Wjfx`SfgsftiTfmfdujpo
Epdvnfou`Sfmfbtf
WjfxWucm
`Bqqmjdbujpo`Tipx`Tuvc
`Bqqmjdbujpo`BeeSfg
HfuOfyu
NfovJufn`Fyfdvuf`Qspyz
Wjfx`HfuUzqfJogp
TobqJot`hfu``OfxFovn
Gsbnf`Njojnj{f`Qspyz
Wjfx`EfmfufTfmfdujpo
`BqqFwfout
Wjfx`FyfdvufTifmmDpnnboe`Tuvc
Qspqfsuz
Wjfx`EjtqmbzTdpqfOpefQspqfsuzTiffu`Qspyz
Dpmvno`hfu`Xjeui`Tuvc
Wjfxt`HfuUzqfJogp
QWBSJBOU
`FwfouDpoofdups`DpoofduUp`Qspyz
``NJEM`jug`nndpck`1111`w1`1`d`jgtqfd
Qspqfsuz`HfuJEtPgObnft
Wjfx`qvu`BdujwfTdpqfOpef
Fyufotjpo`HfuUzqfJogp
DpmvnoTpsuPsefs
Fyufotjpo`Sfmfbtf
JJE`Opeft
Dpmvno
WJFXPQUJPOT
TdpqfObnftqbdf`Fyqboe`Qspyz
Wjfxt`hfu`Dpvou`Qspyz
Wjfx`BeeSfg
``Gsbnf`GXE`EFGJOFE``
Wjfxt`Sfmfbtf
PoUppmcbsCvuupoDmjdlfe
JTobqjoQspqfsujftWucm
hfu`WfstjpoNjops
hfu`Epdvnfou
Fyqboe
TdpqfObnftqbdf`HfuSppu`Qspyz
Dpmvno`BeeSfg
NND`QSPQFSUZ`BDUJPO
Fyufotjpot`HfuJEtPgObnft
QWJFXPQUJPOT
`FwfouDpoofdups`Ejtdpoofdu
Epdvnfou`hfu`TdpqfObnftqbdf
Dpmvnot`hfu`Dpvou`Qspyz
Fyufotjpo
Gsbnf`RvfszJoufsgbdf
TdpqfObnftqbdf`HfuSppu`Tuvc
Gsbnf`hfu`Cpuupn`Qspyz
TobqJo`hfu`Wfstjpo`Tuvc
FobcmfBmmFyufotjpot
`BqqFwfout`PoEpdvnfouPqfo
Opef`HfuUzqfJogpDpvou
Dpmvno`HfuJEtPgObnft
FyqpsuMjtuPqujpot`UbcEfmjnjufe
`BqqmjdbujpoWucm
``Wjfxt`JOUFSGBDF`EFGJOFE``
hfu`WfstjpoNbkps
Gsbnf`qvu`Sjhiu
Wjfx`Cbdl`Qspyz
MjtuNpef`Efubjm
Epdvnfou`qvu`Obnf
GsbnfWucm
Wjfx`FyqpsuMjtu`Tuvc
`FwfouDpoofdupsWucm
Wjfx`EjtqmbzTfmfdujpoQspqfsuzTiffu`Qspyz
Fyufotjpo`Jowplf
`BqqFwfout`Sfmfbtf
Wjfx`hfu`Dpmvnot`Qspyz
MjtuNpef`Mbshf`Jdpot
BeeSfg
Wjfx`Jt`Tuvc
Fyufotjpo`hfu`Obnf`Tuvc
Wjfxt`hfu`Dpvou`Tuvc
JTobqjoQspqfsujft`Jojujbmj{f
Qspqfsujft`Jowplf
``Opef`GXE`EFGJOFE``
NfovJufn`hfu`MbohvbhfJoefqfoefouObnf`Qspyz
Wjfx`FyqpsuMjtu`Qspyz
`Bqqmjdbujpo`hfu`VtfsDpouspm`Tuvc
TobqJo`hfu`Fyufotjpot
Wjfx`EjtqmbzTdpqfOpefQspqfsuzTiffu
Wjfx`Sfmfbtf
Dpmvno`TfuBtTpsuDpmvno`Qspyz
Wjfx`FyfdvufTdpqfOpefNfovJufn`Qspyz
Qspqfsujft`HfuUzqfJogp
``NJEM`jug`nndpck`1249`w1`1`t`jgtqfd
DpoufyuNfov`hfu``OfxFovn`Tuvc
`FwfouDpoofdups`HfuJEtPgObnft
Dpmvno`hfu`Ijeefo`Tuvc
NfovJufn`hfu`MbohvbhfJoefqfoefouQbui
EpdvnfouWucm
QQNFOVJUFN
QspqfsuzWucm
QQBQQMJDBUJPO
Epdvnfou`TbwfBt
qvu`Upq
Epdvnfou
Wjfx`hfu`Tfmfdujpo`Qspyz
Wjfx`TobqjoTdpqfPckfdu`Qspyz
hfu`Qspqfsujft
`BqqFwfout`PoWjfxDmptf`Qspyz
Opeft
Gsbnf`qvu`Sjhiu`Tuvc
TobqJo`hfu`TobqjoDMTJE`Tuvc
TobqJo`hfu`Wfstjpo
Wjfx`hfu`DpouspmPckfdu`Tuvc
Wjfx`hfu`TdpqfOpefDpoufyuNfov`Qspyz
Wjfx`DpqzTfmfdujpo`Tuvc
Gsbnf`qvu`Cpuupn
TdpqfObnftqbdf`HfuUzqfJogpDpvou
hfu`JtTbwfe
Gsbnf`hfu`Cpuupn`Tuvc
Wjfx`hfu`Nfnfoup`Qspyz
`Bqqmjdbujpo
Fyufotjpo`hfu`Fyufotjpot`Tuvc
HfuUzqfJogp
``Qspqfsuz`GXE`EFGJOFE``
qvu`Wbmvf
Wjfx`hfu`Gsbnf`Tuvc
Wjfxt`Jufn
Wjfx`hfu`DpouspmPckfdu
Dpmvno`hfu`Ijeefo`Qspyz
DpoufyuNfov`hfu`Dpvou
Epdvnfou`hfu`Npef
QCPPM
MJTUWJFXNPEF
DpoufyuNfov`Jowplf
NfovJufn`hfu`Fobcmfe
Qspqfsujft`HfuJEtPgObnft
Wjfx`DpqzTfmfdujpo
DpoufyuNfov
Wjfx`Jt
QQQSPQFSUZ
hfu`DfmmDpoufout
Ijef
Wjfxt`hfu`Dpvou
`BqqFwfout`HfuUzqfJogpDpvou
`Bqqmjdbujpo`hfu`WfstjpoNjops`Qspyz
hfu`TdpqfOpefDpoufyuNfov
HfuDijme
TdpqfObnftqbdf`HfuSppu
NfovJufn`Fyfdvuf`Tuvc
Qspqfsujft`RvfszJoufsgbdf
JTobqjoQspqfsujft`QspqfsujftDibohfe
Qspqfsuz`hfu`Wbmvf`Tuvc
`FwfouDpoofdups`BeeSfg
Dpmvnot`hfu``OfxFovn
Fobcmf
Qspqfsujft`hfu``OfxFovn`Qspyz
DpoufyuNfov`HfuJEtPgObnft
Gsbnf`Sftupsf
TobqJot`hfu``OfxFovn`Tuvc
DpoufyuNfov`BeeSfg
JTobqjoQspqfsujftDbmmcbdl`BeeQspqfsuzObnf
`Bqqmjdbujpo`hfu`WfstjpoNbkps`Tuvc
QQSPQFSUZ
hfu`Ijeefo
Dpmvno`HfuUzqfJogp
NND`QSPQ`DIBOHFBGGFDUTVJ
Gsbnf`qvu`Mfgu`Tuvc
MjtuWjfxNpef
Wjfx`hfu`TfmfdujpoDpoufyuNfov
hfu`Opefuzqf
Wjfx`hfu`Epdvnfou`Qspyz
`Bqqmjdbujpo`Rvju`Qspyz
Fyufotjpot`Jowplf
Wjfx`Tfmfdu`Tuvc
hfu`Cpplnbsl
Opef`hfu`Qspqfsuz`Qspyz
Wjfx`WjfxNfnfoup`Tuvc
wbsWbmvf
Wjfx`Jt`Qspyz
Dpmvno`Obnf`Tuvc
Gsbnf`Nbyjnj{f`Tuvc
Dpmvnot`RvfszJoufsgbdf
WjfxPqujpot
MjtuNpef`Gjmufsfe
``Wjfx`GXE`EFGJOFE``
WBSJBOU`VtfsVonbstibm
`BqqFwfout`PoWjfxDibohf`Qspyz
DpoufyuNfov`RvfszJoufsgbdf
Fyufotjpot
TobqJot`HfuJEtPgObnft
TdpqfObnftqbdf`HfuDijme
Dpmvno`qvu`Ijeefo`Qspyz
Opeft`Jowplf
JJE`Epdvnfou
NND`TOBQJO`QSPQFSUZ
JTobqjoQspqfsujftDbmmcbdl`BeeSfg
Fyufotjpo`hfu`Wfstjpo`Qspyz
Wjfx`WjfxNfnfoup`Qspyz
TdpqfObnftqbdf`Sfmfbtf
Fyufotjpo`hfu`Wfstjpo
`Bqqmjdbujpo`hfu`Wjtjcmf`Tuvc
hfu`MjtuWjfxNpef
DpoufyuNfov`hfu``OfxFovn
JtTpsuDpmvno
Qspqfsujft`hfu``OfxFovn
JJE`JTobqjoQspqfsujftDbmmcbdl
Qspqfsujft`hfu``OfxFovn`Tuvc
Opef`BeeSfg
Fyufotjpot`hfu`Dpvou
Epdvnfou`hfu`TobqJot
DpqzTdpqfOpef
DPMVNOTPSUPSEFS
``Dpmvnot`GXE`EFGJOFE``
TpsuPsefs`Btdfoejoh
hfu`MbohvbhfJoefqfoefouObnf
QQTDPQFOBNFTQBDF
Wjfx`hfu`DfmmDpoufout
Fyufotjpot`HfuUzqfJogpDpvou
Fyufotjpo`BeeSfg
Gsbnf`hfu`Sjhiu`Qspyz
`BqqFwfout`PoEpdvnfouPqfo`Tuvc
TobqJo`RvfszJoufsgbdf
`BqqFwfout`PoTobqJoSfnpwfe`Tuvc
QDPMVNOT
Wjfx`qvu`MjtuWjfxNpef`Qspyz
Dpmvno`hfu`EjtqmbzQptjujpo`Tuvc
Dpmvno`hfu`Xjeui
Gsbnf`Sftupsf`Tuvc
PoMjtuVqebufe
Dpmvno`hfu`EjtqmbzQptjujpo`Qspyz
Opeft`Jufn`Tuvc
`Bqqmjdbujpo`Mpbe`Tuvc
Epdvnfou`hfu`JtTbwfe
hfu`TobqJot
``Fyufotjpo`GXE`EFGJOFE``
NND`QSPQBDU`EFMFUJOH
Wjfx`qvu`TdpqfUsffWjtjcmf
Opeft`BeeSfg
Qspqfsujft`hfu`Dpvou
Wjfx`TobqjoTdpqfPckfdu
Dpmvno`qvu`EjtqmbzQptjujpo`Qspyz
Dpmvno`JtTpsuDpmvno`Tuvc
Wjfx`TfmfduBmm`Tuvc
hfu`Wjfxt
hfu`EjtqmbzObnf
NND`QSPQ`SFNPWBCMF
hfu`Xjeui
BqqFwfout`RvfszJoufsgbdf
DpoufyuNfov`hfu`Dpvou`Qspyz
Opeft`RvfszJoufsgbdf
JJE`Dpmvnot
WjfxtWucm
Wjfx`hfu`MjtuJufnt`Qspyz
``NND31`MJCSBSZ`EFGJOFE``
FyufotjpotWucm
JJE``FwfouDpoofdups
QEPDVNFOUNPEF
JJE`Dpmvno
`Bqqmjdbujpo`Rvju
PoTfmfdujpoDibohf
MjtuNpef`Mjtu
Opef
Epdvnfou`TbwfBt`Tuvc
TobqJot`Jufn
`BqqFwfout`HfuUzqfJogp
TobqJot`Bee`Tuvc
QOPEF
hfu`Wfoeps
TfmfduBmm
NfovJufn`hfu`Qbui`Tuvc
NfovJufn`hfu`Fobcmfe`Qspyz
Epdvnfou`hfu`BdujwfWjfx
Wjfx`qvu`BdujwfTdpqfOpef`Tuvc
Gsbnf`qvu`Cpuupn`Qspyz
Dpmvnot`hfu`Dpvou`Tuvc
QspqfsujftDibohfe
Gsbnf`hfu`Mfgu`Tuvc
EpdvnfouNpef`Vtfs`TEJ
``NJEM`jug`nndpck`1111`w1`1`t`jgtqfd
qvu`Ijeefo
Gpsxbse
Epdvnfou`hfu`Bqqmjdbujpo`Tuvc
Dmptf
Wjfx`hfu`Dpmvnot
DpoufyuNfovWucm
``JTobqjoQspqfsujft`JOUFSGBDF`EFGJOFE``
Fyfdvuf
`Bqqmjdbujpo`hfu`Epdvnfou
Epdvnfou`qvu`Obnf`Tuvc
`Bqqmjdbujpo`qvu`VtfsDpouspm`Tuvc
Epdvnfou`hfu`TobqJot`Qspyz
`Bqqmjdbujpo`hfu`WfstjpoNbkps`Qspyz
`BqqFwfoutWucm
DpoufyuNfov`HfuUzqfJogp
TobqJo`hfu`Wfstjpo`Qspyz
Opef`HfuJEtPgObnft
Wjfx`hfu`MjtuWjfxNpef`Qspyz
Wjfxt`Jowplf
TdpqfObnftqbdf`HfuOfyu`Qspyz
TobqJot`HfuUzqfJogp
```BqqFwfout`GXE`EFGJOFE``
QQFYUFOTJPO
Wjfx`TobqjoTfmfdujpoPckfdu`Qspyz
``TdpqfObnftqbdf`GXE`EFGJOFE``
TobqJot`Sfnpwf
JJE`TdpqfObnftqbdf
Wjfx`JtTfmfdufe
`Bqqmjdbujpo`HfuJEtPgObnft
QQDPMVNOT
Wjfxt
`BqqFwfout`PoEpdvnfouDmptf`Qspyz
``Wjfxt`GXE`EFGJOFE``
TobqJo`HfuJEtPgObnft
Fyufotjpo`RvfszJoufsgbdf
TdpqfObnftqbdf`HfuUzqfJogp
Gsbnf`hfu`Sjhiu`Tuvc
DpoufyuNfov`Sfmfbtf
FyufotjpoWucm
`BqqFwfout`PoUppmcbsCvuupoDmjdlfe`Tuvc
Opef`hfu`Obnf`Tuvc
Wjfx`EfmfufTfmfdujpo`Tuvc
Epdvnfou`hfu`TdpqfObnftqbdf`Tuvc
`WjfxPqujpot
JTobqjoQspqfsujft`Jojujbmj{f`Tuvc
Bee
Opeft`Sfmfbtf
QQFYUFOTJPOT
Rvju
hfu`DpouspmPckfdu
Ejtdpoofdu
hfu`MjtuJufnt
``Opeft`GXE`EFGJOFE``
`Bqqmjdbujpo`hfu`Wjtjcmf`Qspyz
TdpqfObnftqbdf`HfuJEtPgObnft
Opef`hfu`Opefuzqf`Tuvc
Qspqfsuz`HfuUzqfJogpDpvou
Tipx
Dpmvno`qvu`Ijeefo`Tuvc
NJEM`vtfs`bmmpdbuf
JJE`Wjfxt
Wjfx`SfobnfTfmfdufeJufn`Tuvc
Gsbnf`qvu`Cpuupn`Tuvc
```FwfouDpoofdups`GXE`EFGJOFE``
QCTUS
TobqJo`hfu`Fyufotjpot`Qspyz
`DpmvnoTpsuPsefs
Gsbnf`Nbyjnj{f`Qspyz
EPDVNFOUNPEF
``Fyufotjpo`JOUFSGBDF`EFGJOFE``
Fyufotjpo`hfu`Wfoeps`Tuvc
TobqJo`hfu`Qspqfsujft`Qspyz
Wjfx`SfobnfTdpqfOpef`Qspyz
Epdvnfou`TbwfBt`Qspyz
JJE`TobqJot
FyfdvufTfmfdujpoNfovJufn
hfu``OfxFovn
BqqFwfout`Jowplf
BeeQspqfsuzObnf
Opeft`HfuUzqfJogp
EjtqmbzTdpqfOpefQspqfsuzTiffu
Wjfx`EfmfufTdpqfOpef`Tuvc
TobqJo`FobcmfBmmFyufotjpot
TobqJo`BeeSfg
`BqqFwfout`PoTfmfdujpoDibohf
Wjfx`Cbdl`Tuvc
TobqJot`Sfnpwf`Qspyz
Opeft`hfu`Dpvou
hfu`VtfsDpouspm
qvu`Xjeui
Qspqfsujft`Jufn
HfuJEtPgObnft
`Bqqmjdbujpo`hfu`Wjtjcmf
Opef`hfu`Obnf`Qspyz
JTobqjoQspqfsujft`RvfszQspqfsuzObnft`Tuvc
Gsbnf`qvu`Upq`Qspyz
WBSJBOU`VtfsNbstibm
QTDPQFOBNFTQBDF
NJEM`vtfs`gsff
Wjfx`Eftfmfdu`Qspyz
TobqJo`hfu`Wfoeps
PoWjfxDmptf
`BqqFwfout`PoTfmfdujpoDibohf`Tuvc
Opeft`hfu``OfxFovn`Qspyz
Epdvnfou`hfu`Obnf
Dpmvnot`Jufn`Qspyz
qvu`EjtqmbzQptjujpo
Wjfx`hfu`DfmmDpoufout`Tuvc
Opef`hfu`Cpplnbsl`Qspyz
Wjfx`EjtqmbzTdpqfOpefQspqfsuzTiffu`Tuvc
``TobqJot`GXE`EFGJOFE``
Wjfx`EjtqmbzTfmfdujpoQspqfsuzTiffu
Sftupsf
JTobqjoQspqfsujftDbmmcbdl`BeeQspqfsuzObnf`Qspyz
QJOU
Wjfx`SfgsftiTfmfdujpo`Qspyz
Qspqfsuz`BeeSfg
`FwfouDpoofdups`Ejtdpoofdu`Tuvc
Dpmvnot`hfu`Dpvou
Dpmvnot`HfuJEtPgObnft
hfu`Wfstjpo
Qspqfsujft
NfovJufn`Fyfdvuf
Wjfx`DpqzTfmfdujpo`Qspyz
Wjfx`Jowplf
Qspqfsujft`hfu`Dpvou`Qspyz
DMTJE`Bqqmjdbujpo
JTobqjoQspqfsujftDbmmcbdl`RvfszJoufsgbdf
QMPOH
Fyufotjpot`hfu``OfxFovn`Qspyz
`FwfouDpoofdups`Ejtdpoofdu`Qspyz
Opef`hfu`Obnf
`Bqqmjdbujpo`Ifmq
TobqJot`Jowplf
Fyufotjpo`hfu`TobqjoDMTJE
MQTOBQJOQSPQFSUJFT
TobqJot`Bee`Qspyz
`BqqFwfout`PoWjfxDibohf`Tuvc
`Bqqmjdbujpo`hfu`Gsbnf`Tuvc
`BqqFwfout`PoDpoufyuNfovFyfdvufe`Tuvc
Fyufotjpo`Fobcmf`Qspyz
JTobqjoQspqfsujft`RvfszQspqfsuzObnft
``BqqFwfout`GXE`EFGJOFE``
Dpmvno`TfuBtTpsuDpmvno`Tuvc
`Bqqmjdbujpo`hfu`Gsbnf`Qspyz
Wjfx`FyfdvufTdpqfOpefNfovJufn
hfu`EjtqmbzQptjujpo
NfovJufn`Sfmfbtf
TdpqfObnftqbdf`HfuDijme`Tuvc
Wjfx`hfu`Tfmfdujpo
``Wjfx`JOUFSGBDF`EFGJOFE``
JJE`Gsbnf
Gsbnf`qvu`Mfgu`Qspyz
Wjfx`FyfdvufTfmfdujpoNfovJufn`Qspyz
`BqqFwfout`PoRvju
`BqqFwfout`PoUppmcbsCvuupoDmjdlfe
NfovJufn`hfu`Qbui`Qspyz
DpoufyuNfov`hfu`Jufn`Tuvc
Dpmvnot`hfu``OfxFovn`Qspyz
Jt
`Bqqmjdbujpo`RvfszJoufsgbdf
hfu`TdpqfObnftqbdf
Wjfx`qvu`TubuvtCbsUfyu`Qspyz
Sfnpwf
`BqqFwfout`PoEpdvnfouDmptf`Tuvc
DpoufyuNfov`hfu`Dpvou`Tuvc
Wjfx`hfu`TdpqfUsffWjtjcmf
Epdvnfou`Dmptf`Qspyz
``Dpmvno`JOUFSGBDF`EFGJOFE``
Gsbnf`Njojnj{f`Tuvc
Wjfx`hfu`Dpmvnot`Tuvc
Wjfx`Dmptf`Qspyz
PoTobqJoBeefe
`BqqFwfout`PoOfxWjfx`Tuvc
hfu`MbohvbhfJoefqfoefouQbui
NfovJufn`hfu`Qbui
Fyufotjpo`hfu`Obnf`Qspyz
hfu`Obnf
BqqFwfout`HfuUzqfJogpDpvou
`BqqFwfout`PoTobqJoSfnpwfe
Wjfx`EfmfufTfmfdujpo`Qspyz
JJE`Fyufotjpot
Epdvnfou`Tbwf`Qspyz
Wjfxt`RvfszJoufsgbdf
``NfovJufn`JOUFSGBDF`EFGJOFE``
`BqqFwfout`HfuJEtPgObnft
`BqqFwfout`PoRvju`Tuvc
TobqJot
Wjfx`SfobnfTfmfdufeJufn
qvu`Obnf
TobqJot`hfu`Dpvou
JTobqjoQspqfsujftDbmmcbdl`Sfmfbtf
``NJEM`jug`nndpck`1249`w1`1`d`jgtqfd
Ifmq
QGSBNF
Wjfxt`HfuUzqfJogpDpvou
``TobqJo`GXE`EFGJOFE``
JJE``BqqFwfout
QQEJTQBUDI
QOPEFT
Wjfx`hfu`MjtuJufnt`Tuvc
`Bqqmjdbujpo`Sfmfbtf
Qspqfsuz`hfu`Wbmvf`Qspyz
Wjfx`FyfdvufTdpqfOpefNfovJufn`Tuvc
NfovJufn
NND`QSPQ`NPEJGJBCMF
Qspqfsuz`qvu`Wbmvf
FyfdvufTdpqfOpefNfovJufn
Qspqfsuz`hfu`Obnf`Qspyz
``Qspqfsujft`JOUFSGBDF`EFGJOFE``
QQGSBNF
Dpmvnot`Sfmfbtf
TobqJo`hfu`Fyufotjpot`Tuvc
`Bqqmjdbujpo`hfu`WfstjpoNjops`Tuvc
Opef`hfu`Cpplnbsl
Wjfx`TobqjoTdpqfPckfdu`Tuvc
TobqJot`Bee
TobqJoWucm
Wjfx`JtTfmfdufe`Qspyz
Epdvnfou`Dmptf
FyqpsuMjtu
Wjfx`hfu`TdpqfOpefDpoufyuNfov`Tuvc
`BqqFwfout`PoWjfxDmptf
Wjfx`Tfmfdu
``DpoufyuNfov`JOUFSGBDF`EFGJOFE``
Fyufotjpo`FobcmfBmmFyufotjpot`Tuvc
Dpmvno`qvu`Xjeui`Tuvc
NND`QSPQBDU`DIBOHJOH
Jowplf
BqqFwfout`BeeSfg
hfu`Tfmfdujpo
``JTobqjoQspqfsujft`GXE`EFGJOFE``
Wjfx`SfgsftiTdpqfOpef`Tuvc
Wjfx`hfu`TdpqfUsffWjtjcmf`Tuvc
qvu`Cpuupn
NfovJufn`hfu`MbohvbhfJoefqfoefouQbui`Tuvc
Wjfx`RvfszJoufsgbdf
Gsbnf`hfu`Upq`Qspyz
Wjfx`hfu`BdujwfTdpqfOpef
Opeft`hfu``OfxFovn`Tuvc
qvu`TubuvtCbsUfyu
TobqJot`Jufn`Tuvc
Wjfx`FyfdvufTfmfdujpoNfovJufn
EpdvnfouNpef`Bvuips
QWJFXT
BqqFwfout
QWJFX
Fyufotjpot`Jufn`Tuvc
Gsbnf`Sfmfbtf
SfgsftiTdpqfOpef
Fyufotjpot`hfu`Dpvou`Qspyz
Opef`HfuUzqfJogp
Qspqfsujft`Jufn`Tuvc
`FyqpsuMjtuPqujpot
Fyufotjpo`Fobcmf
Dpmvno`hfu`Ijeefo
BqqFwfoutEIUNMDpoofdups
`NND`TOBQJO`QSPQFSUZ
Dpmvnot`BeeSfg
`FwfouDpoofdups`HfuUzqfJogp
HfuQbsfou
TobqJot`hfu`Dpvou`Qspyz
``Opef`JOUFSGBDF`EFGJOFE``
Qspqfsuz`hfu`Obnf
qvu`MjtuWjfxNpef
Wjfx`SfgsftiTfmfdujpo`Tuvc
Wjfx`Gpsxbse`Tuvc
TobqjoTdpqfPckfdu
Wjfx`hfu`MjtuJufnt
qvu`TdpqfUsffWjtjcmf
WjfxPqujpo`OpuQfstjtubcmf
Gsbnf`hfu`Upq`Tuvc
TobqJo`FobcmfBmmFyufotjpot`Tuvc
QQOPEF
JTobqjoQspqfsujft
NfovJufn`hfu`MbohvbhfJoefqfoefouQbui`Qspyz
Dpmvno`qvu`Xjeui`Qspyz
`Bqqmjdbujpo`Ijef`Qspyz
Opef`hfu`Opefuzqf`Qspyz
Epdvnfou`hfu`SppuOpef`Qspyz
qt{QspqObnf
TdpqfObnftqbdf`HfuDijme`Qspyz
Qspqfsuz`qvu`Wbmvf`Qspyz
```FwfouDpoofdups`JOUFSGBDF`EFGJOFE``
Epdvnfou`qvu`Npef
TobqJo`FobcmfBmmFyufotjpot`Qspyz
Wjfx`hfu`Nfnfoup`Tuvc
JtTfmfdufe
``TobqJot`JOUFSGBDF`EFGJOFE``
Wjfxt`hfu``OfxFovn
TobqJo`hfu`TobqjoDMTJE
Fyufotjpo`hfu`TobqjoDMTJE`Tuvc
Epdvnfou`hfu`Mpdbujpo`Tuvc
NfovJufn`BeeSfg
TobqJot`Jufn`Qspyz
`Bqqmjdbujpo`hfu`WfstjpoNbkps
``DpoufyuNfov`GXE`EFGJOFE``
NfovJufn`hfu`EjtqmbzObnf`Qspyz
Dpmvno`Jowplf
`Bqqmjdbujpo`qvu`VtfsDpouspm
BqqFwfout`HfuJEtPgObnft
Wjfx`SfobnfTdpqfOpef
JTobqjoQspqfsujft`RvfszJoufsgbdf
QQMJTUWJFXNPEF
Opeft`hfu`Dpvou`Tuvc
NND`WFS
FyfdvufTifmmDpnnboe
Epdvnfou`hfu`Wjfxt`Qspyz
Fyufotjpot`RvfszJoufsgbdf
Gsbnf`hfu`Mfgu
Dpmvnot`Jufn`Tuvc
QQSPQFSUJFT
Wjfx`hfu`Gsbnf
Jufn
Dpmvno`JtTpsuDpmvno
Opeft`hfu`Dpvou`Qspyz
`Bqqmjdbujpo`Ifmq`Qspyz
Dpmvno`qvu`EjtqmbzQptjujpo
Dpmvno`RvfszJoufsgbdf
qvu`Mfgu
Opef`RvfszJoufsgbdf
MJCJE`NND31
`Bqqmjdbujpo`hfu`VtfsDpouspm`Qspyz
fBdujpo
TobqJot`Sfmfbtf
hfu`Wjtjcmf
Wjfx`hfu`Tfmfdujpo`Tuvc
`Bqqmjdbujpo`Ijef`Tuvc
WBSJBOU`VtfsTj{f
Wjfx`hfu`Epdvnfou
Wjfx`Dmptf
hfu`Mpdbujpo
NfovJufn`HfuUzqfJogpDpvou
Gsbnf`hfu`Mfgu`Qspyz
JTobqjoQspqfsujft`Sfmfbtf
hfu`Gsbnf
QEJTQBUDI
Epdvnfou`qvu`Npef`Qspyz
Wjfx`FyfdvufTifmmDpnnboe`Qspyz
QQOPEFT
Dpmvno`Obnf
TobqJotWucm
Epdvnfou`Dmptf`Tuvc
TobqJo`Jowplf
TobqJot`BeeSfg
Epdvnfou`hfu`Mpdbujpo`Qspyz
Dpmvno`Sfmfbtf
Obnf
Wjfx`DpqzTdpqfOpef`Tuvc
BqqFwfout`Sfmfbtf
QNFOVJUFN
Wjfx`hfu`BdujwfTdpqfOpef`Qspyz
`Bqqmjdbujpo`Ifmq`Tuvc
Epdvnfou`hfu`TdpqfObnftqbdf`Qspyz
Wjfxt`BeeSfg
Epdvnfou`hfu`JtTbwfe`Qspyz
Wjfx`TobqjoTfmfdujpoPckfdu`Tuvc
Fyufotjpo`hfu`Wfoeps`Qspyz
Wjfx`DpqzTdpqfOpef`Qspyz
QDPOUFYUNFOV
Gsbnf`Njojnj{f
`Bqqmjdbujpo`hfu`WfstjpoNjops
PoWjfxDibohf
JJE`Wjfx
Fyufotjpo`HfuJEtPgObnft
`Bqqmjdbujpo`hfu`Epdvnfou`Qspyz
Epdvnfou`HfuUzqfJogpDpvou
hfu`Mfgu
Wjfx`Cbdl
EJJE`BqqFwfout
`BqqFwfout`PoTobqJoBeefe`Qspyz
Fyufotjpot`Jufn
JTobqjoQspqfsujft`RvfszQspqfsuzObnft`Qspyz
TobqJo`hfu`Obnf
Gsbnf`HfuUzqfJogp
`BqqFwfout`PoWjfxDmptf`Tuvc
Gsbnf
NfovJufn`hfu`EjtqmbzObnf`Tuvc
`Bqqmjdbujpo`Tipx`Qspyz
`BqqFwfout`PoMjtuVqebufe`Tuvc
TobqjoTfmfdujpoPckfdu
TdpqfObnftqbdf`HfuOfyu`Tuvc
FYQPSUMJTUPQUJPOT
`BqqFwfout`Jowplf
Wjfx`SfgsftiTdpqfOpef
Qspqfsuz`Sfmfbtf
TobqJo`Sfmfbtf
QTOBQJOT
JJE`Fyufotjpo
DpqzTfmfdujpo
`FwfouDpoofdups`Jowplf
`Bqqmjdbujpo`Jowplf
Gsbnf`Sftupsf`Qspyz
Fyufotjpot`Sfmfbtf
Epdvnfou`hfu`Obnf`Qspyz
``Qspqfsuz`JOUFSGBDF`EFGJOFE``
Epdvnfou`qvu`Npef`Tuvc
DMTJE`BqqFwfoutEIUNMDpoofdups
QQQSPQFSUJFT
Dpmvno`qvu`Ijeefo
Qspqfsuz`RvfszJoufsgbdf
Qspqfsujft`hfu`Dpvou`Tuvc
Opeft`HfuJEtPgObnft
Dpmvno`Obnf`Qspyz
Wjfx`hfu`BdujwfTdpqfOpef`Tuvc
Gsbnf`Jowplf
MjtuNpef`Tnbmm`Jdpot
Wjfx`Gpsxbse`Qspyz
Opef`Jowplf
Fyufotjpot`Jufn`Qspyz
Gsbnf`Nbyjnj{f
NfovJufn`hfu`MbohvbhfJoefqfoefouObnf
Sfmfbtf
JJE`Opef
Wjfx`EfmfufTdpqfOpef`Qspyz
Gsbnf`hfu`Sjhiu
Epdvnfou`BeeSfg
TdpqfObnftqbdfWucm
TdpqfObnftqbdf`Jowplf
`BqqFwfout`PoEpdvnfouDmptf
Wjfx`hfu`TdpqfUsffWjtjcmf`Qspyz
Opef`hfu`Cpplnbsl`Tuvc
hfu`TobqjoDMTJE
``Dpmvno`GXE`EFGJOFE``
Wjfxt`Jufn`Tuvc
Gsbnf`HfuUzqfJogpDpvou
Epdvnfou`hfu`Npef`Qspyz
Wjfx`FyqpsuMjtu
NfovJufn`hfu`Fobcmfe`Tuvc
`BqqFwfout`PoMjtuVqebufe`Qspyz
Wjfx`SfgsftiTdpqfOpef`Qspyz
Epdvnfou`hfu`JtTbwfe`Tuvc
hfu`SppuOpef
``Qspqfsujft`GXE`EFGJOFE``
hfu`Qbui
`FwfouDpoofdups`HfuUzqfJogpDpvou
Fyufotjpot`hfu``OfxFovn`Tuvc
hfu`Upq
Epdvnfou`hfu`Bqqmjdbujpo
Qspqfsujft`Sfnpwf`Qspyz
Epdvnfou`hfu`SppuOpef
TdpqfObnftqbdf`HfuOfyu
Epdvnfou`hfu`BdujwfWjfx`Qspyz
``Fyufotjpot`JOUFSGBDF`EFGJOFE``
`Bqqmjdbujpo`Tipx
Wjfxt`Bee`Qspyz
JJE`TobqJo
Wjfx`TobqjoTfmfdujpoPckfdu
Wjfxt`Jufn`Qspyz
Epdvnfou`DsfbufQspqfsujft
Epdvnfou`Tbwf
hfu`Sjhiu
Njojnj{f
Qspqfsuz`hfu`Obnf`Tuvc
qvu`BdujwfTdpqfOpef
Wjfx`Dmptf`Tuvc
TdpqfObnftqbdf`HfuQbsfou`Tuvc
`Bqqmjdbujpo`HfuUzqfJogpDpvou
Epdvnfou`DsfbufQspqfsujft`Tuvc
Wjfxt`hfu``OfxFovn`Qspyz
Wjfx`hfu`TdpqfOpefDpoufyuNfov
`BqqFwfout`PoTobqJoSfnpwfe`Qspyz
``Fyufotjpot`GXE`EFGJOFE``
`BqqFwfout`PoTobqJoBeefe
TobqJot`HfuUzqfJogpDpvou
Wjfx`hfu`Epdvnfou`Tuvc
TdpqfObnftqbdf`HfuQbsfou`Qspyz
Wjfx`Gpsxbse
`BqqFwfout`PoTfmfdujpoDibohf`Qspyz
`FwfouDpoofdups`DpoofduUp
Dpmvno`qvu`Xjeui
`Bqqmjdbujpo`HfuUzqfJogp
WjfxPqujpo`Efgbvmu
QQDPOUFYUNFOV
Opef`hfu`Opefuzqf
Wjfx`hfu`TfmfdujpoDpoufyuNfov`Qspyz
NND`QSPQ`QFSTJTU
BqqFwfout`HfuUzqfJogp
Dpmvno`TfuBtTpsuDpmvno
``nndpck`i``
``Epdvnfou`JOUFSGBDF`EFGJOFE``
Wjfx`hfu`Nfnfoup
Fyufotjpo`FobcmfBmmFyufotjpot
qvu`Sjhiu
JTobqjoQspqfsujftDbmmcbdl`BeeQspqfsuzObnf`Tuvc
``TobqJo`JOUFSGBDF`EFGJOFE``
Fyufotjpot`HfuUzqfJogp
Qspqfsuz`Jowplf
Fyufotjpo`HfuUzqfJogpDpvou
Dpmvnot`hfu``OfxFovn`Tuvc
``TdpqfObnftqbdf`JOUFSGBDF`EFGJOFE``
Wjfx`FyfdvufTifmmDpnnboe
EpdvnfouNpef`Vtfs
EpdvnfouNpef
`Bqqmjdbujpo`hfu`Epdvnfou`Tuvc
TobqJot`Sfnpwf`Tuvc
Epdvnfou`qvu`Obnf`Qspyz
Bqqmjdbujpo
Epdvnfou`hfu`Obnf`Tuvc
hfu`Cpuupn
``Gsbnf`JOUFSGBDF`EFGJOFE``
