#Encrypted file follows
SPVUFS`JG`TUBUF`DPOOFDUFE
mqcDvtupnBvuiEbub
`QQQ`BUDQ`JOGP
NQSEU`Jteo
NQSFU`Wqo
exJgUzqf
NQS`JOUFSGBDF`BENJO`EJTBCMFE
NQS`NbyBsfbDpef
SBT`QPSU`OPO`PQFSBUJPOBM
exJoufsgbdfUzqf
exCzuftYnjufe
`SBT`DPOOFDUJPO`2
`SBT`QPSU`DPOEJUJPO
iUsbotqpsu
bu
Hvje
NqsDpogjhJoufsgbdfUsbotqpsuBee
NqsBenjoMjolIbohvqOpujgjdbujpo
NQS`EFWJDF`1
xt{Xltub
exgOfuQspupdpmt
NqsDpogjhHfuGsjfoemzObnf
exSfnpufBvuifoujdbujpoQspupdpm
NqsDpogjhTfswfsTfuJogp
NqsBenjoJtTfswjdfSvoojoh
ddq
NqsBenjoJoufsgbdfRvfszVqebufSftvmu
NqsBenjoJoufsgbdfEfwjdfHfuJogp
SPVUFS`JG`UZQF`EFEJDBUFE
NqsDpogjhUsbotqpsuHfuJogp
t{EfwjdfObnf
exOvnM3uqQpsut
QQQ`JOGP`3
NqsBenjoBddfquOfxDpoofdujpo
`NQS`EFWJDF`2
NqsBenjoEfsfhjtufsDpoofdujpoOpujgjdbujpo
QQQ`MDQ`JOGP
QQQ`DDQ`DPNQSFTTJPO
jqy
NQS`DSFEFOUJBMTFY`1
NqsDpogjhTfswfsJotubmm
`QQQ`DDQ`JOGP
NqsBenjoDpoofdujpoDmfbsTubut
NQSEU`TX67
`QQQ`OCGDQ`JOGP
gFobcmfe
exDpnqsfttjpoSbujpPvu
NqsBenjoJoufsgbdfTfuDsfefoujbmt
NQS`JOUFSGBDF`1
QQQ`JQDQ`JOGP
exMjofTqffe
JQYBEESFTTMFO
NQSEU`Jseb
exIbsexbsfPwfssvoFss
NqsJogpCmpdlFyjtut
NQSFU`Ejsfdu
exCzuftSdwfe
exDiboofmt
QJE`BUBML
xt{QpsuObnf
NqsBenjoJoufsgbdfUsbotqpsuTfuJogp
xt{Beesftt
NqsDpogjhTfswfsSftupsf
QQQ`DDQ`JOGP
NQSJP`SfrvjsfDIBQ
NQSEN`EjbmBtOffefe
exUsbotqpsuJe
exSfnpufDpnqsfttjpoBmhpsjuin
NqsBenjoHfuQEDTfswfs
exgPqujpot
`NQS`JQJOJQ`JOUFSGBDF`1
jqbeesXjot
NBY`EFWJDF`OBNF
QNQS`TFSWFS`2
SBT`IBSEXBSF`GBJMVSF
xt{MphpoEpnbjo
QQQ`MDQ`TTIG
SPVUFS`JG`TUBUF`VOSFBDIBCMF
iDpoofdujpo
exSfnpufPqujpot
NqsBenjoQpsuHfuJogp
QNQS`TFSWFS`1
`SPVUFS`DPOOFDUJPO`TUBUF
NqsBenjoNJCFouszTfu
NqsBenjoUsbotqpsuTfuJogp
QQQ`JQDQ`JOGP3
NqsBenjoJtEpnbjoSbtTfswfs
iQpsu
NQSJP`SfrvjsfQBQ
QQQ`MDQ`4`EFT
NqsDpogjhJoufsgbdfTfuJogp
NQS`NbyQbeUzqf
SBTQSJW3`EjbmjoQpmjdz
NQS`FOBCMF`SBT`PO`EFWJDF
NQS`NbyY36Beesftt
QQQ`MDQ`NVMUJMJOL`GSBNJOH
NqsDpogjhJoufsgbdfEfmfuf
exIbsexbsfDpoejujpo
`NQS`JGUSBOTQPSU`1
QSBT`QPSU`1
NQS`WT`QquqPomz
`NQS`TFSWFS`1
NQS`FU`Sfrvjsf
gVoSfbdibcjmjuzSfbtpot
NqsBenjoJoufsgbdfHfuDsfefoujbmt
SBTQSJW`EjbmjoQsjwjmfhf
xt{SfnpufBeesftt
NqsBenjoNJCTfswfsDpoofdu
`NQS`TFSWFS`2
NQS`JOUFSGBDF`OP`NFEJB`TFOTF
NqsDpogjhUsbotqpsuEfmfuf
NqsBenjoBddfquOfxDpoofdujpo3
jqbeesXjotBmu
SPVUFS`JOUFSGBDF`UZQF
SBT`QPSU`DPOEJUJPO
NQSJP`TxDpnqsfttjpo
NqsBenjoNJCTfuUsbqJogp
xt{JgUsbotqpsuObnf
NQS`FU`SfrvjsfNby
NqsBenjoJoufsgbdfEfwjdfTfuJogp
NqsBenjoJoufsgbdfUsbotqpsuBee
NqsBenjoNJCTfswfsEjtdpoofdu
`NQS`JOUFSGBDF`1
NBY`JOUFSGBDF`OBNF`MFO
NqsBenjoJoufsgbdfUsbotqpsuSfnpwf
NqsDpogjhJoufsgbdfHfuIboemf
QQQ`DDQ`FODSZQUJPO51CJU
NqsJogpCmpdlBee
NqsDpogjhJoufsgbdfFovn
NQS`WT`QquqGjstu
SPVUFS`JG`UZQF`DMJFOU
NQSEU`Tfsjbm
NqsBenjoTfswfsTfuJogp
NqsTfuvqJqJoJqJoufsgbdfGsjfoemzObnfGsff
t{Y36QbeUzqf
NqsDpogjhUsbotqpsuHfuIboemf
NQS`TFSWFS`1
SSBT`TFSWJDF`OBNF
exDvtupnBvuiEbubTj{f
`QQQ`JOGP`3
exUzqf
NQS`NbyQipofOvncfs
xt{GsjfoemzObnf
SBT`QPSU`BVUIFOUJDBUJOH
NQS`JOUFSGBDF`OP`EFWJDF
NQSJP`QspnpufBmufsobuft
iJoufsgbdf
mdq
exUfsnjobufSfbtpo
QQQ`MDQ`QGD
SPVUFS`JG`UZQF`MPPQCBDL
NqsDpogjhTfswfsCbdlvq
NqsDpogjhTfswfsDpoofdu
SBT`GMBHT`NFTTFOHFS`QSFTFOU
NqsBenjoJoufsgbdfHfuDsfefoujbmtFy
xt{EfwjdfObnf
mqcDsfefoujbmtJogp
SBT`GMBHT`SBT`DPOOFDUJPO
QSBT`VTFS`2
NQSEU`Tpofu
QSBT`DPOOFDUJPO`1
NqsDpogjhJoufsgbdfUsbotqpsuHfuJogp
exDpoofdujpoTubuf
NBY`USBOTQPSU`OBNF`MFO
`NQS`JOUFSGBDF`2
NqsBenjoNJCFouszEfmfuf
NQS`DSFEFOUJBMTFY`2
exBmjhonfouFss
exSfnpufFbqUzqfJe
NqsDpogjhTfswfsSfgsfti
NQS`FOBCMF`SPVUJOH`PO`EFWJDF
jq
QNQS`EFWJDF`2
exEjbmFyusbTbnqmfTfdpoet
NqsBenjoVtfsTfuJogp
QNQS`EFWJDF`1
SBTQSJW`OpDbmmcbdl
jqbeesEot
NQSJP`SfrvjsfEbubFodszqujpo
NqsBenjoJoufsgbdfFovn
NQS`WT`M3uqPomz
NQSJP`JqIfbefsDpnqsfttjpo
NqsBenjoUsbotqpsuDsfbuf
NQSJP`SfrvjsfFodszqufeQx
NQSJP`SfrvjsfFBQ
exBvuifoujdbujpoEbub
NqsBenjoNJCFouszHfuOfyu
QQQ`MDQ`FBQ
t{Y36Beesftt
NqsBenjoNJCFouszDsfbuf
NQSJP`SfrvjsfNtDIBQ
NqsBenjoBddfquOfxMjol
NQSEN`EjbmGjstu
QQQ`MDQ`TQBQ
`QQQ`JQDQ`JOGP3
NqsBenjoJoufsgbdfDsfbuf
QQQ`OCGDQ`JOGP
SBT`VTFS`1
`SBT`VTFS`1
exUpubmOvncfsPgDbmmt
QQQ`JOGP
mqxtEjbmpvuIpvstSftusjdujpo
NQSJP`TibsfeQipofOvncfst
QNQS`JOUFSGBDF`2
NqsBenjoDpoofdujpoIbohvqOpujgjdbujpo
exMbtuFssps
t{Y36VtfsEbub
NQSJP`SfrvjsfNtFodszqufeQx
exQquqQpsuGmbht
NQS`TFSWFS`IBOEMF
NqsBenjoJoufsgbdfVqebufQipofcpplJogp
QQQ`DDQ`IJTUPSZMFTT
NqsBenjoHfuFsspsTusjoh
exFbqUzqfJe
exGsbnftYnjufe
NQSOQ`Jqy
SPVUFS`JG`UZQF`JOUFSOBM
exM3uqQpsuGmbht
NqsDpogjhTfswfsEjtdpoofdu
t{Bmufsobuft
exDsdFss
NQSFU`Qipof
NqsBenjoQpsuEjtdpoofdu
NQSEU`Qbsbmmfm
jqbees
QQQ`MDQ`DIBQ`NT
NqsBenjoVtfsHfuJogp
exBvuifoujdbujpoQspupdpm
gMboPomzNpef
SBT`QPSU`2
NqsBenjoDpoofdujpoFovn
exDpnqsfttjpoBmhpsjuin
NqsTfuvqJqJoJqJoufsgbdfGsjfoemzObnfFovn
NQSEN`EjbmBmm
QqqJogp3
`QQQ`MDQ`JOGP
QQQ`JQYDQ`JOGP
NQS`JGUSBOTQPSU`1
NqsBenjoTfswfsTfuDsfefoujbmt
t{EfwjdfUzqf
NqsDpogjhCvggfsGsff
QNQS`DSFEFOUJBMTFY`2
xt{EfwjdfUzqf
NQSEU`Y36
NqsDpogjhJoufsgbdfUsbotqpsuFovn
NqsBenjoSfmfbtfJqBeesftt
NQS`JOUFSGBDF`3
NqsDpogjhHfuHvjeObnf
NqsBenjoJoufsgbdfEjtdpoofdu
exEjbmNpef
NQS`WT`Efgbvmu
exUjnfpvuFss
QJE`JQ
NQS`NbyEfwjdfObnf
NqsBenjoJoufsgbdfHfuIboemf
`NQS`EFWJDF`1
SPVUFS`JG`UZQF`UVOOFM2
exWqoTusbufhz
exGsbnftSdwfe
NqsBenjoFtubcmjtiEpnbjoSbtTfswfs
SPVUFS`JG`TUBUF`EJTDPOOFDUFE
QSBT`VTFS`1
NQS`FU`Opof
`SBT`IBSEXBSF`DPOEJUJPO
`NQS`DSFEFOUJBMTFY`1
NQS`NbyFouszObnf
NQS`JOUFSGBDF`PVU`PG`SFTPVSDFT
SBT`QPSU`BVUIFOUJDBUFE
QNQS`JOUFSGBDF`1
NqsBenjoTfswfsEjtdpoofdu
SPVUFS`JG`TUBUF`DPOOFDUJOH
SBTDDQDB`NQQD
NBY`QPSU`OBNF
exDpoofdujpoGmbht
QSBT`QPSU`2
`SBT`QPSU`1
NqsBenjoDpoofdujpoIbohvqOpujgjdbujpo3
QQQ`MDQ`BDGD
`NQS`DSFEFOUJBMTFY`2
NQSEU`Bun
SBT`QPSU`EJTDPOOFDUFE
ocg
QQQ`BUDQ`JOGP
exIbohVqFyusbQfsdfou
NqsBenjoNJCFouszHfuGjstu
QQQ`DDQ`FODSZQUJPO239CJU
SBT`QPSU`1
NQS`NbyJqyBeesftt
NqsBenjoNJCCvggfsGsff
`SBT`DPOOFDUJPO`1
NqsDpogjhUsbotqpsuDsfbuf
xt{SfnpufDpnqvufs
NqsBenjoJoufsgbdfDpoofdu
`SBT`QPSU`2
NqsBenjoQpsuSftfu
NQSEU`Hfofsjd
exFssps
exEjbmFyusbQfsdfou
``SPVUJOH`NQSBENJO`I``
hvje
NqsBenjoJoufsgbdfVqebufSpvuft
NBY`QIPOF`OVNCFS`MFO
NqsBenjoTfswfsHfuJogp
SBTQSJW`DbmmfsTfuDbmmcbdl
NQS`JOUFSGBDF`TFSWJDF`QBVTFE
QNQS`JGUSBOTQPSU`1
SBTQSJW`DbmmcbdlUzqf
NQSEU`GsbnfSfmbz
SBTQSJW`BenjoTfuDbmmcbdl
QSBT`DPOOFDUJPO`3
NqsJogpEvqmjdbuf
NQS`JQJOJQ`JOUFSGBDF`1
SBT`QPSU`DBMMJOH`CBDL
SPVUFS`JG`UZQF`IPNF`SPVUFS
NQSJP`TqfdjgjdJqBees
NQS`NbyGbdjmjujft
hvjeJe
NQS`EFWJDF`2
NqsBenjoTfswfsHfuDsfefoujbmt
t{MpdbmQipofOvncfs
NQSEU`Wqo
NqsBenjoQpsuFovn
exTvcFousjft
NQSJP`SfrvjsfTQBQ
QQQ`JQDQ`WK
NQS`USBOTQPSU`1
NqsDpogjhJoufsgbdfUsbotqpsuSfnpwf
NqsDpogjhUsbotqpsuFovn
NQSJET`VtfHmpcbmWbmvf
NQSEU`Qbe
SBT`DPOOFDUJPO`2
SPVUFS`JG`UZQF`GVMM`SPVUFS
NQSJP`SfrvjsfNtDIBQ3
`SBT`DPOOFDUJPO`3
NqsBenjoNJCHfuUsbqJogp
JQBEESFTTMFO
NQSJP`OfuxpslMphpo
exDpoofduEvsbujpo
exCvggfsPwfssvoFss
t{Y36Gbdjmjujft
NqsBenjoJoufsgbdfTfuDsfefoujbmtFy
NQS`NbyDbmmcbdlOvncfs
NqsDpogjhJoufsgbdfHfuJogp
NqsDpogjhTfswfsHfuJogp
exSfnpufBvuifoujdbujpoEbub
exQpsutJoVtf
NJC`TFSWFS`IBOEMF
NqsBenjoDpoofdujpoHfuJogp
NqsBenjoSfhjtufsDpoofdujpoOpujgjdbujpo
NqsBenjoCvggfsGsff
`SPVUFS`JOUFSGBDF`UZQF
xt{UsbotqpsuObnf
NQS`JOUFSGBDF`DPOOFDUJPO`GBJMVSF
exSfnpufUfsnjobufSfbtpo
`NQS`JOUFSGBDF`3
NqsDpogjhJoufsgbdfDsfbuf
`QQQ`JQYDQ`JOGP
QQQ`DDQ`FODSZQUJPO67CJU
SPVUFS`DPOOFDUJPO`TUBUF
NqsBenjoJoufsgbdfEfmfuf
NQS`JOUFSGBDF`EJBMPVU`IPVST`SFTUSJDUJPO
QJE`JQY
QQQ`MDQ`DIBQ`NE6
BUBEESFTTMFO
QSBT`DPOOFDUJPO`2
`NQS`USBOTQPSU`1
NqsTfuvqJqJoJqJoufsgbdfGsjfoemzObnfEfmfuf
NQS`NbyEfwjdfUzqf
exDvtupnBvuiLfz
NQSJP`JqTfdQsfTibsfeLfz
QJE`OCG
SBTDDQDB`TUBD
NQS`WT`M3uqGjstu
xt{JoufsgbdfObnf
xt{QipofOvncfs
exFodszqujpoUzqf
NQSOQ`Jq
xt{NfejbObnf
NQSJP`EjtbcmfMdqFyufotjpot
xt{VtfsObnf
cgQsjwjmfhf3
exOvnQquqQpsut
NQS`NbyJqBeesftt
SBT`VTFS`2
QNQS`JOUFSGBDF`3
SPVUFS`JG`UZQF`EJBMPVU
SBT`GMBHT`QQQ`DPOOFDUJPO
NQS`NbyVtfsEbub
NqsBenjoTfswfsDpoofdu
`QQQ`JOGP
SBT`GMBHT`RVBSBOUJOF`QSFTFOU
NQSJP`TqfdjgjdObnfTfswfst
NqsBenjoHfuJqBeesfttGpsVtfs
NqsJogpCmpdlGjoe
NQSJP`TfdvsfMpdbmGjmft
SBT`DPOOFDUJPO`3
NqsBenjoQpsuDmfbsTubut
NqsBenjoJoufsgbdfUsbotqpsuHfuJogp
exPqujpot
QQQ`MDQ`QBQ
iJgUsbotqpsu
NqsJogpCmpdlSfnpwf
exQpsuDpoejujpo
exVqUjnf
exJemfEjtdpoofduTfdpoet
SBT`IBSEXBSF`PQFSBUJPOBM
NqsBenjoUfsnjobufEmm
QqqJogp
NqsBenjoEfwjdfFovn
exGsbnjohFss
NqsBenjoDpoofdujpoSfnpwfRvbsboujof
NqsJogpDsfbuf
NQS`FU`Pqujpobm
NQSJET`Ejtbcmfe
exTj{f
NqsBenjoNJCFouszHfu
QNQS`JQJOJQ`JOUFSGBDF`1
NqsJogpCmpdlTfu
exDpnqsfttjpoSbujpJo
NqsDpogjhJoufsgbdfUsbotqpsuTfuJogp
NqsBenjoTfoeVtfsNfttbhf
`SBT`VTFS`2
NqsTfuvqJqJoJqJoufsgbdfGsjfoemzObnfDsfbuf
exUpubmQpsut
NqsJogpCmpdlRvfszTj{f
SBT`QPSU`JOJUJBMJ[JOH
NqsBenjoUsbotqpsuHfuJogp
exIbohVqFyusbTbnqmfTfdpoet
cgQsjwjmfhf
NQS`TFSWFS`2
NQSEU`Npefn
SBT`DPOOFDUJPO`1
NqsDpogjhJoufsgbdfUsbotqpsuHfuIboemf
SBT`TFSWFS`IBOEMF
NQS`JOUFSGBDF`2
QQQ`MDQ`DIBQ
SBT`QPSU`MJTUFOJOH
NBY`NFEJB`OBNF
QNQS`DSFEFOUJBMTFY`1
NqsJogpSfnpwfBmm
QQQ`MDQ`DIBQ`NTW3
NQSJP`SfnpufEfgbvmuHbufxbz
NqsBenjoJoufsgbdfTfuJogp
NqsDpogjhUsbotqpsuTfuJogp
NBY`EFWJDFUZQF`OBNF
NqsBenjoJojujbmj{fEmm
QQQ`MDQ`EFT`67
`QQQ`JQDQ`JOGP
NqsBenjoJoufsgbdfHfuJogp
QQQ`DDQ`FODSZQUJPO51CJUPME
SBT`IBSEXBSF`DPOEJUJPO
NqsJogpEfmfuf
QNQS`USBOTQPSU`1
jqbeesEotBmu
