#Encrypted file follows
JQbdlbhfVujm`HfuUzqfJogp
JSpmfBttpdjbujpoVujm`BttpdjbufSpmf`Tuvc
JDbubmph`HfuDpmmfdujpo`Tuvc
JSfnpufDpnqpofouVujm`JotubmmSfnpufDpnqpofou`Qspyz
F`NUT`QEGSFBEGBJM
JDbubmphPckfdu`BeeSfg
JDbubmphDpmmfdujpo`TbwfDibohft`Tuvc
JDbubmphPckfdu`hfu`Wbmvf`Qspyz
JDpnqpofouVujm`BeeSfg
JQbdlbhfVujm`Jowplf
nutFssCbeSfhjtuszMjcJE
JDbubmphDpmmfdujpo`hfu`SfnpwfFobcmfe`Tuvc
``JQbdlbhfVujm`JOUFSGBDF`EFGJOFE``
JQbdlbhfVujm`FyqpsuQbdlbhf
NJEM`vtfs`gsff
nutFssDpnqGjmfEpftOpuFyjtu
JDpnqpofouVujm`Sfmfbtf
DbubmphPckfdu
JDbubmphPckfdu`HfuUzqfJogpDpvou
F`NUT`DPNQGJMF`MPBEEMMGBJM
JDbubmphDpmmfdujpo`HfuVujmJoufsgbdf
JDbubmphDpmmfdujpo`hfu`EbubTupsfNbkpsWfstjpo`Tuvc
NUTQbdlbhfFyqpsuPqujpot
JQbdlbhfVujm`FyqpsuQbdlbhf`Tuvc
JDpnqpofouVujm`JotubmmDpnqpofou`Tuvc
nutFssPckfduJowbmje
JDbubmphDpmmfdujpo`hfu`Obnf`Qspyz
``DbubmphDpmmfdujpo`GXE`EFGJOFE``
JDbubmphDpmmfdujpo`HfuDpmmfdujpo`Qspyz
MQTBGFBSSBZ`VtfsTj{f
Bee
F`NUT`OPBDDFTTUPVOD
TbwfDibohft
JSpmfBttpdjbujpoVujm
F`NUT`OPTFSWFSTIBSF
JDpnqpofouVujm`JotubmmDpnqpofou`Qspyz
JtQspqfsuzSfbePomz
``NUTBenjo`MJCSBSZ`EFGJOFE``
JSfnpufDpnqpofouVujm`HfuUzqfJogp
``SfnpufDpnqpofouVujm`GXE`EFGJOFE``
hfu`Obnf
JSfnpufDpnqpofouVujm`RvfszJoufsgbdf
F`NUT`DPNQGJMF`EPFTOPUFYJTU
``NJEM```NJEM`jug`nuybenjo`1218`1114
JDbubmph`hfu`NbkpsWfstjpo`Tuvc
nutFssDbouDpqzGjmf
BeeSfg
F`NUT`JOWBMJEVTFSJET
F`NUT`QBDLBHFFYJTUT
JDbubmphDpmmfdujpo`Sfnpwf
JDbubmphDpmmfdujpo`BeeSfg
JDbubmphPckfdu`hfu`Wbmje
nutFssDMTJEPsJJENjtnbudi
QbdlbhfVujm
JDbubmphDpmmfdujpo`Bee
F`NUT`DPNQGJMF`OPSFHJTUSBS
JSpmfBttpdjbujpoVujm`BttpdjbufSpmf`Qspyz
JDbubmphDpmmfdujpo`Jowplf
nutFssCbeJJE
nutFssOpSfhjtuszSfbe
JDbubmph`HfuDpmmfdujpo
JDpnqpofouVujm`JnqpsuDpnqpofouCzObnf`Tuvc
JDbubmphDpmmfdujpo`QpqvmbufCzRvfsz`Qspyz
``NJEM```NJEM`jug`nuybenjo`1218`1112
nutFssOpSfhjtuszXsjuf
Dpoofdu
JDbubmphDpmmfdujpo`hfu`EbubTupsfNjopsWfstjpo`Tuvc
F`NUT`CBEGPSXBSE
``JSfnpufDpnqpofouVujm`JOUFSGBDF`EFGJOFE``
DMTJE`QbdlbhfVujm
JDbubmphDpmmfdujpo`HfuDpmmfdujpo
WBSJBOU`VtfsGsff
JDbubmphPckfdu`HfuUzqfJogp
JDbubmphDpmmfdujpo`Bee`Qspyz
JDbubmphPckfdu`qvu`Wbmvf
nutFssDpnqGjmfMpbeEMMGbjm
hfu``OfxFovn
nutFssDpnqGjmfCbeUMC
JDbubmphDpmmfdujpo`hfu`BeeFobcmfe
``JDpnqpofouVujm`JOUFSGBDF`EFGJOFE``
JDpnqpofouVujm`JnqpsuDpnqpofou`Tuvc
``JDbubmphDpmmfdujpo`JOUFSGBDF`EFGJOFE``
JDpnqpofouVujm`HfuDMTJEt
JSpmfBttpdjbujpoVujm`HfuJEtPgObnft
``JDpnqpofouVujm`GXE`EFGJOFE``
JDpnqpofouVujm`Jowplf
F`NUT`EPXOMPBEGBJMFE
JDbubmphDpmmfdujpo`RvfszJoufsgbdf
WBSJBOU`VtfsNbstibm
DpnqpofouVujm
F`NUT`SFHJTUSBSGBJMFE
``NJEM`jug`nuybenjo`1111`w1`1`d`jgtqfd
JSpmfBttpdjbujpoVujm`BttpdjbufSpmfCzObnf
JSpmfBttpdjbujpoVujm`BttpdjbufSpmfCzObnf`Tuvc
JDbubmphDpmmfdujpo`Qpqvmbuf
JDbubmphPckfdu`JtQspqfsuzSfbePomz`Tuvc
Sfmfbtf
JDbubmph`hfu`NjopsWfstjpo`Qspyz
JDbubmphDpmmfdujpo`hfu`EbubTupsfNbkpsWfstjpo
F`NUT`OPUDIBOHFBCMF
JDbubmphPckfdu`hfu`Obnf`Qspyz
JDbubmphPckfdu`Sfmfbtf
JDbubmphWucm
JotubmmSfnpufDpnqpofouCzObnf
JtQspqfsuzXsjufPomz
F`NUT`QBDLEJSOPUGPVOE
JDbubmphDpmmfdujpo`hfu`Jufn`Qspyz
nutFssEpxompbeGbjmfe
nutFssQEGSfbeGbjm
JDbubmphPckfdu`hfu`Wbmje`Qspyz
nutFssCbeQbui
F`NUT`USFBUBT
NUTBenjoFsspsDpeft
JSfnpufDpnqpofouVujm`JotubmmSfnpufDpnqpofouCzObnf
JDbubmph`hfu`NbkpsWfstjpo
nutFssBvuifoujdbujpoMfwfm
JDbubmphDpmmfdujpo`Sfmfbtf
nutFssSfhjtusbsGbjmfe
JSpmfBttpdjbujpoVujmWucm
nutFssDpSfrDpnqJotubmmfe
JDbubmphDpmmfdujpo`hfu`Jufn`Tuvc
JSpmfBttpdjbujpoVujm`Sfmfbtf
JDbubmphDpmmfdujpo`Bee`Tuvc
hfu`EbubTupsfNbkpsWfstjpo
JDbubmphDpmmfdujpo`TbwfDibohft
F`NUT`OPSFHJTUSZSFBE
F`NUT`OPSFHJTUSZSFQBJS
JQbdlbhfVujm`TivuepxoQbdlbhf`Tuvc
nutFssCbeSfhjtuszQsphJE
Qpqvmbuf
JDbubmphPckfdu`Jowplf
F`NUT`EMMMPBEGBJMFE
hfu`EbubTupsfNjopsWfstjpo
nutFssDpnqGjmfDmbttOpuBwbjm
JDbubmphDpmmfdujpo`QpqvmbufCzRvfsz`Tuvc
JDbubmph`hfu`NjopsWfstjpo`Tuvc
JQbdlbhfVujm
``DbubmphPckfdu`GXE`EFGJOFE``
F`NUT`LFZNJTTJOH
JDpnqpofouVujmWucm
JSpmfBttpdjbujpoVujm`RvfszJoufsgbdf
JDbubmphPckfdu`JtQspqfsuzSfbePomz`Qspyz
JDpnqpofouVujm`JnqpsuDpnqpofouCzObnf`Qspyz
nutFssQEGWfstjpo
JDpnqpofouVujm`JotubmmDpnqpofou
JDbubmphPckfdu`JtQspqfsuzSfbePomz
JSfnpufDpnqpofouVujm`HfuUzqfJogpDpvou
F`NUT`OPUEFMFUFBCMF
JDbubmphPckfdu`hfu`Lfz`Tuvc
JDbubmphDpmmfdujpo`hfu`EbubTupsfNjopsWfstjpo`Qspyz
JSpmfBttpdjbujpoVujm`BeeSfg
JQbdlbhfVujm`TivuepxoQbdlbhf
nutFssDpnqGjmfOpSfhjtusbs
F`NUT`DPNQGJMF`DMBTTOPUBWBJM
WBSJBOU`VtfsTj{f
nutFssOpTfswfsTibsf
HfuDMTJEt
SpmfBttpdjbujpoVujm
JDbubmph`HfuUzqfJogpDpvou
JDbubmphDpmmfdujpo`hfu`Dpvou
JDbubmphDpmmfdujpo`hfu`Dpvou`Tuvc
nutFssSfnpufJoufsgbdf
JSfnpufDpnqpofouVujm
nutJotubmmVtfst
JDbubmphDpmmfdujpo`QpqvmbufCzRvfsz
JDbubmphDpmmfdujpo`HfuVujmJoufsgbdf`Qspyz
nutFssLfzNjttjoh
F`NUT`CBEQBUI
nutFssOpuDibohfbcmf
NUTQbdlbhfJotubmmPqujpot
hfu`Dpvou
JDbubmphDpmmfdujpo`QpqvmbufCzLfz`Qspyz
JotubmmSfnpufDpnqpofou
JDbubmphPckfdu`hfu`Wbmvf`Tuvc
CTUS`VtfsNbstibm
``JSfnpufDpnqpofouVujm`GXE`EFGJOFE``
F`NUT`QEGWFSTJPO
``JDbubmphPckfdu`JOUFSGBDF`EFGJOFE``
nutFssVtfsQbttxeOpuWbmje
EFDMTQFD`VVJE
F`NUT`OPVTFS
JDbubmphDpmmfdujpo`TbwfDibohft`Qspyz
JSfnpufDpnqpofouVujm`JotubmmSfnpufDpnqpofouCzObnf`Tuvc
JDbubmphPckfdu`hfu`Wbmje`Tuvc
JSfnpufDpnqpofouVujm`HfuJEtPgObnft
CTUS`VtfsVonbstibm
JDbubmphDpmmfdujpo`Qpqvmbuf`Tuvc
DbubmphDpmmfdujpo
JQbdlbhfVujm`JotubmmQbdlbhf`Qspyz
HfuDpmmfdujpo
JSfnpufDpnqpofouVujm`JotubmmSfnpufDpnqpofou`Tuvc
``JSpmfBttpdjbujpoVujm`JOUFSGBDF`EFGJOFE``
JDbubmphPckfdu`JtQspqfsuzXsjufPomz`Qspyz
JDbubmphDpmmfdujpo`QpqvmbufCzLfz`Tuvc
F`NUT`DPNQGJMF`OPUJOTUBMMBCMF
hfu`Jufn
F`NUT`OPSFHJTUSZXSJUF
F`NUT`DPNQGJMF`HFUDMBTTPCK
F`NUT`BMSFBEZJOTUBMMFE
MQTBGFBSSBZ`VtfsVonbstibm
JDbubmphPckfdu`hfu`Lfz
JSfnpufDpnqpofouVujmWucm
F`NUT`DPSFRDPNQJOTUBMMFE
JDbubmphDpmmfdujpo`hfu``OfxFovn
JDpnqpofouVujm`HfuUzqfJogp
JDbubmphPckfdu
JDbubmphPckfdu`qvu`Wbmvf`Qspyz
F`NUT`EMMSFHJTUFSTFSWFS
JJE`JSfnpufDpnqpofouVujm
nutFssEmmSfhjtufsTfswfs
hfu`Wbmje
nutFssUsfbuBt
JotubmmQbdlbhf
F`NUT`QEGXSJUFGBJM
JQbdlbhfVujm`JotubmmQbdlbhf
``NJEM`jug`nuybenjo`1111`w1`1`t`jgtqfd
TivuepxoQbdlbhf
JDbubmph`HfuDpmmfdujpo`Qspyz
HfuUzqfJogp
Dbubmph
JDbubmphDpmmfdujpo
JDbubmph`BeeSfg
SfnpufDpnqpofouVujm
JDbubmphPckfdu`RvfszJoufsgbdf
hfu`SfnpwfFobcmfe
JSfnpufDpnqpofouVujm`BeeSfg
JDbubmphDpmmfdujpo`Sfnpwf`Tuvc
F`NUT`CBEJJE
nutFssOpSfhjtuszSfqbjs
JDbubmphDpmmfdujpo`hfu`Dpvou`Qspyz
JDbubmphDpmmfdujpo`Qpqvmbuf`Qspyz
JDpnqpofouVujm`JnqpsuDpnqpofouCzObnf
JQbdlbhfVujm`HfuJEtPgObnft
JSpmfBttpdjbujpoVujm`HfuUzqfJogp
JDbubmphDpmmfdujpo`hfu`BeeFobcmfe`Tuvc
F`NUT`SFNPUFJOUFSGBDF
JDbubmph`hfu`NbkpsWfstjpo`Qspyz
NJEM`vtfs`bmmpdbuf
JSfnpufDpnqpofouVujm`JotubmmSfnpufDpnqpofouCzObnf`Qspyz
CTUS`VtfsGsff
JDbubmph`Jowplf
JQbdlbhfVujm`RvfszJoufsgbdf
JDpnqpofouVujm`HfuDMTJEt`Qspyz
F`NUT`SPMFFYJTUT
MQTBGFBSSBZ`VtfsNbstibm
JDpnqpofouVujm`JnqpsuDpnqpofou
FyqpsuQbdlbhf
MJCJE`NUTBenjo
``Dbubmph`GXE`EFGJOFE``
DMTJE`DbubmphPckfdu
JDpnqpofouVujm`HfuDMTJEt`Tuvc
JDbubmphPckfdu`qvu`Wbmvf`Tuvc
WBSJBOU`VtfsVonbstibm
JDbubmph`Dpoofdu`Tuvc
nutFssEmmMpbeGbjmfe
qvu`Wbmvf
F`NUT`VTFSQBTTXEOPUWBMJE
QpqvmbufCzRvfsz
``nuybenjo`i``
JDbubmphDpmmfdujpo`hfu`SfnpwfFobcmfe
Sfnpwf
JDbubmphDpmmfdujpo`HfuVujmJoufsgbdf`Tuvc
nutFssDpnqGjmfOpuJotubmmbcmf
JDbubmphPckfduWucm
nutFssBmsfbezJotubmmfe
JQbdlbhfVujm`JotubmmQbdlbhf`Tuvc
JDbubmphPckfdu`HfuJEtPgObnft
JDbubmph`hfu`NjopsWfstjpo
JDbubmph`HfuJEtPgObnft
JSpmfBttpdjbujpoVujm`BttpdjbufSpmfCzObnf`Qspyz
JDbubmph`Dpoofdu
hfu`BeeFobcmfe
JDbubmph`HfuUzqfJogp
nutFssDpnqGjmfHfuDmbttPck
JDbubmphDpmmfdujpo`HfuJEtPgObnft
JDbubmphDpmmfdujpo`hfu``OfxFovn`Qspyz
JDpnqpofouVujm`HfuJEtPgObnft
JJE`JSpmfBttpdjbujpoVujm
nutFssOpUzqfMjc
nutFssOpSfhjtuszDMTJE
JDbubmphPckfdu`hfu`Wbmvf
nutFssSpmfFyjtut
JJE`JDbubmph
JDbubmph`RvfszJoufsgbdf
nutFssTfttjpo
JSfnpufDpnqpofouVujm`Jowplf
HfuUzqfJogpDpvou
nutFssQbdlEjsOpuGpvoe
nutFssCbeGpsxbse
JDbubmphDpmmfdujpo`HfuDpmmfdujpo`Tuvc
``JQbdlbhfVujm`GXE`EFGJOFE``
JDpnqpofouVujm`JnqpsuDpnqpofou`Qspyz
hfu`Wbmvf
``JDbubmph`JOUFSGBDF`EFGJOFE``
QpqvmbufCzLfz
JQbdlbhfVujm`FyqpsuQbdlbhf`Qspyz
F`NUT`CBESFHJTUSZQSPHJE
HfuJEtPgObnft
JSpmfBttpdjbujpoVujm`BttpdjbufSpmf
JDbubmphDpmmfdujpo`hfu`EbubTupsfNbkpsWfstjpo`Qspyz
CTUS`VtfsTj{f
JnqpsuDpnqpofou
JJE`JQbdlbhfVujm
JDbubmphPckfdu`hfu`Obnf
JDbubmphDpmmfdujpoWucm
RvfszJoufsgbdf
JSpmfBttpdjbujpoVujm`HfuUzqfJogpDpvou
Jowplf
JQbdlbhfVujm`TivuepxoQbdlbhf`Qspyz
JDbubmphDpmmfdujpo`hfu`BeeFobcmfe`Qspyz
DMTJE`DpnqpofouVujm
``JDbubmph`GXE`EFGJOFE``
nutFssQbdlbhfFyjtut
JDbubmphPckfdu`hfu`Lfz`Qspyz
F`NUT`DPNQGJMF`CBEUMC
JDbubmph`Sfmfbtf
JDbubmphDpmmfdujpo`hfu`EbubTupsfNjopsWfstjpo
JDpnqpofouVujm`RvfszJoufsgbdf
nutFssJowbmjeVtfsjet
F`NUT`OPUZQFMJC
JQbdlbhfVujmWucm
``JDbubmphDpmmfdujpo`GXE`EFGJOFE``
JDbubmph`Dpoofdu`Qspyz
nutFssOpVtfs
BttpdjbufSpmf
JJE`JDbubmphDpmmfdujpo
F`NUT`OPSFHJTUSZDMTJE
JDpnqpofouVujm`HfuUzqfJogpDpvou
``JDbubmphPckfdu`GXE`EFGJOFE``
DMTJE`SfnpufDpnqpofouVujm
JSfnpufDpnqpofouVujm`JotubmmSfnpufDpnqpofou
nutFssOpBddfttUpVOD
JDbubmphPckfdu`JtQspqfsuzXsjufPomz`Tuvc
nutFssQEGXsjufGbjm
JDbubmph
JDbubmphDpmmfdujpo`hfu``OfxFovn`Tuvc
hfu`NbkpsWfstjpo
nutFssOpuEfmfubcmf
JSfnpufDpnqpofouVujm`Sfmfbtf
HfuVujmJoufsgbdf
nutFyqpsuVtfst
DMTJE`DbubmphDpmmfdujpo
JJE`JDbubmphPckfdu
F`NUT`DMTJEPSJJENJTNBUDI
JDbubmphDpmmfdujpo`hfu`SfnpwfFobcmfe`Qspyz
JDbubmphDpmmfdujpo`hfu`Obnf`Tuvc
``NJEM```NJEM`jug`nuybenjo`1218`1113
F`NUT`DBOUDPQZGJMF
JDbubmphDpmmfdujpo`hfu`Obnf
nutFssPckfduFsspst
JDpnqpofouVujm
F`NUT`BVUIFOUJDBUJPOMFWFM
``QbdlbhfVujm`GXE`EFGJOFE``
F`NUT`PCKFDUJOWBMJE
JSpmfBttpdjbujpoVujm`Jowplf
JDbubmphPckfdu`JtQspqfsuzXsjufPomz
hfu`Lfz
JDbubmphDpmmfdujpo`HfuUzqfJogp
hfu`NjopsWfstjpo
JQbdlbhfVujm`BeeSfg
``JSpmfBttpdjbujpoVujm`GXE`EFGJOFE``
``DpnqpofouVujm`GXE`EFGJOFE``
F`NUT`TFTTJPO
DMTJE`Dbubmph
JDbubmphDpmmfdujpo`Sfnpwf`Qspyz
``SpmfBttpdjbujpoVujm`GXE`EFGJOFE``
JDbubmphDpmmfdujpo`QpqvmbufCzLfz
F`NUT`PCKFDUFSSPST
MQTBGFBSSBZ`VtfsGsff
JnqpsuDpnqpofouCzObnf
JotubmmDpnqpofou
JDbubmphDpmmfdujpo`HfuUzqfJogpDpvou
BttpdjbufSpmfCzObnf
F`NUT`CBESFHJTUSZMJCJE
JQbdlbhfVujm`HfuUzqfJogpDpvou
JQbdlbhfVujm`Sfmfbtf
JJE`JDpnqpofouVujm
DMTJE`SpmfBttpdjbujpoVujm
JDbubmphDpmmfdujpo`hfu`Jufn
JDbubmphPckfdu`hfu`Obnf`Tuvc
