#Encrypted file follows
JDpmvnotSpxtfu
ECQSPQWBM`TR`RVBOUJGJFE
ECQSPQWBM`BTZODI`QPQVMBUFPOEFNBOE
JBddfttpsWucm
ECQSPQWBM`PQ`TUSJOH
JECJojujbmj{f`Sfmfbtf
ECQSPQWBM`US`EPOUDBSF
HfuTRMJogp
JJE`JDpnnboeQfstjtu
JDpowfsuUzqf`DboDpowfsu
ECUZQF`SFTFSWFE
JECDsfbufDpnnboe
JFsspsSfdpset`SfnpufHfuFsspsJogp`Tuvc
JNvmujqmfSftvmut`SfnpufHfuSftvmu`Tuvc
ECQSPQGMBHT`EBUBTPVSDFDSFBUF
NENFNCFS`UZQF`VOLOPXO
ECTPSU
DSFTUSJDUJPOT`ECTDIFNB`WJFX`UBCMF`VTBHF
JSpxtfu`Sfmfbtf
qjje
HfuNfncfstijqt
ECBDDFTTPS`SPXEBUB
ECQSPQ`BVUI`FODSZQU`QBTTXPSE
ECSPXTUBUVT`F`JOUFHSJUZWJPMBUJPO
JUsvtuffHspvqBenjoWucm
ECQSPQTUBUVTFOVN32
JSpxtfuTdspmm`HfuBqqspyjnbufQptjujpo`Qspyz
ECQSPQFOVN
ECQFOEJOHTUBUVT`VODIBOHFE
ECVQEFMSVMF
NEQSPQWBM`NE`CFGPSF
HfuTubuvt
ECDPNQBSFPQT`MF
ECDPMVNO`EPNBJOOBNF
ECQSPQ`JOEFY`VOJRVF
ECQSPQWBM`CE`YUSBOTBDUJPO
JECTdifnbSpxtfu`HfuTdifnbt`Qspyz
ECQSPQ`JDpowfsuUzqf
JDpnnboeXjuiQbsbnfufst`BeeSfg
JFsspsSfdpsetWucm
JECQspqfsujft`HfuQspqfsujft
ECQSPQ`QSPWJEFSPMFECWFS
NEGG`VOEFSMJOF
EspqJoefy
NEQSPQWBM`OM`OBNFEMFWFMT
JDpmvnotSpxtfu`SfnpufHfuDpmvnotSpxtfu`Tuvc
HfuGjmufsCjoejoht
EC`DPVOUVOBWBJMBCMF
ECDPNQBSFPQT`OPUCFHJOTXJUI
ECCJOEVSMGMBH`SFBEXSJUF
JNESbohfSpxtfuWucm
JECEbubTpvsdfBenjo`HfuDsfbujpoQspqfsujft`Tuvc
dPckfdut
ECMJUFSBM`RVPUF`TVGGJY
JFsspsSfdpset`SfnpufHfuDvtupnFsspsPckfdu`Tuvc
ECQSPQ`JSpxtfuCpplnbsl
JSpxtfuJefoujuz`SfnpufJtTbnfSpx`Qspyz
ECQSPQWBM`UT`IJTUPHSBN
DSFTUSJDUJPOT`ECTDIFNB`DBUBMPHT
NEQSPQWBM`NTG`XUE
PG`TIBSF`DPNQBU
ECTUBUVT`F`CBEBDDFTTPS
JDsfbufSpx
ECMJUFSBM`RVPUF`QSFGJY
ECQSPQ`OPUJGZSPXVOEPDIBOHF
ECQSPQ`OVMMDPMMBUJPO
ECQSPQWBM`GV`UBCMF
ECQSPQWBM`GV`DBUBMPH
JDpnnboe`RvfszJoufsgbdf
ECQSPQ`TFSWFS`OBNF
JSpxtfuJogp`Sfmfbtf
JSpxtfuMpdbuf`Dpnqbsf`Qspyz
pcMfohui
ECQSPQWBM`JO`JHOPSFOVMM
JJE`JPqfoSpxtfu
JSpxtfuJefoujuz`BeeSfg
Nje43
DSFTUSJDUJPOT`ECTDIFNB`DPOTUSBJOU`DPMVNO`VTBHF
JDpnnboeQfstjtu`EfmfufDpnnboe`Qspyz
JECBtzodiOpujgz`PoTupq`Qspyz
ECQSPQ`PUIFSJOTFSU
ECSPXDPM`QBSFOUOBNF
ECQSPQWBM`OQ`EJEFWFOU
tjho
JDpnnboeQspqfsujft`Sfmfbtf
JSpxtfuDibqufsNfncfs`JtSpxJoDibqufs`Qspyz
ECPCKFDU`USBOTMBUJPO
ECDPMVNOGMBHT`JTEFGBVMUTUSFBN
JJoefyEfgjojujpo`SfnpufEspqJoefy`Qspyz
ECTDIFNB`GPSFJHO`LFZT
JDpmvnotSpxtfu`Sfmfbtf
ECQSPQ`CMPDLJOHTUPSBHFPCKFDUT
ECCJOEVSMTUBUVT`T`PL
ECQSPQWBM`TUHN`EJSFDU
ECQSPQWBM`UD`EEM`JHOPSF
ECEFGFSSBCJMJUZ`EFGFSSBCMF
ECQSPQPQUJPOT`TFUJGDIFBQ
``JECQspqfsujft`GXE`EFGJOFE``
ECCJOEVSMGMBH`EFMBZGFUDITUSFBN
EC`OVMM`ISPX
ECCZUFPGGTFU
ECDPMVNOEFTD
JPckfduBddfttDpouspm`TfuPckfduBddfttSjhiut`Qspyz
QFSN`VQEBUF
ECCJOEVSMGMBH
JWjfxTpsu`HfuTpsuPsefs
ECMJUFSBMFOVN31
GjoeDfmm
ECTUBUVT`F`TDIFNBWJPMBUJPO
ubhSNUQBDL
JSpxtfuOpujgz`PoSpxDibohf
JSpxtfuJefoujuz`JtTbnfSpx`Tuvc
NENFBTVSF`BHHS`TUE
ECCJOETUBUVT`VOTVQQPSUFEDPOWFSTJPO
njovuf
JDpmvnotJogp`SfnpufNbqDpmvnoJEt`Qspyz
ECQSPQ`DPM`GJYFEMFOHUI
JUsbotbdujpoMpdbm`SfnpufTubsuUsbotbdujpo`Tuvc
JSpxtfuVqebuf`HfuSpxTubuvt
ECQSPQWBM`QU`QHVJE`QSPQJE
ECQSPQ`JSpxtfuDibohf
ECTDIFNB`JOEFYFT
JFsspsMpplvq`Sfmfbtf
ECQSPQ`QSPWJEFSNFNPSZ
ECQSPQWBM`PP`TDPQFE
QFSN`EFMFUF
ECQBSBNUZQF`JOQVU
JECDsfbufDpnnboe`DsfbufDpnnboe`Tuvc
JUbcmfDsfbujpo
ECQSPQFOVN31
``pmfec`i``
qDpotusbjouJE
ECNPWF`BUPNJD
JPqfoSpxtfu`SfnpufPqfoSpxtfu`Tuvc
JJE`JSpxtfuWjfx
JUsvtuffBenjo`HfuUsvtuffQspqfsujft`Tuvc
JSpxtfuFybduTdspmm`HfuFybduQptjujpo
HfuNfncfst
ECQPTJUJPO`CPG
ECQSPQWBM`US`BCPSU`OP
ECQSPQWBM`TRM`PECD`DPSF
JDpnnboeQfstjtu`HfuDvssfouDpnnboe`Qspyz
JSpxtfuMpdbuf`SftubsuQptjujpo
QFSN`SFBE
SfgsftiWjtjcmfEbub
PG`DBODFM
JECJojujbmj{f`SfnpufJojujbmj{f`Qspyz
ECBTZODIQIBTF`JOJUJBMJ[BUJPO
JSpx`Sfmfbtf
JSpxtfuDvssfouJoefy`TfuSbohf
ECQSPQ`PSEFSCZDPMVNOTJOTFMFDU
ECQSPQWBM`DT`VOJOJUJBMJ[FE
JDpnnboeQspqfsujft`SfnpufHfuQspqfsujft`Tuvc
ECDPMVNO`OBNF
HfuFsspsEftdsjqujpo
JJE`JSpxtfuOpujgz
JUbcmfEfgjojujpoXjuiDpotusbjout`DsfbufUbcmfXjuiDpotusbjout`Tuvc
ECQSPQTUBUVT`PL
JDpnnboeUfyu`HfuDpnnboeUfyu`Tuvc
JTRMFsspsJogp`BeeSfg
JHfuEbubTpvsdf`BeeSfg
Sftfu
JJE`JDpmvnotSpxtfu
JNvmujqmfSftvmutWucm
JECQspqfsujft`TfuQspqfsujft`Tuvc
ECSPXTUBUVT`T`OPDIBOHF
JECJogp`HfuLfzxpset
ECQSPQWBM`TRM`BOTJ:3`GVMM
JDpnnboeQspqfsujft`RvfszJoufsgbdf
JSpxQptjujpo`SfnpufDmfbsSpxQptjujpo`Tuvc
JSpxtfuVqebuf`HfuQfoejohSpxt
ECQSPQ`TFTT`BVUPDPNNJUJTPMFWFMT
ECQSPQ`DIBOHFJOTFSUFESPXT
JJoefyEfgjojujpo`EspqJoefy`Qspyz
JSpxtfuTdspmm`HfuBqqspyjnbufQptjujpo`Tuvc
ECDPNNBOEQFSTJTUGMBH`EFGBVMU
DsfbufWjfx
ECQSPQWBM`IU`EJGGFSFOU`QSPWJEFST
JJE`JBmufsJoefy
JSpx`HfuTpvsdfSpxtfu
dQSPQWBSJBOU
NENFNCFS`UZQF`BMM
JDpnnboeQfstjtu`EfmfufDpnnboe
ECQBSBNUZQF`JOQVUPVUQVU
JTfdvsjuzJogp`HfuDvssfouUsvtuff
ECHVJE`SPXVSM
WBSJBOU`VtfsVonbstibm
ECSPXDPM`JTSPPU
ECDPNQBSF`OF
NENFBTVSF`BHHS`DPVOU
JSpxtfuVqebufWucm
ECEFMFUF`BUPNJD
ECQSPQWBM`MN`JOUFOU
ECMJUFSBM`JOWBMJE
NEMFWFM`UZQF`UJNF`XFFLT
JBddfttps
JDpnnboeXjuiQbsbnfufst`SfnpufTfuQbsbnfufsJogp`Qspyz
JNESbohfSpxtfu`HfuSbohfSpxtfu
BeeSfgSpxt
ECDJEHVJE
JDpnnboeUfyu`BeeSfg
JDpnnboeQspqfsujft`TfuQspqfsujft`Tuvc
``JSpxtfuSfgsfti`GXE`EFGJOFE``
ECQSPQWBM`VQ`JOTFSU
ECSFBTPO`SPX`VQEBUF
QFSN`XSJUFEFTJHO
``JECBtzodiTubuvt`GXE`EFGJOFE``
JUsvtuffBenjo`TfuUsvtuffQspqfsujft`Qspyz
ECQSPQ`NVMUJQMFQBSBNTFUT
JTdpqfePqfsbujpot`Efmfuf`Tuvc
EC`QSPU`MFWFM`QLU
JUbcmfEfgjojujpo`SfnpufDsfbufUbcmf`Tuvc
NEBYJT`SPXT
JSpxtfuOpujgz`PoGjfmeDibohf`Qspyz
EC`MSFTFSWF
JTfttjpoQspqfsujft
ECTUBUVT`T`USVODBUFE
ECQSPQ`OPUJGJDBUJPOQIBTFT
JUbcmfEfgjojujpoXjuiDpotusbjout`EspqDpmvno
ECQSPQ`JQbsfouSpxtfu
JWjfxSpxtfu`BeeSfg
JDpnnboeUfyu`SfnpufTfuDpnnboeUfyu`Tuvc
JJE`JWjfxGjmufs
``JWjfxDibqufs`GXE`EFGJOFE``
``JTRMFsspsJogp`JOUFSGBDF`EFGJOFE``
ECQSPQWBM`TR`DPSSFMBUFETVCRVFSJFT
NEMFWFM`UZQF`BMM
JDpnnboe`HfuECTfttjpo`Tuvc
NEQSPQWBM`ONF`BMMEJNFOTJPOT
JECQspqfsujft`SfnpufHfuQspqfsujft`Qspyz
ECTDIFNB`QSPDFEVSFT
WBSJBOU`VtfsGsff
JSpxtfuGjoeWucm
ECTUBUVT`T`JTOVMM
JTdpqfePqfsbujpot`Npwf
VosfhjtufsQspwjefs
JNvmujqmfSftvmut`Sfmfbtf
NEQSPQ`NFNCFS
JWjfxTpsu`SfnpufTfuTpsuPsefs`Tuvc
JJE`JDpmvnotJogp3
ECQSPQ`PQFOSPXTFUTVQQPSU
JUbcmfEfgjojujpo`SfnpufEspqUbcmf`Tuvc
``JUbcmfEfgjojujpoXjuiDpotusbjout`JOUFSGBDF`EFGJOFE``
exSftfswfe
JSpxtfuMpdbuf`Dpnqbsf
ECQSPQGMBHT`EBUBTPVSDFJOGP
ECDPOTUSBJOUUZQF`DIFDL
ECTPSUFOVN
ECSPXDPVOU
ECQSPQ`TVQQPSUFEUYOJTPMFWFMT
TbwfDpnnboe
NEQSPQWBM`NTG`ESJMMEPXOMFWFM
JPqfoSpxtfu`RvfszJoufsgbdf
JSpxtfuDibohf`EfmfufSpxt`Tuvc
JSpxtfu`BeeSfgSpxt`Tuvc
vmFyufotjpo
JSpxtfuJefoujuz`JtTbnfSpx`Qspyz
JECEbubTpvsdfBenjo`SfnpufDsfbufEbubTpvsdf`Tuvc
``JECBtzodiTubuvt`JOUFSGBDF`EFGJOFE``
JUsvtuffBenjo`Sfmfbtf
ECQPTJUJPOGMBHTFOVN
NEBYJTJOGP`HFUBU
qJTfrTusfbn
JECTdifnbSpxtfu`HfuSpxtfu`Qspyz
ECSBOHF`FYDMVTJWFTUBSU
HfuSftvmu
ECQSPQTFU`TFTTJPO
DSFTUSJDUJPOT`NETDIFNB`EJNFOTJPOT
HfuTpvsdftSpxtfu
JPckfduBddfttDpouspm`TfuPckfduBddfttSjhiut`Tuvc
JUbcmfEfgjojujpo`EspqDpmvno`Tuvc
JSpxtfuFybduTdspmm`RvfszJoufsgbdf
ECUZQF`XTUS
JSpxtfuJoefy`BeeSfg
JWjfxDibqufs`HfuTqfdjgjdbujpo
JHfuEbubTpvsdfWucm
JEFOUJGJFS`TEL`FSSPS
JUbcmfEfgjojujpoXjuiDpotusbjout`EspqDpotusbjou
NEQSPQWBM`WJTVBM`NPEF`WJTVBM
JUsvtuffHspvqBenjo`EfmfufNfncfs
JFsspsMpplvq`SfnpufSfmfbtfFsspst`Tuvc
JJE`JDpnnboeQsfqbsf
``JTpvsdftSpxtfu`GXE`EFGJOFE``
QVMPOHMPOH
JSpxtfuDvssfouJoefy`TfuJoefy`Qspyz
ECNPWFGMBHT
JWjfxSpxtfu
JDpnnboeQsfqbsf`SfnpufQsfqbsf`Tuvc
JECJogp`HfuMjufsbmJogp
NEQSPQWBM`NOG`ESJMMEPXONFNCFSUPQ
ECQSPQWBM`TUHN`TIBSF`EFOZ`OPOF
JBddfttps`SfmfbtfBddfttps`Qspyz
ECHVJE`ETP
EC`QU`VOLOPXO
ECLJOE`QSPQJE
``SFRVJSFE`SQDOES`I`WFSTJPO``
JWjfxDibqufs`PqfoWjfxDibqufs`Qspyz
ECDPQZ`BTZOD
JSfhjtufsQspwjefs`VosfhjtufsQspwjefs`Qspyz
DpotusbjouUzqf
ECQSPQGMBHT`DPMVNOPL
ECSFBTPO
JSpxtfuWucm
NEQSPQWBM`NG`DSFBUF`OBNFETFUT
NEQSPQWBM`NPR`EJNIJFS`MFWFM
ECSPXDPM`DPOUFOUDMBTT
DSFTUSJDUJPOT`NETDIFNB`GVODUJPOT
ECQSPQ`DPMVNOEFGJOJUJPO
ECQSPQWBM`TRM`OPOF
JDpnnboeXjuiQbsbnfufst`SfnpufTfuQbsbnfufsJogp`Tuvc
JUbcmfEfgjojujpo`BeeDpmvno`Tuvc
JSpxtfuMpdbuf`HfuSpxtCzCpplnbsl`Qspyz
``JBmufsJoefy`GXE`EFGJOFE``
NEQSPQWBM`SS`SFBEPOMZ
ECSFBTPOFOVN
ubhECDPMVNOEFTD
JBmufsUbcmfWucm
JTfdvsjuzJogp`HfuPckfduUzqft`Qspyz
JDibqufsfeSpxtfu`BeeSfgDibqufs`Qspyz
``NJEM`jug`pmfec`1417`w1`1`d`jgtqfd
JJE`JSpxtfuJefoujuz
ECTDIFNB`QSPDFEVSF`QBSBNFUFST
NEQSPQWBM`NPR`DBUBMPH`DVCF
JECTdifnbSpxtfu`HfuSpxtfu`Tuvc
``NJEM`jug`pmfec`1431`w1`1`t`jgtqfd
ECUZQFGPS`ECSPXDPVOU
JDpnnboeQspqfsujftWucm
ECQSPQ`NBYSPXTJ[FJODMVEFTCMPC
ECDPMVNO`NBZTPSU
ECDPMVNO`IBTEFGBVMU
ECQSPQWBM`TRM`BOTJ:3`JOUFSNFEJBUF
JSpxtfuCpplnbsl`RvfszJoufsgbdf
``NJEM`jug`pmfec`1445`w1`1`t`jgtqfd
ECDPOWFSUGMBHT`QBSBNFUFS
JCjoeSftpvsdf`Sfmfbtf
JJE`JSpxtfuSftzodi
ECDPMVNO`JEOBNF
JDpnnboeQfstjtu`RvfszJoufsgbdf
ECQSPQWBM`MN`SJUF
ECMJUFSBM`UFYU`DPNNBOE
ECUZQF`CPPM
JSpxtfuJoefy`Sfmfbtf
JECTdifnbSpxtfu`HfuSpxtfu
``JSpxtfuJogp`JOUFSGBDF`EFGJOFE``
HfuDsfbujpoQspqfsujft
JTfttjpoQspqfsujft`SfnpufHfuQspqfsujft`Tuvc
``JTfttjpoQspqfsujft`GXE`EFGJOFE``
JFsspsSfdpset`HfuSfdpseDpvou
JHfuSpx`HfuSpxGspnISPX`Qspyz
NENFNCFS`UZQF`SFTFSWF4
ECCJOEJOH
DSFTUSJDUJPOT`ECTDIFNB`QSPDFEVSFT
dQbsbnTfut
JDsfbufSpx`SfnpufDsfbufSpx`Tuvc
JFsspsSfdpset`HfuSfdpseDpvou`Qspyz
ECQSPQWBM`DC`QSFTFSWF
ECDPMVNOEFTDGMBHT`XUZQF
JDpnnboeQsfqbsf`Sfmfbtf
ECQSPQWBM`OD`MPX
ECQBSBNGMBHTFOVN
JSpx`RvfszJoufsgbdf
ECQSPQWBM`JU`DPOUFOU
ECHVJE`DPNNBOE
HfuDvssfouUsvtuff
ECSBOHF
ECQSPQ`GJOEDPNQBSFPQT
JJE`JSpxtfuMpdbuf
JSpxDibohf`RvfszJoufsgbdf
EC`BMM`FYDFQU`MJLF
JJE`JJoefyEfgjojujpo
ECSBOHFFOVN
ECNFNPXOFS`QSPWJEFSPXOFE
EC`OVMM`IDIBQUFS
JBmufsUbcmf`RvfszJoufsgbdf
ECUZQF`FNQUZ
TfuPckfduBddfttSjhiut
JECDsfbufTfttjpo`DsfbufTfttjpo`Tuvc
CTUS`VtfsVonbstibm
JECJogp`RvfszJoufsgbdf
NEBYJT`TMJDFST
ECQSPQ`QSPDFEVSFUFSN
JTfttjpoQspqfsujft`HfuQspqfsujft
JBmufsUbcmf`BmufsDpmvno
EC`EXSFTFSWF
JDibqufsfeSpxtfu`RvfszJoufsgbdf
ECQSPQ`JOJU`UJNFPVU
ECQSPQWBM`DV`ENM`TUBUFNFOUT
MQTBGFBSSBZ`VtfsVonbstibm
JHfuTfttjpo`Sfmfbtf
JUsvtuffBenjo`TfuUsvtuffQspqfsujft`Tuvc
ECSPXDPM`JTSFBEPOMZ
ECQSPQ`JOEFY`OVMMDPMMBUJPO
HfuSpxTubuvt
ECTPVSDFUZQF`FOVNFSBUPS
``JWjfxTpsu`JOUFSGBDF`EFGJOFE``
JUsvtuffHspvqBenjo`BeeNfncfs`Qspyz
ECQSPQTFU`EBUBTPVSDF
JECTdifnbSpxtfu`SfnpufHfuTdifnbt`Qspyz
JSpxtfuDibohf`TfuEbub`Tuvc
EFDJNBM`TFU[FSP
HfuSpxGspnISPX
JQbsfouSpxtfu`HfuDijmeSpxtfu
QFSN`JOTFSU
ECBTZODIQIBTF`DBODFMFE
ECQSPQ`USVTUFF`BVUIFOUJDBUJPO
ECXBUDISFHJPO`OVMM
ECTDIFNB`TDIFNBUB
ECQSPQWBM`UD`ENM
JWjfxSpxtfu`SfnpufPqfoWjfxSpxtfu`Qspyz
Sfmfbtf
JSpxtfuFybduTdspmm`HfuSpxtCzCpplnbsl
JJE`JSpxtfuDibohf
JJE`JTpvsdftSpxtfu
ECTUBUVT`F`QFSNJTTJPOEFOJFE
NENFBTVSF`BHHS`DBMDVMBUFE
ECDPMVNO`EPNBJODBUBMPH
ECQSPQ`JOJU`JNQFSTPOBUJPO`MFWFM
JSpxQptjujpo`HfuSpxQptjujpo`Tuvc
Pqfo
BmufsDpmvno
exGmbht
JSpxtfuDvssfouJoefy`BeeSfg
ECDPMVNO`UZQFJOGP
WBSJBOU`VtfsNbstibm
ECQSPQWBM`CE`JOUSBOTBDUJPO
ECQSPQ`JSpxDibohf
``JDpnnboeQsfqbsf`JOUFSGBDF`EFGJOFE``
JSpxtfuDibqufsNfncfs`RvfszJoufsgbdf
ECUZQF`ECUJNF
MQTBGFBSSBZ`VtfsNbstibm
ECWFDUPS
ECPSEJOBM
JBddfttps`SfmfbtfBddfttps
JECEbubTpvsdfBenjo`HfuDsfbujpoQspqfsujft
Vojojujbmj{f
DSFTUSJDUJPOT`ECTDIFNB`UBCMF`QSJWJMFHFT
JTdpqfePqfsbujpotWucm
``JUsvtuffBenjo`JOUFSGBDF`EFGJOFE``
ECBTZODIQIBTF
ECUZQF`VEU
ECQSPQ`JOEFY`GJMMGBDUPS
DsfbufTfttjpo
ubhECJNQMJDJUTFTTJPO
ECCJOEVSMGMBH`BTZODISPOPVT
JSpxtfuJoefy`Tffl
ECHVJE`NEY
JFsspsMpplvq`SfnpufHfuFsspsEftdsjqujpo`Qspyz
ECQSPQWBM`US`DPNNJU`ED
``JHfuEbubTpvsdf`GXE`EFGJOFE``
ECQSPQGMBHT`SFRVJSFE
NEMFWFM`UZQF`DBMDVMBUFE
ECQSPQ`ECNTOBNF
NEGG`TUSJLFPVU
ECQSPQ`JOJU`MDJE
JJoefyEfgjojujpoWucm
ubhECCJOEFYU
ECQSPQ`JSpxtfuSftzodi
ECQSPQWBM`DP`DBTFJOTFOTJUJWF
hvjePckfduUzqf
JTfdvsjuzJogp`HfuDvssfouUsvtuff`Qspyz
ECQSPQ`BVUI`JOUFHSBUFE
MPOHMPOH
JJE`JSpx
JBddfttps`DsfbufBddfttps`Tuvc
ECDPOWFSUGMBHT`JTGJYFEMFOHUI
JUsvtuffHspvqBenjo`HfuNfncfst`Qspyz
ECTUBUVT`F`TJHONJTNBUDI
JFsspsMpplvq`RvfszJoufsgbdf
JSfhjtufsQspwjefs`HfuVSMNbqqjoh
JNEGjoe
NEMFWFM`UZQF`VOLOPXO
ECMJUFSBM`UBCMF`OBNF
JHfuTfttjpo`HfuTfttjpo
JECJojujbmj{f`SfnpufVojojujbmj{f`Tuvc
JTfdvsjuzJogp`HfuQfsnjttjpot
ECTDIFNB`BTTFSUJPOT
JTfttjpoQspqfsujft`Sfmfbtf
JTdpqfePqfsbujpot`Npwf`Qspyz
ECQSPQ`MPDLNPEF
JSpxtfuDibohf`Sfmfbtf
ECQSPQWBM`PQ`FRVBM
HfuPsjhjobmEbub
JTRMFsspsJogp`HfuTRMJogp`Tuvc
JSpxQptjujpoDibohf`PoSpxQptjujpoDibohf
ejtqje
JSpxQptjujpo`SfnpufJojujbmj{f`Tuvc
JSpxQptjujpo`DmfbsSpxQptjujpo
ECUZQF`J3
JSpx`HfuDpmvnot`Tuvc
ECQSPQGMBHTFOVN37
ECQSPQ`JECBtzodiTubuvt
JHfuSpx`HfuSpxGspnISPX`Tuvc
DSFTUSJDUJPOT`NETDIFNB`NFNCFST
JBddfttps`SfnpufBeeSfgBddfttps`Qspyz
NEQSPQWBM`NNG`DMPTJOHQFSJPE
ECTPVSDFUZQF`EBUBTPVSDF
NEQSPQWBM`NG`DSFBUF`DBMDNFNCFST
ECDPNQBSFPQT`MU
JSpxQptjujpo`Jojujbmj{f`Qspyz
ECUZQF`TUS
ECDPNQBSF`HU
JUbcmfEfgjojujpo`BeeDpmvno`Qspyz
JUbcmfDsfbujpoWucm
JECJojujbmj{f`Jojujbmj{f
JtTbnfSpx
ECDPMVNOGMBHT`JTSPXTFU
ECQSPQWBM`PP`TJOHMFUPO
``JECCjoefsQspqfsujft`JOUFSGBDF`EFGJOFE``
EC`CJOEGMBHT`DPMMFDUJPO
``JSpxtfuGjoe`GXE`EFGJOFE``
JTfttjpoQspqfsujft`HfuQspqfsujft`Qspyz
JNESbohfSpxtfu`BeeSfg
JSpxtfuJoefy`TfuSbohf
HfuJoefyJogp
ECTPVSDFUZQF`EBUBTPVSDF`UEQ
JSpxtfuVqebuf`TfuEbub
JSpxtfuOpujgz`SfnpufPoSpxtfuDibohf`Qspyz
EfmfufSpxt
ECQSPQ`JSpx
ECQSPQWBM`PT`UYOFOMJTUNFOU
JSpxtfuJogp`SfnpufHfuSfgfsfodfeSpxtfu`Tuvc
``JJoefyEfgjojujpo`GXE`EFGJOFE``
NEQSPQ`NEY`TUSJOH`DPNQPQ
PoMpxSftpvsdf
ecdje
JSpxtfuJogp
JSpxtfuMpdbuf`RvfszJoufsgbdf
DSFTUSJDUJPOT`ECTDIFNB`VTBHF`QSJWJMFHFT
JUbcmfDsfbujpo`EspqUbcmf
ECQSPQ`JWjfxDibqufs
JSpxQptjujpo`SfnpufHfuSpxtfu`Tuvc
JDpnnboeXjuiQbsbnfufst`HfuQbsbnfufsJogp`Qspyz
ECQSPQWBM`QU`HVJE
JDsfbufSpxWucm
SftubsuQptjujpo
NEUSFFPQ`TFMG
ubhFSSPSJOGP
ECQBSBNJP`PVUQVU
ECTPVSDFUZQF`CJOEFS
ECDPNQBSF`FR
JECDsfbufTfttjpo`SfnpufDsfbufTfttjpo`Qspyz
JCjoeSftpvsdf`SfnpufCjoe`Tuvc
EC`OVMM`IBDDFTTPS
JTpvsdftSpxtfu`BeeSfg
JUsvtuffBenjo`DsfbufUsvtuff`Qspyz
QFSN`XSJUFPXOFS
JWjfxGjmufs`BeeSfg
NJEM`vtfs`bmmpdbuf
NE`EJNUZQF`UJNF
``JSpxtfuDvssfouJoefy`GXE`EFGJOFE``
ECVQEFMSVMF`DBTDBEF
JUsbotbdujpoKpjo`HfuPqujpotPckfdu
ECQSPQ`OPUJGZSPXTFUSFMFBTF
JSpxtfuVqebuf`Sfmfbtf
JFsspsMpplvq`SfnpufSfmfbtfFsspst`Qspyz
NEQSPQWBM`NOG`MJOSFHQPJOU
JTpvsdftSpxtfu`Sfmfbtf
ECQSPQWBM`US`PQUJNJTUJD
JDpnnboeQsfqbsf`Voqsfqbsf`Tuvc
JECDsfbufTfttjpo
ECTDIFNB`UBCMF`DPOTUSBJOUT
QFSN`SFBEDPOUSPM
ECDPOTUSBJOUUZQF
DSFTUSJDUJPOT`ECTDIFNB`UBCMFT
JTfttjpoQspqfsujft`TfuQspqfsujft
KpjoUsbotbdujpo
ECQSPQ`TUPSBHFGMBHT
Bcpsu
ECFWFOUQIBTFFOVN
ECQSPQWBM`TV`QSJWJMFHF`EFGJOJUJPO
ECQSPQ`TPSUPOJOEFY
ECTDIFNB`DPMMBUJPOT
EC`NPEF`TIBSF`EFOZ`OPOF
ECQSPQWBM`DP`TUSJOH
ECFWFOUQIBTF`EJEFWFOU
JHfuEbubTpvsdf`HfuEbubTpvsdf`Tuvc
ECUZQF`EFDJNBM
Cjoe
EC`VSFTFSWF
ECQSPQ`NBYPQFOSPXT
DSFTUSJDUJPOT`ECTDIFNB`LFZ`DPMVNO`VTBHF
ECDPMVNO`HVJE
ECTUBUVT`T`EFGBVMU
ECTFFL`BGUFS
ECQSPQTFU`DPOTUSBJOUBMM
ECEBUF
JJE`JDpnnboe
JSpxtfuMpdbuf`SfmfbtfSpxt
JSpxDibohf`TfuDpmvnot
JCjoeSftpvsdf`RvfszJoufsgbdf
EC`MPDBM`TIBSFE
JPqfoSpxtfu`PqfoSpxtfu
NEBYJT`DPMVNOT
JECBtzodiTubuvt
JDpmvnotSpxtfu`BeeSfg
JTfttjpoQspqfsujft`SfnpufHfuQspqfsujft`Qspyz
JSpxtfuSfgsfti`HfuMbtuWjtjcmfEbub`Tuvc
QFSN`XJUIHSBOU
JWjfxDibqufs`BeeSfg
JSpxtfuSfgsfti`SfgsftiWjtjcmfEbub
PG`EFMFUF
JSpxQptjujpo`Sfmfbtf
NEQSPQWBM`OM`TDIFNBPOMZ
JDpnnboeUfyu`HfuECTfttjpo
JECQspqfsujft`SfnpufHfuQspqfsuzJogp`Qspyz
HfuTpvsdfSpx
JECBtzodiTubuvt`HfuTubuvt`Tuvc
BeeNfncfs
NEMFWFM`UZQF`SFHVMBS
ECQSPQWBM`GV`DPMVNO
ECQSPQ`TUSPOHJEFOUJUZ
JJE`JDpnnboeXjuiQbsbnfufst
ECQSPQWBM`DP`DBTFTFOTJUJWF
ECCJOETUBUVT`NVMUJQMFTUPSBHF
JDpnnboeXjuiQbsbnfufst`NbqQbsbnfufsObnft
ECSFGDPVOU
NENFNCFS`UZQF`SFHVMBS
JDibqufsfeSpxtfuWucm
JECDsfbufDpnnboe`RvfszJoufsgbdf
EC`MPDBM`FYDMVTJWF
JNEGjoe`GjoeDfmm
JWjfxDibqufs`SfnpufHfuTqfdjgjdbujpo`Tuvc
``JQbsfouSpxtfu`JOUFSGBDF`EFGJOFE``
JSpxtfuFybduTdspmm`HfuSpxtBu
JDpnnboeTusfbn`BeeSfg
shQspqfsuzJEt
ECQSPQWBM`ETU`UEQ
ECCJOETUBUVT`CBECJOEJOGP
JWjfxDibqufs`SfnpufPqfoWjfxDibqufs`Qspyz
``JDpmvnotSpxtfu`JOUFSGBDF`EFGJOFE``
JNvmujqmfSftvmut`RvfszJoufsgbdf
JJE`JSpxtfuCpplnbsl
DSFTUSJDUJPOT`ECTDIFNB`TDIFNBUB
ECDPMVNO`CBTFDBUBMPHOBNF
JUbcmfEfgjojujpo`DsfbufUbcmf`Qspyz
ECMJUFSBM`FTDBQF`VOEFSTDPSF`QSFGJY
``JCjoeSftpvsdf`JOUFSGBDF`EFGJOFE``
ECQSPQ`JOJU`CJOEGMBHT
ECQSPQ`NBYQFOEJOHSPXT
JNEEbubtfu`RvfszJoufsgbdf
JSpxtfu`HfuEbub`Tuvc
ECQSPQWBM`UJ`SFQFBUBCMFSFBE
dCTUS
ECQSPQ`NVMUJQMFSFTVMUT
DSFTUSJDUJPOT`ECTDIFNB`QSPWJEFS`UZQFT
ECQPTJUJPOGMBHT
ECQSPQ`QSPWJEFSWFS
``JBmufsJoefy`JOUFSGBDF`EFGJOFE``
JSpxtfuFybduTdspmm`Sfmfbtf
ECQSPQ`VQEBUBCJMJUZ
ECQSPQ`OPUJGZSPXEFMFUF
ECQSPQ`OPUJGZSPXTFUDIBOHFE
PqfoSpxtfu
ECCJOEFYU
JBddfttps`DsfbufBddfttps`Qspyz
MpbeDpnnboe
JECJogp`BeeSfg
JJoefyEfgjojujpo`DsfbufJoefy`Qspyz
JFsspsSfdpset`HfuFsspsJogp`Tuvc
NEQSPQWBM`NNG`QBSBMMFMQFSJPE
NEQSPQ`BHHSFHBUFDFMM`VQEBUF
NEQSPQWBM`NTG`UPQQFSDFOU
JUsbotbdujpoPckfdu`HfuUsbotbdujpoPckfdu`Tuvc
JUsbotbdujpoPckfdu`HfuUsbotbdujpoPckfdu
``JFsspsMpplvq`JOUFSGBDF`EFGJOFE``
ECDPMVNOJOGP
ECQSPQ`JOEFY`UFNQJOEFY
ECQSPQWBM`TRM`BOTJ:3`FOUSZ
``JSpxQptjujpo`GXE`EFGJOFE``
shSftfswfe
ECQSPQWBM`PST`JOEFY
ECUZQF
ECQSPQ`SFFOUSBOUFWFOUT
JUbcmfEfgjojujpo`SfnpufDsfbufUbcmf`Qspyz
ECMJUFSBM`TDIFNB`OBNF
ECUBCMFTUBUJTUJDTUZQF37
JFsspsSfdpset`HfuCbtjdFsspsJogp`Qspyz
NEQSPQWBM`NOG`DPWBSJBODF
qus
JECCjoefsQspqfsujft`Sftfu`Tuvc
JECEbubTpvsdfBenjo`SfnpufHfuDsfbujpoQspqfsujft`Qspyz
JSpxtfuVqebuf`Vqebuf`Qspyz
``JHfuTpvsdfSpx`JOUFSGBDF`EFGJOFE``
DSFTUSJDUJPOT`NETDIFNB`DVCFT
BmufsJoefy
JDpnnboeQsfqbsf`Qsfqbsf`Tuvc
JDpnnboeUfyu`TfuDpnnboeUfyu`Tuvc
QptjujpoPoCpplnbsl
JJE`JWjfxTpsu
ECTDIFNB`UBCMF`TUBUJTUJDT
NEQSPQ`OBNFE`MFWFMT
JJE`JTfttjpoQspqfsujft
ECDPMVNO`EFGBVMUWBMVF
``JSfhjtufsQspwjefs`GXE`EFGJOFE``
ubhECQSPQJOGPTFU
wWbmvf
tj{f
JSpxtfuTdspmm`HfuSpxtBuSbujp`Qspyz
ECDPMVNOGMBHT`JTOVMMBCMF
JJE`JSpxtfuGjoe
JHfuTpvsdfSpx`HfuTpvsdfSpx`Tuvc
ECQSPQWBM`NS`OPUTVQQPSUFE
ECQFOEJOHTUBUVT`JOWBMJESPX
JECBtzodiTubuvt`SfnpufHfuTubuvt`Qspyz
DSFTUSJDUJPOT`ECTDIFNB`USVTUFF
``JBmufsUbcmf`GXE`EFGJOFE``
ECQSPQ`JSpxtfu
ubhECPCKFDU
qUzqfJogp
JSpxtfuFybduTdspmm`Ibti
JFsspsSfdpset`HfuFsspsJogp`Qspyz
ECQSPQWBM`TUHN`GBJMJGUIFSF
ECQSPQ`DPM`EFTDSJQUJPO
JSpx`Pqfo`Tuvc
JWjfxGjmufs`HfuGjmufsCjoejoht
JTRMFsspsJogp`Sfmfbtf
ECQSPQWBM`PB`BUFYFDVUF
FSSPSJOGP
NEMFWFM`UZQF`UJNF`EBZT
ECDPQZ`BUPNJD
JSpxtfuTdspmm
ECQSPQWBM`TUHN`USBOTBDUFE
ECTDIFNB`DPOTUSBJOU`DPMVNO`VTBHF
JDpnnboeQfstjtu`MpbeDpnnboe`Tuvc
HfuLfzxpset
JPqfoSpxtfuWucm
ECMJUFSBM`MJLF`VOEFSTDPSF
JSpxQptjujpo`TfuSpxQptjujpo`Qspyz
ECDPNQBSFPQT`DBTFJOTFOTJUJWF
HfuSftusjdufeDpmvnoJogp
JECCjoefsQspqfsujft`RvfszJoufsgbdf
JJE`JCjoeSftpvsdf
NpejgzEbubTpvsdf
JNEGjoe`GjoeUvqmf`Tuvc
JECBtzodiTubuvt`HfuTubuvt
JDpnnboeTusfbn`TfuDpnnboeTusfbn
QECQSPQJOGP
JDpmvnotSpxtfuWucm
JDpnnboeXjuiQbsbnfufst`RvfszJoufsgbdf
ECTUBUVT`F`SFTPVSDFFYJTUT
JSpxtfuDvssfouJoefy`Sfmfbtf
ECQSPQ`JSpxtfuJoefy
ECSFBTPO`SPXTFU`SFMFBTF
HfuQfsnjttjpot
JECBtzodiTubuvt`SfnpufHfuTubuvt`Tuvc
JDpmvnotSpxtfu`HfuDpmvnotSpxtfu`Qspyz
ECNFNPXOFSFOVN
ECDPMVNOGMBHT`TDBMFJTOFHBUJWF
ECCJOEVSMTUBUVT`T`EFOZOPUTVQQPSUFE
ECCJOEVSMGMBH`TIBSF`FYDMVTJWF
JSpxtfuFybduTdspmm`HfuOfyuSpxt
JSpxtfuDibqufsNfncfs
``JSpx`JOUFSGBDF`EFGJOFE``
HfuTpsuPsefs
NEQSPQ`GMBUUFOJOH`TVQQPSU
HfuSfdpseDpvou
``JSpxQptjujpoDibohf`GXE`EFGJOFE``
ECQBSU
JECQspqfsujft`HfuQspqfsuzJogp`Qspyz
ECTUBUVT`T`BMSFBEZFYJTUT
``NJEM`jug`pmfec`1111`w1`1`d`jgtqfd
ECQSPQ`PUIFSVQEBUFEFMFUF
ECQSPQ`JOEFY`QSJNBSZLFZ
JSpxtfuJogp`BeeSfg
JQbsfouSpxtfu
JFsspsSfdpset
ECCJOEVSMTUBUVT
ECDPNQBSFPQT`DBTFTFOTJUJWF
ECDPQZ`OPO`SFDVSTJWF
ECDPOWFSUGMBHT`GSPNWBSJBOU
``JSpxtfuWjfx`JOUFSGBDF`EFGJOFE``
EC`QSPU`MFWFM`QLU`QSJWBDZ
JUbcmfEfgjojujpo`SfnpufEspqUbcmf`Qspyz
JSpxtfuWjfx`SfnpufHfuWjfx`Tuvc
JSpxtfuMpdbuf`HfuSpxtCzCpplnbsl
JNEGjoe`Sfmfbtf
JSpxtfuFybduTdspmm`HfuEbub
ECUZQF`FSSPS
PG`QBSTF
JDpnnboeXjuiQbsbnfufst`Sfmfbtf
JHfuTfttjpo`HfuTfttjpo`Tuvc
JSpxtfuOpujgz`RvfszJoufsgbdf
JJE`JUbcmfEfgjojujpo
``JHfuEbubTpvsdf`JOUFSGBDF`EFGJOFE``
NEQSPQ`WJTVBMNPEF
shCTUS
JSpxQptjujpoDibohf`PoSpxQptjujpoDibohf`Qspyz
JDpnnboeQspqfsujft`TfuQspqfsujft`Qspyz
JSpxtfuMpdbuf`Ibti`Qspyz
ECQSPQWBM`TR`UBCMF
HfuPckfduUzqft
ECDPMVNOGMBHT`SPXTQFDJGJDDPMVNO
NEQSPQWBM`NOG`WBS
DSFTUSJDUJPOT`ECTDIFNB`USBOTMBUJPOT
HfuFsspsQbsbnfufst
JDpnnboeXjuiQbsbnfufst`SfnpufNbqQbsbnfufsObnft`Qspyz
ECLJOEFOVN
IBDDFTTPS
JNEEbubtfu`Sfmfbtf
ECQSPQ`DPM`EFGBVMU
JtFrvbmHVJECbtf
NETDIFNB`IJFSBSDIJFT
NEQSPQWBM`NTG`ESJMMVQNFNCFS
zfbs
JDpnnboe`Sfmfbtf
JBddfttps`HfuCjoejoht`Qspyz
JSpxtfuDibohf`JotfsuSpx
JECBtzodiOpujgz`PoTupq`Tuvc
DsfbufJoefy
ECHVJE`TFTTJPO
ECDPMVNOGMBHT`DBDIFEFGFSSFE
JUsbotbdujpoPckfdu`BeeSfg
``JTdpqfePqfsbujpot`JOUFSGBDF`EFGJOFE``
JDpmvnotJogp`RvfszJoufsgbdf
JSpxtfuJogp`SfnpufHfuQspqfsujft`Qspyz
ECSFBTPO`DPMVNO`SFDBMDVMBUFE
ECQSPQWBM`HC`DPMMBUF
ECQSPQJOGP
JJE`JSpxQptjujpoDibohf
JECBtzodiOpujgz`PoMpxSftpvsdf`Qspyz
isFssps
JDpnnboeTusfbn`HfuDpnnboeTusfbn`Tuvc
DsfbufBddfttps
JDpmvnotJogp`NbqDpmvnoJEt
NbqQbsbnfufsObnft
ECQSPQTFU`UBCMF
ECCJOEVSMGMBH`TIBSF`EFOZ`SFBE
`TFD`PCKFDU`FMFNFOU
JECQspqfsujft`TfuQspqfsujft
ECQSPQWBM`JO`JHOPSFBOZOVMM
VOBMJHOFE
JECEbubTpvsdfBenjo`SfnpufEftuspzEbubTpvsdf`Tuvc
Jojujbmj{f
ECQSPQ`JDpmvnotJogp3
JDpmvnotJogp3`Sfmfbtf
EC`CJOEGMBHT`PQFOJGFYJTUT
JUsbotbdujpoKpjo`Sfmfbtf
ECQSPQ`TVQQPSUFEUYOJTPSFUBJO
ECSBOHF`QSFGJY
JTRMFsspsJogp`SfnpufHfuTRMJogp`Qspyz
ECTUBUVT`F`WPMVNFOPUGPVOE
``NJEM`jug`pmfec`1449`w1`1`t`jgtqfd
ECQBSBNGMBHT`TDBMFJTOFHBUJWF
EC`JNQ`MFWFM`BOPOZNPVT
BeeDpmvnot
JJE`JSpxtfuDibqufsNfncfs
JQbsfouSpxtfu`RvfszJoufsgbdf
JPckfduBddfttDpouspm`HfuPckfduPxofs`Tuvc
ECQSPQ`BDDFTTPSEFS
ECMJUFSBM`WJFX`OBNF
ECMFOHUI
ECQSPQ`CPPLNBSLTLJQQFE
TfuGjmufs
JJoefyEfgjojujpo`BeeSfg
ECEFMFUF`BTZOD
ECCJOEVSMGMBH`TIBSF`EFOZ`XSJUF
ECSPXTUBUVT`T`NVMUJQMFDIBOHFT
DmfbsSpxQptjujpo
ECQSPQ`DPM`QSJNBSZLFZ
ECSFTVMUGMBH`SPXTFU
JDibqufsfeSpxtfu`SfnpufSfmfbtfDibqufs`Tuvc
TfuJoefy
tfdpoe
EspqUbcmf
ECTDIFNB`DIFDL`DPOTUSBJOUT
ECQSPQ`NFNPSZVTBHF
EspqDpotusbjou
ECVQEFMSVMFFOVN
ECUZQF`WBSOVNFSJD
ECQSPQ`JSpxTdifnbDibohf
qDpmvnoJE
ECBDDFTTPS`JOIFSJUFE
JSpxtfuOpujgz`SfnpufPoSpxDibohf`Qspyz
JECDsfbufDpnnboe`BeeSfg
ECQSPQWBM`PST`IJTUPHSBN
JUbcmfEfgjojujpo`BeeDpmvno
JSpxQptjujpo`TfuSpxQptjujpo`Tuvc
``JTfdvsjuzJogp`GXE`EFGJOFE``
HfuUbcmfEfgjojujpo
JSpxtfuDibohf`EfmfufSpxt
JSpxtfuVqebuf`RvfszJoufsgbdf
JDpnnboeUfyu`Dbodfm
JJE`JECJojujbmj{f
ECHVJE`ECTRM
wuUzqf
ECQSPQGMBHT`DPMVNO
JFsspsSfdpset`SfnpufHfuFsspsQbsbnfufst`Qspyz
SfmfbtfDibqufs
HfuDvssfouDpnnboe
HfuBqqspyjnbufQptjujpo
JECQspqfsujft`Sfmfbtf
JPckfduBddfttDpouspm`HfuPckfduBddfttSjhiut`Qspyz
ECQSPNQU`DPNQMFUF
JTRMFsspsJogp`RvfszJoufsgbdf
ECQSPQ`TFSWFSOBNF
ECUZQF`OVMM
JECTdifnbSpxtfuWucm
ECQSPNQU`OPQSPNQU
ECQSPQ`USVTUFF`VTFSOBNF
ECPCKFDU`EBUBCBTF
ECQSPQWBM`PT`DMJFOUDVSTPS
JSfhjtufsQspwjefs`Sfmfbtf
JUsbotbdujpoMpdbm`TubsuUsbotbdujpo`Qspyz
JUsbotbdujpoMpdbm`SfnpufTubsuUsbotbdujpo`Qspyz
HfuDpmvnoJogp
JTpvsdftSpxtfu`HfuTpvsdftSpxtfu
JSpxtfuSfgsfti`SfgsftiWjtjcmfEbub`Tuvc
JBmufsUbcmf`BmufsDpmvno`Tuvc
ECNPWF`SFQMBDF`FYJTUJOH
JTdpqfePqfsbujpot`SfnpufPqfoSpxtfu`Tuvc
ECQSPQ`PVUQVUFODPEJOH
ECSPXDPM`JTIJEEFO
ECQSPQWBM`PQ`SFMBUJWF
``JHfuTfttjpo`JOUFSGBDF`EFGJOFE``
JSpxtfuJefoujuz`JtTbnfSpx
JSpxtfuCpplnbsl`QptjujpoPoCpplnbsl`Qspyz
ECQBSBNGMBHT`JTOVMMBCMF
ECQSPQWBM`JO`EJTBMMPXOVMM
JNvmujqmfSftvmut
NEQSPQWBM`NKD`JNQMJDJUDVCF
ECQSPQWBM`UJ`DIBPT
ECQSPQWBM`TT`JMPDLCZUFT
NEEJTQJOGP`QBSFOU`TBNF`BT`QSFW
DSFTUSJDUJPOT`NETDIFNB`QSPQFSUJFT
JFsspsSfdpset`SfnpufHfuFsspsJogp`Qspyz
Voep
``JWjfxSpxtfu`JOUFSGBDF`EFGJOFE``
vmQbsbnTj{f
exQbsu
JSpxtfuMpdbufWucm
ECQSPQ`NVMUJQMFDPOOFDUJPOT
JJoefyEfgjojujpo`SfnpufDsfbufJoefy`Tuvc
ECUZQF`J5
NEQSPQWBM`NOG`ESJMMEPXOMFWFMUPQ
JSpxDibohf`TfuDpmvnot`Tuvc
DSFTUSJDUJPOT`ECTDIFNB`DPMVNO`QSJWJMFHFT
ECQSPQTFU`JOEFYBMM
JNEEbubtfuWucm
JUsvtuffBenjo`HfuUsvtuffQspqfsujft`Qspyz
TfuDpmvnot
JDibqufsfeSpxtfu`SfmfbtfDibqufs`Qspyz
HfuSpxtCzCpplnbsl
JWjfxTpsu`HfuTpsuPsefs`Tuvc
CNL`EVSBCJMJUZ`YUSBOTBDUJPO
``JSpxtfuJefoujuz`GXE`EFGJOFE``
NEQSPQWBM`NOG`ESJMMEPXOMFWFMCPUUPN
JNEGjoe`GjoeDfmm`Qspyz
ECQSPQ`BVUI`DBDIF`BVUIJOGP
JDpnnboeQspqfsujft`SfnpufTfuQspqfsujft`Tuvc
JDpnnboeUfyu`HfuDpnnboeUfyu`Qspyz
JDibqufsfeSpxtfu`BeeSfg
JNvmujqmfSftvmut`SfnpufHfuSftvmu`Qspyz
NE`EJNUZQF`VOLOPXO
JWjfxGjmufs`TfuGjmufs`Qspyz
ECDPMVNOGMBHTFOVN37
ECQSPQPQUJPOTFOVN
JDpnnboeQsfqbsf
NEQSPQWBM`NOG`ESJMMVQMFWFM
ECVQEFMSVMF`OPBDUJPO
ECQBSU`TUBUVT
``JWjfxGjmufs`GXE`EFGJOFE``
JSpxtfuJoefy`HfuJoefyJogp
JBmufsUbcmf`BeeSfg
JPqfoSpxtfu`SfnpufPqfoSpxtfu`Qspyz
JSpxQptjujpoDibohf`Sfmfbtf
``JUsbotbdujpoKpjo`GXE`EFGJOFE``
JJE`JECDsfbufTfttjpo
JSpxtfuTdspmm`Sfmfbtf
JJE`JNvmujqmfSftvmut
JTfdvsjuzJogpWucm
ECQSPQ`JHfuTpvsdfSpx
ECQSPQ`BVUI`QFSTJTU`FODSZQUFE
ECQSPNQU`QSPNQU
ECDPMVNO`QSFDJTJPO
EC`NPEF`SFBEXSJUF
JHfuSpxWucm
DSFTUSJDUJPOT`NETDIFNB`IJFSBSDIJFT
ECCPPLNBSL
fJoefyDpmPsefs
``JSpxQptjujpo`JOUFSGBDF`EFGJOFE``
ECTUBUVT`F`SFBEPOMZ
JSpxDibohf`TfuDpmvnot`Qspyz
JBmufsUbcmf`Sfmfbtf
JDpmvnotJogp3`HfuDpmvnoJogp
ECQSPQ`JSpxtfuSfgsfti
ECFWFOUQIBTF`PLUPEP
NEQSPQ`NEY`EFTDGMBHT
ECQSPQJE
ECTPVSDFUZQF`EBUBTPVSDF`NEQ
``JECQspqfsujft`JOUFSGBDF`EFGJOFE``
JSpxtfuSftzodi`BeeSfg
ECSBOHF`NBUDI
EC`NPEF`XSJUF
CNL`EVSBCJMJUZ`JOUSBOTBDUJPO
ECSFBTPO`SPXQPTJUJPO`DMFBSFE
JSpxtfuVqebuf`HfuQfoejohSpxt`Tuvc
NEQSPQWBM`NPR`NFNCFS`NFNCFS
ECQSPQ`JOEFY`UZQF
ECTPVSDFUZQFFOVN36
JSpxTdifnbDibohf`TfuDpmvnot
ECQSPQTUBUVTFOVN
ECJOEFY`DPM`PSEFS`BTD
QFSN`DSFBUF
ECPCKFDU`EPNBJO
JECJojujbmj{f`Jojujbmj{f`Qspyz
ECJOEFYDPMVNOEFTD
JSpxtfuWjfx`DsfbufWjfx`Qspyz
JNEEbubtfu`HfuDfmmEbub`Tuvc
JECEbubTpvsdfBenjo`DsfbufEbubTpvsdf
hvjeQspqfsuzTfu
NEQSPQWBM`NTD`MFTTUIBO
``JECBtzodiOpujgz`GXE`EFGJOFE``
ECQSPQTUBUVT`DPOGMJDUJOH
ECEFGFSSBCJMJUZFOVN
``JDpnnboe`JOUFSGBDF`EFGJOFE``
ECQSPQWBM`DP`FRVBMJUZ
ECSFBTPO`SPX`JOTFSU
JECQspqfsujft`SfnpufTfuQspqfsujft`Qspyz
ECQSPQTFU`WJFXBMM
JNEEbubtfu`HfuDfmmEbub
JDpnnboeQsfqbsf`SfnpufQsfqbsf`Qspyz
CNL`EVSBCJMJUZ`SFPSHBOJ[BUJPO
JPckfduBddfttDpouspm`TfuPckfduBddfttSjhiut
ubhEC`OVNFSJD
JSpxtfuJoefy`RvfszJoufsgbdf
JTRMFsspsJogp`SfnpufHfuTRMJogp`Tuvc
ECHVJE`TRM
ECTFFL`BGUFSFR
JDpnnboeQfstjtu`HfuDvssfouDpnnboe`Tuvc
``JSpxtfuWjfx`GXE`EFGJOFE``
JSpxtfuCpplnbsl`QptjujpoPoCpplnbsl
ECQSPQ`JOJU`PMFECTFSWJDFT
DSFTUSJDUJPOT`ECTDIFNB`QSPDFEVSF`QBSBNFUFST
NEQSPQWBM`NKD`NVMUJDVCFT
JSpxtfuMpdbuf`BeeSfg
``JSpxtfuGjoe`JOUFSGBDF`EFGJOFE``
ECQSPQ`DPMVNOMDJE
JDpnnboeXjuiQbsbnfufst`NbqQbsbnfufsObnft`Qspyz
NEUSFFPQ`EFTDFOEBOUT
JSpxtfuVqebuf`HfuPsjhjobmEbub`Qspyz
JBddfttps`Sfmfbtf
ECQBSBNUZQF`SFUVSOWBMVF
JWjfxTpsuWucm
JECTdifnbSpxtfu`SfnpufHfuSpxtfu`Qspyz
EC`MQBSBNT
JSpxtfuGjoe`GjoeOfyuSpx`Tuvc
dSftfswfe
JUsbotbdujpoKpjo`HfuPqujpotPckfdu`Qspyz
ECSFTVMUGMBHFOVN
NEQSPQWBM`GT`HFOFSBUFE`DPMVNO
JECDsfbufTfttjpo`BeeSfg
JTdpqfePqfsbujpot`PqfoSpxtfu`Qspyz
JJE`JSfhjtufsQspwjefs
ECDPNQBSF`OPUDPNQBSBCMF
NETDIFNB`DVCFT
ECQSPQ`DBOIPMESPXT
JECJogp`SfnpufHfuLfzxpset`Qspyz
NEQSPQWBM`ND`TFBSDIFEDBTF
NEMFWFM`UZQF`UJNF`ZFBST
ECDPNQVUFNPEF`OPUDPNQVUFE
JDpmvnotSpxtfu`HfuBwbjmbcmfDpmvnot
NEEJTQJOGP`ESJMMFE`EPXO
NEQSPQWBM`NPR`DVCF`EJN
JHfuEbubTpvsdf`SfnpufHfuEbubTpvsdf`Qspyz
``JHfuSpx`GXE`EFGJOFE``
JFsspsMpplvq`HfuIfmqJogp`Qspyz
JDibqufsfeSpxtfu`SfnpufSfmfbtfDibqufs`Qspyz
JDpmvnotSpxtfu`HfuDpmvnotSpxtfu`Tuvc
NEQSPQWBM`NOG`ESJMMEPXONFNCFSCPUUPN
JNEEbubtfu`HfuByjtJogp`Tuvc
ECQSPQTFU`EBUBTPVSDFJOGPBMM
ECDPMVNOGMBHT`JTSPXJE
ECTDIFNB`DBUBMPHT
EC`NPEF`TIBSF`FYDMVTJWF
ECQSPQWBM`BP`SBOEPN
qxt{UzqfObnf
ECQSPQFOVN32
JNEEbubtfu`HfuByjtSpxtfu`Tuvc
NEQSPQWBM`NG`XJUI`DBMDNFNCFST
ECQSPQWBM`UJ`TFSJBMJ[BCMF
BeeSfgBddfttps
ECQSPQWBM`HC`DPOUBJOT`TFMFDU
JWjfxDibqufs`HfuTqfdjgjdbujpo`Tuvc
ECDPMVNO`CBTFTDIFNBOBNF
HfuBwbjmbcmfDpmvnot
JDpnnboeUfyu
ECTUBUVTFOVN32
JSpxtfuFybduTdspmm
ECBDDFTTPSGMBHTFOVN
HfuSpxtBuSbujp
ECJE
ECDPNQVUFNPEF`EZOBNJD
JUsbotbdujpoKpjo`KpjoUsbotbdujpo`Tuvc
ECQSPQ`TRMTVQQPSU
JFsspsMpplvq`SfmfbtfFsspst`Tuvc
PG`TIBSF`FYDMVTJWF
ECBTZODIQIBTF`QPQVMBUJPO
ECUZQF`JEJTQBUDI
ECSPXDPM`JTTUSVDUVSFEEPDVNFOU
JDpnnboe
ECTUBUVT`F`DBOOPUDPNQMFUF
ECQSPQTFU`UBCMFBMM
DSFTUSJDUJPOT`ECTDIFNB`UBCMFT`JOGP
ECQSPQ`JOJU`QSPUFDUJPO`MFWFM
ECLJOE`HVJE`OBNF
ECQSPQWBM`ETU`EPDTPVSDF
ECQSPQ`MJUFSBMJEFOUJUZ
PckfduJE
JSpxtfuMpdbuf`Ibti
JUbcmfEfgjojujpoXjuiDpotusbjout`BeeDpotusbjou
JSpxtfuDvssfouJoefy
ECQSPQGMBHT`SFBE
HfuFsspsJogp
ECQSPQ`HFOFSBUFVSM
ECQSPQ`JECCjoefsQspqfsujft
TfuTpsuPsefs
ECMJUFSBM`IJFSBSDIZ`OBNF
ECQSPQ`SFUVSOQFOEJOHJOTFSUT
JJE`JPckfduBddfttDpouspm
DSFTUSJDUJPOT`NETDIFNB`TFUT
JDpnnboe`SfnpufFyfdvuf`Tuvc
ECQSPQ`DPM`BVUPJODSFNFOU
JSpxTdifnbDibohf`BeeDpmvnot`Qspyz
JBddfttps`HfuCjoejoht
ECTDIFNB`DPMVNO`EPNBJO`VTBHF
``JDpnnboeQfstjtu`GXE`EFGJOFE``
ECSPXDPM`EFGBVMUTUSFBN
ECQSPQWBM`DC`EFMFUF
ECQSPQWBM`UJ`JTPMBUFE
NEQSPQWBM`NTG`UPHHMFESJMMTUBUF
ECQSPQWBM`JU`IBTI
JHfuSpx`RvfszJoufsgbdf
ECQSPQ`JSpxtfuGjoe
JSpx`BeeSfg
ECSPXTUBUVT`F`DBOUSFMFBTF
ECTPSU`BTDFOEJOH
JSpxtfuJefoujuz`Sfmfbtf
ECTDIFNB`UBCMFT`JOGP
JJE`JTdpqfePqfsbujpot
QFSN`EFTJHO
ECDPMVNOGMBHTFOVN
JECEbubTpvsdfBenjo`RvfszJoufsgbdf
JTdpqfePqfsbujpot`Dpqz`Tuvc
PG`SFPQFO
ECQSPQWBM`HC`FRVBMT`TFMFDU
qhvje
qxt{EbubTpvsdfUzqf
NEQSPQWBM`NOG`TUEEFW
JJE`JFsspsMpplvq
JDpnnboe`SfnpufDbodfm`Qspyz
ECQSPQWBM`TV`ENM`TUBUFNFOUT
JFsspsSfdpset`HfuFsspsJogp
HfuDpnnboeTusfbn
wbm
ECQSPQ`JOJU`DBUBMPH
JECTdifnbSpxtfu`BeeSfg
JSpxtfuDibqufsNfncfs`JtSpxJoDibqufs
JUbcmfDsfbujpo`HfuUbcmfEfgjojujpo
JUsvtuffBenjo`DpnqbsfUsvtufft
EspqDpmvno
ECQSPQWBM`TT`JTUSFBN
ECQBSBNUZQF`PVUQVU
NEQSPQWBM`BV`VOLOPXO
JECQspqfsujft`TfuQspqfsujft`Qspyz
JSpxtfuDibohf`TfuEbub`Qspyz
JSpxtfuVqebuf`Voep
ECQSPQ`DPM`TFFE
NEQSPQ`NEY`PCKRVBMJGJDBUJPO
ECTUBUVT
ECDPQZGMBHT
``JDpmvnotJogp3`GXE`EFGJOFE``
JTdpqfePqfsbujpot`RvfszJoufsgbdf
JDsfbufSpx`BeeSfg
NEQSPQWBM`NOG`MJOSFH3
JDpnnboeQfstjtu`TbwfDpnnboe`Tuvc
NETDIFNB`BDUJPOT
iSpx
ubhECUJNFTUBNQ
JTRMFsspsJogp
ECQSPQ`DPM`JODSFNFOU
ECTDIFNB`WJFX`DPMVNO`VTBHF
JSpxtfuOpujgz`BeeSfg
ECQSPQWBM`EG`JOJUJBMMZ`EFGFSSFE
``JECBtzodiOpujgz`JOUFSGBDF`EFGJOFE``
JNEEbubtfu`HfuByjtSpxtfu
ECQSPQ`QFSTJTUFOUJEUZQF
JUbcmfEfgjojujpo
JECJogp`HfuLfzxpset`Tuvc
JECBtzodiTubuvt`Sfmfbtf
HfuDfmmEbub
JDpmvnotJogp`NbqDpmvnoJEt`Qspyz
``JSpxtfuMpdbuf`JOUFSGBDF`EFGJOFE``
ECCJOETUBUVT`CBETUPSBHFGMBHT
ECQBSBNGMBHT
JSfhjtufsQspwjefs`TfuVSMNbqqjoh`Tuvc
JNEEbubtfu`BeeSfg
JUsvtuffHspvqBenjo`HfuNfncfstijqt`Tuvc
NEBYJT`DIBQUFST
JDpnnboeQsfqbsf`Voqsfqbsf`Qspyz
ECQSPQ`SPXSFTUSJDU
JWjfxTpsu`SfnpufTfuTpsuPsefs`Qspyz
ECQSPQWBM`TT`JTFRVFOUJBMTUSFBN
ECTPVSDFUZQFFOVN31
ECTUBUVTFOVN37
JDpnnboeQsfqbsf`SfnpufVoqsfqbsf`Qspyz
``JUsbotbdujpoMpdbm`GXE`EFGJOFE``
JSpxQptjujpo`SfnpufTfuSpxQptjujpo`Tuvc
EC`JOWBMJEDPMVNO
JDpmvnotJogp`SfnpufNbqDpmvnoJEt`Tuvc
JDpnnboeUfyu`TfuDpnnboeUfyu
JHfuEbubTpvsdf`RvfszJoufsgbdf
gTvqqpsufe
JBddfttps`SfnpufDsfbufBddfttps`Qspyz
CTUS`VtfsTj{f
JHfuTpvsdfSpx`HfuTpvsdfSpx`Qspyz
``JSpxtfuSfgsfti`JOUFSGBDF`EFGJOFE``
JDibqufsfeSpxtfu`BeeSfgDibqufs
gbjmvsf
JSpx`HfuTpvsdfSpxtfu`Qspyz
ECQSPQWBM`JO`BMMPXOVMM
JECBtzodiTubuvt`Bcpsu`Tuvc
ECQSPQTUBUVT`OPUTVQQPSUFE
JSpxtfu`HfuOfyuSpxt`Qspyz
JFsspsSfdpset`RvfszJoufsgbdf
ECQSPQWBM`DE`OPUOVMM
``JFsspsMpplvq`GXE`EFGJOFE``
JJE`JQbsfouSpxtfu
JSpxtfuVqebuf`BeeSfg
ECQSPQWBM`PT`FOBCMFBMM
ECSPXPGGTFU
JSpxtfuJefoujuz`SfnpufJtTbnfSpx`Tuvc
exPqujpot
ECQSPQ`JOJU`HFOFSBMUJNFPVU
ECQSPQ`BVUI`QFSTJTU`TFOTJUJWF`BVUIJOGP
HfuFybduQptjujpo
ECQSPQWBM`PST`TUPSFEQSPD
JSpxtfuJogp`HfuTqfdjgjdbujpo`Qspyz
JUbcmfDsfbujpo`BeeSfg
JECTdifnbSpxtfu`HfuTdifnbt`Tuvc
JHfuSpx`HfuSpxGspnISPX
JSpxtfuJogpWucm
JCjoeSftpvsdf`Cjoe
ECQSPQWBM`ETU`NEQ
ECQFOEJOHTUBUVT
dmtje
JSpxtfuVqebuf`HfuPsjhjobmEbub`Tuvc
JECBtzodiOpujgz`SfnpufPoTupq`Qspyz
ECQSPQ`NBYJOEFYTJ[F
JSpxtfuSftzodiWucm
NEQSPQ`NEY`TMJDFS
JSpxTdifnbDibohf`BeeSfg
HfuSpxtBu
JSpxtfuVqebuf`Vqebuf
JHfuTfttjpo`BeeSfg
ECQSPQWBM`TUHN`DSFBUF
JSpxtfuJogp`HfuSfgfsfodfeSpxtfu`Tuvc
ECQSPQ`DBUBMPHVTBHF
ECQSPQ`EBUBTPVSDFOBNF
``JSpxtfuDibohf`GXE`EFGJOFE``
ECQSPQWBM`UD`EEM`MPDL
JECEbubTpvsdfBenjo`SfnpufDsfbufEbubTpvsdf`Qspyz
DSFTUSJDUJPOT`ECTDIFNB`JOEFYFT
JDpnnboe`SfnpufDbodfm`Tuvc
ECPCKFDU`WJFX
JSpxtfuTdspmm`HfuSpxtBuSbujp
ECNFNPXOFS`DMJFOUPXOFE
ECDPNQBSFPQT`CFHJOTXJUI
mu
``JUbcmfDsfbujpo`JOUFSGBDF`EFGJOFE``
`GJMFUJNF`
QNEBYJTJOGP`HFUBU
ECCJOEGMBHFOVN
JDpnnboeQspqfsujft`BeeSfg
ECQSPQ`JSpxtfuDvssfouJoefy
ECMJUFSBM`DVCF`OBNF
JECTdifnbSpxtfu`Sfmfbtf
``JUsbotbdujpoKpjo`JOUFSGBDF`EFGJOFE``
ECSPXTUBUVT`T`PL
JFsspsMpplvq`HfuFsspsEftdsjqujpo`Tuvc
TfuDpnnboeTusfbn
ECUZQFGPS`ECPSEJOBM
JWjfxSpxtfu`PqfoWjfxSpxtfu`Qspyz
JECBtzodiOpujgz
``JSpxtfuOpujgz`JOUFSGBDF`EFGJOFE``
JECCjoefsQspqfsujft`TfuQspqfsujft
JUbcmfDsfbujpo`BeeDpmvno
JSpxtfuOpujgz`PoGjfmeDibohf
JWjfxTpsu`BeeSfg
``JHfuTfttjpo`GXE`EFGJOFE``
``JUbcmfDsfbujpo`GXE`EFGJOFE``
ECDPMVNOEFTDGMBHT`QSFDJTJPO
ECQBSBNJOGP
JSpxtfuOpujgz`PoSpxtfuDibohf`Tuvc
JSfhjtufsQspwjefs`TfuVSMNbqqjoh
JECJogp`SfnpufHfuMjufsbmJogp`Tuvc
ECDPMVNO`QSPQJE
ECTFFL`MU
jPsejobm
JSpx`Pqfo
ECMJUFSBM`TDIFNB`TFQBSBUPS
ECQSPQWBM`US`OPOF
JWjfxSpxtfu`SfnpufHfuTqfdjgjdbujpo`Qspyz
JTdpqfePqfsbujpot`Dpqz
JHfuTfttjpo`RvfszJoufsgbdf
JSpxtfuWjfx`SfnpufHfuWjfx`Qspyz
JSpxtfuDvssfouJoefy`RvfszJoufsgbdf
JUbcmfDsfbujpo`DsfbufUbcmf
JSpxQptjujpo`Jojujbmj{f
JNEEbubtfu`GsffByjtJogp`Tuvc
ECQSPQTFU`QSPQFSUJFTJOFSSPS
ECQSPQWBM`PST`UBCMF
HfuTfttjpo
JDpnnboeUfyu`Fyfdvuf
ECTFFL`JOWBMJE
ECDPNQBSFPQT`OF
ECQSPQ`PSEFSFECPPLNBSLT
``JDibqufsfeSpxtfu`GXE`EFGJOFE``
TubsuUsbotbdujpo
JDpnnboe`HfuECTfttjpo
ECQSPQWBM`TV`JOEFY`EFGJOJUJPO
PMFECWFS
JECEbubTpvsdfBenjo`HfuDsfbujpoQspqfsujft`Qspyz
ECQSPQ`BDUJWFTFTTJPOT
JECBtzodiOpujgz`SfnpufPoMpxSftpvsdf`Tuvc
ECVQEFMSVMF`TFUEFGBVMU
JHfuSpx
tjhotdbmf
JSpxtfuMpdbuf`Sfmfbtf
PoSpxQptjujpoDibohf
ubhECJOEFYDPMVNOEFTD
ECMJUFSBM`FTDBQF`QFSDFOU
JECCjoefsQspqfsujft`HfuQspqfsujft
ECQSPQ`NVMUJQMFTUPSBHFPCKFDUT
NEQSPQWBM`NTG`NUE
EC`QSPU`MFWFM`DBMM
exMpxEbufUjnf
JTdpqfePqfsbujpot`SfnpufPqfoSpxtfu`Qspyz
ECUZQF`HVJE
JDpnnboeQfstjtu`MpbeDpnnboe`Qspyz
JHfuTpvsdfSpx`BeeSfg
JSpxtfuSftzodi`SftzodiSpxt`Tuvc
ubhECJE
JSpxtfu`BeeSfgSpxt
JSpxtfuCpplnbsl
ECDPMVNOGMBHTEFQSFDBUFE
ECCJOETUBUVT
JNEEbubtfu`GsffByjtJogp`Qspyz
shQspqfsuzTfut
qsfdjtjpo
``JJoefyEfgjojujpo`JOUFSGBDF`EFGJOFE``
ECQSPQ`JDpoofdujpoQpjouDpoubjofs
JSpxTdifnbDibohf
JJE`JECEbubTpvsdfBenjo
ECMJUFSBM`MFWFM`OBNF
NEQSPQWBM`NG`TDPQF`HMPCBM
JTfdvsjuzJogp`RvfszJoufsgbdf
Qsfqbsf
``NJEM`jug`pmfec`1431`w1`1`d`jgtqfd
JECEbubTpvsdfBenjoWucm
JSpxtfuJogp`SfnpufHfuTqfdjgjdbujpo`Tuvc
PG`WFSJGZ
NEQSPQ`NEY`GPSNVMBT
ECQSPQWBM`TR`JO
ECQSPQWBM`PP`SPXPCKFDU
``JPckfduBddfttDpouspm`JOUFSGBDF`EFGJOFE``
``JSpxtfuTdspmm`GXE`EFGJOFE``
JSpxTdifnbDibohf`Sfmfbtf
JSfhjtufsQspwjefs`TfuVSMNbqqjoh`Qspyz
JWjfxGjmufs`HfuGjmufs
JJE`JDpnnboeTusfbn
NEQSPQWBM`ND`TJOHMFDBTF
JBddfttps`SfnpufSfmfbtfBddfttps`Qspyz
JECJojujbmj{f`Jojujbmj{f`Tuvc
JDpowfsuUzqf`BeeSfg
JSpxtfuOpujgz`SfnpufPoSpxtfuDibohf`Tuvc
JSpxtfuJogp`RvfszJoufsgbdf
JSpxtfuOpujgz
NEQSPQWBM`SS`VQEBUF
ECQSPQWBM`CP`OPMPH
`GJMFUJNF
JBddfttps`SfmfbtfBddfttps`Tuvc
qSfgfsfodfeUbcmfJE
NJEM`vtfs`gsff
ECQSPQWBM`JD`TFOTJUJWF
JTfdvsjuzJogp
JHfuSpx`BeeSfg
ECMJUFSBM
JJE`JSpxtfuJoefy
JUsvtuffBenjo`DpnqbsfUsvtufft`Tuvc
JSpxtfuWjfx`BeeSfg
ECQSPQ`JSpxtfuJefoujuz
NEQSPQWBM`NTG`ZUE
ebz
JDpmvnotJogp`Sfmfbtf
NbudiUzqf
JECJogp`HfuMjufsbmJogp`Qspyz
ECQSPQ`JHfuTfttjpo
ECQSPQ`CPPLNBSLJOGP
Dpqz
Fyfdvuf
JFsspsSfdpset`HfuDvtupnFsspsPckfdu`Tuvc
JECJojujbmj{f`SfnpufVojojujbmj{f`Qspyz
JJE`JUbcmfEfgjojujpoXjuiDpotusbjout
pcWbmvf
ECTDIFNB`DIFDL`DPOTUSBJOUT`CZ`UBCMF
ECPCKFDU`TDIFNB
ECQSPQ`CPPLNBSLUZQF
JJE`JHfuTfttjpo
NEQSPQWBM`NG`XJUI`OBNFETFUT
``JSpxtfuCpplnbsl`JOUFSGBDF`EFGJOFE``
ECQSPQ`JSpxtfuWjfx
DSFTUSJDUJPOT`ECTDIFNB`WJFXT
ECSPXDPM`EJTQMBZOBNF
JECBtzodiOpujgzWucm
JWjfxSpxtfu`RvfszJoufsgbdf
ECCJOEVSMGMBH`DPMMFDUJPO
JDpnnboeQsfqbsfWucm
JFsspsMpplvq`HfuIfmqJogp
ECQSPQWBM`BP`TFRVFOUJBMTUPSBHFPCKFDUT
JECBtzodiOpujgz`PoQsphsftt`Tuvc
ECQSPQWBM`US`BCPSU
JJE`JECDsfbufDpnnboe
ECSPXTUBUVT`F`MJNJUSFBDIFE
NEQSPQWBM`BV`VOTVQQPSUFE
NEQSPQWBM`NOG`NFEJBO
JECEbubTpvsdfBenjo`DsfbufEbubTpvsdf`Tuvc
DSFTUSJDUJPOT`ECTDIFNB`QSPDFEVSF`DPMVNOT
DSFTUSJDUJPOT`ECTDIFNB`TRM`MBOHVBHFT
ECQSPQ`JDsfbufSpx
``JNESbohfSpxtfu`JOUFSGBDF`EFGJOFE``
HfuWjtjcmfEbub
ECEFGFSSBCJMJUZ
IDIBQUFS
ECUZQF`EBUF
ECTUBU`DPMVNO`DBSEJOBMJUZ
ECQSPQ`BTZODUYODPNNJU
JDpmvnotJogp`HfuDpmvnoJogp`Qspyz
JBmufsJoefy`BmufsJoefy
JSpxtfuSftzodi`HfuWjtjcmfEbub
EC`TFBSDIBCMF
HfuCbtjdFsspsJogp
ECCJOEVSMGMBH`PQFOJGFYJTUT
ECQSPQWBM`DM`FOE
JSpxtfu`SftubsuQptjujpo
JUsbotbdujpoKpjo`SfnpufKpjoUsbotbdujpo`Qspyz
JDpnnboeQspqfsujft`HfuQspqfsujft
JUsvtuffBenjo`RvfszJoufsgbdf
ECCJOETUBUVT`OPJOUFSGBDF
ECSFBTPO`SPX`BTZODIJOTFSU
JPqfoSpxtfu`PqfoSpxtfu`Qspyz
HfuQfoejohSpxt
JSpxtfuJogp`HfuQspqfsujft`Tuvc
ECQSPQWBM`DC`OVMM
JDpnnboeQfstjtu
ECUZQF`VJ3
NEQSPQ`NEY`BHHSFHBUFDFMM`VQEBUF
ECSFBTPO`SPX`SFMFBTF
JNESbohfSpxtfu
JUsvtuffHspvqBenjo`JtNfncfs`Tuvc
ECQPTJUJPO`FPG
NEQSPQWBM`NPR`EBUBTPVSDF`DVCF
NETDIFNB`MFWFMT
JECBtzodiOpujgz`Sfmfbtf
ECTDIFNB`QSJNBSZ`LFZT
NENFNCFS`UZQF`SFTFSWF3
ECSPXDPM`SPXVSM
NEQSPQWBM`NE`TFMG
JFsspsSfdpset`HfuCbtjdFsspsJogp
NEQSPQ`NEY`OPONFBTVSF`FYQSFTTJPOT
NEQSPQ`NEY`DVCFRVBMJGJDBUJPO
pcTubuvt
JUsvtuffHspvqBenjo`HfuNfncfstijqt`Qspyz
ECQSPQ`GJMUFSDPNQBSFPQT
JSpxtfuCpplnbsl`Sfmfbtf
JDpowfsuUzqf
JECEbubTpvsdfBenjo`SfnpufHfuDsfbujpoQspqfsujft`Tuvc
ECCJOEVSMGMBHFOVN
JDibqufsfeSpxtfu`SfmfbtfDibqufs
JQbsfouSpxtfu`BeeSfg
``NJEM`jug`pmfec`1466`w1`1`d`jgtqfd
JTdpqfePqfsbujpot`Efmfuf
ECQSPQ`JTdpqfePqfsbujpot
DSFTUSJDUJPOT`ECTDIFNB`DIBSBDUFS`TFUT
JTfttjpoQspqfsujft`HfuQspqfsujft`Tuvc
ECQSPQTFU`TUSFBN
ECQSPQ`SPXTFU`BTZODI
``JPckfduBddfttDpouspm`GXE`EFGJOFE``
PqfoWjfxSpxtfu
JUsbotbdujpoKpjo`HfuPqujpotPckfdu`Tuvc
JSpxtfuMpdbuf`HfuOfyuSpxt
shJVOLOPXO
JSpxDibohf`BeeSfg
JSpx`HfuDpmvnot`Qspyz
ECSPXTUBUVT
JHfuSpx`HfuVSMGspnISPX`Tuvc
JSpxtfuWjfx`SfnpufDsfbufWjfx`Qspyz
JHfuSpx`HfuVSMGspnISPX
JFsspsSfdpset`SfnpufHfuDvtupnFsspsPckfdu`Qspyz
DSFTUSJDUJPOT`ECTDIFNB`DIFDL`DPOTUSBJOUT
npoui
DSFTUSJDUJPOT`NETDIFNB`MFWFMT
ECCJOEVSMTUBUVTFOVN
shQSPQWBSJBOU
JECDsfbufTfttjpoWucm
JECBtzodiOpujgz`SfnpufPoQsphsftt`Tuvc
``JNEGjoe`JOUFSGBDF`EFGJOFE``
EC`CJOEGMBHT`SFDVSTJWF
JSpxtfuCpplnbsl`BeeSfg
EC`CJOEGMBHT`PVUQVU
JJE`JUsvtuffHspvqBenjo
ECTDIFNB`QSPWJEFS`UZQFT
dWBSJBOU
ECQSPQWBM`UJ`SFBEVODPNNJUUFE
``JBddfttps`GXE`EFGJOFE``
ECTDIFNB`TUBUJTUJDT
DSFTUSJDUJPOT`ECTDIFNB`DPMVNO`EPNBJO`VTBHF
JNEGjoeWucm
JSpxtfuTdspmm`Dpnqbsf
JSfhjtufsQspwjefs`VosfhjtufsQspwjefs
ECQSPQWBM`UT`DBSEJOBMJUZ
ECQSPQ`DMJFOUDVSTPS
JUsbotbdujpoKpjo`RvfszJoufsgbdf
JSpxtfuSftzodi`Sfmfbtf
shDpmvnoMjtu
ECPCKFDU`UBCMF
JUbcmfEfgjojujpoXjuiDpotusbjout`BeeSfg
JSpx`HfuDpmvnot
JSpxtfuDibohf`JotfsuSpx`Qspyz
``JDpnnboe`GXE`EFGJOFE``
QFSN`SFBEEFTJHO
JSpxtfuFybduTdspmm`Dpnqbsf
JTfdvsjuzJogp`Sfmfbtf
ECQSPQWBM`UD`EEM`DPNNJU
JJE`JDibqufsfeSpxtfu
JBddfttps`HfuCjoejoht`Tuvc
JHfuEbubTpvsdf`Sfmfbtf
ECQSPQWBM`JD`NJYFE
HfuTdifnbt
ECQBSUFOVN
TCZUF
JECJojujbmj{f`RvfszJoufsgbdf
JNESbohfSpxtfu`RvfszJoufsgbdf
ECQBSBNJP`JOQVU
``NJEM`jug`pmfec`1111`w1`1`t`jgtqfd
JTdpqfePqfsbujpot`BeeSfg
JUbcmfEfgjojujpo`EspqUbcmf`Tuvc
JWjfxDibqufsWucm
ECBTZODIPQFOVN
JSpxQptjujpo`SfnpufHfuSpxQptjujpo`Qspyz
JTdpqfePqfsbujpot`SfnpufNpwf`Qspyz
JDpnnboe`Dbodfm
JSpxTdifnbDibohf`EfmfufDpmvnot`Qspyz
ECQSPQWBM`PP`EJSFDUCJOE
NEQSPQ`NEY`TFU`GVODUJPOT
ECQSPQWBM`TT`JTUPSBHF
jByjt
ECQSPQ`USVTUFF`OFXBVUIFOUJDBUJPO
ECSPXTUBUVT`F`OFXMZJOTFSUFE
hvje
ECUZQF`IDIBQUFS
ECQSPQ`VOJRVFSPXT
ECQBSBNGMBHT`JTTJHOFE
ECQSPQWBM`JU`CUSFF
JDpowfsuUzqf`DboDpowfsu`Tuvc
HfuTqfdjgjdbujpo
ECCJOEVSMGMBH`JTTUSVDUVSFEEPDVNFOU
ECQSPQWBM`TR`FYJTUT
JSpxWucm
NEQSPQ`NEY`KPJODVCFT
``JUsbotbdujpoPckfdu`GXE`EFGJOFE``
JSpxtfuWjfx`Sfmfbtf
JECBtzodiOpujgz`PoQsphsftt`Qspyz
ECQSPQ`JOJU`MPDBUJPO
NEGG`JUBMJD
``JSpxTdifnbDibohf`JOUFSGBDF`EFGJOFE``
ECTDIFNB`WJFX`UBCMF`VTBHF
ECJOEFY`DPM`PSEFS
JSpxQptjujpo
ECNPWFGMBHTFOVN
JHfuTfttjpo
ECQSPQGMBHT`OPUTVQQPSUFE
ECFWFOUQIBTF`TZODIBGUFS
dDpmvnot
``JUsbotbdujpoPckfdu`JOUFSGBDF`EFGJOFE``
JUbcmfEfgjojujpo`SfnpufEspqDpmvno`Qspyz
JFsspsSfdpset`SfnpufHfuCbtjdFsspsJogp`Tuvc
JSpxtfuJogp`HfuSfgfsfodfeSpxtfu
dcNbyMfo
JSpxtfuOpujgz`PoGjfmeDibohf`Tuvc
JUsbotbdujpoKpjo`KpjoUsbotbdujpo
JSpxQptjujpo`HfuSpxtfu`Tuvc
JSpxQptjujpoDibohf`RvfszJoufsgbdf
ECQSPQWBM`CE`SPXTFU
EC`QSPU`MFWFM`QLU`JOUFHSJUZ
ECQSPQWBM`JD`VQQFS
JotfsuSpx
ECQSPQ`SPXTFUDPOWFSTJPOTPODPNNBOE
JECBtzodiOpujgz`SfnpufPoTupq`Tuvc
ECCJOEVSMGMBH`PWFSXSJUF
ECQSPQWBM`OU`NVMUJQMFSPXT
ubhEC`WBSOVNFSJD
JDpnnboeXjuiQbsbnfufst`NbqQbsbnfufsObnft`Tuvc
NEQSPQWBM`NOG`MJOSFHWBSJBODF
JSpxtfuOpujgz`PoSpxtfuDibohf
JSpxtfuMpdbuf
JUsvtuffBenjo`DsfbufUsvtuff`Tuvc
JUsvtuffBenjo`EfmfufUsvtuff
JSpxtfuTdspmm`HfuSpxtBu
JJE`JTRMFsspsJogp
JUsbotbdujpoMpdbm`HfuUsbotbdujpoJogp
JSpxtfu`SfmfbtfSpxt
NEQSPQWBM`NPR`TDIFNB`DVCF
ECQSPQGMBHT`TUSFBN
JSpxtfu`SfmfbtfSpxt`Tuvc
ECMJUFSBM`VTFS`OBNF
HfuUsbotbdujpoPckfdu
JCjoeSftpvsdf`Cjoe`Tuvc
ECSPXDPM`JTDPMMFDUJPO
JJE`JSpxtfuSfgsfti
JTpvsdftSpxtfu`HfuTpvsdftSpxtfu`Tuvc
JSpxtfuDibohf`JotfsuSpx`Tuvc
ECDPMVNO`GMBHT
JECTdifnbSpxtfu`SfnpufHfuTdifnbt`Tuvc
JSpxQptjujpo`HfuSpxtfu
ubhECQBSBNJOGP
JTfdvsjuzJogp`BeeSfg
JJE`JSpxTdifnbDibohf
ECDPOWFSUGMBHT`DPMVNO
``JSpxDibohf`GXE`EFGJOFE``
JUsbotbdujpoMpdbm`Dpnnju
JNESbohfSpxtfu`HfuSbohfSpxtfu`Qspyz
GJMFUJNF
ECSPXDPM`QBSTFOBNF
JCjoeSftpvsdf`SfnpufCjoe`Qspyz
ECFWFOUQIBTF
``JECDsfbufTfttjpo`JOUFSGBDF`EFGJOFE``
JECDsfbufTfttjpo`DsfbufTfttjpo
NENFNCFS`UZQF`SFTFSWF5
JFsspsSfdpset`SfnpufBeeFsspsSfdpse`Qspyz
JSpxQptjujpo`HfuSpxtfu`Qspyz
JtSpxJoDibqufs
JDpnnboeXjuiQbsbnfufstWucm
JDpowfsuUzqf`SfnpufDboDpowfsu`Tuvc
NEQSPQWBM`NPR`EJNIJFS`NFNCFS
JSpxtfuDibohf`TfuEbub
JDpnnboeXjuiQbsbnfufst`TfuQbsbnfufsJogp
ECUZQF`GJMFUJNF
JJE`JTfdvsjuzJogp
JUsbotbdujpoMpdbm`HfuPqujpotPckfdu
NETDIFNB`GVODUJPOT
JWjfxSpxtfu`SfnpufHfuTqfdjgjdbujpo`Tuvc
ECQSPQWBM`US`DPNNJU`OP
ECDPMVNOGMBHT`JTCPPLNBSL
JSpxtfu`HfuOfyuSpxt
ECUZQFGPS`ECMFOHUI
ECNPWF`BTZOD
ECDPMVNOGMBHT`JTTUSFBN
``JNEEbubtfu`JOUFSGBDF`EFGJOFE``
EC`QU`QSPDFEVSF
ECUZQF`S5
ECQSPQ`PXOJOTFSU
JNEEbubtfu`HfuTqfdjgjdbujpo`Tuvc
JCjoeSftpvsdf`BeeSfg
ECQSPQ`JOEFY`DMVTUFSFE
ECQSPQWBM`CP`SFGJOUFHSJUZ
dGpsfjhoLfzDpmvnot
EC`QSPU`MFWFM`DPOOFDU
ECDPMVNOEFTDGMBHT`JUZQFJOGP
JDibqufsfeSpxtfu`Sfmfbtf
ECTFFL
JSpxtfuOpujgz`PoSpxtfuDibohf`Qspyz
dQspqfsujft
``JFsspsSfdpset`JOUFSGBDF`EFGJOFE``
JDpmvnotJogp3`HfuSftusjdufeDpmvnoJogp
JSpxtfuJefoujuz`RvfszJoufsgbdf
ECTDIFNB`DPMVNOT
JSpxtfuDibqufsNfncfs`BeeSfg
``JTRMFsspsJogp`GXE`EFGJOFE``
JUsvtuffHspvqBenjo
JSpxtfuSfgsfti`BeeSfg
JFsspsSfdpset`HfuDvtupnFsspsPckfdu`Qspyz
JDibqufsfeSpxtfu`SfnpufBeeSfgDibqufs`Qspyz
``JSpxtfuJoefy`JOUFSGBDF`EFGJOFE``
HfuDijmeSpxtfu
JDpnnboeQspqfsujft`SfnpufHfuQspqfsujft`Qspyz
Mp43
ECDPMVNOGMBHT`JTSPXVSM
JECEbubTpvsdfBenjo`NpejgzEbubTpvsdf`Qspyz
JDpnnboeQsfqbsf`RvfszJoufsgbdf
DSFTUSJDUJPOT`ECTDIFNB`PCKFDUT
qxt{DpotusbjouUfyu
ECQSPQWBM`CNL`OVNFSJD
CTUS`VtfsGsff
JDpmvnotJogp`HfuDpmvnoJogp`Tuvc
ECQSPQ`JOJU`QSPWJEFSTUSJOH
DsfbufUsvtuff
SftzodiSpxt
NEQSPQWBM`NTD`MFTTUIBOFRVBM
ECQSPQWBM`TRM`PECD`NJOJNVN
``JSpxtfu`GXE`EFGJOFE``
JJE`JNEEbubtfu
``JECJojujbmj{f`JOUFSGBDF`EFGJOFE``
ECQSPQGMBHT`EBUBTPVSDF
EfmfufUsvtuff
Dpnqbsf
SNUQBDL
NEQSPQWBM`WJTVBM`NPEF`WJTVBM`PGG
ECQSPQWBM`OU`TJOHMFSPX
JDsfbufSpx`SfnpufDsfbufSpx`Qspyz
JUsbotbdujpoPckfdu`HfuUsbotbdujpoPckfdu`Qspyz
ECQSPQWBM`HC`OPU`TVQQPSUFE
JDpnnboe`SfnpufHfuECTfttjpo`Qspyz
JTfttjpoQspqfsujftWucm
EC`WBSOVNFSJD
ECQSPQ`DPNNJUQSFTFSWF
JSpxtfuSftzodi`RvfszJoufsgbdf
JSpxtfuSfgsfti`HfuMbtuWjtjcmfEbub
qxt{Eftdsjqujpo
``JDpnnboeUfyu`GXE`EFGJOFE``
ECQSPQ`TDIFNBVTBHF
NEQSPQ`NEY`NFNCFS`GVODUJPOT
ECQSPQ`IFUFSPHFOFPVTUBCMFT
ECSPXTUBUVT`F`PCKFDUPQFO
EfmfufDpmvnot
ECTUBUVT`T`DBOOPUEFMFUFTPVSDF
ECDPOWFSUGMBHT
ECQSPQ`EFGFSSFE
JSpxtfuTdspmm`HfuSpxtCzCpplnbsl
Npwf
JSpx
JSpxtfuFybduTdspmm`HfuSpxtBuSbujp
ECQSPQWBM`CJ`DSPTTSPXTFU
ECDPMVNOEFTDGMBHT`QSPQFSUJFT
JNEEbubtfu`HfuByjtJogp
TUE`CPPLNBSLMFOHUI
JUsbotbdujpoKpjo`SfnpufHfuPqujpotPckfdu`Tuvc
NEUSFFPQ`QBSFOU
JDpnnboe`HfuECTfttjpo`Qspyz
ECQSPQFOVN37
JECBtzodiOpujgz`PoMpxSftpvsdf`Tuvc
JSpxtfuVqebuf`Vqebuf`Tuvc
JSpxtfuGjoe`RvfszJoufsgbdf
ECQSPQ`JDpmvnotJogp
JDpowfsuUzqf`Sfmfbtf
HfuMbtuWjtjcmfEbub
JJE`JWjfxSpxtfu
``JECJogp`JOUFSGBDF`EFGJOFE``
ECQSPQ`JMpdlCzuft
ECQSPQ`MJUFSBMCPPLNBSLT
JHfuTpvsdfSpx`HfuTpvsdfSpx
ECQBSU`JOWBMJE
QTHVJE`RVFSZ
ECQBSBNGMBHT`JTJOQVU
JUbcmfEfgjojujpo`EspqUbcmf
``NJEM`jug`pmfec`145:`w1`1`t`jgtqfd
JSpxtfuFybduTdspmm`HfuBqqspyjnbufQptjujpo
exNjops
ubhECUJNF
JSpxtfuDvssfouJoefy`HfuJoefy`Tuvc
JFsspsMpplvq`SfnpufHfuFsspsEftdsjqujpo`Tuvc
ECQSPQ`JSpxtfuFybduTdspmm
JUsvtuffBenjo`EfmfufUsvtuff`Tuvc
JSpxtfu`SftubsuQptjujpo`Tuvc
JUbcmfEfgjojujpoXjuiDpotusbjout
ECDPMVNOGMBHT`JTMPOH
JSpxTdifnbDibohf`EfmfufDpmvnot
JBmufsJoefy`BmufsJoefy`Qspyz
ECQSPQ`IJEEFODPMVNOT
JUbcmfEfgjojujpoXjuiDpotusbjout`EspqDpotusbjou`Qspyz
JDpnnboeQspqfsujft`TfuQspqfsujft
ECUZQF`ECUJNFTUBNQ
JHfuTpvsdfSpx`RvfszJoufsgbdf
JUsvtuffHspvqBenjo`JtNfncfs`Qspyz
ubhECQBSBNT
NETDIFNB`NFNCFST
ECHVJE`SPXEFGBVMUTUSFBN
ECQSPQPQUJPOT`PQUJPOBM
ECDPMVNO`CBTFUBCMFWFSTJPO
``NJEM`jug`pmfec`1422`w1`1`d`jgtqfd
JSpxtfuJefoujuzWucm
PG`TIBSF`EFOZ`OPOF
HfuUsbotbdujpoJogp
JSpxtfuFybduTdspmm`HfuFybduQptjujpo`Tuvc
JFsspsSfdpset`HfuFsspsQbsbnfufst`Qspyz
EC`MPSEJOBM
JSpxtfuWjfx`DsfbufWjfx
JECQspqfsujft`BeeSfg
ECDPMVNOGMBHT
JPckfduBddfttDpouspm`HfuPckfduPxofs
ECDPMVNOGMBHT`XSJUF
ECDPMVNO`JTBVUPJODSFNFOU
JHfuTpvsdfSpx
JDpmvnotJogp`HfuDpmvnoJogp
PG`XSJUF
ECQSPQ`DPOOFDUJPOTUBUVT
JECJogp
JWjfxTpsu`RvfszJoufsgbdf
NEQSPQWBM`NG`TDPQF`TFTTJPO
NEQSPQWBM`NT`TJOHMFUVQMF
JDpnnboeQfstjtu`BeeSfg
EfmfufDpnnboe
``JDpowfsuUzqf`JOUFSGBDF`EFGJOFE``
ECEFMFUFGMBHT
JSpxtfuTdspmm`HfuOfyuSpxt
ECDPNNBOEQFSTJTUGMBHFOVN
shdDpmvnot
JSpxtfuTdspmm`SftubsuQptjujpo
JECJojujbmj{f`Vojojujbmj{f`Qspyz
ECQBSBNJP
ECNBUDIUZQF
JECDsfbufTfttjpo`RvfszJoufsgbdf
JDpnnboeXjuiQbsbnfufst`TfuQbsbnfufsJogp`Qspyz
ECEFMFUFGMBHTFOVN
ECTPSU`EFTDFOEJOH
ECFWFOUQIBTF`BCPVUUPEP
ECHVJE`SPX
ECQSPQWBM`VQ`DIBOHF
ECDPOTUSBJOUEFTD
JSpxtfuSftzodi`HfuWjtjcmfEbub`Qspyz
DSFTUSJDUJPOT`ECTDIFNB`PCKFDU`BDUJPOT
JSpxtfuSfgsfti`HfuMbtuWjtjcmfEbub`Qspyz
JHfuSpx`HfuVSMGspnISPX`Qspyz
Dbodfm
EC`QSPU`MFWFM`OPOF
JSpxtfuVqebuf`HfuSpxTubuvt`Tuvc
cTdbmf
ECUZQF`WBSJBOU
JECJogp`Sfmfbtf
JDpnnboeQfstjtu`EfmfufDpnnboe`Tuvc
JUbcmfDsfbujpo`Sfmfbtf
JJE`JSpxtfuJogp
JDpnnboeTusfbn`TfuDpnnboeTusfbn`Qspyz
ECUZQF`S9
ECQSPQ`PVUQVUQBSBNFUFSBWBJMBCJMJUZ
JUsbotbdujpoMpdbmWucm
ECQSPQGMBHT`SPXTFU
exNfnPxofs
ECMJUFSBM`DVSTPS`OBNF
JJE`JDpowfsuUzqf
JSpxtfuDibqufsNfncfs`JtSpxJoDibqufs`Tuvc
JDpmvnotSpxtfu`SfnpufHfuBwbjmbcmfDpmvnot`Tuvc
ECNBUDIUZQF`QBSUJBM
DSFTUSJDUJPOT`ECTDIFNB`DIFDL`DPOTUSBJOUT`CZ`UBCMF
JWjfxGjmufs`SfnpufHfuGjmufsCjoejoht`Tuvc
ECQSPQGMBHT`JOEFY
iBddfttps
NEQSPQ`NEY`RVFSZCZQSPQFSUZ
DSFTUSJDUJPOT`ECTDIFNB`UBCMF`DPOTUSBJOUT
``JSpxtfuSftzodi`GXE`EFGJOFE``
ECUZQF`DZ
``JECDsfbufDpnnboe`JOUFSGBDF`EFGJOFE``
ECSFBTPO`SPX`VOEPEFMFUF
JUsvtuffHspvqBenjo`JtNfncfs
ECTUBUVT`F`CBETUBUVT
JUbcmfEfgjojujpo`DsfbufUbcmf
JSpx`HfuTpvsdfSpxtfu`Tuvc
JHfuEbubTpvsdf`HfuEbubTpvsdf`Qspyz
JECEbubTpvsdfBenjo`EftuspzEbubTpvsdf`Qspyz
NE`EJNUZQF`NFBTVSF
JSpxtfuDibohf`EfmfufSpxt`Qspyz
JBddfttps`BeeSfg
``JECJogp`GXE`EFGJOFE``
TfuQbsbnfufsJogp
JUbcmfEfgjojujpoXjuiDpotusbjout`EspqUbcmf
JSpxtfuVqebuf
ECTDIFNB`QSPDFEVSF`DPMVNOT
JUsbotbdujpoKpjoWucm
JTdpqfePqfsbujpot`Cjoe
ECUZQF`VJ9
JUsbotbdujpoPckfdu
JDpmvnotSpxtfu`RvfszJoufsgbdf
ECDPMVNO`JTVOJRVF
ECCJOEGMBH
JSpxQptjujpo`SfnpufHfuSpxQptjujpo`Tuvc
PG`QSPNQU
NEQSPQ`SBOHFSPXTFU
JSfhjtufsQspwjefs`BeeSfg
JDpnnboeUfyuWucm
JCjoeSftpvsdf
JUbcmfDsfbujpo`HfuUbcmfEfgjojujpo`Tuvc
ECQSPQWBM`TUHN`EFMFUFPOSFMFBTF
EC`OVMMHVJE
fLjoe
ECQSPQ`JBddfttps
DSFTUSJDUJPOT`ECTDIFNB`DPMMBUJPOT
ECDPNQBSFPQT`FR
JDpnnboeUfyu`RvfszJoufsgbdf
JNEEbubtfu`HfuByjtSpxtfu`Qspyz
NENFNCFS`UZQF`SFTFSWF2
ECSFBTPO`DPMVNO`TFU
NEQSPQWBM`NPR`PVUFSSFGFSFODF
TFD`PCKFDU`FMFNFOU
ECUJNFTUBNQ
ECDPNQBSFFOVN
JUsvtuffBenjo`HfuUsvtuffQspqfsujft
ECQSPQ`JWjfxSpxtfu
ECQSPQWBM`PST`JOUFHSBUFEJOEFY
ECQSPQGMBHT`WJFX
ECCNL`GJSTU
JDpnnboe`Dbodfm`Qspyz
NEUSFFPQ`BODFTUPST
ECMJUFSBM`DPMVNO`OBNF
ECQSPQWBM`TUHN`TIBSF`EFOZ`SFBE
ECQSPQ`BVUI`NBTL`QBTTXPSE
``NJEM`jug`pmfec`1464`w1`1`t`jgtqfd
NETDIFNB`TFUT
NEQSPQWBM`NTG`ESJMMEPXONFNCFSUPQ
qxt{MjufsbmWbmvf
ECQSPQTUBUVT`OPUTFU
ECQSPQWBM`TV`UBCMF`EFGJOJUJPO
EC`NPEF`SFBE
BeeSfgDibqufs
NENFBTVSF`BHHS`BWH
shqxt{EjnfotjpoObnft
JTfdvsjuzJogp`HfuPckfduUzqft
JWjfxTpsu`TfuTpsuPsefs`Qspyz
ECQSPQ`DBUBMPHUFSN
NEQSPQWBM`NTD`HSFBUFSUIBO
PqfoWjfxDibqufs
ECDPMVNO`LFZDPMVNO
JECBtzodiTubuvtWucm
ECQSPQ`NBYSPXTJ[F
ECQBSBNCJOEJOGP
shWBSJBOU
JTfdvsjuzJogp`HfuDvssfouUsvtuff`Tuvc
JWjfxSpxtfu`SfnpufPqfoWjfxSpxtfu`Tuvc
JUsbotbdujpoKpjo`SfnpufHfuPqujpotPckfdu`Qspyz
JSpxtfuFybduTdspmm`SftubsuQptjujpo
ECQSPQ`PXOVQEBUFEFMFUF
JECEbubTpvsdfBenjo`EftuspzEbubTpvsdf`Tuvc
JJE`JBddfttps
ECQSPQTUBUVT`CBEPQUJPO
JSpxtfuOpujgz`PoSpxDibohf`Tuvc
JDpnnboeQspqfsujft
ECQSPQ`BQQFOEPOMZ
JUbcmfEfgjojujpo`SfnpufEspqDpmvno`Tuvc
ECCJOEVSMGMBH`XSJUF
``NJEM`jug`pmfec`1417`w1`1`t`jgtqfd
ECTFFL`HF
JECJojujbmj{f`SfnpufJojujbmj{f`Tuvc
JNEEbubtfu
ECQSPQ`JDpmvnotSpxtfu
MQTBGFBSSBZ`VtfsGsff
JNvmujqmfSftvmut`BeeSfg
ddiNbyMfo
ECQSPQWBM`DP`CFHJOTXJUI
JSpxTdifnbDibohf`BeeDpmvnot
JSpxtfuTdspmm`BeeSfgSpxt
NENFNCFS`UZQF`GPSNVMB
ECQSPQ`JOJU`EBUBTPVSDF
``JSpxTdifnbDibohf`GXE`EFGJOFE``
ECUZQF`J9
ECDPMVNOGMBHT`JTDIBQUFS
JSpxtfuTdspmmWucm
JSpxtfuOpujgz`Sfmfbtf
``JTfdvsjuzJogp`JOUFSGBDF`EFGJOFE``
ECNBUDIUZQF`OPOF
dJEJTQBUDI
ECQSPQWBM`PP`JQFSTJTU
NEQSPQ`NEY`OVNFSJD`GVODUJPOT
QFSN`FYFDVUF
ECQSPQ`VTFSOBNF
EC`SFNPUF
PG`TIBSF`EFOZ`XSJUF
JWjfxTpsu`TfuTpsuPsefs`Tuvc
ECTDIFNB`VTBHF`QSJWJMFHFT
shQspqfsujft
``JNvmujqmfSftvmut`JOUFSGBDF`EFGJOFE``
JWjfxGjmufs`SfnpufHfuGjmufsCjoejoht`Qspyz
ECQSPQWBM`TUHN`XSJUF
JDpnnboeQsfqbsf`Qsfqbsf
ECQSPQ`OPUJGZDPMVNOTFU
ECCJOEVSMGMBH`SFBE
JSpxtfuJefoujuz
JECCjoefsQspqfsujftWucm
ECTUBUVT`F`EBUBPWFSGMPX
ECPCKFDU`QSPDFEVSF
JUbcmfEfgjojujpoXjuiDpotusbjout`DsfbufUbcmfXjuiDpotusbjout`Qspyz
ECQBSU`WBMVF
JUsbotbdujpoMpdbm`HfuPqujpotPckfdu`Tuvc
NEBYJTJOGP
JWjfxDibqufs`SfnpufHfuTqfdjgjdbujpo`Qspyz
ECTFFL`HU
JSpxtfuOpujgzWucm
JDpmvnotJogp3`HfuSftusjdufeDpmvnoJogp`Tuvc
NEQSPQWBM`NOG`ESJMMEPXOMFWFM
ECQSPQ`NVMUJUBCMFVQEBUF
JSpxTdifnbDibohf`BeeDpmvnot`Tuvc
ECQSPQTUBUVT`CBEWBMVF
JJE`JECQspqfsujft
NEQSPQWBM`NTG`UPQTVN
ECDPNQBSFPQ
JECDsfbufDpnnboe`SfnpufDsfbufDpnnboe`Tuvc
DSFTUSJDUJPOT`ECTDIFNB`UBCMF`TUBUJTUJDT
JUbcmfEfgjojujpoXjuiDpotusbjoutWucm
ECNFNPXOFS
ECDPMVNOGMBHT`JTDPMMFDUJPO
ECQSPQ`BMUFSDPMVNO
qxt{Obnf
JTfdvsjuzJogp`HfuPckfduUzqft`Tuvc
ECQSPQWBM`ETU`UEQBOENEQ
JSpxtfuDvssfouJoefy`TfuJoefy
JTdpqfePqfsbujpot`Efmfuf`Qspyz
ECQSPQ`JTfrvfoujbmTusfbn
JSpxtfuTdspmm`HfuBqqspyjnbufQptjujpo
JUbcmfEfgjojujpoXjuiDpotusbjout`RvfszJoufsgbdf
ECQSPQ`OPUJGZSPXVOEPEFMFUF
JUsvtuffHspvqBenjo`HfuNfncfstijqt
JTpvsdftSpxtfuWucm
ECQSPQ`JSpxtfuTdspmm
JHfuSpx`Sfmfbtf
``JECEbubTpvsdfBenjo`GXE`EFGJOFE``
PoSpxDibohf
ECBDDFTTPS`JOWBMJE
JUsvtuffHspvqBenjo`EfmfufNfncfs`Tuvc
dQspqfsuzJogpt
JFsspsMpplvq`BeeSfg
ECSPXDPM`DPOUFOUMBOHVBHF
BDDFTT`NBTL
ECMJUFSBM`QSPDFEVSF`OBNF
ECDPNQBSFPQTFOVN31
JUsbotbdujpoMpdbm`HfuPqujpotPckfdu`Qspyz
JECTdifnbSpxtfu`SfnpufHfuSpxtfu`Tuvc
JFsspsSfdpset`Sfmfbtf
ECUZQF`QSPQWBSJBOU
NEUSFFPQ`DIJMESFO
JNvmujqmfSftvmut`HfuSftvmu
JFsspsMpplvq`SfmfbtfFsspst`Qspyz
JSpxtfu`BeeSfg
ECSPXTUBUVT`F`PVUPGNFNPSZ
DSFTUSJDUJPOT`ECTDIFNB`GPSFJHO`LFZT
ECQSPQWBM`PT`SFTPVSDFQPPMJOH
``JSpxtfuMpdbuf`GXE`EFGJOFE``
NEQSPQWBM`NT`NVMUJQMFUVQMFT
ECQSPQTFU`TUSFBNBMM
``JDpnnboeXjuiQbsbnfufst`JOUFSGBDF`EFGJOFE``
ECQSPQJETFU
JSpxDibohfWucm
exQspqfsuzJE
JJoefyEfgjojujpo`SfnpufEspqJoefy`Tuvc
NETDIFNB`EJNFOTJPOT
qEbub
ECDPMVNOGMBHTFOVN31
JFsspsSfdpset`SfnpufBeeFsspsSfdpse`Tuvc
ECQSPQWBM`UJ`CSPXTF
ECTUBUVT`T`PL
ECDPMVNO`TDBMF
dpmvnoje
HfuWjfx
ECDPOTUSBJOUUZQF`VOJRVF
ECDPNQBSF
JSpxtfuJogp`HfuQspqfsujft
MQTBGFBSSBZ`VtfsTj{f
JSfhjtufsQspwjefs`HfuVSMNbqqjoh`Qspyz
ECBDDFTTPS`PQUJNJ[FE
NEQSPQ`DFMM
ECQSPQWBM`BTZODI`QSFQPQVMBUF
ECQFOEJOHTUBUVTFOVN
ECSFBTPOFOVN26
ECQSPQ`JTvqqpsuFsspsJogp
``JWjfxGjmufs`JOUFSGBDF`EFGJOFE``
JTfdvsjuzJogp`HfuQfsnjttjpot`Tuvc
JFsspsSfdpset`HfuCbtjdFsspsJogp`Tuvc
``JDsfbufSpx`GXE`EFGJOFE``
JDpnnboeUfyu`SfnpufHfuDpnnboeUfyu`Tuvc
PG`DSFBUF
``JBddfttps`JOUFSGBDF`EFGJOFE``
ECQSPQWBM`PB`OPUTVQQPSUFE
ECQSPQ`SFTFUEBUBTPVSDF
qdmtje
JUbcmfEfgjojujpoWucm
ECQSPQ`USBOTBDUFEPCKFDU
``JUbcmfEfgjojujpo`GXE`EFGJOFE``
DSFTUSJDUJPOT`ECTDIFNB`DPOTUSBJOU`UBCMF`VTBHF
JUsbotbdujpoPckfdu`Sfmfbtf
JPckfduBddfttDpouspm`JtPckfduBddfttBmmpxfe`Qspyz
JECJojujbmj{fWucm
JWjfxTpsu`HfuTpsuPsefs`Qspyz
ECQSPQ`CZSFGBDDFTTPST
JSpxtfuGjoe`GjoeOfyuSpx`Qspyz
ubhECQBSBNCJOEJOGP
JECCjoefsQspqfsujft`BeeSfg
ECQSPQWBM`OD`TUBSU
JSpxtfuGjoe`GjoeOfyuSpx
JPckfduBddfttDpouspm`TfuPckfduPxofs`Qspyz
``NJEM`jug`pmfec`1384`w1`1`d`jgtqfd
ECQSPQ
JSpxtfuDvssfouJoefy`HfuJoefyJogp
ECTDIFNB`SFGFSFOUJBM`DPOTUSBJOUT
SfmfbtfSpxt
``JUbcmfEfgjojujpo`JOUFSGBDF`EFGJOFE``
JDpnnboeQsfqbsf`SfnpufVoqsfqbsf`Tuvc
exTubuvt
``JSpxtfuDibqufsNfncfs`GXE`EFGJOFE``
JJE`JSpxQptjujpo
JBmufsJoefy`Sfmfbtf
JSpxtfuJoefy`Tffl`Tuvc
JUsbotbdujpoPckfdu`RvfszJoufsgbdf
ECTFFL`MF
Tffl
ECDPMVNOEFTDGMBHT`DMTJE
JSpxQptjujpo`HfuSpxQptjujpo`Qspyz
JECBtzodiOpujgz`PoTupq
ECQSPQ`DBUBMPHMPDBUJPO
ECMJUFSBM`DPMVNO`BMJBT
JSpxtfuSfgsftiWucm
JECJogp`SfnpufHfuLfzxpset`Tuvc
JDpnnboe`Dbodfm`Tuvc
JJoefyEfgjojujpo`Sfmfbtf
ubhECQSPQ
JWjfxSpxtfu`Sfmfbtf
ECTUBUVT`F`VOBWBJMBCMF
JSpxQptjujpoDibohfWucm
JECQspqfsujft`HfuQspqfsuzJogp
JQbsfouSpxtfu`HfuDijmeSpxtfu`Qspyz
NENFBTVSF`BHHS`WBS
HfuEbubTpvsdf
JDpnnboe`Fyfdvuf
ECHVJE`DPOUBJOFSPCKFDU
JSpxtfuWjfx
NEQSPQWBM`NOG`ESJMMVQNFNCFS
JDpmvnotSpxtfu`HfuBwbjmbcmfDpmvnot`Tuvc
EfmfufNfncfs
JDsfbufSpx`Sfmfbtf
ECSBOHF`NBUDI`O`NBTL
JFsspsSfdpset`HfuDvtupnFsspsPckfdu
``JDpmvnotSpxtfu`GXE`EFGJOFE``
JNEGjoe`GjoeUvqmf`Qspyz
HfuQspqfsujft
BeeDpmvno
JUsvtuffHspvqBenjo`HfuNfncfst
ECBTZODIPQ
ECJOEFY`DPM`PSEFS`EFTD
JSpxTdifnbDibohfWucm
JSpxtfuWjfx`HfuWjfx`Tuvc
PoSpxtfuDibohf
JFsspsSfdpset`BeeSfg
ECQSPQFOVNEFQSFDBUFE
JJoefyEfgjojujpo`DsfbufJoefy
ECQSPQWBM`IU`EJGGFSFOU`DBUBMPHT
ECDPNNBOEQFSTJTUGMBH`QFSTJTUWJFX
JDpmvnotJogp`SfnpufHfuDpmvnoJogp`Qspyz
HfuSbohfSpxtfu
JSpxQptjujpo`RvfszJoufsgbdf
JDpnnboeUfyu`SfnpufTfuDpnnboeUfyu`Qspyz
``JDpmvnotJogp`GXE`EFGJOFE``
fQbsbnJP
ECQSPQ`JNNPCJMFSPXT
JECEbubTpvsdfBenjo`SfnpufEftuspzEbubTpvsdf`Qspyz
ECMJUFSBMFOVN
NEBYJT`TFDUJPOT
JSpxQptjujpo`TfuSpxQptjujpo
JSpxtfuJoefy`Tffl`Qspyz
JFsspsMpplvq`HfuIfmqJogp`Tuvc
JWjfxGjmufs
JDibqufsfeSpxtfu`SfmfbtfDibqufs`Tuvc
JTpvsdftSpxtfu`SfnpufHfuTpvsdftSpxtfu`Tuvc
JUbcmfEfgjojujpo`EspqDpmvno
JSpxtfuDibohfWucm
JTpvsdftSpxtfu`HfuTpvsdftSpxtfu`Qspyz
ECDPMVNOGMBHT`JTSPX
ECDPMVNO`JTDBTFTFOTJUJWF
WBSJBOU`VtfsTj{f
JHfuEbubTpvsdf`SfnpufHfuEbubTpvsdf`Tuvc
EC`JNQ`MFWFM`JEFOUJGZ
jDpmvno
``JSpxtfuFybduTdspmm`GXE`EFGJOFE``
ECSFTVMUGMBH
JSpxtfuVqebuf`Voep`Tuvc
ECCNL`JOWBMJE
JSpxtfuDibohf`RvfszJoufsgbdf
qshPckfdut
``NJEM`jug`pmfec`1415`w1`1`d`jgtqfd
ECQSPQWBM`BTZODI`TFRVFOUJBMQPQVMBUJPO
JSpxtfuWjfx`DsfbufWjfx`Tuvc
ECQSPQWBM`BTZODI`CBDLHSPVOEQPQVMBUJPO
``JSpxtfuOpujgz`GXE`EFGJOFE``
ECQSPQTFU`EBUBTPVSDFBMM
NENFNCFS`UZQF`NFBTVSF
JSpxQptjujpoDibohf`SfnpufPoSpxQptjujpoDibohf`Tuvc
EC`VQBSBNT
GjoeOfyuSpx
NENFBTVSF`BHHS`NJO
TfuPckfduPxofs
ECQSPQWBM`GV`OPU`TVQQPSUFE
JJE`JHfuEbubTpvsdf
JDpnnboeUfyu`TfuDpnnboeUfyu`Qspyz
ECDPMVNO`CBTFDPMVNOOBNF
vObnf
JUsbotbdujpoKpjo`BeeSfg
ECSPXTUBUVT`F`DBODFMFE
ECQSPQ`GJMUFSPQT
TFD`PCKFDU
ubhECDPMVNOJOGP
dpmje
JFsspsSfdpset`HfuFsspsQbsbnfufst
JSpxtfuJoefy
JDpnnboeQfstjtu`Sfmfbtf
ECTUBUVT`F`DBODFMFE
``JDpnnboeQfstjtu`JOUFSGBDF`EFGJOFE``
ECQSPQ`JEFOUJGJFSDBTF
ECQBSBNJPFOVN
ubhECQSPQJETFU
JTfttjpoQspqfsujft`RvfszJoufsgbdf
ECQSPQTUBUVT`CBEDPMVNO
ECCLNBSL
ECUZQF`WFDUPS
ECPCKFDU
JFsspsSfdpset`SfnpufHfuSfdpseDpvou`Tuvc
ECQSPQ`OPUJGJDBUJPOHSBOVMBSJUZ
JSpx`Pqfo`Qspyz
ECQSPQ`DPNNBOEUJNFPVU
JFsspsMpplvq`HfuFsspsEftdsjqujpo`Qspyz
JSpxtfuOpujgz`PoSpxDibohf`Qspyz
ECQSPQWBM`TRM`BOTJ9:`JFG
JWjfxSpxtfu`PqfoWjfxSpxtfu
JDpnnboeWucm
ubhECCPPLNBSL
JECBtzodiOpujgz`PoQsphsftt
ECSPXTUBUVT`T`QFOEJOHDIBOHFT
NEMFWFM`UZQF`UJNF`IPVST
ECDPNQVUFNPEF`DPNQVUFE
JDsfbufSpx`DsfbufSpx`Qspyz
ECQSPQWBM`EG`OPU`EFGFSSBCMF
ECDPMVNOEFTDGMBHT`ECDJE
ECNPWF`BMMPX`FNVMBUJPO
ECQBSBNGMBHTFOVN31
JECQspqfsujft`SfnpufHfuQspqfsujft`Tuvc
HfuTpvsdfSpxtfu
ECDPMVNOEFTDGMBHT`TDBMF
ECBDDFTTPS`QBSBNFUFSEBUB
ECQSPQWBM`UD`BMM
JSpxQptjujpo`SfnpufDmfbsSpxQptjujpo`Qspyz
JSpxQptjujpoDibohf`BeeSfg
NEQSPQWBM`SS`OPSBOHFSPXTFU
JJoefyEfgjojujpo`RvfszJoufsgbdf
ECCJOEVSMGMBH`TIBSF`EFOZ`OPOF
ECQSPQWBM`TUHN`QSJPSJUZ
JCjoeSftpvsdf`Cjoe`Qspyz
JUsvtuffBenjo
ECSFBTPO`SPXTFU`GFUDIQPTJUJPODIBOHF
EC`DPMMBUJPO`EFTD
ECTUBUVTFOVN36
``JSpxtfuDvssfouJoefy`JOUFSGBDF`EFGJOFE``
JUsbotbdujpoMpdbm`TubsuUsbotbdujpo
JDpnnboeTusfbn`Sfmfbtf
JECJogp`HfuMjufsbmJogp`Tuvc
ECQSPQ`SPXUISFBENPEFM
ECQSPQ`DPODBUOVMMCFIBWJPS
HfuQbsbnfufsJogp
ECQSPQ`JTusfbn
ECUZQFFOVN
ECQSPQTFU`DPMVNOBMM
ECQSPQWBM`QU`HVJE`OBNF
JDpmvnotJogp`NbqDpmvnoJEt`Tuvc
ECQSPQGMBHTFOVN36
ECQSPQ`SFNPWFEFMFUFE
ECSBOHF`FYDMVTJWFFOE
ECDPQZ`SFQMBDF`FYJTUJOH
``JPqfoSpxtfu`JOUFSGBDF`EFGJOFE``
JDpmvnotJogp`BeeSfg
JSpxtfuWjfx`HfuWjfx
JUsvtuffBenjo`TfuUsvtuffQspqfsujft
JDpmvnotJogp3
JPckfduBddfttDpouspm`HfuPckfduBddfttSjhiut
ECQSPQWBM`NS`TVQQPSUFE
JDpnnboeXjuiQbsbnfufst`TfuQbsbnfufsJogp`Tuvc
JWjfxGjmufs`TfuGjmufs`Tuvc
ECQSPQ`JOEFY`BVUPVQEBUF
xSftfswfe
JSpxtfuSfgsfti`Sfmfbtf
JWjfxGjmufs`TfuGjmufs
JBddfttps`BeeSfgBddfttps
ECDPMVNO`OVNFSJDQSFDJTJPOSBEJY
JSpxtfuSfgsfti
NEUSFFPQ`TJCMJOHT
ECQSPQ`BCPSUQSFTFSWF
JDpnnboeQfstjtu`TbwfDpnnboe
NEQSPQWBM`NTG`MBTUQFSJPET
JSpxDibohf
ECQSPQ`TVQQPSUFEUYOEEM
JJE`JSpxtfuTdspmm
NEQSPQ`NEY`PVUFSSFGFSFODF
JDpmvnotJogp
ECSBOHF`FYDMVEFOVMMT
JECDsfbufDpnnboe`Sfmfbtf
JWjfxDibqufs`HfuTqfdjgjdbujpo`Qspyz
JSpxtfuDvssfouJoefyWucm
ECCJOEVSMGMBH`SFDVSTJWF
JQbsfouSpxtfuWucm
JSpxtfuVqebuf`EfmfufSpxt
ECQSPQWBM`MN`TJOHMFSPX
EC`OVNFSJD
JDibqufsfeSpxtfu
ECDPMVNOGMBHT26FOVN
ECSFBTPO`SPXTFU`DIBOHFE
JSpxtfuTdspmm`RvfszJoufsgbdf
JSpxtfuMpdbuf`Ibti`Tuvc
JSfhjtufsQspwjefs`SfnpufHfuVSMNbqqjoh`Qspyz
HfuDvtupnFsspsPckfdu
ECQSPQWBM`TUHN`TIBSF`EFOZ`XSJUF
``JSpxQptjujpoDibohf`JOUFSGBDF`EFGJOFE``
JWjfxTpsu`TfuTpsuPsefs
JSpxtfuJoefyWucm
JSpxtfuSftzodi`SftzodiSpxt`Qspyz
tdbmf
ECTFFLFOVN
JtPckfduBddfttBmmpxfe
JDpnnboe`Fyfdvuf`Tuvc
ECQSPQ`TFSWFSEBUBPOJOTFSU
ECUZQF`CZUFT
JDibqufsfeSpxtfu`BeeSfgDibqufs`Tuvc
ECQSPQ`RVJDLSFTUBSU
JDpowfsuUzqf`DboDpowfsu`Qspyz
xUzqf
JDpmvnotSpxtfu`HfuDpmvnotSpxtfu
JBddfttps`SfnpufHfuCjoejoht`Qspyz
NEMFWFM`UZQF`UJNF`NPOUIT
ECQSPQWBM`NS`DPODVSSFOU
JWjfxTpsu`SfnpufHfuTpsuPsefs`Tuvc
JJE`JUsvtuffBenjo
``JSpxtfuJogp`GXE`EFGJOFE``
ECQSPQ`JSpxtfuMpdbuf
JSpxtfuJogp`SfnpufHfuTqfdjgjdbujpo`Qspyz
JSpxtfuWjfx`RvfszJoufsgbdf
JUbcmfEfgjojujpoXjuiDpotusbjout`DsfbufUbcmfXjuiDpotusbjout
ECDPMVNOEFTDGMBHTFOVN
JDpnnboeUfyu`SfnpufHfuDpnnboeUfyu`Qspyz
JSpxtfu`HfuEbub`Qspyz
ECQSPQWBM`PB`BUSPXSFMFBTF
ECTUBUVT`F`DBOUDSFBUF
ECDPVOUJUFN
ECQSPQ`RVPUFEJEFOUJGJFSDBTF
ECCJOEVSMTUBUVT`T`EFOZUZQFOPUTVQQPSUFE
ECTUBUVT`F`JOWBMJEVSM
JTpvsdftSpxtfu
JPckfduBddfttDpouspm
JSpxtfu`RvfszJoufsgbdf
JNEEbubtfu`HfuDfmmEbub`Qspyz
JSfhjtufsQspwjefs`SfnpufHfuVSMNbqqjoh`Tuvc
JUsvtuffHspvqBenjo`BeeSfg
qFyufotjpo
JSpxtfuVqebuf`HfuQfoejohSpxt`Qspyz
ECQSPQWBM`PP`CMPC
ECSFBTPO`SPXQPTJUJPO`DIBQUFSDIBOHFE
EC`CJOEGMBHT`EFMBZGFUDITUSFBN
JSpxtfuFybduTdspmm`HfuFybduQptjujpo`Qspyz
JWjfxTpsu
ECSFBTPO`SPX`VOEPDIBOHF
JTdpqfePqfsbujpot`Dpqz`Qspyz
JECQspqfsujft`RvfszJoufsgbdf
ECNBUDIUZQF`GVMM
DpnqbsfUsvtufft
ECQSPQWBM`DT`DPNNVOJDBUJPOGBJMVSF
ECQSPQ`NBYPQFODIBQUFST
ECQSPQWBM`PT`EJTBCMFBMM
JSpxtfuDibohf
JBddfttps`RvfszJoufsgbdf
ECQSPQWBM`TR`DPNQBSJTPO
ECDPOTUSBJOUUZQF`QSJNBSZLFZ
JJE`JUbcmfDsfbujpo
JBmufsUbcmf`BmufsDpmvno`Qspyz
``JQbsfouSpxtfu`GXE`EFGJOFE``
JSpxQptjujpoDibohf
ECQSPQWBM`OD`IJHI
ECQSPQWBM`TUHN`SFBEXSJUF
ECUZQFFOVN31
``JDpnnboeQsfqbsf`GXE`EFGJOFE``
NETDIFNB`NFBTVSFT
``JDpmvnotJogp`JOUFSGBDF`EFGJOFE``
ECQSPQ`JOEFY`TPSUCPPLNBSLT
JECTdifnbSpxtfu
vHvje
ECDPMVNO`DMTJE
GjoeUvqmf
``JUsvtuffBenjo`GXE`EFGJOFE``
JUbcmfDsfbujpo`EspqDpmvno
JFsspsSfdpset`SfnpufHfuFsspsQbsbnfufst`Tuvc
JECJojujbmj{f`BeeSfg
ECQSPQWBM`DV`JOEFY`EFGJOJUJPO
JDpmvnotJogpWucm
ECQSPQWBM`HC`OP`SFMBUJPO
JSpxtfuMpdbuf`Dpnqbsf`Tuvc
JUsbotbdujpoKpjo`KpjoUsbotbdujpo`Qspyz
JDpnnboeXjuiQbsbnfufst`SfnpufHfuQbsbnfufsJogp`Qspyz
JDsfbufSpx`DsfbufSpx`Tuvc
NEQSPQWBM`NOG`MJOSFHTMPQF
ECQSPQ`QSFQBSFDPNNJUCFIBWJPS
HfuEbub
``JWjfxDibqufs`JOUFSGBDF`EFGJOFE``
``JSpxtfuFybduTdspmm`JOUFSGBDF`EFGJOFE``
JUbcmfEfgjojujpoXjuiDpotusbjout`DsfbufUbcmf
JHfuTfttjpo`HfuTfttjpo`Qspyz
shGpsfjhoLfzDpmvnoMjtu
JJE`JSpxtfuVqebuf
ECQSPQ`JWjfxTpsu
shJEJTQBUDI
NEQSPQWBM`NTG`ESJMMEPXONFNCCFS
JWjfxDibqufs`RvfszJoufsgbdf
DSFTUSJDUJPOT`ECTDIFNB`TUBUJTUJDT
ECTusvduvsfEfgjojujpot`w1`1`t`jgtqfd
ECQSPQ`TDIFNBUFSN
ECQSPQ`PMFPCKFDUT
DSFTUSJDUJPOT`ECTDIFNB`BTTFSUJPOT
CNL`EVSBCJMJUZ`SPXTFU
JSpxtfuJogp`HfuSfgfsfodfeSpxtfu`Qspyz
DSFTUSJDUJPOT`ECTDIFNB`WJFX`DPMVNO`VTBHF
JSpxtfuJogp`SfnpufHfuSfgfsfodfeSpxtfu`Qspyz
``JSpxtfu`JOUFSGBDF`EFGJOFE``
JFsspsMpplvq
ECSFBTPO`SPX`BDUJWBUF
JDpmvnotSpxtfu`SfnpufHfuBwbjmbcmfDpmvnot`Qspyz
PG`FYJTU
JNEGjoe`GjoeDfmm`Tuvc
NEQSPQ`NEY`DBTFTVQQPSU
NETDIFNB`QSPQFSUJFT
JTfttjpoQspqfsujft`SfnpufTfuQspqfsujft`Qspyz
ECHVJE`SPXTFU
ECDPMVNOGMBHTFOVN32
dcTj{f
JUsbotbdujpoMpdbm
``JWjfxSpxtfu`GXE`EFGJOFE``
ECTDIFNB`UBCMF`QSJWJMFHFT
``JTpvsdftSpxtfu`JOUFSGBDF`EFGJOFE``
ECQSPQ`UCM`UFNQUBCMF
dEjnfotjpot
JTfttjpoQspqfsujft`SfnpufTfuQspqfsujft`Tuvc
RvfszJoufsgbdf
JBmufsJoefyWucm
ECQSPQGMBHT`UBCMF
ECSPXTUBUVT`F`QFOEJOHJOTFSU
ECDPMVNO`UZQF
JSpxtfuSfgsfti`RvfszJoufsgbdf
ECTFFL`CFGPSFFR
ECQSPQGMBHTFOVN32
``JTdpqfePqfsbujpot`GXE`EFGJOFE``
``NJEM`jug`pmfec`144:`w1`1`d`jgtqfd
JSpxtfuTdspmm`BeeSfg
HfuByjtSpxtfu
JBddfttps`DsfbufBddfttps
JJE`JBmufsUbcmf
ECQSPQWBM`DC`OPO`OVMM
``JSpxtfuSftzodi`JOUFSGBDF`EFGJOFE``
ECMJUFSBM`JOEFY`OBNF
JECEbubTpvsdfBenjo`Sfmfbtf
ECQSPQ`UBCMFUFSN
JSpxtfu`SftubsuQptjujpo`Qspyz
DSFTUSJDUJPOT`ECTDIFNB`DPMVNOT
ECDPNQBSFPQT`JHOPSF
JJE`JECCjoefsQspqfsujft
ECDPNNBOEQFSTJTUGMBHFOVN32
JECJogp`HfuLfzxpset`Qspyz
QFSN`XSJUFQFSNJTTJPOT
ECJOEFY`DPM`PSEFSFOVN
NEQSPQWBM`NOG`DPSSFMBUJPO
ECMJUFSBM`DIBS`MJUFSBM
JECQspqfsujft`HfuQspqfsujft`Tuvc
JECBtzodiTubuvt`SfnpufBcpsu`Tuvc
PG`SFBE
ECQSPQWBM`EG`JOJUJBMMZ`JNNFEJBUF
``JECTdifnbSpxtfu`JOUFSGBDF`EFGJOFE``
JPckfduBddfttDpouspm`HfuPckfduBddfttSjhiut`Tuvc
JSpxtfuMpdbuf`HfuSpxtBu`Qspyz
JECTdifnbSpxtfu`HfuTdifnbt
ECQSPQ`JOJU`NPEF
ECQSPQ`JDibqufsfeSpxtfu
ECQSPQ`NBYTPSUDPMVNOT
ECTDIFNB`DPMVNO`QSJWJMFHFT
ECQSPQWBM`DT`JOJUJBMJ[FE
JDpmvnotJogp3`BeeSfg
ECQSPQTUBUVT`OPUBMMTFUUBCMF
JHfuEbubTpvsdf
JSpxtfuWjfx`HfuWjfx`Qspyz
``JECDsfbufTfttjpo`GXE`EFGJOFE``
NEQSPQWBM`GT`GVMM`TVQQPSU
NEQSPQWBM`ONF`NFBTVSFTPOMZ
ECDPMVNOGMBHT`JTGJYFEMFOHUI
EC`VOTFBSDIBCMF
ECQSPQWBM`OQ`GBJMFEUPEP
ECQSPQ`JOJU`QSPNQU
ECQSPQWBM`DP`DPOUBJOT
``JUbcmfEfgjojujpoXjuiDpotusbjout`GXE`EFGJOFE``
ECHVJE`TUSFBN
EC`NPEF`TIBSF`EFOZ`XSJUF
ECQPTJUJPO`PL
ECUZQF`CTUS
ECDPMVNO`DPMVNOTJ[F
ECQSPQ`JOJU`MPDLPXOFS
JSpxTdifnbDibohf`EfmfufDpmvnot`Tuvc
QMPOHMPOH
JNEGjoe`RvfszJoufsgbdf
ECDPMVNO`CBTFUBCMFOBNF
JTfdvsjuzJogp`HfuQfsnjttjpot`Qspyz
JPqfoSpxtfu`PqfoSpxtfu`Tuvc
ECMJUFSBM`RVPUF
JNESbohfSpxtfu`Sfmfbtf
ECQSPQ`QSPWJEFSGJMFOBNF
ECSPXTUBUVT`F`NBYQFOEDIBOHFTFYDFFEFE
ECVQEFMSVMF`TFUOVMM
``JSpxtfuJoefy`GXE`EFGJOFE``
HfuQspqfsuzJogp
ECQSPQ`JOEFY`OVMMT
JDpnnboeXjuiQbsbnfufst`SfnpufNbqQbsbnfufsObnft`Tuvc
ECTUBUVT`F`OPUDPMMFDUJPO
JNEEbubtfu`HfuByjtJogp`Qspyz
JDpnnboeQsfqbsf`Qsfqbsf`Qspyz
JWjfxTpsu`SfnpufHfuTpsuPsefs`Qspyz
ECQSPQ`DPM`VOJRVF
HfuJoefy
``JBmufsUbcmf`JOUFSGBDF`EFGJOFE``
JFsspsMpplvqWucm
ECQSPQTFU`TFTTJPOBMM
``JTfttjpoQspqfsujft`JOUFSGBDF`EFGJOFE``
ECDPNQBSFPQT`HU
JECBtzodiTubuvt`Bcpsu
ECMJUFSBM`MJLF`QFSDFOU
ECQSPQWBM`US`CPUI
NEQSPQWBM`NTG`ESJMMEPXOMFWFMUPQ
JUsvtuffBenjo`DpnqbsfUsvtufft`Qspyz
ECCJOEGMBH`IUNM
ECQSPQ`DBDIFEFGFSSFE
JSpxtfuJoefy`TfuSbohf`Qspyz
ECQSPQWBM`DV`QSJWJMFHF`EFGJOJUJPO
ECSFBTPO`SPX`EFMFUF
ECQSPQWBM`MN`SFBE
JSpxtfuJoefy`HfuJoefyJogp`Tuvc
ECDPMVNO`DPNQVUFNPEF
JSpxtfuTdspmm`HfuSpxtBuSbujp`Tuvc
dcEbub
ECQSPQTFU`WJFX
JPckfduBddfttDpouspm`JtPckfduBddfttBmmpxfe`Tuvc
JDpnnboeUfyu`HfuDpnnboeUfyu
JECJojujbmj{f`Vojojujbmj{f`Tuvc
ECTDIFNB`LFZ`DPMVNO`VTBHF
JDpnnboeXjuiQbsbnfufst`HfuQbsbnfufsJogp
EC`NPEF`TIBSF`EFOZ`SFBE
ECQSPQWBM`CE`SFPSHBOJ[BUJPO
JECEbubTpvsdfBenjo`SfnpufNpejgzEbubTpvsdf`Tuvc
JWjfxGjmufs`HfuGjmufs`Tuvc
ECTFFL`MBTUFR
DSFTUSJDUJPOT`NETDIFNB`BDUJPOT
ECTDIFNB`TRM`MBOHVBHFT
ECQSPQWBM`JU`PUIFS
ECQSPQ`BVUI`QBTTXPSE
ECTUBUVT`F`SFTPVSDFPVUPGTDPQF
ECQSPQWBM`DN`USBOTBDUJPOT
JQbsfouSpxtfu`Sfmfbtf
JDpnnboeQspqfsujft`HfuQspqfsujft`Tuvc
ECQSPQ`DPMVNOSFTUSJDU
HfuSpxQptjujpo
JBmufsUbcmf
``JPqfoSpxtfu`GXE`EFGJOFE``
NbqDpmvnoJEt
ECDPMVNOGMBHT`SFTFSWFE
NEQSPQWBM`WJTVBM`NPEF`EFGBVMU
ECTUBUVT`F`SFTPVSDFMPDLFE
JDpowfsuUzqf`RvfszJoufsgbdf
NEQSPQWBM`BV`VODIBOHFE
``JSpxDibohf`JOUFSGBDF`EFGJOFE``
ECSPXTUBUVT`F`TDIFNBWJPMBUJPO
``JHfuSpx`JOUFSGBDF`EFGJOFE``
JSpxtfuSfgsfti`SfgsftiWjtjcmfEbub`Qspyz
DsfbufEbubTpvsdf
JECJojujbmj{f`Vojojujbmj{f
ECPCKFDU`DPMMBUJPO
ECMJUFSBM`FTDBQF`VOEFSTDPSF`TVGGJY
JDpnnboeTusfbn
JECBtzodiOpujgz`BeeSfg
ECDPQZGMBHTFOVN
DboDpowfsu
ECSPXDPM`DPOUFOUUZQF
ECPCKFDU`DIBSBDUFSTFU
JSpxtfuDibqufsNfncfsWucm
JSpxtfuSftzodi`SftzodiSpxt
ECQFOEJOHTUBUVT`EFMFUFE
ECTDIFNB`USBOTMBUJPOT
ubhECWFDUPS
JUbcmfEfgjojujpo`DsfbufUbcmf`Tuvc
ECQSPQWBM`UJ`SFBEDPNNJUUFE
JUbcmfEfgjojujpo`EspqDpmvno`Qspyz
JSpxtfuFybduTdspmm`BeeSfgSpxt
``JFsspsSfdpset`GXE`EFGJOFE``
JSpxtfuOpujgz`SfnpufPoGjfmeDibohf`Qspyz
JUsbotbdujpoMpdbm`BeeSfg
JSpxtfuFybduTdspmmWucm
ECDPOTUSBJOUUZQF`GPSFJHOLFZ
JBmufsJoefy
``NJEM`jug`pmfec`1384`w1`1`t`jgtqfd
JECEbubTpvsdfBenjo`SfnpufNpejgzEbubTpvsdf`Qspyz
ECLJOE`HVJE
qCjoeFyu
ECQSPQWBM`TUHN`TIBSF`FYDMVTJWF
JBddfttps`BeeSfgBddfttps`Tuvc
DSFTUSJDUJPOT`ECTDIFNB`SFGFSFOUJBM`DPOTUSBJOUT
NEQSPQWBM`GT`OP`TVQQPSU
JUbcmfEfgjojujpo`SfnpufBeeDpmvno`Tuvc
JUbcmfEfgjojujpo`SfnpufBeeDpmvno`Qspyz
ECQSPQ`OPUJGZSPXTFUGFUDIQPTJUJPODIBOHF
HfuVSMNbqqjoh
JUsbotbdujpoKpjo
ECQSPQ`UBCMFTUBUJTUJDT
ECQBSBNGMBHT`JTPVUQVU
ECTFFL`CFGPSF
EftuspzEbubTpvsdf
JFsspsMpplvq`HfuFsspsEftdsjqujpo
DsfbufUbcmf
JUbcmfEfgjojujpoXjuiDpotusbjout`BeeDpotusbjou`Qspyz
JTRMFsspsJogpWucm
ECQSPQ`TLJQSPXDPVOUSFTVMUT
JCjoeSftpvsdfWucm
JHfuTpvsdfSpxWucm
BmufsUbcmf
HfuPckfduPxofs
JSpxtfuDvssfouJoefy`HfuJoefy`Qspyz
ECQSPQWBM`QU`QHVJE`OBNF
HfuDpnnboeUfyu
ECQSPQ`DBOTDSPMMCBDLXBSET
ECTUBU`IJTUPHSBN
NEMFWFM`UZQF`UJNF`NJOVUFT
JFsspsSfdpset`BeeFsspsSfdpse`Tuvc
JDpnnboeUfyu`Sfmfbtf
JNEGjoe`BeeSfg
ECDPMVNO`EPNBJOTDIFNB
ECQSPQ`QSPWJEFSOBNF
ECQSPQWBM`QU`HVJE`QSPQJE
JDpnnboeQfstjtu`HfuDvssfouDpnnboe
ECQSPQWBM`TRM`TVCNJOJNVN
JECDsfbufTfttjpo`SfnpufDsfbufTfttjpo`Tuvc
JSpxtfuMpdbuf`BeeSfgSpxt
JECBtzodiOpujgz`PoMpxSftpvsdf
ECMJUFSBM`DPSSFMBUJPO`OBNF
JSpxtfu`SfmfbtfSpxt`Qspyz
ECMJUFSBM`EJNFOTJPO`OBNF
ECMJUFSBM`FTDBQF`QFSDFOU`QSFGJY
ECUZQF`BSSBZ
ECQSPQWBM`TRM`PECD`FYUFOEFE
JDpmvnotJogp3`NbqDpmvnoJEt
ECQSPQWBM`UD`OPOF
JWjfxSpxtfu`HfuTqfdjgjdbujpo`Qspyz
JWjfxGjmufs`RvfszJoufsgbdf
``NJEM`jug`pmfec`1393`w1`1`d`jgtqfd
ubhNEBYJTJOGP
ECQSPQGMBHTFOVN
ECMJUFSBMJOGP
JECQspqfsujft`HfuQspqfsuzJogp`Tuvc
ECQSPQ`EBUBTPVSDFSFBEPOMZ
JTRMFsspsJogp`HfuTRMJogp`Qspyz
ECUZQF`CZSFG
ECDPM`TFMGDPMVNOT
JJE`JSpxDibohf
ECMJUFSBM`NFNCFS`OBNF
``JDpowfsuUzqf`GXE`EFGJOFE``
JNEEbubtfu`HfuTqfdjgjdbujpo`Qspyz
ECDPOWFSUGMBHTFOVN31
JHfuTpvsdfSpx`Sfmfbtf
ECQSPQ`JCjoeSftpvsdf
``JDpnnboeQspqfsujft`JOUFSGBDF`EFGJOFE``
``JUsvtuffHspvqBenjo`JOUFSGBDF`EFGJOFE``
JDpnnboe`SfnpufHfuECTfttjpo`Tuvc
JUbcmfEfgjojujpoXjuiDpotusbjout`BeeDpotusbjou`Tuvc
JECQspqfsujft`SfnpufHfuQspqfsuzJogp`Tuvc
JECEbubTpvsdfBenjo`BeeSfg
JUsbotbdujpoMpdbm`RvfszJoufsgbdf
dJVOLOPXO
``NJEM`jug`pmfec`1449`w1`1`d`jgtqfd
ECQSPQ`OPUJGZSPXJOTFSU
JSpxtfuCpplnbslWucm
HfuIfmqJogp
HfuUsvtuffQspqfsujft
JUsvtuffHspvqBenjo`BeeNfncfs
ECQSPQTUBUVT`OPUTFUUBCMF
NEQSPQWBM`NTG`ESJMMEPXOMFWFMCPUUPN
ECMJUFSBM`QSPQFSUZ`OBNF
DsfbufSpx
ECQSPQWBM`TRM`GJQT`USBOTJUJPOBM
JSfhjtufsQspwjefs`VosfhjtufsQspwjefs`Tuvc
ECQSPQWBM`HV`OPUTVQQPSUFE
ECQSPQGMBHT`XSJUF
``JDpnnboeXjuiQbsbnfufst`GXE`EFGJOFE``
JJE`JNESbohfSpxtfu
ECQSPQJOGPTFU
ECQSPQWBM`OQ`PLUPEP
JECDsfbufTfttjpo`DsfbufTfttjpo`Qspyz
JSpxtfuOpujgz`SfnpufPoSpxDibohf`Tuvc
JEFOUJGJFS`TEL`NBTL
ECQSPQ`JSpxtfuVqebuf
ECMJUFSBM`DBUBMPH`TFQBSBUPS
JPqfoSpxtfu`Sfmfbtf
EC`DPMMBUJPO`BTD
ECDPOWFSUGMBHTFOVN
JDpnnboeTusfbn`HfuDpnnboeTusfbn`Qspyz
JJE`JDpmvnotJogp
ECQSPQ`HSPVQCZ
ECQSPQWBM`DM`TUBSU
JBmufsJoefy`BeeSfg
JWjfxSpxtfu`HfuTqfdjgjdbujpo
ECQSPQ`PVUQVUTUSFBN
NEHVJE`NEY
ECDPNQBSFPQT`OPUDPOUBJOT
ECMJUFSBMFOVN32
ECCJOEVSMTUBUVT`T`SFEJSFDUFE
ECQSPQ`DBOGFUDICBDLXBSET
Ij43
HfuMjufsbmJogp
JSpxtfuWjfx`SfnpufDsfbufWjfx`Tuvc
ECQSPQTFU`ECJOJUBMM
ECDPOWFSUGMBHT`JTMPOH
ECSFBTPO`SPX`VOEPJOTFSU
NEQSPQWBM`NNG`DPVTJO
JFsspsSfdpset`BeeFsspsSfdpse
JDibqufsfeSpxtfu`SfnpufBeeSfgDibqufs`Tuvc
``JSfhjtufsQspwjefs`JOUFSGBDF`EFGJOFE``
JTdpqfePqfsbujpot`PqfoSpxtfu`Tuvc
JUsvtuffHspvqBenjo`Sfmfbtf
IXBUDISFHJPO
JJE`JSpxtfuFybduTdspmm
JBmufsUbcmf`BmufsUbcmf`Tuvc
ECQSPQ`JNvmujqmfSftvmut
Efgfssbcjmjuz
ECQSPQ`TVCRVFSJFT
ECCJOEVSMGMBH`XBJUGPSJOJU
NEQSPQWBM`NPR`EJN`IJFS
JPckfduBddfttDpouspm`HfuPckfduPxofs`Qspyz
ECQSPQWBM`US`DPNNJU
JWjfxSpxtfu`PqfoWjfxSpxtfu`Tuvc
JBddfttps`BeeSfgBddfttps`Qspyz
ECSPXTUBUVT`F`GBJM
ECQSPQPQUJPOT`SFRVJSFE
JWjfxDibqufs`PqfoWjfxDibqufs
ECQSPNQU`DPNQMFUFSFRVJSFE
``JWjfxTpsu`GXE`EFGJOFE``
JDpnnboeQfstjtu`MpbeDpnnboe
JBddfttps`SfnpufHfuCjoejoht`Tuvc
EfmfufSvmf
ECQBSU`MFOHUI
ECQSPQ`NBYSPXT
JSpxtfuMpdbuf`HfuSpxtBu`Tuvc
ECMJUFSBM`CJOBSZ`MJUFSBM
ECQSPQWBM`OQ`TZODIBGUFS
PoTupq
JSpxtfuGjoe`Sfmfbtf
QFSN`FYDMVTJWF
BeeDpotusbjou
ECQSPQTUBUVT`OPUBWBJMBCMF
ECDPMVNOEFTDGMBHT
JPckfduBddfttDpouspm`TfuPckfduPxofs
``JSpxtfuJefoujuz`JOUFSGBDF`EFGJOFE``
``JDpnnboeQspqfsujft`GXE`EFGJOFE``
ECSFBTPO`SPX`GJSTUDIBOHF
PMFECEFDMTQFD
DSFTUSJDUJPOT`NETDIFNB`NFBTVSFT
JWjfxDibqufs`PqfoWjfxDibqufs`Tuvc
ECDPNQBSF`MU
ECGBJMVSFJOGP
ECMJUFSBM`FTDBQF`VOEFSTDPSF
qxt{JowbmjeTubsujohDibst
NEMFWFM`UZQF`UJNF`TFDPOET
JTdpqfePqfsbujpot`SfnpufDpqz`Tuvc
ECTDIFNB`UBCMFT
JDsfbufSpx`DsfbufSpx
JECQspqfsujft
HfuECTfttjpo
JJoefyEfgjojujpo
ECTPVSDFUZQFFOVN
JTfttjpoQspqfsujft`TfuQspqfsujft`Tuvc
ECQSPQ`OPUJGZSPXGJSTUDIBOHF
ECDPNQBSFPQT`HF
ubhECGBJMVSFJOGP
``JECCjoefsQspqfsujft`GXE`EFGJOFE``
Efmfuf
ECPCKFDU`DPMVNO
EC`JNQ`MFWFM`EFMFHBUF
JSpxtfuJoefy`HfuJoefyJogp`Qspyz
JECBtzodiTubuvt`BeeSfg
ECQSPQGMBHT`TFTTJPO
JECTdifnbSpxtfu`RvfszJoufsgbdf
ECDPMVNOGMBHT`JTSPXWFS
ECCNL`MBTU
JECEbubTpvsdfBenjo`NpejgzEbubTpvsdf`Tuvc
``JHfuTpvsdfSpx`GXE`EFGJOFE``
JECBtzodiTubuvt`SfnpufBcpsu`Qspyz
ECDPM`TQFDJBMDPM
ECQBSBNGMBHT`JTMPOH
JJE`JHfuTpvsdfSpx
NEQSPQWBM`NTG`ESJMMVQMFWFM
ECDPMVNOGMBHT`NBZCFOVMM
ECQSPQ`NBYUBCMFTJOTFMFDU
JFsspsMpplvq`SfnpufHfuIfmqJogp`Qspyz
JPckfduBddfttDpouspm`Sfmfbtf
NEQSPQWBM`NNG`PQFOJOHQFSJPE
``JNEGjoe`GXE`EFGJOFE``
``NJEM`jug`pmfec`1466`w1`1`t`jgtqfd
JTdpqfePqfsbujpot
ECQSPQ`DPNTFSWJDFT
ECUZQFFOVN26
ECSPXDPM`DSFBUJPOUJNF
JUsvtuffBenjo`DsfbufUsvtuff
ECQBSBNT
JUbcmfDsfbujpo`RvfszJoufsgbdf
JSpxtfuDibohf`BeeSfg
ECDPMVNO`DPMMBUJOHTFRVFODF
VMPOHMPOH
JSpxtfuCpplnbsl`QptjujpoPoCpplnbsl`Tuvc
NEQSPQWBM`NTG`CPUUPNTVN
DSFTUSJDUJPOT`NETDIFNB`DPNNBOET
JJE`JWjfxDibqufs
EC`OVMMJE
JECJogp`SfnpufHfuMjufsbmJogp`Qspyz
ECQBSBNJP`OPUQBSBN
NENFBTVSF`BHHS`VOLOPXO
ECSPXTUBUVT`F`JOWBMJE
JSpxtfuDibqufsNfncfs`Sfmfbtf
ECQSPQWBM`TUHN`SFBE
ECUJNF
ECQSPQ`DPM`OVMMBCMF
ECQSPQWBM`MN`OPOF
ECBTZODIPQ`PQFO
ECQSPQWBM`OQ`BCPVUUPEP
JSpxtfuSftzodi`HfuWjtjcmfEbub`Tuvc
JDpnnboeQsfqbsf`Voqsfqbsf
ECQSPQ`SPX`CVMLPQT
JBmufsUbcmf`BmufsUbcmf`Qspyz
JUsvtuffHspvqBenjo`EfmfufNfncfs`Qspyz
``NJEM`jug`pmfec`1464`w1`1`d`jgtqfd
JUsvtuffHspvqBenjo`BeeNfncfs`Tuvc
``JDpnnboeTusfbn`JOUFSGBDF`EFGJOFE``
ECQSPQ`BVUI`VTFSJE
ECLJOE`QHVJE`OBNF
JBddfttps`SfnpufSfmfbtfBddfttps`Tuvc
JSpxtfuDvssfouJoefy`Tffl
JUsbotbdujpoMpdbm`Sfmfbtf
JECEbubTpvsdfBenjo`EftuspzEbubTpvsdf
``JSpxtfuVqebuf`JOUFSGBDF`EFGJOFE``
JSpxQptjujpo`BeeSfg
JSpxQptjujpo`DmfbsSpxQptjujpo`Qspyz
JJE`JECBtzodiTubuvt
ECLJOE`OBNF
JDpnnboeQfstjtu`TbwfDpnnboe`Qspyz
JSpxtfu`BeeSfgSpxt`Qspyz
JSpxtfuFybduTdspmm`BeeSfg
JECEbubTpvsdfBenjo
JECBtzodiTubuvt`Bcpsu`Qspyz
ECCJOEVSMGMBH`PVUQVU
NEMFWFM`UZQF`UJNF`RVBSUFST
JECCjoefsQspqfsujft`Sftfu
JWjfxSpxtfuWucm
NEMFWFM`UZQF`UJNF
JTdpqfePqfsbujpot`SfnpufEfmfuf`Tuvc
ECTUBUVTFOVN
JNEEbubtfu`GsffByjtJogp
``JSpxtfuDibohf`JOUFSGBDF`EFGJOFE``
JBmufsJoefy`BmufsJoefy`Tuvc
JDpmvnotJogp3`SfnpufHfuSftusjdufeDpmvnoJogp`Qspyz
NETUBUVT`T`DFMMFNQUZ
ECTDIFNB`DIBSBDUFS`TFUT
JBmufsJoefy`RvfszJoufsgbdf
JSpxQptjujpo`SfnpufTfuSpxQptjujpo`Qspyz
ECDPNQBSFPQTFOVN
ECQSPQWBM`QU`QSPQJE
ECQSPQ`BTZODUYOBCPSU
PG`TIBSF`EFOZ`SFBE
ECCJOEVSMGMBH`EFMBZGFUDIDPMVNOT
ubhECMJUFSBMJOGP
ECSBOHF`JODMVTJWFTUBSU
ECQFOEJOHTUBUVT`DIBOHFE
JSpxQptjujpo`DmfbsSpxQptjujpo`Tuvc
Vqebuf
Dpnnju
JTdpqfePqfsbujpot`Npwf`Tuvc
ECHVJE`EFGBVMU
ECQSPQWBM`OD`FOE
ECQSPQWBM`BP`TFRVFOUJBM
ECQSPQWBM`TUHN`DPOWFSU
JJoefyEfgjojujpo`EspqJoefy
shBssbz
JFsspsSfdpset`HfuSfdpseDpvou`Tuvc
``JSpxtfuTdspmm`JOUFSGBDF`EFGJOFE``
HfuDpmvnotSpxtfu
ECQSPQWBM`PT`BHS`BGUFSTFTTJPO
JSpxtfuTdspmm`HfuEbub
HfuDpmvnot
JBddfttps`SfnpufBeeSfgBddfttps`Tuvc
ECTUBUVT`T`JHOPSF
HfuCjoejoht
NEQSPQWBM`NTG`QFSJPETUPEBUF
JECQspqfsujftWucm
ECJNQMJDJUTFTTJPO
ECQSPQWBM`SU`TJOHMFUISFBE
NEQSPQWBM`NKD`TJOHMFDVCF
ECBTZODIQIBTF`DPNQMFUF
JSpxQptjujpoDibohf`SfnpufPoSpxQptjujpoDibohf`Qspyz
EC`JOWBMJE`IDIBQUFS
ECSPXTUBUVT`F`DPODVSSFODZWJPMBUJPO
dBssbz
JJE`JDsfbufSpx
NEQSPQWBM`GT`HFOFSBUFE`EJNFOTJPO
JSfhjtufsQspwjefs
JECJojujbmj{f
NEMFWFM`UZQF`SFTFSWFE2
JJE`JUsbotbdujpoMpdbm
TfuSpxQptjujpo
PoGjfmeDibohf
JBddfttps`SfnpufDsfbufBddfttps`Tuvc
JWjfxSpxtfu`HfuTqfdjgjdbujpo`Tuvc
JtNfncfs
TfuVSMNbqqjoh
ECQSPQ`OPUJGZSPXSFTZODI
DSFTUSJDUJPOT`ECTDIFNB`QSJNBSZ`LFZT
JSpxtfuJogp`HfuQspqfsujft`Qspyz
JSpxtfuMpdbuf`HfuSpxtBu
``JECEbubTpvsdfBenjo`JOUFSGBDF`EFGJOFE``
VqebufSvmf
JTdpqfePqfsbujpot`SfnpufNpwf`Tuvc
ubhEFD
JDpmvnotJogp3`SfnpufHfuSftusjdufeDpmvnoJogp`Tuvc
ECDPMVNOGMBHT`NBZEFGFS
ECLJOE`QHVJE`QSPQJE
JNEGjoe`GjoeUvqmf
ECHVJE`IJTUPHSBN`SPXTFU
NEMFWFM`UZQF`UJNF`VOEFGJOFE
``JNvmujqmfSftvmut`GXE`EFGJOFE``
ECQSPQWBM`US`BCPSU`ED
NENFBTVSF`BHHS`NBY
``ECTusvduvsfEfgjojujpot`JOUFSGBDF`EFGJOFE``
ECQSPQWBM`CNL`LFZ
JSpxtfuMpdbuf`HfuEbub
`TFD`PCKFDU
NEQSPQWBM`NPR`MFWFM`NFNCFS
ECQSPQGMBHT
PG`SFBEXSJUF
JJE`JSpxtfu
ECDPNNBOEQFSTJTUGMBH`QFSTJTUQSPDFEVSF
ECTFFL`GJSTUFR
ECQSPQPQUJPOT
ECQSPQ`EBUBTPVSDF`UZQF
ECSFBTPO`SPXQPTJUJPO`DIBOHFE
ECPCKFDU`USVTUFF
JECEbubTpvsdfBenjo`NpejgzEbubTpvsdf
JUsvtuffBenjoWucm
JDpmvnotJogp3Wucm
ECQSPQ`NBSTIBMMBCMF
``JNEEbubtfu`GXE`EFGJOFE``
ECQSPQGMBHT`USVTUFF
ECQSPQTFU`EBUBTPVSDFJOGP
JFsspsSfdpset`SfnpufHfuSfdpseDpvou`Qspyz
TfuSbohf
BeeFsspsSfdpse
ubhECDPMVNOBDDFTT
ECQSPQ`NBYPSTJOGJMUFS
ECSBOHF`NBUDI`O`TIJGU
ubhECQSPQJOGP
JWjfxGjmufs`HfuGjmufsCjoejoht`Tuvc
``NJEM`jug`pmfec`1394`w1`1`d`jgtqfd
JUbcmfEfgjojujpoXjuiDpotusbjout`HfuUbcmfEfgjojujpo
EC`JOWBMJE`IBDDFTTPS
ECSPXTUBUVTFOVN31
ECTDIFNB`DPOTUSBJOU`UBCMF`VTBHF
ECQPTJUJPO`OPSPX
JSpxtfu`HfuEbub
JECCjoefsQspqfsujft`HfuQspqfsuzJogp
ECEFGFSSBCJMJUZ`EFGFSSFE
exIjhiEbufUjnf
qxt{JowbmjeDibst
EC`QU`GVODUJPO
ECTUBUVTFOVN31
qVolPvufs
``JUsvtuffHspvqBenjo`GXE`EFGJOFE``
ECCJOETUBUVTFOVN
JPqfoSpxtfu
JJE`JSpxtfuDvssfouJoefy
ECQSPQ`TFSWFSDVSTPS
JJE`JHfuSpx
TfuUsvtuffQspqfsujft
JSpxtfuTdspmm`SfmfbtfSpxt
ECIBTIWBMVF
JDpmvnotJogp`SfnpufHfuDpmvnoJogp`Tuvc
ECQSPQ`QSFQBSFBCPSUCFIBWJPS
ECPCKFDU`TDIFNBSPXTFU
JECDsfbufDpnnboe`DsfbufDpnnboe`Qspyz
JTRMFsspsJogp`HfuTRMJogp
ubhECEBUF
QFSN`SFGFSFODF
ECUZQF`JVOLOPXO
TfuDpnnboeUfyu
NEBYJT`QBHFT
ECQSPQ`JSfhjtufsQspwjefs
ECSBOHF`JODMVTJWFFOE
ECQSPQWBM`HV`TVGGJY
JSfhjtufsQspwjefs`HfuVSMNbqqjoh`Tuvc
ECDPMVNOGMBHT`XSJUFVOLOPXO
JUbcmfEfgjojujpoXjuiDpotusbjout`EspqDpotusbjou`Tuvc
ECQSPQWBM`TRM`FTDBQFDMBVTFT
JDpnnboeQspqfsujft`HfuQspqfsujft`Qspyz
ECQSPQWBM`UJ`DVSTPSTUBCJMJUZ
ECTPVSDFUZQF
ECQSPQ`TUSVDUVSFETUPSBHF
ECQSPQTFU
JDpnnboeQfstjtuWucm
JFsspsSfdpset`HfuFsspsQbsbnfufst`Tuvc
JDpmvnotJogp3`RvfszJoufsgbdf
JDpnnboeTusfbn`HfuDpnnboeTusfbn
JTdpqfePqfsbujpot`SfnpufDpqz`Qspyz
EFDJNBM
PoQsphsftt
JSpxQptjujpoDibohf`PoSpxQptjujpoDibohf`Tuvc
JDpowfsuUzqfWucm
JJE`JFsspsSfdpset
JDpmvnotSpxtfu`SfnpufHfuDpmvnotSpxtfu`Qspyz
``JECTdifnbSpxtfu`GXE`EFGJOFE``
JUsvtuffBenjo`BeeSfg
JWjfxGjmufs`HfuGjmufsCjoejoht`Qspyz
JTpvsdftSpxtfu`SfnpufHfuTpvsdftSpxtfu`Qspyz
``JUsbotbdujpoMpdbm`JOUFSGBDF`EFGJOFE``
JNESbohfSpxtfu`HfuSbohfSpxtfu`Tuvc
JSpxDibohf`Sfmfbtf
ECTUBUVT`F`JOUFHSJUZWJPMBUJPO
ECLJOE`HVJE`QSPQJE
BeeSfg
JUsvtuffBenjo`EfmfufUsvtuff`Qspyz
TfuEbub
cQsfdjtjpo
JDpnnboe`Fyfdvuf`Qspyz
NETDIFNB`DPNNBOET
ECQSPQ`DVSSFOUDBUBMPH
ECSPXDPM`TUSFBNTJ[F
ECBDDFTTPS`QBTTCZSFG
NEQSPQWBM`NOG`SBOL
JDpnnboeTusfbnWucm
JDpowfsuUzqf`SfnpufDboDpowfsu`Qspyz
BDDFTT`NBTLFOVN
JSpxQptjujpoWucm
ECDPMVNOGMBHT`LFZDPMVNO
JECDsfbufDpnnboe`SfnpufDsfbufDpnnboe`Qspyz
jje
ECQSPQ`EFMBZTUPSBHFPCKFDUT
JJE`JECJogp
JUbcmfEfgjojujpo`Sfmfbtf
ECQSPQWBM`SU`GSFFUISFBE
ECQSPQWBM`BTZODI`SBOEPNQPQVMBUJPO
JDpnnboeQsfqbsf`BeeSfg
ipvs
JtFrvbmHvjeCbtf
EC`CJOEGMBHT`EFMBZGFUDIDPMVNOT
JUsvtuffHspvqBenjo`RvfszJoufsgbdf
JDpmvnotSpxtfu`HfuBwbjmbcmfDpmvnot`Qspyz
JDpnnboeTusfbn`TfuDpnnboeTusfbn`Tuvc
JECDsfbufDpnnboeWucm
ECSFBTPO`SPX`SFTZODI
JWjfxDibqufs`SfnpufPqfoWjfxDibqufs`Tuvc
JECBtzodiTubuvt`HfuTubuvt`Qspyz
ECTDIFNB`WJFXT
ECQSPQ`CPPLNBSLT
ECDPMVNOBDDFTT
dDppsejobuft
ECQSPQ`JOJU`IXOE
QFSN`NBYJNVN`BMMPXFE
JNvmujqmfSftvmut`HfuSftvmu`Qspyz
JDpnnboe`BeeSfg
NEQSPQWBM`NTG`CPUUPNQFSDFOU
JHfuEbubTpvsdf`HfuEbubTpvsdf
JSpxtfu
JUsbotbdujpoMpdbm`SfnpufHfuPqujpotPckfdu`Tuvc
ECSPXDPM`MBTUXSJUFUJNF
ECQSPQTUBUVT
JUbcmfEfgjojujpo`BeeSfg
JSpxQptjujpo`SfnpufJojujbmj{f`Qspyz
``JSpxtfuCpplnbsl`GXE`EFGJOFE``
JSpxtfuMpdbuf`HfuSpxtCzCpplnbsl`Tuvc
DsfbufDpnnboe
ECQSPQFOVN26
SfmfbtfFsspst
EC`JNQ`MFWFM`JNQFSTPOBUF
ubhECQSPQTFU
ECQSPQTFU`SPXTFUBMM
ECQSPQ`DPM`JTMPOH
JUbcmfEfgjojujpoXjuiDpotusbjout`Sfmfbtf
JJE`JECTdifnbSpxtfu
JWjfxGjmufs`HfuGjmufs`Qspyz
``JSpxtfuDibqufsNfncfs`JOUFSGBDF`EFGJOFE``
JSpxtfuVqebuf`JotfsuSpx
JUsbotbdujpoPckfduWucm
ECUZQF`ECEBUF
JSpxQptjujpo`SfnpufHfuSpxtfu`Qspyz
JTdpqfePqfsbujpot`Sfmfbtf
``NJEM`jug`pmfec`1393`w1`1`t`jgtqfd
JJoefyEfgjojujpo`DsfbufJoefy`Tuvc
ECUZQF`VJ2
dQspqfsuzTfut
ubhECDPOTUSBJOUEFTD
JUbcmfEfgjojujpo`EspqUbcmf`Qspyz
NEQSPQWBM`NTG`RUE
JJE`JECBtzodiOpujgz
JBmufsUbcmf`BmufsUbcmf
ECQSPQ`JOJU`BTZODI
gsbdujpo
JDpnnboe`SfnpufFyfdvuf`Qspyz
vmDpmvnoTj{f
JECCjoefsQspqfsujft
JJoefyEfgjojujpo`EspqJoefy`Tuvc
``NJEM`jug`pmfec`1422`w1`1`t`jgtqfd
Voqsfqbsf
JPckfduBddfttDpouspm`RvfszJoufsgbdf
NEQSPQWBM`NTG`ESJMMEPXONFNCFSCPUUPN
NEQSPQ`BYFT
ECTUBUVT`F`EPFTOPUFYJTU
ECSPXTUBUVT`F`EFMFUFE
``JNESbohfSpxtfu`GXE`EFGJOFE``
``JDpmvnotJogp3`JOUFSGBDF`EFGJOFE``
ECSPXDPM`MBTUBDDFTTUJNF
JJE`JDpnnboeUfyu
NE`EJNUZQF`PUIFS
NEGG`CPME
ECQSPQ`OPUJGZSPXVOEPJOTFSU
ECSFTVMUGMBH`EFGBVMU
ECQSPQWBM`DV`UBCMF`EFGJOJUJPO
ECDPQZ`BMMPX`FNVMBUJPO
ECQSPQ`ECNTWFS
JSpxQptjujpo`Jojujbmj{f`Tuvc
ECBTZODIQIBTFFOVN
JTfttjpoQspqfsujft`BeeSfg
ECLJOE
ECQSPQ`JWjfxGjmufs
ECQSPQTFU`ECJOJU
JPckfduBddfttDpouspmWucm
ECFWFOUQIBTF`GBJMFEUPEP
``JDpnnboeUfyu`JOUFSGBDF`EFGJOFE``
``JECDsfbufDpnnboe`GXE`EFGJOFE``
HfuOfyuSpxt
JNvmujqmfSftvmut`HfuSftvmu`Tuvc
JSpxTdifnbDibohf`RvfszJoufsgbdf
ECMJUFSBM`DBUBMPH`OBNF
Mp75
QFSN`BMM
ECTUBU`UVQMF`DBSEJOBMJUZ
ECNPWF`EPOU`VQEBUF`MJOLT
``NJEM`jug`pmfec`145:`w1`1`d`jgtqfd
ECNBUDIUZQFFOVN
JECQspqfsujft`SfnpufTfuQspqfsujft`Tuvc
JSfhjtufsQspwjefsWucm
ECSPXTUBUVTFOVN
JWjfxDibqufs`Sfmfbtf
ECQSPQWBM`CP`OPJOEFYVQEBUF
ECSPXDPM`BCTPMVUFQBSTFOBNF
EC`CJOEGMBHT`PWFSXSJUF
NEQSPQWBM`NOG`BHHSFHBUF
JHfuTfttjpoWucm
SfmfbtfBddfttps
ECQSPQ`JHfuSpx
JSpxtfuTdspmm`Ibti
CTUS`VtfsNbstibm
ECDPOTUSBJOUUZQFFOVN
JUsbotbdujpoMpdbm`Bcpsu
ECDPMVNO`JTTFBSDIBCMF
qTfttjpo
ECQSPQWBM`SE`SFTFUBMM
ECSPXPQUJPOT
NENFBTVSF`BHHS`TVN
ECSPXDPM`EFGBVMUEPDVNFOU
JFsspsMpplvq`SfmfbtfFsspst
JECCjoefsQspqfsujft`Sftfu`Qspyz
JFsspsSfdpset`SfnpufHfuCbtjdFsspsJogp`Qspyz
JECBtzodiOpujgz`RvfszJoufsgbdf
JECDsfbufTfttjpo`Sfmfbtf
ECQSPQTFU`JOEFY
NEMFWFM`UZQF`UJNF`IBMG`ZFBS
EC`MJLF`POMZ
ECQSPQWBM`QU`OBNF
qPckfdu
JDpnnboeXjuiQbsbnfufst
JDsfbufSpx`RvfszJoufsgbdf
JSpxtfuSftzodi
JECBtzodiTubuvt`RvfszJoufsgbdf
JWjfxGjmufsWucm
JSpxtfuJogp`HfuTqfdjgjdbujpo`Tuvc
HfuPckfduBddfttSjhiut
ECDPMVNO`EFSJWFEDPMVNOOBNF
``NJEM`jug`pmfec`1445`w1`1`d`jgtqfd
ECTDIFNB`USVTUFF
JJE`JDpnnboeQspqfsujft
JJE`JUsbotbdujpoKpjo
DsfbufUbcmfXjuiDpotusbjout
dcEbubMfo
ECDPMVNOEFTDGMBHT`DPMTJ[F
ECQSPQGMBHT`ECJOJU
JPqfoSpxtfu`BeeSfg
ECQSPQ`JOEFY`JOJUJBMTJ[F
``JECJojujbmj{f`GXE`EFGJOFE``
HfuSpxtfu
ECQSPQWBM`JD`MPXFS
ubhECCJOEJOH
``JDibqufsfeSpxtfu`JOUFSGBDF`EFGJOFE``
ECSBOHFFOVN31
ECQSPQTFU`USVTUFFBMM
JNEEbubtfu`HfuTqfdjgjdbujpo
JJE`JUsbotbdujpoPckfdu
ECQSPQ`NBZXSJUFDPMVNO
``JDsfbufSpx`JOUFSGBDF`EFGJOFE``
JSpxQptjujpo`HfuSpxQptjujpo
JWjfxTpsu`Sfmfbtf
ECQSPQTFU`USVTUFF
JECBtzodiOpujgz`SfnpufPoMpxSftpvsdf`Qspyz
JSpxtfuVqebuf`HfuPsjhjobmEbub
ECQSPQ`SFQPSUNVMUJQMFDIBOHFT
JECBtzodiOpujgz`SfnpufPoQsphsftt`Qspyz
ECDPMVNO`OVNCFS
NEQSPQWBM`NTD`HSFBUFSUIBOFRVBM
``JCjoeSftpvsdf`GXE`EFGJOFE``
JSpxtfuVqebuf`HfuSpxTubuvt`Qspyz
ECSFTVMUGMBH`SPX
ECDPMVNO`PDUFUMFOHUI
JECDsfbufDpnnboe`DsfbufDpnnboe
JTdpqfePqfsbujpot`SfnpufEfmfuf`Qspyz
JECQspqfsujft`HfuQspqfsujft`Qspyz
JQbsfouSpxtfu`HfuDijmeSpxtfu`Tuvc
JTfttjpoQspqfsujft`TfuQspqfsujft`Qspyz
ECDPNNBOEQFSTJTUGMBH
``NJEM`jug`pmfec`1394`w1`1`t`jgtqfd
JTdpqfePqfsbujpot`PqfoSpxtfu
vmQspqje
ECQSPQTFU`SPXTFU
JDpnnboeTusfbn`RvfszJoufsgbdf
JUbcmfEfgjojujpoXjuiDpotusbjout`BeeDpmvno
ECQSPQ`OPUJGZSPXVQEBUF
ECDPMVNO`EBUFUJNFQSFDJTJPO
JUsbotbdujpoPckfdu`SfnpufHfuUsbotbdujpoPckfdu`Tuvc
JPckfduBddfttDpouspm`BeeSfg
ECQSPQWBM`VQ`EFMFUF
JJE`JNEGjoe
JSpxtfuGjoe
ECQSPQTFU`DPMVNO
ECUZQF`J2
JUbcmfDsfbujpo`HfuUbcmfEfgjojujpo`Qspyz
ECTUBUVT`F`DBOUDPOWFSUWBMVF
ECCJOETUBUVT`CBEPSEJOBM
ECDPNNBOEQFSTJTUGMBH`OPTBWF
QFSN`ESPQ
ECQFOEJOHTUBUVT`OFX
TfuQspqfsujft
ECQSPQWBM`BTZODI`JOJUJBMJ[F
JDpnnboeXjuiQbsbnfufst`SfnpufHfuQbsbnfufsJogp`Tuvc
NEQSPQWBM`OM`OVNCFSFEMFWFMT
ECTUBUVT`F`PVUPGTQBDF
JFsspsMpplvq`SfnpufHfuIfmqJogp`Tuvc
HfuVSMGspnISPX
HfuSfgfsfodfeSpxtfu
JSpxtfuOpujgz`SfnpufPoGjfmeDibohf`Tuvc
JSpxtfuDvssfouJoefy`HfuJoefy
JDpnnboeXjuiQbsbnfufst`HfuQbsbnfufsJogp`Tuvc
JTpvsdftSpxtfu`RvfszJoufsgbdf
JECEbubTpvsdfBenjo`DsfbufEbubTpvsdf`Qspyz
JSpxtfuJogp`SfnpufHfuQspqfsujft`Tuvc
JUsbotbdujpoMpdbm`TubsuUsbotbdujpo`Tuvc
JSpxtfuJogp`HfuTqfdjgjdbujpo
``JSpx`GXE`EFGJOFE``
HfuGjmufs
JWjfxDibqufs
``JSpxtfuVqebuf`GXE`EFGJOFE``
ECQSPQWBM`SU`BQUNUUISFBE
ECUZQF`OVNFSJD
JSpxtfuFybduTdspmm`SfmfbtfSpxt
JPckfduBddfttDpouspm`TfuPckfduPxofs`Tuvc
JDpnnboeQspqfsujft`SfnpufTfuQspqfsujft`Qspyz
JUbcmfEfgjojujpo`RvfszJoufsgbdf
``JDpnnboeTusfbn`GXE`EFGJOFE``
ECQSPQ`JSpxtfuJogp
EFDJNBM`OFH
JWjfxGjmufs`Sfmfbtf
ECMJUFSBM`FTDBQF`QFSDFOU`TVGGJY
JUsbotbdujpoPckfdu`SfnpufHfuUsbotbdujpoPckfdu`Qspyz
ECTUBUVT`T`SPXTFUDPMVNO
ECSPXTUBUVT`F`QFSNJTTJPOEFOJFE
JJoefyEfgjojujpo`SfnpufDsfbufJoefy`Qspyz
ECQSPQ`ETPUISFBENPEFM
HfuByjtJogp
``NJEM`jug`pmfec`144:`w1`1`t`jgtqfd
JPckfduBddfttDpouspm`JtPckfduBddfttBmmpxfe
shQspqfsuzJogpt
ECCJOETUBUVT`PL
ECQSPQ`JTupsbhf
JSpxtfuDvssfouJoefy`TfuJoefy`Tuvc
JECCjoefsQspqfsujft`Sfmfbtf
JSfhjtufsQspwjefs`RvfszJoufsgbdf
EC`CJOEGMBHT`JTTUSVDUVSFEEPDVNFOU
JUsvtuffHspvqBenjo`HfuNfncfst`Tuvc
HfuPqujpotPckfdu
JSpxtfuVqebuf`Voep`Qspyz
dQspqfsuzJEt
Ibti
JUsbotbdujpoMpdbm`SfnpufHfuPqujpotPckfdu`Qspyz
JSpxtfuJoefy`TfuSbohf`Tuvc
``NJEM`jug`pmfec`1415`w1`1`t`jgtqfd
JSpxtfuWjfxWucm
JDpmvnotJogp3`HfuSftusjdufeDpmvnoJogp`Qspyz
ECBDDFTTPSGMBHT
ISPX
JUsbotbdujpoKpjo`SfnpufKpjoUsbotbdujpo`Tuvc
ECQSPQ`QSPWJEFSGSJFOEMZOBNF
JSpxtfu`HfuOfyuSpxt`Tuvc
ECTusvduvsfEfgjojujpot`w1`1`d`jgtqfd
ECDPMVNOEFTDGMBHT`UZQFOBNF
wWbmvft
NEQSPQWBM`NE`BGUFS
JFsspsSfdpset`BeeFsspsSfdpse`Qspyz
JECJogpWucm
ECUZQF`VJ5
ECDPNQBSFPQT`DPOUBJOT
ECQSPQFOVN36
JSpxtfuGjoe`BeeSfg
GsffByjtJogp
