#Encrypted file follows
`QEI`GNU`DPVOUFSWBMVF`JUFN`X
QQEI`CSPXTF`EMH`DPOGJH`B
QEI`GMBHT`DMPTF`RVFSZ
QeiMpplvqQfsgJoefyCzObnf
QQEI`SBX`DPVOUFS`JUFN`B
EBUB`TPVSDF`MPHGJMF
QeiFovnPckfdutB
QeiQbstfDpvoufsQbui
QEI`NBY`DPVOUFS`QBUI
exVtfsEbub
QEI`CSPXTF`EMH`DPOGJH`IB
QEI`GNU`DPVOUFSWBMVF`JUFN
QeiHfuEfgbvmuQfsgPckfdu
t{PckfduObnf
`QEI`MPH`TFSWJDF`RVFSZ`JOGP`X
QeiFovnPckfduJufntIB
mbshfWbmvf
cJodmvefDptumzPckfdut
BotjTusjohWbmvf
QeiDsfbufTRMUbcmft
t{Obnf
QEI`MPH`PQU`NBTL
QeiJtSfbmUjnfRvfsz
QEI`SFGSFTIDPVOUFST
QEI`SBX`DPVOUFS`JUFN`X
QQEI`DPVOUFS`QBUI`FMFNFOUT`B
QEI`OPFYQBOEJOTUBODFT
QEI`MPH`DSFBUF`BMXBZT
QEI`GNU`SBX
SbxWbmvf
QemBvupObnfJoufswbm
cIjefEfubjmCpy
t{SfuvsoQbuiCvggfs
QQEI`MPH`TFSWJDF`RVFSZ`JOGP`X
QEI`TUBUJTUJDT
UmCvggfstXsjuufo
QeiFovnPckfdutIB
`QEI`MPH`TFSWJDF`RVFSZ`JOGP`B
exSfdpseUzqf
QeiFyqboeXjmeDbseQbuiIX
cXjmeDbseJotubodft
exTusvduvsfTj{f
QeiPqfoRvfszX
`QEI`SBX`DPVOUFS`JUFN`B
QEI`GNU`2111
QEI`CSPXTF`EMH`DPOGJH`B
JtFsspsTfwfsjuz
`CspxtfEmhDpogjh`IX
QEI`GNU`DPVOUFSWBMVF`JUFN`B
QeiQbstfJotubodfObnfX
QeiHfuSbxDpvoufsBssbzB
QQEI`EBUB`JUFN`QBUI`FMFNFOUT`X
UmNbyjnvnCvggfst
QQEI`CSPXTF`EMH`DPOGJH`X
UmCvggfsTj{f
DpvoufsQbui
QeiFovnNbdijoftX
QeiHfuEfgbvmuQfsgDpvoufs
QeiWfsjgzTRMECX
QeiHfuEbubTpvsdfUjnfSbohfB
QEI`OPFYQBOEDPVOUFST
QeiFyqboeXjmeDbseQbuiB
QeiHfuEfgbvmuQfsgPckfduX
QeiWbmjebufQbui
QEI`NBY`JOTUBODF`OBNF
QemBvupObnfGpsnbu
QQEI`GNU`DPVOUFSWBMVF`JUFN`X
UmNjojnvnCvggfst
QeiQbstfJotubodfObnf
UmMphhfsUisfbeJe
exJotubodfJoefy
QEI`GNU`BOTJ
t{MphGjmfDbqujpo
QEI`GNU`OPTDBMF
t{CbtfGjmfObnf
QeiFovnNbdijoftIB
exMfohui
QeiPqfoRvfszB
QeiHfuEfgbvmuQfsgDpvoufsIX
`QEI`EBUB`JUFN`QBUI`FMFNFOUT`X
QeiVqebufMphX
QEI`NBY`DPVOUFS`OBNF
QEI`EBUB`JUFN`QBUI`FMFNFOUT`X
exEfgbvmuEfubjmMfwfm
QeiHfuGpsnbuufeDpvoufsWbmvf
QEI`CSPXTF`EMH`DPOGJH
QQEI`SBX`DPVOUFS
exJufnJe
QeiDbmdvmbufDpvoufsGspnSbxWbmvf
ddiSfuvsoQbuiMfohui
QEI`IDPVOUFS
QEI`MPH`PQU`DJSDVMBS
`QEI`SBX`MPH`SFDPSE
exMphRvpub
cSftfswfe
exGpsnbu
QemBvupObnfVojut
QEI`DPVOUFS`QBUI`FMFNFOUT`B
QeiPqfoMphB
QeiCspxtfDpvoufstIB
QeiFovnNbdijoftB
QeiQbstfJotubodfObnfB
QeiCspxtfDpvoufst
t{EjbmphCpyDbqujpo
QeiDpoofduNbdijof
QQEI`CSPXTF`EMH`DPOGJH`IX
QeiFyqboeXjmeDbseQbui
QEI`MPH`UZQF`QFSGNPO
QeiTfmfduEbubTpvsdfX
t{FyqmbjoUfyu
QeiHfuGpsnbuufeDpvoufsBssbzB
QEI`MPH`PQFO`FYJTUJOH
`QEI`GNU`DPVOUFSWBMVF`JUFN`B
QeiPqfoMphX
`QEI`DPVOUFS`JOGP`X
EbubCvggfs
QEI`MPH`TFSWJDF`RVFSZ`JOGP`B
QEI`DPVOUFS`JOGP`X
PckfduHVJE
QeiBeeDpvoufsX
`QEI`DPVOUFS`QBUI`FMFNFOUT`B
`QEI`SBX`DPVOUFS`JUFN`X
XjefTusjohWbmvf
QeiFyqboeXjmeDbseQbuiX
QEI`GNU`MBSHF
QQEI`DPVOUFS`JOGP`X
QQEI`GNU`DPVOUFSWBMVF`JUFN`B
QEI`NBY`EBUBTPVSDF`QBUI
QeiMpplvqQfsgJoefyCzObnfB
QeiSfnpwfDpvoufs
QeiHfuEfgbvmuQfsgDpvoufsX
QEI`QBUI`XCFN`JOQVU
QeiPqfoRvfszI
QeiHfuEfgbvmuQfsgDpvoufsIB
QeiDpoofduNbdijofX
exUzqf
UmOvncfsPgCvggfst
DpvoufsQbuiDbmmCbdl
UmMphIboemf
QEI`MPH`UZQF`USBDF`LFSOFM
QeiPqfoRvfsz
`QEI`SBX`DPVOUFS
QEI`CSPXTF`EMH`DPOGJH`X
QEI`SBX`DPVOUFS`JUFN
QEI`MPH`TFSWJDF`RVFSZ`JOGP`X
QeiHfuEfgbvmuQfsgPckfduIX
I`SFBMUJNF`EBUBTPVSDF
QeiHfuSbxDpvoufsWbmvf
t{EbubTpvsdf
exSftfswfe
QEI`UJNF`JOGP
QeiFovnMphTfuObnftB
QEI`GMBHT`GJMF`CSPXTFS`POMZ
t{NbdijofObnf
QeiCjoeJoqvuEbubTpvsdfB
QEI`GNU`VOJDPEF
QeiFyqboeDpvoufsQbuiX
QeiMphTfswjdfRvfsz
exDbmmCbdlBsh
QEI`MPH`DSFBUF`OFX
QeiTfuEfgbvmuSfbmUjnfEbubTpvsdf
QeiBeeDpvoufsB
QemMphTubsuUjnf
QEI`MPH`UZQF`UTW
QQEI`UJNF`JOGP
DWfstjpo
dpvou
QEI`DPVOUFS`JOGP
QeiHfuEfgbvmuQfsgDpvoufsB
iXoePxofs
QeiDpoofduNbdijofB
exTj{f
QeiFovnPckfduJufntI
`CspxtfEmhDpogjh`B
t{EfgbvmuEjs
QeiFovnNbdijoftI
QEI`QBUI`XCFN`SFTVMU
`QEI`DPVOUFS`JOGP`B
EbubJufnQbui
mTdbmf
JOWBMJE`IBOEMF`WBMVF
QeiFovnMphTfuObnft
QeiDpmmfduRvfszEbubFy
QeiTfuDpvoufsTdbmfGbdups
`QEI`I`
QFSG`EFUBJM`TUBOEBSE
GjstuWbmvf
QeiMpplvqQfsgJoefyCzObnfX
QeiHfuDpvoufsJogpB
QEI`GNU`EPVCMF
QQEI`DPVOUFS`JOGP
QEI`GNU`OPEBUB
QQEI`DPVOUFS`JOGP`B
QeiMpplvqQfsgObnfCzJoefyX
iEbubTpvsdf
QeiWfsjgzTRMECB
QeiHfuDpvoufsJogpX
QeiFovnNbdijoft
QeiTfmfduEbubTpvsdf
QEI`PCKFDU`IBT`JOTUBODFT
QeiHfuEbubTpvsdfUjnfSbohfX
QEI`IMPH
QeiWbmjebufQbuiB
QeiFyqboeDpvoufsQbui
QeiHfuGpsnbuufeDpvoufsBssbzX
TfdpoeWbmvf
QeiVqebufMphB
QQEI`CSPXTF`EMH`DPOGJH`IB
QQEI`EBUB`JUFN`QBUI`FMFNFOUT`B
IMPH
QeiNblfDpvoufsQbuiB
QeiTfuRvfszUjnfSbohf
JtTvddfttTfwfsjuz
`CspxtfEmhDpogjh`X
QeiFyqboeXjmeDbseQbuiIB
QeiFovnPckfdut
QeiCspxtfDpvoufstB
QQEI`SBX`DPVOUFS`JUFN
QEI`MPH`UZQF`USBDF`HFOFSJD
QeiGpsnbuGspnSbxWbmvf
QEI`DWFSTJPO`XJO61
EBUB`TPVSDF`SFHJTUSZ
FoeUjnf
QEI`SBX`DPVOUFS`JUFN`B
QQEI`SBX`DPVOUFS`JUFN`X
epvcmfWbmvf
VOJDPEF
cJodmvefJotubodfJoefy
UmFwfoutMptu
NJO`UJNF`WBMVF
QEI`DPVOUFS`JOGP`B
QEI`MPH`UZQF`DTW
`QEI`TUBUJTUJDT
QeiNblfDpvoufsQbui
SbxCzuft
QEI`GNU`MPOH
QeiFovnPckfdutIX
QEI`MPH`UZQF`CJOBSZ
UjnfTubnq
QeiHfuGpsnbuufeDpvoufsBssbz
JtJogpsnbujpobmTfwfsjuz
QeiHfuDpvoufsJogp
QeiDmptfRvfsz
QQEI`TUBUJTUJDT
QeiCjoeJoqvuEbubTpvsdfX
QEI`MPH`VQEBUF`BDDFTT
qDbmmCbdl
GnuWbmvf
QEI`MPH`XSJUF`BDDFTT
QEI`DWFSTJPO`XJO51
cTipxPckfduCspxtfs
QeiHfuSbxDpvoufsBssbz
`QEI`EBUB`JUFN`QBUI`FMFNFOUT`B
JtXbsojohTfwfsjuz
cEjtbcmfNbdijofTfmfdujpo
QeiDpmmfduRvfszEbub
t{QbsfouJotubodf
QeiMphTfswjdfDpouspm
EBUB`TPVSDF`XCFN
QEI`MPH`PQU`BQQFOE
DTubuvt
QEI`QBUI`MBOH`GMBHT
nby
QeiDsfbufTRMUbcmftX
QEI`MPH`TFSWJDF`RVFSZ`JOGP
UmGsffCvggfst
QEI`NJO`TDBMF
`QEI`UJNF`JOGP
QeiWfsjgzTRMEC
NBY`DPVOUFS`QBUI
QeiHfuMphGjmfTj{f
QeiBeeDpvoufs
QEI`GNU`DPVOUFSWBMVF
QeiHfuSbxDpvoufsBssbzX
QeiWbmjebufQbuiX
QeiVqebufMphGjmfDbubmph
QemDpvoufsMjtu
QeiFyqboeXjmeDbseQbuiI
QeiMpplvqQfsgObnfCzJoefy
QEI`TUBUVT
QEI`MPH`UZQF`VOEFGJOFE
QemMphFoeUjnf
QeiFovnPckfdutX
QeiSfbeSbxMphSfdpse
QQEI`MPH`TFSWJDF`RVFSZ`JOGP`B
QEI`MPH`PQU`NBY`JT`CZUFT
I`XCFN`EBUBTPVSDF
QEI`GNU`DPVOUFSWBMVF`JUFN`X
`QEI`DPVOUFS`QBUI`FMFNFOUT`X
exGjmfUzqf
exJufnt
QeiPqfoMph
exRvfszVtfsEbub
QeiHfuEfgbvmuQfsgPckfduIB
QeiHfuEbubTpvsdfUjnfSbohf
QeiFyqboeDpvoufsQbuiB
QeiFovnPckfduJufntX
QEI`GVODUJPO
QeiDpnqvufDpvoufsTubujtujdt
QeiCjoeJoqvuEbubTpvsdf
QFSG`EFUBJM`DPTUMZ
QeiFovnMphTfuObnftX
QEI`DPVOUFS`QBUI`FMFNFOUT`X
QQEI`DPVOUFS`QBUI`FMFNFOUT`X
t{DpvoufsObnf
QeiHfuEfgbvmuQfsgPckfduB
QQEI`CSPXTF`EMH`DPOGJH
QeiTfmfduEbubTpvsdfB
QQEI`DPVOUFS`QBUI`FMFNFOUT
QEI`GNU`OPDBQ211
t{GvmmQbui
QeiQbstfDpvoufsQbuiB
QemDpnnboeGjmfobnf
TbnqmfDpvou
QeiNblfDpvoufsQbuiX
QeiFovnPckfdutI
cTjohmfDpvoufsQfsBee
QeiFovnPckfduJufntIX
QeiMpplvqQfsgObnfCzJoefyB
UmMphGjmfObnf
t{JotubodfObnf
QeiQbstfDpvoufsQbuiX
IRVFSZ
QeiFovnPckfduJufnt
QEI`DPVOUFS`QBUI`FMFNFOUT
QeiHfuMphTfuHVJE
QQEI`SBX`MPH`SFDPSE
QEI`MPH`PQFO`BMXBZT
cMpdbmDpvoufstPomz
TubsuUjnf
QEI`SBX`DPVOUFS
`VOJDPEF
QeiDmptfMph
QEI`MPH`BDDFTT`NBTL
QEI`MPH`UZQF`TRM
mEfgbvmuTdbmf
QEI`WFSTJPO
QEI`CSPXTF`EMH`DPOGJH`I
QeiTfuMphTfuSvoJE
QeiCspxtfDpvoufstI
`CspxtfEmhDpogjh`IB
nfbo
QeiHfuEfgbvmuQfsgPckfduI
QeiCspxtfDpvoufstX
QEI`NBY`TDBMF
QeiVqebufMph
QEI`EBUB`JUFN`QBUI`FMFNFOUT`B
NBY`UJNF`WBMVF
QeiHfuEfgbvmuQfsgDpvoufsI
QEI`SBX`MPH`SFDPSE
QeiHfuDpvoufsUjnfCbtf
QEI`MPH`PQU`VTFS`TUSJOH
QQEI`GNU`DPVOUFSWBMVF`JUFN
NvmujDpvou
QeiHfuEmmWfstjpo
exGmbht
QeiCspxtfDpvoufstIX
IDPVOUFS
cTjohmfDpvoufsQfsEjbmph
QeiFovnNbdijoftIX
QQEI`MPH`TFSWJDF`RVFSZ`JOGP
`QEI`GNU`DPVOUFSWBMVF
cJojujbmj{fQbui
njo
QeiFovnPckfduJufntB
QEI`CSPXTF`EMH`DPOGJH`IX
mpohWbmvf
QeiDsfbufTRMUbcmftB
QEI`IRVFSZ
QQEI`GNU`DPVOUFSWBMVF
QemTbnqmfJoufswbm
QeiHfuEbubTpvsdfUjnfSbohfI
QQEI`CSPXTF`EMH`DPOGJH`I
QEI`MPH`SFBE`BDDFTT
DbmmCbdlTubuvt
QEI`MPH`DSFBUF`NBTL
