#Encrypted file follows
QJENTJ`DPQZSJHIU
dbvvje
JQspqfsuzTfuTupsbhf`Pqfo`Qspyz
qspqje
ubhDBM
QJENTJ`TUBUVT`JOQSPHSFTT
ubhDBI
QJEETJ`TMJEFDPVOU
JQspqfsuzTupsbhf`Sfwfsu
DBMQTUS
JQspqfsuzTupsbhf`Sfmfbtf
qqvolWbm
dbebuf
dbdz
JJE`JQspqfsuzTupsbhf
JQspqfsuzTupsbhf`TfuDmbtt`Qspyz
MQTBGFBSSBZ`VtfsTj{f
JQspqfsuzTupsbhf`RvfszJoufsgbdf
QSPQTFUIES`PTWFS`NBKPS
DBCTUSCMPC
qctusWbm
QJE`TFDVSJUZ
vjWbm
ubhDBMQTUS
JQspqfsuzTupsbhf`TfuUjnft
QSPQTFUIES`PTWFS`NJOPS
DBJ
dzWbm
JQspqfsuzTupsbhf
Sfmfbtf
DBCPPM
JQspqfsuzTupsbhf`XsjufQspqfsuzObnft`Qspyz
JQspqfsuzTupsbhf`EfmfufNvmujqmf`Qspyz
JFovnTUBUQSPQTUH`Ofyu`Qspyz
ubhDBQSPQWBSJBOU
dbctus
QJETJ`DSFBUF`EUN
``qspqjem`i``
JQspqfsuzTupsbhf`SfbeQspqfsuzObnft`Qspyz
JQspqfsuzTupsbhf`Tubu`Qspyz
QJEEJ`UIVNCOBJM
QJE`NPEJGZ`UJNF
QJETJ`XPSEDPVOU
QSPQTFUGMBH`OPOTJNQMF
JFovnTUBUQSPQTFUTUH`SfnpufOfyu`Qspyz
QJENTJ`TPVSDF
efdWbm
GsffQspqWbsjbouBssbz
QJENTJ`FEJUPS
qt{Wbm
tdpef
CTUS`VtfsNbstibm
JQspqfsuzTfuTupsbhf`Efmfuf`Qspyz
JQspqfsuzTupsbhf`TfuDmbtt`Tuvc
QspqWbsjbouDmfbs
dbqspqwbs
qtdpef
QJETJ`UJUMF
QJENTJ`TUBUVT`PUIFS
QJETJ`MBTUBVUIPS
QJEETJ`NBOBHFS
TfuDmbtt
DBD
JFovnTUBUQSPQTFUTUH`Ofyu
QspqWbsjbouJoju
SfbeQspqfsuzObnft
ubhDBJ
JQspqfsuzTfuTupsbhf`Pqfo
JQspqfsuzTfuTupsbhfWucm
QJE`CFIBWJPS
JFovnTUBUQSPQTFUTUH`Ofyu`Qspyz
JFovnTUBUQSPQTUH`Ofyu`Tuvc
QSPQTQFD
QJEETJ`NNDMJQDPVOU
JQspqfsuzTfuTupsbhf`Efmfuf`Tuvc
``NJEM`jug`qspqjem`1111`w1`1`t`jgtqfd
JFovnTUBUQSPQTUH`Sfmfbtf
QSPQTFUIES`PTWFSTJPO`VOLOPXO
gmuWbm
jWbm
ubhDBECM
qdmjqebub
gjmfujnf
xSftfswfe4
JQspqfsuzTupsbhf`Dpnnju`Qspyz
JFovnTUBUQSPQTFUTUH`Dmpof
ubhDBCTUS
JFovnTUBUQSPQTUH`SfnpufOfyu`Qspyz
JQspqfsuzTupsbhf`SfbeNvmujqmf`Qspyz
QJETJ`DIBSDPVOU
EfmfufNvmujqmf
JJE`JFovnTUBUQSPQTFUTUH
QJEETJ`QSFTGPSNBU
dbecm
qebuf
dmtje
ubhDBVJ
QJENTJ`TUBUVT`SFWJFX
JFovnTUBUQSPQTFUTUH`Dmpof`Tuvc
QSPQTFUIES`PTWFS`LJOE
QspqTuhObnfUpGnuJe
JQspqfsuzTfuTupsbhf`RvfszJoufsgbdf
QJETJ`QBHFDPVOU
JQspqfsuzTfuTupsbhf
qqejtqWbm
QJENTJ`PXOFS
QJE`GJSTU`OBNF`EFGBVMU
TUBUQSPQTFUTUH
QJE`MPDBMF
MQWFSTJPOFETUSFBN
viWbm
qjWbm
JFovnTUBUQSPQTFUTUH`Sftfu
dbdmjqebub
Dmpof
QJENTJ`TUBUVT`GJOBM
dbvj
JFovnTUBUQSPQTFUTUH`BeeSfg
TfuUjnft
jouWbm
QJENTJ`TUBUVT`OPSNBM
JQspqfsuzTfuTupsbhf`Pqfo`Tuvc
QJEETJ`DPNQBOZ
QJETJ`UIVNCOBJM
JJE`JFovnTUBUQSPQTUH
QJENTJ`QSPKFDU
JQspqfsuzTupsbhf`Fovn
JQspqfsuzTupsbhf`EfmfufQspqfsuzObnft`Tuvc
QJEETJ`DBUFHPSZ
QJEETJ`MJOFDPVOU
wu
qwbsWbm
qvjWbm
``NJEM`jug`qspqjem`1111`w1`1`d`jgtqfd
QSPQTFU`CFIBWJPS`DBTF`TFOTJUJWF
JFovnTUBUQSPQTUH`Tljq`Qspyz
QJE`NBY`SFBEPOMZ
MQQSPQWBSJBOU
dbvi
ubhDBGJMFUJNF
JQspqfsuzTupsbhf`SfbeNvmujqmf
Sftfu
qdzWbm
mWbm
DBI
QJE`NJO`SFBEPOMZ
JFovnTUBUQSPQTFUTUH`Sftfu`Qspyz
JFovnTUBUQSPQTUHWucm
JQspqfsuzTfuTupsbhf`Dsfbuf`Qspyz
QJE`GJSTU`VTBCMF
QSPQWBS`QBE3
JQspqfsuzTupsbhf`XsjufNvmujqmf`Qspyz
dbi
dbmqtus
JQspqfsuzTupsbhf`XsjufQspqfsuzObnft`Tuvc
JJE`JQspqfsuzTfuTupsbhf
JFovnTUBUQSPQTUH`Sftfu`Qspyz
MQFOVNTUBUQSPQTFUTUH
qgmuWbm
QJE`EJDUJPOBSZ
JQspqfsuzTupsbhf`EfmfufNvmujqmf
GnuJeUpQspqTuhObnf
exPTWfstjpo
gnuje
``SFRVJSFE`SQDOES`I`WFSTJPO``
JFovnTUBUQSPQTFUTUH`Sfmfbtf
ubhTUBUQSPQTFUTUH
QJENTJ`TUBUVT
cppmWbm
QJEETJ`QBSDPVOU
JQspqfsuzTupsbhf`SfbeQspqfsuzObnft
QJETJ`SFWOVNCFS
JFovnTUBUQSPQTUH`Sftfu`Tuvc
JFovnTUBUQSPQTFUTUH`RvfszJoufsgbdf
dbd
``JFovnTUBUQSPQTUH`GXE`EFGJOFE``
QJETJ`FEJUUJNF
JFovnTUBUQSPQTFUTUH`Dmpof`Qspyz
``JFovnTUBUQSPQTFUTUH`JOUFSGBDF`EFGJOFE``
``JQspqfsuzTfuTupsbhf`JOUFSGBDF`EFGJOFE``
ctusWbm
QSPQWBSJBOU
JQspqfsuzTupsbhf`XsjufQspqfsuzObnft
dbctuscmpc
JQspqfsuzTupsbhf`EfmfufQspqfsuzObnft
qxt{Wbm
``JQspqfsuzTupsbhf`GXE`EFGJOFE``
qvmWbm
JFovnTUBUQSPQTFUTUH
WFSTJPOFETUSFBN
DBDZ
NJEM`vtfs`gsff
qefdWbm
JFovnTUBUQSPQTFUTUH`SfnpufOfyu`Tuvc
JQspqfsuzTupsbhf`Sfwfsu`Tuvc
vmWbm
QJEETJ`OPUFDPVOU
DBMQXTUS
``NJEM`jug`qspqjem`1231`w1`1`t`jgtqfd
DBQSPQWBSJBOU
JFovnTUBUQSPQTUH`Dmpof`Tuvc
RvfszJoufsgbdf
ubhDBD
Pqfo
ubhQSPQWBSJBOU
qTupsbhf
ctuscmpcWbm
vmLjoe
MQQSPQFSUZTFUTUPSBHF
cWbm
ubhDBVI
SfbeNvmujqmf
QJENTJ`TUBUVT`ESBGU
JQspqfsuzTupsbhf`XsjufNvmujqmf
MQQSPQFSUZTUPSBHF
QspqWbsjbouDpqz
QJEETJ`IJEEFODPVOU
QSPQWBS`QBE2
JQspqfsuzTupsbhf`Fovn`Tuvc
qvjouWbm
mqxtusObnf
CTUS`VtfsGsff
qmWbm
xSftfswfe3
qTusfbn
`QSPQWBSJBOUJOJU`EFGJOFE`
EfmfufQspqfsuzObnft
QJE`DPEFQBHF
QJENTJ`TUBUVT`OFX
Fovn
JFovnTUBUQSPQTUH`RvfszJoufsgbdf
QSPQWBS`QBE4
dbgmu
XsjufNvmujqmf
``JQspqfsuzTupsbhf`JOUFSGBDF`EFGJOFE``
JQspqfsuzTupsbhfWucm
mqxtus
JQspqfsuzTfuTupsbhf`Sfmfbtf
QJENTJ`TFRVFODF`OP
JFovnTUBUQSPQTUH`Dmpof
QSPQTFUGMBH`BOTJ
MQTBGFBSSBZ`VtfsVonbstibm
``JFovnTUBUQSPQTFUTUH`GXE`EFGJOFE``
QSTQFD`JOWBMJE
ubhDBMQXTUS
QSTQFD`MQXTUS
bujnf
DDI`NBY`QSPQTUH`OBNF
JQspqfsuzTfuTupsbhf`Fovn`Tuvc
DBECM
DBVJ
NJEM`vtfs`bmmpdbuf
JFovnTUBUQSPQTUH`BeeSfg
DBVM
JQspqfsuzTupsbhf`EfmfufNvmujqmf`Tuvc
QJETJ`MBTUQSJOUFE
DBVI
QJETJ`BQQOBNF
JFovnTUBUQSPQTFUTUH`Tljq`Tuvc
Tubu
DBCTUS
dbmqxtus
Sfwfsu
DBM
ubhDBDMTJE
qcppmWbm
qvvje
QJEETJ`IFBEJOHQBJS
DBGJMFUJNF
qbssbz
QJEETJ`TDBMF
qcWbm
QSPQTFUGMBH`VOCVGGFSFE
dFmfnt
DBGMU
QJENTJ`QSPEVDUJPO
ebuf
JQspqfsuzTfuTupsbhf`Dsfbuf`Tuvc
dbgjmfujnf
JQspqfsuzTupsbhf`SfbeNvmujqmf`Tuvc
ubhDBTDPEF
BeeSfg
QJETJ`DPNNFOUT
dbtdpef
qWfstjpofeTusfbn
JQspqfsuzTupsbhf`Fovn`Qspyz
QJETJ`LFZXPSET
CTUS`VtfsVonbstibm
TuhDsfbufQspqTfuTuh
JQspqfsuzTupsbhf`TfuUjnft`Qspyz
``JFovnTUBUQSPQTUH`JOUFSGBDF`EFGJOFE``
dujnf
``NJEM`jug`qspqjem`1231`w1`1`d`jgtqfd
JFovnTUBUQSPQTUH`SfnpufOfyu`Tuvc
QJETJ`TVCKFDU
MQTBGFBSSBZ`VtfsGsff
JQspqfsuzTfuTupsbhf`BeeSfg
ubhTUBUQSPQTUH
ubhDBEBUF
JQspqfsuzTupsbhf`XsjufNvmujqmf`Tuvc
dbvm
QJETJ`UFNQMBUF
qjouWbm
JQspqfsuzTupsbhf`Dpnnju
QSTQFD`QSPQJE
JFovnTUBUQSPQTFUTUH`Ofyu`Tuvc
JQspqfsuzTfuTupsbhf`Fovn`Qspyz
JFovnTUBUQSPQTFUTUH`Sftfu`Tuvc
Tljq
QJE`JMMFHBM
JQspqfsuzTupsbhf`TfuUjnft`Tuvc
JFovnTUBUQSPQTUH`Ofyu
ubhDBDMJQEBUB
JQspqfsuzTfuTupsbhf`Dsfbuf
JQspqfsuzTupsbhf`SfbeQspqfsuzObnft`Tuvc
qFmfnt
DBTDPEF
JQspqfsuzTupsbhf`Sfwfsu`Qspyz
JQspqfsuzTupsbhf`Tubu
DBDMJQEBUB
QJETJ`BVUIPS
ubhDBDZ
cppm
qvolWbm
JFovnTUBUQSPQTUH`Tljq
ubhWfstjpofeTusfbn
Dsfbuf
ubhDBVM
QJENTJ`SBUJOH
dbj
ubhDBCPPM
TUBUQSPQTUH
dbvc
hvjeWfstjpo
ubhDBGMU
JFovnTUBUQSPQTFUTUHWucm
xSftfswfe2
nujnf
``JQspqfsuzTfuTupsbhf`GXE`EFGJOFE``
DBVC
ubhQSPQTQFD
qdWbm
QJENTJ`TUBUVT`WBMVF
hsgGmbht
MQFOVNTUBUQSPQTUH
QJEETJ`CZUFDPVOU
Efmfuf
vjouWbm
QJENTJ`TUBUVT`QSFMJN
QJENTJ`TUBUVT`FEJU
MQTBGFBSSBZ`VtfsNbstibm
JQspqfsuzTupsbhf`TfuDmbtt
QSPQTFUGMBH`DBTF`TFOTJUJWF
JQspqfsuzTupsbhf`Tubu`Tuvc
dbm
JFovnTUBUQSPQTFUTUH`Tljq
ecmWbm
JFovnTUBUQSPQTUH`Dmpof`Qspyz
QJEETJ`MJOLTEJSUZ
ubhDBCTUSCMPC
qejtqWbm
TuhPqfoQspqTuh
qqbssbz
qecmWbm
QSPQTFUGMBH`EFGBVMU
DBDMTJE
Ofyu
JQspqfsuzTfuTupsbhf`Fovn
JFovnTUBUQSPQTUH`Tljq`Tuvc
JQspqfsuzTupsbhf`EfmfufQspqfsuzObnft`Qspyz
dbcppm
dWbm
XsjufQspqfsuzObnft
iWbm
JFovnTUBUQSPQTUH
QJETJ`EPD`TFDVSJUZ
JFovnTUBUQSPQTUH`Sftfu
DBEBUF
cmpc
QJENTJ`TUBUVT`QSPPG
QJEETJ`EPDQBSUT
ubhDBVC
JQspqfsuzTupsbhf`Dpnnju`Tuvc
ubh`joofs`QSPQWBSJBOU
QJENTJ`TVQQMJFS
JFovnTUBUQSPQTFUTUH`Tljq`Qspyz
JQspqfsuzTupsbhf`BeeSfg
CTUS`VtfsTj{f
Dpnnju
JQspqfsuzTfuTupsbhf`Efmfuf
QJETJ`MBTUTBWF`EUN
TuhDsfbufQspqTuh
