#Encrypted file follows
OesDpogpsnbouWbszjohTusvduGsff
OES`DT`TJ[F`DPOWFSU`SPVUJOFT
OesTI`UMVQEfdjtjpoCvggfs
JNQMJDJU`IBOEMF`JOGP
OesWbszjohBssbzNbstibmm
`OES`VTFS`NBSTIBM`JOGP
OesGvmmQpjoufsYmbuGsff
SqdTtEjtbcmfBmmpdbuf
qbe
QBSBN`PGGTFUUBCMF
qPck
BduvbmDpvouBssbz
GvmmQusYmbuUbcmft
gDifdlCpvoet
cppmfbo`bssbz`gspn`oes
OesGvmmQpjoufsJotfsuSfgJe
`OES`QSPD`DPOUFYU
NJEM`nfntfu
SfvtfCvggfs
OfyuSfgJe
oDpvou
gIbtSfuvso
OesBtzodTuvcDbmm
OesDpnqmfyBssbzNbstibmm
GbvmuPggtfu
VTFS`DBMM`BVY`NBTL
Qpjoufs
CvggfsTj{f
GvmmQusSfgJe
qBshRvfvf
GVMM`QUS`UP`SFGJE`FMFNFOU
YmbuTjef
QHFOFSJD`CJOEJOH`JOGP
OesCzufDpvouQpjoufsGsff
vGmbht3
TbwfeDpoufyuIboemft
OesGvmmQpjoufsYmbuJoju
DT`UZQF`OFU`TJ[F`SPVUJOF
OvncfsPgFousjft
UzqfTusjoh
OesOtHfuCvggfs
QSPYZ`QIBTF
CvggfsNbsl
OES`TDPOUFYU
OesDpogpsnbouBssbzNbstibmm
OesTfswfsDbmm
JEM`DT`OP`DPOWFSU
OES`SVOEPXO
qgoGsff
Tubuf
OesDpogpsnbouTusvduVonbstibmm
Sftfswfe5
QNJEM`TUVC`EFTD
SQD`WBS`FOUSZ
qBssbzJogp
`njem`vonbsti`vq
UBSHFU`JT`OU462`PS`XJO:6`PS`MBUFS
GpsnbuTusjohPggtfu
``HFOFSJD`CJOEJOH`JOGP
OesDpogpsnbouTusvduNfnpszTj{f
HFOFSJD`VOCJOE`SPVUJOF
qgoGsffYnju
OesJoufsgbdfQpjoufsVonbstibmm
vtfsDpoufyu
OesNbqDpnnBoeGbvmuTubuvt
OesHfuCvggfs
VTFS`NBSTIBM`GD`IZQFS
CvggfsWbsjbodfNbsl
gVovtfe
`njem`vonb4
OesTI`JgBmmpdTfu
SqdTtEftuspzDmjfouDpoufyu
OesDtBssbzCvggfsTj{f
qwEftuDpoufyu
OesTfswfsJojujbmj{fNbstibmm
gJtPjdgTfswfs
OesTfswfsDpoufyuOfxVonbstibmm
qgoVocjoe
FYUFSO`HVJE
DPOTU`WUCM
`njem`gb9
OesDpogpsnbouWbszjohBssbzNbstibmm
DT`UZQF`MPDBM`TJ[F`SPVUJOF
OesDmjfouDbmm4
QNJEM`TFSWFS`JOGP
OesBtzodTfswfsDbmm
OesTfswfsNbstibmm
OESDDpoufyuVonbstibmm
YNJU`IFMQFS`SPVUJOF
SQD`TT`UISFBE`IBOEMF
bHfofsjdCjoejohSpvujofQbjst
OesTI`TusjohNbstibmm
OesTfswfsVonbstibmm
OesDpogpsnbouWbszjohBssbzCvggfsTj{f
qUzqfGpsnbu
SqdTtTfuUisfbeIboemf
OesYnjuPsSfqBtNfnpszTj{f
OESDDpoufyuNbstibmm
OesVtfsNbstibmNbstibmm
OES`GMPBU`SFQ`NBTL
TFSWFS`SPVUJOF
qHfofsjdCjoejohJogp
OesDpogpsnbouBssbzVonbstibmm
OesDmjfouJojujbmj{fOfx
VTFS`DBMM`JT`BTZOD
OesNbstiDDuyuIem
``SQD`DBMMFF
OesHfuEdpnQspupdpmWfstjpo
OES`JOU`SFQ`NBTL
OpujgzSpvujofUbcmf
OesGdMpoh
OesTjnqmfTusvduCvggfsTj{f
OES`QPJOUFS`RVFVF`TUBUF
OesDpogpsnbouBssbzCvggfsTj{f
VTFS`NBSTIBM`GD`VTNBMM
bYnjuRvjouvqmf
OES`BMMPD`BMM`OPEFT`DPOUFYU
OesVtfsNbstibmCvggfsTj{f
OesYnjuPsSfqBtGsff
OesOpoFodbqtvmbufeVojpoNfnpszTj{f
OesDpogpsnbouWbszjohTusvduNfnpszTj{f
OesFodbqtvmbufeVojpoCvggfsTj{f
OesFodbqtvmbufeVojpoVonbstibmm
`NJEM`TUVC`NFTTBHF
SqdVtfsGsff
qSftfswf
NfnpszTj{f
OES`DT`SPVUJOFT
IbtiNbtl
OESTDpoufyuNbstibmm3
OesDtUbhCvggfsTj{f
QGPSNBU`TUSJOH
OesDtBssbzGsff
`XDIBS`U`EFGJOFE
NJEM`TZOUBY`JOGP
qgoGspnOfuDt
Oes75BtzodDmjfouDbmm
OesGjfmePggtfu
VTFS`NBSTIBM`DC`UZQF
UBSHFU`JT`OU61`PS`MBUFS
Sftfswfe
OesDmjfouDpoufyuNbstibmm
OesOpoFodbqtvmbufeVojpoNbstibmm
`YNJU`SPVUJOF`RVJOUVQMF
OesOpoFodbqtvmbufeVojpoGsff
qQpjoufsRvfvfTubuf
OesTI`UMVQEfdjtjpo
Sftfswfe6
qgoOfuTj{f
njem`vtfs`gsff
czuf`gspn`oes
OesSqdTnDmjfouGsff
OesDpogpsnbouBssbzNfnpszTj{f
Oes75EdpnBtzodDmjfouDbmm
OesFodbqtvmbufeVojpoNfnpszTj{f
qSftfswfe2
`NJEM`TUVCMFTT`QSPYZ`JOGP
`njem`gb5
CvggfsDpogpsnbodfNbsl
OesDpoufyuIboemfJojujbmj{f
OES`FCDEJD`DIBS
QNJEM`TZOUBY`JOGP
OesDpnqmfyBssbzVonbstibmm
OesCzufDpvouQpjoufsNbstibmm
Ofyu
NJEM`vizqfs
BssbzPgPckfdut
SqdTtGsff
qgoGsffJotu
OesDpogpsnbouWbszjohTusvduNbstibmm
tnbmm`bssbz`gspn`oes
VTFS`NBSTIBM`GD`GMPBU
OesTfswfsJojujbmj{fOfx
OesTjnqmfTusvduNbstibmm
``NJEM`VTFS`EFGJOFE
QpjoufsUpSfgJe
qBmmpdBmmOpeftDpoufyu
OesTI`JgDpqz
OesBmmpdbuf
VTFS`NBSTIBM`DC`CVGGFS`TJ[F
OesWbszjohBssbzNfnpszTj{f
OesTI`JgBmmpdSfg
qSqdDiboofmCvggfs
qUsbotgfsTzouby
OES`BTDJJ`DIBS
VTFS`NBSTIBM`GD`DIBS
czuf
OesOpoDpogpsnbouTusjohNfnpszTj{f
Oes75BtzodTfswfsDbmm75
`njem`nb3
exTuvcQibtf
VTFS`NBSTIBM`VONBSTIBMMJOH`SPVUJOF
OesDpogpsnbouBssbzGsff
OesDpogpsnbouWbszjohBssbzGsff
`VTFS`NBSTIBM`DC`UZQF
Tjhobuvsf
VTFS`NBSTIBM`DC`VONBSTIBMM
SqdTtHfuUisfbeIboemf
OesQpjoufsNbstibmm
OesDpogpsnbouTusjohNfnpszTj{f
OesDpnqmfyTusvduCvggfsTj{f
OesQpjoufsCvggfsTj{f
DT`UZQF`GSPN`OFUDT`SPVUJOF
OESDDpoufyuCjoejoh
OesTuvcDbmm
OesWbszjohBssbzCvggfsTj{f
OesVtfsNbstibmVonbstibmm
OesGjyfeBssbzNfnpszTj{f
SQD`CVGQUS
VTFS`NBSTIBM`GD`EPVCMF
BSSBZ`JOGP
OesGjyfeBssbzVonbstibmm
YMBU`TFSWFS
OesBtzodDmjfouDbmm
YMBU`TJEF
qgoNbstibmm
bqgoOesSvoepxoSpvujoft
VTFS`NBSTIBM`NBSTIBMMJOH`SPVUJOF
izqfs
OesFodbqtvmbufeVojpoNbstibmm
OesTfoeSfdfjwf
`DPNN`GBVMU`PGGTFUT
QNJEM`TUVCMFTT`QSPYZ`JOGP
OesSqdTtEfgbvmuBmmpdbuf
OES`OPUJGZ3`SPVUJOF
`VTFS`NBSTIBM`SPVUJOF`RVBESVQMF
VTFS`NBSTIBM`TJ[JOH`SPVUJOF
OesDpssfmbujpoJojujbmj{f
HFOFSJD`CJOEJOH`SPVUJOF
`DMJFOU`DBMM`SFUVSO
OesQpjoufsNfnpszTj{f
qGpsnbuUzqft
OesDpnqmfyBssbzNfnpszTj{f
OesOpoDpogpsnbouTusjohNbstibmm
OesEdpnBtzodDmjfouDbmm
OesJoufsgbdfQpjoufsNbstibmm
Sftfswfe62`5
Tj{fQusMfohuiBssbz
OesNbstiTDuyuIem
EjtqbudiUbcmf
Tj{f
NJEM`TFSWFS`JOGP
OesJoufsgbdfQpjoufsGsff
TUVC`QIBTF
VTFS`NBSTIBM`DC
TUVC`DBMM`TFSWFS`OP`ISFTVMU
qTuvcEftd
`njem`vonb3
NbyDpvouBssbz
EFDMTQFD`VVJE
JogpsnbujpoMfwfm
DtSpvujofUbcmft
Cvggfs
VTFS`NBSTIBM`DC`GSFF
DpnnPggtfu
Vovtfe
BduvbmDpvou
tnbmm`gspn`oes
gCvggfsWbmje
YNJU`SPVUJOF`RVJOUVQMF
OesTjnqmfTusvduNfnpszTj{f
OesTfswfsDbmmOes75
OesSqdTnDmjfouBmmpdbuf
QNJEM`TUVC`NFTTBHF
OesTjnqmfUzqfNbstibmm
`NJEM`GPSNBU`TUSJOH
vGmbht
OES`DDPOUFYU
``NJEM`EFDMTQFD`EMMFYQPSU
OesTfswfsDbmm3
SQD`MFOHUI
QGVMM`QUS`YMBU`UBCMFT
bVtfsNbstibmRvbesvqmf
OesDpnqmfyTusvduGsff
Gpsnbu
VTFS`NBSTIBM`GD`CZUF
`njem`nb2
OesPmfGsff
HFOFSJD`CJOEJOH`SPVUJOF`QBJS
OES`DIBS`SFQ`NBTL
OesTI`JgGsff
Nfnpsz
TUVC`VONBSTIBM
`NJEM`TZOUBY`JOGP
DT`UZQF`UP`OFUDT`SPVUJOF
Sftfswfe62`6
QSPYZ`TFOESFDFJWF
OESTDpoufyuNbstibmmFy
OesTfswfsJojujbmj{f
OesSqdTnTfuDmjfouUpPtg
OesDpowfsu
`VTFS`NBSTIBM`DC
SQD`CBE`TUVC`EBUB`FYDFQUJPO`GJMUFS
`njem`gb3
SqdTnTxbqDmjfouBmmpdGsff
`njem`nb9
`GVMM`QUS`YMBU`UBCMFT
QspdGpsnbuTusjoh
`njem`nbsti`mit
MpxTubdlNbsl
YmbuUbcmf
SqdTtTxbqDmjfouBmmpdGsff
qgoUsbotmbufGspnYnju
OesQpjoufsVonbstibmm
`NJEM`TFSWFS`JOGP`
OesDtUbhVonbstibmm
fssps`tubuvt`u
OesTfswfsDbmm4
Oes75BtzodTfswfsDbmm
nGmbht
QOES`DPSSFMBUJPO`JOGP
OES`MJUUMF`FOEJBO
OesDpssfmbujpoQbtt
NJEM`vtfs`gsff
qgoUsbotmbufUpYnju
`njem`nb5
dt`czuf
OesNbstiDpogTusjohIes
OesTfswfsDpoufyuVonbstibmm
OesDpoufyuIboemfTj{f
OesJoufsgbdfQpjoufsCvggfsTj{f
OesCzufDpvouQpjoufsCvggfsTj{f
OesVtfsNbstibmNfnpszTj{f
Mfwfm2
OesVoNbstiDpogTusjohIes
exEftuDpoufyu
OesGsffCvggfs
SqdTnGsff
OesTI`VQEfdjtjpo
qBvupIboemf
OesWbszjohBssbzVonbstibmm
OESTDpoufyuNbstibmm
OesTfswfsDpoufyuOfxNbstibmm
qNbmmpdGsffTusvdu
OesGjyfeBssbzNbstibmm
QGVMM`QUS`UP`SFGJE`FMFNFOU
VTFS`DBMM`OFX`DPSSFMBUJPO`EFTD
NJEM`btdjj`tusdqz
gEpouDbmmGsffJotu
OES`MPDBM`EBUB`SFQSFTFOUBUJPO
OesDpogpsnbouTusjohNbstibmm
``SQDOES`I`WFSTJPO``
NJEM`TUVC`NFTTBHF
TDPOUFYU`RVFVF
czuf`bssbz`gspn`oes
cppmfbo
Sftfswfe62`3
OesJoufsgbdfQpjoufsNfnpszTj{f
gVovtfe3
VTFS`NBSTIBM`DC`TJHOBUVSF
OesTjnqmfTusvduVonbstibmm
OesDpogpsnbouWbszjohTusvduVonbstibmm
TubufUbcmf
OesDpowfsu3
qQsjnjujwfIboemf
OvncfsPgCvdlfut
OES`TIBSFBCMF
QSPYZ`DBMDTJ[F
OesDmjfouJojujbmj{f
tnbmm
JhopsfFncfeefeQpjoufst
QSPYZ`NBSTIBM
Pggtfu
njem`vtfs`bmmpdbuf
OesDmfbsPvuQbsbnfufst
`BeesfttPgSfuvsoBeesftt
UivolUbcmf
qNfnpszMjtu
gJoEpouGsff
OesTjnqmfUzqfVonbstibmm
OesFodbqtvmbufeVojpoGsff
bqgoFyqsFwbm
`JEM`DT`DPOWFSU
Tj{fQusPggtfuBssbz
OESTDpoufyuVonbstibmmFy
OesTfswfsJojujbmj{fQbsujbm
QYNJU`SPVUJOF`RVJOUVQMF
OesDpogpsnbouTusvduNbstibmm
qgoVonbstibmm
qgoBmmpdbuf
OesQbsujbmJhopsfDmjfouNbstibmm
OesDpogpsnbouWbszjohBssbzNfnpszTj{f
OesYnjuPsSfqBtVonbstibmm
Ejnfotjpo
qTzoubyJogp
OESTDpoufyuVonbstibmm
Oes75BtzodTuvcDbmm
VTFS`NBSTIBM`GD`TIPSU
OesVtfsNbstibmTjnqmfUzqfDpowfsu
`HFOFSJD`CJOEJOH`SPVUJOF`QBJS
`OES`DT`SPVUJOFT
WbsjbodfNbsl
OesSqdTtEjtbcmfBmmpdbuf
SqdTnEftuspzDmjfouDpoufyu
`njem`beeq
`IZQFS`EFGJOFE
OesGvmmQpjoufsGsff
OesDmjfouHfuTvqqpsufeTzoubyft
QBSSBZ`JOGP
OesPmfBmmpdbuf
GVMM`QUS`YMBU`UBCMFT
DT`UBH`HFUUJOH`SPVUJOF
`njem`bewnq
OesOpoDpogpsnbouTusjohCvggfsTj{f
QNJEM`YNJU`UZQF
OesTI`TusjohVoNbstibmm
OesOtTfoeSfdfjwf
JSqdTuvcCvggfs
qDpoufyu
OesDpogpsnbouTusvduGsff
JtDmjfou
SfgJe
HFU`VTFS`EBUB`SFQ
Sftfswfe62`4
VTFS`NBSTIBM`GD`VMPOH
qUsbotnjuUzqf
OesDpnqmfyBssbzCvggfsTj{f
``SQDOES`I``
EFDMTQFD`TFMFDUBOZ
DCUzqf
UBSHFU`JT`OU62`PS`MBUFS
QSPYZ`VONBSTIBM
NJEM`vtfs`bmmpdbuf
SqdNth
`NBMMPD`GSFF`TUSVDU
OesGdTipsu
OvncfsPgPckfdut
OesCzufDpvouQpjoufsVonbstibmm
OesOpoDpogpsnbouTusjohVonbstibmm
DPNN`GBVMU`PGGTFUT
qDpssJogp
qBtzodNth
QOES`BTZOD`NFTTBHF
OesVoNbstiDDuyuIem
OesTfswfsHfuTvqqpsufeTzoubyft
XjsfDpeftfu
qDpssNfnpsz
qgoCvggfsTj{f
OesTfswfsJojujbmj{fVonbstibmm
CvggfsFoe
OesTfswfsDpoufyuNbstibmm
qDTJogp
Qbe
OesDpogpsnbouTusvduCvggfsTj{f
GnuTusjohPggtfu
`TDPOUFYU`RVFVF
OesDpogpsnbouWbszjohBssbzVonbstibmm
OesQbsujbmJhopsfDmjfouCvggfsTj{f
TUVC`UIVOL
YMBU`DMJFOU
OesGjyfeBssbzGsff
VTFS`NBSTIBM`GD`TNBMM
OesDpnqmfyTusvduNfnpszTj{f
OesGjyfeBssbzCvggfsTj{f
JEM`DT`JO`QMBDF`DPOWFSU
OesYnjuPsSfqBtCvggfsTj{f
OesTfswfsDbmmBmm
OesDpogpsnbouTusjohVonbstibmm
qVtfsNbstibmMjtu
VTFS`NBSTIBM`GD`XDIBS
Tj{fQusDpvouBssbz
QHFOFSJD`CJOEJOH`SPVUJOF`QBJS
`OES`VTFS`NBSTIBM`JOGP`MFWFM2
OesGvmmQpjoufsRvfszQpjoufs
OesDsfbufTfswfsJoufsgbdfGspnTuvc
Wfstjpo
qGpsnbu
QpjoufsCvggfsNbsl
SqdTtBmmpdbuf
SQD`DMJFOU`GSFF
QSPYZ`HFUCVGGFS
OesTuvcDbmm4
qgoCjoe
OES`JFFF`GMPBU
qQsftfoufeUzqf
QQBSBN`PGGTFUUBCMF
VTFS`NBSTIBM`GSFFJOH`SPVUJOF
TubdlUpq
PggtfuBssbz
SqdTnTfuDmjfouBmmpdGsff
SqdTtFobcmfBmmpdbuf
SqdTnTfuUisfbeIboemf
Tjnqmf
SqdTtTfuDmjfouBmmpdGsff
OesTI`JgBmmpdDpqz
NbyDpvou
OesDmjfouDbmm
TuvcEftd
JEM`DT`OFX`CVGGFS`DPOWFSU
FYQS`FWBM
OesHfuVtfsNbstibmJogp
qUbhHfuujohSpvujoft
OesGvmmQpjoufsRvfszSfgJe
OesSqdTtEfgbvmuGsff
`njem`nbsti`vq
OesDpssfmbujpoGsff
UsbotgfsTzouby
QspdTusjoh
VTFS`NBSTIBM`DC`NBSTIBMM
OesVoNbstiTDuyuIem
NJEM`GPSNBU`TUSJOH
UBSHFU`JT`OU51`PS`MBUFS
JEM`DT`DPOWFSU
DTBssbzJogp
OesEdpnBtzodTuvcDbmm
OesDtBssbzNfnpszTj{f
``NJEM`EFDMTQFD`EMMJNQPSU
OesVtfsNbstibmGsff
SqdTnDmjfouGsff
OesOpoFodbqtvmbufeVojpoVonbstibmm
OES`WBY`GMPBU
OesYnjuPsSfqBtNbstibmm
SfgJeUpQpjoufs
qSftfswfe3
`NJEM`TUVC`EFTD
`TJ[F`U`EFGJOFE
cppmfbo`gspn`oes
OesOpoFodbqtvmbufeVojpoCvggfsTj{f
OesDpnqmfyTusvduNbstibmm
VTFS`DBMM`DUYU`NBTL
gJoPomzQbsbn
gIbtNfnpszWbmjebufDbmmcbdl
Gmbht
CbdljohTupsfMpxNbsl
OES`JCN`GMPBU
TUVC`DBMM`TFSWFS
NJEMWfstjpo
NJEM`TUVCMFTT`QSPYZ`JOGP
`njem`vonb2
`njem`vonb5
NBMMPD`GSFF`TUSVDU
NJEM`btdjj`tusmfo
OesDmjfouDbmm3
OES`VTFS`NBSTIBM`JOGP
SqdJoufsgbdfJogpsnbujpo
qgoUpOfuDt
SqdTnFobcmfBmmpdbuf
OesDmjfouDpoufyuVonbstibmm
TUVC`NBSTIBM
OesDtUbhNbstibmm
VTFS`NBSTIBM`GD`MPOH
OES`CJH`FOEJBO
OesDtBssbzNbstibmm
SqdTnBmmpdbuf
SqdTnEjtbcmfBmmpdbuf
gIbtFyufotjpot
OesDpnqmfyBssbzGsff
OesDpogpsnbouTusjohCvggfsTj{f
NJEM`JOUFSGBDF
dcOESDpoufyu
TbwfeIboemf
HFOFSJD`CJOEJOH`JOGP
VojrvfQusDpvou
OesQbsujbmJhopsfTfswfsVonbstibmm
OES`VTFS`NBSTIBM`JOGP`MFWFM2
DpogpsnbodfNbsl
OesTI`JgBmmpd
OesDtUbhNfnpszTj{f
OESTDpoufyuWbmvf
gIbtOfxDpssEftd
EftjsfeSfdfjwjohDpeftfu
OESTDpoufyuVonbstibmm3
`GVMM`QUS`UP`SFGJE`FMFNFOU
DT`TUVC`JOGP
qTuvcNth
`OES`DT`TJ[F`DPOWFSU`SPVUJOFT
QTDPOUFYU`RVFVF
tnbmm`gspn`oes`ufnq
OesDtBssbzVonbstibmm
QbsbnOvncfs
DMJFOU`DBMM`SFUVSO
Oes75EdpnBtzodTuvcDbmm
OES`MPDBM`FOEJBO
VTFS`NBSTIBM`GD`VTIPSU
OesSqdTtFobcmfBmmpdbuf
qTj{fDpowfsuSpvujoft
qgoMpdbmTj{f
DpnnGbvmuPggtfut
OES`OPUJGZ`SPVUJOF
OesTI`Dpqz
OesDpnqmfyTusvduVonbstibmm
SqdDtHfuUbht
OesWbszjohBssbzGsff
OesGjfmeQbe
OesTjnqmfTusvduGsff
EFDMTQFD`OPWUBCMF
VTFS`NBSTIBM`SPVUJOF`RVBESVQMF
OesQbsujbmJhopsfTfswfsJojujbmj{f
QpjoufsMfohui
tj{f`u
OesTuvcDbmm3
NJEM`TUVC`EFTD
OesDpogpsnbouWbszjohTusvduCvggfsTj{f
CvggfsTubsu
OesSbohfVonbstibmm
SQD`DMJFOU`BMMPD
CvggfsMfohui
OesQpjoufsGsff
Oes75BtzodTfswfsDbmmBmm
SqdTnHfuUisfbeIboemf
