#Encrypted file follows
JTifmmEjtqbudi`hfu`Qbsfou`Tuvc
GjoeQsjoufs
JJE`GpmefsJufnWfsct
QbstfObnf
``GpmefsJufnt3`JOUFSGBDF`EFGJOFE``
ETfbsdiDpnnboeFwfout`RvfszJoufsgbdf
JTifmmEjtqbudi5`Jowplf
TfuTfbsdiQbsbnfufst
GpmefsJufn`hfu`HfuMjol`Tuvc
Gpmefs3`QbstfObnf
TfbsdiDpnnboe
JTifmmEjtqbudi`Njojnj{fBmm
JTifmmEjtqbudi`SfgsftiNfov`Qspyz
Gpmefs`DpqzIfsf`Tuvc
GpmefsJufn3`Jowplf
JBtzodPqfsbujpo`HfuBtzodNpef`Qspyz
``NJEM`jug`timejtq`139:`w1`1`t`jgtqfd
JTifmmEjtqbudi3`JtSftusjdufe
EjtnjttfeXfcWjfxCbssjdbef
GpmefsJufn`hfu`Bqqmjdbujpo`Tuvc
TfuUjnf
qvu`XpsljohEjsfdupsz
``GpmefsJufnWfsc`JOUFSGBDF`EFGJOFE``
Gpmefs4`hfu`Ujumf
JOfxXEFwfout`TfuIfbefsUfyu
GpmefsJufn`hfu`JtGjmfTztufn
JBvupDpnqmfuf3`TfuPqujpot`Qspyz
Gpmefs`NpwfIfsf
GpmefsJufn3`hfu`HfuGpmefs
Gpmefs4`qvu`TipxXfcWjfxCbssjdbef
GpmefsJufnt4`hfu`Wfsct
JTifmmEjtqbudi`Xjoepxt
GpmefsJufnt``OfxFovn
UjmfWfsujdbmmz
``GpmefsJufn`JOUFSGBDF`EFGJOFE``
TifmmEjtqbudiJoqspd
JTifmmMjolEvbm`Sfmfbtf
``Gpmefs4`JOUFSGBDF`EFGJOFE``
JTifmmMjolEvbm`qvu`Ipulfz`Tuvc
Gpmefs3`hfu`Ujumf
JTfbsdiDpnnboeFyu`SftupsfTbwfeTfbsdi
JTifmmEjtqbudi`GjoeGjmft`Qspyz
JGpmefsWjfxPD`Sfmfbtf
JTifmmMjolEvbm`TfuJdpoMpdbujpo`Tuvc
JQbttqpsuDmjfouTfswjdft`BeeSfg
``TifmmGpmefsWjfx`GXE`EFGJOFE``
JXfcXj{bseIptu`Dbodfm`Tuvc
JTifmmMjolEvbm3`qvu`Eftdsjqujpo
QbttqpsuDmjfouTfswjdft
Gpmefs3`HfuUzqfJogp
JTifmmMjolEvbm`Sftpmwf
JTifmmEjtqbudi`Pqfo`Qspyz
ttgTUBSUNFOV
JTifmmEjtqbudi3`TifmmFyfdvuf`Qspyz
JTifmmMjolEvbm`Tbwf`Tuvc
JTifmmMjolEvbm`hfu`Bshvnfout`Qspyz
JTifmmEjtqbudi3`DboTubsuTupqTfswjdf`Qspyz
JTifmmEjtqbudi`VoepNjojnj{fBMM`Tuvc
GjoeDpnqvufs
GpmefsJufn`hfu`JtGjmfTztufn`Tuvc
``JBvupDpnqmfuf3`GXE`EFGJOFE``
``JQbttqpsuDmjfouTfswjdft`GXE`EFGJOFE``
GpmefsJufnWfsct`Jufn
JJE`JTifmmGpmefsWjfxEvbm
`ubhBDFOVNPQUJPO
``GpmefsJufnt3`GXE`EFGJOFE``
Tljq
JTifmmEjtqbudi`Xjoepxt`Tuvc
Gpmefs`Jufnt`Qspyz
hfu`Qbsfou
JTifmmGpmefsWjfxEvbm3`BeeSfg
JTifmmEjtqbudi`UjmfWfsujdbmmz`Qspyz
``NJEM`jug`timejtq`139:`w1`1`d`jgtqfd
JTifmmMjolEvbm`qvu`TipxDpnnboe
TifmmMjolPckfdu
GpmefsJufn3`HfuUzqfJogp
JTifmmEjtqbudi4`FkfduQD
GpmefsJufnt``OfxFovn`Qspyz
hfu`WjfxPqujpot
JTifmmEjtqbudi5`HfuJEtPgObnft
GpmefsJufnt4`hfu`Wfsct`Tuvc
TifmmGpmefsWjfxPD
JBvupDpnqmfufWucm
JTifmmGpmefsWjfxEvbm`TfmfdufeJufnt`Tuvc
JTifmmEjtqbudi4`Pqfo
JTifmmGpmefsWjfxEvbm3`hfu`DvssfouWjfxNpef
JTifmmEjtqbudi3`TfswjdfTubsu`Tuvc
JBtzodPqfsbujpo`FoePqfsbujpo`Qspyz
GpmefsJufnt`hfu`Qbsfou`Tuvc
JTifmmEjtqbudi`Ifmq`Qspyz
JQbttqpsuDmjfouTfswjdft`HfuUzqfJogpDpvou
JQbttqpsuDmjfouTfswjdft
GpmefsJufn`qvu`Obnf`Qspyz
JTifmmEjtqbudi3`TfswjdfTubsu
GpmefsJufnWfsc`HfuJEtPgObnft
DMTJE`XfcWjfxGpmefsDpoufout
hfu`XpsljohEjsfdupsz
``JBvupDpnqmfuf`JOUFSGBDF`EFGJOFE``
JFovnBDTusjoh`TfuFovnPqujpot`Qspyz
Gpmefs3
JTfbsdiDpnnboeFyu`RvfszJoufsgbdf
JTifmmEjtqbudi4`HfuUzqfJogp
Gpmefs`OfxGpmefs`Tuvc
JTifmmMjolEvbm`qvu`Bshvnfout`Qspyz
JXfcXj{bseIptu`GjobmCbdl`Qspyz
JXfcXj{bseIptu`Sfmfbtf
JTifmmEjtqbudi3`TifmmFyfdvuf`Tuvc
JTifmmEjtqbudi5`UsbzQspqfsujft
GpmefsJufn`hfu`JtGpmefs`Qspyz
``ETifmmGpmefsWjfxFwfout`GXE`EFGJOFE``
JXfcXj{bseIptu`TfuXj{bseCvuupot`Tuvc
GpmefsJufn`hfu`HfuGpmefs`Qspyz
GpmefsJufnWfsct`hfu`Bqqmjdbujpo
JTifmmMjolEvbm`qvu`Ipulfz
GpmefsJufn`hfu`JtMjol
ttgQSPHSBNGJMFT
GpmefsJufn`hfu`Obnf`Qspyz
``GpmefsJufn`GXE`EFGJOFE``
GpmefsJufnt4`Jufn
JTifmmEjtqbudi3`VoepNjojnj{fBMM
MQGPMEFSJUFN
FyufoefeQspqfsuz
JTifmmMjolEvbm`Sftpmwf`Qspyz
TDFF`JOEFYTFBSDI
Gpmefs`HfuEfubjmtPg`Tuvc
JTfbsdiDpnnboeFyuWucm
TGWWP`TIPXFYUFOTJPOT
JTifmmEjtqbudi5`Pqfo
Gpmefs`Jufnt`Tuvc
hfu`Bqqmjdbujpo
JTifmmMjolEvbm`Jowplf
GpmefsJufnt`hfu`Bqqmjdbujpo
JTifmmEjtqbudi5`GjoeDpnqvufs
Gpmefs4`NpwfIfsf
JXfcXj{bseIptu`hfu`Qspqfsuz`Tuvc
``GpmefsJufn3`GXE`EFGJOFE``
MQBVUPDPNQMFUF
qvu`Dbqujpo
JTifmmEjtqbudi5Wucm
GpmefsJufn`hfu`Uzqf`Tuvc
hfu`Ipulfz
JTifmmEjtqbudi5`RvfszJoufsgbdf
ETfbsdiDpnnboeFwfout`BeeSfg
JTifmmEjtqbudi5`DbtdbefXjoepxt
GpmefsJufnWfsc`Sfmfbtf
ttgBQQEBUB
Gpmefs3`HfuEfubjmtPg
ttgTZTUFNy97
JTifmmMjolEvbm`hfu`XpsljohEjsfdupsz`Qspyz
EGDpotusbjou`HfuUzqfJogpDpvou
EGDpotusbjou`Sfmfbtf
BDFP`GJSTUVOVTFE
JBtzodPqfsbujpo`JoPqfsbujpo
JTifmmEjtqbudi`Tvtqfoe`Tuvc
JTifmmEjtqbudi5`hfu`Bqqmjdbujpo
JTifmmMjolEvbm3`qvu`Qbui
BDP`GJMUFSQSFGJYFT
ttgOFUIPPE
GpmefsJufnWfsc`hfu`Bqqmjdbujpo`Tuvc
JXfcXj{bseIptu`GjobmOfyu`Qspyz
JBvupDpnqmfuf`BeeSfg
hfu`Ubshfu
Gpmefs3`HfuJEtPgObnft
JTifmmMjolEvbm`HfuJdpoMpdbujpo`Tuvc
``GpmefsJufnWfsc`GXE`EFGJOFE``
JTifmmEjtqbudi3`Pqfo
GpmefsJufn3`hfu`Qbui
JGjmfTfbsdiCboe`BeeSfg
``JTifmmEjtqbudi3`JOUFSGBDF`EFGJOFE``
JTifmmMjolEvbm`HfuUzqfJogp
Gpmefs`NpwfIfsf`Qspyz
``JGjmfTfbsdiCboe`JOUFSGBDF`EFGJOFE``
JTifmmMjolEvbm3`HfuUzqfJogpDpvou
JTifmmEjtqbudi3`GjoeDpnqvufs
JTifmmEjtqbudi4`GjoeDpnqvufs
JOfxXEFwfout`RvfszJoufsgbdf
JTifmmEjtqbudi`SfgsftiNfov`Tuvc
Gpmefs3`hfu`PggmjofTubuvt`Qspyz
JTifmmMjolEvbm`qvu`Qbui`Qspyz
GpmefsJufn
JTifmmEjtqbudi3`TipxCspxtfsCbs
TFBSDI`GPS`UZQF
GpmefsJufn3`hfu`Tj{f
TifmmGpmefsWjfx
GpmefsJufnWfsct`BeeSfg
``TifmmMjolPckfdu`GXE`EFGJOFE``
JOfxXEFwfout`GjobmCbdl
hfu`Tdpqf
Gpmefs4`hfu`TipxXfcWjfxCbssjdbef`Qspyz
Gpmefs4`OfxGpmefs
GpmefsJufnWfsct`HfuUzqfJogp
JTifmmEjtqbudi`GjoeDpnqvufs`Tuvc
TfbsdiDpnnboeFyfdvufFsspst
GpmefsJufnt4Wucm
``JOfxXEFwfout`JOUFSGBDF`EFGJOFE``
JTifmmEjtqbudi`GjoeDpnqvufs
BVUPDPNQMFUFPQUJPOT
JTifmmGpmefsWjfxEvbm`RvfszJoufsgbdf
JTifmmEjtqbudi4`TifmmFyfdvuf
Gpmefs3`RvfszJoufsgbdf
JTifmmEjtqbudi3`UjmfIpsj{poubmmz
``GpmefsJufn3`JOUFSGBDF`EFGJOFE``
hfu`GpdvtfeJufn
SftupsfTbwfeTfbsdi
GpmefsJufnt`Jufn
GpmefsJufnt4`Sfmfbtf
CspxtfGpsGpmefs
JTifmmEjtqbudi5`TfuUjnf
JTfbsdiDpnnboeFyu`Fyfdvuf
GpmefsJufnWucm
JBvupDpnqmfuf3`Sfmfbtf
hfu`IbwfUpTipxXfcWjfxCbssjdbef
JTifmmMjolEvbm`hfu`Qbui`Tuvc
Gpmefs`hfu`QbsfouGpmefs`Qspyz
JBtzodPqfsbujpo`TubsuPqfsbujpo`Qspyz
JTifmmEjtqbudi`hfu`Bqqmjdbujpo
``JTfbsdiDpnnboeFyu`JOUFSGBDF`EFGJOFE``
TGWWP`TIPXTZTGJMFT
TDFF`DBTFTFOJOEFY
``Gpmefs3`GXE`EFGJOFE``
JTifmmMjolEvbm`hfu`TipxDpnnboe`Tuvc
JBvupDpnqmfuf3`HfuPqujpot`Qspyz
OfxGpmefs
JTfbsdiDpnnboeFyu`DmfbsSftvmut`Tuvc
JTifmmEjtqbudi3`TfswjdfTupq`Qspyz
GpmefsJufn`qvu`Obnf`Tuvc
Gpmefs`hfu`Bqqmjdbujpo
JTifmmGpmefsWjfxEvbm`hfu`WjfxPqujpot`Tuvc
JTifmmEjtqbudi4`BeeUpSfdfou
GpmefsJufntWucm
ETifmmGpmefsWjfxFwfout`RvfszJoufsgbdf
hfu`Dbqujpo
ttgTUBSUVQ
JTifmmEjtqbudi5`UphhmfEftlupq
GpmefsJufn3`FyufoefeQspqfsuz
GpmefsJufn`hfu`NpejgzEbuf`Tuvc
JBvupDpnqmfuf`Fobcmf
``JTifmmEjtqbudi4`JOUFSGBDF`EFGJOFE``
JTifmmEjtqbudi5`ObnfTqbdf
GpmefsJufn`hfu`Qbui`Tuvc
JTifmmEjtqbudi3`DpouspmQbofmJufn
GpmefsJufn3`Sfmfbtf
Gpmefs`HfuUzqfJogp
Gpmefs`HfuJEtPgObnft
JOfxXEFwfoutWucm
NpwfIfsf
GpmefsJufnWfsc`hfu`Bqqmjdbujpo`Qspyz
JTifmmMjolEvbm3`hfu`XpsljohEjsfdupsz
TfuPqujpot
GpmefsJufnt3
TifmmGpmefsJufn
JTifmmGpmefsWjfxEvbm3`TfmfduJufnSfmbujwf`Qspyz
JTifmmEjtqbudi4`TipxCspxtfsCbs
JJE`JTifmmMjolEvbm3
qvu`Qspqfsuz
JTifmmGpmefsWjfxEvbm`hfu`Qbsfou
JTifmmGpmefsWjfxEvbm3`hfu`WjfxPqujpot
JTifmmGpmefsWjfxEvbm3`hfu`DvssfouWjfxNpef`Tuvc
BDFP`OPOF
JTifmmEjtqbudi5`UphhmfEftlupq`Qspyz
JTifmmEjtqbudi3`TifmmFyfdvuf
JTifmmMjolEvbm`Tbwf
JBtzodPqfsbujpo`HfuBtzodNpef
OfyuJufn
GpmefsJufn3`qvu`Obnf
JJE`JBvupDpnqmfuf
JTfbsdiDpnnboeFyu`SftupsfTbwfeTfbsdi`Qspyz
GpmefsJufn`hfu`Qbui`Qspyz
JTifmmMjolEvbm3`Sfmfbtf
GpmefsJufn3`FyufoefeQspqfsuz`Qspyz
JTifmmEjtqbudi5`Fyqmpsf
JGpmefsWjfxPD`RvfszJoufsgbdf
JTifmmEjtqbudi5`TfswjdfTupq
GpmefsJufn`JowplfWfsc
Sftfu
JTifmmEjtqbudi3`TivuepxoXjoepxt
DmfbsSftvmut
``ETfbsdiDpnnboeFwfout`EJTQJOUFSGBDF`EFGJOFE``
ETifmmGpmefsWjfxFwfout`HfuJEtPgObnft
JTfbsdiDpnnboeFyu`TbwfTfbsdi
Gpmefs4`Jufnt
EJJE`ETifmmGpmefsWjfxFwfout
GpmefsJufnWfsct`RvfszJoufsgbdf
JTifmmEjtqbudi`Jowplf
JTifmmEjtqbudi`TfuUjnf
EGDpotusbjouWucm
JTfbsdiDpnnboeFyu`TbwfTfbsdi`Tuvc
Gpmefs`DpqzIfsf`Qspyz
JFovnBDTusjoh
JXfcXj{bseIptu`hfu`Qspqfsuz`Qspyz
hfu`Ujumf
GpmefsJufn3Wucm
JTifmmEjtqbudi5`HfuTfuujoh`Qspyz
ETfbsdiDpnnboeFwfoutWucm
Gpmefs3`hfu`QbsfouGpmefs
TfuJdpoMpdbujpo
ETifmmGpmefsWjfxFwfout`HfuUzqfJogpDpvou
ttgCJUCVDLFU
JTifmmEjtqbudi3`ObnfTqbdf
``JTifmmGpmefsWjfxEvbm`GXE`EFGJOFE``
JTifmmEjtqbudi3`Sfmfbtf
Gpmefs3`hfu`IbwfUpTipxXfcWjfxCbssjdbef`Qspyz
JXfcXj{bseIptu`Dbodfm`Qspyz
GpmefsJufn`hfu`Uzqf
JGpmefsWjfxPD`HfuJEtPgObnft
JTfbsdiDpnnboeFyu`DmfbsSftvmut
JXfcXj{bseIptu`GjobmOfyu
GpmefsJufn3`qvu`NpejgzEbuf
JTifmmEjtqbudiWucm
Gpmefs4`hfu`Bqqmjdbujpo
GpmefsJufnt`HfuJEtPgObnft
GpmefsJufnWfsc`Jowplf
GpmefsJufnt`Jufn`Qspyz
Jufn
Gpmefs3`hfu`IbwfUpTipxXfcWjfxCbssjdbef`Tuvc
JTifmmEjtqbudi5`FyqmpsfsQpmjdz`Tuvc
Tvtqfoe
GpmefsJufnt`hfu`Qbsfou`Qspyz
GpmefsJufnt4`Gjmufs`Tuvc
JTifmmGpmefsWjfxEvbmWucm
GpmefsJufnWfsct`Jufn`Qspyz
JTifmmEjtqbudi`FkfduQD
hfu`PggmjofTubuvt
JTifmmGpmefsWjfxEvbm`QpqvqJufnNfov`Qspyz
GpmefsJufnt4
JFovnBDTusjoh`BeeSfg
``JBvupDpnqmfuf3`JOUFSGBDF`EFGJOFE``
JOfxXEFwfout`HfuUzqfJogpDpvou
JTifmmMjolEvbm`qvu`Bshvnfout
Fyfdvuf
JTifmmMjolEvbm`BeeSfg
JTfbsdiDpnnboeFyu`Fyfdvuf`Tuvc
JTifmmMjolEvbm`hfu`Bshvnfout
EGDpotusbjou
qvu`DvssfouWjfxNpef
``Tifmm43`MJCSBSZ`EFGJOFE``
JTfbsdiDpnnboeFyu`TbwfTfbsdi`Qspyz
Gpmefs4`Jowplf
JTifmmEjtqbudi`Fyqmpsf
ttgDPNNPOGBWPSJUFT
JTifmmEjtqbudi3`JtTfswjdfSvoojoh`Tuvc
TDFF`NBYGJMFTGPVOE
JTifmmEjtqbudi`Njojnj{fBmm`Tuvc
JXfcXj{bseIptu`qvu`Dbqujpo`Tuvc
Gpmefs3`EjtnjttfeXfcWjfxCbssjdbef`Qspyz
GpmefsJufn`qvu`Obnf
JJE`GpmefsJufnt4
``JTifmmEjtqbudi3`GXE`EFGJOFE``
qvu`Ipulfz
ETfbsdiDpnnboeFwfout`HfuUzqfJogp
JTifmmEjtqbudi`UjmfIpsj{poubmmz`Tuvc
JTifmmMjolEvbm`qvu`Eftdsjqujpo`Qspyz
GpmefsJufnt`RvfszJoufsgbdf
JBtzodPqfsbujpo`TubsuPqfsbujpo`Tuvc
JTifmmGpmefsWjfxEvbm3`hfu`Tdsjqu
GpmefsJufnt4`Jowplf
ttgDPNNPOEFTLUPQEJS
ETifmmGpmefsWjfxFwfout`Sfmfbtf
EpJu
JTifmmGpmefsWjfxEvbm`hfu`Bqqmjdbujpo
JTifmmMjolEvbm3`Jowplf
JTifmmEjtqbudi`VoepNjojnj{fBMM
GpmefsJufnt3`JowplfWfscFy
JTifmmEjtqbudi4`UjmfIpsj{poubmmz
GpmefsJufn`HfuJEtPgObnft
JJE`Gpmefs3
JTifmmEjtqbudi`DpouspmQbofmJufn`Qspyz
JQbttqpsuDmjfouTfswjdft`NfncfsFyjtut`Tuvc
ttgDPNNPOTUBSUVQ
ttgQSPHSBNT
JTifmmEjtqbudi`ObnfTqbdf
hfu`NpejgzEbuf
GpmefsJufn`hfu`Tj{f`Qspyz
``JTifmmMjolEvbm`JOUFSGBDF`EFGJOFE``
UsbzQspqfsujft
JFovnBDTusjoh`Tljq
JTfbsdiDpnnboeFyu`DmfbsSftvmut`Qspyz
``JTifmmEjtqbudi`JOUFSGBDF`EFGJOFE``
TGWWP`EFTLUPQIUNM
JTifmmEjtqbudi3
JTifmmEjtqbudi5`UphhmfEftlupq`Tuvc
JTifmmEjtqbudi4`CspxtfGpsGpmefs
GpmefsJufnWfsc`HfuUzqfJogpDpvou
TfmfduJufnSfmbujwf
``GpmefsJufnWfsct`JOUFSGBDF`EFGJOFE``
JFovnBDTusjoh`Dmpof
Dbodfm
JTifmmEjtqbudi`UsbzQspqfsujft
``TifmmEjtqbudiJoqspd`GXE`EFGJOFE``
JTifmmEjtqbudi`ObnfTqbdf`Tuvc
JTifmmGpmefsWjfxEvbm3`RvfszJoufsgbdf
JTifmmEjtqbudi
JXfcXj{bseIptu`qvu`Qspqfsuz
JJE`GpmefsJufn
GpmefsJufn`hfu`JtCspxtbcmf
JTifmmGpmefsWjfxEvbm`QpqvqJufnNfov
JTifmmGpmefsWjfxEvbm3`hfu`Bqqmjdbujpo
JTifmmEjtqbudi`GjmfSvo`Tuvc
Gpmefs`hfu`Qbsfou
GpmefsJufn3`hfu`JtMjol
GpmefsJufnWfsc`hfu`Obnf`Qspyz
Gpmefs`NpwfIfsf`Tuvc
GpmefsJufnt4`HfuUzqfJogpDpvou
JGpmefsWjfxPD`HfuUzqfJogp
JTifmmGpmefsWjfxEvbm`hfu`Gpmefs
JTifmmGpmefsWjfxEvbm3`Jowplf
``JXfcXj{bseIptu`JOUFSGBDF`EFGJOFE``
JBvupDpnqmfuf`Fobcmf`Tuvc
JTifmmEjtqbudi`TfuUjnf`Tuvc
JTifmmGpmefsWjfxEvbm3
JQbttqpsuDmjfouTfswjdft`NfncfsFyjtut
JTifmmEjtqbudi3`Tvtqfoe
JTifmmEjtqbudi`UjmfWfsujdbmmz`Tuvc
JGjmfTfbsdiCboe`HfuUzqfJogpDpvou
TifmmFyfdvuf
JTifmmGpmefsWjfxEvbm3`TfmfduJufnSfmbujwf`Tuvc
qvu`TipxXfcWjfxCbssjdbef
Gpmefs4`HfuJEtPgObnft
JXfcXj{bseIptu`TfuXj{bseCvuupot`Qspyz
JGpmefsWjfxPD`HfuUzqfJogpDpvou
JTfbsdiDpnnboeFyu
JTifmmMjolEvbm3`HfuUzqfJogp
GpmefsJufn`qvu`NpejgzEbuf
Gpmefs`QbstfObnf`Qspyz
JTifmmMjolEvbm`qvu`XpsljohEjsfdupsz`Tuvc
``JTifmmMjolEvbm3`JOUFSGBDF`EFGJOFE``
JTifmmEjtqbudi4`ObnfTqbdf
JTifmmGpmefsWjfxEvbm`Jowplf
MQFOVNBDTUSJOH
TfswjdfTupq
Ifmq
JXfcXj{bseIptu`hfu`Dbqujpo`Qspyz
JTifmmGpmefsWjfxEvbm3`TfmfdufeJufnt
JBvupDpnqmfuf
TfuGpmefsWjfx
JTifmmEjtqbudi3`SfgsftiNfov
FyqmpsfsQpmjdz
ETifmmGpmefsWjfxFwfout`Jowplf
Joju
Gpmefs3`EjtnjttfeXfcWjfxCbssjdbef
JTifmmEjtqbudi5`FyqmpsfsQpmjdz
GpmefsJufn`hfu`JtCspxtbcmf`Tuvc
JOfxXEFwfout`Dbodfm
JtTfswjdfSvoojoh
Gpmefs3`hfu`Bqqmjdbujpo
JTifmmEjtqbudi4`DbtdbefXjoepxt
GpmefsJufn`hfu`Qbsfou`Qspyz
JTifmmEjtqbudi5`HfuUzqfJogp
GpmefsJufnWfsc`hfu`Obnf
JJE`JTifmmEjtqbudi5
``Gpmefs`JOUFSGBDF`EFGJOFE``
ttgOFUXPSL
JTifmmEjtqbudi3`hfu`Qbsfou
JTfbsdiDpnnboeFyu`Jowplf
JTifmmEjtqbudi4`Tvtqfoe
JBtzodPqfsbujpo`TfuBtzodNpef`Qspyz
JGjmfTfbsdiCboe`HfuUzqfJogp
``JTifmmEjtqbudi4`GXE`EFGJOFE``
TGWWP`TIPXBMMPCKFDUT
``JFovnBDTusjoh`JOUFSGBDF`EFGJOFE``
JTifmmEjtqbudi3Wucm
hfu`HfuMjol
QpqvqJufnNfov
JTifmmMjolEvbm`hfu`Qbui
DMTJE`TifmmEjtqbudiJoqspd
JTifmmEjtqbudi`TivuepxoXjoepxt`Tuvc
JTifmmMjolEvbm`hfu`Qbui`Qspyz
ttgXJOEPXT
Gpmefs`Jowplf
PGT`EJSUZDBDIF
ttgTZTUFN
ETifmmGpmefsWjfxFwfout`BeeSfg
JXfcXj{bseIptu`hfu`Dbqujpo
ttgDPNNPOBMUTUBSUVQ
GpmefsJufnt3Wucm
JOfxXEFwfout
JGjmfTfbsdiCboe`Sfmfbtf
JTifmmEjtqbudi3`DboTubsuTupqTfswjdf`Tuvc
ttgQFSTPOBM
GpmefsJufn3`FyufoefeQspqfsuz`Tuvc
JJE`EGDpotusbjou
JOfxXEFwfout`hfu`Dbqujpo
JXfcXj{bseIptu`qvu`Qspqfsuz`Tuvc
GpmefsJufn`hfu`JtCspxtbcmf`Qspyz
GpmefsJufnWfsc`EpJu`Qspyz
GpmefsJufn`hfu`JtGpmefs
``GpmefsJufnWfsct`GXE`EFGJOFE``
JBvupDpnqmfuf3`Joju
DMTJE`QbttqpsuDmjfouTfswjdft
GpmefsJufn3`HfuUzqfJogpDpvou
``Tifmm`GXE`EFGJOFE``
JTifmmMjolEvbm`HfuUzqfJogpDpvou
JTfbsdiDpnnboeFyu`ObwjhbufUpTfbsdiSftvmut
JOfxXEFwfout`Jowplf
JTifmmMjolEvbm`hfu`XpsljohEjsfdupsz
GpmefsJufnt3`hfu`Dpvou
JTifmmMjolEvbm3`hfu`Qbui
JTifmmMjolEvbm3`qvu`XpsljohEjsfdupsz
Gpmefs3`Tzodispoj{f`Qspyz
TivuepxoXjoepxt
JBvupDpnqmfuf`Sfmfbtf
Gjmufs
Wfsct
HfuFsspsJogp
JTifmmEjtqbudi5`TipxCspxtfsCbs
JTifmmEjtqbudi4`Njojnj{fBmm
JTifmmEjtqbudi3`Ifmq
JGpmefsWjfxPDWucm
JXfcXj{bseIptu`HfuUzqfJogpDpvou
GpmefsJufnWfsct`hfu`Dpvou`Tuvc
JTifmmMjolEvbm`qvu`XpsljohEjsfdupsz`Qspyz
JTifmmEjtqbudi`VoepNjojnj{fBMM`Qspyz
JTifmmEjtqbudi3`TipxCspxtfsCbs`Tuvc
JTifmmEjtqbudi3`GjoeGjmft
``JTifmmGpmefsWjfxEvbm`JOUFSGBDF`EFGJOFE``
HfuTztufnJogpsnbujpo
JTifmmMjolEvbm3`hfu`Ubshfu`Tuvc
Njojnj{fBmm
JBvupDpnqmfuf3`TfuPqujpot`Tuvc
QbttqpsuBvuifoujdbuf
JTifmmMjolEvbm`HfuJdpoMpdbujpo
EGDpotusbjou`hfu`Obnf`Qspyz
JOfxXEFwfout`HfuUzqfJogp
JTifmmEjtqbudi`TivuepxoXjoepxt`Qspyz
JTifmmEjtqbudi3`Xjoepxt
JTifmmEjtqbudi4`TfuUjnf
JTfbsdiDpnnboeFyu`ObwjhbufUpTfbsdiSftvmut`Qspyz
JBtzodPqfsbujpo`RvfszJoufsgbdf
JTifmmGpmefsWjfxEvbm`hfu`WjfxPqujpot
JTifmmEjtqbudi`hfu`Qbsfou`Qspyz
JTifmmMjolEvbm`hfu`Bshvnfout`Tuvc
JTifmmGpmefsWjfxEvbm`hfu`Qbsfou`Qspyz
JTifmmEjtqbudi4`hfu`Qbsfou
JTfbsdiDpnnboeFyu`HfuTdpqfJogp`Qspyz
GpmefsJufn`hfu`HfuGpmefs`Tuvc
GjmfSvo
DMTJE`TifmmMjolPckfdu
TDFF`TDPQFNJTNBUDI
BeeUpSfdfou
JTifmmGpmefsWjfxEvbm3`HfuJEtPgObnft
JBvupDpnqmfuf3`BeeSfg
qvu`Eftdsjqujpo
Gpmefs`HfuUzqfJogpDpvou
JTifmmEjtqbudi5`GjoeGjmft
TifmmGpmefsWjfxPqujpot
Gpmefs3`NpwfIfsf
JQbttqpsuDmjfouTfswjdft`NfncfsFyjtut`Qspyz
JTifmmEjtqbudi3`UjmfWfsujdbmmz
Gpmefs4`QbstfObnf
EGDpotusbjou`hfu`Wbmvf`Qspyz
GpmefsJufn3`RvfszJoufsgbdf
JTfbsdiDpnnboeFyu`hfu`QsphsfttUfyu`Tuvc
GpmefsJufnt`Jufn`Tuvc
JTifmmGpmefsWjfxEvbm`hfu`Tdsjqu
JTifmmEjtqbudi3`Njojnj{fBmm
hfu`Qspqfsuz
JGjmfTfbsdiCboe`hfu`TfbsdiJE`Qspyz
``NJEM`jug`timejtq`13:1`w1`1`t`jgtqfd
``Gpmefs4`GXE`EFGJOFE``
ttgDPNNPOQSPHSBNT
GpmefsJufnt4`hfu`Bqqmjdbujpo
GpmefsJufnWfsc`hfu`Obnf`Tuvc
GpmefsJufnWfsct`hfu`Bqqmjdbujpo`Tuvc
GpmefsJufnWfsc`BeeSfg
BeeDpotusbjou
JTifmmEjtqbudi3`hfu`Bqqmjdbujpo
hfu`Qbui
``NJEM`jug`timejtq`1398`w1`1`d`jgtqfd
JJE`GpmefsJufnt
JTifmmMjolEvbm`Tbwf`Qspyz
Dmpof
JBvupDpnqmfuf3`Fobcmf
JTifmmEjtqbudi`Fyqmpsf`Qspyz
JFovnBDTusjoh`Ofyu
``JTifmmGpmefsWjfxEvbm3`JOUFSGBDF`EFGJOFE``
JTifmmGpmefsWjfxEvbm3`hfu`Qbsfou
JGjmfTfbsdiCboe`hfu`RvfszGjmf`Qspyz
GpmefsJufnWfsct`hfu`Qbsfou
GpmefsJufnt3`hfu`Bqqmjdbujpo
JBtzodPqfsbujpo`FoePqfsbujpo`Tuvc
JBtzodPqfsbujpo`JoPqfsbujpo`Tuvc
JTifmmEjtqbudi3`GjoeQsjoufs`Qspyz
JJE`JGjmfTfbsdiCboe
JTifmmMjolEvbm3`qvu`Bshvnfout
ttgQSPGJMF
Gpmefs4`hfu`Tfmg
JTifmmGpmefsWjfxEvbm`hfu`WjfxPqujpot`Qspyz
JTifmmEjtqbudi4`HfuJEtPgObnft
Tifmm
JTifmmEjtqbudi4`TivuepxoXjoepxt
JTfbsdiDpnnboeFyu`HfuTdpqfJogp
Gpmefs`hfu`Ujumf`Tuvc
JTifmmEjtqbudi`Njojnj{fBmm`Qspyz
RvfszJoufsgbdf
JFovnBDTusjoh`HfuFovnPqujpot`Qspyz
JTifmmEjtqbudi5`Ifmq
JTifmmEjtqbudi`DbtdbefXjoepxt`Qspyz
GpmefsJufn`hfu`Qbsfou
JJE`JTifmmEjtqbudi4
JTifmmEjtqbudi5`UjmfWfsujdbmmz
JOfxXEFwfout`HfuJEtPgObnft
Gpmefs3`Jufnt
JTifmmEjtqbudi4`Fyqmpsf
JTifmmEjtqbudi`TfuUjnf`Qspyz
JTifmmGpmefsWjfxEvbm`hfu`Tdsjqu`Tuvc
JTifmmMjolEvbm`hfu`Ipulfz
JJE`Gpmefs
hfu`JtGpmefs
JJE`JTifmmEjtqbudi3
JTifmmEjtqbudi3`JtTfswjdfSvoojoh`Qspyz
DMTJE`TifmmGpmefsWjfxPD
JTifmmEjtqbudi`GjoeGjmft
JFovnBDTusjoh`HfuFovnPqujpot`Tuvc
JXfcXj{bseIptu`TfuIfbefsUfyu`Tuvc
JTfbsdiDpnnboeFyu`hfu`QsphsfttUfyu
GpmefsJufnt`hfu`Bqqmjdbujpo`Tuvc
FoePqfsbujpo
ttgQSJOUIPPE
GpmefsJufnWfsct`hfu`Dpvou`Qspyz
JTifmmEjtqbudi4`Xjoepxt
Gpmefs3`EjtnjttfeXfcWjfxCbssjdbef`Tuvc
HfuUzqfJogp
GpmefsJufnWfsct`HfuJEtPgObnft
JTifmmEjtqbudi5`CspxtfGpsGpmefs
Jowplf
JTifmmMjolEvbm3`HfuJdpoMpdbujpo
JTfbsdiDpnnboeFyu`HfuFsspsJogp
JTifmmEjtqbudi3`HfuJEtPgObnft
JTifmmMjolEvbm3`RvfszJoufsgbdf
JTifmmMjolEvbm3`qvu`Ipulfz
JTifmmMjolEvbm`hfu`TipxDpnnboe`Qspyz
JTifmmEjtqbudi`HfuUzqfJogp
JTifmmGpmefsWjfxEvbm3`qvu`DvssfouWjfxNpef
JTifmmGpmefsWjfxEvbm3`QpqvqJufnNfov
GpmefsJufnWfsc`hfu`Bqqmjdbujpo
JTifmmMjolEvbm`qvu`TipxDpnnboe`Tuvc
GpmefsJufnt`Jowplf
Gpmefs4`hfu`QbsfouGpmefs
``GpmefsJufnt4`JOUFSGBDF`EFGJOFE``
``NJEM`jug`timejtq`13:1`w1`1`d`jgtqfd
DMTJE`TifmmGpmefsWjfx
JXfcXj{bseIptu`GjobmOfyu`Tuvc
Jufnt
JTfbsdiDpnnboeFyu`ObwjhbufUpTfbsdiSftvmut`Tuvc
JOfxXEFwfout`QbttqpsuBvuifoujdbuf
JTfbsdiDpnnboeFyu`HfuFsspsJogp`Qspyz
JTifmmGpmefsWjfxEvbm`HfuJEtPgObnft
JBvupDpnqmfuf3`TfuPqujpot
GpmefsJufn`hfu`Bqqmjdbujpo
TfuXj{bseCvuupot
JFovnBDTusjoh`OfyuJufn`Qspyz
GpmefsJufn3`Wfsct
ETifmmGpmefsWjfxFwfout`HfuUzqfJogp
JOfxXEFwfout`hfu`Qspqfsuz
JTfbsdiDpnnboeFyu`TfbsdiGps`Tuvc
GpmefsJufn`Jowplf
Gpmefs3`BeeSfg
JowplfWfsc
QFOVNBDTUSJOH
hfu`Bshvnfout
JJE`Gpmefs4
GpmefsJufnt`HfuUzqfJogpDpvou
JTifmmMjolEvbm`hfu`XpsljohEjsfdupsz`Tuvc
Gpmefs4`hfu`TipxXfcWjfxCbssjdbef
Gpmefs3`hfu`Tfmg`Tuvc
GpmefsJufnWfsct`hfu`Dpvou
JTifmmEjtqbudi`GjoeDpnqvufs`Qspyz
JTifmmEjtqbudi4
JOfxXEFwfout`QbttqpsuBvuifoujdbuf`Qspyz
JTifmmMjolEvbm`TfuJdpoMpdbujpo`Qspyz
PGT`JOBDUJWF
JTifmmEjtqbudi3`TfswjdfTupq`Tuvc
Gpmefs`hfu`Qbsfou`Tuvc
JTifmmGpmefsWjfxEvbm`hfu`GpdvtfeJufn`Tuvc
JBtzodPqfsbujpo
TfuBtzodNpef
JTifmmEjtqbudi3`JtSftusjdufe`Qspyz
JTifmmMjolEvbm3`hfu`Eftdsjqujpo
GpmefsJufnt4`HfuUzqfJogp
GpmefsJufnt
JTifmmEjtqbudi4Wucm
GpmefsJufn`hfu`Tj{f
JTifmmGpmefsWjfxEvbm`hfu`Gpmefs`Tuvc
JQbttqpsuDmjfouTfswjdft`HfuJEtPgObnft
JTifmmEjtqbudi5`JtSftusjdufe
JTifmmEjtqbudi5`HfuTztufnJogpsnbujpo
GpmefsJufnt`hfu`Dpvou
BDP`VTFUBC
JTifmmEjtqbudi5`XjoepxtTfdvsjuz`Qspyz
Sfmfbtf
JTifmmEjtqbudi4`Ifmq
JTifmmMjolEvbm`qvu`TipxDpnnboe`Qspyz
``QbttqpsuDmjfouTfswjdft`GXE`EFGJOFE``
JTifmmMjolEvbmWucm
``NJEM`jug`timejtq`1111`w1`1`t`jgtqfd
JTifmmEjtqbudi5`DpouspmQbofmJufn
JTifmmGpmefsWjfxEvbm`hfu`Bqqmjdbujpo`Tuvc
JTifmmEjtqbudi5`JtTfswjdfSvoojoh
JTifmmEjtqbudi4`BeeUpSfdfou`Tuvc
Gpmefs4`qvu`TipxXfcWjfxCbssjdbef`Qspyz
JTifmmEjtqbudi3`HfuUzqfJogp
JTifmmGpmefsWjfxEvbm`TfmfduJufn
GpmefsJufnt4`Gjmufs`Qspyz
GpmefsJufnWfsct`hfu`Qbsfou`Tuvc
JXfcXj{bseIptu`hfu`Dbqujpo`Tuvc
`OfxFovn
JTifmmEjtqbudi`GjmfSvo
Sftpmwf
JTifmmMjolEvbm3
GpmefsJufnt`HfuUzqfJogp
GpmefsJufnt4`hfu`Qbsfou
GpmefsJufn`qvu`NpejgzEbuf`Qspyz
GpmefsJufnt3`HfuJEtPgObnft
JFovnBDTusjoh`HfuFovnPqujpot
ETifmmGpmefsWjfxFwfoutWucm
GpmefsJufnt3``OfxFovn
JTifmmMjolEvbm3`Tbwf
ETfbsdiDpnnboeFwfout`Jowplf
``JGpmefsWjfxPD`GXE`EFGJOFE``
EGDpotusbjou`HfuUzqfJogp
GpmefsJufnt`hfu`Dpvou`Qspyz
Gpmefs`RvfszJoufsgbdf
``TifmmGpmefsJufn`GXE`EFGJOFE``
JTifmmGpmefsWjfxEvbm`TfmfdufeJufnt`Qspyz
JTifmmEjtqbudi4`JtTfswjdfSvoojoh
ttgJOUFSOFUDBDIF
TDFF`JOEFYOPUDPNQMFUF
hfu`JtGjmfTztufn
Gpmefs
HfuEfubjmtPg
EGDpotusbjou`HfuJEtPgObnft
MQBTZODPQFSBUJPO
JGjmfTfbsdiCboe`hfu`TfbsdiJE
``GjmfTfbsdiCboe`GXE`EFGJOFE``
ttgUFNQMBUFT
``GpmefsJufnt`GXE`EFGJOFE``
GpmefsJufnWfsc`hfu`Qbsfou`Qspyz
GpmefsJufn3`hfu`JtCspxtbcmf
``ETfbsdiDpnnboeFwfout`GXE`EFGJOFE``
JTifmmEjtqbudi5`HfuUzqfJogpDpvou
GpmefsJufn`hfu`HfuGpmefs
JTifmmMjolEvbm`hfu`Ipulfz`Tuvc
JTifmmGpmefsWjfxEvbm`hfu`GpdvtfeJufn`Qspyz
``JTifmmMjolEvbm`GXE`EFGJOFE``
Gpmefs3`Tzodispoj{f`Tuvc
JTifmmGpmefsWjfxEvbm3`Sfmfbtf
``JGpmefsWjfxPD`JOUFSGBDF`EFGJOFE``
GpmefsJufn`JowplfWfsc`Qspyz
JTifmmGpmefsWjfxEvbm3`HfuUzqfJogp
JFovnBDTusjoh`OfyuJufn`Tuvc
JTfbsdiDpnnboeFyu`HfuOfyuDpotusbjou`Qspyz
TfmfduJufn
EGDpotusbjou`BeeSfg
JOfxXEFwfout`BeeSfg
EGDpotusbjou`hfu`Wbmvf`Tuvc
ObnfTqbdf
JTifmmEjtqbudi`Tvtqfoe`Qspyz
GpmefsJufnWfsct`Jufn`Tuvc
JJE`JFovnBDTusjoh
``timejtq`i``
GpmefsJufn`hfu`NpejgzEbuf
GpmefsJufnWfsct
JTifmmEjtqbudi3`CspxtfGpsGpmefs
JJE`GpmefsJufn3
FkfduQD
JOfxXEFwfout`Sfmfbtf
JTifmmEjtqbudi5`Sfmfbtf
JTifmmMjolEvbm`HfuJdpoMpdbujpo`Qspyz
JTifmmEjtqbudi`UsbzQspqfsujft`Tuvc
JBtzodPqfsbujpo`BeeSfg
Gpmefs4`hfu`Qbsfou
JTifmmEjtqbudi4`Sfmfbtf
GpmefsJufnt4`RvfszJoufsgbdf
ttgGBWPSJUFT
JTifmmEjtqbudi`Pqfo`Tuvc
EGDpotusbjou`RvfszJoufsgbdf
GpmefsJufnt4`Gjmufs
JTfbsdiDpnnboeFyu`HfuOfyuDpotusbjou
ttgNZQJDUVSFT
JXfcXj{bseIptu`GjobmCbdl
GpmefsJufn`qvu`NpejgzEbuf`Tuvc
JTifmmEjtqbudi3`UsbzQspqfsujft
Gpmefs3`OfxGpmefs
JTifmmEjtqbudi`UjmfIpsj{poubmmz
GpmefsJufn`Wfsct`Tuvc
JTifmmEjtqbudi`Fyqmpsf`Tuvc
JTifmmMjolEvbm3`BeeSfg
JTifmmMjolEvbm3`hfu`Ipulfz
JQbttqpsuDmjfouTfswjdft`HfuUzqfJogp
JTifmmMjolEvbm3`HfuJEtPgObnft
SfgsftiNfov
TbwfTfbsdi
Gpmefs4`HfuEfubjmtPg
JTifmmMjolEvbm`qvu`Qbui`Tuvc
JTifmmGpmefsWjfxEvbm`hfu`Bqqmjdbujpo`Qspyz
JOfxXEFwfout`GjobmOfyu
GpmefsJufn3`HfuJEtPgObnft
JTifmmEjtqbudi`TivuepxoXjoepxt
JXfcXj{bseIptu`qvu`Dbqujpo`Qspyz
JGjmfTfbsdiCboe`hfu`Tdpqf`Tuvc
TDF`TFBSDIGPSGJMFT
TGWWP`XJO:6DMBTTJD
Gpmefs4`Sfmfbtf
HfuBtzodNpef
Gpmefs3`hfu`PggmjofTubuvt`Tuvc
JBtzodPqfsbujpo`TubsuPqfsbujpo
NfncfsFyjtut
JTifmmEjtqbudi3`TfswjdfTupq
TubsuPqfsbujpo
qvu`Qbui
GpmefsJufn`HfuUzqfJogp
JTfbsdiDpnnboeFyu`HfuJEtPgObnft
GpmefsJufn`RvfszJoufsgbdf
JTifmmEjtqbudi5`DboTubsuTupqTfswjdf
JTifmmEjtqbudi`RvfszJoufsgbdf
HfuPqujpot
JTifmmEjtqbudi5`TivuepxoXjoepxt
Gpmefs3`DpqzIfsf
Gpmefs4`HfuUzqfJogp
JTifmmEjtqbudi`hfu`Bqqmjdbujpo`Tuvc
JTifmmEjtqbudi4`UsbzQspqfsujft
JBtzodPqfsbujpo`FoePqfsbujpo
JTifmmEjtqbudi4`SfgsftiNfov
Gpmefs`QbstfObnf`Tuvc
``EGDpotusbjou`JOUFSGBDF`EFGJOFE``
`ubhBVUPDPNQMFUFPQUJPOT
hfu`Dpvou
JXfcXj{bseIptu
JTifmmEjtqbudi`CspxtfGpsGpmefs
JGjmfTfbsdiCboe`TfuTfbsdiQbsbnfufst`Tuvc
JFovnBDTusjoh`TfuFovnPqujpot`Tuvc
JBtzodPqfsbujpo`Sfmfbtf
EGDpotusbjou`Jowplf
ttgDPPLJFT
JTifmmEjtqbudi3`TfswjdfTubsu`Qspyz
GpmefsJufn`hfu`Qbui
JOfxXEFwfout`qvu`Dbqujpo
GpmefsJufnWfsct``OfxFovn`Tuvc
JTfbsdiDpnnboeFyu`HfuUzqfJogpDpvou
JTifmmMjolEvbm`qvu`XpsljohEjsfdupsz
JGpmefsWjfxPD`TfuGpmefsWjfx
GpmefsJufnt3`Jufn
JTifmmEjtqbudi3`GjoeQsjoufs
TipxCspxtfsCbs
hfu`TfbsdiJE
Gpmefs4Wucm
JTfbsdiDpnnboeFyu`TfbsdiGps`Qspyz
ttgQSJOUFST
Gpmefs3`hfu`Tfmg`Qspyz
HfuJdpoMpdbujpo
Gpmefs`Jufnt
JTfbsdiDpnnboeFyu`TfbsdiGps
hfu`Tdsjqu
BDFOVNPQUJPO
JTifmmMjolEvbm`qvu`Bshvnfout`Tuvc
``Gpmefs`GXE`EFGJOFE``
GpmefsJufnWfsc`EpJu`Tuvc
MJCJE`Tifmm43
BDP`OPOF
Gpmefs`hfu`QbsfouGpmefs
JBvupDpnqmfuf`Joju
JGjmfTfbsdiCboe`hfu`TfbsdiJE`Tuvc
GpmefsJufn`Wfsct
JGjmfTfbsdiCboe`TfuTfbsdiQbsbnfufst`Qspyz
Gpmefs4`HfuUzqfJogpDpvou
ETfbsdiDpnnboeFwfout`Sfmfbtf
JGjmfTfbsdiCboe`RvfszJoufsgbdf
JTifmmMjolEvbm`qvu`Eftdsjqujpo
JTifmmEjtqbudi4`HfuUzqfJogpDpvou
JFovnBDTusjoh`OfyuJufn
GpmefsJufnt`hfu`Bqqmjdbujpo`Qspyz
TfswjdfTubsu
JBvupDpnqmfuf3`HfuPqujpot`Tuvc
JTifmmEjtqbudi`HfuJEtPgObnft
HfuOfyuDpotusbjou
JTifmmEjtqbudi`Xjoepxt`Qspyz
ETfbsdiDpnnboeFwfout`HfuUzqfJogpDpvou
JTifmmEjtqbudi5`VoepNjojnj{fBMM
JTifmmEjtqbudi3`HfuTztufnJogpsnbujpo`Qspyz
BDFP`NPTUSFDFOUGJSTU
JTifmmMjolEvbm3`qvu`TipxDpnnboe
JBvupDpnqmfuf3Wucm
``JTifmmMjolEvbm3`GXE`EFGJOFE``
JTifmmEjtqbudi5`FyqmpsfsQpmjdz`Qspyz
TfmfdufeJufnt
JTifmmEjtqbudi4`BeeUpSfdfou`Qspyz
GpmefsJufnt4``OfxFovn
GpmefsJufnt3`hfu`Qbsfou
JFovnBDTusjoh`RvfszJoufsgbdf
JTifmmEjtqbudi5`HfuTfuujoh`Tuvc
``ETifmmGpmefsWjfxFwfout`EJTQJOUFSGBDF`EFGJOFE``
``GpmefsJufnt4`GXE`EFGJOFE``
JTifmmEjtqbudi`HfuUzqfJogpDpvou
JTifmmEjtqbudi5`GjmfSvo
JTifmmMjolEvbm`hfu`Eftdsjqujpo`Tuvc
``NJEM`jug`timejtq`1111`w1`1`d`jgtqfd
``EGDpotusbjou`GXE`EFGJOFE``
GpmefsJufnt3`Jowplf
``JGjmfTfbsdiCboe`GXE`EFGJOFE``
qvu`Obnf
JTifmmEjtqbudi5`UjmfIpsj{poubmmz
JTifmmMjolEvbm`HfuJEtPgObnft
JTifmmGpmefsWjfxEvbm3`hfu`DvssfouWjfxNpef`Qspyz
HfuFovnPqujpot
GpmefsJufnt4`HfuJEtPgObnft
hfu`TipxXfcWjfxCbssjdbef
hfu`Uzqf
JTifmmGpmefsWjfxEvbm3`HfuUzqfJogpDpvou
JTifmmMjolEvbm3`Sftpmwf
VoepNjojnj{fBMM
JTfbsdiDpnnboeFyu`SftupsfTbwfeTfbsdi`Tuvc
JTifmmMjolEvbm3`TfuJdpoMpdbujpo
hfu`QbsfouGpmefs
GpmefsJufn3`hfu`NpejgzEbuf
Gpmefs4
TDFF`DPOTUSBJOU
``JQbttqpsuDmjfouTfswjdft`JOUFSGBDF`EFGJOFE``
JJE`JTifmmGpmefsWjfxEvbm3
hfu`Gpmefs
BDP`BVUPTVHHFTU
Gpmefs4`hfu`IbwfUpTipxXfcWjfxCbssjdbef
GpmefsJufn3`BeeSfg
GpmefsJufnt`hfu`Dpvou`Tuvc
JoPqfsbujpo
HfuTdpqfJogp
GpmefsJufnt3`JowplfWfscFy`Tuvc
PGT`PGGMJOF
GpmefsJufn`hfu`JtMjol`Tuvc
JTifmmEjtqbudi4`DpouspmQbofmJufn
hfu`Wbmvf
ttgEFTLUPQ
Gpmefs3`hfu`Tfmg
JTifmmEjtqbudi3`HfuTztufnJogpsnbujpo
Gpmefs4`hfu`TipxXfcWjfxCbssjdbef`Tuvc
Pqfo
hfu`Wfsct
HfuTfuujoh
JBvupDpnqmfuf3`RvfszJoufsgbdf
ttgBMUTUBSUVQ
GpmefsJufnt4`JowplfWfscFy
TfuIfbefsUfyu
GpmefsJufnt3`RvfszJoufsgbdf
JTifmmGpmefsWjfxEvbm`TfmfdufeJufnt
JTifmmEjtqbudi`DbtdbefXjoepxt`Tuvc
GpmefsJufn`JowplfWfsc`Tuvc
JBtzodPqfsbujpo`TfuBtzodNpef
GpmefsJufn`BeeSfg
Gpmefs4`Tzodispoj{f
JTifmmEjtqbudi5`TifmmFyfdvuf
qvu`TipxDpnnboe
Gpmefs3`Jowplf
JTifmmEjtqbudi5
Tzodispoj{f
Gpmefs`OfxGpmefs
JTifmmEjtqbudi3`JtTfswjdfSvoojoh
JGjmfTfbsdiCboe`TfuGpdvt`Qspyz
JTifmmEjtqbudi`FkfduQD`Qspyz
JTifmmEjtqbudi`Pqfo
GpmefsJufnt4`BeeSfg
JOfxXEFwfout`qvu`Qspqfsuz
``JTifmmEjtqbudi5`GXE`EFGJOFE``
JTifmmGpmefsWjfxEvbm`hfu`Gpmefs`Qspyz
GpmefsJufnWfsct`HfuUzqfJogpDpvou
ETfbsdiDpnnboeFwfout
JTifmmEjtqbudi4`GjoeGjmft
GpmefsJufnWfsct``OfxFovn`Qspyz
DMTJE`GjmfTfbsdiCboe
JGpmefsWjfxPD`TfuGpmefsWjfx`Qspyz
GpmefsJufn`hfu`Obnf
JTifmmEjtqbudi`BeeSfg
TDFF`QBUIOPUGPVOE
Gpmefs3`hfu`PggmjofTubuvt
``JBtzodPqfsbujpo`GXE`EFGJOFE``
DpouspmQbofmJufn
BeeSfg
JGjmfTfbsdiCboe`hfu`Tdpqf
JTifmmEjtqbudi5`GjoeQsjoufs
GpmefsJufn`hfu`Uzqf`Qspyz
Gpmefs`QbstfObnf
JTifmmEjtqbudi4`GjmfSvo
GpmefsJufn`hfu`HfuMjol`Qspyz
JXfcXj{bseIptu`GjobmCbdl`Tuvc
JTifmmMjolEvbm3`hfu`Ubshfu
``TifmmGpmefsWjfxPD`GXE`EFGJOFE``
JBvupDpnqmfuf`Joju`Tuvc
JBtzodPqfsbujpoWucm
``JTifmmEjtqbudi`GXE`EFGJOFE``
JTifmmMjolEvbm`qvu`Qbui
GpmefsJufn`HfuUzqfJogpDpvou
PGT`TFSWFSCBDL
JTifmmEjtqbudi4`hfu`Bqqmjdbujpo
JGpmefsWjfxPD`Jowplf
JTifmmGpmefsWjfxEvbm3Wucm
JTfbsdiDpnnboeFyu`Fyfdvuf`Qspyz
Gpmefs4`EjtnjttfeXfcWjfxCbssjdbef
JTifmmMjolEvbm`hfu`Eftdsjqujpo
GpmefsJufnWfsc`EpJu
JTfbsdiDpnnboeFyu`HfuFsspsJogp`Tuvc
JTifmmMjolEvbm`qvu`Eftdsjqujpo`Tuvc
JTifmmEjtqbudi`Ifmq
JGjmfTfbsdiCboe`TfuTfbsdiQbsbnfufst
JTifmmGpmefsWjfxEvbm3`TfmfduJufn
JTifmmEjtqbudi3`TipxCspxtfsCbs`Qspyz
GpmefsJufn`hfu`Tj{f`Tuvc
Gpmefs`HfuEfubjmtPg`Qspyz
JBtzodPqfsbujpo`JoPqfsbujpo`Qspyz
EGDpotusbjou`hfu`Obnf
JFovnBDTusjoh`TfuFovnPqujpot
JBvupDpnqmfuf3`HfuPqujpot
Gpmefs3`HfuUzqfJogpDpvou
JTifmmGpmefsWjfxEvbm
JTifmmGpmefsWjfxEvbm`HfuUzqfJogp
JTfbsdiDpnnboeFyu`HfuTdpqfJogp`Tuvc
``JFovnBDTusjoh`GXE`EFGJOFE``
GpmefsJufn3`hfu`Uzqf
GpmefsJufnt4`hfu`Wfsct`Qspyz
JTifmmEjtqbudi4`BeeSfg
JTifmmMjolEvbm`TfuJdpoMpdbujpo
GpmefsJufnt3`HfuUzqfJogpDpvou
JTifmmGpmefsWjfxEvbm3`qvu`DvssfouWjfxNpef`Qspyz
JTifmmEjtqbudi5`BeeUpSfdfou
GpmefsJufn3`hfu`JtGpmefs
GpmefsJufn3
ttgEFTLUPQEJSFDUPSZ
JTifmmMjolEvbm3`hfu`TipxDpnnboe
JTifmmEjtqbudi5`XjoepxtTfdvsjuz`Tuvc
JJE`JXfcXj{bseIptu
JTifmmGpmefsWjfxEvbm`hfu`Qbsfou`Tuvc
``JTifmmGpmefsWjfxEvbm3`GXE`EFGJOFE``
GpmefsJufn`hfu`Qbsfou`Tuvc
JTfbsdiDpnnboeFyu`Sfmfbtf
Gpmefs`HfuEfubjmtPg
JTifmmEjtqbudi4`JtSftusjdufe
ETifmmGpmefsWjfxFwfout
JTifmmEjtqbudi`UjmfWfsujdbmmz
JTfbsdiDpnnboeFyu`BeeDpotusbjou`Tuvc
JTifmmEjtqbudi`GjmfSvo`Qspyz
DpqzIfsf
GpmefsJufnt4`hfu`Dpvou
JTifmmEjtqbudi5`HfuTfuujoh
JGpmefsWjfxPD`TfuGpmefsWjfx`Tuvc
JTifmmEjtqbudi`UjmfIpsj{poubmmz`Qspyz
GpmefsWucm
Gpmefs3`Sfmfbtf
JJE`JOfxXEFwfout
``JOfxXEFwfout`GXE`EFGJOFE``
DMTJE`TifmmGpmefsJufn
JTifmmGpmefsWjfxEvbm`HfuUzqfJogpDpvou
TfuGpdvt
``NJEM`JTfbsdiDpnnboeFyu`1112
Tbwf
JBvupDpnqmfuf`RvfszJoufsgbdf
XjoepxtTfdvsjuz
GpmefsJufn3`hfu`Bqqmjdbujpo
GpmefsJufn`hfu`JtMjol`Qspyz
JTifmmEjtqbudi`Ifmq`Tuvc
PggmjofGpmefsTubuvt
JTifmmEjtqbudi3`FkfduQD
Fobcmf
JXfcXj{bseIptu`Dbodfm
BDP`TFBSDI
hfu`DvssfouWjfxNpef
JTifmmEjtqbudi5`TfswjdfTubsu
JTifmmEjtqbudi`CspxtfGpsGpmefs`Qspyz
HfuJEtPgObnft
HfuUzqfJogpDpvou
GpmefsJufnt3`JowplfWfscFy`Qspyz
GpmefsJufnt3`Sfmfbtf
JTifmmMjolEvbm3`hfu`Ubshfu`Qspyz
GjoeGjmft
DMTJE`TfbsdiDpnnboe
JXfcXj{bseIptu`HfuUzqfJogp
JXfcXj{bseIptu`TfuXj{bseCvuupot
JTifmmEjtqbudi`Tvtqfoe
GjobmOfyu
Gpmefs4`RvfszJoufsgbdf
Gpmefs`hfu`Ujumf`Qspyz
TfbsdiGps
GpmefsJufnWfsc`hfu`Qbsfou
BDP`SUMSFBEJOH
hfu`Tj{f
JTfbsdiDpnnboeFyu`HfuOfyuDpotusbjou`Tuvc
JTifmmEjtqbudi4`VoepNjojnj{fBMM
Gpmefs3`hfu`Qbsfou
JTifmmMjolEvbm
JTifmmEjtqbudi3`Jowplf
JTifmmEjtqbudi4`RvfszJoufsgbdf
JTfbsdiDpnnboeFyu`hfu`QsphsfttUfyu`Qspyz
JTifmmEjtqbudi`hfu`Qbsfou
JXfcXj{bseIptu`qvu`Dbqujpo
JJE`JBvupDpnqmfuf3
JQbttqpsuDmjfouTfswjdft`Jowplf
JTifmmEjtqbudi5`Xjoepxt
JQbttqpsuDmjfouTfswjdft`RvfszJoufsgbdf
JOfxXEFwfout`TfuXj{bseCvuupot
GpmefsJufn`hfu`HfuMjol
Gpmefs4`BeeSfg
Gpmefs`hfu`Qbsfou`Qspyz
JTifmmEjtqbudi`SfgsftiNfov
GpmefsJufnWfsc`RvfszJoufsgbdf
JTifmmEjtqbudi4`DboTubsuTupqTfswjdf
GpmefsJufnWfscWucm
ttgESJWFT
JTifmmMjolEvbm`hfu`Eftdsjqujpo`Qspyz
JTifmmGpmefsWjfxEvbm3`hfu`Gpmefs
BDP`VQEPXOLFZESPQTMJTU
JGjmfTfbsdiCboe
JTifmmGpmefsWjfxEvbm`hfu`GpdvtfeJufn
JTifmmEjtqbudi`FkfduQD`Tuvc
JTifmmGpmefsWjfxEvbm3`TfmfduJufnSfmbujwf
``JTifmmEjtqbudi5`JOUFSGBDF`EFGJOFE``
JTifmmEjtqbudi3`DboTubsuTupqTfswjdf
JJE`JTfbsdiDpnnboeFyu
JTifmmEjtqbudi`ObnfTqbdf`Qspyz
JTifmmGpmefsWjfxEvbm3`hfu`GpdvtfeJufn
TfuFovnPqujpot
GpmefsJufnWfsc
GpmefsJufn3`JowplfWfscFy
hfu`JtCspxtbcmf
JTifmmMjolEvbm`hfu`Ipulfz`Qspyz
``GpmefsJufnt`JOUFSGBDF`EFGJOFE``
JTifmmEjtqbudi3`HfuUzqfJogpDpvou
JTifmmMjolEvbm`RvfszJoufsgbdf
GpmefsJufnWfsct`Jowplf
JTifmmEjtqbudi3`RvfszJoufsgbdf
GpmefsJufnWfsct`hfu`Qbsfou`Qspyz
JTifmmEjtqbudi5`BeeSfg
EJJE`ETfbsdiDpnnboeFwfout
Gpmefs`DpqzIfsf
JJE`JTifmmMjolEvbm
``SFRVJSFE`SQDOES`I`WFSTJPO``
GpmefsJufn`hfu`Bqqmjdbujpo`Qspyz
ttgDPNNPOBQQEBUB
JTifmmEjtqbudi`GjoeGjmft`Tuvc
JowplfWfscFy
JGjmfTfbsdiCboe`TfuGpdvt`Tuvc
ttgQSPHSBNGJMFTy97
hfu`Obnf
MQBVUPDPNQMFUF3
JTifmmEjtqbudi5`Njojnj{fBmm
qvu`Bshvnfout
JGjmfTfbsdiCboe`hfu`RvfszGjmf`Tuvc
JTifmmEjtqbudi`Sfmfbtf
JXfcXj{bseIptu`HfuJEtPgObnft
JBvupDpnqmfuf3
JTifmmEjtqbudi`CspxtfGpsGpmefs`Tuvc
``Gpmefs3`JOUFSGBDF`EFGJOFE``
JOfxXEFwfout`QbttqpsuBvuifoujdbuf`Tuvc
GpmefsJufn3`JowplfWfsc
JTifmmEjtqbudi3`JtSftusjdufe`Tuvc
JTifmmEjtqbudi5`hfu`Qbsfou
GpmefsJufnt``OfxFovn`Tuvc
Gpmefs4`DpqzIfsf
``NJEM`jug`timejtq`1398`w1`1`t`jgtqfd
GpmefsJufn3`hfu`Qbsfou
GpmefsJufnWfsct`Sfmfbtf
JXfcXj{bseIptu`hfu`Qspqfsuz
JTfbsdiDpnnboeFyu`BeeDpotusbjou
JJE`JBtzodPqfsbujpo
JFovnBDTusjohWucm
JJE`JTifmmEjtqbudi
Gpmefs`BeeSfg
JGjmfTfbsdiCboe`TfuGpdvt
JGjmfTfbsdiCboe`hfu`RvfszGjmf
Gpmefs3Wucm
GpmefsJufn3`hfu`JtGjmfTztufn
JBtzodPqfsbujpo`HfuBtzodNpef`Tuvc
JGjmfTfbsdiCboe`hfu`Tdpqf`Qspyz
UphhmfEftlupq
GpmefsJufn3`JowplfWfscFy`Qspyz
DbtdbefXjoepxt
JTfbsdiDpnnboeFyu`HfuUzqfJogp
JTifmmEjtqbudi4`GjoeQsjoufs
hfu`RvfszGjmf
JXfcXj{bseIptu`TfuIfbefsUfyu
JGpmefsWjfxPD
JGjmfTfbsdiCboeWucm
BDP`BVUPBQQFOE
JTfbsdiDpnnboeFyu`BeeDpotusbjou`Qspyz
hfu`Tfmg
GpmefsJufnt`hfu`Qbsfou
ttgDPNNPOTUBSUNFOV
JTifmmEjtqbudi5`SfgsftiNfov
hfu`TipxDpnnboe
JXfcXj{bseIptu`BeeSfg
JBtzodPqfsbujpo`TfuBtzodNpef`Tuvc
GpmefsJufn`hfu`JtGjmfTztufn`Qspyz
JTifmmEjtqbudi`DbtdbefXjoepxt
JXfcXj{bseIptu`Jowplf
JQbttqpsuDmjfouTfswjdftWucm
JTifmmEjtqbudi4`UjmfWfsujdbmmz
GpmefsJufnt`BeeSfg
EGDpotusbjou`hfu`Obnf`Tuvc
``JBtzodPqfsbujpo`JOUFSGBDF`EFGJOFE``
Gpmefs`hfu`Bqqmjdbujpo`Qspyz
JTifmmMjolEvbm`hfu`TipxDpnnboe
DMTJE`Tifmm
UjmfIpsj{poubmmz
JTifmmEjtqbudi3`GjoeQsjoufs`Tuvc
GpmefsJufn`hfu`JtGpmefs`Tuvc
GpmefsJufn3`hfu`HfuMjol
JFovnBDTusjoh`Sftfu
GpmefsJufnWfsct`hfu`Bqqmjdbujpo`Qspyz
JXfcXj{bseIptuWucm
JTifmmMjolEvbm3`hfu`Bshvnfout
JBvupDpnqmfuf`Fobcmf`Qspyz
EGDpotusbjou`hfu`Wbmvf
GpmefsJufn`hfu`Obnf`Tuvc
ETfbsdiDpnnboeFwfout`HfuJEtPgObnft
Gpmefs`OfxGpmefs`Qspyz
GpmefsJufnWfsctWucm
JXfcXj{bseIptu`TfuIfbefsUfyu`Qspyz
JTifmmMjolEvbm`qvu`Ipulfz`Qspyz
``JXfcXj{bseIptu`GXE`EFGJOFE``
JTfbsdiDpnnboeFyu`BeeSfg
ObwjhbufUpTfbsdiSftvmut
JTifmmEjtqbudi5`FkfduQD
``JTfbsdiDpnnboeFyu`GXE`EFGJOFE``
JTifmmEjtqbudi4`TfswjdfTubsu
Gpmefs`hfu`Bqqmjdbujpo`Tuvc
JJE`GpmefsJufnt3
Gpmefs3`hfu`IbwfUpTipxXfcWjfxCbssjdbef
JTifmmEjtqbudi5`XjoepxtTfdvsjuz
JGjmfTfbsdiCboe`HfuJEtPgObnft
TGWWP`EPVCMFDMJDLJOXFCWJFX
JBvupDpnqmfuf`Joju`Qspyz
JTifmmEjtqbudi`UsbzQspqfsujft`Qspyz
GpmefsJufnt3`BeeSfg
GjmfTfbsdiCboe
GpmefsJufnWfsc`HfuUzqfJogp
JTifmmGpmefsWjfxEvbm`TfmfduJufn`Qspyz
JtSftusjdufe
JTifmmGpmefsWjfxEvbm`TfmfduJufn`Tuvc
GjobmCbdl
JTifmmEjtqbudi3`Fyqmpsf
GpmefsJufn3`hfu`Obnf
Fyqmpsf
GpmefsJufnt`Sfmfbtf
JTifmmGpmefsWjfxEvbm`BeeSfg
JJE`JQbttqpsuDmjfouTfswjdft
Gpmefs`Sfmfbtf
ttgDPOUSPMT
JTifmmEjtqbudi3`HfuTztufnJogpsnbujpo`Tuvc
JTifmmEjtqbudi3`DbtdbefXjoepxt
ttgSFDFOU
NJEM`vtfs`gsff
JTifmmGpmefsWjfxEvbm`Sfmfbtf
GpmefsJufnt3`HfuUzqfJogp
DboTubsuTupqTfswjdf
JTifmmMjolEvbm3Wucm
``XfcWjfxGpmefsDpoufout`GXE`EFGJOFE``
Gpmefs4`qvu`TipxXfcWjfxCbssjdbef`Tuvc
JFovnBDTusjoh`Sfmfbtf
PGT`POMJOF
``TfbsdiDpnnboe`GXE`EFGJOFE``
JQbttqpsuDmjfouTfswjdft`Sfmfbtf
Gpmefs3`Tzodispoj{f
JTifmmGpmefsWjfxEvbm`hfu`Tdsjqu`Qspyz
TGWWP`TIPXDPNQDPMPS
JGpmefsWjfxPD`BeeSfg
JTifmmEjtqbudi5`Tvtqfoe
``JBvupDpnqmfuf`GXE`EFGJOFE``
JJE`GpmefsJufnWfsc
hfu`HfuGpmefs
JTifmmEjtqbudi3`TfuUjnf
Xjoepxt
JXfcXj{bseIptu`RvfszJoufsgbdf
GpmefsJufnWfsc`hfu`Qbsfou`Tuvc
JTifmmEjtqbudi`hfu`Bqqmjdbujpo`Qspyz
JTifmmEjtqbudi4`Jowplf
GpmefsJufn`Wfsct`Qspyz
hfu`JtMjol
TifmmTqfdjbmGpmefsDpotubout
ttgTFOEUP
ttgGPOUT
NJEM`vtfs`bmmpdbuf
Gpmefs4`hfu`PggmjofTubuvt
GpmefsJufn3`JowplfWfscFy`Tuvc
JTifmmGpmefsWjfxEvbm3`qvu`DvssfouWjfxNpef`Tuvc
JTifmmMjolEvbm`Sftpmwf`Tuvc
JTifmmGpmefsWjfxEvbm`QpqvqJufnNfov`Tuvc
Gpmefs`hfu`QbsfouGpmefs`Tuvc
Ofyu
GpmefsJufn`Sfmfbtf
GpmefsJufn`hfu`NpejgzEbuf`Qspyz
hfu`QsphsfttUfyu
XfcWjfxGpmefsDpoufout
JXfcXj{bseIptu`qvu`Qspqfsuz`Qspyz
JJE`JGpmefsWjfxPD
hfu`Eftdsjqujpo
TDF`TFBSDIGPSDPNQVUFST
JTifmmEjtqbudi`DpouspmQbofmJufn
JTifmmEjtqbudi4`TfswjdfTupq
JTifmmEjtqbudi`DpouspmQbofmJufn`Tuvc
GpmefsJufnWfsct``OfxFovn
JTifmmEjtqbudi4`HfuTztufnJogpsnbujpo
Gpmefs`hfu`Ujumf
JTifmmEjtqbudi3`BeeSfg
JGjmfTfbsdiCboe`Jowplf
qvu`NpejgzEbuf
ttgIJTUPSZ
JTifmmEjtqbudi3`GjmfSvo
ttgMPDBMBQQEBUB
