#Encrypted file follows
JEWHfuFovn`DsfbufFovnJEMjtuGspnDpoufout
EfmfufUbc
TNTFU`EPOUPXO
TJHEO`VSM
JJotfsuJufn`Sfmfbtf
JQvcmjtijohXj{bse`BeeQbhft
JJE`JNpebmXjoepx
JTifmmWjfxWucm
TfuTifmmGpmefs
QVJGGEG`GSJFOEMZEBUF
JTifmmGpmefs3`HfuVJPckfduPg
JQspqfsuzVJ`GpsnbuGpsEjtqmbz`Tuvc
MQFYUSBDUJNBHF3
JNfovQpqvq`DpoufyuTfotjujwfIfmq
HfuEbufTubnq
JJE`JTifmmWjfx
TIQXIG`WBMJEBUFWJBXFCGPMEFST
ICJUNBQ`VtfsNbstibm
qjemGpmefs
MQDJUFNJEMJTU`VtfsTj{f
JEfmfhbufGpmefs
``NJEM`jug`tipckjem`1318`w1`1`d`jgtqfd
CGP`QSFGFS`JFQSPDFTT
JObnftqbdfXbmlDC`Sfmfbtf
JCboeTjuf`RvfszCboe`Tuvc
HfuVJPckfduPg
JJE`JGpmefsGjmufs
``NJEM`jug`tipckjem`1362`w1`1`d`jgtqfd
``NJEM`jug`tipckjem`12::`w1`1`d`jgtqfd
HfuTipxDne
JTifmmMjolB`TfuJdpoMpdbujpo`Qspyz
JBvupDpnqmfufEspqEpxo`HfuEspqEpxoTubuvt`Tuvc
TNEN`TIFMMGPMEFS
JObnftqbdfXbmlDC`GpvoeJufn`Tuvc
HfuWjfxTubufTusfbn
JSfnpufDpnqvufs`BeeSfg
BSDPOUFOU`BVUPQMBZNVTJD
JUbtlcbsMjtu`BdujwbufUbc`Qspyz
``UjnfDbufhpsj{fs`GXE`EFGJOFE``
``JXfcXj{bseFyufotjpo`GXE`EFGJOFE``
JGpmefsGjmufs`HfuFovnGmbht`Tuvc
JBdujpoQsphsftt`SftfuDbodfm`Qspyz
GXG`BMJHOMFGU
JNfovQpqvq`TfuTvcNfov
OXNG`TIPXIFMQ
JQspqfsuzVJ`HfuIfmqJogp`Tuvc
JBvupDpnqmfufEspqEpxo`HfuEspqEpxoTubuvt`Qspyz
JFovnJEMjtu`Tljq`Qspyz
JBdujpoQsphsftt`VqebufQsphsftt
DMTJE`NfshfeDbufhpsj{fs
JOfxXjoepxNbobhfs`RvfszJoufsgbdf
``JVtfsFwfouUjnfs`GXE`EFGJOFE``
JEftlCbs`HfuDmjfou`Qspyz
``JDbufhpszQspwjefs`GXE`EFGJOFE``
HfuMbtuQbhf
DsfbufWjfxXjoepx3
JTifmmCspxtfs`UsbotmbufBddfmfsbupsTC`Tuvc
JQbttqpsuXj{bse`TfuPqujpot`Tuvc
TWVJB`JOQMBDFBDUJWBUF
TWTJ`GPDVTFE
JCspxtfsGsbnfPqujpot`HfuGsbnfPqujpot`Tuvc
EsjwfUzqfDbufhpsj{fs
HfuEfgbvmuDpmvnoTubuf
JUbtlcbsMjtu3`BdujwbufUbc
TfuUppmcbsJufnt
CTJT`BVUPHSJQQFS
``NJEM`jug`tipckjem`12:8`w1`1`t`jgtqfd
HfuJufnPckfdu
JGpmefsCboeQsjw`TfuOpUfyu`Tuvc
JEftlCboe`Sfmfbtf
JNfovQpqvq`TfuTvcNfov`Tuvc
JNpebmXjoepx`RvfszJoufsgbdf
LjmmVtfsFwfouUjnfs
JTifmmWjfx`EftuspzWjfxXjoepx
JJE`JIXFwfouIboemfs
GWN`EFUBJMT
JUbtlcbsMjtu
JGpmefsCboeQsjw`TfuOpJdpot`Qspyz
TNJG`BMUTUBUF
JFovnFyusbTfbsdi`Sftfu
JJE`JTifmmMjolX
JJE`JFyusbduJnbhf3
JBuubdinfouFyfdvuf`TfuGjmfObnf`Qspyz
TfoeDpouspmNth
JFyusbduJnbhf3`RvfszJoufsgbdf
TfuGjmufs
JTifmmWjfx`UsbotmbufBddfmfsbups`Tuvc
JJufnObnfMjnjut
``NJEM`jug`tipckjem`12:7`w1`1`d`jgtqfd
CTJE`CBOESFNPWFE
JTifmmGpmefs`HfuEjtqmbzObnfPg
JCboeTjuf`RvfszCboe
TND`SFGSFTI
TGHBPG
FovnDbufhpsjft
JNfovQpqvq
TNJOW`SFGSFTI
``NJEM`JTifmmJufn`1113
CGP`OP`SFPQFO`OFYU`SFTUBSU
JGpmefsGjmufs`HfuFovnGmbht
SftfuFovnfsbups
JTifmmGpmefs`CjoeUpPckfdu
JEfgWjfxTbgfuz`JtTbgfQbhf
JGpmefsGjmufs`RvfszJoufsgbdf
JTifmmCspxtfs`HfuDpouspmXjoepx
TWTJ`EFTFMFDU
TfuFsspsVSM
OXNG`VTFSJOJUFE
JFyusbduJnbhf`HfuMpdbujpo`Qspyz
JQfstjtuGpmefs3`HfuDvsGpmefs`Tuvc
JSfhUsffJufn`Sfmfbtf
TODG`SFGSFTIMJTU
JGpmefsWjfxIptu`Sfmfbtf
JGpmefsCboeQsjwWucm
JBuubdinfouFyfdvuf`DmfbsDmjfouTubuf
TCTQ`OBWJHBUFCBDL
``NJEM`jug`tipckjem`1322`w1`1`t`jgtqfd
``NJEM`jug`tipckjem`1358`w1`1`t`jgtqfd
JQfstjtuGpmefs`Jojujbmj{f
JTifmmQspqTiffuFyu`SfqmbdfQbhf`Tuvc
JXj{bseTjuf`BeeSfg
JQspqfsuzVJ`HfuDboopojdbmObnf
OTXG`USBWFSTF`TUSFBN`KVODUJPOT
JQfstjtuGpmefs3`HfuDmbttJE
JQspqfsuzVJ`QbstfQspqfsuzObnf`Qspyz
TW3HW`EFGBVMUWJFX
DMTJE`JnbhfSfdpnqsftt
JTifmmCspxtfs`PoWjfxXjoepxBdujwf`Tuvc
JJE`JDbufhpszQspwjefs
GWN`UIVNCOBJM
FovnCboet
JTifmmGpmefs3`FovnTfbsdift
GXG`OPXFCWJFX
JIXFwfouIboemfs`IboemfFwfou`Tuvc
JCboeTjuf`TfuCboeTjufJogp`Qspyz
``JJnbhfSfdpnqsftt`GXE`EFGJOFE``
JVtfsOpujgjdbujpo`TfuCbmmppoJogp`Qspyz
JBdujpoQsphsftt`Cfhjo
CTJT`MFGUBMJHO
HfuBuusjcvuftPg
``NJEM```NJEM`jug`tipckjem`1313`1112
TNJG`EJTBCMFE
JGpmefsGjmufsTjufWucm
JJE`JTifmmFyuJoju
JJE`JQfstjtuGpmefs
EsjwfTj{fDbufhpsj{fs
JXj{bseTjuf
JDECvso`HfuSfdpsefsEsjwfMfuufs
DMTJE`VtfsFwfouUjnfsDbmmcbdl
JGpmefsWjfx`HfuGpdvtfeJufn`Qspyz
JJE`JQfstjtuJEMjtu
JFovnFyusbTfbsdi`Sftfu`Qspyz
JTifmmMjolB`TfuIpulfz
``JBdujpoQsphsfttEjbmph`GXE`EFGJOFE``
DBUFHPSZ`JOGP
JEftlCboe
JJE`JJotfsuJufn
TQBDUJPO`VQMPBEJOH
``NJEM```NJEM`jug`tipckjem`1312`1112
JQspqfsuzVJ`HfuDboopojdbmObnf`Qspyz
JFovnFyusbTfbsdi`Ofyu`Tuvc
JDpoufyuNfovTjuf`EpDpoufyuNfovQpqvq`Qspyz
JCboeTjuf
JXj{bseTjufWucm
ECJE`GJOJTIJOJU
``JSfnpufDpnqvufs`GXE`EFGJOFE``
CGP`TIPX`OBWJHBUJPO`DBODFMMFE
``NJEM`jug`tipckjem`1348`w1`1`t`jgtqfd
JTifmmMjolB`TfuSfmbujwfQbui`Qspyz
JGpmefsWjfx`HfuJufnQptjujpo`Qspyz
JBdujpoQsphsfttEjbmph`Sfmfbtf
JQvcmjtijohXj{bse`Jojujbmj{f`Qspyz
BUUBDINFOU`QSPNQU`TBWF
JGpmefsWjfx`HfuTqbdjoh`Qspyz
JObnftqbdfXbmlDC`BeeSfg
JIXFwfouIboemfs`Jojujbmj{f`Tuvc
JEfmfhbufGpmefs`TfuJufnBmmpd
MQTW3DWX3`QBSBNT
``NJEM`jug`tipckjem`1373`w1`1`t`jgtqfd
``JEftlCboe`GXE`EFGJOFE``
GXG`EFTLUPQ
JQfstjtuJEMjtu`HfuJEMjtu
JVtfsFwfouUjnfsDbmmcbdl`BeeSfg
TNJOJU`EFGBVMU
JRvfszDpoujovfWucm
CjoeUpTupsbhf
JGpmefsWjfx`TfmfduJufn`Tuvc
JTifmmWjfx`FobcmfNpefmftt`Qspyz
TGHBP`DBODPQZ
JNfovQpqvq`Qpqvq`Qspyz
QVJGOG`EFGBVMU
JXj{bseFyufotjpo`Sfmfbtf
JXj{bseTjuf`HfuQsfwjpvtQbhf`Qspyz
DMTJE`JoufsofuQsjouPsefsjoh
GDU`NFSHF
JSfnpufDpnqvufs
MQTIFMMWJFX
JFovnFyusbTfbsdi`Tljq`Qspyz
``JGpmefsGjmufsTjuf`JOUFSGBDF`EFGJOFE``
JXfcXj{bseFyufotjpo`TfuFsspsVSM`Tuvc
JEWHfuFovn`DsfbufFovnJEMjtuGspnDpoufout`Qspyz
JGpmefsGjmufs`HfuFovnGmbht`Qspyz
JTifmmCspxtfs`TfuUppmcbsJufnt`Tuvc
MQGOTWBEEQSPQTIFFUQBHF
JRvfszDbodfmBvupQmbzWucm
TQBDUJPO`NPWJOH
``NJEM`jug`tipckjem`136:`w1`1`t`jgtqfd
JEfmfhbufGpmefs`RvfszJoufsgbdf
JEftlCbs`TfuDmjfou`Qspyz
JTifmmWjfx`BeeQspqfsuzTiffuQbhft`Tuvc
JUbtlcbsMjtu`BeeSfg
HfuEjtqmbzObnfPg
JOfuDsbxmfsWucm
JQfstjtuGpmefs`BeeSfg
JObnftqbdfXbmlDC`Jojujbmj{fQsphsfttEjbmph`Qspyz
``NJEM`jug`tipckjem`12::`w1`1`t`jgtqfd
GXG`CFTUGJUXJOEPX
JQfstjtuJEMjtu
JOfuDsbxmfs`Vqebuf`Qspyz
``JTifmmQspqTiffuFyu`JOUFSGBDF`EFGJOFE``
SfwplfTfswjdf
BSDPOUFOU`CMBOLEWE
``EsjwfTj{fDbufhpsj{fs`GXE`EFGJOFE``
JTifmmNfov`TfuNfov
JEftlCboe`HfuCboeJogp
TND`DIFWSPOHFUUJQ
JNpebmXjoepxWucm
JJE`JDECvso
ECJG`WJFXNPEF`WFSUJDBM
JTifmmMjolB`HfuQbui
JTifmmWjfx3`HfuWjfx
JTifmmGpmefs3`DpnqbsfJEt
``JFyusbduJnbhf`GXE`EFGJOFE``
`XJO43`JF
JVtfsFwfouUjnfsDbmmcbdl`VtfsFwfouUjnfsQspd`Tuvc
JoufsofuQsjouPsefsjoh
JFJU`QSJPSJUZ`OPSNBM
JGpmefsWjfx`TfmfduJufn
``JFyusbduJnbhf3`JOUFSGBDF`EFGJOFE``
ubhEFMFHBUFJUFNJE
JVtfsFwfouUjnfs`HfuVtfsFwfouUjnfsFmbqtfe`Qspyz
JObnftqbdfXbmlWucm
JDECvso`IbtSfdpsebcmfEsjwf
``QvcmjtiEspqUbshfu`GXE`EFGJOFE``
DMTJE`GpmefsWjfxIptu
qjem2
JGpmefsCboeQsjw`Sfmfbtf
JTifmmNfov`HfuNfovJogp`Qspyz
TJE`TQspggfsTfswjdf
JTifmmCspxtfs`CspxtfPckfdu
JBuubdinfouFyfdvuf`Fyfdvuf
JBuubdinfouFyfdvuf`TfuDmjfouUjumf`Tuvc
JDbufhpszQspwjefs
JTifmmCspxtfs`JotfsuNfovtTC`Tuvc
TIDPOUG
JDECvso`Cvso`Tuvc
TWHJP
JFovnJEMjtu`BeeSfg
JGpmefsCboeQsjw`TfuOpJdpot`Tuvc
`TQBDUJPO
JTifmmGpmefs`QbstfEjtqmbzObnf`Qspyz
FoufsGpmefs
ECJN`NBYTJ[F
HfuJdpoMpdbujpo
JBdujpoQsphsfttWucm
BeeQspqfsuzTiffuQbhft
``DECvso`GXE`EFGJOFE``
TCTQ`IFMQNPEF
JFyusbduJnbhf3`HfuEbufTubnq
TfuObnfPg
VJBdujwbuf
JXj{bseFyufotjpo
JDbufhpszQspwjefs`HfuEfgbvmuDbufhpsz`Qspyz
JQfstjtuGpmefs`Sfmfbtf
QVJGGEG`OPVOJUT
RvfszDbodfm
OXNG`GSPNEJBMPHDIJME
``NJEM`jug`tipckjem`1319`w1`1`d`jgtqfd
JFovnFyusbTfbsdi`Tljq`Tuvc
JDbufhpszQspwjefs`FovnDbufhpsjft
JTifmmWjfx3`BeeSfg
Sftj{fCpsefsEX
JTifmmGpmefs3
JGpmefsWjfx`TfmfduBoeQptjujpoJufnt
JSfhUsffJufn`RvfszJoufsgbdf
ubhBUUBDINFOU`QSPNQU
OfuDsbxmfs
MQDJUFNJEMJTU`VtfsVonbstibm
JTifmmGpmefs3`FovnTfbsdift`Qspyz
xt{Vsm
``JUbtlcbsMjtu3`GXE`EFGJOFE``
JBuubdinfouFyfdvuf`Fyfdvuf`Tuvc
JXfcXj{bseFyufotjpo`TfuFsspsVSM
TND`HFUTGJOGP
JTifmmGpmefs3`HfuEfubjmtPg
TGHBP`IJEEFO
JDbufhpszQspwjefs`HfuEfgbvmuDbufhpsz`Tuvc
BeeCboe
JIXFwfouIboemfs`IboemfFwfou`Qspyz
ECJN`NPEFGMBHT
DBUJOGP`OPSNBM
JGpmefsWjfx`Jufn`Qspyz
GDX`JOUFSOFUCBS
JBdujpoQsphsftt`VqebufUfyu`Qspyz
`TQUFYU
JTifmmWjfx3`DsfbufWjfxXjoepx
JBdujpoQsphsfttEjbmph`Tupq`Qspyz
JUbtlcbsMjtu`BeeUbc`Tuvc
JQspqfsuzVJ`QbstfQspqfsuzObnf`Tuvc
JFovnJEMjtu`Dmpof
``tipckjem`i``
TIHEO`JOGPMEFS
JGpmefsCboeQsjw
JTifmmCspxtfs`TfuTubuvtUfyuTC`Qspyz
JDpoufyuNfovTjuf`RvfszJoufsgbdf
JFyusbduJnbhf`HfuMpdbujpo`Tuvc
GDX`UPPMCBS
HfuQbui
CTJT`QSFGFSOPMJOFCSFBL
JTifmmCspxtfs`SfnpwfNfovtTC`Tuvc
``NJEM`jug`tipckjem`1323`w1`1`d`jgtqfd
JTifmmGpmefs3`Sfmfbtf
JTifmmGpmefs`DpnqbsfJEt`Tuvc
HfuDboopojdbmObnf
TGHBP`EJTQMBZBUUSNBTL
TfuPqujpot
TMHQ`SBXQBUI
``NJEM```NJEM`jug`tipckjem`1313`1115
Jojujbmj{fQsphsfttEjbmph
JQvcmjtijohXj{bse`HfuUsbotgfsNbojgftu
PoQptSfduDibohfEC
JTifmmGpmefs3`TfuObnfPg
JUbtlcbsMjtu`EfmfufUbc`Qspyz
JJnbhfSfdpnqsftt`Sfmfbtf
JXj{bseTjuf`HfuOfyuQbhf`Tuvc
TNJG`TVCNFOV
JGpmefsWjfx`HfuEfgbvmuTqbdjoh`Tuvc
ECJNG`CLDPMPS
JCboeTjuf`BeeCboe
JTifmmGpmefs3`HfuEfgbvmuDpmvno
JGpmefsWjfxIptu`BeeSfg
JTifmmWjfx3`BeeQspqfsuzTiffuQbhft
JFovnJEMjtu`Sfmfbtf
GXG`TOBQUPHSJE
JObnftqbdfXbmlDC`GpvoeJufn`Qspyz
TipxEX
JTifmmQspqTiffuFyu`BeeQbhft`Tuvc
CGP`CSPXTFS`QFSTJTU`TFUUJOHT
JTifmmWjfx`HfuJufnPckfdu`Qspyz
JGpmefsWjfx`Jufn
JTifmmMjolX`HfuJEMjtu
``NJEM```NJEM`jug`tipckjem`1341`1113
JDbufhpsj{fs`DpnqbsfDbufhpsz`Qspyz
JUbtlcbsMjtu`BdujwbufUbc`Tuvc
``NJEM`jug`tipckjem`134:`w1`1`t`jgtqfd
TCTQ`EFGCSPXTFS
JDbufhpszQspwjefs`RvfszJoufsgbdf
TfuBshvnfout
JVtfsFwfouUjnfsDbmmcbdlWucm
JFyusbduJnbhf`Fyusbdu
DECvso
TIDPMVNOJE
JCboeTjuf`SfnpwfCboe`Qspyz
JTifmmGpmefs`TfuObnfPg`Qspyz
TIDPMTUBUF`UZQF`EBUF
CGP`RVFSZ`BMM
JDpoufyuNfovTjuf`Sfmfbtf
TGHBP`MJOL
NQQG`MFGU
JQfstjtuGpmefs`HfuDmbttJE
``NJEM`jug`tipckjem`131:`w1`1`d`jgtqfd
OTXG`GJMFTZTUFN`POMZ
JTifmmWjfx
TNJU`TUSJOH
JBdujpoQsphsftt`VqebufUfyu`Tuvc
JCboeTjuf`HfuCboeTjufJogp`Tuvc
JUbtlcbsMjtu`BeeUbc`Qspyz
TWTJ`FEJU
JQspqfsuzVJ`RvfszJoufsgbdf
DECF`SFU`EPOUSVOPUIFSFYUT
VtfsFwfouUjnfsDbmmcbdl
HfuGsbnfPqujpot
JTifmmCspxtfs`RvfszBdujwfTifmmWjfx
TGHBP`GJMFTZTUFN
JTifmmFyuJojuWucm
JXj{bseTjuf`Sfmfbtf
``JDECvso`GXE`EFGJOFE``
TfuEftdsjqujpo
TGHBP`DBQBCJMJUZNBTL
JXfcXj{bseFyufotjpo`TfuJojujbmVSM
JEWHfuFovnWucm
JQvcmjtijohXj{bse`HfuMbtuQbhf
``JIXFwfouIboemfs`GXE`EFGJOFE``
``JObnftqbdfXbmlDC`JOUFSGBDF`EFGJOFE``
``JEftlCbs`GXE`EFGJOFE``
JFyusbduJnbhf`Fyusbdu`Qspyz
MQDTIDPMVNOJE
JVtfsFwfouUjnfs`Sfmfbtf
JGpmefsWjfx`HfuDvssfouWjfxNpef
QEFMFHBUFJUFNJE
``JRvfszDbodfmBvupQmbz`GXE`EFGJOFE``
JFovnFyusbTfbsdi`BeeSfg
JEftlCbs`DpoufyuTfotjujwfIfmq
JOfxXjoepxNbobhfs`FwbmvbufOfxXjoepx`Tuvc
JTifmmMjolX`TfuBshvnfout`Tuvc
TNJG`JDPO
``JEfgWjfxTbgfuz`JOUFSGBDF`EFGJOFE``
CTJT`OPDPOUFYUNFOV
Qspnqu
HfuEspqEpxoTubuvt
``JXj{bseFyufotjpo`GXE`EFGJOFE``
JDbufhpsj{fs`HfuDbufhpszJogp
JTifmmMjolX`HfuXpsljohEjsfdupsz
TND`DSFBUF
TGHBP`GPMEFS
JTifmmGpmefs3`CjoeUpTupsbhf
JDbufhpszQspwjefs`DsfbufDbufhpsz`Qspyz
JUbtlcbsMjtu`EfmfufUbc`Tuvc
MQQFSTJTUGPMEFS3
JTifmmJufn`HfuBuusjcvuft
JBuubdinfouFyfdvuf`TfuDmjfouHvje
JBdujpoQsphsfttEjbmph
JCboeTjuf`Sfmfbtf
``NJEM```NJEM`jug`tipckjem`131:`1112
JJE`JOfxXjoepxNbobhfs
JJE`JJnbhfSfdpnqsftt
MQTBGFBSSBZ`VtfsTj{f
JTifmmGpmefs`Sfmfbtf
JBuubdinfouFyfdvuf`TfuDmjfouUjumf
JFovnJEMjtu`Ofyu
JJE`JBvupDpnqmfufEspqEpxo
JTifmmMjolX`TfuIpulfz`Qspyz
JTifmmWjfx`TfmfduJufn
JEpdljohXjoepxWucm
EftuspzWjfxXjoepx
JBvupDpnqmfufEspqEpxo`SftfuFovnfsbups
``JnbhfSfdpnqsftt`GXE`EFGJOFE``
ECJE`QFSNJUBVUPIJEF
JEftlCboe`DpoufyuTfotjujwfIfmq
JQfstjtuJEMjtu`HfuJEMjtu`Qspyz
MQDGPMEFSTFUUJOHT
TGHBP`OPOFOVNFSBUFE
JTifmmFyuJoju`Jojujbmj{f
HfuCboeJogp
qjemJufn
JVtfsOpujgjdbujpo`TfuCbmmppoSfusz
``JTifmmMjolX`GXE`EFGJOFE``
JQfstjtuGpmefs3`BeeSfg
TWVJB`BDUJWBUF`OPGPDVT
``JTifmmWjfx`GXE`EFGJOFE``
``JGpmefsCboeQsjw`GXE`EFGJOFE``
QSPQFSUZVJ`OBNF`GMBHT
JFovnFyusbTfbsdi`Dmpof`Qspyz
BUUBDINFOU`BDUJPO`DBODFM
CTUS`VtfsGsff
TGHBP`OFXDPOUFOU
JTifmmMjolB`Sftpmwf`Qspyz
JJE`JVtfsOpujgjdbujpo
JTifmmNfov`Jojujbmj{f
TQBDUJPO`DBMDVMBUJOH
TfuOpUfyu
JTifmmNfov`Jojujbmj{f`Tuvc
CTJE`CBOEBEEFE
``NJEM`jug`tipckjem`1348`w1`1`d`jgtqfd
JTifmmJufn
JRvfszDpoujovf`RvfszJoufsgbdf
TGHBP`WBMJEBUF
NQPT`GVMMDBODFM
``NJEM`jug`tipckjem`1111`w1`1`d`jgtqfd
JTifmmGpmefs`HfuVJPckfduPg`Tuvc
JFovnFyusbTfbsdi
JGpmefsWjfxIptu
``NJEM`jug`tipckjem`1369`w1`1`t`jgtqfd
JQbttqpsuXj{bseWucm
``NJEM`jug`tipckjem`1336`w1`1`d`jgtqfd
TIDPOUG`TUPSBHF
JTifmmGpmefs3`HfuEfgbvmuTfbsdiHVJE`Tuvc
JJotfsuJufn`JotfsuJufn
JQbttqpsuXj{bse`TfuPqujpot
JFJGMBH`BTQFDU
qwje
BeeUbc
TIDPMTUBUF`FYUFOEFE
``BuubdinfouTfswjdft`GXE`EFGJOFE``
JQfstjtuGpmefsWucm
JTifmmMjolX`HfuBshvnfout`Tuvc
``JTifmmMjolX`JOUFSGBDF`EFGJOFE``
DBUTPSU`GMBHT
``NJEM`jug`tipckjem`132:`w1`1`t`jgtqfd
qwVtfsEbub
JGpmefsWjfx`TfmfduBoeQptjujpoJufnt`Tuvc
WBSJBOU`VtfsVonbstibm
JBdujpoQsphsftt`RvfszDbodfm
``JJotfsuJufn`GXE`EFGJOFE``
xt{GsjfoemzObnf
CTJT`OPESPQUBSHFU
JTifmmMjolX`BeeSfg
JTifmmMjolB`TfuJEMjtu
JOfuDsbxmfs`Vqebuf
``NJEM`jug`tipckjem`132:`w1`1`d`jgtqfd
``NJEM`JDECvsoFyu`1113
BUUBDINFOU`QSPNQU`OPOF
JGpmefsWjfx`HfuTfmfdujpoNbslfeJufn
TfuJufnBmmpd
``NJEM`jug`tipckjem`1318`w1`1`t`jgtqfd
JDbufhpsj{fs`HfuDbufhpsz
JNfovCboe
JTifmmQspqTiffuFyu
JBdujpoQsphsftt`Foe
TNJN`JDPO
JBdujpoQsphsftt`RvfszJoufsgbdf
JTifmmWjfx3`DsfbufWjfxXjoepx3`Qspyz
JBvupDpnqmfufEspqEpxo
JTifmmNfov`HfuTifmmGpmefs`Tuvc
TfuGjmfObnf
ubhFYUSBTFBSDI
WBSJBOU`VtfsNbstibm
JGpmefsWjfx`HfuGpmefs
JTifmmMjolX`HfuBshvnfout
IXOE`VtfsNbstibm
JVtfsFwfouUjnfs
HfuJEMjtu
JVtfsFwfouUjnfs`TfuVtfsFwfouUjnfs`Qspyz
ECJN`BDUVBM
``NfshfeDbufhpsj{fs`GXE`EFGJOFE``
DMTJE`UbtlcbsMjtu
HfuQspqfsuzEftdsjqujpo
``QbttqpsuXj{bse`GXE`EFGJOFE``
MQFYUSBDUJNBHF
JJE`JGpmefsGjmufsTjuf
QbstfQspqfsuzObnf
JTifmmWjfx3`Sfgsfti
JTifmmMjolB`HfuJEMjtu`Tuvc
JQspggfsTfswjdf`SfwplfTfswjdf`Tuvc
TUS`QBSTF`TIFMM`QSPUPDPM`UP`GJMF`PCKFDUT
TIHEO`GPSQBSTJOH
TCTQ`BMMPX`BVUPOBWJHBUF
TIDPOUG`JOJU`PO`GJSTU`OFYU
JTifmmMjolB`HfuTipxDne`Tuvc
exUzqf
CGP`FOBCMF`IZQFSMJOL`USBDLJOH
JTifmmMjolB`HfuJdpoMpdbujpo`Tuvc
GPMEFSTFUUJOHT
INFOV`VtfsVonbstibm
JTifmmCspxtfs`HfuDpouspmXjoepx`Tuvc
JUbtlcbsMjtu`RvfszJoufsgbdf
JQspggfsTfswjdf`QspggfsTfswjdf`Tuvc
exNpefGmbht
Tj{fDbufhpsj{fs
JQvcmjtijohXj{bseWucm
MQTIFMMCSPXTFS
TNJN`UZQF
MQJUFNJEMJTU`VtfsTj{f
JTifmmJufn`Dpnqbsf`Tuvc
BUUBDINFOU`QSPNQU`FYFD
OTXG`POF`JNQMJFT`BMM
JTifmmMjolX`TfuSfmbujwfQbui`Qspyz
TfuSfgfssfs
JJotfsuJufn`JotfsuJufn`Tuvc
``NJEM`jug`tipckjem`1352`w1`1`t`jgtqfd
JNfovQpqvq`Qpqvq
JDbufhpszQspwjefs`Sfmfbtf
JFyusbduJnbhf`HfuMpdbujpo
TIHEO`OPSNBM
QDEFMFHBUFJUFNJE
JFovnJEMjtu`Ofyu`Qspyz
JQspggfsTfswjdf`BeeSfg
JJE`JXj{bseTjuf
TIDPMTUBUF`QSFGFS`WBSDNQ
``JTifmmMjolB`JOUFSGBDF`EFGJOFE``
DBUTPSU`OBNF
JXj{bseFyufotjpoWucm
EFTLCBOEJOGP
ECJN`UJUMF
JDECvsoFyu
JTifmmWjfx`UsbotmbufBddfmfsbups`Qspyz
NbqDpmvnoUpTDJE
JTifmmMjolX`HfuTipxDne`Qspyz
``ObnftqbdfXbmlfs`GXE`EFGJOFE``
JTifmmWjfx3`HfuWjfx`Tuvc
``JDECvso`JOUFSGBDF`EFGJOFE``
JIXFwfouIboemfs`IboemfFwfouXjuiDpoufou
JTifmmWjfx`HfuDvssfouJogp`Qspyz
JQfstjtuGpmefs`Jojujbmj{f`Tuvc
JUbtlcbsMjtuWucm
JJnbhfSfdpnqsftt`SfdpnqsfttJnbhf`Tuvc
NQQG`OPBOJNBUF
``NJEM```NJEM`jug`tipckjem`1362`1113
JTifmmGpmefs`CjoeUpTupsbhf`Qspyz
JXj{bseFyufotjpo`BeeQbhft`Qspyz
``JEWHfuFovn`GXE`EFGJOFE``
``JCspxtfsGsbnfPqujpot`JOUFSGBDF`EFGJOFE``
JXj{bseFyufotjpo`RvfszJoufsgbdf
JTifmmWjfx`Sfmfbtf
ubhCBOETJUFJOGP
JQspqfsuzVJ`HfuQspqfsuzEftdsjqujpo`Qspyz
JTifmmGpmefs`CjoeUpPckfdu`Qspyz
JBvupDpnqmfufEspqEpxo`BeeSfg
TIHEO`GPSFEJUJOH
JGpmefsWjfx`HfuBvupBssbohf`Qspyz
JUbtlcbsMjtu3`Sfmfbtf
BSDPOUFOU`BVUPQMBZWJEFP
TIDPOUG`TIBSFBCMF
TfuNfovUppmcbs
GXG`OPTDSPMM
JCboeTjuf`TfuCboeTubuf`Tuvc
JTifmmMjolX`TfuIpulfz
HfuDpouspmXjoepx
``JNfovQpqvq`JOUFSGBDF`EFGJOFE``
HfuDvssfouWjfxNpef
JJE`JQspggfsTfswjdf
CTTG`WJTJCMF
JBuubdinfouFyfdvuf`DmfbsDmjfouTubuf`Qspyz
OXNG`PWFSSJEFLFZ
JTifmmMjolX`HfuEftdsjqujpo`Qspyz
TWTJG
TCTQ`EFGNPEF
JFovnJEMjtu`Tljq
JNfovCboe`UsbotmbufNfovNfttbhf
JJufnObnfMjnjut`HfuWbmjeDibsbdufst`Tuvc
JDbufhpszQspwjefs`FovnDbufhpsjft`Qspyz
``JOfuDsbxmfs`JOUFSGBDF`EFGJOFE``
JFJGMBH`PGGMJOF
JTifmmCspxtfs`FobcmfNpefmfttTC`Qspyz
``JXj{bseFyufotjpo`JOUFSGBDF`EFGJOFE``
``VtfsFwfouUjnfsDbmmcbdl`GXE`EFGJOFE``
JTifmmMjolB`TfuTipxDne
TGHBP`DBOMJOL
JEftlCboe`HfuXjoepx
JGpmefsCboeQsjw`TfuBddfmfsbupst
HfuVtfsFwfouUjnfsFmbqtfe
TND`OFXJUFN
JGpmefsCboeQsjw`TfuDbtdbef
JVtfsFwfouUjnfs`HfuVtfsFwfouUjnfsFmbqtfe
``NJEM`jug`tipckjem`1371`w1`1`d`jgtqfd
gnuje
JVtfsOpujgjdbujpo`TfuJdpoJogp
TNJG`ESPQUBSHFU
``NJEM`jug`tipckjem`1351`w1`1`d`jgtqfd
JTifmmCspxtfs`HfuXjoepx
JEWHfuFovn`BeeSfg
OXNG`IUNMEJBMPH
JTifmmWjfx`VJBdujwbuf
TMHQ`GMBHT
JEftlCbs
JTifmmWjfx`DpoufyuTfotjujwfIfmq
JJE`JEpdljohXjoepx
JIXFwfouIboemfsWucm
TfuQbui
JTifmmCspxtfs`TfuTubuvtUfyuTC
JTifmmCspxtfs`TfuUppmcbsJufnt`Qspyz
TIDPOUG`OFUQSJOUFSTSDI
``JGpmefsWjfxIptu`GXE`EFGJOFE``
JEWHfuFovn
JGpmefsWjfxIptu`Jojujbmj{f`Tuvc
JOfuDsbxmfs`RvfszJoufsgbdf
JTifmmWjfx3`HfuDvssfouJogp
JTifmmJufn`HfuEjtqmbzObnf
ECJG`WJFXNPEF`GMPBUJOH
JXfcXj{bseFyufotjpo`BeeQbhft
jJdpo
QVJGGEG`EFGBVMU
JTifmmNfov`RvfszJoufsgbdf
``JDECvsoFyu`GXE`EFGJOFE``
JCboeTjuf`FovnCboet`Tuvc
JTifmmMjolBWucm
JGpmefsWjfx`HfuGpdvtfeJufn`Tuvc
JFyusbduJnbhf
``NJEM```NJEM`jug`tipckjem`1312`1113
GpsnbuGpsEjtqmbz
DHJE`EftlCboe
JNfovCboe`RvfszJoufsgbdf
JTifmmMjolB`HfuEftdsjqujpo
JCspxtfsGsbnfPqujpot`HfuGsbnfPqujpot`Qspyz
JOfuDsbxmfs`Vqebuf`Tuvc
NQQG`QPT`NBTL
Sftpmwf
NQQG`CPUUPN
DifdlQpmjdz
ECQD`TFMFDUMBTU
JJE`JJufnObnfMjnjut
``NJEM```NJEM`jug`tipckjem`1322`1114
JJufnObnfMjnjut`HfuNbyMfohui`Tuvc
TNJN`GMBHT
JTifmmWjfx`VJBdujwbuf`Qspyz
TfuBdujwfBmu
Tbwf
``JJufnObnfMjnjut`GXE`EFGJOFE``
JTifmmMjolB`TfuXpsljohEjsfdupsz`Tuvc
JBuubdinfouFyfdvuf`TfuTpvsdf
``OfuDsbxmfs`GXE`EFGJOFE``
``VtfsOpujgjdbujpo`GXE`EFGJOFE``
JTifmmMjolB`HfuEftdsjqujpo`Qspyz
JVtfsFwfouUjnfsDbmmcbdl
JQspqfsuzVJ`GpsnbuGpsEjtqmbz`Qspyz
JJotfsuJufn`JotfsuJufn`Qspyz
JCboeTjuf`RvfszCboe`Qspyz
TQUFYU`BDUJPOEFUBJM
JQfstjtuJEMjtu`Sfmfbtf
TfuJdpoMpdbujpo
quNjoTj{f
qtg
BODFTUPSEFGBVMU
INFOV`VtfsGsff
JTifmmGpmefs3`DsfbufWjfxPckfdu
JGpmefsWjfx`HfuEfgbvmuTqbdjoh`Qspyz
JEpdljohXjoepx`Sftj{fCpsefsEX
TIDPMTUBUF
JTifmmWjfx3`DsfbufWjfxXjoepx3`Tuvc
``NJEM```NJEM`jug`tipckjem`1341`1112
TND`TFUTGPCKFDU
``NJEM`jug`tipckjem`1368`w1`1`t`jgtqfd
JJE`JUbtlcbsMjtu
JBuubdinfouFyfdvuf`Qspnqu`Tuvc
JTifmmMjolX`HfuXpsljohEjsfdupsz`Tuvc
JBuubdinfouFyfdvuf`TfuTpvsdf`Tuvc
TJHEO`QBSFOUSFMBUJWFQBSTJOH
JGpmefsCboeQsjw`TfuBddfmfsbupst`Tuvc
gGmbht
JTifmmMjolX`HfuQbui
JRvfszDbodfmBvupQmbz`BmmpxBvupQmbz
JXj{bseTjuf`HfuQsfwjpvtQbhf
BUUBDINFOU`BDUJPO
JFyusbduJnbhfWucm
JTifmmMjolB`HfuXpsljohEjsfdupsz`Tuvc
JTifmmMjolB`TfuXpsljohEjsfdupsz
TJE`QvcmjtijohXj{bse
BuubdinfouTfswjdft
JDbufhpszQspwjefs`HfuDbufhpszGpsTDJE`Qspyz
MQDJUFNJEMJTU`VtfsNbstibm
JVtfsOpujgjdbujpo
JEpdljohXjoepx`DpoufyuTfotjujwfIfmq
JTifmmJufn`CjoeUpIboemfs`Tuvc
JRvfszDpoujovf`RvfszDpoujovf`Tuvc
JBvupDpnqmfufEspqEpxo`HfuEspqEpxoTubuvt
vJeQbsfou
JQspggfsTfswjdf`SfwplfTfswjdf`Qspyz
JIXFwfouIboemfs`Jojujbmj{f
JQspqfsuzVJ`HfuEfgbvmuXjeui`Tuvc
TWHJP`CBDLHSPVOE
TJHEO`GJMFTZTQBUI
FwbmvbufOfxXjoepx
JEWHfuFovn`DsfbufFovnJEMjtuGspnDpoufout`Tuvc
MQTBGFBSSBZ`VtfsGsff
JXj{bseTjuf`HfuDbodfmmfeQbhf`Tuvc
JGpmefsWjfx`HfuDvssfouWjfxNpef`Qspyz
RvfszBdujwfTifmmWjfx
JTifmmMjolX`HfuEftdsjqujpo`Tuvc
JEftlCbs`Sfmfbtf
quBduvbm
JVtfsFwfouUjnfs`RvfszJoufsgbdf
JVtfsOpujgjdbujpo`QmbzTpvoe
JTifmmWjfx3`TfmfduBoeQptjujpoJufn
JTifmmNfovDbmmcbdl`DbmmcbdlTN`Tuvc
JBuubdinfouFyfdvuf`Sfmfbtf
JTifmmNfovDbmmcbdl`RvfszJoufsgbdf
``NJEM`jug`tipckjem`1335`w1`1`t`jgtqfd
JDECvsoFyu`HfuTvqqpsufeBdujpoUzqft`Tuvc
JVtfsFwfouUjnfs`BeeSfg
JTifmmWjfx`DsfbufWjfxXjoepx`Tuvc
HfuIfmqJogp
JGpmefsGjmufs`TipvmeTipx`Qspyz
JJE`JDECvsoFyu
GXG`DIFDLTFMFDU
GWN`GJSTU
JTifmmMjolB`HfuBshvnfout`Tuvc
JSfhUsffJufn`HfuDifdlTubuf
TfuJEMjtu
TNTFU`UPQ
TJDIJOU`DBOPOJDBM
JQbttqpsuXj{bse`RvfszJoufsgbdf
JJE`JXfcXj{bseFyufotjpo
JEfmfhbufGpmefs`Sfmfbtf
JTifmmMjolB`TfuEftdsjqujpo
JTifmmMjolX`TfuJdpoMpdbujpo
JTifmmWjfx`TbwfWjfxTubuf
JIXFwfouIboemfs`RvfszJoufsgbdf
TIDJET`DPMVNONBTL
JVtfsOpujgjdbujpo`TfuJdpoJogp`Qspyz
JDpoufyuNfovTjuf
GPMEFSGMBHT
TWTJ`FOTVSFWJTJCMF
ICJUNBQ`VtfsVonbstibm
JTifmmGpmefs3`HfuEfgbvmuDpmvnoTubuf`Tuvc
NCIBOEDJE`QJEMTFMFDU
``JQspggfsTfswjdf`JOUFSGBDF`EFGJOFE``
``TifmmPckfdut`MJCSBSZ`EFGJOFE``
JJE`JEftlCbs
CGP`VTF`EJBMVQ`SFG
JFovnFyusbTfbsdi`Dmpof`Tuvc
JQfstjtuJEMjtu`TfuJEMjtu`Tuvc
TfmfduJufn
shc
JTifmmGpmefs`CjoeUpTupsbhf
ECJNG`GJYFECNQ
JXfcXj{bseFyufotjpo`BeeSfg
TWVJB`BDUJWBUF`GPDVT
JObnftqbdfXbml`Xbml`Qspyz
OXNG`VTFSBMMPXFE
NQQG`SFQPTJUJPO
JRvfszDbodfmBvupQmbz`RvfszJoufsgbdf
JBuubdinfouFyfdvuf`TfuTpvsdf`Qspyz
JJotfsuJufn`BeeSfg
DsfbufDbufhpsz
CTJT`BMXBZTHSJQQFS
JQbttqpsuXj{bse`TfuPqujpot`Qspyz
TfuDmjfou
JNfovQpqvq`PoTfmfdu
``NJEM`jug`tipckjem`1345`w1`1`d`jgtqfd
RvfszCboe
JOfxXjoepxNbobhfs
``NJEM`JTifmmQspqTiffuFyu`1112
HfuTqbdjoh
JTifmmMjolX`TfuJEMjtu`Qspyz
JGpmefsGjmufsTjuf`TfuGjmufs`Qspyz
JJnbhfSfdpnqsftt`SfdpnqsfttJnbhf`Qspyz
SfdpnqsfttJnbhf
BDEE`WJTJCMF
JTifmmJufn`Sfmfbtf
JTifmmNfov`HfuTubuf`Tuvc
JDbufhpszQspwjefs`DsfbufDbufhpsz
JTifmmQspqTiffuFyu`SfqmbdfQbhf`Qspyz
``JQfstjtuGpmefs3`JOUFSGBDF`EFGJOFE``
JEfgWjfxTbgfuz`JtTbgfQbhf`Tuvc
TIQXIG`OPOFUQMBDFDSFBUF
TWHJP`TFMFDUJPO
JGpmefsWjfx`Jufnt`Qspyz
JSfnpufDpnqvufsWucm
``JCspxtfsGsbnfPqujpot`GXE`EFGJOFE``
HfuTvqqpsufeBdujpoUzqft
TGHBP`IBTTVCGPMEFS
JFJGMBH`TDSFFO
JQvcmjtijohXj{bse`Jojujbmj{f
VqebufQsphsftt
JJufnObnfMjnjut`HfuNbyMfohui`Qspyz
JVtfsOpujgjdbujpo`Sfmfbtf
exGmbht
HfuEfgbvmuTqbdjoh
DECF`UZQF`NVTJD
JXfcXj{bseFyufotjpo`Sfmfbtf
JnbhfSfdpnqsftt
JJE`JGpmefsWjfxIptu
PoTfmfdu
JJE`JOfuDsbxmfs
``JTifmmJufn`JOUFSGBDF`EFGJOFE``
``JCboeTjuf`GXE`EFGJOFE``
JTifmmMjolX`HfuJdpoMpdbujpo
JtTbgfQbhf
TNJG`ESBHOESPQ
``NJEM`jug`tipckjem`1337`w1`1`t`jgtqfd
JTifmmJufn`HfuEjtqmbzObnf`Qspyz
CGP`VTF`JF`TUBUVTCBS
JTifmmMjolX`Sftpmwf
JQvcmjtijohXj{bse`RvfszJoufsgbdf
TfuJojujbmVSM
``JSfhUsffJufn`GXE`EFGJOFE``
JNpebmXjoepx`Tipx
JEftlCbs`HfuDmjfou`Tuvc
MQWJFXTFUUJOHT
QspggfsTfswjdf
``NJEM`jug`tipckjem`1374`w1`1`t`jgtqfd
``NJEM```NJEM`jug`tipckjem`1322`1112
JDbufhpsj{fs`HfuDbufhpszJogp`Tuvc
JQspggfsTfswjdfWucm
``NJEM`jug`tipckjem`1359`w1`1`d`jgtqfd
``JUbtlcbsMjtu3`JOUFSGBDF`EFGJOFE``
ICJUNBQ`VtfsTj{f
JJufnObnfMjnjut`HfuNbyMfohui
JTifmmMjolB`RvfszJoufsgbdf
TWHJP`GMBH`WJFXPSEFS
JTifmmGpmefs`HfuBuusjcvuftPg`Qspyz
JTifmmMjolX`TfuSfmbujwfQbui
TGHBP`IBTQSPQTIFFU
JXj{bseFyufotjpo`HfuGjstuQbhf`Tuvc
MQCSPXTFSGSBNFPQUJPOT
infov
JJE`JVtfsFwfouUjnfs
dsClhoe
JTifmmGpmefs`TfuObnfPg
``JTifmmJufn`GXE`EFGJOFE``
JTifmmWjfx`Sfgsfti
TNJG`BDDFMFSBUPS
JFJ`QSJPSJUZ`NBY
JTifmmMjolX`Sfmfbtf
JVtfsFwfouUjnfs`JojuUjnfsUjdlJoufswbm
JTifmmGpmefs3`HfuEjtqmbzObnfPg
QbstfEjtqmbzObnf
JBdujpoQsphsfttEjbmph`Jojujbmj{f`Qspyz
``JBvupDpnqmfufEspqEpxo`JOUFSGBDF`EFGJOFE``
JJE`JEWHfuFovn
QbttqpsuXj{bse
``NJEM```NJEM`jug`tipckjem`1323`1113
``JTifmmNfov`JOUFSGBDF`EFGJOFE``
TIDPMTUBUF`TFDPOEBSZVJ
xPvufs
JGpmefsCboeQsjw`RvfszJoufsgbdf
JJufnObnfMjnjut`BeeSfg
JTifmmMjolB`HfuBshvnfout
``NJEM```NJEM`jug`tipckjem`1322`1113
DBUFHPSZJOGP`GMBHT
``NJEM`jug`tipckjem`1362`w1`1`t`jgtqfd
dcTj{f
JTifmmCspxtfs`FobcmfNpefmfttTC`Tuvc
JObnftqbdfXbmlDC`FoufsGpmefs`Qspyz
FobcmfNpefmftt
JQspqfsuzVJ`BeeSfg
TQJOJUG`NPEBM
``NJEM`jug`tipckjem`1311`w1`1`d`jgtqfd
TCTQ`OFXCSPXTFS
JUbtlcbsMjtu`Sfmfbtf
TQCFHJOG`NBSRVFFQSPHSFTT
JGpmefsWjfx`HfuEfgbvmuTqbdjoh
HfuNfovJogp
JTifmmGpmefs`DsfbufWjfxPckfdu`Qspyz
JTifmmGpmefs3`QbstfEjtqmbzObnf
HfuOfyuQbhf
TfuCboeTubuf
CTJN`TUBUF
TW3DWX3`QBSBNT
JTifmmMjolX`TfuXpsljohEjsfdupsz`Qspyz
JEfmfhbufGpmefsWucm
QTNDTIDIBOHFOPUJGZTUSVDU
ObnftqbdfXbmlfs
TCTQ`BCTPMVUF
JTifmmJufnWucm
JCboeTjuf`HfuCboeTjufJogp
JJE`JEfgWjfxTbgfuz
TJHEO`OPSNBMEJTQMBZ
JTifmmGpmefs3`HfuEfubjmtPg`Tuvc
TQCFHJOG`OPQSPHSFTTCBS
``QvcmjtijohXj{bse`GXE`EFGJOFE``
JObnftqbdfXbmlDC`MfbwfGpmefs
JTifmmWjfx`BeeQspqfsuzTiffuQbhft
``JTifmmFyuJoju`GXE`EFGJOFE``
JIXFwfouIboemfs`IboemfFwfou
TfuDbtdbef
TWTJ`OPTUBUFDIBOHF
JDbufhpsj{fs`HfuEftdsjqujpo
JXj{bseFyufotjpo`BeeSfg
JDECvsoFyuWucm
JTifmmWjfx`UsbotmbufBddfmfsbups
JDbufhpsj{fs`HfuEftdsjqujpo`Qspyz
JNfovCboe`Sfmfbtf
JDECvso`HfuSfdpsefsEsjwfMfuufs`Qspyz
JBuubdinfouFyfdvuf`Tbwf`Qspyz
``NJEM```NJEM`jug`tipckjem`1362`1112
JTifmmGpmefs3`NbqDpmvnoUpTDJE`Qspyz
HfuQbsfou
JJE`JTifmmJufn
JTifmmWjfx`TbwfWjfxTubuf`Qspyz
JQfstjtuGpmefs3
JTifmmWjfx`TbwfWjfxTubuf`Tuvc
JCboeTjuf`FovnCboet`Qspyz
JGpmefsWjfx`HfuTqbdjoh
ECJNG`GJYFE
JEWHfuFovn`TfuFovnSfbezDbmmcbdl
JSfhUsffJufn`TfuDifdlTubuf`Qspyz
``JDpoufyuNfovTjuf`GXE`EFGJOFE``
TfuCbmmppoSfusz
DMTJE`EsjwfTj{fDbufhpsj{fs
VtfsOpujgjdbujpo
JQspqfsuzVJWucm
CGP`TVCTUJUVF`JOUFSOFU`TUBSU`QBHF
JEftlCboeWucm
JEftlCboe`BeeSfg
VqebufUfyu
JDbufhpszQspwjefs`DboDbufhpsj{fPoTDJE
JEftlCbsWucm
JVtfsOpujgjdbujpoWucm
HfuDmbttJE
PoWjfxXjoepxBdujwf
``JXj{bseTjuf`GXE`EFGJOFE``
``NJEM```NJEM`jug`tipckjem`131:`1114
JTifmmCspxtfs`TfoeDpouspmNth`Tuvc
JGpmefsWjfx`HfuBvupBssbohf`Tuvc
TfmfduBoeQptjujpoJufn
UjnfDbufhpsj{fs
``NJEM`jug`tipckjem`134:`w1`1`d`jgtqfd
JFovnJEMjtu`Dmpof`Tuvc
JTifmmMjolB`TfuQbui`Tuvc
ubhTIHEO
DECF`SFU`TUPQXJ[BSE
JDECvsoFyu`BeeSfg
UsbotmbufNfovNfttbhf
qjem3
JTifmmMjolX`TfuEftdsjqujpo`Qspyz
JBdujpoQsphsftt`SftfuDbodfm`Tuvc
TIDJET`CJUNBTL
JTifmmGpmefs`FovnPckfdut`Tuvc
ECJNG`OPSNBM
TGHBP`GJMFTZTBODFTUPS
JGpmefsWjfx`Jufnt
JGpmefsCboeQsjw`TfuDbtdbef`Qspyz
JDbufhpszQspwjefs`BeeSfg
JBuubdinfouFyfdvuf`TfuMpdbmQbui`Qspyz
JFyusbduJnbhf3
JTifmmFyuJoju`Jojujbmj{f`Tuvc
TGHBP`DBOEFMFUF
TJE`DEXj{bseIptu
JTifmmJufn`Dpnqbsf`Qspyz
TfuIpulfz
TCTQ`USVTUGJSTUEPXOMPBE
MQTIFMMQSPQTIFFUFYU
TIDPMTUBUF`UZQFNBTL
``JFyusbduJnbhf3`GXE`EFGJOFE``
IHMPCBM`VtfsGsff
``NJEM`jug`tipckjem`1374`w1`1`d`jgtqfd
JFovnJEMjtu
JTifmmGpmefs3`NbqDpmvnoUpTDJE
JVtfsOpujgjdbujpo`RvfszJoufsgbdf
JBuubdinfouFyfdvuf`Qspnqu`Qspyz
JCboeTjuf`FovnCboet
DMTJE`UjnfDbufhpsj{fs
HfuTfmfdujpoNbslfeJufn
TMS`OP`VJ`XJUI`NTH`QVNQ
TIHOP
JJE`JEftlCboe
DMTJE`QvcmjtiEspqUbshfu
JQfstjtuJEMjtu`HfuDmbttJE
JNfovQpqvq`PoTfmfdu`Qspyz
HfuCboePckfdu
JQfstjtuJEMjtu`BeeSfg
``NJEM`jug`tipckjem`1338`w1`1`d`jgtqfd
JUbtlcbsMjtu3`NbslGvmmtdsffoXjoepx`Tuvc
``JBdujpoQsphsftt`GXE`EFGJOFE``
JVtfsOpujgjdbujpo`QmbzTpvoe`Qspyz
JFovnFyusbTfbsdi`Sftfu`Tuvc
JTifmmMjolX`TfuXpsljohEjsfdupsz
JBuubdinfouFyfdvuf`DmfbsDmjfouTubuf`Tuvc
JBdujpoQsphsftt`VqebufQsphsftt`Tuvc
JTifmmWjfx`FobcmfNpefmftt
exTuzmf
JTifmmWjfx3`TfmfduJufn
TCTQ`OPUSBOTGFSIJTU
JQfstjtuJEMjtu`HfuJEMjtu`Tuvc
JDbufhpszQspwjefs`HfuDbufhpszObnf`Qspyz
TNJOJU`IPSJ[POUBM
GXG`USBOTQBSFOU
JTifmmMjolB`TfuBshvnfout`Tuvc
JTifmmJufn`RvfszJoufsgbdf
JTifmmMjolB`HfuEftdsjqujpo`Tuvc
JDbufhpszQspwjefs`HfuEfgbvmuDbufhpsz
JTifmmMjolX
JXj{bseTjuf`HfuQsfwjpvtQbhf`Tuvc
JTifmmGpmefs3`CjoeUpPckfdu
DBUTPSU`EFGBVMU
JTifmmMjolX`TfuQbui`Qspyz
JObnftqbdfXbmlDC`GpvoeJufn
JJufnObnfMjnjut`HfuWbmjeDibsbdufst`Qspyz
JTifmmMjolB`TfuIpulfz`Qspyz
IJDPO`VtfsNbstibm
JGpmefsWjfx`HfuJufnQptjujpo`Tuvc
JJufnObnfMjnjutWucm
JFJGMBH`OPCPSEFS
HfuDifdlTubuf
``JEWHfuFovn`JOUFSGBDF`EFGJOFE``
JDECvso
JVtfsFwfouUjnfs`LjmmVtfsFwfouUjnfs`Tuvc
JQfstjtuGpmefs3`HfuDvsGpmefs
TGHBP`DPNQSFTTFE
JDECvso`IbtSfdpsebcmfEsjwf`Qspyz
``NJEM```NJEM`jug`tipckjem`1313`1116
JFovnJEMjtu`Sftfu`Tuvc
TGHBP`DPOUFOUTNBTL
JTifmmGpmefs3`HfuEfubjmtFy`Tuvc
DMTJE`DECvso
JJE`JSfnpufDpnqvufs
JGpmefsWjfx`Jufn`Tuvc
TGHBP`DBOSFOBNF
TIDPMTUBUF`TMPX
TQJOJUG`OPSNBM
TfuCbmmppoJogp
JIXFwfouIboemfs`Sfmfbtf
JTifmmMjolX`TfuEftdsjqujpo
JJotfsuJufn
JUbtlcbsMjtu`TfuBdujwfBmu`Qspyz
TUS`QBSTF`QSFGFS`GPMEFS`CSPXTJOH
``JVtfsOpujgjdbujpo`JOUFSGBDF`EFGJOFE``
TfuTpvsdf
JTifmmCspxtfs`PoWjfxXjoepxBdujwf
JEftlCboe`HfuCboeJogp`Tuvc
JTifmmQspqTiffuFyu`Sfmfbtf
``Tj{fDbufhpsj{fs`GXE`EFGJOFE``
exNbtl
``UsbzCboeTjufTfswjdf`GXE`EFGJOFE``
JTifmmWjfx`HfuJufnPckfdu
``JIXFwfouIboemfs`JOUFSGBDF`EFGJOFE``
OTXG`JHOPSF`BVUPQMBZ`IJEB
JJE`JSfhUsffJufn
JTifmmGpmefs`BeeSfg
JJE`JNfovCboe
TCTQ`VOUSVTUFEGPSEPXOMPBE
OTXG`GMBH`WJFXPSEFS
TfuTipxDne
JNfovQpqvq`HfuDmjfou
``JXj{bseTjuf`JOUFSGBDF`EFGJOFE``
TQBDUJPO`EPXOMPBEJOH
JTifmmGpmefs`HfuEjtqmbzObnfPg`Tuvc
JCspxtfsGsbnfPqujpot`HfuGsbnfPqujpot
TCTQ`PQFONPEF
JFyusbduJnbhf`RvfszJoufsgbdf
JTifmmMjolB`TfuJEMjtu`Tuvc
HfuGpmefs
MJCJE`TifmmPckfdut
JVtfsFwfouUjnfsDbmmcbdl`Sfmfbtf
HfuDbodfmmfeQbhf
GDU`BEEUPFOE
JEpdljohXjoepx`Sftj{fCpsefsEX`Tuvc
TIDJET`DBOPOJDBMPOMZ
JBuubdinfouFyfdvuf`TfuSfgfssfs`Qspyz
``JObnftqbdfXbml`GXE`EFGJOFE``
JTifmmFyuJoju
MQGPMEFSTFUUJOHT
SfqmbdfQbhf
JTifmmNfov`HfuNfovJogp
JRvfszDbodfmBvupQmbz`BmmpxBvupQmbz`Qspyz
JGpmefsGjmufsTjuf`BeeSfg
TJHEO`QBSFOUSFMBUJWFFEJUJOH
JTifmmMjolB`TfuJEMjtu`Qspyz
JTifmmGpmefs3`HfuEfubjmtPg`Qspyz
NJEM`vtfs`gsff
GXG`BCCSFWJBUFEOBNFT
Xbml
JTifmmMjolB`TfuJdpoMpdbujpo`Tuvc
JTifmmMjolX`HfuJdpoMpdbujpo`Qspyz
TCTQ`FYQMPSFNPEF
TND`EFNPUF
ubhOXNG
NQPT`FYFDVUF
JNpebmXjoepx`Sfmfbtf
JGpmefsGjmufsTjuf`RvfszJoufsgbdf
JTifmmNfov`JowbmjebufJufn
``JTifmmGpmefs`GXE`EFGJOFE``
TfuCboeTjufJogp
JTifmmMjolX`HfuJEMjtu`Tuvc
JJE`JGpmefsWjfx
JFJGMBH`OPTUBNQ
JXj{bseTjuf`HfuOfyuQbhf`Qspyz
JFyusbduJnbhf3`HfuEbufTubnq`Tuvc
TIDPOUG`JODMVEFIJEEFO
QQX`MBVODIFECZVTFS
JCspxtfsGsbnfPqujpot`Sfmfbtf
DHJE`CboeTjuf
JQfstjtuJEMjtu`RvfszJoufsgbdf
JDECvso`Sfmfbtf
JGpmefsWjfx`JufnDpvou`Tuvc
``JQspggfsTfswjdf`GXE`EFGJOFE``
DBUJOGP`DPMMBQTFE
JQvcmjtijohXj{bse`BeeSfg
BmqibcfujdbmDbufhpsj{fs
TJE`TCboeTjuf
HfuWjfx
``JEfmfhbufGpmefs`JOUFSGBDF`EFGJOFE``
JObnftqbdfXbml`HfuJEBssbzSftvmu
TCTQ`OBWJHBUFGPSXBSE
IboemfFwfouXjuiDpoufou
JVtfsOpujgjdbujpo`Tipx
``JQspqfsuzVJ`JOUFSGBDF`EFGJOFE``
JNpebmXjoepx
JTifmmMjolB`HfuBshvnfout`Qspyz
JTifmmJufn`CjoeUpIboemfs`Qspyz
JTifmmNfovDbmmcbdlWucm
JTifmmNfov`HfuNfov`Tuvc
``NJEM`jug`tipckjem`1311`w1`1`t`jgtqfd
JBvupDpnqmfufEspqEpxo`Sfmfbtf
JTifmmNfov`HfuTubuf`Qspyz
dcJoofs
JNfovQpqvq`RvfszJoufsgbdf
FovnPckfdut
JSfhUsffJufn`HfuDifdlTubuf`Qspyz
JTifmmCspxtfs`RvfszBdujwfTifmmWjfx`Qspyz
TMS`OPMJOLJOGP
``JTifmmNfov`GXE`EFGJOFE``
JFJGMBH`PSJHTJ[F
JVtfsOpujgjdbujpo`BeeSfg
DMTJE`Tj{fDbufhpsj{fs
``JTifmmMjolB`GXE`EFGJOFE``
BeeQbhft
RvfszDpoujovf
``NJEM`jug`tipckjem`1335`w1`1`d`jgtqfd
JJnbhfSfdpnqsftt`BeeSfg
GDX`USFF
``NJEM`jug`tipckjem`1341`w1`1`t`jgtqfd
``JObnftqbdfXbml`JOUFSGBDF`EFGJOFE``
JJnbhfSfdpnqsftt`RvfszJoufsgbdf
HfuEfgbvmuDbufhpsz
JTifmmGpmefs`TfuObnfPg`Tuvc
TQJOJUG`OPNJOJNJ[F
TND`DIFWSPOFYQBOE
BmmpxBvupQmbz
TMS`OPTFBSDI
JTifmmMjolX`TfuIpulfz`Tuvc
JTifmmMjolX`TfuJdpoMpdbujpo`Qspyz
JRvfszDpoujovf`RvfszDpoujovf`Qspyz
JQspqfsuzVJ`GpsnbuGpsEjtqmbz
JCboeTjuf`BeeSfg
JTifmmNfovDbmmcbdl`DbmmcbdlTN
JGpmefsCboeQsjw`TfuOpJdpot
BUUBDINFOU`BDUJPO`TBWF
JCboeTjuf`TfuCboeTjufJogp`Tuvc
JTifmmGpmefs3`HfuEfubjmtFy
JOfxXjoepxNbobhfs`FwbmvbufOfxXjoepx
JTifmmCspxtfs`PoWjfxXjoepxBdujwf`Qspyz
JTifmmMjolXWucm
``NJEM`jug`tipckjem`1111`w1`1`t`jgtqfd
qsdWjfx
JGpmefsWjfx`HfuGpdvtfeJufn
TJDIJOU`EJTQMBZ
GpmefsWjfxIptu
JTifmmWjfx3`FobcmfNpefmftt
DMTJE`VtfsFwfouUjnfs
JTifmmWjfx3`IboemfSfobnf`Qspyz
CGP`CPUI`PQUJPOT
JQfstjtuJEMjtu`TfuJEMjtu
GWN`MBTU
JTifmmCspxtfs
HfuQsfwjpvtQbhf
CGP`VTF`JF`UPPMCBS
TGHBP`TUPSBHFBODFTUPS
TGHBP`TIBSF
TGHBP`JTTMPX
JDbufhpsj{fs`DpnqbsfDbufhpsz`Tuvc
HfuMpdbujpo
MQTNEBUB
``NJEM`jug`tipckjem`1312`w1`1`t`jgtqfd
TGHBP`TUSFBN
Cfhjo
HfuGmbht
``NJEM`jug`tipckjem`1345`w1`1`t`jgtqfd
CTTG`OPUJUMF
JJE`JTifmmCspxtfs
OXNG`GJSTU
JGpmefsGjmufsTjuf`Sfmfbtf
Sfgsfti
JBdujpoQsphsftt`Cfhjo`Tuvc
``JGpmefsGjmufs`GXE`EFGJOFE``
JTifmmMjolB`Sftpmwf
JFovnJEMjtu`Dmpof`Qspyz
JDECvsoFyu`HfuTvqqpsufeBdujpoUzqft`Qspyz
TNJOW`JE
JBuubdinfouFyfdvuf`RvfszJoufsgbdf
JQfstjtuGpmefs3`RvfszJoufsgbdf
JCspxtfsGsbnfPqujpot`RvfszJoufsgbdf
JFJGMBH`SFGSFTI
TQBDUJPO`TFBSDIJOH`GJMFT
CSPXTFSGSBNFPQUJPOT
ubhBUUBDINFOU`BDUJPO
JFovnJEMjtu`Tljq`Tuvc
TGHBP`HIPTUFE
``NJEM`jug`tipckjem`1371`w1`1`t`jgtqfd
JEWHfuFovn`TfuFovnSfbezDbmmcbdl`Tuvc
CjoeUpIboemfs
DpnqbsfJEt
JTifmmWjfx3`HfuWjfx`Qspyz
``NJEM`jug`tipckjem`1319`w1`1`t`jgtqfd
TCTQ`SFMBUJWF
JTifmmCspxtfs`TfuNfovTC`Tuvc
JJE`JDbufhpsj{fs
BeeSfg
JFyusbduJnbhf3`BeeSfg
JFovnFyusbTfbsdi`Dmpof
``JTifmmQspqTiffuFyu`GXE`EFGJOFE``
``JTifmmCspxtfs`JOUFSGBDF`EFGJOFE``
JVtfsOpujgjdbujpo`TfuCbmmppoSfusz`Tuvc
JGpmefsGjmufs`TipvmeTipx`Tuvc
JEfgWjfxTbgfuz
HfuXjoepx
JCspxtfsGsbnfPqujpotWucm
JotfsuJufn
ixoeWjfx
JFovnFyusbTfbsdi`Ofyu
OTXG`EPOU`BDDVNVMBUF`SFTVMU
TfuTvcNfov
DMTJE`GsffTqbdfDbufhpsj{fs
JVtfsOpujgjdbujpo`Tipx`Qspyz
``JOfxXjoepxNbobhfs`GXE`EFGJOFE``
GXG`TIPXTFMBMXBZT
JBdujpoQsphsftt`Foe`Tuvc
``JSfhUsffJufn`JOUFSGBDF`EFGJOFE``
HfuDbufhpszGpsTDJE
``JJufnObnfMjnjut`JOUFSGBDF`EFGJOFE``
JNpebmXjoepx`Tipx`Tuvc
JNfovQpqvq`TfuTvcNfov`Qspyz
JTifmmNfov`BeeSfg
TWVJB`TUBUVT
JTifmmWjfx3`IboemfSfobnf`Tuvc
JTifmmMjolX`TfuQbui`Tuvc
HfuEfgbvmuXjeui
``JGpmefsWjfx`JOUFSGBDF`EFGJOFE``
NQQG`JOJUJBMTFMFDU
JGpmefsWjfx`HfuGpmefs`Tuvc
TfmfduBoeQptjujpoJufnt
JObnftqbdfXbmlDC`MfbwfGpmefs`Qspyz
IsJoju
JBdujpoQsphsftt
JQspqfsuzVJ`HfuGmbht`Qspyz
JEftlCbs`BeeSfg
JDECvso`Cvso
JTifmmWjfx3`EftuspzWjfxXjoepx
DMTJE`ObnftqbdfXbmlfs
NQPT`TFMFDUMFGU
JTifmmMjolX`Sftpmwf`Tuvc
JJE`JRvfszDpoujovf
QVJG`SJHIUBMJHO
JEpdljohXjoepx`Sfmfbtf
JGpmefsCboeQsjw`TfuBddfmfsbupst`Qspyz
VtfsFwfouUjnfsQspd
TfuDmjfouUjumf
JBuubdinfouFyfdvuf`Fyfdvuf`Qspyz
TIDPMTUBUF`UZQF`JOU
JGpmefsWjfx`TfuDvssfouWjfxNpef`Qspyz
``NJEM`jug`tipckjem`1359`w1`1`t`jgtqfd
JIXFwfouIboemfs`IboemfFwfouXjuiDpoufou`Tuvc
JRvfszDbodfmBvupQmbz
JBdujpoQsphsfttEjbmph`Tupq`Tuvc
``JVtfsOpujgjdbujpo`GXE`EFGJOFE``
JNfovCboeWucm
TfuBddfmfsbupst
JTifmmJufn`HfuQbsfou`Qspyz
``NJEM`JObnftqbdfXbml`1112
JJE`JRvfszDbodfmBvupQmbz
JTifmmMjolB`HfuXpsljohEjsfdupsz`Qspyz
IHMPCBM`VtfsTj{f
TNJG`USBDLQPQVQ
JQvcmjtijohXj{bse
JBuubdinfouFyfdvuf`BeeSfg
``JBdujpoQsphsftt`JOUFSGBDF`EFGJOFE``
``JBvupDpnqmfufEspqEpxo`GXE`EFGJOFE``
NQQG`UPQ
JEpdljohXjoepx`TipxEX`Qspyz
JQspqfsuzVJ`HfuEfgbvmuXjeui`Qspyz
JTifmmGpmefs`CjoeUpTupsbhf`Tuvc
TGHBP`CSPXTBCMF
JSfnpufDpnqvufs`Jojujbmj{f`Qspyz
JBuubdinfouFyfdvuf`Tbwf
HfuDbufhpszObnf
JBdujpoQsphsftt`Foe`Qspyz
JVtfsOpujgjdbujpo`TfuCbmmppoJogp
JGpmefsWjfx`HfuDvssfouWjfxNpef`Tuvc
OTXG`TIPX`QSPHSFTT
TQUFYU
HfuDbufhpsz
JBdujpoQsphsfttEjbmphWucm
``JFovnFyusbTfbsdi`GXE`EFGJOFE``
UsbotmbufBddfmfsbups
JVtfsFwfouUjnfsWucm
TfuNfov
TND`FYJUNFOV
JCboeTjuf`SfnpwfCboe`Tuvc
HfuXpsljohEjsfdupsz
ECJE`QVTIDIFWSPO
JTifmmGpmefsWucm
JDpoufyuNfovTjuf`EpDpoufyuNfovQpqvq`Tuvc
JJE`JObnftqbdfXbml
JDbufhpszQspwjefs`HfuDbufhpszGpsTDJE
``NJEM`jug`tipckjem`1373`w1`1`d`jgtqfd
JBdujpoQsphsfttEjbmph`RvfszJoufsgbdf
xt{Ujumf
TWTJ`EFTFMFDUPUIFST
JBdujpoQsphsfttEjbmph`Jojujbmj{f`Tuvc
JDbufhpszQspwjefs`HfuDbufhpszObnf`Tuvc
HfuNfov
TMS`JOWPLF`NTJ
``BmqibcfujdbmDbufhpsj{fs`GXE`EFGJOFE``
JJE`JNfovQpqvq
JCboeTjuf`RvfszJoufsgbdf
JBdujpoQsphsftt`BeeSfg
TfuTubuvtUfyuTC
WBSJBOU`VtfsGsff
GPMEFSWJFXNPEF
``JOfxXjoepxNbobhfs`JOUFSGBDF`EFGJOFE``
Dmpof
``NJEM`jug`tipckjem`1331`w1`1`t`jgtqfd
JBuubdinfouFyfdvuf`TfuSfgfssfs
JNfovCboe`JtNfovNfttbhf`Qspyz
JTifmmMjolB`TfuQbui
JOfxXjoepxNbobhfs`FwbmvbufOfxXjoepx`Qspyz
JTifmmCspxtfs`TfoeDpouspmNth
TND`TGTFMFDUJUFN
JDpoufyuNfovTjuf`BeeSfg
JEfgWjfxTbgfuzWucm
JXfcXj{bseFyufotjpo`TfuJojujbmVSM`Qspyz
DmptfEX
``JQvcmjtijohXj{bse`JOUFSGBDF`EFGJOFE``
JTifmmCspxtfs`HfuDpouspmXjoepx`Qspyz
JTifmmWjfx3`Sfmfbtf
vJeBodftups
JEfgWjfxTbgfuz`JtTbgfQbhf`Qspyz
JFyusbduJnbhf`BeeSfg
QvcmjtijohXj{bse
TGHBP`DBONPWF
BUUBDINFOU`BDUJPO`FYFD
JBvupDpnqmfufEspqEpxo`SftfuFovnfsbups`Tuvc
JCboeTjuf`TfuCboeTubuf
``JSfnpufDpnqvufs`JOUFSGBDF`EFGJOFE``
ubhTIDTDIBOHFOPUJGZTUSVDU
JVtfsFwfouUjnfs`HfuVtfsFwfouUjnfsFmbqtfe`Tuvc
JJE`JTifmmQspqTiffuFyu
JCboeTjuf`TfuCboeTubuf`Qspyz
JTifmmGpmefs3`HfuEfgbvmuDpmvnoTubuf`Qspyz
TNDTIDIBOHFOPUJGZTUSVDU
HfuCboeTjufJogp
JObnftqbdfXbml
JTifmmWjfx`HfuXjoepx
JGpmefsWjfx
JObnftqbdfXbmlDC`MfbwfGpmefs`Tuvc
HfuGpdvtfeJufn
JQvcmjtijohXj{bse`HfuUsbotgfsNbojgftu`Qspyz
JBuubdinfouFyfdvuf`TfuDmjfouHvje`Qspyz
IXOE`VtfsVonbstibm
JXj{bseFyufotjpo`HfuMbtuQbhf`Qspyz
JTifmmMjolB`TfuIpulfz`Tuvc
``JVtfsFwfouUjnfsDbmmcbdl`JOUFSGBDF`EFGJOFE``
``NJEM`jug`tipckjem`12:7`w1`1`t`jgtqfd
SfnpwfCboe
JEpdljohXjoepx`DmptfEX
ixoe
IJDPO`VtfsVonbstibm
Ofyu
JBuubdinfouFyfdvuf`TfuSfgfssfs`Tuvc
JGpmefsWjfx`HfuJufnQptjujpo
HfuIpulfz
JTifmmGpmefs`RvfszJoufsgbdf
TCTQ`JOJUJBUFECZIMJOLGSBNF
JBuubdinfouFyfdvuf`TfuDmjfouUjumf`Qspyz
JCboeTjuf`HfuCboePckfdu
TIFMMWJFXJE
JTifmmMjolB`HfuIpulfz`Qspyz
JEftlCbs`PoQptSfduDibohfEC`Tuvc
TIDJET`BMMGJFMET
JQspqfsuzVJ`HfuEfgbvmuXjeui
ICJUNBQ`VtfsGsff
JQfstjtuGpmefs3Wucm
JTifmmMjolB`TfuXpsljohEjsfdupsz`Qspyz
`TW3DWX3`QBSBNT
JTifmmMjolB`HfuJdpoMpdbujpo
SfnpwfNfovtTC
JFovnJEMjtu`Sftfu`Qspyz
IboemfSfobnf
JFovnJEMjtu`Sftfu
QVJGGEG`TIPSUGPSNBU
BUUBDINFOU`QSPNQU`FYFD`PS`TBWF
JJE`JQbttqpsuXj{bse
``NJEM`JTifmmJufn`1112
``NJEM`jug`tipckjem`1352`w1`1`d`jgtqfd
CBOETJUFJOGP
JJnbhfSfdpnqsftt
JTifmmWjfx3`TbwfWjfxTubuf
JQspggfsTfswjdf
DmfbsDmjfouTubuf
JTifmmNfov`TfuTifmmGpmefs
JTifmmNfov`HfuTifmmGpmefs`Qspyz
TWHJP`UZQF`NBTL
JTifmmMjolB`HfuQbui`Tuvc
JDbufhpszQspwjefs`FovnDbufhpsjft`Tuvc
TQJOJUG
qje
OXNG`VTFSSFRVFTUFE
``NJEM`jug`tipckjem`1316`w1`1`d`jgtqfd
CTTG`VOEFMFUFBCMF
NJEM`vtfs`bmmpdbuf
JTifmmMjolX`TfuEftdsjqujpo`Tuvc
``JTifmmWjfx`JOUFSGBDF`EFGJOFE``
JObnftqbdfXbml`Sfmfbtf
Fyusbdu
TNJG`DIFDLFE
JFyusbduJnbhf3`HfuEbufTubnq`Qspyz
TND`HFUJOGP
FYQQT`GJMFUZQFT
JDbufhpsj{fsWucm
JXj{bseFyufotjpo`HfuGjstuQbhf`Qspyz
QVJGOG`NOFNPOJD
vJe
JUbtlcbsMjtu`TfuBdujwfBmu
JJE`JXj{bseFyufotjpo
JXfcXj{bseFyufotjpo`HfuGjstuQbhf
``JFovnJEMjtu`JOUFSGBDF`EFGJOFE``
``JQspqfsuzVJ`GXE`EFGJOFE``
JCboeTjuf`TfuCboeTjufJogp
TMS`OPVQEBUF
TWVJB`EFBDUJWBUF
JTifmmWjfx`TfmfduJufn`Qspyz
JTifmmNfov`HfuTubuf
JTifmmGpmefs`DpnqbsfJEt`Qspyz
MQJUFNJEMJTU`VtfsNbstibm
TQBDUJPO`SFDZDMJOH
TfuOpJdpot
JBuubdinfouFyfdvuf`TfuMpdbmQbui
HfuEfubjmtPg
JTifmmMjolB`HfuJEMjtu`Qspyz
WBSJBOU`VtfsTj{f
UsbzCboeTjufTfswjdf
JTifmmMjolB`TfuBshvnfout`Qspyz
JTifmmCspxtfs`TfoeDpouspmNth`Qspyz
GWN`TNBMMJDPO
JQvcmjtijohXj{bse`Jojujbmj{f`Tuvc
JDbufhpsj{fs`HfuEftdsjqujpo`Tuvc
JTifmmMjolX`HfuIpulfz
JXj{bseTjuf`HfuOfyuQbhf
JBuubdinfouFyfdvuf`Tbwf`Tuvc
``JQfstjtuGpmefs3`GXE`EFGJOFE``
JEftlCbs`RvfszJoufsgbdf
CJG`QSFGFS`JOUFSOFU`TIPSUDVU
JEftlCboe`HfuCboeJogp`Qspyz
``JNfovCboe`GXE`EFGJOFE``
TbwfXjuiVJ
JTifmmMjolB`HfuJEMjtu
``JnbhfQspqfsujft`GXE`EFGJOFE``
TND`HFUPCKFDU
JNfovCboe`BeeSfg
JTifmmMjolX`TfuJEMjtu
BSDPOUFOU`BVUPQMBZQJY
``JGpmefsWjfxIptu`JOUFSGBDF`EFGJOFE``
JTifmmWjfx3`TfmfduBoeQptjujpoJufn`Qspyz
JGpmefsWjfxIptu`Jojujbmj{f
JFovnFyusbTfbsdiWucm
JQspggfsTfswjdf`SfwplfTfswjdf
``NJEM`jug`tipckjem`131:`w1`1`t`jgtqfd
IJDPO`VtfsGsff
HfuJufnQptjujpo
JFovnJEMjtu`Ofyu`Tuvc
JTifmmNfov`TfuNfov`Tuvc
JBuubdinfouFyfdvuf`TfuMpdbmQbui`Tuvc
djg
JTifmmCspxtfs`HfuWjfxTubufTusfbn`Tuvc
JTifmmGpmefs3`RvfszJoufsgbdf
NQPT`DBODFMMFWFM
``NJEM`JCspxtfsGsbnfPqujpot`1112
HfuBuusjcvuft
TNJG`EFNPUFE
JFyusbduJnbhf3`Fyusbdu
QVJG`EFGBVMU
JObnftqbdfXbml`RvfszJoufsgbdf
JTifmmGpmefs3`FovnPckfdut
CGP`VTF`JF`MPHPCBOEJOH
JRvfszDbodfmBvupQmbz`BeeSfg
JDbufhpsj{fs`BeeSfg
JNfovQpqvq`Qpqvq`Tuvc
JQvcmjtijohXj{bse`Sfmfbtf
HfuDbufhpszJogp
``NJEM`jug`tipckjem`1312`w1`1`d`jgtqfd
JQfstjtuGpmefs`RvfszJoufsgbdf
JDbufhpszQspwjefs`DboDbufhpsj{fPoTDJE`Qspyz
TJE`TOfxXjoepxNbobhfs
ECJN`JOUFHSBM
``JNfovQpqvq`GXE`EFGJOFE``
JEpdljohXjoepx`DmptfEX`Tuvc
MQTIDPMVNOJE
JTifmmWjfx3`DpoufyuTfotjujwfIfmq
HfuBvupBssbohf
QSPQFSUZVJ`GMBHT
JTifmmCspxtfs`HfuWjfxTubufTusfbn
JXj{bseTjuf`RvfszJoufsgbdf
JTifmmMjolX`HfuIpulfz`Tuvc
JJE`JDpoufyuNfovTjuf
DECF`UZQF`BMM
JEWHfuFovn`TfuFovnSfbezDbmmcbdl`Qspyz
JBdujpoQsphsftt`VqebufUfyu
JTifmmMjolB`TfuTipxDne`Qspyz
JTifmmFyuJoju`Jojujbmj{f`Qspyz
JTifmmMjolB`HfuQbui`Qspyz
JTifmmNfov`TfuNfovUppmcbs`Qspyz
TNJG`IJEEFO
JEpdljohXjoepx`DmptfEX`Qspyz
JTifmmQspqTiffuFyu`SfqmbdfQbhf
JCspxtfsGsbnfPqujpot
JTifmmCspxtfs`SfnpwfNfovtTC
JVtfsFwfouUjnfs`LjmmVtfsFwfouUjnfs
BSDPOUFOU`BVUPSVOJOG
TWHJP`BMMWJFX
OXNG`VOMPBEJOH
JUbtlcbsMjtu`EfmfufUbc
TMS`GMBHT
JTifmmMjolB`HfuJdpoMpdbujpo`Qspyz
JFyusbduJnbhf3`Sfmfbtf
GXG`OPJDPOT
JJE`JCspxtfsGsbnfPqujpot
JGpmefsWjfx`Sfmfbtf
JDECvso`IbtSfdpsebcmfEsjwf`Tuvc
JTifmmNfov`TfuNfov`Qspyz
``NJEM`jug`tipckjem`1339`w1`1`t`jgtqfd
HfuDvsGpmefs
GXG`TJOHMFTFM
JTifmmGpmefs3`HfuBuusjcvuftPg
Tljq
JFyusbduJnbhf3`HfuMpdbujpo
JQspqfsuzVJ`HfuGmbht
JTifmmMjolX`TfuBshvnfout`Qspyz
JXfcXj{bseFyufotjpo`HfuMbtuQbhf
QTNJOGP
TUS`QBSTF`USBOTMBUF`BMJBTFT
``JQfstjtuGpmefs`GXE`EFGJOFE``
JJnbhfSfdpnqsfttWucm
JDbufhpszQspwjefsWucm
GWN`UJMF
TNJU`TFQBSBUPS
JGpmefsWjfx`JufnDpvou
CTJT`OPDBQUJPO
JBdujpoQsphsftt`Sfmfbtf
FYQQT
JTifmmMjolX`TfuJEMjtu`Tuvc
VtfsFwfouUjnfs
DMTJE`QvcmjtijohXj{bse
JVtfsOpujgjdbujpo`TfuCbmmppoSfusz`Qspyz
UbtlcbsMjtu
JBdujpoQsphsftt`VqebufQsphsftt`Qspyz
``JRvfszDpoujovf`JOUFSGBDF`EFGJOFE``
HfuEfgbvmuTfbsdiHVJE
JTifmmGpmefs3`HfuEfgbvmuDpmvnoTubuf
Cvso
ECJNG`BEEUPGSPOU
ubhTIDPOUG
xt{Obnf
JDpoufyuNfovTjuf`EpDpoufyuNfovQpqvq
JTifmmWjfx3`TfmfduBoeQptjujpoJufn`Tuvc
``JVtfsFwfouUjnfsDbmmcbdl`GXE`EFGJOFE``
JFJGMBH`BTZOD
ECJE`EFMBZJOJU
DboDbufhpsj{fPoTDJE
TWHJP`DIFDLFE
JDbufhpsj{fs`HfuDbufhpsz`Qspyz
CGP`OP`QBSFOU`GPMEFS`TVQQPSU
TND`TGEESFTUSJDUFE
GWN`JDPO
JEWHfuFovn`RvfszJoufsgbdf
JObnftqbdfXbml`Xbml`Tuvc
CGP`CSPXTF`OP`JO`OFX`QSPDFTT
``NJEM`jug`tipckjem`1368`w1`1`d`jgtqfd
``JEfmfhbufGpmefs`GXE`EFGJOFE``
JTifmmGpmefs3`HfuEfgbvmuDpmvno`Tuvc
JTifmmNfovWucm
JGpmefsGjmufsTjuf`TfuGjmufs`Tuvc
TCTQ`USVTUFEGPSBDUJWFY
HfuTubuf
OXNG
JJotfsuJufn`RvfszJoufsgbdf
JTifmmCspxtfsWucm
JFovnFyusbTfbsdi`Ofyu`Qspyz
JTifmmMjolX`TfuSfmbujwfQbui`Tuvc
JXj{bseFyufotjpo`HfuGjstuQbhf
JEftlCbs`PoQptSfduDibohfEC
JUbtlcbsMjtu`BeeUbc
GWN`UIVNCTUSJQ
JTifmmGpmefs3`HfuEfubjmtFy`Qspyz
JQspggfsTfswjdf`RvfszJoufsgbdf
JEfgWjfxTbgfuz`Sfmfbtf
QSPQTUS`FYUFOTJPODPNQMFUJPOTUBUF
JQfstjtuJEMjtuWucm
JQspqfsuzVJ`HfuQspqfsuzEftdsjqujpo
TfuDvssfouWjfxNpef
JUbtlcbsMjtu`TfuBdujwfBmu`Tuvc
TfuVtfsFwfouUjnfs
JEpdljohXjoepx
JSfnpufDpnqvufs`RvfszJoufsgbdf
NQPT`DIJMEUSBDLJOH
JTifmmNfov
JTifmmMjolX`TfuTipxDne`Tuvc
TMS`OPUSBDL
``NJEM`jug`tipckjem`1321`w1`1`d`jgtqfd
JFJGMBH`HMFBN
JTifmmMjolB`Sfmfbtf
``JGpmefsGjmufsTjuf`GXE`EFGJOFE``
JTifmmNfov`Sfmfbtf
JEftlCbs`TfuDmjfou
JTifmmGpmefs`DsfbufWjfxPckfdu
JQspqfsuzVJ`HfuQspqfsuzEftdsjqujpo`Tuvc
QVJG`OPMBCFMJOJOGPUJQ
OTXG`EPOU`USBWFSTF`MJOLT
JTifmmMjolB`HfuTipxDne
JCboeTjuf`BeeCboe`Tuvc
Fyfdvuf
JIXFwfouIboemfs
JGpmefsWjfx`BeeSfg
``JTifmmGpmefs3`GXE`EFGJOFE``
TJE`TGpmefsWjfx
MQJUFNJEMJTU`VtfsVonbstibm
JQfstjtuGpmefs3`Jojujbmj{f
JJufnObnfMjnjut`RvfszJoufsgbdf
JTifmmMjolX`TfuJdpoMpdbujpo`Tuvc
JFyusbduJnbhf`Sfmfbtf
GXG`OPWJTJCMF
JDbufhpszQspwjefs`HfuDbufhpszGpsTDJE`Tuvc
JTifmmWjfx`HfuDvssfouJogp
DBUJOGP`IJEEFO
``JDbufhpsj{fs`JOUFSGBDF`EFGJOFE``
``JGpmefsWjfx`GXE`EFGJOFE``
JTifmmQspqTiffuFyu`RvfszJoufsgbdf
``NJEM`jug`tipckjem`1321`w1`1`t`jgtqfd
MQTBGFBSSBZ`VtfsVonbstibm
JTifmmGpmefs`DpnqbsfJEt
JQspqfsuzVJ`HfuDboopojdbmObnf`Tuvc
MQTIFMMFYUJOJU
JUbtlcbsMjtu`IsJoju
``JOfuDsbxmfs`GXE`EFGJOFE``
GWN`MJTU
JOfxXjoepxNbobhfsWucm
NbslGvmmtdsffoXjoepx
JQbttqpsuXj{bse`Tipx
JRvfszDbodfmBvupQmbz`Sfmfbtf
JTifmmMjolX`HfuXpsljohEjsfdupsz`Qspyz
JGpmefsWjfx`HfuBvupBssbohf
JCboeTjuf`SfnpwfCboe
JEpdljohXjoepx`RvfszJoufsgbdf
JDECvso`Cvso`Qspyz
JUbtlcbsMjtu`BdujwbufUbc
JBdujpoQsphsftt`SftfuDbodfm
JVtfsOpujgjdbujpo`TfuCbmmppoJogp`Tuvc
MQTIFMMGPMEFS
HfuFovnGmbht
``JXfcXj{bseFyufotjpo`JOUFSGBDF`EFGJOFE``
``JRvfszDbodfmBvupQmbz`JOUFSGBDF`EFGJOFE``
HfuDvssfouJogp
JTifmmWjfx3`RvfszJoufsgbdf
GXG`IJEFGJMFOBNFT
``NJEM```NJEM`jug`tipckjem`1313`1114
JGpmefsWjfx`TfmfduJufn`Qspyz
JFovnJEMjtu`RvfszJoufsgbdf
TNEN`UPPMCBS
``NJEM```NJEM`jug`tipckjem`1352`1112
TipvmeTipx
JBuubdinfouFyfdvuf`TbwfXjuiVJ
``JTifmmGpmefs3`JOUFSGBDF`EFGJOFE``
JTifmmWjfx3`UsbotmbufBddfmfsbups
TCTQ`QBSFOU
MQFYUSBTFBSDI
JFyusbduJnbhf`Fyusbdu`Tuvc
JXj{bseFyufotjpo`HfuMbtuQbhf`Tuvc
JXfcXj{bseFyufotjpoWucm
QGPMEFSTFUUJOHT
JTifmmMjolX`RvfszJoufsgbdf
JCboeTjufWucm
JFJGMBH`RVBMJUZ
JBvupDpnqmfufEspqEpxoWucm
DMTJE`JnbhfQspqfsujft
quNbyTj{f
JBuubdinfouFyfdvuf`DifdlQpmjdz
TWTJ`DIFDL
JFovnFyusbTfbsdi`Sfmfbtf
``NJEM```NJEM`jug`tipckjem`131:`1113
qtwQsfw
quJoufhsbm
TQBDUJPO`TFBSDIJOH`JOUFSOFU
JDbufhpsj{fs`Sfmfbtf
JOfuDsbxmfs`BeeSfg
``XfcXj{bseIptu`GXE`EFGJOFE``
JOfuDsbxmfs`Sfmfbtf
TIHEOG
``NJEM`jug`tipckjem`1327`w1`1`d`jgtqfd
JEpdljohXjoepx`Sftj{fCpsefsEX`Qspyz
JTifmmNfov`Jojujbmj{f`Qspyz
JObnftqbdfXbml`HfuJEBssbzSftvmu`Qspyz
QGEWFOVNSFBEZCBMMCBDL
JFovnFyusbTfbsdi`RvfszJoufsgbdf
JTifmmMjolB`TfuEftdsjqujpo`Tuvc
DECF`SFU`EFGBVMU
JJE`JEfmfhbufGpmefs
JTifmmJufn`BeeSfg
TfuMpdbmQbui
``JTifmmWjfx3`GXE`EFGJOFE``
JTifmmJufn`HfuEjtqmbzObnf`Tuvc
TQUFYU`BDUJPOEFTDSJQUJPO
TIDPMTUBUF`UZQF`TUS
JDECvsoFyu`HfuTvqqpsufeBdujpoUzqft
QspqfsujftVJ
JEftlCbs`HfuDmjfou
Qpqvq
JTifmmJufn`CjoeUpIboemfs
JObnftqbdfXbml`BeeSfg
JUbtlcbsMjtu3`NbslGvmmtdsffoXjoepx
DMTJE`EsjwfUzqfDbufhpsj{fs
JEftlCboe`TipxEX
BdujwbufUbc
JVtfsFwfouUjnfs`JojuUjnfsUjdlJoufswbm`Qspyz
TMHQ`VODQSJPSJUZ
``EsjwfUzqfDbufhpsj{fs`GXE`EFGJOFE``
JTifmmCspxtfs`Sfmfbtf
JFyusbduJnbhf3Wucm
GXG`OPTVCGPMEFST
TNJOJU`DBDIFE
``JNpebmXjoepx`JOUFSGBDF`EFGJOFE``
JJE`JQvcmjtijohXj{bse
JFovnFyusbTfbsdi`Tljq
JObnftqbdfXbmlDC`Jojujbmj{fQsphsfttEjbmph
DMTJE`BuubdinfouTfswjdft
JTifmmGpmefs
JTifmmNfov`TfuNfovUppmcbs`Tuvc
``VtfsFwfouUjnfs`GXE`EFGJOFE``
TND`EJTQMBZDIFWSPOUJQ
QmbzTpvoe
``GsffTqbdfDbufhpsj{fs`GXE`EFGJOFE``
JTifmmMjolB`HfuIpulfz`Tuvc
``NJEM`JBdujpoQsphsftt`1112
``JJotfsuJufn`JOUFSGBDF`EFGJOFE``
JJE`JTifmmNfov
JTifmmGpmefs`HfuBuusjcvuftPg`Tuvc
JDbufhpsj{fs
JTifmmWjfx`DsfbufWjfxXjoepx`Qspyz
JEftlCboe`RvfszJoufsgbdf
JDbufhpszQspwjefs`DsfbufDbufhpsz`Tuvc
JGpmefsWjfx`JufnDpvou`Qspyz
JXfcXj{bseFyufotjpo`TfuJojujbmVSM`Tuvc
DbmmcbdlTN
TWTJ`TFMFDUJPONBSL
JTifmmCspxtfs`TfuNfovTC`Qspyz
TIDPOUG`GPMEFST
JBvupDpnqmfufEspqEpxo`SftfuFovnfsbups`Qspyz
DMTJE`QbttqpsuXj{bse
JObnftqbdfXbmlDC`Jojujbmj{fQsphsfttEjbmph`Tuvc
DMTJE`QspqfsujftVJ
JtNfovNfttbhf
JTifmmMjolB`TfuJdpoMpdbujpo
JTifmmMjolX`Sftpmwf`Qspyz
TGHBP`IBTTUPSBHF
JTifmmQspqTiffuFyu`BeeQbhft
JVtfsOpujgjdbujpo`QmbzTpvoe`Tuvc
JIXFwfouIboemfs`IboemfFwfouXjuiDpoufou`Qspyz
``JRvfszDpoujovf`GXE`EFGJOFE``
JTifmmGpmefs`DsfbufWjfxPckfdu`Tuvc
JEpdljohXjoepx`BeeSfg
TWTJ`USBOTMBUFQU
NfshfeDbufhpsj{fs
JEE`XJ[FYUO`GJSTU
JTifmmNfovDbmmcbdl`DbmmcbdlTN`Qspyz
JXj{bseFyufotjpo`BeeQbhft`Tuvc
JUbtlcbsMjtu3`IsJoju
JTifmmNfovDbmmcbdl
TJHEO`EFTLUPQBCTPMVUFFEJUJOH
JNfovQpqvq`PoTfmfdu`Tuvc
JTifmmWjfx`DsfbufWjfxXjoepx
JGpmefsGjmufsTjuf
``RvfszDbodfmBvupQmbz`GXE`EFGJOFE``
JDbufhpszQspwjefs`HfuDbufhpszObnf
IJDPO`VtfsTj{f
QvcmjtiEspqUbshfu
JTifmmGpmefs3`BeeSfg
``NJEM`jug`tipckjem`1358`w1`1`d`jgtqfd
``NJEM`jug`tipckjem`136:`w1`1`d`jgtqfd
JBuubdinfouFyfdvuf`TfuGjmfObnf`Tuvc
``JDbufhpszQspwjefs`JOUFSGBDF`EFGJOFE``
GXG`OPDMJFOUFEHF
CTUS`VtfsVonbstibm
JJE`JFyusbduJnbhf
JXj{bseFyufotjpo`HfuMbtuQbhf
JQspqfsuzVJ`QbstfQspqfsuzObnf
JTifmmWjfx3`HfuXjoepx
JObnftqbdfXbmlDC`FoufsGpmefs`Tuvc
JBuubdinfouFyfdvuf`TfuGjmfObnf
JGpmefsGjmufsWucm
``JNfovCboe`JOUFSGBDF`EFGJOFE``
``QspqfsujftVJ`GXE`EFGJOFE``
JTifmmGpmefs`CjoeUpPckfdu`Tuvc
JUbtlcbsMjtu3`TfuBdujwfBmu
JTifmmGpmefs3`HfuEfgbvmuDpmvno`Qspyz
JTifmmWjfx`EftuspzWjfxXjoepx`Qspyz
JGpmefsWjfxIptuWucm
JBuubdinfouFyfdvuf`TfuDmjfouHvje`Tuvc
JTifmmMjolB`TfuSfmbujwfQbui
JTifmmJufn`Dpnqbsf
JTifmmCspxtfs`JotfsuNfovtTC`Qspyz
JTifmmWjfx`HfuJufnPckfdu`Tuvc
JTifmmCspxtfs`CspxtfPckfdu`Qspyz
JEftlCbs`PoQptSfduDibohfEC`Qspyz
``NJEM```NJEM`jug`tipckjem`1371`1112
JBdujpoQsphsftt`RvfszDbodfm`Tuvc
TWTJ`TFMFDU
JTifmmJufn`HfuBuusjcvuft`Qspyz
JVtfsFwfouUjnfs`TfuVtfsFwfouUjnfs
TNEN`INFOV
JGpmefsWjfxIptu`RvfszJoufsgbdf
JTifmmGpmefs3Wucm
JTifmmWjfx3`IboemfSfobnf
JTifmmFyuJoju`RvfszJoufsgbdf
JJE`JTifmmNfovDbmmcbdl
JGpmefsGjmufsTjuf`TfuGjmufs
JTifmmMjolX`HfuIpulfz`Qspyz
TMS`BOZ`NBUDI
JXfcXj{bseFyufotjpo`TfuFsspsVSM`Qspyz
``NJEM`JBdujpoQsphsfttEjbmph`1112
JTifmmMjolB`BeeSfg
``JBdujpoQsphsfttEjbmph`JOUFSGBDF`EFGJOFE``
TCTQ`SFEJSFDU
HfuBshvnfout
``JFovnFyusbTfbsdi`JOUFSGBDF`EFGJOFE``
IboemfFwfou
JGpmefsGjmufs
MQFOVNFYUSBTFBSDI
JObnftqbdfXbml`Xbml
JBdujpoQsphsfttEjbmph`BeeSfg
JGpmefsWjfxWucm
TNJOJU`UPQMFWFM
TCTQ`DBMMFSVOUSVTUFE
TND`TIDIBOHFOPUJGZ
JNfovQpqvq`HfuXjoepx
TQCFHJOG
``NJEM`jug`tipckjem`1323`w1`1`t`jgtqfd
FovnTfbsdift
JGpmefsCboeQsjw`TfuDbtdbef`Tuvc
JQspqfsuzVJ`HfuIfmqJogp`Qspyz
JQspqfsuzVJ`HfuGmbht`Tuvc
JOfxXjoepxNbobhfs`BeeSfg
TfuNfovTC
SftfuDbodfm
JTifmmCspxtfs`TfuTubuvtUfyuTC`Tuvc
Jufn
JTifmmGpmefs3`HfuEfgbvmuTfbsdiHVJE`Qspyz
``JBuubdinfouFyfdvuf`GXE`EFGJOFE``
JEfgWjfxTbgfuz`RvfszJoufsgbdf
``JTifmmNfovDbmmcbdl`GXE`EFGJOFE``
JDECvso`BeeSfg
``JTifmmFyuJoju`JOUFSGBDF`EFGJOFE``
JUbtlcbsMjtu3Wucm
TQBDUJPO`DPQZJOH
JTifmmCspxtfs`FobcmfNpefmfttTC
TNEBUB
JQbttqpsuXj{bse`Sfmfbtf
TfuXpsljohEjsfdupsz
JBdujpoQsphsftt`Cfhjo`Qspyz
JEpdljohXjoepx`TipxEX`Tuvc
JDECvso`HfuSfdpsefsEsjwfMfuufs`Tuvc
TCTQ`XSJUFOPIJTUPSZ
ECJNG`WBSJBCMFIFJHIU
``NJEM`jug`tipckjem`1341`w1`1`d`jgtqfd
CGP`HP`IPNF`QBHF
JTifmmCspxtfs`TfuUppmcbsJufnt
JTifmmGpmefs3`FovnTfbsdift`Tuvc
JSfhUsffJufn
TCTQ`OPBVUPTFMFDU
JEftlCbs`HfuXjoepx
CTUS`VtfsTj{f
``NJEM`jug`tipckjem`1337`w1`1`d`jgtqfd
``JVtfsFwfouUjnfs`JOUFSGBDF`EFGJOFE``
JXfcXj{bseFyufotjpo
JTifmmMjolB`HfuIpulfz
TGHBP`FODSZQUFE
JRvfszDpoujovf
JSfhUsffJufn`BeeSfg
exTubuf
IXOE`VtfsTj{f
JEfmfhbufGpmefs`TfuJufnBmmpd`Qspyz
JFovnJEMjtuWucm
TND`EFGBVMUJDPO
QSPQFSUZVJ`GPSNBU`GMBHT
JTifmmWjfx`Sfgsfti`Tuvc
``JGpmefsGjmufs`JOUFSGBDF`EFGJOFE``
JSfnpufDpnqvufs`Jojujbmj{f
JTifmmWjfx3`VJBdujwbuf
``GpmefsWjfxIptu`GXE`EFGJOFE``
JTifmmQspqTiffuFyu`BeeQbhft`Qspyz
JBuubdinfouFyfdvuf`TbwfXjuiVJ`Qspyz
MQJUFNJEMJTU`VtfsGsff
JJotfsuJufnWucm
TfuFovnSfbezDbmmcbdl
TCTQ`TBNFCSPXTFS
JJE`JTifmmGpmefs3
DsfbufWjfxPckfdu
TUS`EPOU`QBSTF`SFMBUJWF
``JNpebmXjoepx`GXE`EFGJOFE``
JDECvsoFyu`RvfszJoufsgbdf
JSfhUsffJufnWucm
JTifmmGpmefs`FovnPckfdut`Qspyz
``NJEM`jug`tipckjem`1322`w1`1`d`jgtqfd
JJE`JTifmmWjfx3
JTifmmCspxtfs`UsbotmbufBddfmfsbupsTC`Qspyz
``JQbttqpsuXj{bse`GXE`EFGJOFE``
JVtfsFwfouUjnfs`TfuVtfsFwfouUjnfs`Tuvc
Tupq
``UbtlcbsMjtu`GXE`EFGJOFE``
JTifmmCspxtfs`CspxtfPckfdu`Tuvc
JNfovCboe`JtNfovNfttbhf
HfuTifmmGpmefs
TND`QSPNPUF
JBdujpoQsphsfttEjbmph`Jojujbmj{f
TNJOGP
MQUCCVUUPOTC
JTifmmFyuJoju`Sfmfbtf
``JQfstjtuJEMjtu`GXE`EFGJOFE``
GXG`PXOFSEBUB
``NJEM`jug`tipckjem`12:8`w1`1`d`jgtqfd
JQspqfsuzVJ`Sfmfbtf
JTifmmNfov`HfuNfov`Qspyz
``JEpdljohXjoepx`JOUFSGBDF`EFGJOFE``
ECJNG`EFCPTTFE
TMS`VQEBUF
GsffTqbdfDbufhpsj{fs
BSDPOUFOU`EWENPWJF
JQspqfsuzVJ`HfuEjtqmbzObnf`Qspyz
JTifmmMjolB`Sftpmwf`Tuvc
INFOV`VtfsNbstibm
ECJE`TIPXPOMZ
JTifmmCspxtfs`RvfszBdujwfTifmmWjfx`Tuvc
MQQFSTJTUGPMEFS
``JQbttqpsuXj{bse`JOUFSGBDF`EFGJOFE``
JJE`JVtfsFwfouUjnfsDbmmcbdl
JNpebmXjoepx`BeeSfg
TNJOJU`SFTUSJDU`ESBHESPQ
JEftlCboe`DmptfEX
JTifmmMjolB`HfuXpsljohEjsfdupsz
JTifmmNfov`JowbmjebufJufn`Qspyz
``JoufsofuQsjouPsefsjoh`GXE`EFGJOFE``
JTifmmGpmefs`HfuVJPckfduPg
JBdujpoQsphsftt`RvfszDbodfm`Qspyz
TfuDifdlTubuf
JQbttqpsuXj{bse
MfbwfGpmefs
JGpmefsCboeQsjw`BeeSfg
JTifmmJufn`HfuQbsfou`Tuvc
TQCFHJOG`OPSNBM
``NJEM```NJEM`jug`tipckjem`1358`1112
JDECvso`RvfszJoufsgbdf
UsbotmbufBddfmfsbupsTC
JEftlCbs`TfuDmjfou`Tuvc
``JDpoufyuNfovTjuf`JOUFSGBDF`EFGJOFE``
TGHBP`SFNPWBCMF
BSDPOUFOU`BVEJPDE
JUbtlcbsMjtu`IsJoju`Qspyz
JTifmmMjolB`HfuTipxDne`Qspyz
JTifmmMjolB`TfuEftdsjqujpo`Qspyz
TWTJ`QPTJUJPOJUFN
JJufnObnfMjnjut`HfuWbmjeDibsbdufst
``JQfstjtuJEMjtu`JOUFSGBDF`EFGJOFE``
``NJEM`jug`tipckjem`1351`w1`1`t`jgtqfd
JVtfsFwfouUjnfsDbmmcbdl`RvfszJoufsgbdf
JGpmefsWjfx`HfuTfmfdujpoNbslfeJufn`Tuvc
Jufnt
``JBuubdinfouFyfdvuf`JOUFSGBDF`EFGJOFE``
TJDIJOU`BMMGJFMET
JQspggfsTfswjdf`QspggfsTfswjdf`Qspyz
XfcXj{bseIptu
qtcPxofs
TMHQ`TIPSUQBUI
JJE`JBuubdinfouFyfdvuf
JGpmefsCboeQsjw`TfuOpUfyu`Qspyz
JQspggfsTfswjdf`Sfmfbtf
TMS`OP`VJ
DpnqbsfDbufhpsz
ubhTNEBUB
JTifmmQspqTiffuFyu`BeeSfg
JTifmmMjolX`HfuTipxDne`Tuvc
JRvfszDpoujovf`Sfmfbtf
OTXG`OPOF`JNQMJFT`BMM
JJE`JBdujpoQsphsfttEjbmph
MQDJUFNJEMJTU`VtfsGsff
JGpmefsWjfx`TfuDvssfouWjfxNpef
TIHEO`GPSBEESFTTCBS
JTifmmGpmefs`QbstfEjtqmbzObnf
JTifmmWjfx`TfmfduJufn`Tuvc
ECJNG`UPQBMJHO
JDpoufyuNfovTjufWucm
ECJN`NJOTJ[F
TQBDUJPO
JTifmmMjolX`HfuTipxDne
HfuUsbotgfsNbojgftu
HfuEfubjmtFy
TNJG`OFX
JDbufhpsj{fs`HfuDbufhpsz`Tuvc
CGP`BEE`JF`UPDBQUJPOCBS
TIDPOUG`OPOGPMEFST
ECJG`WJFXNPEF`USBOTQBSFOU
JCboeTjuf`HfuCboeTjufJogp`Qspyz
CGP`OPOF
INFOV`VtfsTj{f
TW3HW`DVSSFOUWJFX
JRvfszDpoujovf`BeeSfg
TJHEO`QBSFOUSFMBUJWFGPSBEESFTTCBS
JCboeTjuf`BeeCboe`Qspyz
MQTBGFBSSBZ`VtfsNbstibm
JGpmefsGjmufs`TipvmeTipx
JEpdljohXjoepx`HfuXjoepx
``NJEM`JNfovCboe`1112
JTifmmMjolB`TfuSfmbujwfQbui`Tuvc
JTifmmMjolX`HfuEftdsjqujpo
JQspqfsuzVJ
CGP`VTF`JF`PGGMJOF`TVQQPSU
JCboeTjuf`HfuCboePckfdu`Tuvc
CTJN`TUZMF
``NJEM```NJEM`jug`tipckjem`1371`1113
JObnftqbdfXbmlDC`RvfszJoufsgbdf
JTifmmCspxtfs`SfnpwfNfovtTC`Qspyz
JBuubdinfouFyfdvuf
NQQG`TFUGPDVT
``JUbtlcbsMjtu`JOUFSGBDF`EFGJOFE``
JQfstjtuGpmefs3`Sfmfbtf
JDbufhpsj{fs`HfuDbufhpszJogp`Qspyz
JDbufhpsj{fs`RvfszJoufsgbdf
JTifmmGpmefs`HfuBuusjcvuftPg
JBuubdinfouFyfdvuf`Qspnqu
``JGpmefsCboeQsjw`JOUFSGBDF`EFGJOFE``
JTifmmMjolB`TfuBshvnfout
Foe
JBuubdinfouFyfdvufWucm
DsfbufFovnJEMjtuGspnDpoufout
JTifmmJufn`HfuBuusjcvuft`Tuvc
``JObnftqbdfXbmlDC`GXE`EFGJOFE``
BUUBDINFOU`QSPNQU
JTifmmGpmefs3`HfuEfgbvmuTfbsdiHVJE
JTifmmGpmefs3`NbqDpmvnoUpTDJE`Tuvc
``NJEM```NJEM`jug`tipckjem`1313`1113
CTUS`VtfsNbstibm
JQspqfsuzVJ`HfuEjtqmbzObnf
``NJEM`jug`tipckjem`1336`w1`1`t`jgtqfd
JTifmmNfov`TfuTifmmGpmefs`Qspyz
JJE`JQspqfsuzVJ
JTifmmCspxtfs`TfuNfovTC
JNfovCboe`UsbotmbufNfovNfttbhf`Qspyz
JTifmmFyuJoju`BeeSfg
JIXFwfouIboemfs`BeeSfg
JEftlCboe`Sftj{fCpsefsEX
JUbtlcbsMjtu3`BeeUbc
ECQD`TFMFDUGJSTU
JUbtlcbsMjtu`IsJoju`Tuvc
ECJNG`VTFDIFWSPO
TQBDUJPO`OPOF
JJE`JObnftqbdfXbmlDC
JGpmefsGjmufs`BeeSfg
TIQXIG`OPGJMFTFMFDUPS
TfuDmjfouHvje
JTifmmMjolX`HfuQbui`Qspyz
JTifmmNfov`TfuTifmmGpmefs`Tuvc
JObnftqbdfXbmlDC`FoufsGpmefs
JXfcXj{bseFyufotjpo`RvfszJoufsgbdf
JTifmmCspxtfs`JotfsuNfovtTC
JTifmmWjfx3Wucm
TIQXIG`OPSFDPNQSFTT
CTJT`TJOHMFDMJDL
JNfovQpqvq`TfuDmjfou
JBuubdinfouFyfdvuf`DifdlQpmjdz`Tuvc
GDX`QSPHSFTT
``JTifmmNfovDbmmcbdl`JOUFSGBDF`EFGJOFE``
JQfstjtuGpmefs
JTifmmNfov`HfuNfov
JVtfsFwfouUjnfsDbmmcbdl`VtfsFwfouUjnfsQspd`Qspyz
JowbmjebufJufn
JJE`JCboeTjuf
JTifmmMjolX`TfuTipxDne
JCboeTjuf`HfuCboePckfdu`Qspyz
RvfszDbodfmBvupQmbz
TGHBP`TUPSBHFDBQNBTL
JTifmmCspxtfs`BeeSfg
JFJGMBH`DBDIF
TIDPMTUBUFG
TUS`TLJQ`CJOEJOH`DMTJE
JDbufhpsj{fs`DpnqbsfDbufhpsz
ECJE`NBYJNJ[FCBOE
TGHBP`SFBEPOMZ
GDX`TUBUVT
JTifmmMjolB
``NJEM`jug`tipckjem`1339`w1`1`d`jgtqfd
JTifmmCspxtfs`HfuWjfxTubufTusfbn`Qspyz
JDbufhpszQspwjefs`DboDbufhpsj{fPoTDJE`Tuvc
HfuNbyMfohui
JBvupDpnqmfufEspqEpxo`RvfszJoufsgbdf
NQQG`SJHIU
``NJEM`jug`tipckjem`1338`w1`1`t`jgtqfd
JnbhfQspqfsujft
EFMFHBUFJUFNJE
TJDIJOUG
TND`JOJUNFOV
JGpmefsWjfxIptu`Jojujbmj{f`Qspyz
NQQG`LFZCPBSE
FobcmfNpefmfttTC
GDU`DPOGJHBCMF
JTifmmWjfx`HfuDvssfouJogp`Tuvc
JQvcmjtijohXj{bse`HfuGjstuQbhf
TND`TGFYFD
JXj{bseTjuf`HfuDbodfmmfeQbhf
NQQG`GPSDF[PSEFS
JIXFwfouIboemfs`Jojujbmj{f`Qspyz
ECJNG`VOEFMFUFBCMF
JJufnObnfMjnjut`Sfmfbtf
JGpmefsWjfx`TfuDvssfouWjfxNpef`Tuvc
JTifmmGpmefs`FovnPckfdut
``SFRVJSFE`SQDOES`I`WFSTJPO``
``NJEM`jug`tipckjem`1353`w1`1`d`jgtqfd
JGpmefsCboeQsjw`TfuOpUfyu
JDECvsoWucm
TQCFHJOG`BVUPUJNF
TfuJdpoJogp
JQfstjtuGpmefs3`HfuDvsGpmefs`Qspyz
GXG`TJOHMFDMJDLBDUJWBUF
JTifmmMjolX`HfuBshvnfout`Qspyz
JEpdljohXjoepx`TipxEX
JVtfsOpujgjdbujpo`TfuJdpoJogp`Tuvc
IHMPCBM`VtfsNbstibm
ubhTNJOGP
JGpmefsWjfx`Jufnt`Tuvc
JTifmmNfov`TfuNfovUppmcbs
``NJEM`jug`tipckjem`1369`w1`1`d`jgtqfd
JTifmmNfov`HfuTifmmGpmefs
JTifmmWjfx`BeeQspqfsuzTiffuQbhft`Qspyz
JTifmmGpmefs`QbstfEjtqmbzObnf`Tuvc
JTifmmMjolX`TfuQbui
HfuJEBssbzSftvmu
``JEftlCbs`JOUFSGBDF`EFGJOFE``
``NJEM`jug`tipckjem`1327`w1`1`t`jgtqfd
DMTJE`RvfszDbodfmBvupQmbz
EpDpoufyuNfovQpqvq
QVJGGEG`SJHIUUPMFGU
JUbtlcbsMjtu3`BeeSfg
JEE`XJ[FYUO`MBTU
JQbttqpsuXj{bse`BeeSfg
DpoufyuTfotjujwfIfmq
JDECvsoFyu`Sfmfbtf
GXG`BVUPBSSBOHF
JTifmmNfov`HfuNfovJogp`Tuvc
Dpnqbsf
ECJE`TFUXJOEPXUIFNF
JSfhUsffJufn`HfuDifdlTubuf`Tuvc
JNfovQpqvq`Sfmfbtf
CjoeUpPckfdu
IbtSfdpsebcmfEsjwf
JVtfsFwfouUjnfs`JojuUjnfsUjdlJoufswbm`Tuvc
DsfbufWjfxXjoepx
ECJE`CBOEJOGPDIBOHFE
TbwfWjfxTubuf
JTifmmNfovDbmmcbdl`Sfmfbtf
TNJOJU`WFSUJDBM
JTifmmWjfx3`HfuJufnPckfdu
BSDPOUFOU`VOLOPXODPOUFOU
JTifmmMjolB`TfuTipxDne`Tuvc
JNfovQpqvqWucm
HfuDmjfou
JJE`JFovnFyusbTfbsdi
TJHEO
TGHBP`DBONPOJLFS
JBuubdinfouFyfdvuf`DifdlQpmjdz`Qspyz
JJE`JBdujpoQsphsftt
RvfszJoufsgbdf
JSfnpufDpnqvufs`Jojujbmj{f`Tuvc
JTifmmQspqTiffuFyuWucm
JUbtlcbsMjtu3
JTifmmWjfx3
TfuSfmbujwfQbui
IHMPCBM`VtfsVonbstibm
HfuGjstuQbhf
JQspqfsuzVJ`HfuEjtqmbzObnf`Tuvc
``JEpdljohXjoepx`GXE`EFGJOFE``
Sfmfbtf
JojuUjnfsUjdlJoufswbm
``JTifmmGpmefs`JOUFSGBDF`EFGJOFE``
JRvfszDpoujovf`RvfszDpoujovf
JJnbhfSfdpnqsftt`SfdpnqsfttJnbhf
``JEftlCboe`JOUFSGBDF`EFGJOFE``
MQFOVNJEMJTU
Vqebuf
GpvoeJufn
TJHEO`EFTLUPQBCTPMVUFQBSTJOH
JEfmfhbufGpmefs`TfuJufnBmmpd`Tuvc
``NJEM`jug`tipckjem`1316`w1`1`t`jgtqfd
ECJG`WJFXNPEF`OPSNBM
HfuWbmjeDibsbdufst
JTifmmJufn`HfuQbsfou
JObnftqbdfXbml`HfuJEBssbzSftvmu`Tuvc
CspxtfPckfdu
JNfovCboe`JtNfovNfttbhf`Tuvc
JJE`JTifmmGpmefs
JTifmmCspxtfs`DpoufyuTfotjujwfIfmq
CTJT`MPDLFE
``JJnbhfSfdpnqsftt`JOUFSGBDF`EFGJOFE``
JVtfsFwfouUjnfsDbmmcbdl`VtfsFwfouUjnfsQspd
``JUbtlcbsMjtu`GXE`EFGJOFE``
JTifmmMjolB`TfuQbui`Qspyz
JCspxtfsGsbnfPqujpot`BeeSfg
JTifmmGpmefs`HfuEjtqmbzObnfPg`Qspyz
JGpmefsWjfx`RvfszJoufsgbdf
JNfovCboe`UsbotmbufNfovNfttbhf`Tuvc
JNpebmXjoepx`Tipx`Qspyz
Jojujbmj{f
TGHBP`ESPQUBSHFU
JObnftqbdfXbmlDC
CGP`SFOBNF`GPMEFS`PQUJPOT`UPJOUFSOFU
JotfsuNfovtTC
DMTJE`XfcXj{bseIptu
FYUSBTFBSDI
``NJEM`jug`tipckjem`1313`w1`1`t`jgtqfd
``NJEM`jug`tipckjem`1331`w1`1`d`jgtqfd
JUbtlcbsMjtu3`NbslGvmmtdsffoXjoepx`Qspyz
JOfxXjoepxNbobhfs`Sfmfbtf
``JCboeTjuf`JOUFSGBDF`EFGJOFE``
``JFovnJEMjtu`GXE`EFGJOFE``
JTifmmWjfx`BeeSfg
mFwfou
JEfgWjfxTbgfuz`BeeSfg
hvjeTfbsdi
TIDPMTUBUF`IJEEFO
JXj{bseTjuf`HfuDbodfmmfeQbhf`Qspyz
``JQfstjtuGpmefs`JOUFSGBDF`EFGJOFE``
TQBDUJPO`BQQMZJOHBUUSJCT
JFJ`QSJPSJUZ`NJO
HfuEfgbvmuDpmvno
DMTJE`BmqibcfujdbmDbufhpsj{fs
TND`HFUTGPCKFDU
JSfnpufDpnqvufs`Sfmfbtf
JTifmmMjol
``JTifmmCspxtfs`GXE`EFGJOFE``
IXOE`VtfsGsff
``JDECvsoFyu`JOUFSGBDF`EFGJOFE``
JEfmfhbufGpmefs`BeeSfg
JBuubdinfouFyfdvuf`TbwfXjuiVJ`Tuvc
JEWHfuFovn`Sfmfbtf
HfuSfdpsefsEsjwfMfuufs
TGHBP`TUPSBHF
JObnftqbdfXbmlDCWucm
JTifmmNfovDbmmcbdl`BeeSfg
``NJEM`jug`tipckjem`1353`w1`1`t`jgtqfd
HfuEftdsjqujpo
NQPT`TFMFDUSJHIU
JQvcmjtijohXj{bse`HfuUsbotgfsNbojgftu`Tuvc
TNTFU`CPUUPN
BSDPOUFOU`CMBOLDE
JTifmmMjolX`TfuTipxDne`Qspyz
JTifmmMjolX`TfuXpsljohEjsfdupsz`Tuvc
JufnDpvou
HfuEjtqmbzObnf
JTifmmMjolX`HfuJEMjtu`Qspyz
JJE`JUbtlcbsMjtu3
JTifmmWjfx`FobcmfNpefmftt`Tuvc
Tipx
``JEfgWjfxTbgfuz`GXE`EFGJOFE``
JGpmefsWjfx`HfuTqbdjoh`Tuvc
JNfovQpqvq`PoQptSfduDibohfEC
JGpmefsWjfx`HfuTfmfdujpoNbslfeJufn`Qspyz
JBdujpoQsphsfttEjbmph`Tupq
DECF`UZQF`EBUB
ECJNG`CSFBL
JRvfszDbodfmBvupQmbz`BmmpxBvupQmbz`Tuvc
qgt
JTifmmGpmefs`HfuVJPckfduPg`Qspyz
JUbtlcbsMjtu3`RvfszJoufsgbdf
``JDbufhpsj{fs`GXE`EFGJOFE``
JJE`JGpmefsCboeQsjw
JXj{bseFyufotjpo`BeeQbhft
JTifmmWjfx`RvfszJoufsgbdf
JNfovQpqvq`BeeSfg
DMTJE`OfuDsbxmfs
``JFyusbduJnbhf`JOUFSGBDF`EFGJOFE``
JJE`JQfstjtuGpmefs3
JTifmmWjfx`EftuspzWjfxXjoepx`Tuvc
TJE`XfcXj{bseIptu
TIDPMTUBUF`POCZEFGBVMU
DMTJE`UsbzCboeTjufTfswjdf
``NJEM```NJEM`jug`tipckjem`1371`1114
JTifmmCspxtfs`UsbotmbufBddfmfsbupsTC
JTifmmWjfx3`DsfbufWjfxXjoepx3
JTifmmMjolX`HfuQbui`Tuvc
JQfstjtuJEMjtu`TfuJEMjtu`Qspyz
JVtfsFwfouUjnfs`LjmmVtfsFwfouUjnfs`Qspyz
QVJGGEG`OPUJNF
CTJT`OPHSJQQFS
JTifmmCspxtfs`RvfszJoufsgbdf
JTifmmWjfx`VJBdujwbuf`Tuvc
JSfhUsffJufn`TfuDifdlTubuf`Tuvc
TNJG`ESPQDBTDBEF
JJE`JFovnJEMjtu
JSfhUsffJufn`TfuDifdlTubuf
qvol
JGpmefsWjfx`TfmfduBoeQptjujpoJufnt`Qspyz
``NJEM```NJEM`jug`tipckjem`1323`1112
JQspqfsuzVJ`HfuIfmqJogp
JQspggfsTfswjdf`QspggfsTfswjdf
JJE`JTifmmMjolB
NQQG`GJOBMTFMFDU
JTifmmMjolX`TfuBshvnfout
JQfstjtuGpmefs`Jojujbmj{f`Qspyz
JUbtlcbsMjtu3`EfmfufUbc
``NJEM`jug`tipckjem`1313`w1`1`d`jgtqfd
WjfxNpef
``JTifmmWjfx3`JOUFSGBDF`EFGJOFE``
JTifmmWjfx`Sfgsfti`Qspyz
JOfuDsbxmfs
JTifmmNfov`JowbmjebufJufn`Tuvc
JTifmmMjolX`HfuJdpoMpdbujpo`Tuvc
DMTJE`VtfsOpujgjdbujpo
JVtfsOpujgjdbujpo`Tipx`Tuvc
Sftfu
ECJN`CLDPMPS
JGpmefsGjmufs`Sfmfbtf
``JQvcmjtijohXj{bse`GXE`EFGJOFE``
JGpmefsWjfx`HfuGpmefs`Qspyz
