#Encrypted file follows
JJoufsofuQspupdpmSppu`Tvtqfoe`Tuvc
JJoufsofuQspupdpmTjolTubdlbcmf`TxjudiTjol
JJoufsofuQspupdpmSppu`Tvtqfoe
NVU[`SFRVJSFTBWFEGJMFDIFDL
``JJoufsofu[pofNbobhfs`JOUFSGBDF`EFGJOFE``
JJoufsofu[pofNbobhfs`Eftuspz[pofFovnfsbups`Qspyz
JJoufsofuUisfbeTxjudi
VSMBDUJPO`IUNM`NBY
JOFU`F`BVUIFOUJDBUJPO`SFRVJSFE
JtWbmjeVSM
QBSTF`FTDBQF
``NJEM`jug`vsmnpo`12:3`w1`1`d`jgtqfd
RVFSZ`SFGSFTI
MphBdujpo
ubhCJOETUBUVT
DJQ`TUBUVT
CJOETUBUVT`FODPEJOH
JJoufsofuTfdvsjuzNbobhfsFy`Sfmfbtf
JCjoeIptuWucm
JJoufsofu`BeeSfg
CJOEG`GPSNT`TVCNJU
VSMBDUJPO`EPXOMPBE`DVSS`NBY
CJOEG`GSPNVSMNPO
JJoufsofuIptuTfdvsjuzNbobhfs`HfuTfdvsjuzJe`Tuvc
VSMBDUJPO`TIFMM`FYFDVUF`MPXSJTL
J[pofJefoujgjfs`TfuJe`Tuvc
DMTJE`TCT`TpguEjtuFyu
JPJofuQspupdpmJogp
CJOEWFSC`QPTU
`ubhQTVBDUJPO
``NJEM`jug`vsmnpo`12:8`w1`1`d`jgtqfd
VSMBDUJPO`JOGPEFMJWFSZ`OP`SFNPWJOH`TVCTDSJQUJPOT
CJOEG`JHOPSFTFDVSJUZQSPCMFN
VSMBDUJPO`IUNM`GPOU`EPXOMPBE
CJOEG`TJMFOUPQFSBUJPO
QVBGPVU`JTMPDL[POFQPMJDZ
JOFU`F`TFDVSJUZ`QSPCMFN
``NJEM`jug`vsmnpo`1319`w1`1`t`jgtqfd
VSM[POF`VTFS`NBY
`MQFODPEJOHGJMUFSGBDUPSZ`EFGJOFE
``NJEM`jug`vsmnpo`1289`w1`1`d`jgtqfd
JJoufsofuQspupdpmWucm
MQPJOFUQSPUPDPMTJOL
VSMBDUJPO`KBWB`NBY
DGTUS`NJNF`IUB
JCjoejoh`Sfmfbtf
QJ`BQBSUNFOUUISFBEFE
GFBUVSF`TBGF`CJOEUPPCKFDU
JJoufsofu[pofNbobhfs`Hfu[pofBuusjcvuft`Qspyz
JJoufsofu[pofNbobhfs`Dsfbuf[pofFovnfsbups
VSMQPMJDZ`BVUIFOUJDBUF`DMFBSUFYU`PL
JJoufsofuQspupdpmTjolTubdlbcmf`SpmmcbdlTxjudi`Tuvc
DPEFCBTFIPME
DPOGJSNTBGFUZBDUJPO`MPBEPCKFDU
VSMPqfoCmpdljohTusfbnX
VSMBDUJPO`TIFMM`JOTUBMM`EUJUFNT
JtBtzodNpojlfs
VSMQPMJDZ`OPUJGZ`PO`EJTBMMPX
GFBUVSF`SFTUSJDU`GJMFEPXOMPBE
JDbubmphGjmfJogp`BeeSfg
JOFU`F`DPOOFDUJPO`UJNFPVU
DMTJE`TCT`TueFodpejohGjmufsGbd
CJOETUBUVT`FOETZODPQFSBUJPO
t{JdpoQbui
DGTUS`NJNF`Y`BSU
CJOEG`QSBHNB`OP`DBDIF
``NJEM`JCjoeTubuvtDbmmcbdl`1114
CJOETUBUVT`DPPLJF`TUBUF`SFKFDU
MQDPEFCBTFIPME
VSMQPMJDZ`DIBOOFM`TPGUEJTU`QSPIJCJU
JJoufsofuTfdvsjuzNhsTjuf`HfuXjoepx
QBSTF`BODIPS
``NJEM`jug`vsmnpo`1298`w1`1`t`jgtqfd
JJoufsofuTfdvsjuzNbobhfsFy`NbqVsmUp[pof
DGTUS`NJNF`SBXEBUB
``NJEM`jug`vsmnpo`1297`w1`1`d`jgtqfd
JXjoJofuIuuqJogp
JFodpejohGjmufsGbdupsz`HfuEfgbvmuGjmufs
F`QFOEJOH
JJoufsofuCjoeJogp`HfuCjoeJogp
``JJoufsofuQspupdpm`GXE`EFGJOFE``
JXjoepxGpsCjoejohVJWucm
TPGUEJTU`BETUBUF`EPXOMPBEFE
ubhCJOETUSJOH
JJoufsofu[pofNbobhfsFy`Tfu[pofBdujpoQpmjdzFy`Tuvc
JJoufsofuTfdvsjuzNhsTjuf`BeeSfg
VSMBDUJPO`JOGPEFMJWFSZ`NJO
JJE`JDpefJotubmm
``NJEM`jug`vsmnpo`12:1`w1`1`d`jgtqfd
DMTJE`TueFodpejohGjmufsGbd
JJoufsofu[pofNbobhfsFy`Tfu[pofBdujpoQpmjdzFy
VSMBDUJPO`JOGPEFMJWFSZ`DVSS`NBY
GJFG`GMBH`QFFL
JJoufsofu[pofNbobhfsFy`BeeSfg
JJoufsofu[pofNbobhfs`Dsfbuf[pofFovnfsbups`Tuvc
IXOE`VtfsNbstibm
`MQJOUFSOFUTFDVSJUZNBOBOHFS`EFGJOFE
VSMBDUJPO`TIFMM`NBY
CTDG`JOUFSNFEJBUFEBUBOPUJGJDBUJPO
JJE`JJoufsofuCjoeJogp
CJOEG`EPOUQVUJODBDIF
``NJEM`jug`vsmnpo`129:`w1`1`d`jgtqfd
VSMEpxompbeUpGjmfB
JJE`JJoufsofuQspupdpmTjol
IXOE`VtfsTj{f
exBewfsujtfeWfstjpoNT
JJoufsofuQspupdpmJogp`DpncjofVsm`Tuvc
JXjoJofuJogp`RvfszPqujpo`Qspyz
JJE`JDbubmphGjmfJogp
JJoufsofu[pofNbobhfsFy`Hfu[pofBdujpoQpmjdzFy
``NJEM`JCjoeTubuvtDbmmcbdl`1113
QVBG`MN[`VOMPDLFE
MQNPOJLFSQSPQ
JJE`JPJofuCjoeJogp
TJE`CjoeIptu
JJoufsofu[pofNbobhfs`Hfu[pofDvtupnQpmjdz`Qspyz
DpJoufsofuQbstfVsm
VSMNPO`PQUJPO`VTFSBHFOU
``JJoufsofuCjoeJogp`JOUFSGBDF`EFGJOFE``
`MQTPGUEJTUFYU`EFGJOFE
HfuCjoeTusjoh
`MQJJOUFSOFUTFTTJPO`EFGJOFE
JCjoeQspupdpm`RvfszJoufsgbdf
VSMBDUJPO`IUNM`KBWB`SVO
JFodpejohGjmufsGbdupsz`BeeSfg
CJOEG`BTZODISPOPVT
JNpojlfsQspq`QvuQspqfsuz`Tuvc
SfhjtufsGpsnbuFovnfsbups
``NJEM`JJoufsofuTfdvsjuzNbobhfs`1113
NLTZT`VSMNPOJLFS
CJOEJOGPG
JJoufsofu[pofNbobhfsWucm
VSMBDUJPO`TIFMM`GJMF`EPXOMPBE
``JCjoejoh`GXE`EFGJOFE``
SfhjtufsNfejbUzqft
``JCjoeIptu`GXE`EFGJOFE``
PJofuDpncjofVsm
`ubhRVFSZPQUJPO
JCjoejoh`Bcpsu`Tuvc
``NJEM`jug`vsmnpo`12:7`w1`1`d`jgtqfd
JJoufsofuTfdvsjuzNbobhfs`Hfu[pofNbqqjoht`Qspyz
JCjoeIptu`NpojlfsCjoeUpPckfdu`Qspyz
JJoufsofuQspupdpmTjol`SfqpsuEbub`Qspyz
CJOETUBUVT`QSPYZEFUFDUJOH
JEbubGjmufs`EpEfdpef
JJoufsofu[pofNbobhfs`Tfu[pofDvtupnQpmjdz`Qspyz
JJoufsofuCjoeJogp`RvfszJoufsgbdf
Hfu[pofDvtupnQpmjdz
DMTJE`TCT`Joufsofu[pofNbobhfs
`ubhTPGUEJTUJOGP
``JXjoJofuIuuqJogp`JOUFSGBDF`EFGJOFE``
``NJEM`jug`vsmnpo`1326`w1`1`d`jgtqfd
JJE`JTpguEjtuFyu
`MQIUUQTFDVSJUZ`EFGJOFE
JCjoeIptu`DsfbufNpojlfs`Tuvc
BtzodJotubmmEjtusjcvujpoVoju
JXjoJofuIuuqJogp`SfnpufRvfszJogp`Tuvc
TJE`TJoufsofuTfdvsjuzNbobhfs
JOFU`F`DPEF`JOTUBMM`TVQQSFTTFE
DpJoufsofuDsfbuf[pofNbobhfs
VSMBDUJPO`BDUJWFY`NJO
``JJoufsofuQspupdpmTjol`JOUFSGBDF`EFGJOFE``
TbwfDpnqmfufe
TFU`GFBUVSF`PO`UISFBE`SFTUSJDUFE
`ubhQBSTFBDUJPO
JJoufsofuTfdvsjuzNbobhfsFy`QspdfttVsmBdujpoFy`Qspyz
JJoufsofu[pofNbobhfs`MphBdujpo`Qspyz
JXsbqqfeQspupdpm`HfuXsbqqfsDpef`Qspyz
VSMQPMJDZ`KBWB`DVTUPN
VSMPTUSN`VTFDBDIFEDPQZ
JXjoJofuIuuqJogp`RvfszPqujpo
CJOETUBUVT`WFSJGJFENJNFUZQFBWBJMBCMF
Tffl
JJoufsofu[pofNbobhfs`Tfu[pofBdujpoQpmjdz
JJoufsofuQsjpsjuz`TfuQsjpsjuz`Qspyz
JIuuqOfhpujbuf3Wucm
HfuOfyuDpefCbtf
`MQDBUBMPHGJMFJOGP`EFGJOFE
JIuuqTfdvsjuz`PoTfdvsjuzQspcmfn`Qspyz
JEbubGjmufs`BeeSfg
TFU`GFBUVSF`PO`UISFBE`JOUSBOFU
JJE`JJoufsofuTfdvsjuzNhsTjuf
VSMBDUJPO`OFUXPSL`DVSS`NBY
JJoufsofuTfdvsjuzNbobhfsFy`TfuTfdvsjuzTjuf
JCjoeQspupdpm`DsfbufCjoejoh
QJ`QSFGFSEFGBVMUIBOEMFS
Dpoujovf
MQCJOETUBUVTDBMMCBDL
VSMUFNQMBUF`DVTUPN
PoPckfduBwbjmbcmf
JFodpejohGjmufsGbdupsz`GjoeCftuGjmufs
JJoufsofuQspupdpmTjol`SfqpsuEbub
QVBG`BDDFQU`XJMEDBSE`TDIFNF
JJoufsofuQspupdpmJogp`RvfszJogp
PoDpefJotubmmQspcmfn
DMTJE`TpguEjtuFyu
`MQQFSTJTUNPOJLFS`EFGJOFE
VSMBDUJPO`IUNM`NJYFE`DPOUFOU
CJOETUBUVT`DPNQBDU`QPMJDZ`SFDFJWFE
ubhVSMUFNQMBUF
JJoufsofuTfttjpo`RvfszJoufsgbdf
JJoufsofuQspupdpmJogp`RvfszJogp`Qspyz
JCjoeTubuvtDbmmcbdl`PoEbubBwbjmbcmf`Qspyz
VSMBDUJPO`DIBOOFM`TPGUEJTU`QFSNJTTJPOT
DpJoufsofuHfuTfttjpo
``NJEM`jug`vsmnpo`128:`w1`1`t`jgtqfd
QVBG`OQM`VTF`MPDLFE`JG`SFTUSJDUFE
CJOETUBUVT`EFDPEJOH
JJoufsofuCjoeJogp`BeeSfg
DJQ`OFFE`SFCPPU`VJ`QFSNJTTJPO
JTpguEjtuFyu`BtzodJotubmmEjtusjcvujpoVoju`Qspyz
SfhjtufsNfejbUzqfDmbtt
JJoufsofuQspupdpmSppu`Dpoujovf`Qspyz
NBY`[POF`EFTDSJQUJPO
DGTUS`NJNF`OVMM
VSMBDUJPO`GFBUVSF`[POF`FMFWBUJPO
JCjoejoh`Sftvnf`Tuvc
Sftvnf
`ubhIJU`MPHHJOH`JOGP
RvfszJogp
JJoufsofuQspupdpmJogp`QbstfVsm
Hfu[pofBdujpoQpmjdzFy
CJOEG`OPXSJUFDBDIF
JCjoeTubuvtDbmmcbdl`PoMpxSftpvsdf`Qspyz
``JJoufsofuTfdvsjuzNbobhfsFy`JOUFSGBDF`EFGJOFE``
VSMBDUJPO`BVUPNBUJD`EPXOMPBE`VJ`NJO
VSMBDUJPO`DPPLJFT
DMTJE`TCT`IuuqTQspupdpm
JCjoejoh`SfnpufHfuCjoeSftvmu`Qspyz
DsfbufBtzodCjoeDuyFy
GNGE`JHOPSFNJNFUFYUQMBJO
JOFU`F`SFEJSFDU`GBJMFE
JEbubGjmufs`RvfszJoufsgbdf
JJoufsofu
``JJoufsofu`GXE`EFGJOFE``
JJoufsofuCjoeJogp`HfuCjoeTusjoh`Tuvc
J[pofJefoujgjfs`Sfnpwf`Tuvc
JJoufsofuUisfbeTxjudi`Qsfqbsf
GFBUVSF`WBMJEBUF`OBWJHBUF`VSM
JCjoeTubuvtDbmmcbdl`PoTupqCjoejoh
``JCjoejoh`JOUFSGBDF`EFGJOFE``
MQSFNGPSNBUFUD
JOFU`F`SFEJSFDUJOH
VSMBDUJPO`GFBUVSF`NJNF`TOJGGJOH
VSMBDUJPO`TIFMM`NPWF`PS`DPQZ
JXjoepxGpsCjoejohVJ`HfuXjoepx`Tuvc
JJoufsofuQspupdpm`VompdlSfrvftu`Tuvc
NPOJLFSQSPQFSUZ
JJoufsofuQspupdpmJogp`DpnqbsfVsm`Tuvc
JIuuqOfhpujbuf3`HfuSppuTfdvsjuzJe
JJoufsofuTfdvsjuzNbobhfsFy`RvfszJoufsgbdf
JJoufsofuQspupdpmSppu`Sfmfbtf
VSMBDUJPO`TIFMM`WFSC
`MQXJOJOFUIUUQJOGP`EFGJOFE
TfuTfdvsjuzTjuf
CJOETUBUVT`TFTTJPO`DPPLJF`SFDFJWFE
JJoufsofuTfttjpo`HfuTfttjpoPqujpo
DGTUS`NJNF`GSBDUBMT
JJoufsofuQsjpsjuz`RvfszJoufsgbdf
DGTUS`NJNF`Y`BJGG
JtMphhjohFobcmfe
JXsbqqfeQspupdpmWucm
JXjoJofuJogp`SfnpufRvfszPqujpo`Tuvc
JJoufsofuCjoeJogp`HfuCjoeJogp`Qspyz
exGmbht
``NJEM`jug`vsmnpo`1294`w1`1`d`jgtqfd
JCjoeIptu`SfnpufNpojlfsCjoeUpTupsbhf`Tuvc
JCjoeIptu`NpojlfsCjoeUpPckfdu`Tuvc
JJoufsofu`Sfmfbtf
JFodpejohGjmufsGbdupsz`Sfmfbtf
MQPJOFUUISFBETXJUDI
JEbubGjmufs`TfuFodpejohMfwfm`Tuvc
JCjoeTubuvtDbmmcbdl`HfuCjoeJogp
VSMBDUJPO`TIFMM`DVSS`NBY
CTDG
JIuuqTfdvsjuzWucm
JCjoeIptu`RvfszJoufsgbdf
VSM[POF`JOUSBOFU
JOFU`F`DBOOPU`JOTUBOUJBUF`PCKFDU
JJoufsofuQspupdpm`RvfszJoufsgbdf
VSMBDUJPO`BDUJWFY`NBY
``NJEM`jug`vsmnpo`1297`w1`1`t`jgtqfd
MQJJOUFSOFUQSPUPDPMTJOLTubdlbcmf
HfuEfgbvmuGjmufs
``JCjoeQspupdpm`JOUFSGBDF`EFGJOFE``
VSMEpxompbeUpGjmf
exBtqfdu
JJoufsofuQspupdpmTjolTubdlbcmf`BeeSfg
CTDG`MBTUEBUBOPUJGJDBUJPO
CJOETUBUVT`QFSTJTUFOU`DPPLJF`SFDFJWFE
DMTJE`TCT`GuqQspupdpm
QJ`QBSTF`VSM
JJoufsofuQspupdpmJogpWucm
JIuuqOfhpujbuf3`BeeSfg
CJOEG`BTZODTUPSBHF
JCjoeQspupdpm`DsfbufCjoejoh`Tuvc
JJoufsofuTfttjpo`HfuTfttjpoPqujpo`Tuvc
JJoufsofuQspupdpm`Tffl`Tuvc
t{ISFG
CJOETUBUVT`DPPLJF`TUBUF`VOLOPXO
JJE`JPJofuQsjpsjuz
JJoufsofu[pofNbobhfs`Hfu[pofBu`Qspyz
JXjoepxGpsCjoejohVJ`HfuXjoepx`Qspyz
JJoufsofuQspupdpmTjol`SfqpsuQsphsftt`Tuvc
JFodpejohGjmufsGbdupszWucm
VSMPTUSN`HFUOFXFTUWFSTJPO
VSMQPMJDZ`MPH`PO`BMMPX
``JXjoJofuJogp`JOUFSGBDF`EFGJOFE``
VSMEpxompbeUpDbdifGjmf
DpncjofVsm
`MQJJOUFSOFUQSPUPDPMTJOLTUBDLBCMF`EFGJOFE
JXjoJofuDbdifIjout`TfuDbdifFyufotjpo`Qspyz
MpdlSfrvftu
MQDBUBMPHGJMFJOGP
JJE`JBvuifoujdbuf
JJoufsofuQsjpsjuz`HfuQsjpsjuz`Qspyz
JJoufsofuTfdvsjuzNbobhfs`RvfszDvtupnQpmjdz`Qspyz
DMTJE`DmbttJotubmmGjmufs
QVBG`EPOUDIFDLCPYJOEJBMPH
QJ`QBTTPOCJOEDUY
`MQJJOUFSOFUUISFBETXJUDI`EFGJOFE
JCjoeTubuvtDbmmcbdl`PoQsphsftt`Qspyz
VSMBDUJPO`BVUPNBUJD`EPXOMPBE`VJ
exWfstjpoNT
QBSTF`MPDBUJPO
JJoufsofuTfdvsjuzNbobhfs`TfuTfdvsjuzTjuf`Tuvc
JXjoJofuJogpWucm
JJoufsofuTfdvsjuzNbobhfs`HfuTfdvsjuzTjuf`Tuvc
CJOETUBUVT
QbstfVsm
JJoufsofu[pofNbobhfs`Eftuspz[pofFovnfsbups`Tuvc
MQJJOUFSOFUQSPUPDPMSPPU
JJoufsofuQspupdpmJogp`QbstfVsm`Tuvc
JJoufsofu[pofNbobhfs`QspnquBdujpo`Qspyz
JJoufsofuQspupdpmTjol`SfqpsuSftvmu`Qspyz
JJE`JXjoJofuJogp
``JXsbqqfeQspupdpm`GXE`EFGJOFE``
JJoufsofu[pofNbobhfs`RvfszJoufsgbdf
JOFU`F`VTF`EFGBVMU`TFUUJOH
SfwplfCjoeTubuvtDbmmcbdl
CJOETUBUVT`CFHJOEPXOMPBEEBUB
GNGE`FOBCMFNJNFTOJGGJOH
DGTUS`NJNF`BWJ
JJoufsofu[pofNbobhfsFy`Sfmfbtf
VSMEpxompbeUpGjmfX
J[pofJefoujgjfs`HfuJe`Tuvc
JJoufsofuIptuTfdvsjuzNbobhfs`QspdfttVsmBdujpo
VSM[POFSFH`ILMN
``NJEM`jug`vsmnpo`12:4`w1`1`d`jgtqfd
`ubhDPEFCBTFIPME
JJoufsofuQspupdpmTjol`Txjudi`Qspyz
JJoufsofuQspupdpm`Sfbe`Qspyz
JCjoejoh`HfuQsjpsjuz`Tuvc
JCjoejoh`HfuQsjpsjuz
CJOETUBUVT`SFEJSFDUJOH
JDbubmphGjmfJogpWucm
MQPJOFUQSJPSJUZ
JJoufsofuCjoeJogpWucm
MQIUUQOFHPUJBUF
RVFSZ`DBO`OBWJHBUF
VosfhjtufsNjnfGjmufs
JJoufsofuTfdvsjuzNbobhfs`QspdfttVsmBdujpo
DGTUS`NJNF`UFYU
VSMBDUJPO`BDUJWFY`PWFSSJEF`TDSJQU`TBGFUZ
JJE`JJoufsofuQsjpsjuz
CTDG`EBUBGVMMZBWBJMBCMF
ImjolHpGpsxbse
JIuuqOfhpujbuf`PoSftqpotf`Qspyz
DG`OVMM
JPJofuQsjpsjuz
QBSTF`EPNBJO
FoeUjnf
MQPJOFUQSPUPDPMJOGP
VSMBDUJPO`EPXOMPBE`TJHOFE`BDUJWFY
qcjoejogp
CJOETUBUVT`DPOUFOUEJTQPTJUJPOBUUBDI
JQfstjtuNpojlfs`Tbwf
JJoufsofuTfdvsjuzNbobhfs`Tfu[pofNbqqjoh`Tuvc
JIuuqOfhpujbuf3`CfhjoojohUsbotbdujpo
``NJEM`jug`vsmnpo`1318`w1`1`t`jgtqfd
JJoufsofu[pofNbobhfsFy`Eftuspz[pofFovnfsbups
``JFodpejohGjmufsGbdupsz`GXE`EFGJOFE``
JCjoeIptu`NpojlfsCjoeUpPckfdu
JDbubmphGjmfJogp`HfuKbwbUsvtu
`MQDPEFJOTUBMM`EFGJOFE
VSMUFNQMBUF`MPX
`MQJJOUFSOFUCJOEJOGP
JJoufsofuQspupdpm`Tvtqfoe
JJoufsofuIptuTfdvsjuzNbobhfs`RvfszDvtupnQpmjdz
JJoufsofuIptuTfdvsjuzNbobhfs`HfuTfdvsjuzJe`Qspyz
JJoufsofuQspupdpmSppu`Ufsnjobuf`Tuvc
VSMBDUJPO`JOGPEFMJWFSZ`OP`FEJUJOH`TVCTDSJQUJPOT
JDbubmphGjmfJogp`HfuDbubmphGjmf`Qspyz
VSMBDUJPO`TDSJQU`NJO
JJE`JPJofuQspupdpm
`MQIUUQOFHPUJBUF`EFGJOFE
VSMQPMJDZ`CFIBWJPS`DIFDL`MJTU
`ubhPJCEH`GMBHT
USVTUFEEPXOMPBEQSPQ
JJoufsofuTfttjpo`SfhjtufsNjnfGjmufs
``JJoufsofu[pofNbobhfs`GXE`EFGJOFE``
JXjoJofuGjmfTusfbn`TfuIboemfGpsVompdl
``NJEM`jug`vsmnpo`1298`w1`1`d`jgtqfd
VSMBDUJPO`TIFMM`NJO
JTpguEjtuFyu`QspdfttTpguEjtu`Tuvc
JOFU`F`EPXOMPBE`GBJMVSF
JTpguEjtuFyu`QspdfttTpguEjtu
JXjoJofuGjmfTusfbn`TfuEfmfufGjmf`Tuvc
qJug
IJU`MPHHJOH`JOGP
JDpefJotubmm`PoDpefJotubmmQspcmfn
JCjoeTubuvtDbmmcbdl`HfuQsjpsjuz`Qspyz
HfuTfttjpoPqujpo
``NJEM`jug`vsmnpo`1299`w1`1`t`jgtqfd
t{DpefCbtf
CJOEJOGP
MQDPEFJOTUBMM
PoTubsuCjoejoh
GJFG`GMBH`GPSDF`KJUVJ
CJOETUBUVT`DPPLJF`TUBUF`EPXOHSBEF
JNpojlfsQspq`QvuQspqfsuz`Qspyz
JCjoeQspupdpm
PoEbubBwbjmbcmf
CJOETUSJOH`BDDFQU`FODPEJOHT
``NJEM`jug`vsmnpo`1293`w1`1`t`jgtqfd
HFU`GFBUVSF`GSPN`SFHJTUSZ
JEbubGjmufs`EpEfdpef`Tuvc
t{EjtqmbzObnf
JXjoJofuDbdifIjout`Sfmfbtf
JJoufsofuQspupdpmTjolTubdlbcmf`SpmmcbdlTxjudi
HfuDmbttJE
MQFODPEJOHGJMUFSGBDUPSZ
VsmNlHfuTfttjpoPqujpo
JJoufsofuQspupdpmSppu`Sftvnf`Tuvc
JJoufsofu[pofNbobhfs`Hfu[pofBdujpoQpmjdz`Tuvc
``NJEM`jug`vsmnpo`1323`w1`1`d`jgtqfd
VSMBDUJPO`DMJFOU`DFSU`QSPNQU
DMTJE`TueVSMQspupdpm
JJoufsofuQspupdpm`Dpoujovf
QVBG`MN[`MPDLFE
JXjoJofuGjmfTusfbn`TfuIboemfGpsVompdl`Qspyz
``JXjoJofuGjmfTusfbn`JOUFSGBDF`EFGJOFE``
JCjoejoh`RvfszJoufsgbdf
VSMBDUJPO`TIFMM`SUG`PCKFDUT`MPBE
VSMBDUJPO`IUNM`NFUB`SFGSFTI
DsfbufCjoejoh
TPGUEJTUJOGP
`MQJJOUFSOFUQSPUPDPMSPPU`EFGJOFE
DGTUS`NJNF`CNQ
JDpefJotubmm
HfuCjoeSftvmu
CJOETUSJOH`IFBEFST
JXjoJofuJogp`BeeSfg
VSM`NL`MFHBDZ
JJoufsofuQspupdpmSppu`Sftvnf`Qspyz
`MQJOUFSOFU[POFNBOBHFS`EFGJOFE
CJOEG`QVMMEBUB
JIuuqOfhpujbuf3`Sfmfbtf
CJOEJOGPG`VSMFODPEFEFYUSBJOGP
JJoufsofu[pofNbobhfs`Hfu[pofDvtupnQpmjdz
JJoufsofu[pofNbobhfs`Hfu[pofBuusjcvuft`Tuvc
JJoufsofuTfdvsjuzNbobhfsFy
MQJJOUFSOFUQSPUPDPM
JJoufsofuTfttjpo`DsfbufCjoejoh`Tuvc
JJoufsofuIptuTfdvsjuzNbobhfs`RvfszJoufsgbdf
CJOEG`OP`VJ
``JBvuifoujdbuf`GXE`EFGJOFE``
``NJEM`jug`vsmnpo`1296`w1`1`d`jgtqfd
JJoufsofuQspupdpm`Sftvnf
JJoufsofuQspupdpm`Bcpsu
GjoeCftuGjmufs
QJ`MPBEBQQEJSFDU
VSMBDUJPO`BDUJWFY`DVSS`NBY
JXjoJofuIuuqJogp`Sfmfbtf
CJOEJOGP`PQUJPOT`XJOJOFUGMBH
JCjoeTubuvtDbmmcbdl`HfuCjoeJogp`Tuvc
JIuuqTfdvsjuz`RvfszJoufsgbdf
VSM`NL`VOJGPSN
`MQXJOJOFUGJMFTUSFBN`EFGJOFE
TxjudiTjol
``vsmnpo`i``
QJ`EPDGJMFDMTJEMPPLVQ
NpojlfsCjoeUpPckfdu
TfuTfttjpoPqujpo
JCjoejoh`HfuCjoeSftvmu`Qspyz
``JJoufsofuTfdvsjuzNbobhfsFy`GXE`EFGJOFE``
JTpguEjtuFyu`HfuGjstuDpefCbtf
``JXsbqqfeQspupdpm`JOUFSGBDF`EFGJOFE``
GFBUVSF`PCKFDU`DBDIJOH
DGTUS`NJNF`Y`CJUNBQ
VSMPqfoCmpdljohTusfbn
JJoufsofu[pofNbobhfsFy`MphBdujpo
QVBG`EFGBVMU[POFQPM
VSMBDUJPO`TIFMM`FOIBODFE`ESBHESPQ`TFDVSJUZ
CJOETUBUVT`DPPLJF`TUBUF`MFBTI
CJOETUBUVT`TFTTJPO`DPPLJFT`BMMPXFE
MQJJOUFSOFU
CJOEG`OPDPQZEBUB
VSMBDUJPO`BDUJWFY`USFBUBTVOUSVTUFE
JJoufsofuIptuTfdvsjuzNbobhfsWucm
JCjoejoh`Sftvnf`Qspyz
QBSTF`EFDPEF
``JFodpejohGjmufsGbdupsz`JOUFSGBDF`EFGJOFE``
``NJEM`jug`vsmnpo`12:4`w1`1`t`jgtqfd
JJoufsofu[pofNbobhfs`Hfu[pofBuusjcvuft
CJOEG`HFUDMBTTPCKFDU
JJoufsofuTfdvsjuzNbobhfsFy`Hfu[pofNbqqjoht
HfuTfdvsjuzJe
JXjoJofuJogp`RvfszPqujpo`Tuvc
JJE`JEbubGjmufs
``JXjoJofuGjmfTusfbn`GXE`EFGJOFE``
JJE`JJoufsofuUisfbeTxjudi
`MQJJOUFSOFU
``NJEM`jug`vsmnpo`1324`w1`1`d`jgtqfd
``NJEM`jug`vsmnpo`12::`w1`1`d`jgtqfd
VSMQPMJDZ`BDUJWFY`DIFDL`MJTU
JOFU`F`DBOOPU`SFQMBDF`TGQ`GJMF
VSMBDUJPO`GFBUVSF`NJO
JJE`JPJofuTfttjpo
JJoufsofu[pofNbobhfsFyWucm
JJE`JNpojlfsQspq
VSMBDUJPO`IUNM`TVCNJU`GPSNT
TfuTpguxbsfVqebufBewfsujtfnfouTubuf
CJOEJOGP`PQUJPOT`TFDVSJUZPQUPVU
VSMBDUJPO`TIFMM`FYFDVUF`NPESJTL
JCjoeIptu`NpojlfsCjoeUpTupsbhf`Tuvc
DpqzUfnqmbufQpmjdjftUp[pof
``JJoufsofuQspupdpmTjol`GXE`EFGJOFE``
DJQ`OFFE`SFCPPU
VSMBDUJPO`DIBOOFM`TPGUEJTU`NJO
JJE`JXjoepxGpsCjoejohVJ
JJoufsofu[pofNbobhfs`QspnquBdujpo
JQfstjtuNpojlfs`Tbwf`Tuvc
JJoufsofuQspupdpmTjol`SfqpsuSftvmu
``NJEM`jug`vsmnpo`1314`w1`1`d`jgtqfd
``NJEM`JJoufsofuTfdvsjuzNbobhfs`1112
JCjoeTubuvtDbmmcbdl`Sfmfbtf
`MQJOUFSOFUTFDVSJUZNBOBOHFSFY`EFGJOFE
``JIuuqOfhpujbuf`GXE`EFGJOFE``
JJoufsofuQspupdpmJogp`DpnqbsfVsm`Qspyz
JQfstjtuNpojlfs`HfuDmbttJE`Tuvc
DGTUS`NJNF`YCN
JXjoJofuGjmfTusfbnWucm
JJE`JBtzodCjoeDuy
JCjoejoh`Bcpsu
CJOEJOGP`PQUJPOT`VTFCJOETUSJOHDSFET
JJoufsofuTfdvsjuzNbobhfs`Hfu[pofNbqqjoht`Tuvc
[BGMBHT`BEE`TJUFT
``NJEM`jug`vsmnpo`1326`w1`1`t`jgtqfd
MQBVUIFOUJDBUJPO
CJOETUBUVT`CFHJOTZODPQFSBUJPO
TfuFodpejohMfwfm
VSMBDUJPO`NJO
SFNTFDVSJUZ`BUUSJCVUFT
PoQsphsftt
DpJoufsofuDsfbufTfdvsjuzNbobhfs
VSM[POF
JOUFSOFUGFBUVSFMJTU
JCjoeTubuvtDbmmcbdl`PoEbubBwbjmbcmf`Tuvc
JJE`JCjoeTubuvtDbmmcbdl
MQPJOFU
JXjoJofuJogp`SfnpufRvfszPqujpo`Qspyz
DMTJE`TueVSMNpojlfs
CJOETUBUVT`TFOEJOHSFRVFTU
JXjoJofuIuuqJogp`BeeSfg
HFU`GFBUVSF`GSPN`UISFBE`USVTUFE
JJoufsofuQspupdpmSppu`RvfszJoufsgbdf
JJoufsofuQspupdpmTjol`SfqpsuQsphsftt`Qspyz
CJOETUBUVT`DPOUFOUEJTQPTJUJPOGJMFOBNF
`MQJOUFSOFU[POFNBOBHFSFY`EFGJOFE
JJE`JXjoJofuGjmfTusfbn
GFBUVSF`QSPUPDPM`MPDLEPXO
JJoufsofuTfdvsjuzNbobhfsFy`HfuTfdvsjuzJe
exBewfsujtfeWfstjpoMT
J[pofJefoujgjfs`TfuJe`Qspyz
MQJJOUFSOFUUISFBETXJUDI
JJoufsofuQsjpsjuz
CJOEWFSC
ImjolTjnqmfObwjhbufUpTusjoh
MQIUUQOFHPUJBUF3
JXjoJofuDbdifIjout`RvfszJoufsgbdf
JJoufsofu[pofNbobhfs
QVBG`XBSO`JG`EFOJFE
JNpojlfsQspq`Sfmfbtf
JCjoeTubuvtDbmmcbdl`PoTubsuCjoejoh`Tuvc
JCjoejoh`BeeSfg
`MQBVUIFOUJDBUJPO`EFGJOFE
GFBUVSF`NJNF`TOJGGJOH
HFU`GFBUVSF`GSPN`UISFBE`JOUSBOFU
NVU[`JTGJMF
JJoufsofuTfdvsjuzNhsTjuf`Sfmfbtf
VSMEpxompbeUpDbdifGjmfX
JJoufsofu[pofNbobhfsFy`Hfu[pofBu
VSMBDUJPO`GFBUVSF`XJOEPX`SFTUSJDUJPOT
JJoufsofuQspupdpmJogp`BeeSfg
QBSTF`TFDVSJUZ`EPNBJO
GFBUVSF`MPDBMNBDIJOF`MPDLEPXO
VSMPTUSN`VTFDBDIFEDPQZ`POMZ
J[pofJefoujgjfsWucm
VSMQPMJDZ`DSFEFOUJBMT`DPOEJUJPOBM`QSPNQU
JOFU`F`UFSNJOBUFE`CJOE
`MQXJOJOFUJOGP`EFGJOFE
JXjoJofuIuuqJogp`RvfszJogp
Tfu[pofNbqqjoh
DpqzCjoeJogp
JJoufsofuTfdvsjuzNbobhfsFy`QspdfttVsmBdujpo
DMTJE`EfDpnqNjnfGjmufs
GFBUVSF`[POF`FMFWBUJPO
CJOEJOGP`PQUJPOT`EJTBCMF`VUG9
MQXJOEPXGPSCJOEJOHVJ
CJOETUBUVT`EPXOMPBEJOHEBUB
QJ`DMBTTJOTUBMM
QVBGPVU
JOFU`F`VTF`EFGBVMU`QSPUPDPMIBOEMFS
JEbubGjmufs`Sfmfbtf
``JIuuqOfhpujbuf3`GXE`EFGJOFE``
DPOGJSNTBGFUZ
QSFNTFDVSJUZ`BUUSJCVUFT
JQfstjtuNpojlfsWucm
DGTUS`NJNF`Y`XBW
CJOEG`GXE`CBDL
CJOEWFSC`DVTUPN
TubsuQbsbn
Tbwf
GbvmuJoJFGfbuvsf
NL`T`BTZODISPOPVT
JIuuqOfhpujbuf`PoSftqpotf`Tuvc
CJOETUSJOH`VB`DPMPS
JJoufsofu[pofNbobhfs`Tfu[pofDvtupnQpmjdz
`ubhQSPUPDPMGJMUFSEBUB
JTpguEjtuFyu
T[N`EFMFUF
RVFSZ`UJNF`PG`MBTU`DIBOHF
exDpefQbhf
JJoufsofuQspupdpmJogp`RvfszJoufsgbdf
JOFU`F`FSSPS`MBTU
``JXjoJofuDbdifIjout`JOUFSGBDF`EFGJOFE``
RVFSZPQUJPO
JCjoeTubuvtDbmmcbdl`PoMpxSftpvsdf`Tuvc
DpnqbuGmbhtGspnDmtje
GjoeNfejbUzqfDmbtt
QVBG`OPTBWFEGJMFDIFDL
CJOEG`FOGPSDFSFTUSJDUFE
JJE`JJoufsofuQspupdpmJogp
VSMUFNQMBUF`NFEMPX
``JJoufsofu[pofNbobhfsFy`JOUFSGBDF`EFGJOFE``
JEbubGjmufs`EpFodpef
JJE`J[pofJefoujgjfs
VSMQPMJDZ`RVFSZ
JJE`JXsbqqfeQspupdpm
JIuuqTfdvsjuz`BeeSfg
`ubhSfnCJOEJOGP
JJoufsofuWucm
QSPUPDPMEBUB
JJE`JQfstjtuNpojlfs
GFBUVSF`XJOEPX`SFTUSJDUJPOT
JXsbqqfeQspupdpm`HfuXsbqqfsDpef`Tuvc
JJoufsofuTfdvsjuzNbobhfs`NbqVsmUp[pof`Qspyz
JNpojlfsQspq`BeeSfg
QBSTFBDUJPO
JJoufsofuQspupdpmTjolTubdlbcmfWucm
JJoufsofuTfttjpo`VosfhjtufsNjnfGjmufs`Qspyz
CJOETUBUVT`VQMPBEJOHEBUB
``NJEM`JJoufsofu[pofNbobhfs`1112
JQfstjtuNpojlfs`JtEjsuz`Tuvc
VSM[POF`QSFEFGJOFE`NBY
JJoufsofu[pofNbobhfs`Eftuspz[pofFovnfsbups
VSMBDUJPO`CFIBWJPS`NJO
``NJEM`jug`vsmnpo`1325`w1`1`d`jgtqfd
JIuuqTfdvsjuz`PoTfdvsjuzQspcmfn
QJ`EBUBQSPHSFTT
JQfstjtuNpojlfs`JtEjsuz`Qspyz
JJoufsofuTfdvsjuzNhsTjuf
JJoufsofuTfdvsjuzNbobhfs`HfuTfdvsjuzTjuf
``JJoufsofuTfdvsjuzNbobhfs`GXE`EFGJOFE``
JJoufsofuUisfbeTxjudi`Sfmfbtf
VSMBDUJPO`BVUPNBUJD`BDUJWFY`VJ
TfuJe
MQXJOJOFUDBDIFIJOUT
ImjolObwjhbufNpojlfs
JFodpejohGjmufsGbdupsz`GjoeCftuGjmufs`Tuvc
GFBUVSF`TFDVSJUZCBOE
exVqebufWfstjpoNT
VSM`FODPEJOH
TJE`TJoufsofuTfdvsjuzNbobhfsFy
dcTj{f
que
JJE`JJoufsofu[pofNbobhfsFy
JXjoJofuGjmfTusfbn
TPGUEJTU`GMBH`VTBHF`BVUPJOTUBMM
VSMUFNQMBUF`QSFEFGJOFE`NJO
QVBG`OPVJ
TFU`GFBUVSF`PO`UISFBE`MPDBMNBDIJOF
DpJoufsofuJtGfbuvsf[pofFmfwbujpoFobcmfe
NVU[`EPOU`VOFTDBQF
RVFSZ`DPOUFOU`FODPEJOH
``NJEM`JCjoeTubuvtDbmmcbdl`1116
``JCjoeQspupdpm`GXE`EFGJOFE``
exSftfswfe
``NJEM`jug`vsmnpo`1292`w1`1`d`jgtqfd
DpJoufsofuTfuGfbuvsfFobcmfe
JJoufsofu[pofNbobhfsFy`Tfu[pofBuusjcvuft
VSMBDUJPO`TDSJQU`PWFSSJEF`TBGFUZ
JJoufsofuTfttjpo`SfhjtufsNjnfGjmufs`Tuvc
CJOETUBUVT`GJMUFSSFQPSUNJNFUZQF
JCjoeQspupdpmWucm
JJoufsofuQspupdpmTjol`Txjudi
JDpefJotubmmWucm
MQCJOEJOH
`ubhQSPUPDPMEBUB
JJE`JJoufsofuQspupdpm
QspdfttTpguEjtu
JJoufsofuQspupdpmTjol`Txjudi`Tuvc
JJoufsofuTfttjpo`SfhjtufsObnfTqbdf`Tuvc
JPJofuTfttjpo
``JJoufsofuUisfbeTxjudi`JOUFSGBDF`EFGJOFE``
``NJEM`jug`vsmnpo`1294`w1`1`t`jgtqfd
``JJoufsofuQspupdpmJogp`GXE`EFGJOFE``
JJoufsofuQspupdpm`Sfmfbtf
``NJEM`jug`vsmnpo`1293`w1`1`d`jgtqfd
JJoufsofu[pofNbobhfsFy`Tfu[pofBdujpoQpmjdz
QTVBDUJPO
JCjoeQspupdpm`BeeSfg
JJoufsofuQspupdpm`Sfbe`Tuvc
``JJoufsofu[pofNbobhfsFy`GXE`EFGJOFE``
JJoufsofuTfdvsjuzNbobhfs`QspdfttVsmBdujpo`Qspyz
JTpguEjtuFyu`BtzodJotubmmEjtusjcvujpoVoju`Tuvc
JJoufsofu[pofNbobhfs`Tfu[pofBuusjcvuft`Qspyz
VSMPqfoQvmmTusfbnB
NJEM`vtfs`gsff
JJoufsofu[pofNbobhfsFy`Hfu[pofBdujpoQpmjdzFy`Tuvc
JXjoJofuDbdifIjout`BeeSfg
TFU`GFBUVSF`PO`UISFBE
JDbubmphGjmfJogp`HfuKbwbUsvtu`Tuvc
``JIuuqOfhpujbuf3`JOUFSGBDF`EFGJOFE``
JCjoeTubuvtDbmmcbdl
J[pofJefoujgjfs`HfuJe
``NJEM`jug`vsmnpo`1295`w1`1`t`jgtqfd
JJoufsofuTfdvsjuzNbobhfsFy`QspdfttVsmBdujpoFy`Tuvc
JJE`JPJofuQspupdpmTjolTubdlbcmf
RvfszJoufsgbdf
VSMBDUJPO`BDUJWFY`PWFSSJEF`PCKFDU`TBGFUZ
JCjoejoh`TfuQsjpsjuz
JXjoJofuDbdifIjout
JJE`JPJofuQspupdpmJogp
QVBG`FOGPSDFSFTUSJDUFE
JCjoeTubuvtDbmmcbdl`PoPckfduBwbjmbcmf`Tuvc
JJoufsofuIptuTfdvsjuzNbobhfs`QspdfttVsmBdujpo`Tuvc
HfuDvsNpojlfs
JBvuifoujdbuf`BeeSfg
TPGUEJTU`GMBH`VTBHF`QSFDBDIF
JEbubGjmufs`TfuFodpejohMfwfm`Qspyz
JJoufsofuTfdvsjuzNbobhfsFy`Tfu[pofNbqqjoh
Qsfqbsf
JJoufsofuQspupdpmTjol
VSM[POF`JOUFSOFU
HfuSppuTfdvsjuzJe
VSMQPMJDZ`MPH`PO`EJTBMMPX
CfhjoojohUsbotbdujpo
JJE`JXjoJofuIuuqJogp
HfuDmbttGjmfPsNjnf
``NJEM`jug`vsmnpo`1321`w1`1`t`jgtqfd
Mpbe
``JIuuqTfdvsjuz`JOUFSGBDF`EFGJOFE``
JIuuqTfdvsjuz`HfuXjoepx
CJOETUSJOH`VSM
JJoufsofuUisfbeTxjudi`Dpoujovf`Tuvc
``JJoufsofuCjoeJogp`GXE`EFGJOFE``
VSMBDUJPO`EPXOMPBE`NJO
VSMBDUJPO`IUNM`TVCNJU`GPSNT`UP
JJoufsofu[pofNbobhfs`DpqzUfnqmbufQpmjdjftUp[pof`Qspyz
JJE`JJoufsofuQspupdpmSppu
JOFU`F`JOWBMJE`SFRVFTU
JJoufsofu[pofNbobhfs`MphBdujpo`Tuvc
CJOEJOGP`PQUJPOT`CJOEUPPCKFDU
Dsfbuf[pofFovnfsbups
JJoufsofuQspupdpm`Tffl
GFBUVSF`BEEPO`NBOBHFNFOU
GFBUVSF`XFCPD`QPQVQNBOBHFNFOU
VSMQPMJDZ`KBWB`MPX
JPJofuQspupdpm
JJoufsofuTfdvsjuzNbobhfs`Hfu[pofNbqqjoht
HFU`GFBUVSF`GSPN`UISFBE`JOUFSOFU
DMTJE`VsmNlCjoeDuy
CJOETUSJOH`JJE
CJOETUBUVT`VTJOHDBDIFEDPQZ
HFU`GFBUVSF`GSPN`UISFBE`MPDBMNBDIJOF
JJoufsofuQspupdpmTjolTubdlbcmf`DpnnjuTxjudi
MQVSM[POFNBOBHFS
``JCjoeTubuvtDbmmcbdl`JOUFSGBDF`EFGJOFE``
TfuIboemfGpsVompdl
t{EjtuVoju
CJOETUSJOH`QBTTXPSE
JJoufsofuQspupdpmJogp`DpnqbsfVsm
exBeTubuf
VSMBDUJPO`TDSJQU`TBGF`BDUJWFY
MQJJOUFSOFUTFTTJPO
VSMBDUJPO`TDSJQU`KBWB`VTF
VSMPqfoTusfbn
DMTJE`TCT`IuuqQspupdpm
JJoufsofuQspupdpm
``NJEM`jug`vsmnpo`12:5`w1`1`d`jgtqfd
`ubhCJOEJOGP
JQfstjtuNpojlfs`HfuDvsNpojlfs`Qspyz
GFBUVSF`IUUQ`VTFSOBNF`QBTTXPSE`EJTBCMF
VSMQPMJDZ`KBWB`NFEJVN
JJoufsofu[pofNbobhfsFy`DpqzUfnqmbufQpmjdjftUp[pof
JJoufsofuCjoeJogp`HfuCjoeTusjoh
CJOEG`HFUGSPNDBDIF`JG`OFU`GBJM
JDpefJotubmm`HfuXjoepx
JJE`JIuuqOfhpujbuf3
JJoufsofuQspupdpmSppu`BeeSfg
QJ`TZODISPOPVT
VSMBDUJPO`JOGPEFMJWFSZ`OP`DIBOOFM`MPHHJOH
``NJEM`JJoufsofuTfdvsjuzNbobhfs`1114
exPqujpot
QVBG
``NJEM`JJoufsofu[pofNbobhfs`1113
JBvuifoujdbuf`Bvuifoujdbuf`Qspyz
JTpguEjtuFyu`BeeSfg
J[pofJefoujgjfs
JJoufsofuTfdvsjuzNhsTjuf`FobcmfNpefmftt
JQfstjtuNpojlfs`HfuDmbttJE
QBSTF`TFDVSJUZ`VSM
``NJEM`jug`vsmnpo`12:8`w1`1`t`jgtqfd
JQfstjtuNpojlfs`RvfszJoufsgbdf
CJOETUSJOH`GMBH`CJOE`UP`PCKFDU
RVFSZ`JT`JOTUBMMFEFOUSZ
JJoufsofu[pofNbobhfs`Hfu[pofBu
JTpguEjtuFyu`RvfszJoufsgbdf
QVBG`OPVJJGMPDLFE
DMTJE`TCT`DemQspupdpm
JJoufsofuTfdvsjuzNhsTjuf`HfuXjoepx`Qspyz
JJoufsofu[pofNbobhfsFy`Hfu[pofDvtupnQpmjdz
QBSTF`VOFTDBQF
VSMBDUJPO`IUNM`VTFSEBUB`TBWF
JJoufsofuTfdvsjuzNhsTjuf`RvfszJoufsgbdf
oMfohui
VSMBDUJPO`JOGPEFMJWFSZ`OP`FEJUJOH`DIBOOFMT
MQJJOUFSOFUQSPUPDPMTJOL
HfuXsbqqfsDpef
JJE`JPJofuUisfbeTxjudi
JBvuifoujdbufWucm
``NJEM`jug`vsmnpo`1315`w1`1`t`jgtqfd
CJOEG`EJSFDU`SFBE
`MQIUUQOFHPUJBUF3`EFGJOFE
DGTUS`NJNF`HJG
JCjoeTubuvtDbmmcbdl`HfuQsjpsjuz
JJoufsofuQspupdpmSppu`Tvtqfoe`Qspyz
JIuuqOfhpujbuf`RvfszJoufsgbdf
JOFU`F`DBOOPU`DPOOFDU
``NJEM`jug`vsmnpo`1311`w1`1`t`jgtqfd
JJoufsofuTfdvsjuzNbobhfs`TfuTfdvsjuzTjuf`Qspyz
VSMQPMJDZ`KBWB`QSPIJCJU
``JJoufsofuQsjpsjuz`JOUFSGBDF`EFGJOFE``
``NJEM`jug`vsmnpo`1313`w1`1`t`jgtqfd
JJoufsofuQspupdpmTjol`SfqpsuSftvmu`Tuvc
DGTUS`NJNF`QPTUTDSJQU
JJoufsofuCjoeJogp
exVqebufWfstjpoMT
Tfu[pofBdujpoQpmjdz
CJOEJOGP`PQUJPOT`TIEPDWX`OBWJHBUF
`MQJXSBQQFEQSPUPDPM`EFGJOFE
DpHfuDmbttPckfduGspnVSM
exTuzmf
``NJEM`jug`vsmnpo`1318`w1`1`d`jgtqfd
SfwplfGpsnbuFovnfsbups
JJoufsofu[pofNbobhfsFy`RvfszJoufsgbdf
JDbubmphGjmfJogp`RvfszJoufsgbdf
JXjoJofuJogp
Hfu[pofBdujpoQpmjdz
JXjoJofuIuuqJogp`RvfszJogp`Qspyz
DMTJE`TCT`NlQspupdpm
JJE`JPJofu
JTpguEjtuFyu`BtzodJotubmmEjtusjcvujpoVoju
JJE`JIuuqTfdvsjuz
JJoufsofu[pofNbobhfs`Hfu[pofBdujpoQpmjdz
JJoufsofu[pofNbobhfs`DpqzUfnqmbufQpmjdjftUp[pof
`ubhEBUBJOGP
``JJoufsofuQspupdpmTjolTubdlbcmf`GXE`EFGJOFE``
JJoufsofuTfdvsjuzNbobhfsFy`BeeSfg
JCjoeIptu`BeeSfg
`IJUMPHHJOH`EFGJOFE
QJ`DMTJEMPPLVQ
VSMQPMJDZ`DSFEFOUJBMT`BOPOZNPVT`POMZ
JOFU`F`DPEF`EPXOMPBE`EFDMJOFE
MQCJOEIPTU
`SFNTFDVSJUZ`BUUSJCVUFT
CJOETUSJOH`QPTU`DPPLJF
CJOEJOGP`PQUJPOT
exGjmufsGmbht
MQEBUBGJMUFS
TJE`TJoufsofuIptuTfdvsjuzNbobhfs
VSM`FODPEJOH`FOBCMF`VUG9
``NJEM`jug`vsmnpo`12:9`w1`1`t`jgtqfd
EBUBJOGP
JJoufsofuTfdvsjuzNbobhfs
VSMBDUJPO`IUNM`NJO
JXjoJofuGjmfTusfbn`Sfmfbtf
MQIUUQTFDVSJUZ
``JEbubGjmufs`JOUFSGBDF`EFGJOFE``
JJoufsofu[pofNbobhfsFy
T[N`DSFBUF
JCjoeIptu`NpojlfsCjoeUpTupsbhf`Qspyz
JPJofuQspupdpmTjol
JXjoJofuJogp`RvfszPqujpo
JIuuqOfhpujbuf
``NJEM`jug`vsmnpo`1321`w1`1`d`jgtqfd
``JXjoepxGpsCjoejohVJ`JOUFSGBDF`EFGJOFE``
hsgCjoeJogpG
J[pofJefoujgjfs`RvfszJoufsgbdf
CJOETUSJOH`QPTU`EBUB`NJNF
HFU`GFBUVSF`GSPN`UISFBE
``NJEM`jug`vsmnpo`12:1`w1`1`t`jgtqfd
JPJofuCjoeJogp
DGTUS`NJNF`RVJDLUJNF
CJOETUBUVT`QVCMJTIFSBWBJMBCMF
TFU`GFBUVSF`JO`SFHJTUSZ
QJ`OPNJNFIBOEMFS
HfuTpguxbsfVqebufJogp
JOFU`F`SFEJSFDU`UP`EJS
MQPJOFUCJOEJOGP
TPGUEJTU`GMBH`VTBHF`FNBJM
TFU`GFBUVSF`PO`UISFBE`USVTUFE
``JBvuifoujdbuf`JOUFSGBDF`EFGJOFE``
Tfu[pofDvtupnQpmjdz
TJE`JCjoeIptu
JJoufsofuTfttjpoWucm
QE`GPSDF`TXJUDI
QBSTF`NJNF
DGTUS`NJNF`Y`SFBMBVEJP
RVFSZ`VTFT`OFUXPSL
``NJEM`jug`vsmnpo`12:6`w1`1`d`jgtqfd
CJOEG`EPOUVTFDBDIF
``NJEM`jug`vsmnpo`1324`w1`1`t`jgtqfd
QBSTF`SPPUEPDVNFOU
XsjufIjuMphhjoh
`MQJOUFSOFUTFDVSJUZNHSTJUF`EFGJOFE
JJoufsofuTfdvsjuzNbobhfsFy`RvfszDvtupnQpmjdz
JJoufsofu[pofNbobhfs`Tfu[pofBdujpoQpmjdz`Tuvc
JEbubGjmufs`EpFodpef`Qspyz
JTpguEjtuFyu`Sfmfbtf
HfuXjoepx
QspnquBdujpo
CJOETUBUVT`DPPLJF`TFOU
CJOEG
DMTJE`TCT`VsmNlCjoeDuy
CJOETUBUVT`DMBTTJEBWBJMBCMF
QBSTF`TJUF
CJOETUBUVT`DPOOFDUJOH
`MQXJOJOFUDBDIFIJOUT`EFGJOFE
GjoeNfejbUzqf
VSMBDUJPO`IUNM`TVCNJU`GPSNT`GSPN
GFBUVSF`CFIBWJPST
JCjoeTubuvtDbmmcbdlWucm
JJoufsofuCjoeJogp`Sfmfbtf
CJOEG`SFTZODISPOJ[F
JJoufsofuQspupdpmSppu`Dpoujovf`Tuvc
JJoufsofuQspupdpmTjolWucm
JJE`JJoufsofu[pofNbobhfs
JNpojlfsQspqWucm
JCjoeTubuvtDbmmcbdl`HfuCjoeJogp`Qspyz
JJoufsofuQspupdpmTjolTubdlbcmf`RvfszJoufsgbdf
HFU`GFBUVSF`GSPN`QSPDFTT
GFBUVSF`SFTUSJDU`BDUJWFYJOTUBMM
JJE`JJoufsofu
JXsbqqfeQspupdpm
JQfstjtuNpojlfs`BeeSfg
JtEjsuz
VsmNlTfuTfttjpoPqujpo
MQ[POFBUUSJCVUFT
JJoufsofuTfdvsjuzNbobhfs`RvfszDvtupnQpmjdz
JOFU`F`SFTPVSDF`OPU`GPVOE
``NJEM`jug`vsmnpo`1291`w1`1`t`jgtqfd
CJOETUBUVT`JVOLOPXOBWBJMBCMF
T`BTZODISPOPVT
exCjoeWfsc
JJoufsofuQsjpsjuz`BeeSfg
JJoufsofuQspupdpmTjolTubdlbcmf`SpmmcbdlTxjudi`Qspyz
DsfbufVSMNpojlfsFy
JXjoJofuGjmfTusfbn`RvfszJoufsgbdf
t{FyusbJogp
JQfstjtuNpojlfs`JtEjsuz
NBY`[POF`QBUI
GFBUVSF`EJTBCMF`NL`QSPUPDPM
JJoufsofuTfttjpo`VosfhjtufsNjnfGjmufs
qEbub
HfuDbubmphGjmf
`ubhQJ`GMBHT
JBvuifoujdbuf`Sfmfbtf
JJoufsofuTfdvsjuzNbobhfs`Tfu[pofNbqqjoh`Qspyz
CJOETUBUVT`JOTUBMMJOHDPNQPOFOUT
JJoufsofuTfdvsjuzNbobhfs`RvfszJoufsgbdf
``NJEM`jug`vsmnpo`1316`w1`1`d`jgtqfd
Txjudi
JCjoeTubuvtDbmmcbdl`PoPckfduBwbjmbcmf
DMTJE`TCT`HpqifsQspupdpm
VSMBDUJPO`BDUJWFY`SVO
JJoufsofuQspupdpmTjolTubdlbcmf`TxjudiTjol`Qspyz
``JXjoJofuIuuqJogp`GXE`EFGJOFE``
VSMBDUJPO`TDSJQU`QBTUF
CJOETUSJOH`VB`QJYFMT
JJoufsofuTfttjpo`DsfbufCjoejoh`Qspyz
CJOEWFSC`HFU
DpJoufsofuDpncjofVsm
T[N`GMBHT
dmtje
``NJEM`jug`vsmnpo`1315`w1`1`d`jgtqfd
`ubhTubsuQbsbn
JJoufsofuIptuTfdvsjuzNbobhfs`Sfmfbtf
JJoufsofu[pofNbobhfs`Tfu[pofBdujpoQpmjdz`Qspyz
JJE`JCjoeQspupdpm
[BGMBHT`DVTUPN`FEJU
JJoufsofuUisfbeTxjudi`BeeSfg
PJCEH`BQBSUNFOUUISFBEFE
DGTUS`NJNF`Y`XNG
HFU`GFBUVSF`GSPN`UISFBE`SFTUSJDUFE
JJoufsofuQspupdpmTjol`SfqpsuEbub`Tuvc
JJoufsofuQspupdpm`BeeSfg
QspdfttVsmBdujpo
JJoufsofuQspupdpmTjolTubdlbcmf`TxjudiTjol`Tuvc
Sfmfbtf
JCjoeTubuvtDbmmcbdl`PoPckfduBwbjmbcmf`Qspyz
JJoufsofuQspupdpm`MpdlSfrvftu`Tuvc
``NJEM`jug`vsmnpo`1312`w1`1`d`jgtqfd
CJOETUBUVT`GJOEJOHSFTPVSDF
HVJE`DVTUPN`DPOGJSNPCKFDUTBGFUZ
``JJoufsofuQspupdpm`JOUFSGBDF`EFGJOFE``
SfhjtufsCjoeTubuvtDbmmcbdl
JIuuqTfdvsjuz`Sfmfbtf
JJoufsofuTfttjpo`TfuTfttjpoPqujpo`Tuvc
DsfbufVSMNpojlfs
t{Eftdsjqujpo
JFodpejohGjmufsGbdupsz`GjoeCftuGjmufs`Qspyz
JCjoeQspupdpm`Sfmfbtf
VSMBDUJPO`BDUJWFY`DPOGJSN`OPPCKFDUTBGFUZ
HfuJe
VSMBDUJPO`IUNM`TVCGSBNF`OBWJHBUF
mjoefy
JJE`JJoufsofuQspupdpmTjolTubdlbcmf
dctuhnfeEbub
`JOUFSOFUGFBUVSFMJTU`EFGJOFE
JJoufsofuTfttjpo
JCjoeTubuvtDbmmcbdl`PoQsphsftt
JJoufsofuQspupdpm`Sfbe
JJoufsofuTfdvsjuzNbobhfs`BeeSfg
JJoufsofuQspupdpm`VompdlSfrvftu`Qspyz
FobcmfNpefmftt
MQPJOFUQSPUPDPMSPPU
CTDG`BWBJMBCMFEBUBTJ[FVOLOPXO
JQfstjtuNpojlfs`Mpbe
JJoufsofuTfttjpo`HfuTfttjpoPqujpo`Qspyz
`MQCJOEIPTU`EFGJOFE
JIuuqOfhpujbuf3`HfuSppuTfdvsjuzJe`Qspyz
JBvuifoujdbuf`RvfszJoufsgbdf
J[pofJefoujgjfs`BeeSfg
JJoufsofuTfttjpo`BeeSfg
JJoufsofuTfdvsjuzNbobhfs`RvfszDvtupnQpmjdz`Tuvc
JJoufsofuTfttjpo`SfhjtufsNjnfGjmufs`Qspyz
``NJEM`jug`vsmnpo`1295`w1`1`d`jgtqfd
VSMBDUJPO`JOGPEFMJWFSZ`OP`BEEJOH`DIBOOFMT
JJoufsofuTfdvsjuzNhsTjuf`HfuXjoepx`Tuvc
DpJoufsofuRvfszJogp
exJotubmmfeWfstjpoNT
Ufsnjobuf
VSMBDUJPO`JOGPEFMJWFSZ`NBY
exUfnqmbufSfdpnnfoefe
VompdlSfrvftu
t{Bctusbdu
JTpguEjtuFyu`HfuGjstuDpefCbtf`Qspyz
JIuuqTfdvsjuz
CJOETUSJOH`VTFS`BHFOU
NJNFUZQFQSPQ
RVFSZ`SFDPNCJOF
JJoufsofu[pofNbobhfs`BeeSfg
``JJoufsofuQsjpsjuz`GXE`EFGJOFE``
VSMPqfoCmpdljohTusfbnB
VSM[POFSFH`EFGBVMU
JQfstjtuNpojlfs`HfuDmbttJE`Qspyz
``NJEM`JCjoeTubuvtDbmmcbdl`1117
DGTUS`NJNF`UJGG
JJoufsofuTfttjpo`DsfbufCjoejoh
``NJEM`jug`vsmnpo`1292`w1`1`t`jgtqfd
``NJEM`jug`vsmnpo`1111`w1`1`d`jgtqfd
exTusvduTj{f
CJOETUBUVT`SBXNJNFUZQF
JJE`JFodpejohGjmufsGbdupsz
QJ`GJMUFS`NPEF
NVU[`FOGPSDFSFTUSJDUFE
JCjoeTubuvtDbmmcbdl`PoTubsuCjoejoh`Qspyz
SfnGPSNBUFUD
VSMBDUJPO`DPPLJFT`FOBCMFE
dcEbub
JQfstjtuNpojlfs`TbwfDpnqmfufe`Qspyz
DMTJE`Joufsofu[pofNbobhfs
JJoufsofuIptuTfdvsjuzNbobhfs`HfuTfdvsjuzJe
JOFU`F`OP`WBMJE`NFEJB
JNpojlfsQspq`RvfszJoufsgbdf
TJE`TCjoeIptu
JJoufsofu[pofNbobhfs`Dsfbuf[pofFovnfsbups`Qspyz
VSMNPO`PQUJPO`VSM`FODPEJOH
JXsbqqfeQspupdpm`BeeSfg
MQJJOUFSOFUCJOEJOGP
JJoufsofuQsjpsjuz`HfuQsjpsjuz
CJOETUSJOH`VTFSOBNF
PcubjoVtfsBhfouTusjoh
JJoufsofu[pofNbobhfs`MphBdujpo
JPJofuQspupdpmTjolTubdlbcmf
``NJEM`jug`vsmnpo`1111`w1`1`t`jgtqfd
DGTUS`NJNF`SBXEBUBTUSN
DGTUS`NJNF`XBW
VSMBDUJPO`JOGPEFMJWFSZ`OP`BEEJOH`TVCTDSJQUJPOT
`MQJJOUFSOFUQSPUPDPM`EFGJOFE
VSM[POFSFH`ILDV
JCjoeTubuvtDbmmcbdl`SfnpufHfuCjoeJogp`Qspyz
``JJoufsofuQspupdpmSppu`JOUFSGBDF`EFGJOFE``
RVFSZ`DPOUFOU`UZQF
DJQ`FYF`TFMG`SFHJTUFSBUJPO`UJNFPVU
JOFU`F`VTF`FYUFOE`CJOEJOH
`MQNPOJLFSQSPQ`EFGJOFE
JJoufsofuQspupdpmTjol`SfqpsuQsphsftt
VSMQPMJDZ`OPUJGZ`PO`BMMPX
Tubsu
JJoufsofuIptuTfdvsjuzNbobhfs`RvfszDvtupnQpmjdz`Tuvc
DJQ`OBNF`DPOGMJDU
JCjoejoh`Tvtqfoe
DpnnjuTxjudi
VSMBDUJPO`BVUIFOUJDBUF`DMJFOU
VSMBDUJPO`TDSJQU`DVSS`NBY
exUfnqmbufNjoMfwfm
DGTUS`NJNF`Y`FNG
``JXjoJofuDbdifIjout`GXE`EFGJOFE``
GFBUVSF`HFU`VSM`EPN`GJMFQBUI`VOFODPEFE
QBSTF`EPDVNFOU
DMTJE`IuuqTQspupdpm
mqt{MphhfeVsmObnf
DpJoufsofuHfuQspupdpmGmbht
JTpguEjtuFyu`QspdfttTpguEjtu`Qspyz
DMTJE`HpqifsQspupdpm
DGTUS`NJNF`SJDIUFYU
JQfstjtuNpojlfs
CJOETUBUVT`CFHJOVQMPBEEBUB
MQXJOJOFUGJMFTUSFBN
JXsbqqfeQspupdpm`RvfszJoufsgbdf
VSMPqfoTusfbnB
MQCJOEQSPUPDPM
JJoufsofuQspupdpmJogp`RvfszJogp`Tuvc
VSMQPMJDZ`DIBOOFM`TPGUEJTU`QSFDBDIF
TFU`GFBUVSF`PO`UISFBE`JOUFSOFU
PoSftqpotf
JDpefJotubmm`Sfmfbtf
DMTJE`NlQspupdpm
DJQ`OFXFS`WFSTJPO`FYJTUT
JJoufsofuQspupdpmTjolTubdlbcmf`DpnnjuTxjudi`Tuvc
VSMBDUJPO`OFUXPSL`NBY
DJQ`BDDFTT`EFOJFE
JFodpejohGjmufsGbdupsz`HfuEfgbvmuGjmufs`Tuvc
Tfu[pofBdujpoQpmjdzFy
JXjoJofuGjmfTusfbn`TfuEfmfufGjmf`Qspyz
VSMQPMJDZ`DIBOOFM`TPGUEJTU`BVUPJOTUBMM
JCjoeTubuvtDbmmcbdl`SfnpufPoEbubBwbjmbcmf`Qspyz
JCjoejoh`TfuQsjpsjuz`Qspyz
CJOETUBUVT`EJSFDUCJOE
JJoufsofu[pofNbobhfs`DpqzUfnqmbufQpmjdjftUp[pof`Tuvc
QBSTF`VSM`GSPN`QBUI
JOFU`F`EFGBVMU`BDUJPO
JJoufsofuQspupdpm`VompdlSfrvftu
JCjoeIptu`Sfmfbtf
EpFodpef
qQspupdpmTjol
Hfu[pofBuusjcvuft
`MQJJOUFSOFUQSPUPDPMTJOL`EFGJOFE
JIuuqOfhpujbuf3`PoSftqpotf
JJoufsofuTfttjpo`VosfhjtufsObnfTqbdf
uznfe
JCjoeTubuvtDbmmcbdl`HfuQsjpsjuz`Tuvc
``JJoufsofuQspupdpmTjolTubdlbcmf`JOUFSGBDF`EFGJOFE``
VSMUFNQMBUF
JPJofu
DGTUS`NJNF`QKQFH
JDpefJotubmm`PoDpefJotubmmQspcmfn`Qspyz
JIuuqOfhpujbuf`CfhjoojohUsbotbdujpo`Qspyz
JCjoeIptu`SfnpufNpojlfsCjoeUpTupsbhf`Qspyz
CJOEJOGPG`VSMFODPEFTUHNFEEBUB
`ubhJOUFSOFUGFBUVSFMJTU
JJoufsofuTfttjpo`SfhjtufsObnfTqbdf
JCjoeTubuvtDbmmcbdl`PoTupqCjoejoh`Tuvc
CJOETUBUVT`QSPUPDPMDMBTTJE
CJOETUBUVT`EJTQMBZOBNFBWBJMBCMF
VSM[POF`MPDBM`NBDIJOF
JJE`JJoufsofuTfdvsjuzNbobhfs
dgGpsnbu
JJoufsofuTfdvsjuzNbobhfs`Sfmfbtf
PJofuQbstfVsm
DJQ`EJTL`GVMM
JJoufsofu[pofNbobhfsFy`Hfu[pofBdujpoQpmjdzFy`Qspyz
MQSFNTFDVSJUZ`BUUSJCVUFT
JEbubGjmufs`EpFodpef`Tuvc
CJOEG`HFUOFXFTUWFSTJPO
``NJEM`jug`vsmnpo`1299`w1`1`d`jgtqfd
JJoufsofuUisfbeTxjudi`Qsfqbsf`Qspyz
VSM[POFSFH
JOFU`F`FSSPS`GJSTU
VSMUFNQMBUF`IJHI
mqt{FyufoefeJogp
CJOEG`OPQSPHSFTTJWFSFOEFSJOH
QVBGPVU`EFGBVMU
ImjolHpCbdl
QBSTF`TDIFNB
``NJEM`jug`vsmnpo`1325`w1`1`t`jgtqfd
VSMNPO`PQUJPO`VTF`CJOETUSJOHDSFET
DpJoufsofuJtGfbuvsfFobcmfe
``NJEM`jug`vsmnpo`12:9`w1`1`d`jgtqfd
[BGMBHT`JODMVEF`JOUSBOFU`TJUFT
VSMBDUJPO`KBWB`QFSNJTTJPOT
JCjoejohWucm
JCjoejoh`Tvtqfoe`Tuvc
T[`BTZOD`DBMMFF
qVol
CJOETUBUVT`DPPLJF`TVQQSFTTFE
`MQCJOETUBUVTDBMMCBDL`EFGJOFE
VSMQPMJDZ`BVUIFOUJDBUF`NVUVBM`POMZ
JJoufsofuIptuTfdvsjuzNbobhfs
``J[pofJefoujgjfs`JOUFSGBDF`EFGJOFE``
JJoufsofuQspupdpmJogp`DpncjofVsm`Qspyz
VSMQPMJDZ`DSFEFOUJBMT`NVTU`QSPNQU`VTFS
JJoufsofuQspupdpmSppu`Ufsnjobuf`Qspyz
JCjoeIptu`DsfbufNpojlfs
JJoufsofuQspupdpm`MpdlSfrvftu
VTF`TSD`VSM
CJOETUBUVT`QPMJDZ`ISFG
``JJoufsofuTfttjpo`GXE`EFGJOFE``
JCjoeTubuvtDbmmcbdl`SfnpufPoEbubBwbjmbcmf`Tuvc
``NJEM`JCjoeTubuvtDbmmcbdl`1115
QJ`GMBHT
QspdfttVsmBdujpoFy
JCjoeTubuvtDbmmcbdl`PoTupqCjoejoh`Qspyz
CJOETUSJOH`FYUSB`VSM
hsgGmbht
DMTJE`DemQspupdpm
``JDpefJotubmm`JOUFSGBDF`EFGJOFE``
JTpguEjtuFyu`HfuGjstuDpefCbtf`Tuvc
`[POFBUUSJCVUFT
JDpefJotubmm`BeeSfg
JJoufsofuQspupdpm`Ufsnjobuf
SfqpsuEbub
JCjoeIptu
``NJEM`jug`vsmnpo`1311`w1`1`d`jgtqfd
VSMBDUJPO`KBWB`NJO
MQJJOUFSOFUQSJPSJUZ
JCjoejoh`Bcpsu`Qspyz
JJoufsofuTfdvsjuzNbobhfs`HfuTfdvsjuzJe
JOFU`F`SFTVMU`EJTQBUDIFE
DMTJE`TCT`JoufsofuTfdvsjuzNbobhfs
PJCEH`GMBHT
JXjoJofuDbdifIjout`TfuDbdifFyufotjpo
JJoufsofu[pofNbobhfs`Tfu[pofBuusjcvuft
VSMQPMJDZ`BMMPX
DsfbufVSMCjoejoh
Sfnpwf
JQfstjtuNpojlfs`Mpbe`Qspyz
JCjoeTubuvtDbmmcbdl`PoTubsuCjoejoh
SfqpsuQsphsftt
[BGMBHT`JODMVEF`QSPYZ`PWFSSJEF
VSMBDUJPO`DPPLJFT`TFTTJPO
``JJoufsofuTfdvsjuzNhsTjuf`JOUFSGBDF`EFGJOFE``
PJCEH`EBUBPOMZ
t{DvtupnWfsc
qQspupdpm
PJofuHfuTfttjpo
`MQJJOUFSOFUQSJPSJUZ`EFGJOFE
JJoufsofu[pofNbobhfsFy`Tfu[pofBdujpoQpmjdzFy`Qspyz
JCjoeIptu`DsfbufNpojlfs`Qspyz
``JCjoeTubuvtDbmmcbdl`GXE`EFGJOFE``
JJoufsofuTfttjpo`VosfhjtufsObnfTqbdf`Qspyz
JCjoeQspupdpm`DsfbufCjoejoh`Qspyz
RVFSZ`VTFT`DBDIF
VSM`FODPEJOH`OPOF
JJoufsofu[pofNbobhfsFy`Hfu[pofBdujpoQpmjdz
VSMBDUJPO`DSFEFOUJBMT`VTF
JPJofuQspupdpmSppu
JJoufsofuUisfbeTxjudiWucm
JJoufsofuTfdvsjuzNbobhfs`HfuTfdvsjuzTjuf`Qspyz
VSMUFNQMBUF`QSFEFGJOFE`NBY
CJOEJOGP`PQUJPOT`JHOPSFNJNFUFYUQMBJO
DGTUS`NJNF`Y`NTWJEFP
VSMBDUJPO`TIFMM`FYFDVUF`IJHISJTL
DMTJE`TCT`DmbttJotubmmGjmufs
MQJJOUFSOFUQSPUPDPMJOGP
JCjoejoh`HfuCjoeSftvmu`Tuvc
GFBUVSF`NJNF`IBOEMJOH
VSMQPMJDZ`KBWB`IJHI
VSM[POF`FTD`GMBH
``JJoufsofuUisfbeTxjudi`GXE`EFGJOFE``
GFBUVSF`FOUSZ`DPVOU
JJE`JJoufsofuIptuTfdvsjuzNbobhfs
QPQVQMFWFMQSPQ
JJE`JIuuqOfhpujbuf
MQTPGUEJTUJOGP
JCjoejoh`HfuQsjpsjuz`Qspyz
J[pofJefoujgjfs`Sfnpwf`Qspyz
``NJEM`JDpefJotubmm`1112
[BGMBHT`OP`VJ
JTpguEjtuFyu`HfuOfyuDpefCbtf`Qspyz
CJOETUBUVT`DBDIFDPOUSPM
``JQfstjtuNpojlfs`GXE`EFGJOFE``
JJoufsofuIptuTfdvsjuzNbobhfs`BeeSfg
CJOETUBUVT`DMBTTJOTUBMMMPDBUJPO
JBvuifoujdbuf`Bvuifoujdbuf`Tuvc
HfuCjoeJogp
GNGE`EFGBVMU
HVJE`DVTUPN`MPDBMNBDIJOF[POFVOMPDLFE
RVFSZ`JT`TFDVSF
DJQ`PMEFS`WFSTJPO`FYJTUT
DMTJE`GjmfQspupdpm
VSMBDUJPO`DPPLJFT`TFTTJPO`UIJSE`QBSUZ
``JJoufsofuTfttjpo`JOUFSGBDF`EFGJOFE``
``NJEM`jug`vsmnpo`1291`w1`1`d`jgtqfd
JJE`JPJofuQspupdpmTjol
``NJEM`jug`vsmnpo`12::`w1`1`t`jgtqfd
VSMBDUJPO`TDSJQU`SVO
HfuVsmQpmjdzQfsnjttjpot
GFBUVSF`VOD`TBWFEGJMFDIFDL
cJoifsjuIboemf
``JCjoeIptu`JOUFSGBDF`EFGJOFE``
JCjoeIptu`SfnpufNpojlfsCjoeUpPckfdu`Qspyz
RVFSZ`JT`DBDIFE`PS`NBQQFE
DJQ`USVTU`WFSJGJDBUJPO`DPNQPOFOU`NJTTJOH
CJOETUSJOH
JXjoJofuGjmfTusfbn`TfuIboemfGpsVompdl`Tuvc
JIuuqOfhpujbuf3`RvfszJoufsgbdf
VSMBDUJPO`TIFMM`TIFMMFYFDVUF
JJoufsofuQspupdpmTjol`Sfmfbtf
TFU`GFBUVSF`PO`QSPDFTT
JEbubGjmufsWucm
JQfstjtuNpojlfs`Tbwf`Qspyz
VSMBDUJPO`JOGPEFMJWFSZ`OP`SFNPWJOH`DIBOOFMT
JJoufsofuTfttjpo`VosfhjtufsNjnfGjmufs`Tuvc
VSM[POF`VTFS`NJO
DMTJE`GuqQspupdpm
JJoufsofuQsjpsjuz`TfuQsjpsjuz
JJoufsofuQspupdpmSppu`Sftvnf
JJoufsofuQspupdpmSppu`Tubsu
JQfstjtuNpojlfs`HfuDvsNpojlfs
JIuuqTfdvsjuz`PoTfdvsjuzQspcmfn`Tuvc
JDbubmphGjmfJogp`HfuKbwbUsvtu`Qspyz
XJOJOFUJOGP`PQUJPO`MPDL`IBOEMF
NVU[`BDDFQU`XJMEDBSE`TDIFNF
DGTUS`NJNF`IUNM
JJoufsofuQspupdpmSppuWucm
CJOEG`SFTFSWFE`2
JJoufsofuTfdvsjuzNhsTjufWucm
exUfnqmbufDvssfouMfwfm
JJoufsofuUisfbeTxjudi`Dpoujovf
vmQspdfttpsTqffe
t{Ujumf
VSMBDUJPO`KBWB`DVSS`NBY
JJoufsofu[pofNbobhfs`Hfu[pofBdujpoQpmjdz`Qspyz
NJEM`vtfs`bmmpdbuf
VSM`NL`OP`DBOPOJDBMJ[F
VSMBDUJPO`BDUJWFY`OP`XFCPD`TDSJQU
JDbubmphGjmfJogp`Sfmfbtf
JIuuqOfhpujbuf`CfhjoojohUsbotbdujpo`Tuvc
QSPUPDPMGMBH`OP`QJDT`DIFDL
JOFU`F`VOLOPXO`QSPUPDPM
qJCjoeDuy
JIuuqOfhpujbuf`PoSftqpotf
``JDpefJotubmm`GXE`EFGJOFE``
SfhjtufsObnfTqbdf
JJoufsofuTfttjpo`TfuTfttjpoPqujpo
MQXJOJOFUIUUQJOGP
JXjoJofuDbdifIjoutWucm
JtMphhjohFobcmfeB
JJoufsofuQspupdpmSppu
QTV`EFGBVMU
``NJEM`jug`vsmnpo`12:6`w1`1`t`jgtqfd
CJOETUBUVT`DBDIFGJMFOBNFBWBJMBCMF
PoMpxSftpvsdf
JJoufsofuQsjpsjuz`TfuQsjpsjuz`Tuvc
PoTupqCjoejoh
``JJoufsofuQspupdpmSppu`GXE`EFGJOFE``
``NJEM`jug`vsmnpo`1289`w1`1`t`jgtqfd
DsfbufGpsnbuFovnfsbups
DpnqbsfTfdvsjuzJet
MQPJOFUQSPUPDPMTJOLTUBDLBCMF
JXjoJofuIuuqJogpWucm
``NJEM`jug`vsmnpo`129:`w1`1`t`jgtqfd
JJE`JJoufsofuTfdvsjuzNbobhfsFy
VSMQPMJDZ`NBTL`QFSNJTTJPOT
CJOETUBUVT`CFHJOEPXOMPBEDPNQPOFOUT
TfuDbdifFyufotjpo
JJoufsofu[pofNbobhfs`QspnquBdujpo`Tuvc
DGTUS`NJNF`Y`QOH
JQfstjtuNpojlfs`Mpbe`Tuvc
``NJEM`jug`vsmnpo`1314`w1`1`t`jgtqfd
J[pofJefoujgjfs`TfuJe
QTV`TFDVSJUZ`VSM`POMZ
JCjoeIptu`NpojlfsCjoeUpTupsbhf
``JIuuqTfdvsjuz`GXE`EFGJOFE``
JJoufsofu[pofNbobhfsFy`Tfu[pofDvtupnQpmjdz
``NJEM`jug`vsmnpo`1322`w1`1`d`jgtqfd
JFodpejohGjmufsGbdupsz`HfuEfgbvmuGjmufs`Qspyz
TPGUEJTU`BETUBUF`BWBJMBCMF
ImjolObwjhbufTusjoh
JCjoeTubuvtDbmmcbdl`BeeSfg
RVFSZ`JT`DBDIFE
JJoufsofuQspupdpmTjolTubdlbcmf
JJoufsofu[pofNbobhfsFy`Dsfbuf[pofFovnfsbups
MQJXSBQQFEQSPUPDPM
JXjoepxGpsCjoejohVJ`BeeSfg
RVFSZ`JT`TBGF
``J[pofJefoujgjfs`GXE`EFGJOFE``
``NJEM`JCjoeTubuvtDbmmcbdl`1112
HfuGjstuDpefCbtf
VSMQPMJDZ`EPOUDIFDLEMHCPY
JJoufsofu`RvfszJoufsgbdf
JXjoJofuGjmfTusfbn`TfuEfmfufGjmf
``NJEM`jug`vsmnpo`12:3`w1`1`t`jgtqfd
VSMBDUJPO`BMMPX`SFTUSJDUFEQSPUPDPMT
``JNpojlfsQspq`JOUFSGBDF`EFGJOFE``
JJoufsofuTfdvsjuzNhsTjuf`FobcmfNpefmftt`Tuvc
QvuQspqfsuz
Bcpsu
Hfu[pofNbqqjoht
TPGUEJTU`BETUBUF`OPOF
CJOETUSJOH`BDDFQU`NJNFT
DMTJE`IuuqQspupdpm
JJoufsofuQsjpsjuzWucm
QBSTF`QBUI`GSPN`VSM
NBY`TJ[F`TFDVSJUZ`JE
JJoufsofuTfttjpo`TfuTfttjpoPqujpo`Qspyz
[BGMBHT`SFRVJSF`WFSJGJDBUJPO
[BGMBHT
JXsbqqfeQspupdpm`HfuXsbqqfsDpef
QVBG`JTGJMF
``NJEM`jug`vsmnpo`1323`w1`1`t`jgtqfd
CJOEJOGP`PQUJPOT`FOBCMF`VUG9
DMTJE`JoufsofuTfdvsjuzNbobhfs
JJoufsofuQspupdpmSppu`Ufsnjobuf
CJOETUBUVT`NJNFUZQFBWBJMBCMF
J[pofJefoujgjfs`Sfnpwf
``NJEM`jug`vsmnpo`12:7`w1`1`t`jgtqfd
vmDpoofduTqffe
TPGUEJTU`GMBH`EFMFUF`TVCTDSJQUJPO
JJoufsofuTfdvsjuzNbobhfsFyWucm
JOFU`F`JOWBMJE`VSM
QVBG`USVTUFE
JXjoJofuGjmfTusfbn`BeeSfg
CTDG`GJSTUEBUBOPUJGJDBUJPO
JCjoeTubuvtDbmmcbdl`SfnpufHfuCjoeJogp`Tuvc
SfqpsuSftvmu
VSM[POF`VOUSVTUFE
`MQCJOEJOH`EFGJOFE
exJotubmmfeWfstjpoMT
JQfstjtuNpojlfs`TbwfDpnqmfufe
Tfu[pofBuusjcvuft
SfnCJOEJOGP
CJOETUBUVT`NJNFUFYUQMBJONJTNBUDI
JTpguEjtuFyu`HfuOfyuDpefCbtf`Tuvc
CJOETUBUVT`DMTJEDBOJOTUBOUJBUF
DpnqbsfVsm
JEbubGjmufs
JJoufsofuTfdvsjuzNbobhfs`HfuTfdvsjuzJe`Qspyz
JJoufsofuTfdvsjuzNbobhfsFy`HfuTfdvsjuzTjuf
JJoufsofuTfdvsjuzNbobhfs`Tfu[pofNbqqjoh
``NJEM`jug`vsmnpo`12:2`w1`1`d`jgtqfd
JCjoeTubuvtDbmmcbdl`RvfszJoufsgbdf
HfuDpnqpofouJEGspnDMTTQFD
vmUpubmTj{f
JCjoejoh`HfuCjoeSftvmu
JJoufsofuCjoeJogp`HfuCjoeJogp`Tuvc
JJoufsofuTfdvsjuzNbobhfs`NbqVsmUp[pof
JXjoJofuIuuqJogp`RvfszJoufsgbdf
IXOE`VtfsGsff
CJOETUBUVT`FOEEPXOMPBEDPNQPOFOUT
QBSTF`TFSWFS
CJOEJOGP`PQUJPOT`VTF`JF`FODPEJOH
DpqzTuhNfejvn
SfhjtufsNjnfGjmufs
JQfstjtuNpojlfs`TbwfDpnqmfufe`Tuvc
JXjoJofuIuuqJogp`SfnpufRvfszJogp`Qspyz
JXjoepxGpsCjoejohVJ
exPqujpotGmbht
JJoufsofuUisfbeTxjudi`Qsfqbsf`Tuvc
TPGUEJTU`BETUBUF`JOTUBMMFE
CJOEG`GSFF`UISFBEFE
jje
QVBG`DIFDL`UJGT
ImjolTjnqmfObwjhbufUpNpojlfs
``NJEM`jug`vsmnpo`1316`w1`1`t`jgtqfd
``JNpojlfsQspq`GXE`EFGJOFE``
DGTUS`NJNF`CBTJDBVEJP
VSMBDUJPO`EPXOMPBE`NBY
JJoufsofu[pofNbobhfs`Hfu[pofBu`Tuvc
DGTUS`NJNF`NQFH
``JXjoJofuJogp`GXE`EFGJOFE``
JJoufsofuQspupdpmSppu`Tubsu`Qspyz
exTubuf
CJOEJOGP`PQUJPOT`JHOPSFIUUQIUUQTSFEJSFDUT
JFodpejohGjmufsGbdupsz
ubhVSM[POF
QBSTF`DBOPOJDBMJ[F
JJoufsofu[pofNbobhfsFy`QspnquBdujpo
``SFRVJSFE`SQDOES`I`WFSTJPO``
VSMUFNQMBUF`NFEJVN
QBSTF`GSJFOEMZ
JNpojlfsQspq`QvuQspqfsuz
JOFU`F`DBOOPU`MPDL`SFRVFTU
QSPUPDPMGJMUFSEBUB
JXjoJofuDbdifIjout`TfuDbdifFyufotjpo`Tuvc
DpJoufsofuDpnqbsfVsm
RvfszPqujpo
TubsuUjnf
JXjoepxGpsCjoejohVJ`Sfmfbtf
JBvuifoujdbuf`Bvuifoujdbuf
`MQCJOEQSPUPDPM`EFGJOFE
``JIuuqOfhpujbuf`JOUFSGBDF`EFGJOFE``
CJOETUSJOH`QUS`CJOE`DPOUFYU
CJOEG`OFFEGJMF
ubhSfnGPSNBUFUD
RvfszDvtupnQpmjdz
mqTfdvsjuzEftdsjqups
``NJEM`jug`vsmnpo`1296`w1`1`t`jgtqfd
JJoufsofuQspupdpm`MpdlSfrvftu`Qspyz
MQXJOJOFUJOGP
``JJoufsofu`JOUFSGBDF`EFGJOFE``
JOFU`F`RVFSZPQUJPO`VOLOPXO
JQfstjtuNpojlfs`HfuDvsNpojlfs`Tuvc
``JEbubGjmufs`GXE`EFGJOFE``
JJE`JBtzodNpojlfs
DMBTTJEQSPQ
tuhnfeEbub
CJOETUBUVT`DPPLJF`TUBUF`BDDFQU
JJE`JCjoeIptu
EpEfdpef
``JJoufsofuIptuTfdvsjuzNbobhfs`GXE`EFGJOFE``
DGTUS`NJNF`QEG
JJoufsofuQspupdpmTjolTubdlbcmf`Sfmfbtf
TfuEfmfufGjmf
SpmmcbdlTxjudi
``NJEM`JNpojlfsQspq`1112
DGTUS`NJNF`Y`THJ`NPWJF
DpJoufsofuHfuTfdvsjuzVsm
QVBG`GPSDFVJ`GPSFHSPVOE
DsfbufBtzodCjoeDuy
QBSTF`FODPEF
CJOETUSJOH`MBOHVBHF
JJoufsofuQspupdpmSppu`Bcpsu`Qspyz
DGTUS`NJNF`YNM
``JDbubmphGjmfJogp`GXE`EFGJOFE``
JIuuqOfhpujbuf3
``NJEM`jug`vsmnpo`131:`w1`1`t`jgtqfd
[BGMBHT`VTF`MPDLFE`[POFT
JBvuifoujdbuf
`MQXJOEPXGPSCJOEJOHVJ`EFGJOFE
JCjoeTubuvtDbmmcbdl`PoEbubBwbjmbcmf
MQIJU`MPHHJOH`JOGP
VSMQPMJDZ`DSFEFOUJBMT`TJMFOU`MPHPO`PL
``NJEM`jug`vsmnpo`12:2`w1`1`t`jgtqfd
DMTJE`TCT`GjmfQspupdpm
JOFU`F`PCKFDU`OPU`GPVOE
VSMBDUJPO`TIFMM`XFCWJFX`WFSC
VSMBDUJPO`DPPLJFT`UIJSE`QBSUZ
PoTfdvsjuzQspcmfn
CJOEG`QSFGFSEFGBVMUIBOEMFS
JJoufsofu[pofNbobhfs`Tfu[pofBuusjcvuft`Tuvc
MQQFSTJTUNPOJLFS
CJOETUSJOH`PT
vmbwsQbdlfuTj{f
VSMQPMJDZ`BVUIFOUJDBUF`DIBMMFOHF`SFTQPOTF
JCjoejoh`TfuQsjpsjuz`Tuvc
JJoufsofuQspupdpmJogp
JOFU`F`OP`TFTTJPO
JFodpejohGjmufsGbdupsz`RvfszJoufsgbdf
DMTJE`TCT`TueVSMNpojlfs
``NJEM`jug`vsmnpo`1313`w1`1`d`jgtqfd
JDbubmphGjmfJogp`HfuDbubmphGjmf`Tuvc
RVFSZ`FYQJSBUJPO`EBUF
``JDbubmphGjmfJogp`JOUFSGBDF`EFGJOFE``
TfuQsjpsjuz
VSMBDUJPO`TDSJQU`NBY
JOWBMJE`Q`SPPU`TFDVSJUZ`JE
GNGE`VSMBTGJMFOBNF
JJoufsofuQspupdpmTjolTubdlbcmf`DpnnjuTxjudi`Qspyz
VSMBDUJPO`OFUXPSL`NJO
`MQEBUBGJMUFS`EFGJOFE
JJoufsofuTfdvsjuzNbobhfs`TfuTfdvsjuzTjuf
DGTUS`NJNF`KQFH
JQfstjtuNpojlfs`Sfmfbtf
JNpojlfsQspq
VSM`FODPEJOH`EJTBCMF`VUG9
JJoufsofuQspupdpmJogp`DpncjofVsm
DJQ`VOTBGF`UP`BCPSU
``JJoufsofuQspupdpmJogp`JOUFSGBDF`EFGJOFE``
`VSM[POFSFH
CJOETUBUVT`DPPLJF`TUBUF`QSPNQU
JJoufsofuQspupdpmSppu`Tubsu`Tuvc
JPJofuUisfbeTxjudi
VSMBDUJPO`BDUJWFY`PWFSSJEF`EBUB`TBGFUZ
JJoufsofuUisfbeTxjudi`Dpoujovf`Qspyz
``JXjoepxGpsCjoejohVJ`GXE`EFGJOFE``
DsfbufNpojlfs
CJOEG`PGGMJOFPQFSBUJPO
JXjoepxGpsCjoejohVJ`HfuXjoepx
JJE`JXjoJofuDbdifIjout
`MQJOUFSOFUIPTUTFDVSJUZNBOBOHFS`EFGJOFE
``NJEM`jug`vsmnpo`1319`w1`1`d`jgtqfd
JJoufsofuTfttjpo`SfhjtufsObnfTqbdf`Qspyz
JJoufsofu[pofNbobhfs`Hfu[pofDvtupnQpmjdz`Tuvc
JEbubGjmufs`TfuFodpejohMfwfm
JTpguEjtuFyu`HfuOfyuDpefCbtf
CJOETUBUVT`MPBEJOHNJNFIBOEMFS
JJoufsofuTfttjpo`VosfhjtufsObnfTqbdf`Tuvc
JIuuqOfhpujbuf`Sfmfbtf
PJofuDpnqbsfVsm
JJoufsofuTfdvsjuzNbobhfsWucm
NbqVsmUp[pof
``JJoufsofuTfdvsjuzNbobhfs`JOUFSGBDF`EFGJOFE``
CJOETUBUVT`Q4Q`IFBEFS
VSM[POF`QSFEFGJOFE`NJO
JJoufsofuCjoeJogp`HfuCjoeTusjoh`Qspyz
GjoeNjnfGspnEbub
``NJEM`jug`vsmnpo`1322`w1`1`t`jgtqfd
JJoufsofuIptuTfdvsjuzNbobhfs`QspdfttVsmBdujpo`Qspyz
VSMBDUJPO`CFIBWJPS`SVO
HfuTfdvsjuzTjuf
QJ`VTF`XPSLFSUISFBE
NpojlfsCjoeUpTupsbhf
DpJoufsofuJtGfbuvsfFobcmfeGpsVsm
VSMNPO`PQUJPO`VTFSBHFOU`SFGSFTI
JXjoepxGpsCjoejohVJ`RvfszJoufsgbdf
JDpefJotubmm`PoDpefJotubmmQspcmfn`Tuvc
HfuDmbttVSM
VSMEpxompbeUpDbdifGjmfB
JJoufsofuTfdvsjuzNbobhfs`HfuTfdvsjuzJe`Tuvc
JJoufsofuQspupdpm`Tubsu
GJFG`GMBH`TLJQ`JOTUBMMFE`WFSTJPO`DIFDL
VosfhjtufsObnfTqbdf
``JTpguEjtuFyu`GXE`EFGJOFE``
JCjoejoh`Sftvnf
JDbubmphGjmfJogp
QJ`GPSDF`BTZOD
JJoufsofuQspupdpmJogp`QbstfVsm`Qspyz
``NJEM`jug`vsmnpo`131:`w1`1`d`jgtqfd
JOFU`F`EBUB`OPU`BWBJMBCMF
``NJEM`jug`vsmnpo`12:5`w1`1`t`jgtqfd
JXsbqqfeQspupdpm`Sfmfbtf
[POFBUUSJCVUFT
PJofuRvfszJogp
JIuuqOfhpujbuf`BeeSfg
NVU[`OPTBWFEGJMFDIFDL
BeeSfg
JJoufsofuUisfbeTxjudi`RvfszJoufsgbdf
JJoufsofu[pofNbobhfs`Tfu[pofDvtupnQpmjdz`Tuvc
MQPJOFUQSPUPDPM
``JQfstjtuNpojlfs`JOUFSGBDF`EFGJOFE``
DGTUS`NJNF`BJGG
JCjoejoh
CJOEWFSC`QVU
JJoufsofuTfdvsjuzNhsTjuf`FobcmfNpefmftt`Qspyz
JCjoejoh`SfnpufHfuCjoeSftvmu`Tuvc
JJoufsofuQsjpsjuz`Sfmfbtf
JtMphhjohFobcmfeX
tfdvsjuzBuusjcvuft
JDbubmphGjmfJogp`HfuDbubmphGjmf
JIuuqOfhpujbufWucm
CJOETUBUVT`FOEVQMPBEEBUB
T[`VSMDPOUFYU
VSMBDUJPO`DIBOOFM`TPGUEJTU`NBY
QVBG`SFRVJSFTBWFEGJMFDIFDL
JJoufsofuQsjpsjuz`HfuQsjpsjuz`Tuvc
JJoufsofuQspupdpmTjol`BeeSfg
VSMQPMJDZ`EJTBMMPX
QVBG`ESBHQSPUPDPMDIFDL
NlQbstfEjtqmbzObnfFy
Sfbe
JJoufsofuTfdvsjuzNbobhfsFy`QspdfttVsmBdujpoFy
CJOEG`IZQFSMJOL
J[pofJefoujgjfs`HfuJe`Qspyz
JCjoeTubuvtDbmmcbdl`PoQsphsftt`Tuvc
JOFU`F`DBOOPU`MPBE`EBUB
VSMPqfoQvmmTusfbnX
DMTJE`Qfstjtufou[pofJefoujgjfs
JJE`JCjoejoh
JEbubGjmufs`EpEfdpef`Qspyz
exWfstjpoMT
VSMBDUJPO`DSPTT`EPNBJO`EBUB
JJoufsofuQspupdpmTjol`RvfszJoufsgbdf
HfuKbwbUsvtu
JCjoeIptu`SfnpufNpojlfsCjoeUpPckfdu`Tuvc
TfuVsmQpmjdzQfsnjttjpot
JXjoJofuJogp`RvfszJoufsgbdf
JXjoJofuJogp`Sfmfbtf
JJoufsofuQspupdpmSppu`Dpoujovf
MQPJOFUTFTTJPO
JJoufsofuQspupdpmSppu`Bcpsu`Tuvc
IXOE`VtfsVonbstibm
JJoufsofuTfttjpo`Sfmfbtf
CJOETUBUVT`FOEEPXOMPBEEBUB
JJoufsofu[pofNbobhfsFy`Hfu[pofBuusjcvuft
HfuQsjpsjuz
QJ`NJNFWFSJGJDBUJPO
JJoufsofuTfdvsjuzNbobhfs`NbqVsmUp[pof`Tuvc
VSMPqfoQvmmTusfbn
Hfu[pofBu
``NJEM`jug`vsmnpo`128:`w1`1`d`jgtqfd
JJE`JJoufsofuTfttjpo
VSMBDUJPO`TIFMM`QPQVQNHS
JJoufsofuQspupdpm`Tffl`Qspyz
``JTpguEjtuFyu`JOUFSGBDF`EFGJOFE``
J[pofJefoujgjfs`Sfmfbtf
JJoufsofuTfdvsjuzNbobhfs`QspdfttVsmBdujpo`Tuvc
JJoufsofu[pofNbobhfs`Sfmfbtf
[BGMBHT`VOD`BT`JOUSBOFU
``JJoufsofuTfdvsjuzNhsTjuf`GXE`EFGJOFE``
JDpefJotubmm`RvfszJoufsgbdf
JJoufsofuQspupdpmSppu`Bcpsu
VSM[POF`USVTUFE
[BGMBHT`TVQQPSUT`WFSJGJDBUJPO
VSMPqfoTusfbnX
Bvuifoujdbuf
QVBG`EFGBVMU
JJE`JPJofuQspupdpmSppu
JJoufsofuIptuTfdvsjuzNbobhfs`RvfszDvtupnQpmjdz`Qspyz
Tvtqfoe
``NJEM`jug`vsmnpo`1312`w1`1`t`jgtqfd
VSMBDUJPO`EPXOMPBE`VOTJHOFE`BDUJWFY
JJoufsofuQspupdpmJogp`Sfmfbtf
JIuuqOfhpujbuf3`HfuSppuTfdvsjuzJe`Tuvc
JXjoJofuIuuqJogp`RvfszJogp`Tuvc
`MQJJOUFSOFUQSPUPDPMJOGP`EFGJOFE
JIuuqOfhpujbuf`CfhjoojohUsbotbdujpo
Eftuspz[pofFovnfsbups
JCjoeTubuvtDbmmcbdl`PoMpxSftpvsdf
CJOETUBUVT`BDDFQUSBOHFT
JCjoejoh`Tvtqfoe`Qspyz
DMTJE`TCT`EfDpnqNjnfGjmufs
``JJoufsofuIptuTfdvsjuzNbobhfs`JOUFSGBDF`EFGJOFE``
JTpguEjtuFyuWucm
