#Encrypted file follows
XBC`SFTPMWF`OP`POF`PGGT
XBC`SFTPMWF`GJSTU`NBUDI
XBC`SFTPMWF`MPDBM`POMZ
XBC`SFTPMWF`OP`OPU`GPVOE`VJ
EFDMBSF`NBQJ`JOUFSGBDF`
XBCJBC`I
XBC`SFTPMWF`VOJDPEF
XBC`SFTPMWF`OFFE`DFSU
NBQJ`JBEESCPPL`NFUIPET
XBC`SFTPMWF`BMM`FNBJMT
XBC`SFTPMWF`VTF`DVSSFOU`QSPGJMF
JOUFSGBDF
