#Encrypted file follows
TfuDpotpmfUfyuBuusjcvuf
cWjtjcmf
`JOQVU`SFDPSE
DPNNPO`MWC`HSJE`MWFSUJDBM
QIBOEMFS`SPVUJOF
HfuDpotpmfQspdfttMjtu
QXJOEPX`CVGGFS`TJ[F`SFDPSE
QNPVTF`FWFOU`SFDPSE
NFOV`FWFOU
DPOTPMF`OP`TFMFDUJPO
HfuMbshftuDpotpmfXjoepxTj{f
QfflDpotpmfJoqvu
HfofsbufDpotpmfDusmFwfou
Dibs
GSPN`MFGU`5UI`CVUUPO`QSFTTFE
GPSFHSPVOE`HSFFO
QDPOTPMF`TFMFDUJPO`JOGP
XsjufDpotpmfPvuqvuX
MFGU`DUSM`QSFTTFE
`LFZ`FWFOU`SFDPSE
TfuDpotpmfNpef
exNpvtfQptjujpo
QDPOTPMF`TDSFFO`CVGGFS`JOGP
xWjsuvbmTdboDpef
NpvtfFwfou
HfuDpotpmfBmjbtB
NPVTF`FWFOU
HfuDpotpmfBmjbtFyftMfohuiX
TfuDpotpmfUjumfB
TdspmmDpotpmfTdsffoCvggfsB
QJOQVU`SFDPSE
HfuDpotpmfBmjbtftX
Z
OMT`BMQIBOVNFSJD
CBDLHSPVOE`HSFFO
xSfqfbuDpvou
XsjufDpotpmfPvuqvuBuusjcvuf
DPPSE
`XJODPO`
QfflDpotpmfJoqvuB
QNFOV`FWFOU`SFDPSE
GsffDpotpmf
QDPOTPMF`GPOU`JOGP
HfuDvssfouDpotpmfGpou
GPDVT`FWFOU`SFDPSE
GSPN`MFGU`2TU`CVUUPO`QSFTTFE
GPSFHSPVOE`CMVF
DPNNPO`MWC`SFWFSTF`WJEFP
DPOTPMF`NPVTF`EPXO
FOBCMF`QSPDFTTFE`PVUQVU
GjmmDpotpmfPvuqvuDibsbdufsB
HfuDpotpmfDQ
NPVTF`XIFFMFE
FOIBODFE`LFZ
`TNBMM`SFDU
cLfzEpxo
QfflDpotpmfJoqvuX
NPVTF`FWFOU`SFDPSE
DUSM`CSFBL`FWFOU
QGPDVT`FWFOU`SFDPSE
DPNNPO`MWC`MFBEJOH`CZUF
BUUBDI`QBSFOU`QSPDFTT
FOBCMF`MJOF`JOQVU
BmmpdDpotpmf
`DIBS`JOGP
HfuDpotpmfBmjbtFyftMfohui
XsjufDpotpmfPvuqvuDibsbdufsX
BuubdiDpotpmf
HfuDpotpmfBmjbtft
MFGU`BMU`QSFTTFE
Sjhiu
exTj{f
HfuDpotpmfPvuqvuDQ
oGpou
TfuDpotpmfUjumfX
SfbeDpotpmfJoqvuX
OMT`JNF`EJTBCMF
DPOTPMF`NPVTF`TFMFDUJPO
HfuDpotpmfBmjbtFyft
Fwfou
TfuDpotpmfDvstpsQptjujpo
QTNBMM`SFDU
exDvstpsQptjujpo
HfuDpotpmfBmjbtftMfohui
exCvuupoTubuf
FOBCMF`QSPDFTTFE`JOQVU
DUSM`MPHPGG`FWFOU
SJHIUNPTU`CVUUPO`QSFTTFE
XsjufDpotpmfJoqvuB
Y
TNBMM`SFDU
exGpouTj{f
DPOTPMF`GVMMTDSFFO
OMT`SPNBO
DPOTPMF`TFMFDUJPO`JO`QSPHSFTT
exDpouspmLfzTubuf
OMT`IJSBHBOB
DPNNPO`MWC`TCDTECDT
exFwfouGmbht
FOBCMF`FDIP`JOQVU
SfbeDpotpmfPvuqvuDibsbdufsX
EPVCMF`DMJDL
CBDLHSPVOE`CMVF
HfuOvncfsPgDpotpmfNpvtfCvuupot
GjmmDpotpmfPvuqvuDibsbdufs
SfbeDpotpmfPvuqvuDibsbdufs
NfovFwfou
TfuDpotpmfDusmIboemfs
DUSM`DMPTF`FWFOU
XsjufDpotpmfPvuqvu
HfuDpotpmfDvstpsJogp
exDpnnboeJe
SJHIU`DUSM`QSFTTFE
TIJGU`QSFTTFE
HfuDpotpmfXjoepx
TfuDpotpmfTdsffoCvggfsTj{f
`GPDVT`FWFOU`SFDPSE
DPOTPMF`GVMMTDSFFO`IBSEXBSF
DsfbufDpotpmfTdsffoCvggfs
cTfuGpdvt
DPNNPO`MWC`HSJE`IPSJ[POUBM
SfbeDpotpmfJoqvu
XJOEPX`CVGGFS`TJ[F`FWFOU
Buusjcvuft
OMT`JNF`DPOWFSTJPO
xWjsuvbmLfzDpef
TfuDpotpmfPvuqvuDQ
QDIBS`JOGP
SfbeDpotpmfX
exNbyjnvnXjoepxTj{f
exGmbht
SfbeDpotpmfPvuqvuDibsbdufsB
TdspmmDpotpmfTdsffoCvggfs
TdspmmDpotpmfTdsffoCvggfsX
`DPOTPMF`TDSFFO`CVGGFS`JOGP
DPNNPO`MWC`VOEFSTDPSF
LfzFwfou
GPDVT`FWFOU
DUSM`D`FWFOU
HfuDpotpmfBmjbtFyftMfohuiB
GPSFHSPVOE`JOUFOTJUZ
HfuDpotpmfUjumfX
SfbeDpotpmf
Mfgu
`XJOEPX`CVGGFS`TJ[F`SFDPSE
`DPOTPMF`DVSTPS`JOGP
BtdjjDibs
exTfmfdujpoBodips
`NPVTF`FWFOU`SFDPSE
Cpuupn
BeeDpotpmfBmjbt
HfuDpotpmfGpouTj{f
XsjufDpotpmfPvuqvuDibsbdufs
SfbeDpotpmfB
SfbeDpotpmfPvuqvu
`DPOTPMF`GPOU`JOGP
`DPPSE
HfuDpotpmfBmjbtFyftX
HfuDpotpmfTfmfdujpoJogp
FOBCMF`XSBQ`BU`FPM`PVUQVU
SfbeDpotpmfPvuqvuX
HfuDpotpmfBmjbt
QLFZ`FWFOU`SFDPSE
LFZ`FWFOU`SFDPSE
BeeDpotpmfBmjbtX
GpdvtFwfou
DPOTPMF`DVSTPS`JOGP
HfuDpotpmfBmjbtftMfohuiX
SfbeDpotpmfPvuqvuBuusjcvuf
GmvtiDpotpmfJoqvuCvggfs
NPVTF`NPWFE
`NFOV`FWFOU`SFDPSE
QDPPSE
XsjufDpotpmfPvuqvuDibsbdufsB
XsjufDpotpmfX
XJOEPX`CVGGFS`TJ[F`SFDPSE
tsTfmfdujpo
CBDLHSPVOE`JOUFOTJUZ
OMT`LBUBLBOB
GPSFHSPVOE`SFE
XjoepxCvggfsTj{fFwfou
DUSM`TIVUEPXO`FWFOU
JOQVU`SFDPSE
BeeDpotpmfBmjbtB
FwfouUzqf
`DPOTPMF`TFMFDUJPO`JOGP
GjmmDpotpmfPvuqvuBuusjcvuf
DBQTMPDL`PO
SJHIU`BMU`QSFTTFE
HfuOvncfsPgDpotpmfJoqvuFwfout
HfuDpotpmfBmjbtftMfohuiB
XsjufDpotpmfJoqvuX
GSPN`MFGU`4SE`CVUUPO`QSFTTFE
TfuDpotpmfDQ
TfuDpotpmfUjumf
OVNMPDL`PO
GjmmDpotpmfPvuqvuDibsbdufsX
DIBS`JOGP
TfuDpotpmfBdujwfTdsffoCvggfs
OMT`ECDTDIBS
HfuDpotpmfTdsffoCvggfsJogp
HfuDpotpmfUjumfB
TDSPMMMPDL`PO
NFOV`FWFOU`SFDPSE
TfuDpotpmfDvstpsJogp
DPOTPMF`GPOU`JOGP
XsjufDpotpmf
XsjufDpotpmfJoqvu
HfuDpotpmfBmjbtX
Upq
CBDLHSPVOE`SFE
tsXjoepx
LFZ`FWFOU
SfbeDpotpmfPvuqvuB
VojdpefDibs
HfuDpotpmfBmjbtFyftB
DPNNPO`MWC`HSJE`SWFSUJDBM
HfuDpotpmfBmjbtftB
HfuDpotpmfEjtqmbzNpef
QDPOTPMF`DVSTPS`JOGP
XsjufDpotpmfPvuqvuB
FOBCMF`NPVTF`JOQVU
GSPN`MFGU`3OE`CVUUPO`QSFTTFE
DPOTPMF`UFYUNPEF`CVGGFS
TfuDpotpmfXjoepxJogp
SfbeDpotpmfJoqvuB
FOBCMF`XJOEPX`JOQVU
DPNNPO`MWC`USBJMJOH`CZUF
HfuDpotpmfUjumf
DPOTPMF`TDSFFO`CVGGFS`JOGP
vDibs
XsjufDpotpmfB
HfuDpotpmfNpef
xBuusjcvuft
DPOTPMF`TFMFDUJPO`JOGP
DPOTPMF`TFMFDUJPO`OPU`FNQUZ
