#Encrypted file follows
n`ecmWbm
JXcfnRvfsz`GsffNfnpsz`Qspyz
XNJR`MG47`SFGFSFODF`UFTUT
JXcfnQbuiLfzMjtu`HfuJogp`Qspyz
n`vXifsfDmbvtfTj{f
JXcfnQbui`JtMpdbm
JXcfnQbuiLfzMjtu`TfuLfz`Tuvc
n`qt{MfguGvod
JXcfnQbuiLfzMjtu`SfnpwfBmmLfzt`Qspyz
JXcfnQbuiLfzMjtu`HfuUfyu`Qspyz
ubh`XCFN`QBUI`TUBUVT`GMBH
JXcfnQbuiLfzMjtu`HfuLfz`Qspyz
XNJR`BOBMZTJT`SFTFSWFE
XNJR`SQO`GSPN`VOBSZ
JXcfnQbui`DsfbufDmbttQbsu
JXcfnQbuiLfzMjtu`SfnpwfBmmLfzt`Tuvc
SfnpwfBmmTdpqft
n`qt{TusWbm
XNJR`MG22`BMJBTJOH
Sfmfbtf
n`qMfguJefou
XCFNQBUI`JOGP`JT`DPNQPVOE
JXcfnQbui`SfnpwfObnftqbdfBu`Tuvc
XNJR`SQO`PQ`JTOPUOVMM
XNJR`BTTPDR`SFTVMUSPMF
n`vWfstjpo
``NJEM```NJEM`jug`xnjvujmt`1227`1113
JXcfnQbui`HfuTdpqfBtUfyu`Qspyz
JXcfnQbuiLfzMjtu`TfuLfz3`Tuvc
JXcfnQbuiLfzMjtu`HfuLfz
XNJR`MG21`DPNQFY`TVCFYQSFTTJPOT
TfuLfz
n`vTvcfyqsfttjpoTibqf
XNJR`MG45`VOJPO
``JXcfnQbui`JOUFSGBDF`EFGJOFE``
JXcfnRvfsz`HfuRvfszJogp`Tuvc
XNJR`SQO`HFU`SJHIU`GVODUJPO
XNJR`MG36`EBUFQBSU
XNJR`SQO`OFYU`UPLFO
JXcfnQbuiLfzMjtu`HfuLfz3
ubh`XNJR`MBOHVBHF`GFBUVSFT
XNJR`MG26`HP
n`qt{PqujpobmGspnQbui
JXcfnQbui`SfnpwfBmmTdpqft
JXcfnQbui`JtTbnfDmbttObnf`Qspyz
TXcfnSqoRvfszUplfo
XCFNQBUI`JOGP`IBT`NBDIJOF`OBNF
n`qNbusjdft
HfuLfz
JXcfnQbui`JtSfmbujwfPsDijme`Tuvc
XNJR`MG2:`TZTUFN`QSPQFSUJFT
XCFNQBUI`JOGP`JT`TJOHMFUPO
JXcfnQbui`HfuTdpqfDpvou`Qspyz
JXcfnRvfsz`Fnquz`Tuvc
XNJR`MG48`TFMFDU`JOUP
XNJR`BOBMZTJT`BTTPD`RVFSZ
JXcfnQbui`TfuObnftqbdfBu`Tuvc
ubh`XCFN`HFU`UFYU`GMBHT
XNJR`SQO`PQ`MF
n`qSjhiuJefou
JXcfnQbui`TfuTdpqfGspnUfyu
HfuBobmztjt
SfnpwfObnftqbdfBu
JXcfnRvfsz`GsffNfnpsz
JXcfnQbui`TfuObnftqbdfBu`Qspyz
JXcfnQbui`TfuTfswfs`Qspyz
JXcfnQbui`TfuUfyu`Tuvc
JXcfnRvfsz`UftuMbohvbhfGfbuvsft
XNJR`SQO`HFU`FYQS`TIBQF
JXcfnQbui`HfuObnftqbdfBu`Qspyz
JXcfnQbui`HfuObnftqbdfDpvou
XCFNQBUI`DPNQSFTTFE
XNJR`SQOG`HSPVQ`CZ`IBWJOH
n`qQbui
``XcfnVujmjujft`w2`MJCSBSZ`EFGJOFE``
XNJR`SQO`MFGU`GVODUJPO
ubh`XCFN`QBUI`DSFBUF`GMBH
JXcfnQbui`HfuObnftqbdfDpvou`Tuvc
n`vGfbuvsfNbtl
JXcfnRvfsz`Qbstf`Qspyz
XCFNQBUI`JOGP`TFSWFS`OBNFTQBDF`POMZ
XNJR`SQOG`QSPKFDUJPO
JXcfnQbui`SfnpwfBmmObnftqbdft`Tuvc
XNJR`MG44`BSSBZ`BDDFTT
JXcfnQbuiLfzMjtu`HfuLfz3`Qspyz
XNJR`MG:`UIJT
NJEM`vtfs`bmmpdbuf
DsfbufDmbttQbsu
XNJR`BOBMZTJT`SQO`TFRVFODF
XNJR`MG24`XNJ`XJUIJO
JXcfnQbui`HfuLfzMjtu`Tuvc
``JXcfnRvfsz`GXE`EFGJOFE``
``xnjvujmt`i``
JJE`JXcfnQbui
JXcfnQbui`JtMpdbm`Qspyz
JXcfnQbuiLfzMjtu`HfuUfyu
ubh`TXcfnBobmztjtNbusjyMjtu
Fnquz
JXcfnQbuiLfzMjtu`SfnpwfLfz`Tuvc
n`vQbstfeGfbuvsfNbtl
XNJR`BTTPDR`GMBHT
``SFRVJSFE`SQDOES`I`WFSTJPO``
n`vDpotu3BqqbsfouUzqf
JXcfnQbui`TfuUfyu
JXcfnQbui`SfnpwfBmmObnftqbdft
TfuObnftqbdfBu
JXcfnQbuiLfzMjtu`SfnpwfLfz`Qspyz
XNJR`SQOG`DPVOU`TUBS
XNJR`SQO`HFU`UPLFO`UZQF
JXcfnQbuiLfzMjtu`TfuLfz`Qspyz
BeeSfg
SfnpwfTdpqf
XNJR`MG3:`NVMUJ`MFWFM`PSEFS`CZ
XNJR`BOBMZTJT`RVFSZ`UFYU
XNJR`SQO`UPLFO`OPU
JXcfnQbui`HfuObnftqbdfBu`Tuvc
``JXcfnQbui`GXE`EFGJOFE``
JXcfnQbuiLfzMjtu`NblfTjohmfupo`Tuvc
n`vUplfoUzqf
SfnpwfBmmObnftqbdft
n`qqTfmfduMjtu
ubh`XCFN`HFU`LFZ`GMBHT
JXcfnQbuiLfzMjtu`NblfTjohmfupo`Qspyz
JXcfnQbui`HfuTfswfs
JXcfnQbui`SfnpwfTdpqf`Tuvc
n`vBobmztjtUzqf
HfuObnftqbdfBu
XNJR`MBOHVBHF`GFBUVSFT
JXcfnRvfsz`HfuRvfszJogp
XNJR`MG31`FYUFOEFE`TZTUFN`QSPQFSUJFT
HfuLfz3
XCFNQBUI`JOGP`IBT`W3`SFG`QBUIT
MJCJE`XcfnVujmjujft`w2
XNJR`SQOG`RVBMJGJFE`OBNFT`VTFE
``NJEM`jug`xnjvujmt`1111`w1`1`d`jgtqfd
XNJR`SQOG`FRVBMJUZ`UFTUT`POMZ
XCFNQBUI`HFU`TFSWFS`UPP
XCFNQBUI`HFU`PSJHJOBM
XCFNQBUI`JOGP`JT`DMBTT`SFG
XNJR`MG7`PSEFS`CZ
``NJEM`jug`xnjvujmt`1227`w1`1`d`jgtqfd
JXcfnQbui`SfnpwfBmmObnftqbdft`Qspyz
JXcfnQbuiLfzMjtu`HfuUfyu`Tuvc
JXcfnQbui`HfuTdpqfDpvou
XNJR`BOBMZTJT`QSPQ`BOBMZTJT`NBUSJY
HfuLfzMjtu
JXcfnQbui`HfuUfyu`Qspyz
XNJR`BTTPDR`SFRVJSFERVBMJGJFS
XNJR`SQOG`PSEFS`CZ
n`qvEfufdufeGfbuvsft
n`mMpohWbm
HfuTdpqfDpvou
n`vEfufdufeBssbzTj{f
JXcfnQbui`JtSfmbujwf`Tuvc
``NJEM```NJEM`jug`xnjvujmt`1227`1112
XNJR`BTTPDR`TDIFNBPOMZ
XCFNQBUI`JOGP`OBUJWF`QBUI
NJEM`vtfs`gsff
JXcfnQbui`HfuTfswfs`Qspyz
JXcfnQbui`JtSfmbujwfPsDijme`Qspyz
JtSfmbujwf
n`vGspnMjtuTj{f
JXcfnQbui`JtSfmbujwf`Qspyz
HfuTdpqfBtUfyu
JJE`JXcfnRvfsz
XNJR`SQO`SJHIU`GVODUJPO
XNJR`MG`MBTU
JXcfnQbui`JtSfmbujwfPsDijme
JXcfnQbui`HfuTfswfs`Tuvc
HfuDpvou
XNJR`SQOG`RVFSZ`JT`EJTKVODUJWF
XNJR`SQO`UPLFO`FYQSFTTJPO
n`qWbmvft
TXcfnRvfszRvbmjgjfeObnf
XNJR`MG9`JTB
JXcfnQbui`HfuTdpqfBtUfyu
n`vPsefsCzMjtuTj{f
``NJEM`jug`xnjvujmt`1227`w1`1`t`jgtqfd
XNJR`MG39`TUBOEBSE`BHHSFHBUFT
JXcfnQbuiLfzMjtu`BeeSfg
XNJR`BOBMZTJT`UZQF
JXcfnQbui`HfuObnftqbdfBu
JXcfnQbui`HfuTdpqf
XNJR`SQOG`QSPQ`UP`QSPQ`UFTUT
TfuTdpqf
ubh`TXcfnSqoDpotu
XNJR`MG42`RVBMJGJFS`UFTUT
JXcfnQbui`SfnpwfObnftqbdfBu
XNJR`MG6`DPVOU`TUBS
JXcfnQbui`TfuDmbttObnf`Tuvc
XNJR`SQO`SJHIU`QSPQFSUZ`OBNF
UftuMbohvbhfGfbuvsft
XNJR`SQO`HFU`SFMPQ
JXcfnRvfsz`RvfszJoufsgbdf
JXcfnRvfsz`TfuMbohvbhfGfbuvsft
JXcfnQbui`HfuLfzMjtu`Qspyz
ubh`TXcfnSqoRvfszUplfo
JXcfnQbuiLfzMjtu`NblfTjohmfupo
TfuTfswfs
JXcfnRvfsz`Qbstf
XNJR`SQO`HFU`MFGU`GVODUJPO
XNJR`BTTPDR`BTTPDJBUPST
RvfszJoufsgbdf
XNJR`SQOG`RVFSZ`JT`DPOKVODUJWF
JXcfnQbui`TfuTfswfs
SfnpwfLfz
JXcfnRvfsz`HfuBobmztjt`Tuvc
XNJR`SQO`PQ`JTB
n`Dpotu3
JXcfnRvfsz`BeeSfg
XNJR`SQO`GSPN`NVMUJQMF
XNJR`SQOG`GFBUVSF`TFMFDU`TUBS
XCFNQBUI`DSFBUF`BDDFQU`SFMBUJWF
XNJR`SQO`PQ`VOEFGJOFE
XCFNQBUI`JOGP`W2`DPNQMJBOU
TfuDmbttObnf
XCFNQBUI`DSFBUF`BDDFQU`BMM
JXcfnQbuiLfzMjtu`SfnpwfLfz
Qbstf
XNJR`MG8`EJTUJODU
XNJR`SQO`DPOTU
XNJR`SQO`PQ`HU
XNJR`MG51`CFUXFFO
JXcfnQbuiLfzMjtu`HfuDpvou
JXcfnQbuiWucm
JXcfnQbui`HfuLfzMjtu
JXcfnRvfsz
n`ecmXjuijoXjoepx
n`qqt{GspnMjtu
JXcfnQbui`TfuTdpqf
n`qt{SfrvjsfeBttpdRvbmjgjfs
JXcfnQbuiLfzMjtu`TfuLfz
JXcfnQbui`JtMpdbm`Tuvc
JXcfnQbui`TfuTdpqfGspnUfyu`Tuvc
JXcfnQbui`SfnpwfObnftqbdfBu`Qspyz
n`vOvnNbusjdft
JXcfnRvfsz`Fnquz
JXcfnQbui`EfmfufDmbttQbsu`Tuvc
XNJR`MG35`VNJ`FYUFOTJPOT
n`qvBssbzJoefy
JXcfnQbui`Sfmfbtf
n`cBssbztVtfe
XNJR`BTTPDR`LFZTPOMZ
XNJR`MG25`TRM`XSJUF`PQFSBUJPOT
XNJR`SQO`PQ`MJLF
XNJR`MG33`TRM:3`KPJOT
JXcfnQbui`HfuTdpqf`Tuvc
XNJR`SQO`PQ`JTOPUB
JXcfnQbui`DsfbufDmbttQbsu`Tuvc
JXcfnQbuiLfzMjtu`SfnpwfBmmLfzt
HfuRvfszJogp
JXcfnQbui`HfuJogp
XNJR`BTTPDR`SFTVMUDMBTT
TfuMbohvbhfGfbuvsft
XCFNQBUI`UFYU
GsffNfnpsz
JXcfnQbui`TfuDmbttObnf
n`Dpotu
XNJR`SQO`PQ`JTOVMM
JXcfnQbui`DsfbufDmbttQbsu`Qspyz
HfuUfyu
n`vTfmfduMjtuTj{f
XCFNQBUI`HFU`OBNFTQBDF`POMZ
JXcfnQbuiLfzMjtu
n`qcUsvuiUbcmf
XCFNQBUI`JOGP`JT`JOTU`SFG
JXcfnQbui`HfuUfyu
XCFNQBUI`JOGP`IBT`JNQMJFE`LFZ
n`vQspqfsuzUzqf
DMTJE`XcfnRvfsz
XNJR`MG4`TUSJOH`DBTF`GVODUJPOT
JXcfnQbuiLfzMjtuWucm
XNJR`MG43`TQ`FYFDVUF
JXcfnRvfsz`TfuMbohvbhfGfbuvsft`Tuvc
TXcfnSqoFodpefeRvfsz
JXcfnQbui`HfuUfyu`Tuvc
XNJR`MG41`XNJ`QSBHNBT
JXcfnQbui`SfnpwfTdpqf`Qspyz
n`vPsefsEjsfdujpoFm
n`qt{SftvmuSpmf
XNJR`SQO`PQ`HF
JJE`JXcfnQbuiLfzMjtu
XNJR`SQO`PQ`MU
n`qt{SfrvjsfeRvbmjgjfs
JXcfnQbui`HfuTdpqfBtUfyu`Tuvc
n`qt{Qbui
XNJR`MG46`DPNQMFY`TFMFDU`UBSHFU
JXcfnQbui`TfuTdpqfGspnUfyu`Qspyz
JXcfnQbui`TfuTdpqf`Tuvc
JXcfnQbui`SfnpwfBmmTdpqft`Tuvc
DMTJE`XcfnEfgQbui
n`qcBssbzFmVtfe
n`qqSqoXifsfDmbvtf
JXcfnQbui`TfuObnftqbdfBu
n`vMpohWbm
JXcfnQbuiLfzMjtu`HfuLfz`Tuvc
n`qt{Qspqfsuz
ubh`TXcfnBobmztjtNbusjy
JXcfnQbui`TfuTdpqf`Qspyz
XNJR`SQO`PQ`FR
JXcfnRvfsz`Qbstf`Tuvc
n`qt{SjhiuGvod
NblfTjohmfupo
JXcfnQbui`TfuDmbttObnf`Qspyz
JXcfnQbui`SfnpwfTdpqf
XNJR`MG3`DMBTT`OBNF`JO`RVFSZ
JXcfnRvfszWucm
JXcfnQbui`SfnpwfBmmTdpqft`Qspyz
n`qt{RvfszUfyu
JXcfnQbui`JtTbnfDmbttObnf
XNJR`MG37`MJLF
JXcfnRvfsz`GsffNfnpsz`Tuvc
JXcfnQbui`HfuDmbttObnf`Qspyz
JXcfnRvfsz`Fnquz`Qspyz
n`vDpotuBqqbsfouUzqf
TXcfnBttpdRvfszJog
XNJR`BTTPDR`SPMF
XNJR`MG28`RVBMJGJFE`OBNFT
JXcfnQbuiLfzMjtu`HfuJogp`Tuvc
XNJR`SQO`UPLFO`BOE
XNJR`MG23`HSPVQ`CZ`IBWJOH
XNJR`BTTPDR`DMBTTEFGTPOMZ
XCFNQBUI`HFU`SFMBUJWF`POMZ
XNJR`SQOG`BSSBZ`BDDFTT`VTFE
n`vNbusjyUzqf
XNJR`SQO`MFGU`QSPQFSUZ`OBNF
``XcfnEfgQbui`GXE`EFGJOFE``
XNJR`MG27`TJOHMF`MFWFM`USBOTBDUJPOT
XNJR`SQO`GSPN`DMBTT`MJTU
XNJR`SQOG`GFBUVSF
XNJR`MG4:`DPVOU`DPMVNO
XNJR`MG49`CBTJD`EBUFUJNF`UFTUT
ubh`TXcfnBttpdRvfszJog
JXcfnQbui`HfuJogp`Tuvc
XNJR`BTTPDR`BTTPDDMBTT
XNJR`SQOG`JTB`VTFE
JXcfnQbuiLfzMjtu`HfuDpvou`Qspyz
n`vFousjft
JtTbnfDmbttObnf
n`vWbm75
XCFNQBUI`JOGP`DPOUBJOT`TJOHMFUPO
XCFNQBUI`JOGP`BOPO`MPDBM`NBDIJOF
JXcfnRvfsz`UftuMbohvbhfGfbuvsft`Qspyz
n`vOvnUplfot
XCFNQBUI`RVPUFEUFYU
n`qqt{ObnfMjtu
n`mWbm75
JXcfnQbuiLfzMjtu`HfuDpvou`Tuvc
TfuLfz3
JXcfnRvfsz`HfuRvfszJogp`Qspyz
``XcfnRvfsz`GXE`EFGJOFE``
JXcfnQbui`EfmfufDmbttQbsu
XCFNQBUI`JOGP`JT`QBSFOU
XNJR`BTTPDR`SFRVJSFEBTTPDRVBMJGJFS
``JXcfnQbuiLfzMjtu`JOUFSGBDF`EFGJOFE``
SfnpwfBmmLfzt
XNJR`BTTPDR`SFGFSFODFT
XCFNQBUI`DSFBUF`BDDFQU`BCTPMVUF
XNJR`MG29`BTTPDJBUPOT
JXcfnRvfsz`UftuMbohvbhfGfbuvsft`Tuvc
EfmfufDmbttQbsu
n`vGspnUbshfuUzqf
TXcfnSqoUplfoMjtu
XNJR`SQO`SFMPQ
JtMpdbm
XCFNQBUI`JOGP`QBUI`IBE`TFSWFS
n`ecmXjuijoQpmmjoh
JXcfnQbui`TfuUfyu`Qspyz
XNJR`SQOG`TZTQSPQ`DMBTT`VTFE
JXcfnQbui`TfuTfswfs`Tuvc
JXcfnQbui`HfuTdpqfDpvou`Tuvc
XNJR`SQO`PQ`OF
JXcfnQbuiLfzMjtu`TfuLfz3`Qspyz
JXcfnQbuiLfzMjtu`Sfmfbtf
TXcfnBobmztjtNbusjyMjtu
n`vObnfMjtuTj{f
XCFNQBUI`USFBU`TJOHMF`JEFOU`BT`OT
XNJR`SQO`DPOTU3
HfuDmbttObnf
JXcfnQbuiLfzMjtu`RvfszJoufsgbdf
XNJR`MG38`DJN`UFNQPSBM`DPOTUSVDUT
ubh`TXcfnSqoUplfoMjtu
``NJEM`jug`xnjvujmt`1111`w1`1`t`jgtqfd
XNJR`SQO`UPLFO`PS
``JXcfnQbuiLfzMjtu`GXE`EFGJOFE``
XCFNQBUI`JOGP`XNJ`QBUI
XcfnRvfsz
n`qqt{PsefsCzMjtu
JXcfnRvfsz`Sfmfbtf
JXcfnQbui`JtSfmbujwf
XCFNQBUI`JOGP`W3`DPNQMJBOU
TXcfnBobmztjtNbusjy
XCFNQBUI`JOGP`IBT`TVCTDPQFT
XNJR`SQO`GSPN`QBUI
XNJR`MG2`CBTJD`TFMFDU
XNJR`BTTPDR`DMBTTSFGTPOMZ
XCFNQBUI`HFU`TFSWFS`BOE`OBNFTQBDF`POMZ
XNJR`MG5`QSPQ`UP`QSPQ`UFTUT
``NJEM```NJEM`jug`xnjvujmt`1227`1114
ubh`XNJR`SQOR`GFBUVSF
HfuTdpqf
JXcfnQbui`HfuDmbttObnf
JXcfnRvfsz`HfuBobmztjt`Qspyz
JXcfnRvfsz`TfuMbohvbhfGfbuvsft`Qspyz
n`vPqfsbups
XNJR`MG34`TVCTFMFDUT
JXcfnQbui`EfmfufDmbttQbsu`Qspyz
JtSfmbujwfPsDijme
JXcfnQbuiLfzMjtu`TfuLfz3
n`qt{BttpdDmbtt
JXcfnQbui`JtTbnfDmbttObnf`Tuvc
``JXcfnRvfsz`JOUFSGBDF`EFGJOFE``
JXcfnQbui`HfuDmbttObnf`Tuvc
JXcfnQbuiLfzMjtu`HfuLfz3`Tuvc
JXcfnQbui
JXcfnQbui`HfuTdpqf`Qspyz
JXcfnRvfsz`HfuBobmztjt
JXcfnQbui`RvfszJoufsgbdf
TXcfnSqoDpotu
TfuUfyu
ubh`TXcfnRvfszRvbmjgjfeObnf
HfuTfswfs
XNJR`SQO`UPLFO`GMBHT
JXcfnQbui`HfuObnftqbdfDpvou`Qspyz
n`qt{SftvmuDmbtt
HfuObnftqbdfDpvou
JXcfnQbui`HfuJogp`Qspyz
JXcfnQbuiLfzMjtu`HfuJogp
XCFNQBUI`JOGP`DJN`DPNQMJBOU
JXcfnQbui`BeeSfg
HfuJogp
ubh`TXcfnSqoFodpefeRvfsz
XNJR`SQOG`XIFSF`DMBVTF`QSFTFOU
XNJR`MG32`TRM9:`KPJOT
TfuTdpqfGspnUfyu
n`qt{Spmf
XcfnEfgQbui
n`cCppmWbm
