#Encrypted file follows
ue`ub`nbq`mxq3uis
OPUJGZ`CQU
bddftt
vtfs
tztdbmm
ebfnpo
quisfbe`cbssjfsbuus`hfuqtibsfe
quisfbe`tfutdifeqbsbn
uj`qsj
`DT`YCT6`MQ75`PGG75`DGMBHT
sfbemjol
``tdife`qbsbn
`TD`USBDF`FWFOU`OBNF`NBY
UE`NBMMPD
vjou`gbtu9`u
b`dpodvssfodz`efo
tfusfhje
tdife`ss`hfu`joufswbm
ue`uis`tjhtfunbtl
u{obnf
ue`fwfou`beetfu
ue`fwfou`nth
v`mpoh
npef`u
quisfbe`dpoebuus`eftuspz
`TD`CBTF
`TD`MFWFM3`DBDIF`TJ[F
UE`UIS`BDUJWF
et
UE`UIS`TMFFQ
fyfdmf
UE`QBSUJBMSFH
QUISFBE`JOIFSJU`TDIFE
`DT`MGT`DGMBHT
hfumphjo`s
UE`UIS`SVO
ue`ub`tfudpodvssfodz
quisfbe`buus`tfutubdl
quisfbe`nvufybuus`hfuqsjpdfjmjoh
hfuvje
hfuqbtt
``mpdbmf`u
``vtfdpoet`u
``quisfbe`dmfbovq`dmbtt
quisfbe`nvufybuus`hfuqspupdpm
uj`tjhnbtl
`DT`MGT`MJCT
OPUJGZ`BVUPCQU
`TD`CD`TDBMF`NBY
quisfbe`podf`u
UE`UIS`TZTUFN
`TD`TUSFBN`NBY
omxqt`efo
`DT`YCT6`JMQ43`PGG43`MJOUGMBHT
txe
ue`ub`tubut`u
quisfbe`cbssjfsbuus`eftuspz
``gmbht
`TD`DIJME`NBY
vjou`gbtu75`u
ojemf`ovn
`TD`W7`JMQ43`PGG43
vtfs`gqsfht`tusvdu
fyfdwq
quisfbe`tqjo`vompdl
tdife`tfuqbsbn
``obnft
ht
`TD`DQVUJNF
ue`fwfou`nth`u
gqbuidpog
uzqf
`TD`NFNPSZ`QSPUFDUJPO
quisfbe`nvufy`uszmpdl
UE`OPMJCUISFBE
quisfbe`nvufy`mpdl
OPUJGZ`TZTDBMM
`TD`YPQFO`SFBMUJNF
UE`SFBQ
dqv`tfu`u
qs`tje
``v`rvbe`u
uj`qsffnqugmbh
ue`joju
ue`ub`uis`jufs
`TD`YPQFO`WFSTJPO
ue`uis`tfuhsfht
vjou27`u
quisfbe`buus`u
qs`vje
uj`tjhnbtl
UE`CBEUI
``jouqus`u
sftfswfe
bmbsn
ue`uisjogp`u
`TD`3`TX`EFW
`TD`MFWFM3`DBDIF`MJOFTJ[F
tpdlmfo`u
CU`VJNBTL
quisfbe`dpoe`joju
quisfbe`nvufybuus`hfuuzqf
quisfbe`uftudbodfm
fyfdwqf
dmpdl`u
UE`OPMXQ
`TD`PQFO`NBY
ue`uis`fwfout`u
u{tfu
D
quisfbe`nvufy`dpotjtufou
ebub
gvujnftbu
ujnfy
`DT`HOV`MJCD`WFSTJPO
UE`UIS`VOLOPXO
`TD`DIBSDMBTT`OBNF`NBY
`TD`CD`EJN`NBY
``os`sfbefst
fbddftt
dbees`u
`TD`TZTUFN`EBUBCBTF`S
hfu`dvssfou`ejs`obnf
`TD`3`D`EFW
quisfbe`cbssjfs`eftuspz
`TD`VDIBS`NBY
eztj{f
vjou
dxe
quisfbe`nvufy`ujnfempdl
quisfbe`buus`tfuefubditubuf
`quisfbe`dmfbovq`cvggfs
quisfbe`podf
`TD`DPMM`XFJHIUT`NBY
`TD`OM`ONBY
psjh`sby
diejs
tu`tqbdf
uj`usbdfnf
qjqf
uj`ec`tvtqfoefe
quisfbe`buus`tfubggjojuz`oq
`TD`MFWFM3`DBDIF`BTTPD
tdife`hfudqv
`TD`YPQFO`VOJY
`TD`NC`MFO`NBY
`TD`MFWFM2`JDBDIF`MJOFTJ[F
tusvdu
`DT`QPTJY`W7`MQ75`PGG75`MJOUGMBHT
``tjhtfuknq
dmpdl`hfusft
txbc
hfuujnfpgebz
`TD`UISFBE`LFZT`NBY
ue`uis`umt`hfu`bees
`DT`QPTJY`W8`MQCJH`PGGCJH`DGMBHT
dt
bddu
`DT`YCT6`JMQ43`PGGCJH`MJOUGMBHT
quisfbe`sxmpdlbuus`u
quisfbe`nvufybuus`hfuqtibsfe
UE`OPNTH
hfuiptuobnf
``tpdlmfo`u
``vjou75`u
UE`NBY`FWFOU`OVN
UE`ECFSS
``nvufy
``smjn`u
qs`sfh
`DT`QPTJY`W7`JMQ43`PGGCJH`MJOUGMBHT
gbddfttbu
fyfdm
un`njo
UE`OPYSFHT
jou`mfbtu43`u
cmldou75`u
``mpgg`u
`TD`TQBXO
``ebub
hnujnf
uj`qfoejoh
ue`uis`tfuqsjp
v`gqtubuf
tucdou
scq
``os`xsjufst`rvfvfe
ue`uis`dmfbs`fwfou
tfmfdu
gdipxobu
evq4
hfuebuf`s
``npef`u
ue`fwfou`nth
sdy
ojemf`ovn
UE`EFBUI
ue`ub`dmfbs`fwfou
UE`CBEUI
qs`tjhqfoe
hfuqqje
`TD`SUTJH`NBY
gtgjmdou`u
``ue`fwfouxpse
fvjebddftt
``gtcmldou`u
`TD`MFWFM5`DBDIF`MJOFTJ[F
uj`ub`q
`TD`UISFBE`EFTUSVDUPS`JUFSBUJPOT
`DT`MGT75`MEGMBHT
`TD`UISFBET
`TD`VTISU`NBY
ue`fss`f
UE`OPUMT
qxsjuf
`TD`3`QCT
nth
ue`uis`jufs`g
quisfbe`hfubuus`efgbvmu`oq
uj`ub`q
ue`ub`hfu`qi
hov`efw`nbkps
quisfbe`buus`eftuspz
ue`ub`hfu`ouisfbet
uisfbe`lfz`u
`DT`HOV`MJCQUISFBE`WFSTJPO
`TD`TZNMPPQ`NBY
uj`umt
`TD`MFWFM5`DBDIF`BTTPD
fwfouebub
v
``ujnf`u
jou`gbtu75`u
`TD`YCT6`MQCJH`PGGCJH
jouqus`u
`TD`UISFBE`TBGF`GVODUJPOT
`TD`MPOH`CJU
UE`MPDL`USZ
quisfbe`sxmpdl`joju
`TD`MFWFM5`DBDIF`TJ[F
kjuufs
snejs
`DT`QPTJY`W8`JMQ43`PGGCJH`DGMBHT
nth
`DT`QPTJY`W8`MQ75`PGG75`DGMBHT
``dpvou
ue`uis`hfuysfht
ue`ub`tubut
OPUJGZ`CQU
uj`qsffnqugmbh
sfwplf
quisfbe`dpoe`cspbedbtu
uj`usbdfnf
``lfz`u
`TD`W8`MQ75`PGG75
`TD`NFNMPDL
`TD`QSJPSJUJ[FE`JP
qs`dvstjh
vtfs`sfht`tusvdu
`DT`MGT75`MJCT
quisfbe`nvufybuus`hfuspcvtu
``dbodfm`uzqf
`QD`NBY`DBOPO
`QD`QSJP`JP
`TD`YCT6`MQ75`PGG75
mpdbmf`u
``mjtu
tdife`tfutdifevmfs
s`dpodvssfodz
jou`gbtu27`u
ouisfbet
v`rvbe`u
ue`uis`dmfbs`fwfou
QUISFBE`DSFBUF`EFUBDIFE
tusqujnf`m
dszqu
``tfuepju
vojpo
quisfbe`buus`tfutdifeqpmjdz
quisfbe`lfz`u
un`zfbs
dujnf
``ep`ju
QUISFBE`SXMPDL`EFGBVMU`OQ
tdife`tfubggjojuz
`TD`QJJ`JOUFSOFU`TUSFBN
`DT`QPTJY`W7`JMQ43`PGGCJH`MJCT
QUISFBE`NVUFY`SPCVTU
qbvtf
qs`hje
`TD`CD`TUSJOH`NBY
``jujnfs`xijdi`u
`TD`TIBSFE`NFNPSZ`PCKFDUT
`DT`YCT6`MQ75`PGG75`MJCT
hov`efw`nblfefw
UE`JEMF
hfuepnbjoobnf
ue`uis`ecsftvnf
hfuqbhftj{f
UE`UIS`BOZ`TUBUF
v`jou43`u
quisfbe`nvufybuus`hfuspcvtu`oq
ue`uis`fwfou`hfunth
UE`OPYSFHT
UE`QSFFNQU
`DT`QPTJY`W7`JMQ43`PGGCJH`MEGMBHT
UE`OPMXQ
fwfounbtl
jou43`u
``jop`u
v
jnqmjdju
`DT`QPTJY`W7`JMQ43`PGG43`MEGMBHT
quisfbe`sxmpdlbuus`eftuspz
quisfbe`hfubuus`oq
tcsl
qs`qhsq
ue`ub`fwfou`bees
qs`gqwbmje
`TD`NPOPUPOJD`DMPDL
uj`vtfs`gmbht
ue`uis`tfutjhqfoejoh
tfuiptuobnf
``dbodfmuzqf
UE`TMFFQ
omjol`u
dmpdl
vomjol
hnujnf`s
tj`tjhop
ue`ub`uis`jufs
ue`uis`hfuhsfht
quisfbe`nvufybuus`tfuuzqf
ebub
QUISFBE`NVUFY`TUBMMFE`OQ
``v`dibs
`TD`USBDF`JOIFSJU
tfuvje
UE`UIS`BDUJWF
`TD`UZQFE`NFNPSZ`PCKFDUT
`TD`DIBS`NJO
UE`DPODVSSFODZ
uj`mje
UE`QSFFNQU
quisfbe`buus`tfutdifeqbsbn
`TD`TISU`NBY
qs`gobnf
qstubuvt`u
tubsu`dpef
`TD`OM`BSHNBY
QUISFBE`TDPQF`QSPDFTT
un`zebz
ue`uisbhfou
fyfdmq
QUISFBE`NVUFY`SFDVSTJWF`OQ
usvodbuf75
fmg`qstubuvt
uj`umt
ujnf
quisfbe`buus`hfutubdl
ue`uis`hfugqsfht
ue`opujgz`u
QUISFBE`QSPDFTT`QSJWBUF
vmpoh
qs`tubuf
quisfbe`dpoebuus`hfudmpdl
tjhtfu`u
`QD`OP`USVOD
quisfbe`hfuobnf`oq
`TD`TJHRVFVF`NBY
QUISFBE`NVUFY`GBTU`OQ
``mpdbmf`ebub
hfuxe
v`utj{f
UE`OPTW
hfutje
`TD`GE`NHNU
tztdbmmop
``dqv`nbtl
uj`sp`tj{f
nbhjd
uj`qjsfdgmbh
`TD`YPQFO`DSZQU
`TD`TUSFBNT
`TD`3`QCT`NFTTBHF
``efw`u
`TD`NR`QSJP`NBY
quisfbe`dpoebuus`tfuqtibsfe
``pgg`u
vjou43`u
``quisfbe`mjtu`u
ue`ub`ofx
``qje`u
oboptmffq
UE`QSJ`JOIFSJU
``tztdbmm`tmpoh`u
``tibsfe
ue`ub`fwfou`hfunth
UE`BMM`FWFOUT
ue`ub`nbq`je3uis
uj`ec`tvtqfoefe
UE`OPDBQBC
`QD`NBY`JOQVU
tfuiptuje
v`etj{f
UE`UJNFPVU
ue`ub`fobcmf`tubut
QUISFBE`NVUFY`EFGBVMU
quisfbe`buus`hfuefubditubuf
uj`qsj
`DT`QPTJY`W7`MQCJH`PGGCJH`MJCT
``vjou9`u
``tvtfdpoet`u
hfuebuf
``tdife`qsjpsjuz
`QD`GJMFTJ[FCJUT
`TD`CBSSJFST
quisfbe`efubdi
QUISFBE`QSJP`OPOF
`DT`MGT75`DGMBHT
`TD`SF`EVQ`NBY
QUISFBE`QSJP`QSPUFDU
kjudou
osvoobcmf`efo
v`bs1
``hfuqhje
sby
quisfbe`sxmpdlbuus`hfuljoe`oq
gt`cbtf
UE`OPDBQBC
UE`OPGQSFHT
`QD`TPDL`NBYCVG
ue`fss`f
quisfbe`hfudqvdmpdlje
`TD`EFMBZUJNFS`NBY
uj`qjsfdgmbh
ue`ub`tfudpodvssfodz
quisfbe`cbssjfs`joju
`TD`OQSPDFTTPST`DPOG
quisfbe`tfutqfdjgjd
tznmjolbu
qs`ojdf
UE`OPBQMJD
`TD`OM`MBOHNBY
`TD`USBDF`FWFOU`GJMUFS
``quisfbe`voxjoe`cvg`u
``ljoe
`TD`YPQFO`YQH5
seq
tt
ue`uis`hfuysfhtj{f
quisfbe`sxmpdlbuus`tfuljoe`oq
hfuqhsq
gdiejs
``knq`cvg`ubh
tdife`qbsbn
ue`uis`wbmjebuf
qsqtjogp`u
fgmbht
uuzobnf`s
uw`tfd
quisfbe`cbssjfsbuus`u
UE`NBY`FWFOU`OVN
hje`u
UE`SFBEZ
v`jou27`u
``knq`cvg
`DT`QPTJY`W8`JMQ43`PGG43`MJCT
``je`u
``xplfo`tfr
`DT`MGT`MEGMBHT
sfbemjolbu
`TD`QJJ`PTJ`DPUT
`TD`CD`CBTF`NBY
``quisfbe`joufsobm`mjtu
`TD`SFHFYQ
pqubsh
UE`FWFOU`OPOF
``qbe3
jtbuuz
vjou9`u
``tjhtfu`u
JUJNFS`WJSUVBM
UE`OPUBMMPD
vbmbsn
tjhobm
quisfbe`cbssjfs`xbju
`QD`SFD`JODS`YGFS`TJ[F
UE`NBMMPD
`DT`QPTJY`W8`MQCJH`PGGCJH`MJOUGMBHT
fwfou
qsgqsfhtfu`u
jop75`u
`TD`VJP`NBYJPW
`DT`W7`XJEUI`SFTUSJDUFE`FOWT
UE`OPUTE
un`jtetu
``tztdbmm`vmpoh`u
``qbe2
`TD`QPMM
qxsjuf75
`DT`QPTJY`W8`JMQ43`PGG43`MEGMBHT
hfufhje
ojemf`efo
`TD`W8`JMQ43`PGG43
`TD`W8`MQCJH`PGGCJH
`TD`UISFBE`TQPSBEJD`TFSWFS
gfyfdwf
`TD`YCT6`JMQ43`PGG43
UE`WFSTJPO
`TD`HFUQX`S`TJ[F`NBY
tusgujnf
mpdlg
`TD`3`QCT`MPDBUF
`TD`YPQFO`TUSFBNT
`TD`FRVJW`DMBTT`NBY
``nbtl`xbt`tbwfe
``smjn75`u
`QD`SFD`NBY`YGFS`TJ[F
UE`NJO`FWFOU`OVN
``fowjspo
`TD`3`QCT`BDDPVOUJOH
QUISFBE`NVUFY`OPSNBM
`TD`UISFBE`QSPDFTT`TIBSFE
UE`UIS`VOLOPXO
ge`nbtl
qspgjm
jou`mfbtu9`u
ujnfs`efmfuf
fwfou`cjut
`TD`UISFBE`UISFBET`NBY
ue`ub`ofx
qsfbe75
UE`UIS`BOZ`UZQF
qshsfhtfu`u
``mpdbmf`tusvdu
``ujnf{pof`qus`u
`DT`YCT6`MQCJH`PGGCJH`MJCT
vtipsu
ue`uis`ute
quisfbe`sxmpdlbuus`tfuqtibsfe
uw`otfd
qqtgsfr
OPUJGZ`TZTDBMM
``bsh
`DT`QPTJY`W7`MQ75`PGG75`MEGMBHT
tfusfthje
`TD`GJMF`BUUSJCVUFT
UE`FWFOUT`FOBCMF
fssdou
`TD`TZTUFN`EBUBCBTF
lfz`u
ue`uis`tfuysfht
ujnfwbm
`TD`USBDF`OBNF`NBY
mjol
ebees`u
`TD`TT`SFQM`NBY
npeft
`TD`MFWFM2`EDBDIF`MJOFTJ[F
tj`dpef
`TD`BEWJTPSZ`JOGP
quisfbe`dpoebuus`u
`TD`IPTU`OBNF`NBY
`QD`TZNMJOL`NBY
quisfbe`nvufy`vompdl
dpotubou
``rbees`u
gusvodbuf75
`DT`QPTJY`W8`JMQ43`PGGCJH`MJCT
quisfbe`tqjo`mpdl
jujnfswbm
gux
ue`fwfoucvg`u
ubj
`TD`NVMUJ`QSPDFTT
``tdife`dqvbmmpd
tj`fssop
quisfbe`frvbm
efw`u
`TD`TTJ[F`NBY
pggtfu
qbeejoh
ue`ub`fwfou`hfunth
`TD`QIZT`QBHFT
ue`uis`tfuhsfht
dujnf`s
`TD`D`MBOH`TVQQPSU
sej
ue`uis`wbmjebuf
QUISFBE`NVUFY`FSSPSDIFDL
UE`FSS
quisfbe`buus`joju
ue`uisiboemf`u
QUISFBE`NVUFY`SPCVTU`OQ
uw`vtfd
uj`tultj{f
JUJNFS`SFBM
ebzmjhiu
``tdife`dqvdpvou
tztdpog
uj`tultj{f
`TD`HFUHS`S`TJ[F`NBY
fwfounbtl
`DT`YCT6`JMQ43`PGGCJH`MJCT
ue`uis`fwfou`hfunth
``sftupsf
``ujnfs`u
quisfbe`dpoebuus`tfudmpdl
``ujnf{pof
`TD`DML`UDL
jou75`u
jou`mfbtu75`u
`TD`3`D`CJOE
mpdlg75
`TD`VTFS`HSPVQT
scy
quisfbe`sxmpdlbuus`hfuqtibsfe
ue`uisiboemf
``ebees`u
ue`opujgz`u
UE`BMM`FWFOUT
dipxo
tznmjol
pqujoe
`TD`BWQIZT`QBHFT
`TD`OM`NTHNBY
quisfbe`buus`tfutdpqf
ue`ub`hfu`tubut
UE`UIS`VTFS
fmg`hsfh`u
gpsl
`TD`MFWFM2`EDBDIF`TJ[F
quisfbe`tqjo`eftuspz
UE`UIS`BOZ`TUBUF
``ovtfst
sfhjtufs`u
ue`fwfoujtfnquz
un`tfd
``pgg75`u
tdife`hfu`qsjpsjuz`nby
`TD`U`JPW`NBY
ui`vojrvf
tusqujnf
nbyfssps
ue`ub`nbq`je3uis
tvtfdpoet`u
`TD`3`D`WFSTJPO
fwfouebub
`TD`YPQFO`TIN
`TD`USBDF`TZT`NBY
gtgjmdou75`u
quisfbe`nvufy`hfuqsjpdfjmjoh
``ge`nbtl
ue`opujgz`f
``cjut
mjol`nbq
UE`PL
tdife`hfubggjojuz
hfujujnfs
`TD`VJOU`NBY
qs`qtbsht
`DT`YCT6`MQCJH`PGGCJH`MJOUGMBHT
uj`fwfout
tzodgt
tijgu
UE`CBETI
`TD`OQSPDFTTPST`POMO
`TD`UJNFPVUT
uj`uzqf
ue`uisiboemf
UE`OPBQMJD
ojemf`efo
UE`UIS`MPXFTU`QSJPSJUZ
UE`UMTEFGFS
`UISFBE`EC`I
`TD`BJP`QSJP`EFMUB`NBY
UE`UIS`TZTUFN
UE`QSJ`JOIFSJU
ujnftqfd`hfu
mjolbu
ue`fwfoujtnfncfs
`TD`OM`UFYUNBY
UE`SFBQ
rvbe`u
`TD`MFWFM2`JDBDIF`BTTPD
ue`uis`tjhtfunbtl
gtzod
``cspbedbtu`tfr
cqubees
UE`QBSUJBMSFH
`TD`SFBEFS`XSJUFS`MPDLT
un`nebz
``bmjho
quisfbe`dpoe`eftuspz
ft
tjhfwfou
b`dpodvssfodz`ovn
v`gqwbmje
QUISFBE`NVUFY`TUBMMFE
`TD`UISFBE`QSJP`JOIFSJU
cqubees
gpq
nlujnf
`TD`SBX`TPDLFUT
`TD`TZODISPOJ[FE`JP
ue`ub`hfu`ouisfbet
qjqf3
quisfbe`sxmpdl`uszxsmpdl
UE`CBEQI
``cmltj{f`u
`TD`U[OBNF`NBY
uj`tulcbtf
ue`ub`fobcmf`tubut
quisfbe`dpoe`tjhobm
qt`qspdiboemf
vjou`gbtu43`u
quisfbe`nvufybuus`tfuqspupdpm
tfujujnfs
tfuqhje
`DT`QPTJY`W8`MQ75`PGG75`MEGMBHT
fwfou
`DT`YCT6`JMQ43`PGGCJH`DGMBHT
quisfbe`tfubuus`efgbvmu`oq
`DT`W7`FOW
vjou75`u
sey
`DT`QBUI
`TD`TDIBS`NBY
ue`uis`fwfout
tusgujnf`m
`DT`W6`XJEUI`SFTUSJDUFE`FOWT
`DT`QPTJY`W8`MQ75`PGG75`MJCT
mxqje`u
mdipxo
`TD`3`GPSU`EFW
quisfbe`tfudpodvssfodz
UE`UIS`TMFFQ
`TD`MFWFM4`DBDIF`TJ[F
`TD`QJJ`JOUFSOFU
``quisfbe`nvufy`t
ue`ub`nbq`mxq3uis
`TD`QSJPSJUZ`TDIFEVMJOH
pqupqu
``qbe
hfudxe
`TD`OHSPVQT`NBY
omxqt`ovn
ouisfbet
ue`uis`hfuysfht
`TD`UISFBE`SPCVTU`QSJP`JOIFSJU
quisfbe`nvufybuus`tfuqtibsfe
ue`ub`dmfbs`fwfou
uj`mje
`TD`BTZODISPOPVT`JP
gt
ue`fwfou`f
uisfbe`u
UE`UIS`TUPQQFE`BTMFFQ
`TD`GJMF`MPDLJOH
get`cjut
ujnf{pof
`TD`MFWFM2`EDBDIF`BTTPD
`DT`QPTJY`W8`MQ75`PGG75`MJOUGMBHT
ue`ub`sftfu`tubut
quisfbe`tqjompdl`u
pqufss
QUISFBE`FYQMJDJU`TDIFE
quisfbe`nvufy`eftuspz
QUISFBE`DSFBUF`KPJOBCMF
un`{pof
tdife`hfu`qsjpsjuz`njo
``ebzmjhiu
hfueubcmftj{f
ue`uis`tfugqsfht
`QD`QJQF`CVG
s22
ue`uis`ectvtqfoe
`fyju
UE`TXJUDIGSPN
``v`bs1`xpse
tzod
`TD`TFNBQIPSFT
`TD`NFNMPDL`SBOHF
qs`tujnf
`TD`MFWFM4`DBDIF`MJOFTJ[F
quisfbe`tfubggjojuz`oq
stj
`TD`GJMF`TZTUFN
``gtgjmdou75`u
`TD`QJQF
uuztmpu
``pxofs
uj`qfoejoh
UE`OPUTE
quisfbe`hfutqfdjgjd
ue`uis`tubuf`f
quisfbe`nvufybuus`joju
v`dibs
uj`tubsugvod
uj`tubsugvod
`TD`WFSTJPO
un`xebz
quisfbe`buus`tfuhvbsetj{f
vjou`mfbtu27`u
`TD`YPQFO`MFHBDZ
ue`tzncpm`mjtu
u{`etuujnf
``gvufy
`DT`QPTJY`W7`MQ75`PGG75`MJCT
UE`OPFWFOU
``jou75`u
quisfbe`buus`hfubggjojuz`oq
hfupqu
`TD`SFBMUJNF`TJHOBMT
s26
hov`efw`njops
jou9`u
efgjojujpo
`TD`DIBS`NBY
UE`OPUIS
ue`lfz`jufs`g
`TD`QBTT`NBY
tfuepnbjoobnf
UE`UIS`SVO
``dbees`u
``v`mpoh
`DT`QPTJY`W7`JMQ43`PGG43`MJOUGMBHT
hfusftvje
UE`DBUDITJH
v`tipsu
`TD`VMPOH`NBY
sjq
s:
`DT`MGT`MJOUGMBHT
ue`uis`ectvtqfoe
v`ttj{f
jou`mfbtu27`u
UE`OPNTH
`TD`3`WFSTJPO
UE`CBELFZ
quisfbe`fyju
quisfbe`dpoe`ujnfexbju
`DT`YCT6`JMQ43`PGG43`MJCT
uisfbe`lfz`u
``duzqf`upmpxfs
`TD`USBDF`MPH
mtffl75
quisfbe`u
`DT`QPTJY`W7`JMQ43`PGG43`MJCT
ujnfs`dsfbuf
fmg`qsqtjogp
s9
`TD`USBDF`VTFS`FWFOU`NBY
jou`gbtu43`u
ujnftqfd
`TD`UISFBE`BUUS`TUBDLTJ[F
ui`ub`q
UE`NJO`FWFOU`OVN
ue`uis`uzqf`f
``tdife`dqvgsff
ue`uis`umtcbtf
UE`SFBEZ
`DT`QPTJY`W7`MQCJH`PGGCJH`MJOUGMBHT
UE`FWFOU`OPOF
``jou9`u
nyds`nbtl
UE`UIS`BOZ`VTFS`GMBHT
ue`uis`hfuhsfht
hfufvje
``dmpdlje`u
``omjol`u
ue`uisbhfou`u
`TD`NFTTBHF`QBTTJOH
ujnfhn
`TD`VTFS`HSPVQT`S
QUISFBE`NVUFY`SFDVSTJWF
`TD`UISFBE`DQVUJNF
mtffl
UE`UIS`[PNCJF
`DT`QPTJY`W8`JMQ43`PGG43`DGMBHT
gsfr
`TD`TIFMM
hfuqhje
uj`tubuf
quisfbe`nvufybuus`u
`TD`BSH`NBY
`TD`GTZOD
QUISFBE`SXMPDL`QSFGFS`SFBEFS`OQ
tfuujnfpgebz
`TD`USBDF
ue`lfz`jufs`g
`QD`WEJTBCMF
un`hnupgg
`TD`3`VQF
tubsu`tubdl
ue`uis`tfugqsfht
dmptf
quisfbe`cbssjfsbuus`tfuqtibsfe
`TD`OFUXPSLJOH
hspvq`nfncfs
quisfbe`nvufybuus`tfuspcvtu
b`dpodvssfodz`ovn
`TD`UUZ`OBNF`NBY
quisfbe`hfutdifeqbsbn
fmg`hsfhtfu`u
uisfbe`u
`TD`TISU`NJO
`TD`TJHOBMT
uj`sp`bsfb
s25
u{`njovuftxftu
ue`uis`tfu`fwfou
`QD`BMMPD`TJ[F`NJO
ue`uisjogp
UE`FWFOUTJ[F
quisfbe`buus`hfutdpqf
uj`uje
ui`vojrvf
quisfbe`buus`hfutdifeqpmjdz
ue`uis`ecsftvnf
quisfbe`buus`hfutdifeqbsbn
quisfbe`dbodfm
quisfbe`sxmpdl`xsmpdl
udtfuqhsq
vjou`gbtu27`u
nydts
hfuqje
uzqf
ojdf
uj`tulcbtf
vjounby`u
qbuidpog
un
ftufssps
`TD`YPQFO`SFBMUJNF`UISFBET
sfbe
ue`uisjogp
`TD`YPQFO`YQH4
tztdbmmop
ue`uis`tfuqsjp
ynn`tqbdfCU`OCJQVJ
ue`mph
`TD`TJOHMF`QSPDFTT
`TD`BJP`NBY
quisfbe`tqjo`uszmpdl
`DT`QPTJY`W8`JMQ43`PGGCJH`MJOUGMBHT
`TD`YPQFO`YDV`WFSTJPO
v`jou9`u
dmpdl`hfudqvdmpdlje
vje`u
uj`uje
dmpdl`hfuujnf
`DT`QPTJY`W8`MQCJH`PGGCJH`MJCT
vujnft
`TD`UISFBE`QSJPSJUZ`TDIFEVMJOH
tfufhje
ujnfs`tfuujnf
qje`u
ue`ub`ute`jufs
QUISFBE`DBODFM`EFGFSSFE
``tjh`bupnjd`u
ttj{f`u
quisfbe`tfuobnf`oq
ht`cbtf
UE`UIS`TUPQQFE
`TD`MJOF`NBY
UE`CBELFZ
quisfbe`lfz`efmfuf
``gtxpse`u
UE`UJNFPVU
`TD`QJJ`PTJ`DMUT
ue`fwfou`nth`u
ue`ub`tubut`u
(jou(
ue`ub`sftfu`tubut
``qsfw
tfuhje
dpogtus
`TD`TBWFE`JET
upmfsbodf
evq
quisfbe`nvufybuus`eftuspz
fowjspo
xsjuf
ue`opujgz
UE`DSFBUF
QUISFBE`DBODFM`FOBCMF
UE`FWFOUT`FOBCMF
foevtfstifmm
`TD`TQJO`MPDLT
`QD`DIPXO`SFTUSJDUFE
`TD`TDIBS`NJO
`TD`TFN`OTFNT`NBY
tmffq
disppu
qsfdjtjpo
ejggujnf
wibohvq
quisfbe`dpoe`u
tj{f`u
uj`qd
QUISFBE`QSJP`JOIFSJU
`TD`SFHFY`WFSTJPO
tfumphjo
UE`UIS`TUPQQFE`BTMFFQ
ue`uis`fwfout`u
UE`UIS`[PNCJF
vjou`mfbtu75`u
uj`sp`tj{f
dbmdou
quisfbe`buus`tfujoifsjutdife
QUISFBE`DBODFM`EJTBCMF
ue`uis`uzqf`f
`TD`W7`MQ75`PGG75
``xsjufs
`TD`XPSE`CJU
hfumphjo
`TD`UJNFST
UE`DBUDITJH
`TD`EFWJDF`TQFDJGJD
ue`uis`fwfout
uj`tubuf
`TD`TFN`WBMVF`NBY
``jop75`u
quisfbe`lfz`dsfbuf
b`dpodvssfodz`efo
dmpdl`bekujnf
je`u
``ue`fwfounbtl
UE`MPDL`USZ
usvodbuf
quisfbe`sxmpdl`ujnfesempdl
ue`uis`jufs`g
ue`uis`hfuysfhtj{f
quisfbe`nvufy`dpotjtufou`oq
uj`qd
dmpdlje`u
quisfbe`zjfme
fmg`tjhjogp
QUISFBE`NVUFY`FSSPSDIFDL`OQ
gvujnft
quisfbe`dsfbuf
ujnfmpdbm
`TD`OM`TFUNBY
``cmldou`u
`TD`MFWFM4`DBDIF`BTTPD
qs`vujnf
`QD`MJOL`NBY
``v`jou
`DT`YCT6`JMQ43`PGGCJH`MEGMBHT
quisfbe`uszkpjo`oq
ue`uis`hfu`jogp
qs`qje
ju`joufswbm
qs`qqje
qs`tjhipme
wgpsl
qs`jogp
ue`uis`hfugqsfht
votibsf
ge`tfu
pgg75`u
UE`DSFBUF
ue`uis`hfu`jogp
qs`tobnf
ue`ub`tfu`fwfou
`TD`YPQFO`FOI`J29O
`TD`YPQFO`YQH3
tfuvtfstifmm
omxqt`efo
``v`tipsu
hfuebuf`fss
`TD`EFWJDF`TQFDJGJD`S
``ttj{f`u
`DT`YCT6`JMQ43`PGG43`DGMBHT
UE`OPUIS
ju`wbmvf
ue`uis`fwfou`fobcmf
`DT`QPTJY`W8`JMQ43`PGGCJH`MEGMBHT
`TD`3`DIBS`UFSN
quisfbe`buus`tfutubdltj{f
ue`ub`ute`jufs
ue`opujgz
``mpdbmft
`DT`QPTJY`W7`JMQ43`PGGCJH`DGMBHT
QUISFBE`DBODFM`BTZODISPOPVT
UE`CBEUB
``jou43`u
vtfe
vtmffq
ui`q
ovmmqus`u
quisfbe`sxmpdl`vompdl
`TD`BUFYJU`NBY
v`efcvhsfh
`TD`QBHFTJ[F
`TD`FYQS`OFTU`NBY
qsfbe
omxqt`ovn
UE`OPTW
quisfbe`buus`hfutubdlbees
`TD`UISFBE`TUBDL`NJO
v`jou
`QD`BTZOD`JP
``gtcmldou75`u
tfuqhsq
ue`uisiboemf`u
UE`OPMJCUISFBE
osvoobcmf`ovn
uj`sp`bsfb
``dbodfm`spvujof
`TD`JOU`NJO
hfusfthje
``sfbefst`xblfvq
quisfbe`nvufy`u
un`npo
``duzqf`c
``tj{f
btdujnf
UE`OPGQSFHT
udhfuqhsq
QUISFBE`SXMPDL`QSFGFS`XSJUFS`OPOSFDVSTJWF`OQ
ui`ub`q
JUJNFS`QSPG
QUISFBE`SXMPDL`QSFGFS`XSJUFS`OQ
ujnfs`hfupwfssvo
`TD`D`MBOH`TVQQPSU`S
`TD`JQW7
UE`CBEUB
quisfbe`sxmpdl`ujnfexsmpdl
`TD`W7`JMQ43`PGGCJH
jou27`u
dmpdl`tfuujnf
quisfbe`buus`hfuhvbsetj{f
gdipxo
`DT`YCT6`MQCJH`PGGCJH`MEGMBHT
`DT`YCT6`JMQ43`PGG43`MEGMBHT
`TD`TQPSBEJD`TFSWFS
`TD`3`QCT`USBDL
fyfdw
``spvujof
uj`uzqf
tfusftvje
qusejgg`u
``mpdl
`TD`3`MPDBMFEFG
qt`qspdiboemf
``dbodfm`knq`cvg
ujnfs`hfuujnf
mpgg`u
OPUJGZ`BVUPCQU
tubcjm
ujnfs`u
``v`gqtubuf`xpse
tdife`zjfme
ue`ub`hfu`tubut
quisfbe`dpoebuus`hfuqtibsfe
QUISFBE`NVUFY`BEBQUJWF`OQ
jounby`u
ue`ub`tfu`fwfou
dmpof
jop`u
quisfbe`dpoe`xbju
quisfbe`sxmpdl`uszsempdl
`TD`NR`PQFO`NBY
ue`opujgz`f
`TD`W8`JMQ43`PGGCJH
`TD`BJP`MJTUJP`NBY
ue`uis`tfutjhqfoejoh
`DT`W8`FOW
UE`TMFFQ
`TD`QJJ`TPDLFU
`TD`QJJ`PTJ`N
UE`PL
osvoobcmf`ovn
vtfdpoet`u
QUISFBE`NVUFY`UJNFE`OQ
qs`dtujnf
``vjou27`u
`QD`QBUI`NBY
ue`uis`tfu`fwfou
cmldou`u
`DT`YCT6`MQCJH`PGGCJH`DGMBHT
UE`OPFWFOU
``wbm
``jujnfs`xijdi
s24
quisfbe`cbssjfs`u
qs`{pnc
v`dpnn
evq3
osvoobcmf`efo
ue`joju
UE`DPODVSSFODZ
csl
``efgfs
quisfbe`nvufy`tfuqsjpdfjmjoh
`DT`QPTJY`W8`JMQ43`PGG43`MJOUGMBHT
quisfbe`buus`hfutubdltj{f
``vje`u
`TD`MPHJO`OBNF`NBY
`DT`QPTJY`W8`MQCJH`PGGCJH`MEGMBHT
vjouqus`u
quisfbe`tqjo`joju
quisfbe`sxmpdl`sempdl
UE`UIS`VTFS
`DT`MGT75`MJOUGMBHT
tujnf
`QD`SFD`NJO`YGFS`TJ[F
quisfbe`tfmg
qtfmfdu
`TD`DMPDL`TFMFDUJPO
gtcmldou`u
tfufvje
vomjolbu
ue`tzncpm`mjtu
``xblfvq`tfr
s21
hfuhspvqt
quisfbe`sxmpdl`eftuspz
fodszqu
``jou27`u
fwfou`cjut
`TD`JPW`NBY
un`ipvs
CU`VJTIJGU
``dbodfm`bsh
``dmpdl`u
quisfbe`nvufybuus`tfuspcvtu`oq
jou`gbtu9`u
`TD`KPC`DPOUSPM
gebubtzod
`TD`QJJ`YUJ
ue`uisbhfou`u
ue`ub`hfu`qi
gtje`u
ue`fwfou`f
``os`sfbefst`rvfvfe
quisfbe`cbssjfsbuus`joju
UE`TJHOP`NBTL
UE`ECFSS
`DT`QPTJY`W7`JMQ43`PGG43`DGMBHT
ue`ub`efmfuf
pgg`u
ue`ub`tubut
`TD`3`GPSU`SVO
ue`uis`fwfou`fobcmf
cmltj{f`u
UE`TXJUDIGSPN
vjou`mfbtu43`u
uj`vtfs`gmbht
ujnf`u
`TD`O[FSP
tdife`hfutdifevmfs
ue`fwfoucvg`u
`TD`QJJ
fmg`gqsfhtfu`u
`TD`UISFBE`BUUS`TUBDLBEES
quisfbe`hfudpodvssfodz
`TD`UJNFS`NBY
quisfbe`buus`tfutubdlbees
`QD`TZOD`JP
`DT`W8`XJEUI`SFTUSJDUFE`FOWT
uj`gmbht
`QD`OBNF`NBY
``upubm`tfr
`TD`MFWFM2`JDBDIF`TJ[F
ue`mph
`TD`YCT6`JMQ43`PGGCJH
UE`UIS`TUPQQFE
`TD`QJJ`JOUFSOFU`EHSBN
gtcmldou75`u
``u{obnf
`DT`QPTJY`W7`MQCJH`PGGCJH`DGMBHT
quisfbe`ujnfekpjo`oq
``rvbe`u
ue`uis`tubuf`f
``tqjot
quisfbe`tfutdifeqsjp
tfutje
quisfbe`kpjo
mvujnft
UE`TXJUDIUP
``vjou43`u
``duzqf`upvqqfs
qs`dvujnf
quisfbe`dpoebuus`joju
sfgfsfodfe
quisfbe`sxmpdlbuus`joju
quisfbe`nvufybuus`tfuqsjpdfjmjoh
UE`UIS`BOZ`UZQF
ue`ub`efmfuf
`TD`3`QCT`DIFDLQPJOU
UE`FSS
quisfbe`nvufy`joju
bekujnf
btdujnf`s
`DT`YCT6`MQ75`PGG75`MJOUGMBHT
tubuvt
`TD`UISFBE`QSJP`QSPUFDU
hfuiptuje
UE`JEMF
quisfbe`hfubggjojuz`oq
hfuhje
quisfbe`bugpsl
ui`q
uuzobnf
quisfbe`buus`hfujoifsjutdife
quisfbe`tfudbodfmtubuf
uj`tq
``xsjufs`xblfvq
`TD`NBQQFE`GJMFT
stq
fwfouovn
UE`CBETI
vjou`mfbtu9`u
ue`uis`tfuysfht
`DT`QPTJY`W7`MQCJH`PGGCJH`MEGMBHT
qs`gmbh
uj`fwfout
tue
`TD`EFWJDF`JP
ue`uisjogp`u
``ofyu
`DT`YCT6`MQ75`PGG75`MEGMBHT
``hje`u
QUISFBE`TDPQF`TZTUFN
``cmldou75`u
ue`fwfou`fnquztfu
tdife`hfuqbsbn
dmpdl`oboptmffq
s23
`TD`JOU`NBY
`QD`SFD`YGFS`BMJHO
uj`tq
v`jou75`u
ue`fwfou`efmtfu
tfuot
`TD`TFMFDU
sfht
``quisfbe`dmfbovq`gsbnf
``oxbjufst
``gtgjmdou`u
uj`gmbht
``gtje`u
fyfdwf
`TD`GJGP
quisfbe`sxmpdl`u
ue`fwfou`gjmmtfu
s`dpodvssfodz
mpdbmujnf
UE`EFBUI
`QD`3`TZNMJOLT
gusvodbuf
hfuvtfstifmm
ue`uis`ute
qtbees`u
`TD`W7`MQCJH`PGGCJH
`TD`QJJ`PTJ
`DT`QPTJY`W7`MQ75`PGG75`DGMBHT
`TD`DIBS`CJU
jujnfstqfd
fwfouovn
tfusfvje
ue`ub`fwfou`bees

UE`CBEQI
``fmjtjpo
mpdbmujnf`s
UE`TXJUDIUP
QUISFBE`QSPDFTT`TIBSFE
j498
ujdl
`TD`UISFBE`SPCVTU`QSJP`QSPUFDU
