#define qnLM LY8c
#define NhTm }
#define qpdp {
#define JbF1 &&
#define LjAT .
#define oPI2 vector
#define rg3n )
#define fmOe ;
#define KQWQ ;
#define ldwh =
#define SvVi vector
#define qiED (
#define qh56 .
#define LmEi curSz
#define P8KR )
#define T4Nq )
#define ZicJ >
#define _VU6 (
#define RY2G ;
#define DssS false
#define fzn4 ;
#define Tjux }
#define OzS3 ,
#define toWF v
#define vCP3 )
#define wwUy ;
#define wWSD ;
#define ZJMY [
#define GFRB (
#define PHgA )
#define AruU !=
#define y3nE ]
#define s00c =
#define Zuoi int
#define qwFk u
#define JRkJ (
#define RMnp stk
#define t8ej (
#define Wd8e )
#define NdxG (
#define tnPf ;
#define lrcm ,
#define o40R }
#define oUS5 ++
#define dqYl ,
#define FTgp <=
#define y3vG KiHs
#define x4hL hmMK
#define Nzb0 (
#define jrrE >=
#define IzPi )
#define Wrms (
#define H1tE size
#define JZxZ unsigned
#define UKTl =
#define C6dY x
#define rUd8 )
#define n4fc .
#define wf3k idx
#define rfLC )
#define RC0v ,
#define U4ln <
#define yvlL ;
#define RUC4 (
#define ek0H ]
#define fCWe .
#define lUom 0
#define F7aE ]
#define GSAt nodesOfColor
#define VXqf unsigned
#define sLxC (
#define Jzyh int
#define LjNS j
#define vJWO ;
#define XjrG }
#define Tscq long
#define WZ6F while
#define xWEP >=
#define i5AI (
#define pchZ col
#define Gd89 S
#define GZy2 =
#define U74V =
#define S76F n
#define DeML }
#define zZHM <
#define GhLf --
#define PWVS if
#define dOlZ (
#define rw7q MmgJ
#define kos8 u
#define aetd ;
#define o5KH ;
#define hEfm long
#define iaka vorder
#define VJSo (
#define HxNs stk
#define Ne3B =
#define Bdeu tag
#define HiBQ )
#define KE6r ;
#define G5Ho parent
#define gdXW col
#define qMC9 i2
#define Cu4L (
#define jXka ++
#define gY7t <
#define Ru4t k
#define vAez ]
#define avU0 ]
#define YyEt ,
#define aGLB (
#define YThZ (
#define q5XT 1
#define Mbql ;
#define FoZZ .
#define tOWa ,
#define S8fB ;
#define L8bE =
#define f3MA t6Qt
#define AfSO y
#define qU2m vector
#define D8FC unsigned
#define UyLX for
#define Oh7y ;
#define hUUT size
#define _q4y (
#define VmuV =
#define mezK 1
#define Kmkz ;
#define M95x stk
#define X6l5 (
#define thfP long
#define T7MI unsigned
#define t2av (
#define Zn0z cin
#define Ln1U ;
#define PNOE [
#define jaEo int
#define tAWr =
#define CLaq State
#define _GDj vector
#define bnyL (
#define MBgA constexpr
#define TP9o const
#define bSSP int
#define BSok int
#define KhdZ ;
#define utMJ ]
#define I8Ge n
#define eVcJ int
#define jjKE ;
#define NEz7 !=
#define RGSX .
#define lqvL ]
#define POm0 )
#define N9Ni u
#define hUEl stk
#define KqFz ;
#define oU9c mid
#define djVH long
#define maIK >
#define h5no vector
#define huW0 (
#define q6SU s
#define gFqG )
#define qdTf (
#define oTJV push_back
#define UhwV [
#define gBEY =
#define bdLi )
#define UpSe ;
#define i778 !
#define KZRH ]
#define jxpv parent
#define HoaS unsigned
#define MxiR (
#define i5ve timer
#define mjGB range_add_subtree
#define FQe3 int
#define OuEq {
#define Swp1 tie
#define ifB2 ^
#define M9Gh (
#define Xg31 k
#define usOX long
#define UuCf st
#define PrFM u
#define aiMq ==
#define GUNL [
#define Xrr4 ]
#define FqcQ {
#define aXaY .
#define IwlP &&
#define o6B6 unsigned
#define uk5s auto
#define fs7g ;
#define rMAS n
#define uFjp max
#define cKYe u
#define n5Ip .
#define U6Mi pop_back
#define Py0z x
#define P4YH long
#define Fmst ;
#define fnpT }
#define z3JR pick
#define _5ZJ (
#define qoW6 ;
#define FcJE int
#define k550 (
#define s1nr [
#define ndSm )
#define R7SH (
#define yRoK [
#define wBeD ;
#define eZQX vector
#define nSoY [
#define JkN7 st
#define w97i unsigned
#define DiY0 )
#define ZGeb [
#define l1fE for
#define opOa )
#define tBT2 }
#define Q4Vo ;
#define hZtI (
#define OIdg 1
#define h2z8 static
#define Yox6 (
#define _Foo (
#define _v9l (
#define WG6J a
#define Qeop ,
#define zlQj st
#define Yi0w )
#define JWc0 i
#define o2ua st
#define AMWn .
#define r5qo parent
#define XxI1 >
#define yhXy [
#define FHHu )
#define RLDi <
#define LLDZ push_back
#define Gkt6 =
#define lyy8 z7kh
#define XOq1 ;
#define QDgH struct
#define UFjq [
#define k0EU u
#define Qlc1 st
#define SkRu .
#define PN4p 0x185e030000000000ULL
#define RtZH a
#define nLyU (
#define B32b )
#define irFM active
#define qy1U stk
#define dXfA 0
#define K9my ++
#define _jm2 (
#define YAzy )
#define g7Eg diff
#define WpVF curSz
#define AIon bool
#define Omxr (
#define alWk const
#define csn3 (
#define SuN8 {
#define lDi6 u
#define Dzv1 .
#define SYXT u
#define Soea &&
#define E9DH t
#define fwJJ for
#define EJqU ;
#define Mjkt tout
#define dfQj Ru1G
#define BUZl ;
#define sxc7 ,
#define QV8A 0
#define thij )
#define DyKx )
#define _yuq >>
#define NNXR ,
#define gDop ;
#define tph9 ]
#define eapr (
#define Y5Hb empty
#define Ba2m )
#define mEip ,
#define v1r7 B
#define w9Jp push_back
#define YaD1 int
#define en5b =
#define PPMf )
#define vjiP A
#define Fdu9 -
#define AuKh int
#define hecZ +
#define hygq long
#define K79l )
#define CUFa u
#define rYW9 =
#define Nqcr reserve
#define pfnl [
#define yEkV ;
#define QkNY long
#define JJ4v vector
#define ntzL int
#define b687 ]
#define cQOQ )
#define veWb auto
#define sDoI (
#define mcdB {
#define J9lF (
#define sGxM v
#define LFaw ++
#define DEcg {
#define Pj4q eulerByTin
#define JPpf v
#define BKng int
#define VlrE )
#define O3ho [
#define FflR v
#define BaVP if
#define gSsW int
#define rxjm p
#define Cqoc long
#define XgCn if
#define qC7a k
#define W0MQ (
#define LrgG ;
#define aBni long
#define FZEK &&
#define E0bG ]
#define bizU pick
#define s5yF n
#define fwv2 (
#define FKGg ;
#define Ovjn )
#define tO5h )
#define OlTt )
#define wrnN tin
#define JC19 =
#define QQ6s vector
#define liSG (
#define ZSf2 nodesOfColor
#define kwf2 0x78ffac0000000000ULL
#define IBDn )
#define zfv4 )
#define DWsK int
#define gtaO (
#define FT70 )
#define D0fC )
#define Ri5k v
#define yddE <
#define wd3q int
#define _ISb ;
#define Szxj int
#define uhiH ]
#define v11j .
#define LTwT Ru1G
#define FJaF ]
#define KT6R u
#define MT0y <
#define w9Cx size
#define v8W0 1
#define pvfj (
#define k17M [
#define uKLp .
#define QlpC (
#define WAuZ )
#define YGdj )
#define RamZ n
#define ZKxm stk
#define HC2m diff
#define IqBB )
#define dKqU =
#define drPp )
#define DqeD ]
#define ergQ )
#define GZxL )
#define zLkq !=
#define CkwE <=
#define rKXz (
#define eiGY c
#define KeqD u
#define Pox7 .
#define Ynnu <=
#define XBVI int
#define ud8U pJOX
#define LyGi (
#define GrKX eulerByTin
#define SaAT +
#define EmP5 {
#define acIm >
#define elwy if
#define eZuI {
#define UGwY 0
#define zBqo ;
#define PKdr <
#define KVc5 L7Wz
#define LxNr int
#define BwV3 ]
#define Lsgb ^
#define GeaV [
#define PQsl <
#define rSt1 u
#define k6UI long
#define fLTT >
#define veqQ [
#define C80I while
#define Q1as s
#define o0qN s
#define kMiC parent
#define rVsb col
#define pFqF (
#define _bGP OSCm
#define TXgn .
#define pyrw stk
#define WzmA size
#define cwYl !=
#define Mnzk (
#define pUi0 (
#define NHsD ;
#define KlPs )
#define HTO8 )
#define D78g 0x78ffac0000000000ULL
#define AK5e (
#define S4sI )
#define mTTW unsigned
#define mn16 }
#define DRXu maxColor
#define rFyK ]
#define hWF4 1
#define vtqS 0
#define ZJBo tout
#define gl96 Ri7E
#define TYnZ (
#define vLQO x
#define o8ln colorsPresent
#define bYpq up
#define nkdM ;
#define nz9a int
#define LxWD )
#define PEHA )
#define yVRy c
#define fJ22 (
#define JtC6 [
#define wBiH u
#define ZKyB (
#define pFMC [
#define xuEw long
#define ysQj A
#define mWhG ;
#define hnGB (
#define XzY1 curTag
#define xPZD ;
#define zz7b diff
#define udyX pick
#define a6ab auto
#define sOof .
#define UF6E aAB1
#define zQoZ ;
#define PCGV {
#define lDBy back
#define zhI7 )
#define QHRM [
#define _7oC long
#define PpUe }
#define k0MP [
#define wNkm )
#define jXtQ (
#define V07Z ]
#define yJNg ==
#define BwqB ;
#define lWWF (
#define Zfqq ;
#define OrG7 0
#define Qd2S .
#define r6o0 sync_with_stdio
#define GbrP ^
#define Rf6S (
#define jFdF long
#define ht6A lca
#define Vhlf (
#define fTeY [
#define gGM2 0
#define KZfi ;
#define DqIe [
#define lVpF +
#define F3Y3 long
#define rDR1 u
#define gmDU )
#define MNT9 (
#define C7te (
#define MfBK y
#define ZFsx colorsPresent
#define CUzb if
#define Zv2H )
#define z6Sb ;
#define c4nR )
#define qwoS )
#define OtzI )
#define i5kk int
#define D5Mw L
#define Qh7D u
#define HsPY ]
#define b1dG (
#define Azr0 u
#define Zco6 long
#define wXK2 B
#define YJMv back
#define cY7c )
#define yAXJ .
#define wQiL L
#define lAyu 3
#define rAmd (
#define wprO (
#define jI8O <
#define Q1rS u
#define jTcf .
#define W3Zq ]
#define CiUQ (
#define _Qoh 2
#define eyGq [
#define AEQS sub
#define eL0i )
#define Frss (
#define LtSU int
#define Nr3A ]
#define Tv7l LOG
#define UkWJ aAB1
#define X3tt (
#define PKe9 (
#define XI18 >>
#define P3mS <
#define XbF5 )
#define _yAR pop_back
#define BilU 0x2852430000000000ULL
#define _cmM pJOX
#define Mh1Z )
#define Ah0a )
#define shvm ]
#define flo2 unsigned
#define KmCL t
#define l4Zo v
#define j4N3 ;
#define msrj oXuA
#define AfyH ]
#define vsDl )
#define EQeN int
#define D1J1 u
#define nwZH )
#define NH2a n
#define qQQJ <
#define t2Zu b
#define RPk7 long
#define wOvN =
#define Io0x ]
#define qdUg )
#define RUx8 pop_back
#define QZbx ZIbK
#define ktCs nx
#define TL3b :
#define QvL0 reserve
#define n4CH ;
#define o7ro )
#define CvY8 (
#define COK9 )
#define ZUda c
#define L5CB <
#define lcOy 1
#define jaAf [
#define boES int
#define QBS7 eDre
#define bFs3 }
#define QEUL while
#define j0ZC )
#define wzm3 long
#define xXwJ v
#define xMrv }
#define vkYq )
#define KBRv int
#define cnHI ^
#define _ZOf Ru1G
#define bnlX long
#define VM58 )
#define buHt )
#define xB6o (
#define E1bn vector
#define KK8G ;
#define kW1s unsigned
#define da2s cxjS
#define skp4 (
#define QbkT push_back
#define EOUh LY8c
#define Aur7 Aavf
#define U9gR L
#define lEkW ;
#define WEvJ (
#define mFRD <
#define JtMs L
#define glIi u
#define yo6u [
#define zPfN )
#define fS83 )
#define IKc3 int
#define cdCH (
#define jnBC (
#define whvH auto
#define TKHE tin
#define QRxN i
#define tT34 ;
#define PvDt -
#define BE9f oXuA
#define hmrI {
#define qdad )
#define O8ck int
#define qYXI [
#define _HnA )
#define Nbym {
#define j0bH .
#define QfpS (
#define j06q )
#define GzGI 0x185e0300000186a0ULL
#define icTF tout
#define t4QT ::
#define yDNz }
#define XLuQ L
#define OTTo pop_back
#define XVZp int
#define KAlQ ,
#define F2xD =
#define r9Iz long
#define qkak =
#define YoNI ]
#define IRen ;
#define niDR }
#define VuVY +
#define IPu1 for
#define Sh47 )
#define LnOO )
#define RIVz 1
#define M5wr ++
#define NmRC ,
#define qLAQ pick
#define zP4G )
#define aW6r return
#define CQQl ,
#define Fm5d return
#define IDcD active
#define AuYM isCut
#define krp0 0
#define gQJl long
#define T92P )
#define VLx4 ]
#define P1BZ ]
#define qjK7 long
#define gubk ]
#define NwJk unsigned
#define JfkB ++
#define Vxrp ;
#define lr8D {
#define jpUp ^
#define B8zO long
#define VBJv {
#define PMPQ [
#define unNB +
#define ErpJ long
#define O1Nt size
#define Pzwb )
#define IMSD (
#define L08k ,
#define hmgw )
#define b3KX j
#define xnHQ =
#define v45U !=
#define ADtC )
#define uC1p vector
#define MIUk >
#define EaMz ;
#define tJAL size
#define rlMl (
#define NYYX isCut
#define BMEL [
#define D7u1 }
#define AZVf ==
#define tOH8 =
#define V9p3 nvXR
#define UEHk ;
#define q0NP )
#define hbUo {
#define dxM9 !
#define ExjL ;
#define jw0h )
#define Qk2T timer
#define Cgbl /
#define AzIU colorsPresent
#define laC7 a
#define tdDo st
#define lXWn .
#define hLGI stk
#define bCMj (
#define FNac j
#define ubHX 1
#define ej2R long
#define IPWk [
#define hXEJ (
#define JDAz ;
#define BtdG }
#define YXfM ,
#define iUKr )
#define iLpl -
#define uu36 (
#define _0JV v
#define nVV6 ,
#define UH7i (
#define rLGg ;
#define FPre (
#define rtn1 (
#define yVsQ (
#define K3hS ++
#define eihO if
#define FZqd ;
#define o42E s
#define ZWO7 <
#define dHtx .
#define ttPZ int
#define jJIR reserve
#define pZrW [
#define a7lc [
#define JHap int
#define PV8u (
#define O8ii empty
#define eNfo clear
#define v7XC .
#define mYyn )
#define TCbs .
#define ts0o )
#define xfqQ <=
#define JTnz )
#define gzSZ )
#define RA1y maxColor
#define jEda =
#define oPEj ]
#define atna (
#define y24c !=
#define _sr3 back
#define dpeT (
#define VLGc )
#define Ngda (
#define I6Pi <
#define BBlr reserve
#define x7gf )
#define YucO (
#define B5as long
#define gJAq &
#define ysLW [
#define P2pH A
#define ule3 int
#define G91M ]
#define A5Kc ;
#define u7Bm )
#define MGfW .
#define OAf4 )
#define tYtS if
#define uIQy ]
#define qSw6 k
#define CI8r ,
#define YX0Y (
#define z7Wr used
#define d5SQ int
#define UMXw (
#define EcvD .
#define Tcuh &
#define ZR2U (
#define Yplf auto
#define W91w ]
#define _SwI back
#define aylR ;
#define VN75 rootsOfColor
#define ndGf long
#define twSQ oGiP
#define RzOK ++
#define ZuEk c
#define dKIu ]
#define K58w <
#define G9KZ ]
#define azT7 )
#define tiKx ;
#define M0WX ;
#define W5y5 size
#define OjQY if
#define OylE ;
#define Bkxx (
#define c9Y7 )
#define F7ha >
#define lfLD }
#define mpo6 1
#define wZVk =
#define BHn6 0x78ffac0000000000ULL
#define H6av (
#define s3Tu :
#define U7IR ;
#define w1nC nodes
#define J0FY 1
#define TLJS maxColor
#define Mf7x B
#define Yg86 c
#define TXcS isCut
#define oG1c pJOX
#define F4Lc int
#define AFx0 )
#define mKDX [
#define jz6z return
#define zvno >
#define nZuu 1
#define YX4d (
#define EUor LY8c
#define B5hJ =
#define mqWb =
#define dVPU depth
#define vOat u
#define hjZh >
#define NEU9 ]
#define WPko ;
#define YUxX 0
#define Y8MX x
#define Rd9o run
#define wTXD int
#define qAPk itIndex
#define Vo6v int
#define ZZC7 pop_back
#define X2da up
#define _Vyn ]
#define pEKm (
#define XOQM +
#define MfE3 long
#define hJZe tin
#define wh1V (
#define dz2Z vt
#define qyVp (
#define fH7C =
#define I1uK [
#define JbbE 1
#define db3i =
#define wU3K [
#define Oerb )
#define nw4i LOG
#define Jl9v 1
#define Fte8 aAB1
#define WwwJ ,
#define pOe2 (
#define bXm5 long
#define PSnC reserve
#define erJc ;
#define KO3H =
#define OqDV int
#define Dbgh (
#define xDM6 tin
#define vGfP {
#define TO76 :
#define rD8E Ru1G
#define ApkR .
#define qTGm .
#define rIHc curSz
#define FMkv ;
#define gGYy u
#define MEjw (
#define VWmm return
#define EGQ8 ]
#define wiuX (
#define mH50 ;
#define gQWB ]
#define NxNM ]
#define XPaC =
#define zbP7 =
#define pl4K base
#define geR8 {
#define fD5y v
#define gOJc cQP9
#define Fzwz auto
#define w1KT [
#define JxdR (
#define J84n )
#define lV1Y (
#define KUPy <
#define qIlB maxColor
#define wMiH ;
#define s9Oo )
#define au2s parent
#define jqzV parent
#define bzpk (
#define P2eq vorder
#define EgSI }
#define GFi7 =
#define lshw [
#define AHp0 (
#define xjlM ,
#define R1OG )
#define QRu6 long
#define VFxw =
#define JyML c
#define by1d QikP
#define JdXl )
#define KmgX addNode
#define Ajwn (
#define xfd4 ^
#define BryH >
#define RITc stk
#define hcrO ]
#define Qj5X if
#define Mhf9 .
#define UcQT +=
#define PGiK [
#define IUS7 ;
#define zXax )
#define QCjp )
#define unvz )
#define RrLy +
#define mL99 }
#define btjO (
#define nQrH [
#define YwLJ )
#define rpz0 ;
#define Gd2T (
#define TP5r .
#define oMBP [
#define tDn2 <
#define Nz0F 1
#define lzin [
#define MtYT (
#define XRSD back
#define Cm11 {
#define r42j ;
#define zHAK ;
#define YzRs [
#define fLa1 int
#define tHaO ]
#define ktHn )
#define F8EL u
#define RQVJ <
#define tXOv {
#define Dcun ]
#define z1Kp 1
#define rW6Y sub
#define SyKV ;
#define vBmt 1
#define gn5L 1
#define OuUP parent
#define B80P ;
#define _4yo push_back
#define PpQm n
#define uMNK WShT
#define nqGQ ;
#define OSUh >>
#define U9Fk 0
#define W5AC for
#define KkiH .
#define xjkJ ;
#define PFuD (
#define KV7o 0
#define JVI3 clear
#define sVRE ,
#define JPRW parent
#define bF0z A
#define eBqG =
#define ZJVM n
#define pvEJ ;
#define KWUS auto
#define uJIn m9vb
#define izk6 ]
#define yKnO >
#define UIuY ]
#define UToT u
#define jRDM =
#define Sk18 ;
#define XrtJ .
#define DHiZ ;
#define kAX0 int
#define nurp ;
#define YXzK <
#define lBiW return
#define Tp2M }
#define m844 {
#define MlIn >
#define q5lD true
#define Y0XH )
#define PPin )
#define Iuah :
#define cxLz }
#define VbVa ]
#define mXKP const
#define aahO aiHI
#define YzTF }
#define hH9P back
#define lhnU st
#define tTKA ]
#define xH6f ;
#define QUsT ,
#define r833 [
#define QAs7 )
#define mRRW ||
#define IOcF (
#define xMl6 )
#define FCx6 active
#define afPZ [
#define n3Vl )
#define QpCQ {
#define Qyz5 u
#define TjkE )
#define cIQU vt
#define SOCL long
#define mtub for
#define GK01 (
#define fak7 push_back
#define jlZY {
#define r8Sy ;
#define lWXO [
#define rgNJ ++
#define gLsv ;
#define FyA6 )
#define VqFT L
#define ZjKF <
#define rZfd .
#define iS9P )
#define Uqgb (
#define uaFM b
#define wgBb int
#define Z3WW col
#define ygtc +
#define AKwo =
#define HtRd (
#define _YhY )
#define Uof9 tout
#define msBR )
#define rBgk vector
#define axRA g
#define Tjt7 ]
#define mmHk (
#define LAl9 [
#define aMHM ]
#define Vkl8 vector
#define vp7p u
#define hUhm .
#define fKuM is_ancestor
#define yOHN ]
#define fXjC 0x2852430000000000ULL
#define qX3e (
#define tKuV ^
#define fLG1 val
#define jnuH ;
#define XKhp >=
#define IViY .
#define QxPO tin
#define ZZdA )
#define mqLC ;
#define jy3y ;
#define vggq ;
#define KY7M [
#define GYMu Aavf
#define JMSd (
#define kURK vector
#define rKOK stk
#define tp7F long
#define uTkl B
#define fXcX parent
#define tvJl int
#define IUCi vector
#define iy6H tin
#define wCXE +
#define KtyQ ]
#define mDOA oXuA
#define AMh3 int
#define dEWO int
#define K5Kn <
#define Ww6B .
#define HTgi is_ancestor
#define iDkN ;
#define pNEP [
#define ZkvQ col
#define pEha (
#define lvx3 size
#define y5KN }
#define _46s ;
#define xo2D )
#define wkp1 =
#define oJCb )
#define VLm5 (
#define NEms present
#define bSQY return
#define u2qS int
#define TXHF )
#define KWo1 1
#define OGbC st
#define ZuAa ]
#define FTYC nodes
#define fyYB (
#define FMVC s
#define hvfD )
#define DWXk Ru1G
#define z3We )
#define eeAz )
#define bz00 .
#define Cxs9 ^
#define fh4e ;
#define elPd (
#define ZXH4 >>
#define It8X isCut
#define iZVV long
#define vfm2 sub
#define lknZ -
#define _fCn )
#define R2hd int
#define O8Lf 1
#define E2KK pJOX
#define tYPi (
#define kogP ]
#define f5eM size
#define Encz }
#define GaRj int
#define JI3O else
#define HFgf ;
#define Wktk continue
#define j8ni (
#define SWkn ==
#define kQEd ]
#define uMG2 <
#define Bh1Z k
#define fg9O MmgJ
#define L0C3 ;
#define Ry6W vector
#define SmNF t7lQ
#define DgbL if
#define vfkS {
#define q1lt size
#define AMUm {
#define yBJ0 )
#define RYRr (
#define MlsI visSum
#define wb8j (
#define PQfF nodes
#define Kno7 )
#define Nol2 )
#define yWJu push_back
#define esf6 )
#define Xjp9 (
#define swQA )
#define Klrs )
#define zZ9K vector
#define kzz0 >
#define RGLB long
#define Rpq2 pick
#define Nt25 ;
#define beyU >
#define x6Oq .
#define mXPC &
#define cW0V ]
#define bXFg )
#define rZEo u
#define dQYH (
#define gL44 n
#define r7n4 int
#define MqHL (
#define Rg2L {
#define OQA8 int
#define s2AH (
#define DkLV -
#define Q5gI long
#define s2SH for
#define l8hQ addNode
#define HjzQ ;
#define EQdm [
#define ebeT int
#define MU0M (
#define lt45 ^
#define YXeL 2
#define uKUT u
#define tCCh for
#define JUa9 ]
#define Kyng +
#define wSQg ;
#define pSdw }
#define dHJv unsigned
#define r050 u
#define MKF4 +=
#define tflM ;
#define aXkm )
#define wxUb nodes
#define BR3f {
#define TzfM Wx9a
#define EnDS {
#define PSgN k
#define vee3 (
#define T7lV vorder
#define asEZ )
#define Wng2 ;
#define N5of ^
#define wqKB ++
#define mc4E Wx9a
#define hE1g (
#define plrT (
#define AQWk (
#define _EeA ;
#define Kvhy int
#define OniC ]
#define MqJM +
#define Kfdq ]
#define JdOI (
#define zSFl (
#define yVea push_back
#define RMmF n
#define p8gF (
#define m6Wi ;
#define co7s ]
#define KK3T ;
#define Fcti unsigned
#define XaVl )
#define F9VD st
#define I5zo )
#define K2ZV used
#define gFe4 itIndex
#define awNM v
#define dhCi )
#define DJA6 ;
#define xFm8 )
#define MFAS size
#define KfQC v
#define GSJw {
#define O4T2 present
#define O3KX ,
#define gdI9 int
#define b3Ki State
#define j1uL for
#define Zz21 n
#define PjLs vector
#define o2LT st
#define ys7h int
#define VgCD k
#define AvcP [
#define Aa2P 0x78ffac0000000000ULL
#define gAGP NbtL
#define mOyl ]
#define zucG static
#define unZC }
#define _vDn =
#define uTB2 vector
#define NPF5 ;
#define CXwD unsigned
#define TqDw [
#define Ya31 fxZV
#define H83n (
#define kEI9 1
#define MHZ0 (
#define kbTP u
#define OIfp [
#define ErNE long
#define ywUo ;
#define lr0N t
#define drUC 1
#define aQoE sub
#define Ki0D 1
#define lCYp int
#define YoYj 1
#define c5tm ;
#define bq1e 1
#define iSFP long
#define epII visSum
#define ZSSD {
#define uevz size_t
#define TQfq )
#define CJTK push_back
#define o0MR 1
#define Lbq5 (
#define FxG7 _OcM
#define rnGi ]
#define MiTC 1
#define UrjO .
#define GYK6 ;
#define fHJ1 st
#define v1Xj u
#define CIgJ depth
#define eM5l long
#define r7LY empty
#define kaqk .
#define Ndfw ,
#define IQLe (
#define lQHt ;
#define ukzA (
#define syxK <
#define T1UP >>
#define UMkS .
#define zqFr (
#define jfsP (
#define TjK1 .
#define ItfV ]
#define jlLo ;
#define UZj0 )
#define k52c .
#define nSSn c
#define wBhP Ru1G
#define jjSP (
#define qfWL (
#define s8g9 range_add_subtree
#define WMZj ;
#define uyOM <<
#define rPu0 ;
#define mUCs (
#define pEPk (
#define EekU 0
#define YsLg )
#define qj78 )
#define EcYb [
#define MqcE vector
#define pdZ1 eulerByTin
#define W20P ;
#define gbbF )
#define z3O6 (
#define YoPw )
#define M73r 0x2852430000000000ULL
#define UMtd ;
#define vHmX :
#define DUiG (
#define nDs6 !=
#define w2nz =
#define f4Bf int
#define I8c8 curSz
#define FOhh )
#define pLjQ int
#define Vo0F )
#define MXXd <<
#define wKkG active
#define WdQp constexpr
#define O4Mk (
#define ilp0 )
#define yBgn int
#define PTbK {
#define jpKl is_ancestor
#define C9JI .
#define rbW1 ]
#define jy7D ]
#define kuNl [
#define tkJG (
#define Fyar )
#define j5a5 >>
#define b02u nodes
#define Dy5P ;
#define lurp =
#define BrR9 =
#define SXXy int
#define kDHg u
#define XsfG (
#define rDKQ )
#define ZAyd =
#define H9fU :
#define pc0d ,
#define rokz int
#define HX5l <
#define ebRG (
#define b056 present
#define _1EY vector
#define Cks0 ]
#define rbbH size
#define bO8f long
#define no9P ,
#define LUD4 )
#define R50N cQP9
#define Uvo2 &
#define rkQl ;
#define eqSy ch
#define fGB6 }
#define g84a depth
#define w4O9 [
#define fWNG .
#define EzY5 1
#define lQdJ -
#define QQ4v ,
#define XwF4 k
#define ypuO n
#define ejLQ )
#define OoKc .
#define Ba4y ;
#define sUvy Ly7A
#define YTjI ;
#define rK1l >
#define tbwB (
#define UTdK Ri7E
#define EQM4 ,
#define FwaW (
#define pwjq A
#define U0Im vt
#define Orab col
#define Ywn3 eDre
#define Kn1o k
#define C5gh static
#define LzVp ]
#define JDkg long
#define xGgF itIndex
#define YH7n -
#define ckom ;
#define aGpr )
#define Hwfz n
#define NAb5 j
#define pnrR .
#define U517 )
#define FsqJ )
#define GSvj (
#define WoJF ;
#define _0VM u
#define Hsqc (
#define gJWB y
#define Mauq =
#define tmBo }
#define IwKf h
#define EHQu back
#define wMK6 int
#define IZWt if
#define Lq4M ;
#define fvFO order
#define d6rq ]
#define GV5r u
#define oNcx (
#define qQVB }
#define p0CI .
#define kTWx ios
#define OLyP ^
#define YSiQ vector
#define UENt 2
#define k8Hu n
#define RSvv i
#define Ypv4 )
#define AunG (
#define dQyI )
#define AATW 1
#define vpAT int
#define sYjc .
#define EjZc (
#define FAcd long
#define W1Iz }
#define BD2E )
#define dfg9 )
#define FysZ HqQA
#define JS83 stdc
#define XHFT v
#define ecTA (
#define PgDa ^
#define Ca3N )
#define WhkK .
#define Jd4b vt
#define Iw7b )
#define QY3w ;
#define T0O4 =
#define MCpt n
#define IPdb )
#define l1Pm ;
#define vBQ9 (
#define YJDa )
#define Iju0 int
#define g2uK [
#define nmPy )
#define GVux diff
#define _ptg uRA2
#define DLxq (
#define Kl3h &&
#define FtGA ;
#define EXRP L
#define cAIP long
#define M1Ll (
#define WXT3 )
#define AeD5 )
#define GIYm [
#define oyvK )
#define aCHt &
#define QGS3 int
#define X0ZA order
#define uW1J =
#define gotJ long
#define okYM depth
#define JqHZ [
#define Tqdl )
#define LgRw u
#define OuMV (
#define psP4 )
#define _FLn (
#define r717 [
#define TvxA long
#define UKLq }
#define dAFH (
#define N2a6 }
#define mBeo tin
#define qkBA ?
#define S46Q ;
#define E50s c
#define nEDE int
#define phi0 .
#define GMYG +
#define J1Jg curSz
#define fz5Q used
#define MXzW nodes
#define Y7k3 (
#define uCFB (
#define VVWj Ru1G
#define jYQv vorder
#define clXh if
#define aNfC ;
#define IVM6 >
#define CV89 ;
#define rWHC [
#define Z14Q ;
#define pkz1 int
#define jNtz [
#define YMRJ )
#define c9Mz ,
#define DUKD {
#define nzme ]
#define kAmJ )
#define Weuw ;
#define IIg3 ,
#define g5D7 {
#define jx4c QgqG
#define aqfI tout
#define njbF 0x2852430000000000ULL
#define qJKe up
#define pp1x }
#define OSeL u
#define uYxc long
#define RzXS v
#define RseZ <
#define KzqX cout
#define dMKJ (
#define EYAn g9rY
#define vsq9 a
#define mzcE ;
#define P0Ux ]
#define Qulr 0x2852430000000000ULL
#define eDM1 0x78ffac0000000000ULL
#define MTzB =
#define Gqes size
#define V7sK ]
#define iaYP )
#define Tt86 vector
#define hJY7 pJOX
#define I86P eulerByTin
#define B1XD )
#define irJp (
#define tzqw u
#define ZBD1 if
#define p4L1 !
#define VLbE ;
#define AGYV }
#define jJK9 if
#define bQZt ]
#define aKem ;
#define MpIg v
#define eRKb long
#define Dj8z ;
#define sQtW cin
#define Jc2K ==
#define GMsn )
#define zLAO n
#define pF7C Wx9a
#define unmG .
#define ONiA (
#define tDtR )
#define vRUb (
#define YQ2Y ;
#define UXO9 [
#define ZWhI if
#define owl7 ^
#define Oazf 2
#define wcWS {
#define wRAE .
#define IWKT (
#define BYag 0
#define N0RP n
#define oXwQ ]
#define Ciji )
#define ohAZ isCompRoot
#define gjB3 b
#define qmv4 (
#define eps8 if
#define Jz7n laYZ
#define si6n Wx9a
#define Jz8d )
#define YtNu s
#define qPHh ;
#define WVgq ;
#define u6JN (
#define Hhoq st
#define _g7q [
#define wais ]
#define lD4H ==
#define DsSB <=
#define zYoN ;
#define y4rA cin
#define fJoJ ;
#define i1Mj n
#define wxXc long
#define LfRB ]
#define TjNz int
#define kTzF ]
#define lZm8 =
#define oxj7 timer
#define vbEZ laYZ
#define b7jE ]
#define Jg8F 0x2852430000000000ULL
#define WE2D ;
#define dHKT )
#define LJBD (
#define QD6C int
#define jVHo =
#define aIl6 col
#define feF7 )
#define wICE ]
#define jnPE (
#define V0qE for
#define LqEh (
#define ZUOj )
#define XmdP (
#define E8LY std
#define ZC4o )
#define UZiH &
#define dCj5 (
#define krot (
#define NQN1 =
#define jJkF stk
#define Io5Y pop_back
#define J6d3 }
#define j3Q7 [
#define TtKD [
#define zjuL 1
#define Kphx ]
#define REPX parent
#define CALy 1
#define XIF7 (
#define SEH5 =
#define yqGo (
#define DIcs laYZ
#define oHWn return
#define iIhs idx
#define k61C A
#define EUYS *
#define JXid st
#define jMQ2 ]
#define PPIH )
#define bzLC (
#define dUGC ||
#define pGE5 WHwc
#define GuWu ^
#define cFTC tag
#define yRFT static
#define cGDv (
#define J2v8 )
#define ZHYo auto
#define VRZp (
#define cwLX ;
#define Ikr9 )
#define rzEI uRA2
#define bFKs mid
#define qOKN !
#define JJQf st
#define l4nd >
#define VE9A ]
#define l0bZ ;
#define G8sF int
#define gMZ7 ,
#define PQ9g addNode
#define DWI9 =
#define acMX Ly7A
#define CpeV 0
#define WHvM st
#define pAbW vector
#define tmEQ )
#define Enfm )
#define yaba oGiP
#define mG3D else
#define hEJQ .
#define ASTe visSum
#define AKvp (
#define Qjuf ;
#define XD59 long
#define KfwC ]
#define KwJp return
#define xJpF =
#define _XYW long
#define GYfB >
#define jtm5 ;
#define H5C0 ;
#define HHnE ;
#define DLA7 nx
#define sD0f <
#define HFvF ;
#define zDMB visSum
#define XOEZ for
#define LVLw )
#define nwCg L7Wz
#define WYSo v
#define rfFV .
#define VxAi u
#define _lG1 long
#define YTH1 addEdgeVT
#define Y4v9 1
#define CLmP =
#define qmcu &&
#define LjTe 1
#define J7jj ]
#define dC0J depth
#define SkVM ++
#define b6NR )
#define Rrkz c
#define snjU unsigned
#define JJZY (
#define X57S maxColor
#define SHXp long
#define nw0D 0
#define b9ma (
#define yf9m (
#define sxKt (
#define ZquT u
#define M5aM st
#define pW4W .
#define RPqF (
#define WpaR =
#define vj51 )
#define aatf u
#define wQHq ;
#define ryly }
#define ZFjj )
#define rkwt .
#define WHEY back
#define nPJD {
#define qDKz ==
#define M2CN 1
#define e795 ,
#define Qjmo )
#define byMb struct
#define AduF )
#define KqjX (
#define F8F1 ]
#define YZQT parent
#define m0YB (
#define kbA5 (
#define LRVM MmgJ
#define YUqt {
#define oYQ2 [
#define x8br pick
#define EP3J [
#define mQMU u
#define lKHs s
#define pxQP n
#define dd2P )
#define nEg7 addEdgeVT
#define sDef )
#define Kt1y bits
#define sTCB 1
#define fgwa ;
#define dSJr (
#define A7Ds int
#define RnrL (
#define Jb17 dAI9
#define Nifl 0
#define hzO3 (
#define OhJG .
#define xqoU push_back
#define iWLU )
#define Xne8 {
#define fb5l MmgJ
#define MUDo +
#define m29r long
#define WxsA u
#define KQEx ;
#define l9cH ;
#define Whed )
#define JcEL 0x2852430000000000ULL
#define bNUf ;
#define Ocyw run
#define eQHM ]
#define j9dh -
#define jwSj ;
#define aNTy up
#define M5yh mid
#define a2ZB int
#define TfI0 0
#define JYmw (
#define PCYG for
#define PgYy st
#define VLUu (
#define N74i ++
#define BOu9 ++
#define rBvN ,
#define TwyF if
#define FaFY ;
#define rFZK !=
#define q2OG =
#define RleT u
#define a9mC ,
#define fitm char
#define XZpk )
#define T85Z int
#define TdgR =
#define tL9D )
#define IPGe )
#define Z7Ul nullptr
#define N60l push_back
#define mlib #include
#define kAmR )
#define A1DB )
#define ixPE )
#define g7i8 ]
#define NswW ;
#define ct7m 1
#define QG4O S
#define lxCD )
#define p793 col
#define acjz [
#define RLYT )
#define pYeN while
#define mi9N order
#define BA97 <
#define e8u4 ;
#define Vcil )
#define heBo -
#define SKca >>
#define MenB (
#define rNSN =
#define NLVO ,
#define pJhP [
#define Vaar >>
#define kPUf .
#define nyG2 [
#define IJkd pJOX
#define b8dk push_back
#define ttMP 1
#define v9rF ;
#define uQhj <=
#define yFcX unsigned
#define ZnJA using
#define Y6ud u
#define Gz9v )
#define _ZpS [
#define hvDA <
#define VdYA [
#define dL92 (
#define zKke u
#define Gayn &&
#define viAa ;
#define IqCl ]
#define NhYk ;
#define xhbL while
#define K0kE 0
#define VZWo addEdgeVT
#define Vlgy st
#define Vjqg while
#define vvsz push_back
#define HTSZ )
#define NqTs int
#define qHYv [
#define rAnB v
#define GGTV )
#define Tpju c
#define g4uj rootsOfColor
#define f1Ms 2
#define Jp0g up
#define Inkn int
#define CEfe )
#define sDvS ;
#define l3eE i
#define e2gC 0
#define dowi [
#define ykEn Wx9a
#define XFsD [
#define htTt (
#define R0ss i
#define IZim )
#define jcxA ]
#define IHKa )
#define eoRQ ;
#define gfsk {
#define mHmt <
#define p3Ej )
#define kcp3 <
#define YKMV L7Wz
#define V0ve (
#define W9Jt int
#define L7o3 Wx9a
#define rqOM ;
#define LiCR ]
#define v7AL auto
#define t5KT (
#define H6Iw JYcs
#define _Nn6 <
#define YGRw <
#define Rkx7 int
#define Ut0H pJOX
#define Jj0G )
#define Ppg3 tag
#define R1LA st
#define qD13 +
#define AkTN ^
#define lo1D "\n"
#define QFGF nodes
#define xlnw =
#define OfqF push_back
#define OInY false
#define RD7C ;
#define yWyJ (
#define e8Ut (
#define gOl3 stk
#define iDfQ k
#define KCMB +=
#define jlvd )
#define iq7y push_back
#define yB4v .
#define pNhk (
#define U0fZ (
#define z0UI else
#define EWtg u
#define diMr (
#define P2Q4 long
#define qCNT vector
#define xKU6 *
#define B6iB back
#define SYs4 >
#define _ioq <
#define BCut size
#define Uckd )
#define UnNi :
#define W8dO --
#define SYTw up
#define HYJX ;
#define i37w int
#define eitB )
#define eaFA g
#define zxQZ )
#define L1kL mqYh
#define TCC0 (
#define IMRp <
#define vg7u 0
#define QGgB curSz
#define V8bC depth
#define czrf ]
#define NkoP &
#define Hzj5 {
#define SvGu unsigned
#define TyKV i
#define UZXK (
#define _u2X >
#define BwXH [
#define lgEN {
#define tk48 (
#define ByAk +
#define YZpy vt
#define bDq8 )
#define A1l0 B
#define ILh5 u
#define mztK ]
#define CIBk (
#define XH1E [
#define bgNK }
#define T7cN )
#define MWK2 for
#define NVpd c
#define LC1z >>
#define PzRZ int
#define iKdm ]
#define x5nE S
#define Ku1J .
#define tzAC (
#define TTEC +
#define H95H )
#define M2d2 ]
#define xAgV <<
#define Mc8V u
#define OaJy (
#define nsdg vorder
#define tW31 back
#define dmVp [
#define hwuR idx
#define FMAz ==
#define dUBI )
#define m0YX u
#define M8ec .
#define G51v [
#define aozV u
#define PeUG reserve
#define ctAP 0x78ffac0000000000ULL
#define Ygdo u
#define qP5d (
#define QWq4 [
#define tJw1 ^
#define KhHR [
#define RM98 +
#define qiWw oGiP
#define OPX4 -=
#define Dlfa st
#define Sl52 ;
#define bae7 (
#define wyrs active
#define GEOT Ru1G
#define ZF9o [
#define c6t9 [
#define RBBp ,
#define kQrY colorsPresent
#define sSuE <
#define vmjL u
#define Iihr }
#define Uqlq st
#define tmjv size
#define D9GT push_back
#define x5p0 st
#define evlF rootsOfColor
#define xGBY ;
#define lKDO <
#define Bn93 B
#define gWih (
#define _SUd while
#define UpqE long
#define MTom )
#define Y4ND +=
#define ym9a vt
#define _ZW4 cin
#define gW4f long
#define VsbL .
#define JS52 if
#define d9BF ++
#define groB u
#define Hm3N g
#define CwhP (
#define blcn (
#define ufWH )
#define L5hP (
#define LXKU ;
#define z5yK vector
#define JS9R g
#define upJ3 active
#define NgYZ u
#define pR0x used
#define LU0S )
#define mXJi =
#define G80W int
#define dz7J .
#define l6y7 +
#define dtLt int
#define GSje [
#define ObGP ;
#define tIVf n
#define mLA7 ;
#define VdqZ col
#define nIji val
#define ImB5 [
#define izd9 [
#define CGgJ int
#define zU7X nodes
#define wmXL <
#define YTEI ;
#define L1Mc 1
#define pcUA push_back
#define RZGf long
#define cZhS [
#define hT6o 0x78ffac0000000001ULL
#define cXl1 (
#define P0gu [
#define jZ9Z long
#define auAC continue
#define DSIg 0x2852430000000000ULL
#define j6iN nodesOfColor
#define EkPX st
#define KGUu )
#define jWJd )
#define fk2c 0
#define UAyr if
#define FMuj [
#define VhXb )
#define yjv0 int
#define XaIu )
#define vz20 )
#define c0ps k
#define OcKZ ;
#define DXwz idx
#define v7Nv [
#define LZsf )
#define mKWz size
#define NJNf ]
#define xCnJ push_back
#define wu04 ]
#define xkRE )
#define faBz .
#define cvtm {
#define oKwz >
#define jzxa vector
#define C4Ww long
#define InBq xe8k
#define q1LT (
#define J1Gs )
#define l1Hk (
#define c7EK (
#define nvmj u
#define ctvB =
#define xksZ ;
#define pf6J st
#define UNnr if
#define aT2r ,
#define BvbR push_back
#define OvP5 main
#define vcNR ]
#define _7eS vector
#define V7Cl {
#define TAtL =
#define K2SG ++
#define FvC5 b
#define q2v6 st
#define RU7P [
#define mALW )
#define d2RA )
#define q6Bd long
#define SDY1 vector
#define vrla (
#define ASGY sub
#define SDxf =
#define op0F ;
#define MvrS ;
#define EBPC (
#define k4dN (
#define Ed5r unsigned
#define OSDU &
#define SOGG =
#define yqJY [
#define WxQZ ,
#define r3aW i
#define LtFw [
#define SNr4 <=
#define zKph g
#define zXko b
#define MeVa V3cZ
#define ZoeK Ly7A
#define JqHd =
#define r5Ob namespace
#define yCp4 int
#define TW5g =
#define tZET int
#define Ttwk (
#define G55W ;
#define ymWN 0
#define kYZT +
#define sQTC ;
#define yVfi int
#define HsNH >=
#define zbrS (
#define Z3Fd )
#define vQFq (
#define EvZf )
#define JXpn return
#define xp4L (
#define tBGi constexpr
#define EWhq =
#define nSDj [
#define EvAy }
#define iWxt ]
#define dHTS <
#define OIZI isCompRoot
#define RU6h )
#define Stvi 0
#define w9KM =
#define lPmu vorder
#define Pigt =
#define KHog hjXn
#define aoJr maxColor
#define O8eH )
#define Ew3f long
#define aCkT ;
#define C2Tq u
#define SlfN QxfT
#define prdt vector
#define LQQT fuHd
#define CjqP unsigned
#define nGWk 0
#define uQoU ]
#define Z8qV (
#define eujB size
#define Jztw 1
#define FZft [
#define jWtQ ,
#define dwkt long
#define at6s }
#define RdGG +
#define C5yP false
#define yjOW .
#define jlRV .
#define LD2j )
#define cVmJ 0x2852430000000000ULL
#define kV8Z ;
#define QS62 int
#define FHRk [
#define Z0yw [
#define lQZ6 .
#define uxe4 (
#define wFbO }
#define Gbqp >
#define n2Zz ans
#define O1D4 curTag
#define Pc1g gzjr
#define sKbF long
#define iOL2 for
#define wDdk long
#define gPq0 ]
#define inRN push_back
#define ePj5 ;
#define TpBk continue
#define H7ra x
#define GhDa Ru1G
#define k9iJ )
#define prLi &
#define iHxm col
#define pvDW 0
#define xnEL -
#define cwoZ vector
#define KUrs (
#define mBSe ]
#define _dfC col
#define KjPA itIndex
#define W2xZ v
#define Z7OY }
#define FAJF stk
#define mK6K 1
#define o13y Wx9a
#define YVeD )
#define D6n4 (
#define hWDM reserve
#define syjF curTag
#define bMoB )
#define FII7 (
#define Xnqa )
#define pGNn st
#define vsVu int
#define rbRQ [
#define fRKB (
#define PbEW st
#define WINO ;
#define E13r ;
#define EaVB u
#define HUos =
#define Nh4S pJOX
#define NDP9 SH5f
#define Jtws ]
#define uXPE (
#define nnuL )
#define Mpaz (
#define yFW2 ,
#define uTrm )
#define lL7O Wx9a
#define sN88 (
#define Km2L [
#define e1JN ,
#define V4Dn =
#define gJLF )
#define SoUx parent
#define tG6u v
#define iQqT <=
#define rx0o reserve
#define tLK4 ;
#define LLDK )
#define aY9j [
#define XQf9 size
#define d5OR )
#define ghYT g
#define SnWj int
#define _ZnN size_t
#define YJPQ for
#define FrBS long
#define OANs st
#define BKMp {
#define Q2X4 j
#define uIjU ,
#define teTT +=
#define rSHV int
#define Qbds ;
#define yOSM u
#define cc5S int
#define HH2z ]
#define go7S +
#define qSuz for
#define p9n9 v
#define _cug OF8D
#define _Cka +
#define wx4H 1
#define H8Sr false
#define IzjE [
#define GUOO )
#define doJu 0x78ffac0000000000ULL
#define vRWL .
#define tr4B auto
#define ngmc u
#define Ao6g (
#define keKV )
#define sQL1 )
#define huJr ;
#define rdty ;
#define eFjl -
#define toXC v
#define oDZh h2z8 tBGi T7MI jZ9Z QkNY Aur7 qkak GzGI sDvS C5gh WdQp mTTW wzm3 SOCL rD8E q2OG DSIg pvEJ yRFT MBgA
#define Pw0b snjU _lG1 gotJ o13y HUos hT6o KE6r mlib mFRD Kt1y Cgbl JS83 M5wr XrtJ IwKf fLTT ZnJA r5Ob E8LY Wng2
#define j6Pc zucG mXKP XVZp jx4c eBqG YucO q1LT AMh3 Z3Fd O4Mk UH7i VJSo CjqP m29r aBni VhXb GYMu ixPE Lsgb PN4p
#define sCQl Klrs QAs7 MvrS IKc3 OvP5 TYnZ jw0h m844 kTWx t4QT r6o0 JdOI H8Sr mYyn OylE Zn0z wRAE Swp1 t8ej Z7Ul
#define dd9Q mALW erJc ntzL ud8U nqGQ _ZW4 OSUh PpQm cwLX eZQX hvDA Inkn F7ha ZkvQ gtaO zLAO MUDo Jztw z3We UEHk
#define uY3S TjNz EYAn rYW9 bCMj RnrL nz9a IPGe k4dN GSvj J9lF JZxZ jFdF _XYW gmDU GEOT qdad GbrP Qulr YoPw Whed
#define jqua LXKU PCYG Omxr FcJE twSQ uW1J M9Gh VRZp JHap LLDK LJBD _Foo bzLC Fcti ej2R ErpJ c9Y7 L7o3 Ypv4 owl7
#define KVnE D78g p3Ej POm0 z6Sb qiWw xfqQ oG1c zYoN yaba wqKB VLGc mcdB sQtW ZXH4 p793 oMBP r3aW yOHN FKGg RA1y
#define vVRq Ne3B uFjp AunG X57S sxc7 Orab EcYb l3eE wais LU0S fgwa qQVB JJ4v tDn2 uC1p gY7t Zuoi T1UP JS9R Wrms
#define adXv I8Ge ByAk Nz0F Enfm iDkN V0qE _FLn ttPZ YKMV JC19 YX4d ebRG wgBb Ca3N plrT PV8u qP5d w97i wxXc bO8f
#define jjX2 UZj0 VVWj S4sI tJw1 BilU zhI7 AFx0 H5C0 nwCg yddE hJY7 PvDt IWKT KUrs QGS3 Mh1Z uxe4 rlMl s2AH D8FC
#define fmYG FrBS RPk7 zXax ykEn kAmJ jpUp eDM1 WXT3 TjkE KhdZ KVc5 d9BF TXHF ZSSD T85Z NDP9 pc0d x4hL G55W y4rA
#define wBwJ _yuq Py0z Vaar MfBK yvlL zKph qHYv C6dY G9KZ M8ec D9GT vBQ9 gJWB EvZf DHiZ ghYT rWHC AfSO czrf rZfd
#define DUlA xqoU YThZ H7ra DyKx mLA7 Iihr wd3q rw7q TdgR m0YB X3tt kAX0 HTSZ Y7k3 MtYT vrla dHJv QRu6 gW4f rUd8
#define DY45 DWXk d5OR ifB2 M73r Yi0w vCP3 IUS7 _SUd jXtQ _5ZJ pFqF pOe2 dEWO Nol2 p8gF dL92 R7SH VXqf iSFP C4Ww
#define gjY4 GMsn mc4E fS83 cnHI BHn6 yBJ0 IZim uyOM fb5l KGUu DsSB Nh4S Qjmo fg9O SkVM yEkV Vkl8 zZHM zZ9K jI8O
#define e4wd lCYp j5a5 SYTw H83n nw4i KAlQ z5yK P3mS wTXD maIK uCFB N0RP _Cka OIdg xjlM Nifl jlvd Y0XH r8Sy _1EY
#define Dvw3 RQVJ vsVu l4nd G5Ho D6n4 tIVf ygtc bq1e WwwJ lUom Jj0G tOWa dC0J _jm2 ypuO TTEC z1Kp rBvN CpeV gFqG
#define p9DD aCkT Tt86 IMRp F4Lc Gbqp iy6H tbwB RamZ XOQM O8Lf aT2r OrG7 aGpr NLVO ZJBo dpeT RMmF go7S ubHX a9mC
#define XoIQ YUxX vz20 NmRC I86P Cu4L k8Hu VuVY hWF4 O3KX UGwY nwZH rkQl uTB2 wmXL Kvhy rK1l vfm2 PFuD pxQP hecZ
#define yDAb RIVz YXfM gGM2 R1OG jnuH a2ZB gAGP tAWr b1dG sN88 cc5S Uckd k550 bae7 MEjw HoaS r9Iz iZVV XZpk _ZOf
#define FsSk BD2E lt45 fXjC VlrE FOhh rpz0 QDgH SlfN YUqt BKng Jb17 YyEt uMNK NNXR _bGP l9cH mn16 c5tm cwoZ PQsl
#define nUqy NqTs acIm qAPk diMr s5yF kYZT KWo1 L08k ymWN P8KR WE2D SDY1 _Nn6 pkz1 beyU L1kL kV8Z pGNn qh56 Nqcr
#define IL0y yqGo MCpt iUKr Sk18 F9VD v11j iq7y pEha J0FY OtzI qoW6 kMiC lWXO mpo6 oXwQ EWhq BYag BwqB g84a KhHR
#define piGu CALy izk6 jRDM fk2c xH6f jzxa YGRw yCp4 XxI1 f3MA m6Wi fvFO yAXJ PSnC ecTA Zz21 J2v8 Weuw QEUL GFRB
#define U6QA qOKN PgYy j0bH O8ii IQLe YMRJ d2RA lr8D yVfi k0EU GZy2 OANs hEJQ XRSD Dbgh DiY0 YTEI eps8 ZKyB KjPA
#define u7ez ysLW r050 ZuAa yJNg vg7u YwLJ vfkS QxPO ImB5 vOat P0Ux Mauq K3hS oxj7 aNfC Pj4q ZGeb i5ve J7jj jEda
#define SaCA NgYZ GYK6 aNTy IzjE Stvi gPq0 ZJMY EWtg Jtws wOvN r5qo rbRQ m0YX shvm Sl52 fwJJ CIBk O8ck iDfQ U74V
#define en6N AATW wWSD Kn1o YXzK Tv7l RD7C XwF4 jXka RU6h nPJD CGgJ bFKs V4Dn qJKe nSoY c0ps Fdu9 YoYj jy7D nSDj
#define JcHg LgRw YoNI NHsD X2da yo6u qSw6 Dcun lshw PrFM gQWB mqWb JMSd M5yh qkBA Jp0g s1nr PSgN j9dh ct7m E0bG
#define lxh2 FMuj oU9c d6rq vHmX pvDW LnOO jlLo pp1x BtdG XgCn vRUb xGgF _ZpS rSt1 nzme qQQJ tk48 A7Ds KlPs axRA
#define BHHA jaAf D1J1 rbW1 pnrR mKWz tYPi wNkm eeAz BKMp rokz MpIg DWI9 eaFA pJhP yOSM iWxt PGiK gFe4 EQdm Ygdo
#define JtNX NxNM BOu9 jcxA YQ2Y Qj5X pUi0 Ri5k qDKz REPX GIYm Mc8V V7sK o7ro Wktk S8fB jqzV eyGq toXC V07Z s00c
#define vac6 groB v9rF okYM c6t9 xXwJ rFyK wZVk dVPU pNEP OSeL y3nE l6y7 MiTC Kmkz Qlc1 dz7J yVea UMXw toWF k9iJ
#define WmsJ mzcE ryly mG3D wcWS mi9N EcvD QbkT c7EK zKke opOa tflM aqfI YzRs KeqD EGQ8 zbP7 Qk2T _ISb q2v6 Ww6B
#define vNSO ZZC7 j8ni keKV M0WX o40R wFbO iOL2 sDoI GaRj C2Tq TO76 X0ZA oyvK EmP5 YaD1 q6SU BrR9 mK6K WINO XOEZ
#define IPvK wb8j boES JPpf s3Tu Hm3N BwXH Qh7D VbVa O8eH Hzj5 UAyr XIF7 tG6u FMAz SoUx k0MP RleT ItfV ilp0 auAC
#define UqVz lQHt FMVC MKF4 aQoE IPWk W2xZ LzVp r42j niDR rW6Y DqIe ILh5 Xrr4 ctvB YtNu Ba4y cxLz tr4B da2s db3i
#define kEPu TtKD Tcuh DqeD Xjp9 tZET FxG7 CQQl LtSU y3vG Tqdl FqcQ Fm5d xDM6 qYXI WG6J ek0H iQqT wrnN nQrH FvC5
#define QvgW NJNf Kl3h Uof9 j3Q7 uaFM IqCl CkwE Mjkt acjz RtZH mOyl vJWO bFs3 UpSe whvH FysZ w9KM UhwV gJAq gubk
#define eqPW Uqgb EQeN UkWJ EQM4 gdI9 gOJc nnuL qpdp ZBD1 MqHL jpKl Bkxx vsq9 WxQZ gjB3 LVLw _YhY JXpn UF6E ExjL
#define lSpq elwy JYmw HTgi GK01 zXko QQ4v laC7 uTrm dd2P aW6r R50N KQWQ wMK6 _ptg lZm8 Fte8 zBqo l1fE hE1g i5kk
#define gMNS DIcs SDxf LRVM DkLV Gd2T Mnzk r7n4 T92P ukzA Vhlf MxiR Ed5r bXm5 UpqE ejLQ si6n vj51 OLyP kwf2 gJLF
#define Y2AM hvfD viAa Jz7n XKhp irJp rtn1 pLjQ LxWD zqFr CvY8 EBPC NwJk eM5l Q5gI swQA GhDa Vcil N5of cVmJ cY7c
#define IoCL tmEQ fzn4 vbEZ W8dO PPin SuN8 LxNr QBS7 xlnw bYpq GUNL Bh1Z tHaO a7lc Y8MX VE9A _EeA JS52 JRkJ ktCs
#define _Ufv FZEK p4L1 fKuM Lbq5 DLA7 QUsT t2Zu Ovjn IPdb rzEI SEH5 Ywn3 L0C3 D7u1 jz6z jxpv jNtz vLQO BwV3 B80P
#define UUk3 fnpT gDop qU2m K5Kn oPI2 L5CB G80W XI18 j6iN zbrS aoJr GMYG zjuL RLYT VLbE h5no _ioq prdt PKdr G8sF
#define _4xq SKca evlF bnyL DRXu RM98 kEI9 JTnz j4N3 kURK RseZ fitm SYs4 O4T2 RUC4 qIlB RdGG lcOy RBBp EekU ergQ
#define mU0o fJoJ MWK2 lWWF f4Bf EUor TW5g qyVp HtRd OqDV ts0o cdCH tzAC e8Ut yFcX MfE3 JDkg bMoB pF7C IqBB Cxs9
#define Rtl0 Aa2P Ciji drPp KqFz EOUh FTgp E2KK Oh7y qnLM K2SG x7gf V7Cl yjv0 LQQT F2xD pdZ1 w1KT KmCL KZRH mWhG
#define HRgy NEms kuNl rVsb cZhS aatf VLx4 mBSe xnHQ v8W0 fs7g GSAt UXO9 Z3WW k17M kos8 W3Zq Tjt7 OoKc LLDZ H6av
#define ITqJ lDi6 psP4 bNUf UNnr QlpC YZQT wU3K CUFa uIQy zLkq QV8A JbF1 pchZ _g7q JPRW Z0yw VxAi _Vyn HsPY y24c
#define aImg aIl6 dowi vp7p jMQ2 q0NP Cm11 g4uj v7Nv _dfC Km2L au2s GSje uKUT AfyH wICE uhiH LjAT CJTK Frss v1Xj
#define Q0Rv Xnqa l0bZ W1Iz xMrv SvVi kcp3 FQe3 BryH _cug wSQg kQrY Ku1J BBlr qX3e Hwfz b6NR U7IR YJPQ fRKB i37w
#define gtlS ZUda TAtL wx4H nurp Rrkz uQhj TLJS gLsv JyML K9my HiBQ jJK9 ZR2U b056 JtC6 Yg86 FJaF Fyar ZFsx qTGm
#define bbN4 vvsz LyGi Tpju xMl6 DJA6 Zco6 bnlX UTdK AKwo _VU6 ndGf _7oC ufWH AzIU TXgn eujB aGLB YAzy UMtd MqcE
#define xxxM mHmt Cqoc eRKb MlIn GVux hnGB i1Mj MqJM lAyu dqYl e2gC dHKT FZqd veWb aahO lurp JqHZ NkoP tph9 atna
#define txyH rSHV MeVa e795 B8zO Ew3f H6Iw bdLi DEcg g7Eg veqQ hJZe yqJY KT6R rnGi aMHM teTT fLG1 KQEx HC2m QWq4
#define hPI2 icTF r717 WxsA cW0V unNB nZuu b687 OPX4 nIji rqOM tmBo EJqU qCNT syxK QQ6s HX5l KBRv LC1z YZpy pvfj
#define JsAL rMAS SaAT Ki0D zfv4 Ln1U PjLs sD0f Jzyh zvno Ppg3 FPre gL44 lVpF vBmt no9P dXfA ZUOj Nt25 SnWj pGE5
#define fzhN Pigt yWyJ _q4y Vo6v Iw7b i5AI AHp0 TCC0 kW1s uYxc B5as GGTV dfQj ZFjj xfd4 JcEL VM58 dQyI n4CH YSiQ
#define cCcY K58w OQA8 yKnO V9p3 tiKx fz5Q bz00 rx0o MU0M NH2a nmPy E13r Yplf uJIn en5b PMPQ mXPC avU0 sxKt gSsW
#define oWM6 KHog I5zo BR3f clXh LqEh cFTC LAl9 ngmc dKIu v45U XzY1 Kno7 QpCQ Bdeu pFMC mQMU LiCR JqHd syjF Fmst
#define n7IK cIQU fTeY EaVB iKdm jlRV JVI3 Hsqc tO5h HjzQ K2ZV UrjO inRN krot cKYe sDef aKem YzTF XjrG jy3y v7AL
#define SdMl Ya31 xJpF yhXy OSDU JUa9 JJZY XBVI QZbx mEip ebeT Pc1g XbF5 VBJv dz2Z I1uK rxjm uQoU UMkS b8dk qmv4
#define mCKP eqSy CEfe nkdM at6s zHAK _GDj RLDi TvxA RZGf kzz0 MlsI OaJy ZJVM RrLy EzY5 gMZ7 KV7o msBR sQTC UyLX
#define FaJX jnPE SXXy nSSn H9fU o8ln zP4G OuEq O1D4 LFaw FMkv z7Wr Qd2S eNfo cXl1 iS9P NPF5 TP9o a6ab Uvo2 ysQj
#define Cyiy gBEY ZSf2 yRoK E50s co7s Vxrp alWk KWUS prLi wXK2 MTzB VN75 mKDX yVRy eQHM o5KH Ry6W ZWO7 QD6C IVM6
#define zFMJ wxUb op0F MXzW rkwt hWDM PKe9 q5XT Kyng bF0z n5Ip BCut t5KT bDq8 wCXE v1r7 fWNG O1Nt NdxG J1Gs gzSZ
#define Dywg QY3w w1nC Dzv1 _4yo FwaW Jl9v eitB tLK4 _ZnN RSvv VFxw TfI0 OzS3 NAb5 wkp1 U9Fk XOq1 Vjqg EjZc R0ss
#define rCCH MT0y pwjq faBz MFAS CwhP tDtR mRRW FNac U4ln A1l0 p0CI W5y5 dCj5 ndSm eL0i AMUm R2hd bizU ePj5 CUzb
#define xHTR qiED b3KX SWkn uTkl OhJG WzmA liSG MTom dUGC OuMV QRxN BA97 vjiP pW4W tJAL b9ma D0fC Soea mBeo lzin
#define Ye9A P2pH KY7M JWc0 wu04 Nr3A ZjKF TKHE izd9 Bn93 BMEL LjNS Cks0 Kphx sQL1 Wd8e Rpq2 tOH8 k61C XFsD TyKV
#define c24y N74i NEU9 jtm5 JI3O udyX jVHo Mf7x LtFw Q2X4 JfkB Io0x rPu0 DgbL V0ve x8br Jc2K L1Mc iaYP TpBk fmOe
#define vlWl BaVP FII7 QFGF lQZ6 B6iB blcn c4nR cwYl z3JR YJDa zU7X vRWL yWJu hZtI qLAQ IzPi OcKZ EvAy pAbW dHTS
#define G5aG fLa1 hjZh EkPX ywUo R1LA k52c QvL0 rAmd PQfF rfFV rbbH lV1Y QCjp xKU6 UENt esf6 wwUy PQ9g xB6o sTCB
#define gEOI TQfq wMiH x5p0 yjOW pcUA u6JN M2CN K79l Qbds j1uL skp4 uevz DXwz ZAyd ttMP aylR hwuR sSuE FTYC uKLp
#define SRKM XQf9 dQYH j0ZC fh4e wf3k RzOK s9Oo gfsk DWsK RzXS mXJi b02u afPZ iIhs kTzF zQoZ KmgX Rf6S fD5y ktHn
#define oc2Q xGBY jaEo VqFT KO3H ht6A Nzb0 XHFT sVRE fHJ1 Mhf9 _sr3 xp4L xo2D unvz mqLC l8hQ zSFl D5Mw dUBI huJr
#define Mc03 tYtS X6l5 XLuQ NEz7 o2LT unmG tW31 eapr u7Bm ZC4o DUKD C80I _v9l pf6J ApkR lvx3 huW0 lxCD HsNH YXeL
#define c8RN IwlP CIgJ dmVp zlQj pfnl Uqlq C9JI Gqes MNT9 xkRE eFjl _Qoh mztK F7aE jrrE V8bC TqDw wQiL OniC B1XD
#define dMLn Rg2L YTH1 t2av JJQf pZrW PbEW IViY w9Cx IMSD FyA6 lQdJ Oazf KfwC IIg3 lhnU KkiH _SwI IOcF Vo0F Sh47
#define jmpl ObGP UuCf kPUf OTTo QfpS AduF NswW EgSI eihO gWih WHvM yB4v WHEY btjO oJCb nDs6 JtMs jWJd cvtm VZWo
#define xxiM wprO EXRP uIjU OGbC sOof hH9P vee3 PHgA ADtC wQHq Hhoq TP5r _yAR Ao6g FsqJ qPHh tdDo phi0 BvbR C7te
#define kUPh U9gR tL9D Zfqq tBT2 lfLD Dlfa AMWn OfqF RYRr WYSo qdUg BUZl bgNK xhbL dMKJ o2ua v7XC f5eM wh1V vsDl
#define UshK MIUk drUC J84n geR8 nEg7 uu36 M5aM PNOE JXid VsbL tmjv XmdP GUOO lknZ f1Ms P1BZ Qeop Vlgy dHtx EHQu
#define eYHP fyYB U517 PPIH HYJX JkN7 TjK1 RUx8 pNhk WAuZ jwSj NhTm Fzwz It8X SOGG r833 UZiH HH2z qdTf PzRZ wBiH
#define nG8c YVeD hmrI VWmm VdqZ AvcP gGYy hcrO aiMq NVpd YTjI fGB6 EaMz ZHYo ohAZ _vDn oYQ2 aCHt kogP yVsQ Iju0
#define bDi9 _0VM kAmR eZuI IZWt jjSP AuYM WEvJ qwFk gbbF Oerb KwJp DssS WMZj ZWhI dOlZ Azr0 lD4H o0MR dhCi oHWn
#define g0Z1 iHxm aY9j mezK g7i8 rFZK ZuEk HFvF lBiW sLxC fXcX UFjq F8EL vcNR AruU krp0 Gayn gdXW GeaV OuUP P0gu
#define n6dI Q1rS W91w M2d2 AZVf eiGY COK9 KK3T UKLq Lq4M rBgk uMG2 yBgn _u2X P2eq jjKE T7lV hUhm PeUG KqjX pR0x
#define xwCM n4fc hUUT RPqF YsLg j06q A5Kc lgEN IUCi lKDO bSSP oKwz rKOK Q4Vo qy1U fCWe fak7 yf9m JbbE YGdj SyKV
#define u8Xc WZ6F wiuX i778 RITc x6Oq Y5Hb Mpaz rfLC Ah0a jlZY eVcJ ZquT ldwh hUEl MGfW YJMv VLUu IBDn vggq gOl3
#define s9pZ sYjc Io5Y elPd bXFg WPko iaka FoZZ xCnJ pEKm kDHg qj78 tnPf IPu1 mmHk Rkx7 _0JV Iuah ym9a OIfp Y6ud
#define HMjZ lqvL dfg9 jJkF TCbs w9Jp vQFq p9n9 vkYq HHnE DeML N2a6 qSuz VLm5 u2qS qC7a VmuV JxdR Szxj HTO8 lPmu
#define WeKa WhkK q1lt DUiG asEZ iLpl Y4v9 _46s VgCD xWEP nw0D rdty Xg31 GhLf buHt Xne8 ys7h rDR1 L8bE jYQv g2uK
#define o2p7 Ru4t vAez Mbql P4YH wDdk Q1as NQN1 vtqS RY2G W5AC CiUQ d5SQ rAnB TL3b Jd4b FHRk rZEo KtyQ AeD5 hbUo
#define VGWs OjQY htTt TXcS Yox6 FflR rDKQ Pzwb lKHs UcQT ASGY G51v KfQC F8F1 IRen z0UI o42E KCMB zDMB RU7P awNM
#define saZQ LfRB xksZ AGYV ASTe EP3J tzqw bQZt T0O4 o0qN xPZD Tjux byMb CLaq tXOv BSok glIi WVgq AIon FCx6 Dj8z
#define HgCp sKbF ErNE I8c8 KZfi PpUe aetd E1bn I6Pi b3Ki GYfB pyrw tT34 HxNs SkRu jJIR cGDv nsdg lXWn H1tE AKvp
#define zu4m zxQZ A1DB S46Q ZKxm aXaY oTJV hXEJ GSJw LjTe yFW2 OInY lrcm nGWk Encz Gz9v W20P pYeN mUCs dxM9 FAJF
#define S8Tr kaqk r7LY Z8qV n3Vl LD2j EnDS uk5s VdYA nvmj jWtQ wKkG RC0v WpVF kQEd XPaC M95x RGSX lDBy YX0Y xFm8
#define x09u HFgf RMnp Pox7 U6Mi XsfG PPMf WoJF PWVS l1Hk OIZI MenB aozV XaIu T4Nq PTbK QGgB CLmP bzpk q6Bd hygq
#define UspB XaVl AEQS O3ho GV5r tTKA xnEL epII ZF9o kbTP b7jE l1Pm irFM UKTl q5lD xjkJ mjGB tkJG UToT c9Mz rIHc
#define l9eM aXkm NhYk yDNz TwyF MHZ0 NYYX Ngda Qyz5 qwoS qmcu IDcD IHKa vGfP s8g9 hzO3 SYXT CI8r heBo J1Jg hmgw
#define qjlg FaFY upJ3 fH7C C5yP mH50 unZC mtub kbA5 W9Jt l4Zo UnNi U0Im QHRM vmjL UIuY _fCn hLGI jTcf N60l fwv2
#define HjKK g5D7 sGxM e1JN wyrs Ndfw LmEi y5KN JdXl Qjuf Tp2M Z7OY _7eS KUPy XD59 k6UI ZicJ x5nE pEPk S76F qD13
#define Sckh gn5L nVV6 K0kE LZsf Dy5P FAcd qjK7 by1d dKqU L5hP DLxq dtLt H95H csn3 nLyU oNcx o6B6 SHXp xuEw B32b
#define IIcA LTwT Ba2m tKuV Jg8F azT7 FT70 eoRQ tCCh rKXz vpAT BE9f GFi7 jnBC qfWL nEDE rg3n Ttwk fJ22 Ajwn CXwD
#define oUXx usOX gQJl cQOQ lL7O T7cN GuWu doJu thij ZZdA FtGA mDOA SNr4 _cmM rLGg msrj rgNJ GZxL Nbym Rd9o Y4ND
#define Vk1k zz7b XH1E E9DH utMJ wBeD tvJl SmNF rNSN GrKX w4O9 lr0N Kfdq Z14Q QG4O nyG2 N9Ni G91M B5hJ Ocyw lEkW
#define kFaS J6d3 P2Q4 djVH lyy8 WpaR gl96 EUYS ONiA RGLB tp7F LUD4 IJkd KK8G s2SH U0fZ AuKh sUvy w2nz uXPE UZXK
#define JJ7D ule3 iWLU dSJr z3O6 W0MQ SvGu thfP cAIP Zv2H TzfM PEHA PgDa ctAP FHHu Ikr9 CV89 ZoeK Ynnu Ut0H LrgG
#define xYGB acMX oUS5 Jz8d PCGV F3Y3 hEfm InBq Gkt6 pl4K YH7n Gd89 FZft qMC9 oPEj JDAz KzqX MXXd n2Zz xAgV lo1D
#define skEq e8u4 pSdw bSQY AK5e M1Ll QS62 feF7 dAFH AQWk jfsP flo2 dwkt Tscq OAf4 wBhP OlTt AkTN njbF _HnA zPfN
#define V8aS ckom mL99
#define h7cL oDZh Pw0b j6Pc sCQl dd9Q uY3S jqua KVnE vVRq adXv jjX2 fmYG wBwJ DUlA DY45 gjY4 e4wd Dvw3 p9DD XoIQ
#define Lv94 yDAb FsSk nUqy IL0y piGu U6QA u7ez SaCA en6N JcHg lxh2 BHHA JtNX vac6 WmsJ vNSO IPvK UqVz kEPu QvgW
#define lD1Q eqPW lSpq gMNS Y2AM IoCL _Ufv UUk3 _4xq mU0o Rtl0 HRgy ITqJ aImg Q0Rv gtlS bbN4 xxxM txyH hPI2 JsAL
#define ReZE fzhN cCcY oWM6 n7IK SdMl mCKP FaJX Cyiy zFMJ Dywg rCCH xHTR Ye9A c24y vlWl G5aG gEOI SRKM oc2Q Mc03
#define kgFH c8RN dMLn jmpl xxiM kUPh UshK eYHP nG8c bDi9 g0Z1 n6dI xwCM u8Xc s9pZ HMjZ WeKa o2p7 VGWs saZQ HgCp
#define iEH8 zu4m S8Tr x09u UspB l9eM qjlg HjKK Sckh IIcA oUXx Vk1k kFaS JJ7D xYGB skEq V8aS
#define VQvR h7cL Lv94 lD1Q ReZE kgFH iEH8
#define VQvR h7cL Lv94 lD1Q ReZE kgFH iEH8
VQvR
