sequence27.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence28.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence29.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence30.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence31.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence32.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence33.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence34.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence35.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence36.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence37.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence38.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence39.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence40.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence41.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence42.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence43.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence44.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence45.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence46.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence47.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence48.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence49.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence50.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 35
  subtaskId: 6

sequence21.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

sequence22.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

sequence23.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

sequence24.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

sequence25.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

sequence26.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

sequence15.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 20
  subtaskId: 4

sequence16.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 20
  subtaskId: 4

sequence17.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 20
  subtaskId: 4

sequence18.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 20
  subtaskId: 4

sequence19.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 20
  subtaskId: 4

sequence20.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 20
  subtaskId: 4

sequence11.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 3

sequence12.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 3

sequence13.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 3

sequence14.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 3

sequence5.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

sequence6.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

sequence7.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

sequence8.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

sequence9.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

sequence10.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

sequence1.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

sequence2.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

sequence3.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

sequence4.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

