#Encrypted file follows
TDTJ`JPDUM`TUBSU`VOJU
`TDTJ`JPDUM`I
TDTJ`JPDUM`UFTU`VOJU`SFBEZ
TDTJ`JPDUM`TUPQ`VOJU
TDTJ`JPDUM`TZOD
TDTJ`JPDUM`TFOE`DPNNBOE
TDTJ`JPDUM`EPPSMPDL
TDTJ`JPDUM`CFODINBSL`DPNNBOE
TDTJ`JPDUM`EPPSVOMPDL
