#!/bin/bash
set -e
rm -r data/
mkdir -p data

for id in $(seq 1 25); do
    infile="data/friend${id}.in"
    outfile="data/friend${id}.out"

    echo "[Test $id] generating $infile"

    # 调用你的生成器：./gen [id]
    ./gen $id > "$infile"

    # 调用你的标程 ./std
    ./std < "$infile" > "$outfile"
    ./val $id < "$infile"
done

rm data.zip
cd data
zip ../data.zip *
cd ..

echo "All data generated."
