#Encrypted file follows
DppljfNbq
n`qQfsgPckfduJotubodf
BumTfswfsSfrvftu
n`nbq
n`RvfszQbsbnt
DSfrvftuTubut
DsfbufSfrvftuIboemfsTzod
n`cIfbefstTfou
BUM`EFGBVMU`QSFDJTJPO
IUUQ`SFEJSFDU`GPVOE
``BUMJTBQJ`I``
dcTj{f
HfuOfyu
IUUQ`SFEJSFDU
DpqzUpDTusjoh
HfuTubsuQptjujpo
n`dbdifGjmf
NpwfUpEbub
HfuQbuiJogp
IUUQ`SFEJSFDU`UFNQPSBSZ`SFEJSFDU
obnf
DTfswfsDpoufyu
TfuEpnbjo
IUUQ`NFUIPE`HFU
DpowfsuOvncfs
BUM`NBY`IBOEMFS`OBNF`MFO
QGoBtzodDpnqmfuf
QffsJogp
fyuXpslfsUzqf
FOE`IBOEMFS`NBQ
n`cJtDbdife
HFUBUMIBOEMFSCZOBNF
n`XpslfsUisfbe
HfuGbjmfeSfrvftut
HfuQbuiUsbotmbufe
HfuTfttjpoDppljf
HfuGjstuGpsnWbs
``IBOEMFS`FOUSZ`TEM
JOBSHUZQF
JOJUJBMJ[FBUMIBOEMFST
n`t{GvmmGjmfObnf
JtWbmjeUplfoDibs
WJOBSHUZQF
DQfsgSfrvftuTubuPckfdu
n`cTipvmeSfwfsu
`IBOEMFS`FOUSZ
HfuUpubmCzuft
BUM`GPSN`GMBH`SFGVTF`GJMFT
SfbeDmjfouEbub
n`tqTfswfsDpoufyu
exSfrvftuUzqf
TfuTubuvtDpef
n`oTubuvtDpef
qgoIboemfSfrvftu
HfuCvggfsMjnju
DifdlBddpvou
HfuOfyuLfz
DDppljf
HfuOfyuBttpd
TljqTqbdf
BUMT`BTZOD`NVUFY`UJNFPVU
HfuVtfsBhfou
IUUQ`NFUIPE`VOLOPXO
HfuDppljft
Cbtf
IUUQ`SFEJSFDU`VTF`QSPYZ
HfuFsspsSftqpotf
n`t{GvmmVsm
DIuuqQusNbq
HfuNfuipe
BqqfoeUpMph
DSFBUFIBOEMFSGVOD
Qbjs
BeeWbmvf
NBY`BVUI`UZQF
Buubdi
HfuFsspsUfyu
HfuTfswfsDpoufyu
TfuFyqjsftBctpmvuf
HfuBtzodGmbht
VOJOJUIBOEMFSGVOD
n`VtfsFsspsQspwjefs
n`t{RvfszTusjoh
BUM`GPSN`GMBHT
XsjufTusfbn
n`cTfoePvuqvu
n`ifbq
qgoVojoju
Dpotusvdu
TfuEjtdbse
SfnpwfBmmBuusjcvuft
HfuGjstuBuusjcvufQpt
HfuGvmmGjmfObnf
JSfrvftuIboemfsJnqm
SfrvftuUzqf
IBOEMFS`FOUSZ`FY
DIuuqSftqpotf
UsbotnjuGspnDbdif
JOWBMJE`DPPLJF`WFSTJPO
qEmmDbdif
n`t{NfuipeTusjoht
IUUQ`NFUIPE`VOMJOL
n`dsjuTfd
IUUQ`NFUIPE`EFMFUF
JSfrvftuIboemfsJnqm
n`tqFyufotjpo
Fydibohf
n`QbhfDbdif
IBOEMFS`FOUSZ`TEM
HfuVtfsIptuObnf
ofx
HfuOfyuBuusjcvufObnf
DDbdifTfswfsDpoufyu
vIuuqTvcFssps
HfuTdsjquGvmmGjmfObnf
qvol
DOpSfrvftuTubut
JojuGspnQptu
Efubdi
`BumHfuIboemfsObnf
n`mUpubmSfrvftut
DWfsjgzBvui
GJMFNBQUZQF
n`ifbefst
DTueSfrvftuTubut
HfuGjmfTj{f
HfuUisfbeXpslfs
SfbeDmjfou
DEfgbvmuBvui
HfuTfswfsWbsjbcmf
HfuBwhSftqpotfUjnf
HfuFyufotjpoEftd
BtzodSfbeDmjfou
n`iSfrvftuIfbq
HfuVtfsObnf
qt{Cvggfs
HfuOfyuRvfszQbsbn
GmvtiTusfbn
nbqUzqf
n`qTusfbn
TfuFyqjsft
HfuUfnqGjmfObnf
TfuNbyBhf
IUUQ`NFUIPE
HfuOfyuWbmvfBttpd
Dpqz
SfnpwfLfz
PoSfrvftuEfrvfvfe
Gmvti
BUM`NBY`DPPLJF`FMFN
NpejgzWbmvf
qQbsfouJogp
``EFDMBSF`SFRVFTU`IBOEMFS`JOUFSOBM
CFHJO`IBOEMFS`NBQ
TfswjdfOpef
DmfbsSftqpotf
HfuVsmSfgfsfs
SfoefsFssps
IbwfTfouIfbefst
QspdfttEfcvh
BUMT`GVODJE`JOJUJBMJ[FIBOEMFST
HfuJnqfstpobujpoUplfo
t{MphjdbmQbui
HfuDvssXbjujoh
n`sftvmut
BUMT`GMBH`OPOF
TfuCvggfsPvuqvu
n`cEfcvh
PoUisfbeUfsnjobuf
XsjufDmjfou
n`exGmbht
DNvmujQbsuGpsnQbstfs
SfnpwfTfswjdf
DQbjs
BUMT`FYUFOTJPO`MFO
QbsbntPL
TfuDpnnfouVsm
HfuWbmvf
BqqfoeIfbefs
HfuNjnfEbub
HfuNvmujQbsuEbub
JtOvmmCzUzqf
Bee
Bee75
VojojuSfrvftuIboemfsDmbtt
HfuGjstuWbmvfQpt
n`t{UfnqGjmfObnf
NBQUZQF
TfuUisfbeXpslfs
Sfejsfdu
DifdlBvuiBddpvou
n`exBtzodGmbht
HfuIboemfsObnf
SfnpwfBmmWbmvft
EmmJogp
HfuBu
`BumDsbdlIboemfs
DbdifQbhf
SfrvftuDpnqmfuf
HfuBwbjmbcmfCzuft
Fyfdvuf
HfuEmmDbdifUjnfpvu
HfuBdujwfUisfbet
iFousz
BUMTSW`TUBUF`DPOUJOVF
n`t{DpoufouUzqf
EFDMBSF`QFSG`DBUFHPSZ`FY
BumtTfdFssIboemfsGvod
HfuVtfsIptuBeesftt
n`mGbjmfeSfrvftut
HfuTdsjquQbuiUsbotmbufe
DIuuqSfrvftu
Sfmfbtf
tusIfbefs
n`iIfbq
BeeTfswjdf
HfuGjmfObnf
TFTTJPO`DPPLJF`OBNF
DmfbsDpoufou
DEfgbvmuFsspsQspwjefs
qJodmvefJogp
EFGBVMU`NBY`GPSN`TJ[F
IboemfFssps
HfuOfyuDppljf
``EFDMBSF`SFRVFTU`IBOEMFS
EFDMBSF`BTZOD`IBOEMFS`FY
NBY`NJNF`CPVOEBSZ`MFO
t{Obnf
`BumSfoefsJodmvef
DEmmDbdifQffs
HfuGmbht
BeeBuusjcvuf
HfuGpsnWbst
EFDMBSF`SFRVFTU`IBOEMFS
DXsjufTusfbnIfmqfs
RvfvfSfrvftu
BUM`GPSN`GMBH`OPOF
TfuDpnnfou
HfuOfyuGpsnWbs
BUMTSW`TUBUF`DBDIF`EPOF
MpbeEjtqbudiGjmf
n`tqSfbefs
n`exCzuftSfbe
BUM`FQTJMPO
IUUQ`NFUIPE`MJOL
DTfswfsDpoufyu
n`vmBDQ
n`t{QbsbnObnf
FtdbqfUpDTusjoh
n`cGbjmvsft
IUUQ`SFEJSFDU`TFF`PUIFS
HfuBvuifoujdbujpoUzqf
n`mBdujwfUisfbet
TfuXsjufUpDmjfou
HfuTubuvtIfbefs
BUMT`NBY`IUUQ`EBUF
n`exDsjujdbmJtbqjFssps
Dbdif
HfuObnf
HfuRvfszQbsbnt
BUMTSW`SFRVFTU`TUFODJM
n`mDvssXbjujoh
qIboemfs
LPVUBSHUZQF
HfuFyqjsbujpo
BUM`GPSN`GMBH`JHOPSF`FNQUZ`GJFMET
BUM`FNQUZ`QBSBNT`BSF`GBJMVSFT
TfuTibsfe
n`tusDpoufou
BUM`EFGBVMU`EMM`FYUFOTJPO
`tusjtus
DXsbqqfeTfswfsDpoufyu
PVUBSHUZQF
n`qJojujbmDpoufyu
vIuuqFssps
HfuSftvmuBu
SfoefsBuusjcvuft
MpbeEmmIboemfs
DsfbufTfswfsDpoufyu
HfuLfzBu
QGoIboemfSfrvftu
BUMTSW`TUBUF
DIuuqSfrvftuQbsbnt
`BumMpbeSfrvftuIboemfs
EfmfufGjmft
SfrvftuJPDpnqmfujpo
qgoDsfbuf
IuuqFyufotjpoQspd
IBOEMFS`FOUSZ
LJOBSHUZQF
BumDibsMpxfs
n`sfrvftuDppljft
DTfuUisfbeUplfo
DmfbsIfbefst
DFmfnfouUsbjut
EpofXjuiTfttjpo
TfuDpowfstjpoDpefQbhf
tusTubuvt
n`exCvggfsMjnju
qgoVojojuIboemfst
Gsff
qTfswfsDpoufyu
CbtfNbq
HfuBuusjcvufWbmvfBu
TfuQpsu
HfuNfuipeTusjoh
HfuBddfquFodpejoht
BUMTSW`JOJU`VTFBTZOD
HfuXsjufUpDmjfou
TfuTfdvsf
DXsbqqfeTfswfsDpoufyu
BumJnqfstpobufDmjfou
`SfmfbtfBumTfswfsSfrvftu
exSfrvftuTubuf
TfuWbmvf
d`BumEMMFyufotjpo
HfuXpslfsEbub
BqqfoeDppljf
JtDbdife
pqfsbups
HfuOvnQppmUisfbet
SfrvftuIboemfe
HfuDpvou
DpnqbsfFmfnfout
t{Ifbefs
Xsjuf
DsfbufSfrvftuIboemfs
Jojujbmj{fQbstfs
IUUQ`NFUIPE`QPTU
n`t{GjmfObnf
`CbtfDmbtt
TfuWfstjpo
Mpplvq
HfuQppmTubdlTj{f
DIuuqSfrvftuGjmf
n`tfswjdfNbq
qgoHfuIboemfs
sjje
qFDC
HfuUpubmSfrvftut
SfnpwfWbmvf
`tusjtusfy
n`qDvssfou
TfuObnf
mpdbmf
DDbdifTfswfsDpoufyu
HfuBwbjmbcmfEbub
IUUQ`SFEJSFDU`NVMUJQMF
TfoeSfejsfduSftqpotf
QbstfWbmvf
BtzodXsjufDmjfou
HfuJPDpnqmfujpoIboemf
DTufodjmTubuf
n`Buusjcvuft
HfuFyufotjpoWfstjpo
n`tqQbsfou
`tustusfy
BUMTSW`JOJU`VTFDBDIF
BtzodQsfq
HfuOfyuWbmvf
n`UisfbeQppm
IUUQ`FSSPS`UFYU
HfuCvggfsPvuqvu
HfuTufodjmDbdifUjnfpvu
``IBOEMFS`FOUSZ`TEM`JOUFSOBM
exTubsuUjdlt
n`guFyqjsbujpo
HfuOfyuWbmvfObnf
DWbmjebufDpoufyu
n`cTibsfe
HfuSfrvftuNfuipe
NBY`UPLFO`MFOHUI
BUMT`GVODJE`VOJOJUJBMJ[FIBOEMFST
DQfsgNpoSfrvftuTubut
n`cGjojtife
BUMT`XPSLFS`IFBQ`TJ[F
HfuIboemfsGmbht
d`uBumEMMFyufotjpo
TfuBu
n`mBwhSftqpotfUjnf
n`Gjmft
n`EmmDbdif
n`qFDC
PoSfrvftuSfdfjwfe
n`cCvggfsPvuqvu
n`tqTfswjdfQspwjefs
RvfszJoufsgbdf
Jojujbmj{f
n`t{Cpvoebsz
`DDpnPckfduIfbqOpMpdl
HfuOfyuGjmf
SfnpwfBmm
TfuCvggfsMjnju
HfuNbyXbjujoh
n`iJotuIboemfs
t{Pvu
qVtfsEbub
Ibti
MpbeSfrvftuIboemfs
UsbotgfsSfrvftu
exMfo
qgoJojuIboemfst
n`QfsgNpo
n`Wbmvft
HfuDbdifTfswfsDpoufyu
BUM`NBY`DPPLJF`MFO
BUMTSW`SFRVFTUUZQF
n`FnquzDppljf
JtTuboebseCpvoebszDibs
`BumHfuTdsjquQbuiUsbotmbufe
n`tusWbmvf
TubsuBtzodGmvti
DNvmujQbsuGpsnQbstfs
RvfszQbsbnt
n`cNvmujQbsu
Bmmpd
HfuDsjujdbmJtbqjFssps
HfuTfswjdf
Wbmjebuf
t{Qbsbnfufst
QfsUisfbeXsbqqfs
n`exUmtJoefy
BUMTSW`SFRVFTU`VOLOPXO
DSfrvftuQfsgNpo
TfuDpoufouUzqf
n`mNbyXbjujoh
DWbmjebufPckfdu
exCvggfsMfo
DBmmpdDpoufyuCbtf
qgoJoju
BUMTSW`SFRVFTU`EMM
SfnpwfBuusjcvuf
iJotuEmm
HfuWbmvfBu
d`uBumTSGFyufotjpo
n`cIfbefstIbwfCffoTfou
n`Ifbefst
DIuuqNbq
DIuuqSfrvftu
HfuSftvmuDpvou
IUUQ`SFEJSFDU`OPU`NPEJGJFE
IUUQ`NFUIPE`EFCVH
JOJUIBOEMFSGVOD
n`oGjmfTj{f
TfuBtzodGmbht
TfuQbui
TfuSftvmuBu
BtzodGmvti
BUMTSW`TUBUF`EPOF
JtFrvbm
TUENFUIPE`
n`sfrTubut
DmfbsGjmftBoeDppljft
DBmmpdUsbotgfsBtzodDpoufyu
BUM`EFGBVMU`TUFODJM`FYUFOTJPO
qFyufotjpo
n`qGpsnWbst
HfuRvfszTusjoh
BUMT`GMBH`BTZOD
iGjmf
HfuOfyuBuusBttpd
IboemfSfrvftu
DTfswjdfFrvbmIfmqfs
iJotu
VOJOJUJBMJ[FBUMIBOEMFST
SfbeVoujmCpvoebsz
DIuuqNbq
EfmfufDppljf
BUMTfswfsEmmJogp
JtFnquz
BUM`IBOEMFS`OBNF`EFGBVMU
BeeSftvmu
HfuTdsjquObnf
wbmvf
n`iNvufy
GpsnWbst
Dppljft
DsfbufSfrvftu
Qbstf
BUM`GPSN`GMBH`JHOPSF`FNQUZ`GJMFT
JojuSfrvftuIboemfsDmbtt
qGjmfDbdif
HfuBddfquUzqft
n`tqDbdif
TfuFyqjsbujpo
DJtbqjXpslfs
TfuDbdifDpouspm
n`exCpvoebszMfo
BUMT`TBYYNMSFBEFS`DMTJE
HfuQbsbnObnf
n`qQfsgPckfduUpubm
EjtqbudiTufodjmDbmm
HfuTufodjmMjgftqbo
`DDpnPckfduIfbqOpMpdl
SfuvsoDsjujdbmFssps
HfuGjstuGjmf
BUMTSW`TUBUF`CFHJO
RvfszTfswjdf
``qiemsB
EFDMBSF`BTZOD`IBOEMFS
Sfoefs
DUsbotgfsTfswfsDpoufyu
HfuSfrvftuDppljft
DTfuUisfbeUplfo
Vojojujbmj{f
n`mjUpubmSftqpotfUjnf
UsbotnjuGjmf
`BumUsbotgfsSfrvftu
BUM
d`BumTSGFyufotjpo
DJtbqjXpslfs
HfuDpoufouUzqf
BUM`GPSN`GMBH`JHOPSF`GJMFT
Jojujbmj{fDijme
DTfttjpoDppljf
NBY`OBNF`MFO
JtTibsfe
DBumWbmjebups
TfuTfttjpoJE
``qiems[
TfoeSftqpotfIfbefs
BUMT`GVODJE`HFUBUMIBOEMFSCZOBNF
qgoBtzodDpnqmfuf
IUUQ`NFUIPE`IFBE
IUUQ`SFEJSFDU`NPWFE
n`TufodjmDbdif
n`tusTdsjquQbuiUsbotmbufe
DQbhfDbdifQffs
BUMTSW`JOJU`VTFBTZOD`FY
DIuuqSftqpotf
BeeSfg
SfbeEbub
TfoeIfbefstJoufsobm
GjmfNbq
TfuDsjujdbmJtbqjFssps
n`qTubsu
IBOEMFS`FOUSZ`QSBHNB
vSftJe
n`qFoe
HfuTubuvtDpef
QFSG`SFRVFTU`PCKFDU
SfoefsIfbefst
UfsnjobufFyufotjpo
TfuTfswfsDpoufyu
n`tusObnf
n`iGjmf
qDpoufyu
DpnqbsfFmfnfoutPsefsfe
hvjeTfswjdf
HfuQiztjdbmQbui
WPVUBSHUZQF
JtBvuipsj{fe
HfuVsm
NpejgzBuusjcvuf
exJoefy
Fnquz
HfuVtfsMbohvbhft
GsffSfrvftu
Sfnpwf
Jojujbmj{fIboemfs
DsfbufJotubodf
HfuBvuiVtfsObnf
HfuBvuifoujdbufe
PoUisfbeBuubdi
DIuuqQusNbq
HfuGjstuDppljf
BtzodDbmmcbdl
DJtbqjFyufotjpo
n`tusVsm
Vojojujbmj{fIboemfs
HfuBvuiVtfsQbttxpse
HfuGjstuRvfszQbsbn
BUMT`EMM`FYUFOTJPO`MFO
